### ISSUE TITLE
Describe building process in README

### ISSUE THREAD

**Issue by imv** [MrKepzie/Natron#1001]
Open source projects usually provide building instructions, even if they are trivial to build, i.e. one simply has to run make or cmake or ./configure.sh && make.
Natron is not trivial to build, simply running qmake produces weird errors. One has to copy & edit config.pri, one has to select a config option, and so on.
Right now I'm lost. I could ask on forum, but I think this should be documented somewhere.

**Comment by olear** [comment]
We have README's for each platform, could be better, but they provide the basics.

What OS/Distro are you building on?

**Comment by imv** [comment]
Arch Linux.
Still, the build instruction for linux first describes how to set up a build server than how to do an actual build.

Is it possible to build Natron without build server?

When I run MKJOBS=8 NATRON_LICENSE=GPL sh snapshot.sh, I first have to remove the "Wrong distro, stupid :P" condition from common.sh. It's almost like the build system is user-hostile on purpose.

Then the build script clones Natron. Why does it do it? We already have ths source code, we're in the work tree, since we have the bukld scripts. Why not just build the current revision?

Then it fails with

    snapshot.sh: line 111: /path/to/Natron/tools/linux/.autobuild/commits-hash.sh: No such file or directory

When invoked as described in README.md, build.sh tries to access remote server by ssh. Yes, I can add localhost into repo.sh, but still, it asks password, so it's hard to automate it.

And so on. I.e. you have to perform a lot more actions than described in README.md, and you have to read the build scripts to figure them out.

**Comment by olear** [comment]
https://github.com/MrKepzie/Natron/blob/workshop/tools/linux/include/misc/build-natron-on-archlinux.sh, outdated, but you should be able to understand what's needed.

https://raw.githubusercontent.com/MrKepzie/Natron/workshop/tools/linux/include/natron/config_py3.pri example, remove anything with /opt.

And remove this line from global.pri https://github.com/MrKepzie/Natron/blob/workshop/global.pri#L245

**Comment by imv** [comment]
Thanks. Still, the point stands.

**Comment by olear** [comment]
Sure, will update the docs when I get the time.

**Comment by azerupi** [comment]
I am on Arch Linux and I installed all dependencies through pacman except cairo that I had to build from source

```
sudo pacman -S qt4 boost expat glew python2-pyside python2-shiboken
```

For cairo

```
git clone git://anongit.freedesktop.org/git/cairo
cd cairo
./autogen.sh
make
sudo make install
```

It is installed in `/usr/local/lib`

Finally, this is the **config.pri** that I used:

https://gist.github.com/azerupi/080a415a844a303be331

@olear, I can make a pull request with more details for Arch Linux :)

**Comment by devernay** [comment]
There is no need for a build server... There used to be Linux instructions that just gave the list of packages to install and the sequence of instructions. Don't use the build scripts in tools/Linux. Either take a look at previous versions of the Linux install instructions, or take a look at the osx build instructions, which are not very different. I'll rewrite the Linux build instructions.

Le 3 novembre 2015 05:38:39 GMT+01:00, Michael Ivko <notifications@github.com> a écrit :
>Arch Linux.
>Still, the build instruction for linux first describes how to set up a
>build server than how to do an actual build.
>
>Is it possible to build Natron without build server?
>
>When I run MKJOBS=8 NATRON_LICENSE=GPL sh snapshot.sh, I first have to
>remove the "Wrong distro, stupid :P" condition from common.sh. It's
>almost like the build system is user-hostile on purpose.
>
>Then the build script clones Natron. Why does it do it? We already have
>ths source code, we're in the work tree, since we have the bukld
>scripts. Why not just build the current revision?
>
>Then it fails with
>
>snapshot.sh: line 111:
>/path/to/Natron/tools/linux/.autobuild/commits-hash.sh: No such file or
>directory
>
>When invoked as described in README.md, build.sh tries to access remote
>server by ssh. Yes, I can add localhost into repo.sh, but still, it
>asks password, so it's hard to automate it.
>
>And so on. I.e. you have to perform a lot more actions than described
>in README.md, and you have to read the build scripts to figure them
>out.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/MrKepzie/Natron/issues/1001#issuecomment-153236676

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by devernay** [comment]
I'm adding an "Installing" section in README.md which redirects to either a binary distribution or the INSTALL_*.md files

**Comment by devernay** [comment]
@imv Do the instructions in https://github.com/MrKepzie/Natron/commit/c4229467ee5f7157ab01d973a4907bd758239ee8 seem ok for you?
@azerupi please send me detailed arch linux build instructions, or do a pull request - as you wish

**Comment by imv** [comment]
@devernay the link in c422946 is invalid. Otherwise it works, yes. Thanks.
