### ISSUE TITLE
Motion blur options in Roto ?

### ISSUE THREAD

**Issue by mathiastesar** [MrKepzie/Natron#1008]
Hi , i was wondering if there are motion blur/shutter options in the Roto node.
Thanks team !

**Comment by azerupi** [comment]
Questions are better asked on the [forum](https://forum.natron.fr/) where more users will be able to answer it. Try to keep posts on the issue tracker to only issues and feature requests so as to not overwhelm the developers with notifications. Thanks! :)

**Comment by MrKepzie** [comment]
We could expose the motion blur parameters of the Transform in the Transform tab if it's what you mean ?

**Comment by mathiastesar** [comment]
yep, that would be great ! :^) Thks ! 
can't wait to make some tests on the RC3 by the way

**Comment by sozap** [comment]
I think in Nuke motion blur on roto is also done on shape changing , not only on transforms...
But having it in transform is a good step forward !

**Comment by devernay** [comment]
is it just a matter of exposing the MB parameters? If yes, why not do it now?
https://www.facebook.com/groups/NatronNation/permalink/623979534436285/

**Comment by devernay** [comment]
@sozap the motion blur in the transform node gets the image (i.e. the roto shape) at each fractional time, so it should blur the changing shape too. I'm not sure, though. Please test by putting a transform after an animated roto shape. If it doesn't work, it needs to be fixed.

**Comment by sozap** [comment]
Hum, If I understand you correctly that's not working...
![roto_blur](https://cloud.githubusercontent.com/assets/9614046/16366068/47d77c2a-3c11-11e6-8a13-1be26f12f810.jpg)
The viewer 2 show the previous frame , both viewers should be blurred...

I found at first a bit weird that the Transform gets the fractional time of his input, but after thinking that make sense in some cases, but shouldn't that slow down rendertime (depending on the input) ? then maybe having it as an option...

**Comment by MrKepzie** [comment]
Motion-Blur is implemented in 2.2 for Bezier and strokes on the GPU
