### ISSUE TITLE
RC3: node ROTO report 1

### ISSUE THREAD

**Issue by manuelsongokuh** [MrKepzie/Natron#1009]
new for RC3: "pivot 2d" (i dont know what is name..) THIS NEW IS TRUE NEEDED! :+1: 

propreties:"Roto1"
tab: trasform, there are 2:
a)-center:
this is a pivot 2d, and it's relative from Bezier2 ('rectangle box'). when i change bezier2 (move 1 point to other space) will changed of pivot 2d, this is RELATIVE.this is ok.

b)-translate:
this is relative from pivot 2d. this is ok.

c)there is other translate: 'rectangle box' of bezier2, this is not show x/y in propretries.
this is ok but there are confusing: example
when i click(2 clicked) line of bezier2 there is: showed 'rectangle box' (box is around of bezier2). this is other translate..uhmm..

1) solution for a):
change word "center:" to 
"center of pivot 2d:" or 
"pivot of translate position:" or
"position of pivot 2d:" or
"position the anchor of pivot 2d"...
why i did say to change word "center:"? because "center:" is confusign and not clarify, 
seem "center:" is the center of translate or layer.. also "center:" is not true center..because i change change top-right of project this is not center name..this is example.
so needs new name PIVOT or PIVOT 2d..this is good clarify, it's right?

2)solution for c):
NEW 1 BUTTON in propreties of Roto1: 'active' or 'inactive' for to show 'rectangle box' of bezier2.
rectangle is good because can modify :scala, trasform, inside of all points, curve, bezier, this is not delete but keeps on, but change Gui clean and care it ok?

what do you think about this solutions?

**Comment by MrKepzie** [comment]
The parameters are named after the ones in the Transform node for consistency. "Center" relates to the center of the affine transformation. 

Anyway there are 2 kinds of transformations:

- The bounding box in the Viewer (the rectangle),  which allows to transform the selected points, but does not actually change the transform parameters. 

- The Transform parameters which hold an optional transform which can be applied to the shape.
