### ISSUE TITLE
QComboBox resizes the window 

### ISSUE THREAD

**Issue by cg-cnu** [MrKepzie/Natron#1013]
Clicking on QComboBox twice and moving the cursor causes the window to resize. Uploaded a video [here](https://youtu.be/Wi513SyRi7o)

**Comment by manuelsongokuh** [comment]
YES! i have same this issue!! me tooo!!
opensuse 13.2 kde4 last version.
i did try other solution but nothing resolve..maybe natron will be fix.. i dont know..

**Comment by olear** [comment]
Looks like a window manager issue.

Running KDE here as well, but unable to replicate

**Comment by manuelsongokuh** [comment]
@olear see my screen record kde4
http://sendvid.com/xk9yk7we

**Comment by olear** [comment]
Change '-style fusion' with '-style plastique' in 'Natron' (the exe wrapper).

**Comment by manuelsongokuh** [comment]
@olear : same problem with "-style plastique" in natron..

**Comment by olear** [comment]
Odd, I was running using 'plastique' and was unable to reproduce the error, but when I changed to the default 'fusion', I was able to replicate.

**Comment by manuelsongokuh** [comment]
update: worked, i'm bad word for now is worked with -style plastique

# start app, with optional debug
if [ "$1" = "-debug" -a -x "$DIR/bin/Natron.debug" ]; then
    SEGFAULT_SIGNALS="all"
    export SEGFAULT_SIGNALS
    catchsegv "$DIR/bin/Natron.debug" -style plastique "$@"
else
    "$DIR/bin/Natron" -style plastique "$@"
fi

**Comment by olear** [comment]
Great, will update the script (or maybe it should be forced by app?)

**Comment by manuelsongokuh** [comment]
yes but i'm not decide.. see resolve for @cg-cnu ...?

but i'm curious what is different: fusion and plastique?
there are other style?

**Comment by olear** [comment]
Qt has different styles/themes, Fusion is not an valid style in Qt4, that's probably the reason for the problem.

Qt has several styles, check qtconfig,

**Comment by manuelsongokuh** [comment]
WOW! you can explain to @cg-cnu or you will fix natron for linux, this is be good solution.
good night! you go to bed!

**Comment by manuelsongokuh** [comment]
fusion not worked
plastique worked
cleanlooks, worked
oxygen not worked

**Comment by olear** [comment]
That's because Qt included with Natron only supports the default themes (plastique, cleanlooks etc). Fusion/Oxygen will not work.

**Comment by cg-cnu** [comment]
@olear @manuelsongokuh 
Thanks -style plastique fixed the issue.

**Comment by manuelsongokuh** [comment]
@olear hello i did find this information helpful :
http://blog.qt.io/blog/2012/10/30/cleaning-up-styles-in-qt5-and-adding-fusion/
fusion for QT5 is BEAUTIFUL!! maybe in the future?opinion..?

**Comment by olear** [comment]
Fusion is also available in Qt4 through third-party, have tested it, but you also need a "Natron theme" to take advantage of it. 

Something to consider when we move to Qt5.

**Comment by manuelsongokuh** [comment]
of course, will wait for move to qt5, thank you!

**Comment by manuelsongokuh** [comment]
any news about fusion qt5?
because i find good theme from shotcut so i show you great different UI theme:
shotcut vs natron theme qt

shotcut maybe used qt5 with fusion (is beautiful UI careful)
![natron-vs-shotcut-theme-qt](https://cloud.githubusercontent.com/assets/12126929/20606999/2f190d5e-b275-11e6-8b0e-029b2ff8d7c0.png)

but i dont know if natron did moved to qt5..?

**Comment by olear** [comment]
Fusion is also available for Qt4, but Natron has always used a custom theme that overrides the engine and will probably continue that way. There will be some small changes in v2.2 regarding looks, but there will probably not be any major changes until after that.

**Comment by manuelsongokuh** [comment]
oh.. okay, for future.
but what is available theme for natron (moment)? plastique, other style?

**Comment by olear** [comment]
Plastique is forced on Linux in the application, on the other platforms the default is selected, but as I said the engine don't matter as we override everything with the Natron theme (and in the code).

**Comment by manuelsongokuh** [comment]
maybe is strange, so i need teel you:
i click from preferences>appearance, i click restore defaults, close natron and re open natron font size is 11 this is defualt?
if default font size is 11 then font size 11 is too (ugly font UI)
i test change from font size 11 to 10 is beautiful..but i do testing but you can try , maybe is bug or error for defualt ok?

**Comment by manuelsongokuh** [comment]
ok for natron theme , understand thank you.

but do you find strange font bold and size? or that is fine..i dont know..

**Comment by olear** [comment]
Font size 10 is default on Windows/Linux in v2.2.

**Comment by manuelsongokuh** [comment]
go to see
http://sendvid.com/dqrmzcsu

version develop 2.1.9

**Comment by manuelsongokuh** [comment]
other important : color UI select in menu: orange but font color is grey is not GOOD..need change for GOOD UI color..

see example here bad color:
![natron-ui colore orange](https://cloud.githubusercontent.com/assets/12126929/20607501/41d161e0-b279-11e6-9774-0473258d7be3.png)

**Comment by olear** [comment]
This has also been fixed in v2.2.

**Comment by manuelsongokuh** [comment]
ok, where i will donwload snapshot 2.2?

**Comment by olear** [comment]
Not available yet, you can either build it from source or wait.
