### ISSUE TITLE
file browser ui enhancements

### ISSUE THREAD

**Issue by cg-cnu** [MrKepzie/Natron#1014]
Requesting some small but time saving enhancements to the existing file browser ui.

* Connect the 'Enter' signal from the QLineEdit  to the open button.
* Change the Shift tab ordering from QLineEdit to QTableWidget which lists the files and folders instead of the bookmarks widgets.

**Comment by devernay** [comment]
thanks.
that kind of request is always wellcom: small changes that improve the user experience!

**Comment by olear** [comment]
Got some "paper cuts" ...

* I got a sequence named seq_XXXXXX.exr_1080.png, Natron does not detect this as a sequence, only individual images (works in Shake, Nuke has same issue as Natron)
* Try view a folder while images are copied/created in that folder, the file-browser will rescan the folder in a endless loop

**Comment by cg-cnu** [comment]
@devernay Glad its helpful! Afraid I might sound picky ;)
some more tiny issue. Just adding to the list. 
* In case of sequences, **Type** is showing as tif (  5090-5720 / 5731-5743 / 5749 / 5751-5757 / 5759 )
* Once you select the sequence the QLineEdit is updated with /path/to/fileset/sequence_####.tif (  5090-5720 / 5731-5743 / 5749 / 5751-5757 / 5759 ). We should be having just /path/to/fileset/sequence_####.tif
