### ISSUE TITLE
NatronRenderer Render individual frames and by frame

### ISSUE THREAD

**Issue by cg-cnu** [MrKepzie/Natron#1016]
Right now NatronRenderer only takes frame ranges.

Is it possible to render individual frames separated by comma.
e.g, NatronRenderer -w  Write1 1952,1958,1960 /path/to/natron/file.ntp
e.g, NatronRenderer -o /path/to/override/folder/test.####.jpg 1952,1958,1960 /path/to/natron/file.ntp

As already mentioned here #973, an option to render by frame in case of mentioning frame ranges.
e.g, NatronRenderer -w Write1 1950-1960:4 /path/to/natron/file.ntp

so, we should be having the functionality like this.
e.g, NatronRenderer -w Write1 1945,1949,1950-1960:4,1965 /path/to/natron/file.ntp

**Comment by MrKepzie** [comment]
Implemented
