### ISSUE TITLE
Centos dependencies link broken

### ISSUE THREAD

**Issue by cg-cnu** [MrKepzie/Natron#1017]
Trying to compile on centos 7 
> https://github.com/MrKepzie/Natron/blob/workshop/INSTALL_LINUX.md#centos6-64-bit
> wget http://downloads.natron.fr/Third_Party_Binaries/Natron-CY2015-Linux-x86_64-SDK.tar.xz

Dependencies link broken 
> wget http://downloads.natron.fr/Third_Party_Binaries/Natron-CY2015-Linux-x86_64-SDK.tar.xz
--2015-11-12 16:29:17--  http://downloads.natron.fr/Third_Party_Binaries/Natron-CY2015-Linux-x86_64-SDK.tar.xz
Resolving downloads.natron.fr (downloads.natron.fr)... 176.31.174.181
Connecting to downloads.natron.fr (downloads.natron.fr)|176.31.174.181|:80... connected.
HTTP request sent, awaiting response... 404 Not Found

**Comment by olear** [comment]
* http://downloads.natron.fr/Third_Party_Binaries/Natron-2.0.0-RC3-CY2015-Linux-x86_64-SDK.tar.xz
* http://downloads.natron.fr/Third_Party_Binaries/Natron-2.0.0-RC3-CY2015-Linux-x86_64-SDK-update-01.tar.xz

Note these are for v6, should work on v7

**Comment by cg-cnu** [comment]
@olear 
Thanks for the link.
