### ISSUE TITLE
Natron Crashes: Smooth node before Edge node adjustments

### ISSUE THREAD

**Issue by blackearth2014** [MrKepzie/Natron#1018]
The Smooth filter node works fine after the Edge node, but before the Edge node is instantly quits while adjusting parameters.

Error report below

https://gist.github.com/blackearth2014/9a742cb5f18beca28750

![smooth node - edge node](https://cloud.githubusercontent.com/assets/7956901/11116934/e1d67810-8903-11e5-8dd8-c259a0b25ac3.png)

**Comment by olear** [comment]
Unable to replicate on Linux.

**Comment by blackearth2014** [comment]
I have just downloaded the latest  snapshot. I will see if it still crashes when I make adjustments to the smooth node before the edge node.

**Comment by olear** [comment]
Tested latest snapsshot on OSX, works for me ...

**Comment by olear** [comment]
Still an issue?

**Comment by blackearth2014** [comment]
No
