### ISSUE TITLE
Sapphire LensFlare

### ISSUE THREAD

**Issue by olear** [MrKepzie/Natron#1020]
Add a node from MonstersGT and press the help button, an external window will open and Natron on Linux will crash: /home/olear/bin/Natron: line 87: 11711 Floating point exception(core dumped), does not crash on OSX.

Add lensflare from Sapphire and press presets or edit (something that triggers their preset browser or editor), this will open an error dialog: 

Sapphire Error:
doDialog: unknown action 20188592

pressing help will also trigger this, Natron on Linux will then crash, same error on OSX but no crash.

Both bundles worked in Natron pre v2. I also noted that Lensflare has no output in RC2/RC3, but does have output in RC1.

**Comment by devernay** [comment]
this is because sapphire implements a buggy dialog suite (see discussion on ofxa-members list).
I know about the osx message, but didn't know it crashed linux.
We should maybe disable the dialog suite, at least in releases?

**Comment by olear** [comment]
Ok. ofxa-members is a closed group, so didn't know that.

I don't know what the best solutions would be, not having access to dialogs/presets in Sapphire is kind of a show-stopper. But we should at least avoid a crash in Natron.

**Comment by MrKepzie** [comment]
I have disabled the dialog suite v1

**Comment by MrKepzie** [comment]
confirm that crashes are gone on linux and close

**Comment by olear** [comment]
Dialogs now work. Note that S_LensFlare is still broken, no image (last worked in RC1) other plugins seems to work.

**Comment by olear** [comment]
The help button on any plugin from Sapphire will crash Natron on Linux.

And Lensflare is still not usable (no lensflare ;) ), RC1 was the last working version.

**Comment by olear** [comment]
https://github.com/MrKepzie/Natron/commit/8f94127739f54b1220aa92cc4b04d8d5aef2e4b4 breaks S_LensFlare.

**Comment by olear** [comment]
Default scale width in Nuke is 403.2, setting that in Natron gives more or less the same image.
