### ISSUE TITLE
crash while copy/paste a node

### ISSUE THREAD

**Issue by mathiastesar** [MrKepzie/Natron#1021]
Hi team, 
i have a crash occuring in a comp when i try to copy/paste an already connected read node in the nodegraph. 
I have the following message in a popup panel:
Error while creating node fr.inria.openfx.ReadOIIO: Invalid plugin label:

thks ;^)

**Comment by MrKepzie** [comment]
Can you give me the steps to reproduce the crash ?

**Comment by mathiastesar** [comment]
Looks like some memory problem, in a small document i have no troubles copy pasting nodes. I have like 150 - 200 nodes in my comp, the nodegraph becomes quite laggy (known issue) and when i try to copy paste a connected node a crash with this message always occurs.  Unfortunately i have no more infos showing up in debug mode.

**Comment by olear** [comment]
Could you make the project file (ntp) available for testing?

**Comment by MrKepzie** [comment]
Can you confirm that it happens with PyPlug only ?
If not can you give me the script-name and label of the nodes you are trying to copy

**Comment by MrKepzie** [comment]
I fixed it in a recent commit. Please check back in RC4 if the problem still persists.

**Comment by mathiastesar** [comment]
Top, T as une idee de quand serait dispo la RC4 ?
thks

2015-11-16 5:01 GMT-05:00 Alexandre Gauthier <notifications@github.com>:

**Comment by olear** [comment]
Still an issue?

**Comment by mathiastesar** [comment]
fixed on the RC5 ;^)

2015-12-09 11:13 GMT-05:00 Ole-André Rodlie <notifications@github.com>:
