### ISSUE TITLE
Ubuntu 15.04 to 15.10 OIIO/OpenEXR issue

### ISSUE THREAD

**Issue by adallafontana** [MrKepzie/Natron#1022]
I have try to install Natron2 on two laptops with 15.10
but on Read menu I found only psd and svg option and in Write nothing.

**Comment by MrKepzie** [comment]
Can you launch from the terminal and copy/paste the output

**Comment by adallafontana** [comment]
~/Natron2$ ./Natron -debug
Natron Version 2.0.0
Copyright (C) 2015 the Natron developers
>>>Use the --help or -h option to print usage.<<<
init.py script not loaded
initGui.py script not loaded

I tried to delete all old installations, preference and cache folder from HD and reinstall Natron2 stable version and also shapshot, but I have same result.

**Comment by olear** [comment]
Something must be different on your setup, 15.10 works just fine with Natron.

- 15.10 clean install?
- Have you used Natron before on that installation?
- What's in /usr/OFX/Plugins?
- Where's Natron installed, and what's in the Plugins folder?
- Check depends on IO.ofx (ldd path/to/Natron/Plugins/IO.ofx/Contents/Linux-x86-64/IO.ofx)
- Remove Natron settings/config/cache (rm -rf ~/.cache/INRIA ~/.config/INRIA ~/.local/share/INRIA)

**Comment by adallafontana** [comment]
[quote] Something must be different on your setup, 15.10 works just fine with Natron.[/quote]
Natron works, only the IO doesn't.
[quote] 15.10 clean install? [/quote]
...will be this one, but now for me it's complicate and boring reinstall all others app (..that working well) only for Natron. 
thank you Olear

**Comment by olear** [comment]
Didn't mean you should reinstall, I wondered if it was a clean install.

**Comment by adallafontana** [comment]
No, isn't clean install, is an update fron 15.04

**Comment by olear** [comment]
Ok, can you also provide a output of
ldd /path/to/Natron2/Plugins/IO.ofx/Contents/Linux-x86-64/IO.ofx

**Comment by adallafontana** [comment]
Sorry what do you mean for "output", the file IO.ofx exist in the right path.

**Comment by olear** [comment]
open a terminal, use the command 'ldd' on the IO.ofx file, then post the output here is possible.

**Comment by adallafontana** [comment]
linux-vdso.so.1 =>  (0x00007ffddd5df000)
	libGL.so.1 => /usr/lib/nvidia-352/libGL.so.1 (0x00007fb9b9443000)
	libIlmImf-2_2.so.22 => /home/alelaptop/Natron2/Plugins/IO.ofx.bundle/Contents/Linux-x86-64/../../Libraries/libIlmImf-2_2.so.22 (0x00007fb9b8f6f000)
	libImath-2_2.so.12 => /home/alelaptop/Natron2/Plugins/IO.ofx.bundle/Contents/Linux-x86-64/../../Libraries/libImath-2_2.so.12 (0x00007fb9b8d5e000)
	libHalf.so.12 => /home/alelaptop/Natron2/Plugins/IO.ofx.bundle/Contents/Linux-x86-64/../../Libraries/libHalf.so.12 (0x00007fb9b8b1c000)
	libIex-2_2.so.12 => /home/alelaptop/Natron2/Plugins/IO.ofx.bundle/Contents/Linux-x86-64/../../Libraries/libIex-2_2.so.12 (0x00007fb9b88fc000)
	libIexMath-2_2.so.12 => /home/alelaptop/Natron2/Plugins/IO.ofx.bundle/Contents/Linux-x86-64/../../Libraries/libIexMath-2_2.so.12 (0x00007fb9b86f8000)
	libIlmThread-2_2.so.12 => /home/alelaptop/Natron2/Plugins/IO.ofx.bundle/Contents/Linux-x86-64/../../Libraries/libIlmThread-2_2.so.12 (0x00007fb9b84f1000)
	libavformat.so.56 => /home/alelaptop/Natron2/Plugins/IO.ofx.bundle/Contents/Linux-x86-64/../../Libraries/libavformat.so.56 (0x00007fb9b8113000)
	libavcodec.so.56 => /home/alelaptop/Natron2/Plugins/IO.ofx.bundle/Contents/Linux-x86-64/../../Libraries/libavcodec.so.56 (0x00007fb9b6d7d000)
	libswscale.so.3 => /home/alelaptop/Natron2/Plugins/IO.ofx.bundle/Contents/Linux-x86-64/../../Libraries/libswscale.so.3 (0x00007fb9b6b04000)
	libavutil.so.54 => /home/alelaptop/Natron2/Plugins/IO.ofx.bundle/Contents/Linux-x86-64/../../Libraries/libavutil.so.54 (0x00007fb9b689d000)
	libOpenImageIO.so.1.5 => /home/alelaptop/Natron2/Plugins/IO.ofx.bundle/Contents/Linux-x86-64/../../Libraries/libOpenImageIO.so.1.5 (0x00007fb9b5f94000)
	libSeExpr.so => /home/alelaptop/Natron2/Plugins/IO.ofx.bundle/Contents/Linux-x86-64/../../Libraries/libSeExpr.so (0x00007fb9b5d4e000)
	libOpenColorIO.so.1 => /home/alelaptop/Natron2/Plugins/IO.ofx.bundle/Contents/Linux-x86-64/../../Libraries/libOpenColorIO.so.1 (0x00007fb9b5a1b000)
	liblcms2.so.2 => /home/alelaptop/Natron2/Plugins/IO.ofx.bundle/Contents/Linux-x86-64/../../Libraries/liblcms2.so.2 (0x00007fb9b57c3000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fb9b5441000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fb9b5139000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fb9b4f21000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fb9b4d03000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fb9b4939000)
	libnvidia-tls.so.352.41 => /usr/lib/nvidia-352/tls/libnvidia-tls.so.352.41 (0x00007fb9b4735000)
	libnvidia-glcore.so.352.41 => /usr/lib/nvidia-352/libnvidia-glcore.so.352.41 (0x00007fb9b1ca3000)
	libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007fb9b1969000)
	libXext.so.6 => /usr/lib/x86_64-linux-gnu/libXext.so.6 (0x00007fb9b1756000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fb9b1552000)
	libz.so.1 => /home/alelaptop/Natron2/Plugins/IO.ofx.bundle/Contents/Linux-x86-64/../../Libraries/libz.so.1 (0x00007fb9b133c000)
	libmodplug.so.1 => /home/alelaptop/Natron2/Plugins/IO.ofx.bundle/Contents/Linux-x86-64/../../Libraries/libmodplug.so.1 (0x00007fb9b0fb1000)
	libbz2.so.1 => /home/alelaptop/Natron2/Plugins/IO.ofx.bundle/Contents/Linux-x86-64/../../Libraries/libbz2.so.1 (0x00007fb9b0da0000)
	libswresample.so.1 => /home/alelaptop/Natron2/Plugins/IO.ofx.bundle/Contents/Linux-x86-64/../../Libraries/libswresample.so.1 (0x00007fb9b0b86000)
	libxvidcore.so.4 => /home/alelaptop/Natron2/Plugins/IO.ofx.bundle/Contents/Linux-x86-64/../../Libraries/libxvidcore.so.4 (0x00007fb9b086f000)
	libx264.so.146 => /home/alelaptop/Natron2/Plugins/IO.ofx.bundle/Contents/Linux-x86-64/../../Libraries/libx264.so.146 (0x00007fb9b04e8000)
	libvpx.so.2 => /home/alelaptop/Natron2/Plugins/IO.ofx.bundle/Contents/Linux-x86-64/../../Libraries/libvpx.so.2 (0x00007fb9b0117000)
	libogg.so.0 => /home/alelaptop/Natron2/Plugins/IO.ofx.bundle/Contents/Linux-x86-64/../../Libraries/libogg.so.0 (0x00007fb9aff10000)
	libtheoraenc.so.1 => /home/alelaptop/Natron2/Plugins/IO.ofx.bundle/Contents/Linux-x86-64/../../Libraries/libtheoraenc.so.1 (0x00007fb9afcd0000)
	libtheoradec.so.1 => /home/alelaptop/Natron2/Plugins/IO.ofx.bundle/Contents/Linux-x86-64/../../Libraries/libtheoradec.so.1 (0x00007fb9afab7000)
	libspeex.so.1 => /home/alelaptop/Natron2/Plugins/IO.ofx.bundle/Contents/Linux-x86-64/../../Libraries/libspeex.so.1 (0x00007fb9af89f000)
	libschroedinger-1.0.so.0 => /home/alelaptop/Natron2/Plugins/IO.ofx.bundle/Contents/Linux-x86-64/../../Libraries/libschroedinger-1.0.so.0 (0x00007fb9af5d9000)
	libopus.so.0 => /home/alelaptop/Natron2/Plugins/IO.ofx.bundle/Contents/Linux-x86-64/../../Libraries/libopus.so.0 (0x00007fb9af38e000)
	libmp3lame.so.0 => /home/alelaptop/Natron2/Plugins/IO.ofx.bundle/Contents/Linux-x86-64/../../Libraries/libmp3lame.so.0 (0x00007fb9af118000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fb9aef0f000)
	libboost_filesystem.so.1.55.0 => /home/alelaptop/Natron2/Plugins/IO.ofx.bundle/Contents/Linux-x86-64/../../Libraries/libboost_filesystem.so.1.55.0 (0x00007fb9aecf9000)
	libboost_regex.so.1.55.0 => /home/alelaptop/Natron2/Plugins/IO.ofx.bundle/Contents/Linux-x86-64/../../Libraries/libboost_regex.so.1.55.0 (0x00007fb9aea12000)
	libboost_system.so.1.55.0 => /home/alelaptop/Natron2/Plugins/IO.ofx.bundle/Contents/Linux-x86-64/../../Libraries/libboost_system.so.1.55.0 (0x00007fb9ae80f000)
	libboost_thread.so.1.55.0 => /home/alelaptop/Natron2/Plugins/IO.ofx.bundle/Contents/Linux-x86-64/../../Libraries/libboost_thread.so.1.55.0 (0x00007fb9ae5f7000)
	libfreetype.so.6 => /home/alelaptop/Natron2/Plugins/IO.ofx.bundle/Contents/Linux-x86-64/../../Libraries/libfreetype.so.6 (0x00007fb9ae36a000)
	libpng12.so.0 => /home/alelaptop/Natron2/Plugins/IO.ofx.bundle/Contents/Linux-x86-64/../../Libraries/libpng12.so.0 (0x00007fb9ae144000)
	libtiff.so.5 => /home/alelaptop/Natron2/Plugins/IO.ofx.bundle/Contents/Linux-x86-64/../../Libraries/libtiff.so.5 (0x00007fb9aded2000)
	libjpeg.so.9 => /home/alelaptop/Natron2/Plugins/IO.ofx.bundle/Contents/Linux-x86-64/../../Libraries/libjpeg.so.9 (0x00007fb9adc97000)
	libraw_r.so.10 => /home/alelaptop/Natron2/Plugins/IO.ofx.bundle/Contents/Linux-x86-64/../../Libraries/libraw_r.so.10 (0x00007fb9ad9f0000)
	/lib64/ld-linux-x86-64.so.2 (0x000055f20635b000)
	libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x00007fb9ad7ce000)
	liborc-0.4.so.0 => /home/alelaptop/Natron2/Plugins/IO.ofx.bundle/Contents/Linux-x86-64/../../Libraries/liborc-0.4.so.0 (0x00007fb9ad54d000)
	libjasper.so.1 => /home/alelaptop/Natron2/Plugins/IO.ofx.bundle/Contents/Linux-x86-64/../../Libraries/libjasper.so.1 (0x00007fb9ad2f5000)
	libgomp.so.1 => /usr/lib/x86_64-linux-gnu/libgomp.so.1 (0x00007fb9ad0d2000)
	libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007fb9acece000)
	libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007fb9accc8000)

**Comment by olear** [comment]
Thanks.

**Comment by devernay** [comment]
fixed?

**Comment by adallafontana** [comment]
No, also with the  last snapshot.

**Comment by legocef01** [comment]
I also have the same problem. After an upgrade to ubuntu 15.10, problems come with Read and write. I can't import most pictures. For Read, I only have 4 extension support for importation : PSD, SVG,  SVGZ and XCF.

**Comment by olear** [comment]
Will try to find the bug, currently unable to replicate (I test on Ubuntu 15.10 before every release, and it works here).

Any special software installed? So I can replicate your installations and find the bug.

**Comment by adallafontana** [comment]
hummm... maybe Krita? I have Krita and Natron on 15.04 and all works, but Krita support OCIO and I had some conflict with other software in the past.

**Comment by olear** [comment]
IO.ofx uses it own OCIO/OIIO, so the system OCIO/OIIO will not be used.

```
libOpenColorIO.so.1 => /home/alelaptop/Natron2/Plugins/IO.ofx.bundle/Contents/Linux-x86-64/../../Libraries/libOpenColorIO.so.1 (0x00007fb9b5a1b000)
```

Will install 15.04 on a spare computer, and will install random gfx/vfx software, then update to 15.10 and see what happens...

I will also do a couple of test builds of IO.ofx for you to try.

**Comment by olear** [comment]
Try (re)moving the libOpenColorIO.so.1 and/or libOpenImageIO.so.1.5 lib from the Plugins/IO.ofx.bundle/Libraries folder (you could also try moving the complete 'Libraries' folder (verify that you have OIIO/OCIO/ffmpeg installed on the system first)).

**Comment by olear** [comment]
Finally able to replicate the bug after upgrading from 15.04 to 15.10.

Its a problem with OpenImageIO, working on a fix.

**Comment by olear** [comment]
Please download  http://downloads.natron.fr/~olear/github/IO.ofx and overwrite Natron2/Plugins/IO.ofx.bundle/Contents/Linux-x86-64/IO.ofx and verify that it works.

**Comment by legocef01** [comment]
I tried to remove the libraries, no thing have changed. Il also removed IO.ofx, nothing again. I don't know what is the problem. 
You said "verify that you have OIIO/OCIO/ffmpeg-libs/SeExpr installed on the system first". How can I verify that?

**Comment by adallafontana** [comment]
Here it works!
But olear now what's happen, every time we updating the new snapshot must we change this file?

**Comment by olear** [comment]
I will update the build server, just need a verification that it works for you (does here).

@legocef01 You downloaded http://downloads.natron.fr/~olear/github/IO.ofx and replaced the file?

**Comment by adallafontana** [comment]
yes sorry, I have repalced the file and now works.

**Comment by legocef01** [comment]
Ha ok! All work fine now. Thank you! The workaround for me was to replace the IO.ofx file.

**Comment by olear** [comment]
Will be fixed in a build later today.
