### ISSUE TITLE
GEOMETRY IMPORT FEATURE REQUEST

### ISSUE THREAD

**Issue by Ambassy** [MrKepzie/Natron#1023]
HI DEVS
since there is a plan to implement 3D support in natron, it could be profitable to be able to import geometry/wire frame so that the artist can project onto textures. 

in my opinion this feature might vital and fatal in a software targeting VFX industry. this also make it easy to introduce natron in the complex VFX arsenal.

**Comment by Ambassy** [comment]
to make it clear i want to make a mountains scene from these goemetry by projecting the painted texture on such geometry.
file:///home/216181453/Downloads/back_wireframe.png

and make desert scene from this one.
file:///home/216181453/Downloads/wireframe.gif

**Comment by MrKepzie** [comment]
This is quite a vast feature request and if it will be one day implemented we will before hand make sure that make something that is widely needed by most users. Let me close this for now, we will talk about it when the 3D workspace will exist
