### ISSUE TITLE
Script Editor enhancements

### ISSUE THREAD

**Issue by cg-cnu** [MrKepzie/Natron#1024]
Trying out Natron python api and I found some issue with the Script Editor.
I agree, internal Script Editor is not intended to be a feature rich text editor. 
But, I feel it need some basic stuff to make it more usable to run scripts or try out the api. 

* Undo: Need to retrieve the executed script on undo ( ctrl+z )
* Don't Clear the script: Right now the QTextBox is cleared on 'Ctrl+Enter', please don't clear it.
* Execute selected script: If code is selected execute just the selected part else execute the whole script.

These are some small annoying stuff I found, would love to hear what others think.

**Comment by MrKepzie** [comment]
I have implemented your points 2 and 3, point 1 is already implemented via ctrl + [
