### ISSUE TITLE
render aborted: exr files

### ISSUE THREAD

**Issue by mathiastesar** [MrKepzie/Natron#1025]
Hi team, 
I have a problem since the RC3.
I try to write a stereo shot in exr using the following pattern:
sh02540_test_%V_#####.exr

i have a aborted render popup message when i try to render.
If i remove the %V and put "left " or "right" instead i have no issues to render.
The problem never occured on RC2 abd below here.

Thanks ! :^)

**Comment by MrKepzie** [comment]
Works fine here, can you post a screenshot of the writ node settings ?

**Comment by MrKepzie** [comment]
Also show the project settings View tab

**Comment by mathiastesar** [comment]
![write_rc3](https://cloud.githubusercontent.com/assets/15384202/11153841/a4f88044-8a09-11e5-9392-d0cb752122c1.png)

here is the screenshot

**Comment by MrKepzie** [comment]
Can you show the Views tab of the project settings ?

**Comment by mathiastesar** [comment]
Hi Alex, you can close this one i just made a reboot since the last install in the studio and it works fine for the render. However it crashes when i try to add several layers to the exr. I ll keep you updated in a new post.
thks !

**Comment by MrKepzie** [comment]
ok
