### ISSUE TITLE
Read EXR command line process does not finish.

### ISSUE THREAD

**Issue by timurhai** [MrKepzie/Natron#1026]
Hi.
If project has a reader with exr file type, command line mode process does not finish.
Here is a Natron project, some image files, command to run Natron and an archive with it all:
http://afanasy.info/tmp/read_exr_bug

On Linux command is working (finishes with success):

    /opt/Natron/Natron -b -w Write1 1-1 project.ntp

On Windows it does not finish:

    "C:\Program Files\INRIA\Natron-2.0.0-RC3\bin\Natron.exe" -b -w Write1 1-1 project.ntp

But if i  change reader file extension from ".exr" to ".png" (both files are provided, 51 line in the projcet) it works fine.

**Comment by MrKepzie** [comment]
Hi, I'm unable to reproduce the issue on Windows currently. Can you check again with a more recent snapshot ? http://downloads.natron.fr/Windows/snapshots/64bit/files/

**Comment by timurhai** [comment]
Hi.
Great!
Today (nov-16) snapshot works fine!
