### ISSUE TITLE
[wishlist] support for VapourSynth filters/plugins/scripts in Natron

### ISSUE THREAD

**Issue by YAFU** [MrKepzie/Natron#1027]
In Blender 3D/Cycles we made some noise reduction experiments with VapourSynth:
http://blenderartists.org/forum/showthread.php?378736-Cycles-noise-reduction-with-VapourSynth

There are filters/plugins that allow achieve excellent noise reduction results without blurring much the image. Although these scripts use some convinations of filters and plugins, some plugins are easier to use as KNLMeansCL (OpenCL noise reduction plugin):
http://forum.doom9.org/showthread.php?s=2e35f6f4b1f2c364526fb606fc27d616&t=171379

It would be great if Natron could support these VapourSynth filters, because we could use multilayer EXR to obtain different levels of noise reduction in each Blender render layer and compositing at same time.

**Comment by PostPollux** [comment]
This denoising is pretty awesome! I'm actually trying to get this VapourSynth setup working for quite a while now, but I had no luck so far. To have this functionality in Natron would be a dream!

**Comment by YAFU** [comment]
@PostPollux, If you have a Linux distribution based on Ubuntu, there in the message #10 in blenderartists link I mentioned how to install from PPA. In that thread there are scripts mainly for noise reduction in ray tracing renderers, but can be adapted for any purpose. If you have a good graphics card a simple script to reduce noise with KNLMeansCL is (save de file as "script.vpy" for example):
http://www.pasteall.org/62417

Then run from the terminal in the path of the script:
vspipe --y4m script.vpy - | ffmpeg -i pipe: -vcodec libx264 -crf 5 encoded.mp4

These filters analyze more than one frame at a time to reduce noise, so I hope that's not a problem in order to implement it in Natron.

**Comment by devernay** [comment]
This issue was moved to NatronGitHub/Natron#124
