### ISSUE TITLE
light wrap node

### ISSUE THREAD

**Issue by Ambassy** [MrKepzie/Natron#1030]
HELLO DEVS.

a composite can not be a composite without perfect light match between fore groung and background.
IN MY OPINION NATRON CAN BENEFIT FROM A LIGHT WRAP NODE to match lights in the composite.
may be its not the priority now but you can implement it when you have time.

THANKS IN ADVANCE.

**Comment by devernay** [comment]
LightWrap is a gizmo in Nuke, you can make the same (as a pyplug) in Natron.
See also http://www.nukepedia.com/gizmos/filter/bm_lightwrap and the LightWrap pyplog from @Coyhot (I don't have the download link)

**Comment by Ambassy** [comment]
tanks in advance.
is there a plan to bundle that lightWrap from @Coyhot with natron.
btw thanks for what natron is nowadays. my boss is about to agree the use of natron in the studio.
