### ISSUE TITLE
clear cache issue

### ISSUE THREAD

**Issue by mathiastesar** [MrKepzie/Natron#1031]
Hi team,
I frequently have crashes when i use the "clear all caches" function in some larger comps.
thks !!!

**Comment by MrKepzie** [comment]
This probably is fixed in RC4. Will be released later today

**Comment by olear** [comment]
Still an issue?

**Comment by mathiastesar** [comment]
hi ! je check today sur la rc5 ;^)

2015-12-09 10:35 GMT-05:00 Ole-André Rodlie <notifications@github.com>:
