### ISSUE TITLE
text pango error when connecting

### ISSUE THREAD

**Issue by Ambassy** [MrKepzie/Natron#1033]
the text pango node is reporting an error of missing fonts when connecting between viewer and reader node.
![font missing](https://cloud.githubusercontent.com/assets/13351377/11346831/3fc55618-9227-11e5-83cc-f4537974b398.PNG)
![pango error](https://cloud.githubusercontent.com/assets/13351377/11346857/7034af9c-9227-11e5-8ee8-30d6cbc42cbc.PNG)

**Comment by olear** [comment]
Seems like a build issue on Windows, will check.

**Comment by olear** [comment]
Works in latest snapshot for Windows.
