### ISSUE TITLE
file path in the title bar

### ISSUE THREAD

**Issue by cg-cnu** [MrKepzie/Natron#1035]
Display complete path to the file and natron version in the title bar.
Right now it just displays **Natron - filename.ntp**

**Comment by MrKepzie** [comment]
We prefer indicating just the filename, you can still get the full path in the project settings.
Another way to overcome this could be to add a Python callback when a Window title is set

**Comment by cg-cnu** [comment]
I would vote for having an option in the Edit > Preferences > General to enable project path in the Window title. Will be handy when working on multiple files and versions.

What about showing natron version in the title?

**Comment by devernay** [comment]
@cg-cnu what OS are you using?

On OS X we could implement cmd-click on the titlebar to show where the file is located, as in all other OS X apps. See https://doc.qt.io/archives/qq/qq18-macfeatures.html#newevents

**Comment by devernay** [comment]
btw, here are the guidelines for formatting the window title from the file path:
http://doc.qt.io/qt-4.8/qwidget.html#windowFilePath-prop

**Comment by devernay** [comment]
Having the fill project path in the titlebar is both unrealistic and unfriendly (a file path can easily be more than 100 characters long).
Commit https://github.com/MrKepzie/Natron/commit/826a2270f51186237626af409979ae591d0315ff brings a more standard titlebar on all OSes.
For now, OS X gets the possibility to show the full path, either by cmd-clicking it, or by drag-and-dropping it (e.g. to a terminal).
I do not know the exact behaviour on other OSes, but if will follow the user interface guidelines for each OS.

**Comment by cg-cnu** [comment]
> Having the fill project path in the titlebar is both unrealistic and unfriendly (a file path can easily be more than 100 characters long).
@devernay Almost all the software(maya,blender) I use, displays the full file path in the title bar. Which is quite handy. It would be great if we show the version also. 
just an example from maya..
![windowtitlebar](https://cloud.githubusercontent.com/assets/2767425/11492727/073257e2-9817-11e5-931b-7c64a7f178ba.png)

**Comment by devernay** [comment]
@cg-gnu what you propose violates all user interface guidelines I could find:
- On Windows https://msdn.microsoft.com/en-us/library/windows/desktop/bb246387
- On OSX https://developer.apple.com/library/mac/documentation/UserExperience/Conceptual/OSXHIGuidelines/WindowNaming.html
- On GNOME https://developer.gnome.org/hig-book/unstable/windows-properties.html.en ("Omit information that does not assist in this selection, for example the application's version number or vendor name.")

We are using Qt to set the window title from the file name in a portable way: http://doc.qt.io/qt-4.8/qwidget.html#windowFilePath-prop

My advice: Just use project names that are more meaningful than "test", and voilà. Maybe you took bad habits from software that do not fillow UI guidelines.

**Comment by cg-cnu** [comment]
@devernay 
While I was just using the project name as ""test"" just to provide a screen shot reference, I am quite surprised to hear that it was against the user interface guidelines. Even with proper production pipeline in place I would love to have the whole path visible in the title bar. Will see if anyone else would like to have it or may be its just. Thanks.
