### ISSUE TITLE
ctrl+f: Select all nodes containing the text

### ISSUE THREAD

**Issue by cg-cnu** [MrKepzie/Natron#1036]
Couple of enhancements on the search nodes functionality. 

> Connect enter on QLineEdit to QPushButton 'ok'. 

Cycling through the nodes will be easy.

> Option to select all the nodes.

Helps in getting a overview of the script.
> Option to automatically open the properties window on selection. 

Will be helpful in comparing the parameters on different nodes when cycling through.
 
Would like to know what other people think.

**Comment by MrKepzie** [comment]
1) is a bug and was fixed
2) you can just press CTRL+A to select all nodes
3) We have more wider plans to address this with a smarter selection, so I close this as this is already in the "todo" list

**Comment by cg-cnu** [comment]
1) Thanks for that!
2) I meant to say all nodes matching the pattern, instead of selecting one after the another.
eg, searching for roto* now will cycle through each roto node on pressing ok. I was looking for a way to select all roto nodes in one go.
3)Awesome! Is it anywhere in the git issues ?
