### ISSUE TITLE
NatronRenderer: rending frames randomly

### ISSUE THREAD

**Issue by cg-cnu** [MrKepzie/Natron#1038]
Thanks for the fixes and the features in cli. https://github.com/MrKepzie/Natron/issues/1016
One thing I noticed, NatronRenderer renders frames randomly. Is it be possible to make it render in an ascending order, which is the usually expected order.

**Comment by MrKepzie** [comment]
It is not random it's just multi-threaded. If you want to have a single frame computed at once, just set the number of parallel renders in the General Settings to 1.
