### ISSUE TITLE
Render inidividual and ranges using write node in gui

### ISSUE THREAD

**Issue by cg-cnu** [MrKepzie/Natron#1039]
Same functionality as mentioned in https://github.com/MrKepzie/Natron/issues/1016 but for the write node.
eg; 125,126,158-170:2,200.  Will be very helpful in rendering error frames in one batch in gui.

**Comment by devernay** [comment]
note that it works on the command-line, see https://github.com/MrKepzie/Natron/issues/1016

**Comment by devernay** [comment]
This issue was moved to NatronGitHub/Natron#126
