### ISSUE TITLE
curve interpolation issue: values in properties panel not updated

### ISSUE THREAD

**Issue by PostPollux** [MrKepzie/Natron#1046]
The interpolations in the curve editor seem to be a bit confusing if you have just two keyframes. For some reason most of the interplations result in linear... Everything works perfect if you have 3 or more keyframes (except the first and the last keyframe). I think one would expect to get an eased-in and eased-out cuve if you have two keyframes and choose smooth or horizontal as interpolation mode. You can see it in the video here:
https://goo.gl/photos/bJnfTCVXTkqf8EpF6

I have the newest version of Natron at commit 89b2e201cda3f0a9522944e79343b5cc6182a743 running under Linux Manjaro.

**Comment by devernay** [comment]
The value in the properties panel is not updated, but interpolation works (go on frame forward, then backward: the value is then updated)

**Comment by PostPollux** [comment]
Yes, you are right. The value in the properties panel doesn't update. I didn't even notice this. But what I think should happen if you set the interpolation to smooth/horizontal is:
https://goo.gl/photos/iU4sA3xUG7oVcT9E8

**Comment by devernay** [comment]
You are right there is a bug with horizontal, which doesn't set one of the tangents on the first and last keyframe.
The smooth behavior is normal, because tangents are broken ar the first and last keyframe.
You can join them by going through Catmull-Rom, then adjusting them.
