### ISSUE TITLE
Creating Pyplug Issues

### ISSUE THREAD

**Issue by huargovfx** [MrKepzie/Natron#1065]
Good day, I have the following problems:
When creating a Pyplug, a param with hide checkbox on, doesn't save the param propeties. I had to do it manually. Before I used to "param.setVisible(False)", now it doesn't.

Also Label is not working when creating user params. it just shows " : "

Cheers.

**Comment by MrKepzie** [comment]
The first is a bug that I just fixed. 

For the Label, this is the "Default Value" of the parameter that will be visible, not its actual label.

**Comment by huargovfx** [comment]
Thank you, I must update my scripts with the new config.

**Comment by MrKepzie** [comment]
Just re-exporting should be fine
