### ISSUE TITLE
Render panel Error

### ISSUE THREAD

**Issue by peterrobie** [MrKepzie/Natron#1066]
When rendering a simple scene (image sequence -> two text nodes overlayed with mix node) and adding a write node, if I click on Render in the node panel I get errors. However, if I go to the file menu and render from there then it gives the error, but also writes the file and completes the process.

Mac OS (10.11.1) and Natron 2.0.0 RC.

**Comment by MrKepzie** [comment]
Which RC version? I'm unable to reproduce on OSX 10.11.1

**Comment by peterrobie** [comment]
Hi Alexandre, 2.0.0 RC 4.

Additional note: Previously installed was 1.0.0, downloaded 2.0.0 RC 4 and overwrote 1.0.0. Might be possible that something didn't get overwritten correctly too. 

I'll do a video screen cap tonight showing the recreation of the issue and post that for you.

As noted, I was able to get around the issue after some troubleshooting and using the file menu.

Thanks!

**Comment by MrKepzie** [comment]
Indeed a screencast would be useful to be able to reproduce the error.

**Comment by peterrobie** [comment]
https://youtu.be/srtFm_525KU

I have to head back to work, but it should be posted here shortly.

**Comment by MrKepzie** [comment]
The fact that your panel is disabled is because you turned on "Turbo mode" in the viewer, which indicates that the properties will no longer be refreshed to optimize playback. The drawback being, you can no longer interact with the widgets until you release the turbo mode. 


Also note that to write out videos you need to use the WriteFFMPEG node (and use the right codec). The Write node can only output image sequences.

**Comment by peterrobie** [comment]
Thanks Alexandre. I'll check those here in a bit. I know a lot of it last night was trial and error. Are there going to be additional updates to a more comprehensive "Getting started" video series? That would be incredibly helpful.

Again, I'll turn off turbo mode and re-do the workflow that I followed last night to reproduce the error.

**Comment by MrKepzie** [comment]
That is up to the community, you may find more resources on the forums.
