### ISSUE TITLE
Help menu

### ISSUE THREAD

**Issue by cg-cnu** [MrKepzie/Natron#1069]
Will be helpful for artists starting out instead of searching around.
I would suggest the following contents.

* Website ( http://natron.fr/ )
* Tutorials ( Link to basic getting started tutorials )
* User Documentation  (end user documentation)
* Developer Documentation  (http://natron.readthedocs.org/)
* Forum  ( http://forum.natron.fr/ )
* Source code( https://github.com/MrKepzie/Natron )
* About (move from file menu to here)

**Comment by devernay** [comment]
On windows, the "About Natron" menu entry should be in the "Help" menu:
https://msdn.microsoft.com/en-us/library/windows/desktop/dn742392%28v=vs.85%29.aspx
```
Help
    <program name> help F1
    <separator>
    About <program name> 
```

The same holds for GNOME

**Comment by olear** [comment]
So, is this ok to merge?

https://github.com/olear/Natron/commit/d5efde27a20c51b92baf95eb7867ab36a4c760dd
https://github.com/olear/Natron/commit/ac47f39dc7686b41ddf0d107e6a4a442bcc3c267

help
 * website
 * forum
 * issues
 * wiki
 * python api
 * about natron

**Comment by MrKepzie** [comment]
sure
