### ISSUE TITLE
wacom tablet middle mouse issue

### ISSUE THREAD

**Issue by adallafontana** [MrKepzie/Natron#1070]
the middle mouse of the wacom pen for drag, works bad, randomize or full doesn't drag but only on viewer windows, on the Node Graph works right.

I test it on Ubuntu 15.04 and 15.10 with 3 different kind of wacom tablets.

**Comment by devernay** [comment]
I also noticed that on OSX dragging with the pen works, but has a lot of lag (about 0.2-0.3s), whereas the mouse responds instantly. I observe the same lag on the viewer and the nodegraph.

**Comment by olear** [comment]
My wacom works ok, but I get lag in the viewer when moving, but it's better than it was. The nodegraph is ok here.

**Comment by adallafontana** [comment]
Bug recipe:
open Natron, create CheckerBoard node and connected to viewer, enlarge the viewer to full screen, press F or use zoom for enlarge the picture to a full screen, I try to drag or zooming with middle mouse (mouse) and all works ok; I try to do the same with wacom pen and I have the evident delay until to a stop the movement.
With NodeGraph I don't have any problem.

**Comment by MrKepzie** [comment]
Is this still the case after recent snapshots ?

**Comment by adallafontana** [comment]
With c1fd19dc2e825c127a61bd0c42011b099b94d063 still the same, I test ever the wacom middle drag also with other software where works good.

**Comment by olear** [comment]
Latest snapshot on Linux seems to have fixed most of the issues here at least. Will test on a different computer as-well.

**Comment by adallafontana** [comment]
Have you repeat my bug recipe?
With a standard layout viewer and the image zoom e.g. at 33% works good, the issue happen when the zoom is 100% or more.

**Comment by olear** [comment]
I add a image, zoom 100% or more, drag.... mouse/wacom seems very similar.

**Comment by adallafontana** [comment]
Ok, I tested on 3 machines with 3 kind of wacom (intuos 3 medium, intuos 5 medium, intuos Pro medium):
Desktop Ubuntu 15.04 : working bad.
Desktop Ubuntu 15.10 : working good (the mouse is always better but only a bit, it is precise, no any delay)
Laptop  Ubuntu 15.10 : working good (like a desktop 15.10)

Olear, what system have you tested?

**Comment by olear** [comment]
Will do some tests on Ubuntu tomorrow, what gfx card (and driver) do you use?

**Comment by adallafontana** [comment]
Hi Ole-André,
Ubuntu 15.10, GPU Nvidia Quadro 4000, Driver 352.63

I don't know if the GPU or driver are the issue,
the strange thing is that, with the mouse works fine and also
if I click outside the frame in the black area, the issue happens only 
when I click over the image frame.

thanks

a.

On 07/01/2016 21:13, Ole-André Rodlie wrote:
>
> Will do some tests on Ubuntu tomorrow, what gfx card (and driver) do 
> you use?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/MrKepzie/Natron/issues/1070#issuecomment-169792761>.
>

-- 
Alessandro Dalla Fontana s.r.l.
via Sacchini, 4 - 20131 Milano
t. +39 393 9875960
http://www.alessandrodallafontana.com
https://www.instagram.com/adallafontana

**Comment by olear** [comment]
Ok, the card/driver should not be the issue. Will do various test with Wacom tomorrow on Ubuntu and see what happens.

**Comment by devernay** [comment]
Any update?

**Comment by olear** [comment]
Tested on Ubuntu 14.04, performance seems the same here (not identical, but similar), also ok on CentOS7.

**Comment by adallafontana** [comment]
sorry for the delay, on my desktop Ubuntu 15.10 the issue remain but on others machines with same OS I haven't problems, so I'm thinking that the issue is connected only to that computer.
For me you can close.

thanks
