### ISSUE TITLE
Natron Windows Installer doesn't have a GUI?

### ISSUE THREAD

**Issue by kourbou** [MrKepzie/Natron#1072]
Hey,
When I try to open Natron-2.0.0-RC4-Windows-x86_64bit-setup.exe on on my Windows 10 machine I get no wizard GUI open up for the installer. I checked if it was installing anything, it's using up 20% of my CPU but I don't see it making any files. I ended up using the self contained zip as a workaround.

**Comment by olear** [comment]
Did you try to right-click and run as admin?

**Comment by kourbou** [comment]
Oh it worked. Thanks.
