### ISSUE TITLE
Natron RC4 crash with text Node

### ISSUE THREAD

**Issue by MarcRose** [MrKepzie/Natron#1074]
Problem with the node text.
Constant -> Text -> Viewer.
Change the font in the Text node, Natron RC4 and the latest snapshot crash.
The node text bug on the RC3 does not crach Natron

Probleme avec le node Texte. 
Constant -> Text -> Viewer. 
Changer la police dans le node Text, Natron RC4 et le dernier snapshot crash.
Le node text bug sur la RC3 mais ne fait pas cracher Natron.

**Comment by olear** [comment]
I tested a snapshot from the third of December on my laptop, and I got no crash on Linux, what platform are you using?

**Comment by MarcRose** [comment]
my platform is OSX 10.9.5 and Ubuntu Studio 14.4.3.
In Text mode when I select the source layer menu: Backward.
Natron crash, Natron RC4 and all snapshot.

**Comment by olear** [comment]
Thanks for the info, will see what I can do today.

Btw, I can add background support directly in the text node if wanted.
