### ISSUE TITLE
Primatte error: clip '' does not exist

### ISSUE THREAD

**Issue by nicholascarroll** [MrKepzie/Natron#1075]
Looks like a bug: If you connect a Primatte node it immediately throws a dialog box with the error message: clip '' does not exist.

This has appeared sometime since V 2.0.

**Comment by devernay** [comment]
Which Primatte plugin are you using? Is it possible to download a trial version?

**Comment by nicholascarroll** [comment]
Primatte version 5.1 on Mac. Yes, you can get a trial. You can download it from here: http://www.primatte.com/content.cfm?n=downloads
It will work but with a chequerboard over the output.

**Comment by olear** [comment]
I get no errors on Linux using latest version (v4.1) (just a bunch of license warnings in the terminal), anything special I need to do to replicate?

**Comment by nicholascarroll** [comment]
Thankyou for testing on Linux. I don't have Linux but I am replicating every time on OSX with the Natron December 6 snapshot. Steps are:
1. Add read node
2. Add Primatte either by selecting read node or by connecting the source input
3. Click in the viewer either just a left click or while holding command (select BG colour)
*this will cause the error dialog box to appear*

It only occurs when you select BG colour before any other parameter. Once any parameter is set in Primatte, it does not occur. Therefore it is not a serious problem.

If you would like me to set up a debug you just have to tell me how to do that. Thanks.

**Comment by devernay** [comment]
I can only find 32-bits versions of the primatte plugins. Do you run Natron in 32-bits mode?

**Comment by olear** [comment]
The OFX version is old (20060101), I had to install compat libs (gcc3) on Linux to get it working.

**Comment by olear** [comment]
So tested on OSX 10.6 with snapshot from December the 12th:
![snow leopard - primatte](https://cloud.githubusercontent.com/assets/7461595/11784129/099e28d0-a27b-11e5-9984-edae3a252eab.png)

No issues here

**Comment by nicholascarroll** [comment]
Thanks for testing. Can you please suggest any debug or other checks you want me to perform?
I have access to:
OSX 10.6
OSX 10.9
I will go try to reproduce on 10.6 tonight.

**Comment by nicholascarroll** [comment]
OK I tested and have these notes:
(a) On Natron 2.0 RC5 (Dec 7 build), on OSX 10.9 and 10.10.5, it always reproduces.
(b) On Natron 2.0 Devel (Aug 15 build), it never reproduces.
(c) On my OSX 10.6 it does not load; I don't know why.
*you have to follow the exact steps for reproducing, do not zoom the viewer or anything else.*

**Comment by olear** [comment]
I only have access to 10.6.

I downloaded the universal binary of primatte and ran the install.pl script, then enabled 32bit mode on the Natron launcher, then added the primatte node in Natron. Everything seems to work. I tested a snapshot from November and the latest snapshot.

**Comment by nicholascarroll** [comment]
We need to get you the right version of Primatte which is 64 bit for OSX, version 5.1. I will see if I can send you the binary Primatte gave me. Or, if you prefer, email your MAC address to the contact email at primatte.com and get a full/unlocked time limited trial. But you will need OSX 10.9+ to reproduce.

**Comment by olear** [comment]
I just used the "latest" available version on their website.

It would be best to offer the binary/trial to devernay or MrKezpie since they have better access to Mac than I have.

**Comment by devernay** [comment]
@nicholascarroll it's fine if we get a version that draws a checkerboard, we don't need a trial version. Can you ask Primatte to send us a download link?

**Comment by nicholascarroll** [comment]
sent email

**Comment by nicholascarroll** [comment]
sent by email to alexander
