### ISSUE TITLE
keyboard shortcuts to set in-/out points in viewers

### ISSUE THREAD

**Issue by mash-graz** [MrKepzie/Natron#1079]
right now we can not use "I" and "O" to set the playback range in viewers by using the keyboard to place in/out marks at the actual time stamp.

**Comment by devernay** [comment]
"i" and "o" should set in and out points xhen the viewer or timeline have focus (select the frame, then press "i" or "o")

**Comment by MrKepzie** [comment]
implemented

**Comment by MrKepzie** [comment]
it's ALT+I and ALT+O
