### ISSUE TITLE
File Browser and creating Reads.

### ISSUE THREAD

**Issue by B4adle7** [MrKepzie/Natron#1081]
One of the most import parts of using compositing software is bringing in footage and elements.
![filebrowser](https://cloud.githubusercontent.com/assets/16269992/11763333/86401df6-a0bb-11e5-8177-b6a81531c38f.jpg)
Issues as of RC5:
Windows 10 x64
- Show hidden fildes?
     files? fields?
- ComboBox for "Look in:" is un-useably small.
     This needs to be much wider, or possibly replaced by a shortcut/navigation panel to the left.
     Possibly merged with the semi-navigation panel below.
- As noted on another Issue post, network navigation and access seems impossible.
- Drag and Drop of frames and folders are needed.(Drag and drop into the node editor)
- Copying and Pasting a path to a directory doesn't navigate you to that directory. It simply fails stating that the directory is not a file or image. You can paste the full path to an image file, but it registers as just an image, rather than an image sequence.  This is ok, and is as intended.  However we are still missing how to load in an image sequence efficiently?
- Inconsistency in presenting available drive letters.
       Most times opening the software, the available drives are different.
       Drives for navigation panel are not consistent with directory and file list in selection panel.
- Found endless navigation loop.
       A network drive does/can appear. Navigate through to the directory containing the image sequences. Double clicking on the directory to the image sequence, the navigation resets back to the drive letter list again. This was an endless loop and no way to load the image sequence.

**Comment by devernay** [comment]
This issue was moved to NatronGitHub/Natron#131
