### ISSUE TITLE
Cancel rendering

### ISSUE THREAD

**Issue by michaelWuensch** [MrKepzie/Natron#1083]
Hi there,

When I have a normal write node and I am rendering an image sequence, Natron will freeze whenever I try to cancel the rendering. I am using Windows 7, Natron 2.0 RC5.
Can you try to find the issue and fix it?
Maybe it would just take a lot of time to cancel, but after 1 min i shut down the program manually. Even if it would work after a minute or so, this is not an acceptable time :)

Thanks,
Michael

**Comment by olear** [comment]
What nodes do you have/use in your comp? (a screenshot will do)

**Comment by michaelWuensch** [comment]
![natronbugreport](https://cloud.githubusercontent.com/assets/15313630/11844620/15b6e792-a410-11e5-9663-97904d872993.PNG)

**Comment by MrKepzie** [comment]
i do not have this issue, please send your project and indicate how many cores your cpu have

**Comment by olear** [comment]
It's slow on my machine as-well, see video:
http://downloads.natron.fr/~olear/github/cancel-render.ogv

**Comment by manuelsongokuh** [comment]
thank you!
