### ISSUE TITLE
Resize Node resets

### ISSUE THREAD

**Issue by michaelWuensch** [MrKepzie/Natron#1085]
Hi,

whenever the resize node is connected to a new source the Format is set to the Format that was chosen in the project settings. 

Minimal Example:
Create 2 Consants with e.g. 2k square format. Choose a Project Format (e.g. Pal). Create a resize Node and connect it to the first Constant. Choose as resize Format FullHD. Now just rewire the resize node to the second Constant with the same size and notice how the setting is set back to the Project settings format.

I think the node should keep the settings and instead adapt the Scene Settings on creation! At the moment it seems to always have "PC Video 640x480" as standard.

**Comment by michaelWuensch** [comment]
Sorry I forgot to mention, again i worked with Windows 7 and Natron 2.0 RC5

**Comment by MrKepzie** [comment]
Was fixed in https://github.com/MrKepzie/openfx-io/commit/e5d175d3d4b5204fc1ce1247f533ed11cd76e15c
