### ISSUE TITLE
colorlookup doing nothing

### ISSUE THREAD

**Issue by iscream75** [MrKepzie/Natron#1087]
after saving/closing and reopening a comp some colorlookup have no effect, sometime

**Comment by MrKepzie** [comment]
Can you provide an example reproduce the bug?

**Comment by iscream75** [comment]
​
 bug_colorLookup.ntp
<https://drive.google.com/file/d/0B_eqobfFfxLbZ0ZWemdPT0Y2M2s/view?usp=drive_web>
​attach any file to the inputs, the color correct on the left doesn't work

**Comment by MrKepzie** [comment]
The left colorlookup has the right colorlookup plugged-in as a Mask, hence it doesn't produce appropriate results. When I disconnect it it works OK

**Comment by MrKepzie** [comment]
Also check that the Mask checkbox is unchecked

**Comment by iscream75** [comment]
hummm it happend a lot on 3 project... perhaps it's always the same issue
 but then the bug is that the automatics connection  are too "fast" or easy
... dunno,

kevin

**Comment by MrKepzie** [comment]
Please check if this is because of automatic connections, because otherwise this is another issue.
