### ISSUE TITLE
Roto Undo Issue

### ISSUE THREAD

**Issue by PostPollux** [MrKepzie/Natron#1089]
Hi!
I had to do a quick roto yesterday and I constantly stumbled across a small undo issue which was a bit annoying.
If I'm moving a point of the roto and then afterwards move the whole shape (by accident or on purpous) and then hit undo, ONLY the position of the selected point will be undone and NOT the whole shape. But of course it should be the whole shape, as this was the last operation I did.

Here is a video to clearify what I'm talking about. Each time the shape is jumping I hit crtl-z: 
https://goo.gl/photos/pM74g1YjUEiR3BSf7

Thanks

**Comment by MrKepzie** [comment]
fixed
