### ISSUE TITLE
Drop Shadow Node

### ISSUE THREAD

**Issue by endesse** [MrKepzie/Natron#1090]
Knowing that natron main purpose is compositing, many of it's users may rely on some basic motion graphics. And that's exactly where a simple drop shadow effect comes in handy... It should however respect the alpha channel of the source provided.

**Comment by MrKepzie** [comment]
It was already added earlier today as a PyPlug, see https://github.com/MrKepzie/Natron/commit/5e7629e448cff75223d88b6e55b6082bddc845e2
You can test it through snapshots
