### ISSUE TITLE
how i need de-interlaced with natron?

### ISSUE THREAD

**Issue by manuelsongokuh** [MrKepzie/Natron#1091]
hello
my video MXF footage, 50i (interlaced) i need render to progressive or de-interlaced..?

instead from kdenlive method: from project needs to choose interlaced (25i or 50i or 29i etc) or choose progressive (25p, 50p, 29p, 60p etc).
but i want to use NATRON ok?

**Comment by manuelsongokuh** [comment]
version of natron is snapshot today..

**Comment by olear** [comment]
Deinterlace node is included with Natron, does it not work for you?

**Comment by manuelsongokuh** [comment]
i did try but strange to show in viewer.. like as double.. i can not produce here my home.. tomorrow i will show you ok?

**Comment by manuelsongokuh** [comment]
sorry me, how natron works for project interlaced and progressive..?

**Comment by manuelsongokuh** [comment]
here screenshot
![natron-interlaced-1](https://cloud.githubusercontent.com/assets/12126929/11894353/db8a4e70-a576-11e5-9a94-af7362eaea00.png)

my video is interlaced and i did added de-interlaced but result strange.. it is normal or i'm wrong something ..?

**Comment by manuelsongokuh** [comment]
this is without node de-interlaced, show is result correct.
![natron-interlaced-2](https://cloud.githubusercontent.com/assets/12126929/11894410/26296632-a577-11e5-83a9-cd67fcb3dcb8.png)

but render out jpg result like as interlaced..see result render:
![02388](https://cloud.githubusercontent.com/assets/12126929/11895069/e1c542cc-a57b-11e5-931f-1115f1a529b0.jpg)

**Comment by manuelsongokuh** [comment]
nothing resolve...? maybe i'm wrong something?

**Comment by manuelsongokuh** [comment]
sorry, this is bug of natron or i'm bug?

**Comment by MrKepzie** [comment]
Please post questions on the forums, where users can help you *using* the software. The github is for bugs mainly.
