### ISSUE TITLE
render is long time..why?

### ISSUE THREAD

**Issue by manuelsongokuh** [MrKepzie/Natron#1092]
natron is snapshot today.

my computer is workstation, 2 cpus XEON (24cores) 32gb of ram.
for render out: jpg sequence 90% of compression, and render is 5 hours..but is not finished.. i leave render my office job.. tomorrow i will back my office job, i will check..
so i need to know..
i want render out simple config like as jpg.. but i did try render out mov and 444 prores, render to 8 hours..

so i'm not undy why..

i did preferences: threads i put 24..not change..

but i want to render fast..with good quality and not SUPER QUALITY HEAVE.. but good quality.. i-m hard to find a good preset ready to use..

my video card is nvidia 970, it's can render to GPU or future..

then for now i need to finish my job little..

my video si MXF time is 5minutes..with key chrome and background image..

this is normal to render long time?

thank you for NATRON CREATE!!

**Comment by olear** [comment]
You should check how many cores Natron is using, use 'top' or similar program while you are rendering to see if your cores are in use (100%=1core).

Natron does not use the GPU (but some third-party plugins do).

Are you writing direct to disk or to a server?

**Comment by manuelsongokuh** [comment]
hello, tomorrow i will show for monitor cpu for rendering ok?

ok for GPU third-party plugin, i hope and thank .

render writing direct to disk..

other for "preset" for render good quality, for me easy to use png sequences but slow..

**Comment by manuelsongokuh** [comment]
i'm back here my office work: result render is 1 threads 100% and not all cores 100%..
![natron-long-time-render](https://cloud.githubusercontent.com/assets/12126929/11894256/46a1c1f8-a576-11e5-9254-60eb48ea964c.png)
![natron-long-time-render1](https://cloud.githubusercontent.com/assets/12126929/11894297/94617366-a576-11e5-88fb-f69164f4c91c.png)

**Comment by MrKepzie** [comment]
You don’t need to set “24” in the Preferences, if you read the tooltip it says that 0 will pick whatever is most optimised for your configuration. Natron is smart enough to know you have 24 cores. 

Then bear in mind writing to a video a file is far less optimised that writing image sequence because it needs continuity: you can only write a single frame at once to a video file, so no matter how many threads you have, only 1 thread will be able to write to your ffmpeg file. 
The processing upstream of the WriteFFMPEG node on the other hand is taking advantage of the multi-threading.

**Comment by manuelsongokuh** [comment]
ok i try, thank you

**Comment by manuelsongokuh** [comment]
ko resolved, but there is full documentation for natron to RENDER..?
because you write "The processing upstream of the WriteFFMPEG node on the other hand is taking advantage of the multi-threading" is important for information to know..
i will wait for documentation complete, sorry for post here issue..

**Comment by MrKepzie** [comment]
If you let the default preferences it should work OK. 
Natron is intended for compositing tasks and is working better with image sequences if you can afford using this kind of medium.
