### ISSUE TITLE
is can extract 1 frame to png from viewer?

### ISSUE THREAD

**Issue by manuelsongokuh** [MrKepzie/Natron#1094]
hello

i find helpful to use extract to png from viewer (active), because when i send you original frame result to show you or my other friends or my partners (jobs) to send to show result.

for now i used render out writerFFMPEG and i setting: Frame range >>>manual>>first frame 1 and last frame 1 and quality 90% and click RENDER..

different than extract 1 frame to png from viewer and first set choose current frame and render out direct without setting and will be default 100% quality lossness 

this is good or not good.

i use many time extract from kdnelive have it.

if natron will add new feature i will happy. true fast to use one click to extract direct render out..
good think.

**Comment by MrKepzie** [comment]
You can make a Python script for that or get help on the forums from experienced python developers.
