### ISSUE TITLE
Feature: Import .ntp files

### ISSUE THREAD

**Issue by PostPollux** [MrKepzie/Natron#1096]
I had to do a quick roto while my coworker was working on the key of the same shot. When I was finished we of course wanted to combine our projects. This was harder then expected and doesn't feel right.
Correct me if I'm wrong, but the only way I found is to create a pyplug with "Export Project as Group" and then copy this Pyplug to the plugins folder of my coworker.

But my roto is definetly not a plugin and the last thing I want to do is putting single rotos or shot specific color correction in my plugin folder leading to a chaos in my tools. It just feels wrong and it is pretty inconvenient.

Solutions for this issue:
The easier one:
Under "File" add an "Import Natron Project" option which will just import the tree of another .ntp file. No other settings, just all nodes of the tree.

The even better but I think more complicated solution:
Make copy/past like in Nuke where you can just copy the node tree and past it as plan text somewhere else like an email or another Nuke instance.
At the company where I worked, we used that all the time! That was one big advantage over After effects, because one could work perfectly together. It was a matter of one copy paste to get it working in another comp.

I can imagine that the second solution will need a lot of time and effort to code. So I would be very happy to see the import feature popping up in the near future. It would make collaborative work much more fun.

Thanks in Advance,
Johannes

**Comment by MrKepzie** [comment]
Has been in the todo list for a while, not very complex at all to add in Natron

**Comment by MrKepzie** [comment]
Copy/Paste is implemented. I will add a small node also that enables loading of natron projects

**Comment by PostPollux** [comment]
Awesome! Thanks!

**Comment by MrKepzie** [comment]
it's implemented
