### ISSUE TITLE
feature request: full screen viewer

### ISSUE THREAD

**Issue by iscream75** [MrKepzie/Natron#1099]
This is a feature request
I would like to hide timeline, toolbar and tabs using one or two shortcut in the viewer (undocked). And finaly see my 1920*1080 comp in all it's glory :)

proposal :
shit+space for hiding toolbar and tabs
ctrl+space for the timline
ctrl+shift+space for both

all those shorcuts should also set the zoom level to "fit"

**Comment by MrKepzie** [comment]
Implemented for 2.2
