### ISSUE TITLE
Enhancement of the curve editor

### ISSUE THREAD

**Issue by fPaglia** [MrKepzie/Natron#110]
as proposed by Frédéric here my thought about how to improve the curve editor.
I imagine two kind of activities possible on curves:
1. one time operation
2. editable modifier

__One time operation__ are activities that modify permanently the number and position of key point of a curve.
They can be 
* move
* scale
* rotate

The first 3 activities can be done in two way (I'm just proposing here after a discussion we can end up with the preferred behavior):

selected keypoint can be surrounded by a cage to perform transformation... nothing different  than what is possible on the on screen GUI of transformation node pretty like what nuke does:

![nukecage](https://cloud.githubusercontent.com/assets/5074015/3595960/5a43ab48-0cbd-11e4-97fc-a3e4f2f63643.png)

Or we can gor for a solution like blender uses that I like really much. They have a cursor that have both dimension X and Y so you can edit entire curves or just portion of them in two ways:
* starting from the median point of the group of node
* using the cursor as origin of the transformation 
a solution like this one require the addition of keyboard shortcut to edit keypoint like G,R,S, for grabbing, rotating and scaling key point  that maybe isn't really common in a compositing tool but in my opinion this solution it's less noisy in terms of visual representation and it's much more powerful in therm of editing (I would suggest to add it on the viewer too... But I'll leave this topic for another post)  

![anim_0002](https://cloud.githubusercontent.com/assets/5074015/3596032/9baf6634-0cbe-11e4-84df-967c53888e61.png)

__editable modifier__ are activities based on some sort of scripting directly controlled by the user and are not destructive until user do not decide to bake them on the curve. 

* link of a property of another node
* timeoffset
* simplify
* math operation (randomize, sine, tan, etc etc)
* python scripts

you can refer to nuke or shake manual for a full list of useful expressions

They could be enabled/added as an extra option next to the "keyframe" in the gui  and change the color code of the input panel to show the difference.
Is could be cool to have a three color type:
* blu: keyframe only
* green: expression only
* yellow: expression over curves as modifier

Here a mockup of the GUI. 
As you can see I added the expression button and a scripteditor where to show the expression written.    
![scripteditor](https://cloud.githubusercontent.com/assets/5074015/3596315/1fb2517c-0cc3-11e4-8d50-de6f0f529040.png)

I know there could be dozen of ways to show scripts and we can even imagine a way to display more than one per time splitting the script editor in some way (I have to spend a bit more to design this sort of interface) this idea I'm showing here is working just on a single script visible at time...
 
I'm not a coder so I don't really know if expression should be multiplicative or additive... (I imagine they are multiplicative).
Since blender does exactly that kind of operation (modifiers over keyframes) you can join for a while #blendercoders on IRC to ask someone how the solved this.

About B-spline algorithm, I know Sergey Sharybin (Naz-gul on #blendercoders) has extensively worked with curve for the blender 3D tracking system and for his rotoshape maybe it can help you in someway

**Comment by MrKepzie** [comment]
Scale for the bounding box has been implemented. Rotate is not going to happen.  Expression (and predefined ones) are also available now
