### ISSUE TITLE
rendering speed vs viewing write node

### ISSUE THREAD

**Issue by iscream75** [MrKepzie/Natron#1102]
I didn't use the F7 or render button on my last project
It was way faster to cache the  last node of the tree  then to plug the write node into the viewer and hit play. 
Perhaps a threading issue or drives/cache configuration

**Comment by MrKepzie** [comment]
Interesting, I will take a look

**Comment by MrKepzie** [comment]
Can you provide a project on which we can properly reproduce this bug ? I can't seem to find any difference

**Comment by MrKepzie** [comment]
When you plug a Viewer to a Write node, the Write node will render using the zoom level (mipmap level) indicated by the viewer, hence if you playback for example with a zoom level at 44%, the mipmap level corresponding is 1 (width / 2, height / 2), hence the image rendered by the Write node will be 4 times as small.
On the other hand when you render by hitting the "Render" button, it will render at full resolution. 
I think that was the issue.

**Comment by iscream75** [comment]
But the file on disk are ok when you view the write node afaik
Le 9 janv. 2016 14:52, "Alexandre Gauthier" <notifications@github.com> a
écrit :

**Comment by iscream75** [comment]
Will try to reproduce it with a simple vraph anyway
