### ISSUE TITLE
feature request: "batch" channel renaming

### ISSUE THREAD

**Issue by iscream75** [MrKepzie/Natron#1103]
Would be great to have a node to rename all channel with a "find and replace" style parameters
ex : channels names looks like that :
scene.001.DiffCol.RGB
scene.001.IndexMA.V

I would like to enter those parameter in the node :
FIND : [scene.001.]
REPLACE WITH:[](yes empty string)

This way all gizmo would continue to work if for exemple I render a scene.002

**Comment by MrKepzie** [comment]
You can do that with a shuffle node or in fact any node with the Output Layer drop-down. You just create a new layer and pipe into it whatever source layer you want. 
Currently there's no way to remove channels, I will add a remove channel node for that purpose.

**Comment by iscream75** [comment]
I use shuffles but if the channel's name prefix change you have to re set
all shuffles

http://www.pasteall.org/pic/show.php?id=96724.

kevin

**Comment by MrKepzie** [comment]
Will try to add a ChannelRename and ChannelRemove nodes

**Comment by devernay** [comment]
This issue was moved to NatronGitHub/Natron#133
