### ISSUE TITLE
Bug reader avi 

### ISSUE THREAD

**Issue by openvet** [MrKepzie/Natron#1105]
Bonjour

J'ai découvert natron il y a quelques semaines, c'est un logiciel extraordinaire, mais j'ai eu de gros problèmes pour lire certaines vidéos (même après réencodage) alors que ça marchait avec d'autres.
Je crois avoir trouvé, les dossiers avec des espaces posent problème à la lecture (en tout cas sous linux, manjaro). Le même fichier à la racine est bien lu.
Petit bug mais je me suis arraché les cheveux pour comprendre.

Cordialement.
YP

**Comment by MrKepzie** [comment]
Peux tu nous envoyer un exemple de fichier que tu n'arrives pas à lire ? Tu peux nous l'envoyer en privé par message sur le forum (forum.natron.fr).

**Comment by openvet** [comment]
Bonjour

Désolé de la réponse tardive je n'avais pas vu ton message.
Je vais essayer d'envoyer mon fichier en privé, par contre ce qui pose problème ce ne sont pas les espaces dans les dossier comme je le pensais mais les caractères accentués (mon dossier avait à la fois des espaces et des caractères accentués). 
Toujours besoin de mon fichier?

Cordialement
YP

**Comment by MrKepzie** [comment]
Oui tu peux nous l'envoyer a alexandre dot gauthier-foichat at inria dot fr

**Comment by olear** [comment]
Still an issue? Spaces and accented characters works here on video and images.

**Comment by openvet** [comment]
Bonjour

Oui, toujours le même problème avec la dernière version de Natron : 
https://www.dropbox.com/s/no2o6n48p0a6zmu/Screenshot_20160308_102740.png?dl=0
Mais ce n'est pas très gênant, j'évite les accents dans les noms de dossiers.

Cordialement
YP

**Comment by olear** [comment]
Strange, screenshot from latest snapshot on CentOS7:
![natron-chars](https://cloud.githubusercontent.com/assets/7461595/13597781/95ff707c-e51a-11e5-802a-f4362207df2b.png)

What Linux distro and version are you using?

**Comment by openvet** [comment]
DISTRIB_ID=ManjaroLinux
DISTRIB_RELEASE=15.12
DISTRIB_CODENAME=Capella
DISTRIB_DESCRIPTION="Manjaro Linux"

Manjaro (Linux.4.1.18-2-Manjaro)
KDE 4.14.17


J'ai testé sous ubuntu (14.10 LTS) c'est ok : 
https://www.dropbox.com/s/no2o6n48p0a6zmu/Screenshot_20160308_102740.png?dl=0

**Comment by olear** [comment]
I think this is a locale issue, and related to http://forum.natron.fr/t/solved-file-names-with-national-characters/525/23 , since Manjaro is based on ArchLinux.

What's the output of: 
`cat /etc/locale.gen | sed '/#/d'`

**Comment by openvet** [comment]
fr_FR.UTF-8 UTF-8

**Comment by olear** [comment]
Adding US will probably fix it:

```
sudo sed -i 's/#en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen
sudo locale-gen
```
The start Natron.

**Comment by openvet** [comment]
oui, ça marche.
merci.
YP
