### ISSUE TITLE
AngleBlur Issue

### ISSUE THREAD

**Issue by PostPollux** [MrKepzie/Natron#1106]
The AngleBlur PyPlug is a bit buggy. The center of its second transform node should be the same as the one of the first transform node.

Further more the Viewport stops to update as soon as I changed the "distance" value of the PyPlug. Then it only updates if I pan or zoom in the viewer like what I'm doing at the end of the video.

https://goo.gl/photos/z652TVUGjR5hFMwSA

**Comment by MrKepzie** [comment]
This is not related to angle blur, just a mistake in  yesterday change

**Comment by PostPollux** [comment]
Thanks. I tested your fix and the update in the viewport works fine again!

But the first Issue I mentioned is still there and I think it is related to the angleBlur PyPlug. You can see it at the beginning of the video. If I change the angle the whole image is rotating around and moving outside the format. I think the image should stay where it is while changing the angle. As I mentioned in the post above, I think it's the second Transform node of the pyplug where the "center" value is wrong.
