### ISSUE TITLE
PyPlug Expression Issue

### ISSUE THREAD

**Issue by PostPollux** [MrKepzie/Natron#1108]
I'm working on a "glow" PyPlug right now and I'm almost finished! I'll send it over as soon, as I'm done so you can add it, if you want.

While creating it I found another bug:
If you try to drag and drop a parameter from one node to another inside a group the creation of the expression fails. But it works, if you do it manually.
https://goo.gl/photos/FWqcfGueuR4LMVuM8

At the moment there is only one issue left to finalize the PyPlug. What I need is to script the center of a transform node to be in the center of the input RoD/Format. Is there a way to get the size of an input in an expression? I tried everything but I can't get access to it. Another but not as good solution would be to pick and add the "reset center" button of the transform node to the PyPlug. But when I try to do this, I can't find this button to add to the user params.

**Comment by MrKepzie** [comment]
You need to implement the onInputChanged callback and set it on your PyPlug:

http://natron.readthedocs.org/en/workshop/callbacks.html#the-after-input-changed-callback <http://natron.readthedocs.org/en/workshop/callbacks.html#the-after-input-changed-callback>

You would need to add the hand-written code, as explained in

http://natron.readthedocs.org/en/workshop/groups.html#adding-hand-written-code-callbacks-etc

**Comment by MrKepzie** [comment]
fixed
