### ISSUE TITLE
Feature Request: Krita Animation Plugin

### ISSUE THREAD

**Issue by mamarilmanson** [MrKepzie/Natron#1109]
Hello... If anyone is aware... Krita now supports animation... 

I would like to request for a feature where krita files can be imported to natron for it to be composited here... I got the idea from the Toon Boom animation apps... 

I hope you can get what I am saying... :D

**Comment by olear** [comment]
Can't find any specs on .kra files anywhere, please post.

Btw, I'm adding support for OpenRaster (.ora), but don't know if that helps (not tested anim in Krita). Initial OpenRaster support will just be pure images with layer support.

**Comment by mamarilmanson** [comment]
@olear ~ I'm not familiar regarding your words "specs on .kra files..." I apologize... please do enlighten me... :)

**Comment by olear** [comment]
Just information regarding how to read the KRA files from Krita. Will postpone this until Krita v3 get stable, and I understand how to read the files properly.

**Comment by mamarilmanson** [comment]
ohhh... ok thank you... 

if this post was opened and put into enhancement... then this might get a chance? :)

**Comment by olear** [comment]
Krita 3.0 supports exporting an image sequence, so I don't see the need for this plugin. We already supports KRA files and that should be enough.

**Comment by devernay** [comment]
This issue was moved to NatronGitHub/Natron#134
