### ISSUE TITLE
enancement for keypoint editing via 2d cursor

### ISSUE THREAD

**Issue by fPaglia** [MrKepzie/Natron#111]
I'd like to introduce **the concept of a "2D cursor"**
I don't now if this idea could fit in the actual design but I think it can be a great addition for speed seriously up keypoint editing of shapes in the roto editor as well as in each other editor that have the same kind of operand like future morphing and warping tools or anything else that can arise 

I derived this idea from Blender 3D/2D cursors... so I'm not reinventing the wheel here.
the Cursor is a spare pivot that can be used as center for each transformation.
It's incredibly powerful because you can just move it wherever you like to quickly rotate or scale group of point of your interest.
If you are used to do huge rotoscoping session with lot of human movements you'll understand how such kind of ability would simply reduce the editing time for fine tuning the shapes. In my experience with many compo tools I found incredibly fast the way shake allowed us to switch the position of its center to do the previously mentioned transformation.
It had just a minor issue using the center that way: since the center is still an element of the shape not just an external support you couldn't use a shape animated that way parented to another shape because of the not usability of its reference.

**Why promoting a tool like a 2D cursor** instead of a transform cage with it's own editable center?
Here my reasons:
1. **visually cleaner** : cage are always too visually heavy and add noise in the viewer, sometime moving the center is difficult and this happen even more when you are next to an anchor of the cage 
2. **more precise** : you can place the cursor anywhere even before you make your shape and you could edit it without taking care of is previous position
3. **independent from the selection**: it stays on the chosen position even if nothing is selected, so you don't have to re adapt it  each time you make a selection (this allow a tremendously faster and way more efficient workflow) 

Three element that in my opinion are really valuable.  

**How to handle the 2D cursor**
2D cursor can just be enabled as an other option on the menu.
![roto01](https://cloud.githubusercontent.com/assets/5074015/3610459/818172b0-0d8c-11e4-9ac4-adf8ae438c56.png)
As soon as it is enabled it becomes the active center of transformations.
It can be positioned clicking CTRL+leftClick

selection of keypoint is as always done via a border select or clicking directly on single keypoint, 
- SHIFT + leftclick add keypoint to the selection
- ALT + leftclick remove keypoint to the selection
- L (hit once) can be a lazo selection (SHIFT and ALT as always add and remove element from the selection)
- G (hit once) move entire shape or selected keypoints
- S (hit once) scale entire shape or selected keypoints
- R (hit once) rotate entire shape or selected keypoints

distance between 2D cursor and mouse is relevant since it can change the sensibility of the scale or rotation (smaller distance produces bigger variation and viceversa)

once activated G,S,R:
- leftClick apply the transformations, 
- rightClick discard the transformations 
  while a transformation is active 
- SHIFT reduce the factor of trasformation of 1/10
- ALT increase the facto of transformation of 10
- X restrict x axis operation (G,S only)
- Y restrict y axis operation (G,S only)

As you can see I'm not saying to remove the cage transform it's still useful for many purpose: first of all is the ability to edit shape's transformation in the curve editor or future dopesheet.
My idea is an extra element that will be a companion tool to work specifically on keypoints in a more efficient manner.

Hope you find my idea intresting.
Thanks 
Francesco

**Comment by devernay** [comment]
This issue was moved to NatronGitHub/Natron#78
