### ISSUE TITLE
Natron snapshot freeze ...

### ISSUE THREAD

**Issue by rcspam** [MrKepzie/Natron#1111]
Natron freeze on the splash screen when i open a former ntp file from this summer create with snapshot.
I often open this project without change, just to verify that it loads. Is this a bug or something has change in the ntp format ?
![selection_001](https://cloud.githubusercontent.com/assets/10021906/12005699/bd229684-abb3-11e5-8ecc-3127b8f8277c.png)

**Comment by MrKepzie** [comment]
Please attach a sample to reproduce the bug

**Comment by rcspam** [comment]
In fact, after having dig, 'error windows' are hide by the splash screen. Perhaps can you find a way to stop the splash screen before show the error windows
![error log_001](https://cloud.githubusercontent.com/assets/10021906/12017632/b5b17576-ad59-11e5-89be-b4e5f39952dc.png)
