### ISSUE TITLE
PyPlug Pick buttons

### ISSUE THREAD

**Issue by PostPollux** [MrKepzie/Natron#1113]
It is possible to add buttons to the group user parameters. But it seems not to be possible to pick buttons from nodes contained in the PyPlug/group.

For example: 
"Reset Center" in the transform node
"Analyze Frame" in Image Statistics node
...

 Adding it would be great. Thanks!

**Comment by MrKepzie** [comment]
You could just create a parameter and set in the onParamChanged callback a call to the trigger() function of the original button
