### ISSUE TITLE
problème avec le rotoPaint node

### ISSUE THREAD

**Issue by pitiTutur** [MrKepzie/Natron#1115]
Salut ! J'utilise la version Linux v2.0.0-64bits6-RC5 et j'ai différents soucis avec mes RotoPaint nodes qui semblent faire de liens étranges entre eux (l'un des nodes récupère l'alpha d'un autre sur quelques images de la séquence).
Et finalement, lors d'un export test avec le ffmpeg writer, j'ai cette erreur (j'ai des "unkown errors" avec les autres writers) :

Starting background rendering: /home/tutur/Natron2/bin/Natron -b -w WriteFFmpeg3 --IPCpipe "" "/home/tutur/.local/share/INRIA/Natron/Autosaves/RENDER_SAVE.ntp" Message(stdout): Natron Version 2.0.0
Copyright (C) 2015 the Natron developers
>>>Use the --help or -h option to print usage.<<<
Message(stdout): Restoring the image cache...
Restoring user settings...
Message(stdout): init.py script not loaded
Message(stdout): Loading PyPlugs...
Error(stderr): Traceback (most recent call last):
  File "<string>", line 2, in <module>
Error(stderr):   File "/home/tutur/Natron2/Plugins/PySide/__init__.py", line 41, in <module>
Error(stderr):     _setupQtDirectories()
  File "/home/tutur/Natron2/Plugins/PySide/__init__.py", line 9, in _setupQtDirectories
    from . import _utils
ValueError: Error(stderr): Attempted relative import in non-package
Message(stdout): ERROR: Error while creating node: Error while creating node fr.inria.built-in.RotoPaint: RotoDrawableItem::createNodes
Message(stdout): ERROR: Error while creating node: Error while creating node fr.inria.built-in.RotoPaint: RotoDrawableItem::createNodes
Message(stdout): ERROR: Error while creating node: Error while creating node fr.inria.built-in.RotoPaint: RotoDrawableItem::createNodes
Message(stdout): Rendering started
Message(stdout): No input to render
No input to render
Message(stdout): Rendering finished

Voilà. Merci beaucoup !

**Comment by MrKepzie** [comment]
Ce bug a été résolu il y a quelques jours ici : https://github.com/MrKepzie/Natron/issues/1084

**Comment by pitiTutur** [comment]
Euh, ben, sauf que j'ai encore le bug alors que je viens de réinstaller Natron.
Error while creating node fr.inria.built-in.RotoPaint: RotoDrawableItem::createNodes

**Comment by MrKepzie** [comment]
La mise à jour n'a pas été propagée à la version RC5, elle sera disponible dans la prochaine version. Le fix est pour le moment disponible dans les [snapshots.](http://natron.fr/snapshots/)

Concernant le second bug, c'est parce que tu as un fichier **init.py** ici: 

    /home/tutur/Natron2/Plugins/PySide/init.py

Or comme PySide est déjà un package python avec un fichier __init__.py , ca fait planter la chargement. Merci de déplacer le fichier init.py ailleurs, comme indiqué ici: http://natron.readthedocs.org/en/workshop/startupscripts.html

**Comment by pitiTutur** [comment]
Ah, ok. Merci beaucoup !
