### ISSUE TITLE
feature req: input/ouput(s) node seen by precomp nodes

### ISSUE THREAD

**Issue by iscream75** [MrKepzie/Natron#1116]
Same as for nodegroup

**Comment by MrKepzie** [comment]
Pre comp do not allow you to edit the underlying project "in-place". You have to press the "Edit.." button to edit it in another instance. Allowing you to edit it in the current natron instance would be a bit confusing as to what is the current state of that project, especially if 2 persons are using it at the time.

Furthermore, the pre comp is expected to be "Render-out" only, it does not take any parameter in input: it just reads the images produced by the project with the specified Write node. 

There's an alternative mode into which you do not read what was rendered by the Write node but where you connect your tree directly to the desired node when you uncheck "Pre-render". In this case you can access all the layers coming directly from these nodes as internally the nodes are linked together. 

While you can choose which node to output, it doesn't mean you can change the layout of the graph inside.
