### ISSUE TITLE
Natron freezes on changing sliders in Group/Pyplug

### ISSUE THREAD

**Issue by PostPollux** [MrKepzie/Natron#1120]
For some reason Natron always freezes since todays update as soon as I play a bit with the sliders of a userparameter of my group. It doesn't shut down, it just freezes until you kill the task (I waited several minutes, but it was still frozen).
That also happens when I insert my finished Unspill PyPlug and change a slider there. Before the update it worked fine.

**Comment by MrKepzie** [comment]
Can you provide a project on which to reproduce the bug ?

**Comment by PostPollux** [comment]
Ok, here's a test file. Just try to change any slider in the "glow" group. It freezes immediately. Yesterday it worked fine and I didn't change anything on that group.
[BugTestFile.zip](https://github.com/MrKepzie/Natron/files/73350/BugTestFile.zip)
