### ISSUE TITLE
adding a separator causes file corruption

### ISSUE THREAD

**Issue by PostPollux** [MrKepzie/Natron#1128]
If I add a separator to any User parameters and save the project afterwards, the file is corrupted and can not be opend again.  The Error popping up: "Error while loading project input stream error".

To reproduce just start natron, create a group, add a separator to the user params, save the file and reload.

There is also a problem when I export a plugin containing a seperator. When I then want to add the plugin, there is also an error:

While executing script:
Unspill.createInstance(app1, app1.Unspill1)
Python error:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/johannes/Natron2/Plugins/PyPlugs/Unspill.py", line 185, in createInstance
    lastNode.controls.addParam(param)
UnboundLocalError: local variable 'param' referenced before assignment

I guess it's the same problem...

**Comment by PostPollux** [comment]
Ok, the file opens again! Thanks. But if I export the plugin and try to use it in any comp there is still this error message and the node is not being created:

While executing script:
Unspill.createInstance(app1, app1.Unspill1)
Python error:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/johannes/Natron2/Plugins/PyPlugs/Unspill.py", line 185, in createInstance
    lastNode.controls.addParam(param)
UnboundLocalError: local variable 'param' referenced before assignment

Here's the pyplug. You can copy it in your PyPlugs folder and try to add it. It's the same as a few days ago. The only thing I changed is that I added two separators...
[Unspill.zip](https://github.com/MrKepzie/Natron/files/76585/Unspill.zip)

**Comment by MrKepzie** [comment]
I have fixed it, I forgot to implement the Python bindings side

**Comment by MrKepzie** [comment]
btw you have to re-export it to make it work
