### ISSUE TITLE
color.rga

### ISSUE THREAD

**Issue by iscream75** [MrKepzie/Natron#1131]
Color.RGBA does not exist by defaut or is not listed by shuffle node in the ouput channel available

**Comment by MrKepzie** [comment]
It's called RGBA

**Comment by iscream75** [comment]
OK but there's not RGBA either

![bug](https://cloud.githubusercontent.com/assets/16254684/12167256/62f718ca-b52b-11e5-9f27-63a7362a1c51.jpg)

**Comment by MrKepzie** [comment]
That's because the input to your Shuffle node only has Alpha. 
The color plane can have 3 different values:
RGBA, RGB or Alpha
Maybe we should make it clearer, like Color.RGBA, Color.RGB, Color.Alpha

**Comment by MrKepzie** [comment]
It's been renamed now, wait for the next snapshot
