### ISSUE TITLE
ReadFFmpeg is problem? 2.0-RC5, images sequences PNG..

### ISSUE THREAD

**Issue by manuelsongokuh** [MrKepzie/Natron#1132]
i did converted in png sequences + deinterlaced from MXF footage.

have 2 problems:
1- readffmpeg node is problem?
read node is OK

2- error message...??

see screen record:
http://sendvid.com/b238cnnb

nothing error from terminal..

version:
 8d6d99c37007652f5c256bae330d931d0a4bf460

**Comment by olear** [comment]
Don't use ReadFFmpeg on a image sequence, use ReadOIIO.

**Comment by manuelsongokuh** [comment]
ok, I did not know this. thank you

**Comment by manuelsongokuh** [comment]
for message error,it's normal?

**Comment by manuelsongokuh** [comment]
hi

i think it is possiblw to disable png sequence for node readFFmpeg or warn message error" this images sequence is not good with readFFmpeg and to use read (OIIO)" ?
