### ISSUE TITLE
Shuffle in a PyPlug looses channels

### ISSUE THREAD

**Issue by PostPollux** [MrKepzie/Natron#1134]
A Shuffle Node in a PyPlug seems to loose its specified OutputChannels when it is created. In the PyPlug file they are correct. 
Furthermore Natron just shuts down as soon as I disable the shuffle node! (That's what I'm doing at the end of the Video)
https://goo.gl/photos/DZPqZBJd4Eo8xGos6

**Comment by MrKepzie** [comment]
This was fixed by https://github.com/devernay/openfx-misc/commit/15a54f114bbab5e01523173a829ca882bd5cf62f
