### ISSUE TITLE
Windows Setup problem extracting python stuff

### ISSUE THREAD

**Issue by Chris-R-R** [MrKepzie/Natron#1136]
Several Installer error messages shown installing Natron-2.0.0-RC5-Windows-x86_64bit-setup.exe on Windows 10 64-bit.

For example - 
"Error during installation process (fr.inria.natron.libs);
Error while extracting 'installer://fr.inria.natron.libs/2.0.0lib.7z': Could not open file: C:/Program Files/INRIA/Natron-2.0.0-RC5/lib/python2.7/idlelib/idle_test/test_io.pyc (Unknown error)"

Pressing retry allowed the setup to continue. There were 3 or 4 similar messages shown during installation.
![natronsetup](https://cloud.githubusercontent.com/assets/16574241/12140418/0c2bbab4-b468-11e5-9b41-34bf8bdcf644.png)

**Comment by MrKepzie** [comment]
Try running as admin the installer

**Comment by olear** [comment]
The installer/updater must be run as administrator, but for some reason we are not able to force this, so the only way is to right click and select "run as administrator..."

**Comment by Chris-R-R** [comment]
The uninstaller also appears to have left some stuff behind. I will try "run as administrator" but on the previous attempt I was shown the UAC elevation prompt so I would have expected the installer to be running in the correct context.

**Comment by olear** [comment]
Yeah, but the UAC elevation don't work as it should, and some parts of the install/update gets broken.

We don't remove the directory with Natron, since the user could select a non-standard location and wipe the disk if not careful.

**Comment by Chris-R-R** [comment]
Ok, I can confirm that after manually deleting the stuff left behind from the uninstall and running the setup again with "Run as administrator" works ok.
I initially tried running setup again straight after uninstalling but the setup program then complained about the stuff left behind by the uninstall. It would seem that reinstalling to the same location is not possible without manually cleaning up after the uninstall (see picture below).

![natron2](https://cloud.githubusercontent.com/assets/16574241/12141991/cfbda300-b474-11e5-84a1-6a950fa538f2.png)

**Comment by olear** [comment]
Yeah, known issue. Will try to fix this, but we are using third-party software for the installer, so not always easy to fix.

**Comment by Chris-R-R** [comment]
Ok, thanks for the quick reply. Closing the issue now.

**Comment by olear** [comment]
The installer/updater now defaults to admin (no more extraction issues), will be available in next RC/snapshot.

Uninstall still won't delete all files (to avoid users deleting more than they should if not installed in Program Files), so users must manually delete the folder after uninstall (but why would you uninstall Natron ;) ).
