### ISSUE TITLE
Side by side (Stereoscopy) Node extra function

### ISSUE THREAD

**Issue by sirdavid32** [MrKepzie/Natron#1146]
Hello, I was trying to get a side by side image by using the Side by Side node, and I´d like to suggest that this node should create on the same compo size originally, by squeezing each view (left and right) by exactly half of its value.

I example: I´m working in a 1280x720 composition. I bring my left and right view and connect it to my side by side and I (currently) get on Natron a bigger compo (1280 x 2 = 2560).
Consider, adding an option to squeeze both images by half it´s size to fit original compo size.
1280 / 2 = 640 pixels for the left, and 640 pixels for the right; please. :+1: 

So in the end, both will fit in the original compositing size of : 1280 pixels wide (by 720 in the pictures).
Thanks.

![directly](https://cloud.githubusercontent.com/assets/11066585/12225046/ae028d4a-b7ce-11e5-9a52-433d0d9b99c7.png)
![side](https://cloud.githubusercontent.com/assets/11066585/12225045/ae01bd8e-b7ce-11e5-8b16-ea331b08de9c.png)

**Comment by sirdavid32** [comment]
I know this can be worked out by nodes, but it would be really handy that it would do it automatically by selecting an option like "fit both views on the same compo width ( ) or height ( )" check box.

**Comment by devernay** [comment]
We wont fix this: the correct way is to simply  use a Reformat node after the SidebySide node.
SidebySide should not resample the images. Reformat has all the resampling options.
