### ISSUE TITLE
Seexpr node disappeard

### ISSUE THREAD

**Issue by PostPollux** [MrKepzie/Natron#1150]
The Seexpr Node is gone at 545a5b4.
Sorry if it's not a bug and you did it because of developing reasons. But I just noticed it and thought I'll let you know.

**Comment by olear** [comment]
Try to reload/clear plugin cache.

**Comment by PostPollux** [comment]
Didn't change anything. Still gone.

**Comment by olear** [comment]
was a small bug, will be fixed in next snapshot.
