### ISSUE TITLE
Hovering info disappears

### ISSUE THREAD

**Issue by PostPollux** [MrKepzie/Natron#1151]
A small and not so important one:
The info when hovering over the lock icon of a PyPlug disappears very quick. It's not possible to read it. It seems to behave other then the rest of the hover infos. It stays there as long as you are moving your mouse, but disappears shortly after you stop to move your mouse. The other ones all stay as long as your cursor rests on the param, button, whatever...

https://goo.gl/photos/yDxKiuMf8zYz8w4q6

**Comment by devernay** [comment]
This issue was moved to NatronGitHub/Natron#136
