### ISSUE TITLE
enable node don't propagate inside group

### ISSUE THREAD

**Issue by iscream75** [MrKepzie/Natron#1153]
while disabling a node with "d" shortcut effectively disable nodes inside groups, pressing "d" again only re enable the parent group but not child nodes

**Comment by MrKepzie** [comment]
Can you post a screencast or screenshot to illustrate? I do not understand how to reproduce

**Comment by iscream75** [comment]
https://hangouts.google.com/call/v2nidmzaom7mbpl2vmlajcq3jaa

kevin

**Comment by iscream75** [comment]
select some nodes
create a group with ctrl+shift + g
disable the group with "D"
copy past the group
enable the new group with "D"
the new group don't work
Edit the new group in a new tab  to see all nodes inside it are disabled
