### ISSUE TITLE
Resize node loose parameters

### ISSUE THREAD

**Issue by iscream75** [MrKepzie/Natron#1154]
resize node loose its parameter randomly

**Comment by MrKepzie** [comment]
It's not random, it's whenever you change the input connection

**Comment by iscream75** [comment]
ok, still a bug I think

**Comment by MrKepzie** [comment]
Then please provide steps to reproduce

**Comment by iscream75** [comment]
create two node (read for ex)
add a resize node to the first one
set parameter to scale
enter some value ex:0.5 / 0.5
drag the resize input arrow from the first grade to the second one

parameter is reset to scale

it also happen if you delete le node above the resize in a bigger graph

kevin

**Comment by MrKepzie** [comment]
It has been fixed, note that the Resize node is now deprecated and you should use the Reformat node instead
