### ISSUE TITLE
Unable to use expressions in the 2nd level group

### ISSUE THREAD

**Issue by devrnd** [MrKepzie/Natron#1158]
I'm trying to link a parameter to 'SeExpr'-Node in the group, which is in another group, but i'm getting:

    ERROR: While executing script:
    ret = app1.Group1.Group1.Constant1.color.expression0(1)
    Python error:
    Traceback (most recent call last):
        File "<string>", line 1, in <module>
        File "<string>", line 10, in expression0
    NameError: global name 'Group1' is not defined
However it works fine in the 0th & 1st level group.
http://snag.gy/TNzMw.jpg

**Comment by MrKepzie** [comment]
Here it works well, I cannot reproduce the bug

**Comment by devrnd** [comment]
Wow, pretty fast. Thanks a lot!
