### ISSUE TITLE
Linux: add ntp to mimeapps

### ISSUE THREAD

**Issue by manuelsongokuh** [MrKepzie/Natron#1159]
hi
install natron2 and missed for mime types for *.NTP

so i added manually:
1-
go to path 
~/.local/share/applications/mimeapps.list
add line:
application/ntp+xml=Natron-2.desktop;
save and close.

2-
create file txt (kwrite or kate)

--------------
[Desktop Entry]
Exec=/home/~user~/Natron2/Natron
MimeType=application/ntp+xml;
Name=Natron
NoDisplay=true
Type=Application

---------------

save name: Natron-2.desktop

logout kde4 and login, worked!

but this is manually..
is it possible automatic  duration installation of Natron 2?

**Comment by manuelsongokuh** [comment]
thank you!

**Comment by manuelsongokuh** [comment]
sorry, i tested this mime type but not work 100%, worked 50%..
i did ask team kde see this link for natron ntp:
https://forum.kde.org/viewtopic.php?f=225&t=130593&p=349588#p349588

maybe that you write in code: x-natron.xml   i dont know: this is work..?

i tested version natron:
9b20cf9f992b8d22539301608d034a40995d5863

that ~/.local is worked than /usr/share/mime  but i'm not sure.. you can check it ok?

**Comment by manuelsongokuh** [comment]
maybe will be worked code:
(my case)
```
<?xml version="1.0" encoding="utf-8"?>
<mime-type xmlns="http://www.freedesktop.org/standards/shared-mime-info" type="application/ntp+xml">
  <!--Created automatically by update-mime-database. DO NOT EDIT!-->
  <comment>Natron Project File</comment>
  <icon name="/home/gokuh/.local/share/icons/natronIcon256_linux.png"/>
  <glob-deleteall/>
  <glob pattern="*.ntp"/>
</mime-type>
```

can change 
```
<icon name="~/.local/share/icons/natronIcon256_linux.png"/>
```

i'm not programmer, you can idea ok?

**Comment by manuelsongokuh** [comment]
i tested: that ~/.local/share/mime/package is not worked for me kde4
so i delete ~/.local/share/mime/package/x-natron.xml
i add ~/.local/share/applications/mimeapps.list:
```
application/ntp+xml=Natron2.desktop;
```

and create kwrite:
```
[Desktop Entry]
Comment=Node-graph based compositing software
Exec=/home/gokuh/Natron2/Natron %U
GenericName=Compositing software
MimeType=application/ntp+xml;
Name=Natron2
Categories=Graphics;2DGraphics;RasterGraphics;
Type=Application
Icon=natronIcon256_linux
Version=1.0
Terminal=false
```

save name "Natron2.desktop"
this is worked as fine for kde4..

that /.local/share/mime/package is for gnome?...i dont know..
so i use this ~/.local/share/applications/mimeapps.list worked as fine..

i hope there is other solution for all distros..
good nite

**Comment by olear** [comment]
The installer didn't update the desktop database, so Natron didn't launch in Nautilus, that is now fixed. KDE4 worked with my last commit, don't know why you have problems, probably a conflict from your modifications.

I tested Ubuntu/Fedora/CentOS with Unity/GNOME3/KDE4.

**Comment by manuelsongokuh** [comment]
ah ok i will test other partition opensuse 42.1 kde5, that i did not modifications.
opensuse 13.2 maybe it conflict my manually and installer natron.
i will do test and i will back here for feedback update ok?

**Comment by manuelsongokuh** [comment]
i did tested, opensuse 42.1 leap kde5, worked as FINE with natron installer..

so my opensuse 12.3 is conflit maybe i do bad config.. but FINE ok? finally close issue
thank you and thank to team natron for developing natron!
