### ISSUE TITLE
Enhancement: Extrapolations for Curve Editor

### ISSUE THREAD

**Issue by mifth** [MrKepzie/Natron#116]
Hello guys.

Blender has extrapolations to repeat one animation constantly or linearly. It would be very useful to have such a feature in Natron.

Here is explanation: http://i.imgur.com/DwLRNK3.png

You can test it in Blender Curve editor too. Just open Curve editor and press Shift+E in blender.

**Comment by MrKepzie** [comment]
We have implemented Loop/Negate/Reverse , and possibly you can extend it by writing your custom expression like in Nuke.
