### ISSUE TITLE
ReadOIIO not found

### ISSUE THREAD

**Issue by iscream75** [MrKepzie/Natron#1160]
When opening an existing comp with "2016-Jan-18 09:44:01" natron snapshot I've got this error :

ERROR: The node fr.inria.openfx.ReadOIIO version 2.0 was found in the script but does not exist in the loaded plug-ins.

then natron crash

**Comment by olear** [comment]
Did you clean the plugin cache? Also note that today's Linux snapshots are buggy due to crash reporter changes, so you should revert to an earlier build while we fix things.

**Comment by iscream75** [comment]
Plugin cache cleared and I'm on Windows.
Le 18 janv. 2016 11:24, "Ole-André Rodlie" <notifications@github.com> a
écrit :

**Comment by olear** [comment]
There may be issues on the Windows build as well.

**Comment by MrKepzie** [comment]
Gonna be fix in the next snapshots. We are working on updating the build servers, that's what is causing the troubles

**Comment by iscream75** [comment]
Thx
Le 19 janv. 2016 11:51, "Alexandre Gauthier" <notifications@github.com> a
écrit :
