### ISSUE TITLE
ReadPSD - XCF layers names

### ISSUE THREAD

**Issue by blackearth2014** [MrKepzie/Natron#1164]
ReadPSD - XCF layers names are not translated or read on import in to Natron.
![xcf file layers notranslate](https://cloud.githubusercontent.com/assets/7956901/12563182/f211a71a-c376-11e5-9946-d104b1bf4935.png)

**Comment by olear** [comment]
Confirmed in GIMP 2.8, will try to find out why (they may have changed something compared to older versions)

**Comment by blackearth2014** [comment]
Cool Breeze.

**Comment by olear** [comment]
Added upstream fix for layer name, note that the background layer (first layer) still don't have a name, upstream (IM) is aware of this, I will apply patch when/if they fix it.
