### ISSUE TITLE
Reformat Node: Size Type Issue

### ISSUE THREAD

**Issue by blackearth2014** [MrKepzie/Natron#1165]
The X & Y frame dimensions under the Size type in the format node are performing in reverse. The X is controlling the Frame Height and the Y is controlling the Width. My foreground image is 2100*1500. he reformat node in the size type is reversed. See attached image for reference.

![reformatte node - type bug](https://cloud.githubusercontent.com/assets/7956901/12574094/ac058afe-c3ce-11e5-9278-81a2ee4f11c2.png)

**Comment by devernay** [comment]
also, the origin of the output of reformat should always be (0,0)

**Comment by devernay** [comment]
Rewrote the Reformat node from scratch, to get the same behavior as in Nuke
@blackearth2014 please add a comment if anything is wrong.

**Comment by devernay** [comment]
closed by https://github.com/devernay/openfx-misc/commit/f39a3f1e11a792a43ae053b057b665cef0f6b92c

**Comment by blackearth2014** [comment]
I can't test the rewritten reformat node because there must have been a serious build issue on the Mac. I can't load a Jpeg or PNG file.

![reformat - no loading of formats](https://cloud.githubusercontent.com/assets/7956901/12679860/78d3e010-c674-11e5-9237-cebea0eb78f9.png)
