### ISSUE TITLE
Natron Snapshots: Missing Read, SeGrain and other Nodes

### ISSUE THREAD

**Issue by blackearth2014** [MrKepzie/Natron#1168]
These were the snaps that are having issues with reading JPG and PNG files on my Mac.

Natron-201601281129-e637e6a46bb30908677dc9782c006a592a07d671.dmg
Natron-201601281411-a0033ae73e7c8566c744eefb6003b9cd822dea75.dmg
Natron-201601281717-a72bfd3c61e99e21d2be4f361443fa81f5b3d6a8

**Comment by olear** [comment]
Works in latest build (RC6).

**Comment by blackearth2014** [comment]
When can I go public on NatronNation about this?

**Comment by olear** [comment]
RC6 has been delayed until tomorrow. We had issues on Windows that had to be resolved, and due to network issues in-house, we can't upload the builds until tomorrow.

**Comment by blackearth2014** [comment]
Cool Breeze
