### ISSUE TITLE
Feature: External monitor support with scale 1:1 reproduction and stereo support

### ISSUE THREAD

**Issue by devernay** [MrKepzie/Natron#1172]
When using an external monitor, it would be nice to have a viewer that runs on an external display, with stereo3D support (see http://libgls.sourceforge.net/ )

This viewer could be a clone of one of the viewers in the main GUI, so that we could use the GUI in the main GUI to modify what is displayed on the external monitor (wipe, gain, colorspace, etc)

We should make sure to be able to get pixel-perfect 1:1 reproduction (to test it, display an image with a checkerboard pattern, it should exactly give black and white pixels, no grey)

This issue is related to https://github.com/MrKepzie/Natron/issues/32 , which is for broadcast format (HD-SDI) output hardware.

**Comment by blackearth2014** [comment]
This is great, but will it require purchasing a piece of hardware from companies like AJA and BlackMagic? Or, will a video card with dual GPU connection be suffice.

**Comment by devernay** [comment]
A graphics card with at least 2 outputs will suffice.

**Comment by blackearth2014** [comment]
I have two computers with dual outputs ability. When will this option be available, by version 2.0.

**Comment by devernay** [comment]
This issue was moved to NatronGitHub/Natron#139
