### ISSUE TITLE
NodeGraph zoom issue

### ISSUE THREAD

**Issue by PostPollux** [MrKepzie/Natron#1173]
When I zoom out in the nodegraph, the zoom doesn't stick to the cursor sometimes and the nodes begin to jump away.
Here's a video to illustrate:
https://goo.gl/photos/tHp7T1aKhH3HEn4d9
The only thing I'm doing is zooming out with the mousewheel...

**Comment by MrKepzie** [comment]
This is a known bug and is linked to https://github.com/MrKepzie/Natron/issues/815 
We will solve it by porting the node graph to OpenGL soon
