### ISSUE TITLE
DNX_HD : frame rate condition on writeffmpeg

### ISSUE THREAD

**Issue by edouardchalaron** [MrKepzie/Natron#1174]
Exporting to DNXHD : frame rate can be anything and not restricted only to 24, 25 or 30

**ffmpeg Code to convert a folder of TIff into DNX 10 bits**
Input Tiff are rgb48le, in this case

ffmpeg -vcodec tiff -r 18 -i pict-%010d.tiff -b:v 185000k -pix_fmt yuv422p10 -vcodec dnxhd -threads 4 -r 18 ../R02.mov

Cheers

**Comment by devernay** [comment]
ok we'll look into it

**Comment by edouardchalaron** [comment]
Thanks a lot
