### ISSUE TITLE
Export TIFF 10,12,16 bits

### ISSUE THREAD

**Issue by edouardchalaron** [MrKepzie/Natron#1175]
Writing TIFF files sequence fails to assign proper bit depth value
8 bits return a 8 bits TIFF then 10,12 and above returns a RGB64le where for say a 16i should return rgb48le

Important for film scans
Cheers
Ed

**Comment by MrKepzie** [comment]
This is a bug in OpenImageIO the library used internally to encode. We will see if a fix is possible.

**Comment by devernay** [comment]
@edouardchalaron are you using WriteOIIO to write tiffs?
In the "Info" tab of the WriteOIIO properties panel, is the input format RGB32f or RGBA32f?

**Comment by edouardchalaron** [comment]
Hi, thanks a lot for that.
Will be back to you in a couple of days
Cheers

**Comment by devernay** [comment]
seems to work ok in 2.3.10
