### ISSUE TITLE
renderfarm issue

### ISSUE THREAD

**Issue by ramellij** [MrKepzie/Natron#1176]
Hello, 

I'm trying to render an EXR to JPG compositing over my renderfarm using Afanasy. And for each frames tasks  I get from afanasy this error : 
"AFERROR: Service::parse: parser="natron" returned value is not a tuple"
and from Natron, at the end of the task : 
"Spawned process crashed, exiting."

The render is done but at end of each task the issue Reporter appears on my clients and stop them to go to the next task. If I kill the Natron issue Reporter it continues to the next task as it should and afanasy tells me the task is done. And it repeats again , and again....etc

please help 
JR

**Comment by olear** [comment]
If the comp works in Natron and NatronRenderer, then it's a problems with Afanasy. I don't know how that app works, but maybe make it use the non-crashreporter binaries (-bin) (if on Linux you need to edit the wrapper scripts).

**Comment by ramellij** [comment]
Without the Natron Issue Reporter it just crashs (Natron and NatronRenderer). 
I'm using Windows 7 (server and clients).

**Comment by timurhai** [comment]
Hi.
Afanasy related issues should asked on Afanasy project.

You can copy command that Afanasy runs, execute it in a console.
And if some problem, report here.
You can even not to mention who runs this command, Afanasy or whatever.
