### ISSUE TITLE
re-clean: format file and codec..?

### ISSUE THREAD

**Issue by manuelsongokuh** [MrKepzie/Natron#1177]
natron 2.0 rc6

node writeffmpeg: there are confusign or it correct:
if i choose format file AVI and codec prores 444, that is not supported but can clean list of codec compatible to format file, i think re-clean for format file and codec..it's possible?

update:
annoying to message error:
"writeggmpeg1 error: the selected codec is not supported in this container"
then best to automatic filter for container with codec (supported), so message errore will be never show it..so save time for users..

**Comment by olear** [comment]
I'm not sure this is possible in OpenFX at the moment, one combo-box can't be updated based on the actions in another (the content has already been generated, and is static until you load the plugin again) (correct me if I'm wrong).

So at the moment you need to know "what your doing" when exporting video.

**Comment by manuelsongokuh** [comment]
hi olear
i'm understand, but when i choose format (container) and choose codec , there is error message, that is ok, but every time if i'm wrong combine so there are message errors, this is my distraction for error combine : container  - codec..

i think other way solution:
for container AVI then codec list :mjpeg,raw,dv, etc
for container MKV then codec any
for container mp4 then mpeg4,h264 etc
this is little solution like as list simple and not "be updated based on the actions in another.."
if choose this little solution then needed find all information for ffmpeg (node writeffmpeg), instead node write (OIIO) needed find all information list ok?

this is little think and opinion ok?

**Comment by manuelsongokuh** [comment]
do i can add here extra info for team develops of natron?
![natron-container-codec](https://cloud.githubusercontent.com/assets/12126929/13113646/3077827e-d590-11e5-8a30-8de298aa5236.png)
but that table is not complete i will look for add more information extra ok?
