### ISSUE TITLE
Add a preference to disable dialog request when creating Reader/Writer

### ISSUE THREAD

**Issue by manuelsongokuh** [MrKepzie/Natron#1178]
hi

when i add node write or writeffmpeg, there is FIRST dialog for where place to save..this is annoying

but i think to ask you:
when i add node write and without dialog, i will go to panel properties.. this is not annoying, because i can leave place in properties in peace or i will config later..
this is not bug, but i suggest to little change but i'm not decide, you try think is good or not good ok?

**Comment by olear** [comment]
In most of the cases when you add a write node you want to write something, and getting a file dialog is convenient, same with the read nodes. This saves time (you don't have to push 'r' or 'w', and then move to the properties and push the file dialog button).

**Comment by manuelsongokuh** [comment]
i understand..depend of decision team natron, it's could be not important but it's opinion..

**Comment by manuelsongokuh** [comment]
thank you for opinion share..

**Comment by devernay** [comment]
@manuelsongokuh just type ESC when the dialog appears, and you get the preferences panel. This is just one more keystroke.
I don't think this behavior should be changed.

**Comment by manuelsongokuh** [comment]
hi @devernay 
i did try press keyboard ESC not work because ESC is like as cancel dialog..and not get in preferences panel..uhm..it's strange or i'm wrong?
