### ISSUE TITLE
Natron-201602061533-edac7869c85bba8c9845cf1eeac15276abcc6109 - FFMpeg

### ISSUE THREAD

**Issue by blackearth2014** [MrKepzie/Natron#1179]
The FFmpeg for snapshot Natron-201602061533-edac7869c85bba8c9845cf1eeac15276abcc6109 is not reading my .MXF files from Editshare's Lightworks and the .MTS format in a .Mov container. I have a Sony HD handicam that records in the .MTS format. But when I import it to my FCPx NLE and the it does a transcode upon import. Natron doesn't read those files either. See attached image for screen snapshot reference.

![ffmpeg bug](https://cloud.githubusercontent.com/assets/7956901/12871361/6b570486-cd44-11e5-9b01-f57efe01c308.png)

**Comment by MrKepzie** [comment]
Did it use to work ? can we have a file to test ?

**Comment by blackearth2014** [comment]
This is my first testing it.

**Comment by olear** [comment]
My camera outputs .MTS, and they work in Natron (but you have to force the file, since ReadFFmpeg don't have the .MTS extension added to it's list of supported formats).

**Comment by blackearth2014** [comment]
How do you force the file

**Comment by MrKepzie** [comment]
Actually your error is just because you put a # in the name of the file, which Natron replaces by the current frame. Try renaming your file. We will add an explicit error message in the next version or try to support filenames with # in it.

**Comment by devernay** [comment]
you should remove the `#` in the filename (see the error message in the screenshot, Natron replaces the `#` with the frame number.

**Comment by blackearth2014** [comment]
Okay Thanks.

**Comment by devernay** [comment]
I also added .mts and .ts to the list of supported extensions (.m2ts was already there)

**Comment by blackearth2014** [comment]
Thanks Fred
