### ISSUE TITLE
Importing B&W images (but not to use as mask)

### ISSUE THREAD

**Issue by lucasvreis** [MrKepzie/Natron#1180]
When I import an B&W image things get really bugged, while an image of the same type (.png), with the same import configurations, but colored, works perfectly...

Using Natron for Windows, version 2.0.0 RC4 (for some reason I can't install RC6 in any of my Windows computers, but that's another bug report..)

![07-02-2016 17-28-52](https://cloud.githubusercontent.com/assets/4229115/12875246/a921265e-cdc4-11e5-8f22-04e30b2fd622.jpg)

Original image, but with checkerboard bg for transparency visualization:
![k k_cropped_checker](https://cloud.githubusercontent.com/assets/4229115/12875381/bc233b5e-cdc7-11e5-9913-54ee9cac5b65.png)

**Comment by lucasvreis** [comment]
I'll try to add one colored pixel to the B&W image to see what happens

**Comment by lucasvreis** [comment]
Yes, added a single blue pixel to the image and it seems to import properly. Maybe Natron thinks that I'd only use a B&W image as a mask(!)?

**Comment by MrKepzie** [comment]
Set the "Output components" of the Reader of your Alpha-only PNG to "Alpha" .

**Comment by MrKepzie** [comment]
For the installer, have you tried installing as administrator ?

**Comment by lucasvreis** [comment]
Didn't work :/ , the image is not Alpha-only and I want to use it as a normal image. Setting the output components to "Alpha", if I understood well, will make the reader output have just the alpha channel based on the grayscale of the image, and I want my reader to output the RGB channels _plus_ the alpha one, the same way a colored png with alpha channel would import.

**Comment by MrKepzie** [comment]
Can you send the faulty png?

**Comment by lucasvreis** [comment]
Installed as administrator, and it worked :+1:
Sorry for the inconvenience, when you just double click the installer it still shows the admin dialog before installation process, so I thought that running as admin would have no difference .-.

**Comment by lucasvreis** [comment]
From what I tested, you can try with any png B&W image, but here are the two I'm using for this project:
http://imgur.com/a/f4U0Z

**Comment by lucasvreis** [comment]
Ok, SOLVED! In GIMP, changed the mode from Grayscale to RGB, exported again and it imported correctly in Natron

**Comment by devernay** [comment]
The proper way to do it in Natron is to use a Shuffle node and select "Output Components: RGB" in Shuffle
