### ISSUE TITLE
Command line render crash

### ISSUE THREAD

**Issue by speedr972** [MrKepzie/Natron#1187]
Hi,

I generate a node tree with a python script python.
However, when I try to render it in command line (NatronRenderer or Natron -b), it crashes at the 3rd frame.
Rendering seems to work with the GUI

![natronrenderercrash](https://cloud.githubusercontent.com/assets/5656599/13070777/45d060b6-d48f-11e5-85d9-531097ae8bbf.png)

I also send you the crash report
[crashReport.zip](https://github.com/MrKepzie/Natron/files/132093/crashReport.zip)

Thanks

**Comment by MrKepzie** [comment]
Was received, it's a crash in WriteFFMPEG::writevideo , should be fixed in snapshots
