### ISSUE TITLE
Color Hex Color Codes

### ISSUE THREAD

**Issue by blackearth2014** [MrKepzie/Natron#1188]
Is it possible to have the ability to enter Color Hex Color Codes as colors. It will help entering colors that you like faster.

![color hex color codes](https://cloud.githubusercontent.com/assets/7956901/13132591/197a5d44-d5c2-11e5-8a1d-bf1a8744b81a.png)

**Comment by sobotka** [comment]
Hex values don't mean anything as RGB is a relative colour space.

That means the image above likely is assuming something it isn't telling you: the assumed space is based on REC.709 primaries.

**Comment by devernay** [comment]
This could be added to the future color picker.
@blackearth2014 blackearth2014, I suppose you expect those colors to be sRGB ("web" colors) ?

**Comment by blackearth2014** [comment]
Thanks @devernay. Yes sRGB (Web Colors).

**Comment by mray** [comment]
This would be much appreciated since it allows easy copy from other tools (like Inkscape).
It is only copy+paste *once*.

**Comment by devernay** [comment]
This issue was moved to NatronGitHub/Natron#141
