### ISSUE TITLE
roto shape could not be edited

### ISSUE THREAD

**Issue by UttamPal** [MrKepzie/Natron#1195]
Hi, 

If i add a roto node, like square and circle. then any furter points could not be added into it. for changing the shapes. in first frame.even if in edit beizer path after closing the roto points.

**Comment by blackearth2014** [comment]
I am having the same problem.

**Comment by MrKepzie** [comment]
Fixed

**Comment by UttamPal** [comment]
hi thanks.
how could i update it.

**Comment by blackearth2014** [comment]
Uttam Pal,

That fix has not be build or released in the snapshot folder. Give it a fews hours until the build server posts it.

Omar

**Comment by UttamPal** [comment]
thanks mr. omar. eagerly waiting
