### ISSUE TITLE
Screen operator in Merge Nodes has a bug!

### ISSUE THREAD

**Issue by PostPollux** [MrKepzie/Natron#1197]
I found a bug in the merge node. The screen operation seems to have an issue. It looks like it's using just A+B-AB  and no condition for A and B being bigger than 1.
https://goo.gl/photos/iSFJ4aUhk7eG7QjW9

According to what I found on the web, screen should work like this:
If A or B is less than or equal to 1 the screen, else use the maximum example. Similar to plus. See also Screen. Algorithm:** A+B-AB if A and B between 0-1, else A if A>B else B**
(http://help.thefoundry.co.uk/nuke/8.0/content/reference_guide/merge_nodes/merge.html)

**Comment by MrKepzie** [comment]
ok fixed
