### ISSUE TITLE
Every other time Natron fails to launch OSX

### ISSUE THREAD

**Issue by nicholascarroll** [MrKepzie/Natron#1198]
I am using latest dev builds from snapshots download page. In these recent builds, Natron fails to launch. This is on OSX. The Natron icon bounces around on the dock but the applicaiton never launches.
  However this happens only every second time it launches.

**Comment by MrKepzie** [comment]
What does it says from the command line ?

**Comment by nicholascarroll** [comment]
The problem never occurs if launched from command line. But it does output an error. I wasn't sure whether to run 'Natron' or 'Natron-bin'. Both give the same error but 'Natron' will always require Control-C to get back to the prompt. Like this:
```
MacBook:MacOS nick$ ./Natron
Natron Version 2.0.0
Copyright (C) 2016 the Natron developers
>>>Use the --help or -h option to print usage.<<<
init.py script not loaded
initGui.py script not loaded
2016-03-03 10:21:22.715 Natron-bin[1247:115372] modalSession has been exited prematurely - check for a reentrant call to endModalSession:
^C
MacBook:MacOS nick$ ./Natron-bin 
Natron Version 2.0.0
Copyright (C) 2016 the Natron developers
>>>Use the --help or -h option to print usage.<<<
init.py script not loaded
initGui.py script not loaded
2016-03-03 10:25:48.468 Natron-bin[1250:116320] modalSession has been exited prematurely - check for a reentrant call to endModalSession:
MacBook:MacOS nick$ 
```

**Comment by MrKepzie** [comment]
It looks like the dialog I was talking about must be showing up but is hidden by the splash screen

**Comment by MrKepzie** [comment]
was it fixed ?

**Comment by nicholascarroll** [comment]
No, and I even tried with this latest snapshot:
Natron-201603050036-4f2cb4985f1d12c8c1c8972e30af51ebbc34dd05.dmg (2016-Mar-05 00:52:25)
Before I did I removed /Users/nick/Library/Application Support/INRIA/Natron.
Isn't it affecting others on OSX?

**Comment by MrKepzie** [comment]
Can you try again ? Could you also remove anything in ~/Library/Caches/INRIA

**Comment by nicholascarroll** [comment]
tried that, doing rm -rf ~/Library/Caches/INRIA before each launch. Still does the same thing. I have attached apple console logs for both the successful startup and the failed startup.

[logs.zip](https://github.com/MrKepzie/Natron/files/160620/logs.zip)

**Comment by devernay** [comment]
When it hangs:
- figure out the Natron process number using `ps x`
- there should be two Natron processes, with consecutive process IDs (first column)
- note that process number/ID (let's call it p), and type `kill -ABRT p` where p is the number
- this should trigger the bug reporter, but it doesn't (@MrKepzie @olear breakpad bug?)
- however, you get the apple notification, click on it, and copy-paste the backtrace (the text content of the window) in a [gist](https://gist.github.com)

**Comment by nicholascarroll** [comment]
OK so once it started and hung I did:

MacBook:~ nick$ ps x | grep -i natron
 1128   ??  S      0:00.05 /Applications/Natron.app/Contents/MacOS/Natron
 1130   ??  Z      0:00.00 (Natron-bin)
 1141 s000  R+     0:00.00 grep -i natron
MacBook:~ nick$ kill -ABRT 1128

and here's the [Apple Crash Report gist](https://gist.github.com/nicholascarroll/81d6e94c6929c47913e0).

**Comment by devernay** [comment]
I forgot to mention you had to kill the second process (which appears as Natron-bin here). Normally it should be like this:
```
5566   ??  S      0:00.06 /Applications/Natron.app/Contents/MacOS/Natron
 5567   ??  R      0:02.97 /Applications/Natron.app/Contents/MacOS/Natron --breakpad_process_exec /Applications/Natron.app/Contents/MacOS/Natron --breakpad_process_pid 5566 --breakpad_client_fd -1 --breakpad_pipe_path /var/folders/gt/gffd8dfj1_13gqwy3pcxh1740000gn/T/Natron_CRASH_PIPE_.JL5566 --breakpad_com_pipe_path /var/folders/gt/gffd8dfj1_13gqwy3pcxh1740000gn/T/Natron_CRASH_PIPE_.JL5566IPC_COM
```
However, your report was very informative, since the Natron-bin executable (the *real* thing) appears as a zombie (a dead process waiting to report to its parent). This means that Natron itself actually crashed at that point... So it's more of a crash reporter bug.
Take a try with the latest snapshot (better crash handling on OSX).

**Comment by nicholascarroll** [comment]
I just realized I had the crash reporting turned off in Natron Preferences. I suspect that is ironically the reason for the bug. So please try turning it off and reproducing.

**Comment by olear** [comment]
Still an issue?

**Comment by nicholascarroll** [comment]
i have kept crash reporting turned on since then, so I don't know.

**Comment by nicholascarroll** [comment]
Yes this is still reproducing as of 15 Jun snapshot (v2.1)

**Comment by devernay** [comment]
This issue was moved to NatronGitHub/Natron#143
