### ISSUE TITLE
Primatte small issues - questions

### ISSUE THREAD

**Issue by nicholascarroll** [MrKepzie/Natron#1199]
This issue is about usability of Primatte 5.1 in Natron 2.0 OSX 2 February build. On Apple MacBook (Retina, 12-inch, Early 2015) , Yosemite  10.10.5. So to go through the user experience step by step:

1. The *Auto-Compute* button works OK. I notice though, that this puts the blue keyframe on the *Backing Color* field in the *Expert* tab.
2. *Select BG Color* works OK (although it works even without holding down command and that is not ideal). This also puts the blue keyframe on the *Backing Color*.
3. *Clean BG Noise* works OK however I have to hit _force render_ ('U') every time which is very inconvenient. However I don't know if that is simply because this is a low power machine. 

So, can I ask:
- is it correct to have the keyframing on *Backing Color*?
- is it Natron or Primatte that is letting the picker work even though command is not held down?

**Comment by MrKepzie** [comment]
I have compared in Nuke as well and I get the same behaviour than in Natron. Except that in Nuke, they do not have "Pages" and everything is in the same tab (="Page" in Natron)

1 : Yes this is Primatte that sets a keyframe, not Natron
2 : Again, the keyframe is set by Primatte, and this is the Primatte implementation that does not require command to be held
3: I'm investigating, but I think this is Primatte too

**Comment by nicholascarroll** [comment]
Thanks @MrKepzie well I suppose it works as intended then.
@devernay what makes this is a bug? By the way in case you have not seen it here is a nice explanation of how Primatte uses a [128 faced polyhedron](http://www.primatte.com/content.cfm?n=whitepapers-why). I'm not sure but I think its based on their [patent for a 48 faced polyhedron based chromakeyer](http://www.google.com/patents/US5355174).

Tomorrow I will make sure the remaining features work (especially Fine Tuning sliders) and update this issue with the result.

I don't think it would concern any user that it appearing over two pages in Natron 2.0. Maybe that is the correct way per the standard? And the developer's intention?  I hope that the Primatte developer will read this issue and comment. 
So, in Natron 1.2, it was in one:
<img width="398" alt="main-tab-natron-1 2" src="https://cloud.githubusercontent.com/assets/1062708/13509803/9742bd2c-e1e1-11e5-8a00-c5513f282412.png">

Here it is in Natron 2.0:
<img width="402" alt="main-tab-natron-2 0" src="https://cloud.githubusercontent.com/assets/1062708/13510001/b3a25738-e1e2-11e5-97d6-f9c1e6a11c98.png">
<img width="404" alt="expert-tab-natron-2 0" src="https://cloud.githubusercontent.com/assets/1062708/13510015/cff84cd0-e1e2-11e5-8e23-d15fdda69f72.png">

**Comment by MrKepzie** [comment]
Well if you can reach the  Primatte developers about the matter and report it to them it would be cool

**Comment by nicholascarroll** [comment]
Yes, I have done that and waiting on a response. Now I do find a bug which is with the Fine Tuning Sliders. To reproduce:
1. Get a key (using the *Auto-Compute* button  or by picking the
colour with *Operation* 'Select BG Color')
2. Set the *Operation* to 'Fine Tuning Sliders'
3. Go to the *Expert* tab. The *From Tune* and *To Tune* are
zero - they should instead be already showing values.

Here is a screenshot showing this and also a screenshot showing how it should look if it was working (somehow it worked once for me, but I could not get it to work again):

HOW IT SHOULD BE
<img width="400" alt="fine-tuning-sliders-ok" src="https://cloud.githubusercontent.com/assets/1062708/13543474/aa93a42a-e2bf-11e5-86c6-9df07e743432.png">

HOW IT IS
<img width="402" alt="fine-tuning-sliders-broken" src="https://cloud.githubusercontent.com/assets/1062708/13543484/ba1d7a38-e2bf-11e5-972d-416175dd1933.png">

**Comment by nicholascarroll** [comment]
note this old bug on the same function: 
[Color Knob bugs (Primatte OFX plugin Fine Tuning sliders dont work) #421](https://github.com/MrKepzie/Natron/issues/421)

**Comment by nicholascarroll** [comment]
Comment from Primatte Developer (received by email): "I think the reason it doesnt work is that they dont support access to images during the overlay events."

**Comment by devernay** [comment]
Interesting! thanks for the feedback, we will check for it.

**Comment by devernay** [comment]
marking as bug, although we still don't know if it's on the primatte or on the natron side

**Comment by nicholascarroll** [comment]
It works on the other OFX hosts.

**Comment by MrKepzie** [comment]
I can tell you Primatte only request images when the mouse click is released and we return a correct image from there, so I do not know what is not working, you'd have to be more specific

**Comment by nicholascarroll** [comment]
Have you tried following the steps I provided to reproduce - my post above?

> 1. Get a key (using the Auto-Compute button or by picking the colour with Operation 'Select BG Color')
> 2. Set the Operation to 'Fine Tuning Sliders'
> 3. Go to the Expert tab. The From Tune and To Tune are zero - they should instead be already showing values.

**Comment by MrKepzie** [comment]
Hmm I have the exact same behaviour in Nuke (9): if I apply your steps, the From Tune and To Tune remain to zero.

**Comment by nicholascarroll** [comment]
Sorry, I was missing the step to click in the viewer to set the colour picker for Fine Tuning. Doing that now, all 3 fine tuning sliders do work; it is only the display of the *From Tune* and *To Tune* that is jumping back to zero, and this only happens if you move the slider rapidly.

I will close this and instead raise it with the Primatte developer, and leave it to them to follow up with you directly.
