### ISSUE TITLE
Render not respecting project frame range

### ISSUE THREAD

**Issue by mrhowardjones** [MrKepzie/Natron#1201]
Have an 11000 fr clip.
Set project to 0-100fr
Write node -> render
Attempts to render 11000 frames and not the project range.

2 suggestions on top of the above
Add a render range into the write node (apologies if there - new to Natron) with toggle on/off
Pop up a render dialogue so you can adjust the range

**Comment by olear** [comment]
See 'FrameRange' in the Write node. Set to 'Project frame range' or 'manual'.

**Comment by mrhowardjones** [comment]
Thanks

Missed that completely but getting used to your layout.

Shouldn’t this default to the project settings then? 17 years on Shake and Nuke and I raraely ever want that to not be the project settings.
However the render dialogue always prompts you to check the range which I think for gui use would still be a good thing,
Best

Howard Jones
Visual Effects Supervisor
m: 07973 265624 | e: howard@axis-vfx.com | w: www.axis-vfx.com

> On 2 Mar 2016, at 18:11, Ole-André Rodlie <notifications@github.com> wrote:
> 
> See 'FrameRange' in the Write node. Set to 'Project frame range' or 'manual'.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/MrKepzie/Natron/issues/1201#issuecomment-191355026>.
> 


-- 



*A X I S V F X*

The Bottle Yard Studios

Whitchurch Lane

Bristol BS14 0BH

 

axis-vfx.com
