### ISSUE TITLE
"uniform" scaling checkbox in different nodes

### ISSUE THREAD

**Issue by PostPollux** [MrKepzie/Natron#1204]
I find it kind of confusing that the transform, the blur and the bloom node have a "uniform" checkbox.
I think there is no need for the "uniform" checkbox, as it should be obvious, that it is uniformly scaled as long as there is only one input. If you then hit the "2" then you can scale them separately. That's intutiv and it's done exactly that way for example in the "radial"-node. Is there any good reason for that checkbox?
Btw: In blur and bloom "uniform" is checked by default and in the transform node it's unchecked by default. That's a bit inconsistent.

https://goo.gl/photos/wuZ2khHixcDsr2tv8

**Comment by devernay** [comment]
the uniform checkbox is here both for compatibility with older projects (where there was only one dimension) and for compatibility with Nuke and other OpenFX hosts.

**Comment by devernay** [comment]
The uniform checkbox will disappear on Natron from newly-created nodes. It'll still be there is old graphs if it was checked.

**Comment by PostPollux** [comment]
ok, so basically if I hit the "2" it will be behave like toggling "uniform". Cool, thanks!
