### ISSUE TITLE
TAB Type + Enter Issue

### ISSUE THREAD

**Issue by PostPollux** [MrKepzie/Natron#1205]
I like to hit tab, type in the Nodename and hit enter. For me that's the fastest way. I noticed the following issue:

Hitting enter only produces a node, as long as there is only one left in the list. I think it would be cool if it instead always chooses the first one of the list.
-> typing something like "invert" would work, because there are two entries left in the list
-> you don't have to complete the name and you can hit enter right away as soon as you see your desired node on the top of the list.

**Comment by MrKepzie** [comment]
I think I did this change a few weeks ago, might be broken
