### ISSUE TITLE
add CONTRIBUTING.md, ISSUE_TEMPLATE.md, and PULL_REQUEST_TEMPLATE.md to the repository

### ISSUE THREAD

**Issue by devernay** [MrKepzie/Natron#1207]
see https://github.com/blog/2111-issue-and-pull-request-templates

CONTRIBUTING.md should be in the top-level directory.

ISSUE_TEMPLATE.md and PULL_REQUEST_TEMPLATE.md should be in .github to avoid clutter.

OIIO has these:

https://github.com/OpenImageIO/oiio/blob/master/CONTRIBUTING.md
https://github.com/OpenImageIO/oiio/blob/master/.github/ISSUE_TEMPLATE.md
https://github.com/OpenImageIO/oiio/blob/master/.github/PULL_REQUEST_TEMPLATE.md

**Comment by olear** [comment]
done.
