### ISSUE TITLE
PNG Files- Error Loading

### ISSUE THREAD

**Issue by blackearth2014** [MrKepzie/Natron#1209]
This version Natron-201603041345-278843f3d0d6b2721cd7cbc4dbe791cbb2b7e457 is not recognizing PNG files at all. See attached image for reference.

![png files- error loading](https://cloud.githubusercontent.com/assets/7956901/13528347/5f6c5c26-e1e3-11e5-9834-0c5cf39747a4.png)

**Comment by MrKepzie** [comment]
Can you send a faulty png ?

**Comment by olear** [comment]
I just tested on OSX, can't read or write PNGs.

**Comment by MrKepzie** [comment]
I can do it here, so the version of OIIO compiled must not be correct. Can you relaunch a build on all platforms to include the latest patch i made ?

**Comment by olear** [comment]
OIIO has been rebuilt on Win/Lin, will check Mac.

**Comment by blackearth2014** [comment]
Here is a PNG file freshly rendered from Blender.

![12340001](https://cloud.githubusercontent.com/assets/7956901/13529402/0cd770de-e1ea-11e5-86be-2d083d329a1a.jpg)

**Comment by MrKepzie** [comment]
Github is converting to jpg, upload it on google drive or something else

**Comment by blackearth2014** [comment]
Here is a link to the file https://drive.google.com/open?id=0B3jSQyyH71fGRHVSYXBBaWllQ1k.

**Comment by MrKepzie** [comment]
This is a bug with the OIIO build on Mac. I don't have the issue here

**Comment by olear** [comment]
OIIO links against png, and libpng is included. I can read PNGs from ReadPSD. A bit unsure whats causing the bug...

**Comment by devernay** [comment]
from the console:
```
libpng warning: Application built with libpng-1.2.44 but running with 1.6.21
```
maybe a problem with the include path when building OIIO

**Comment by devernay** [comment]
```
$ fgrep -r 1.2.44 /Applications/Natron.app/Contents/Frameworks/
Binary file /Applications/Natron.app/Contents/Frameworks//libOpenImageIO.1.6.dylib matches
```

**Comment by olear** [comment]
Ahh, so that's the problem. So OIIO catches libpng from the system during build?

**Comment by devernay** [comment]
yes, should be fixed by https://github.com/MrKepzie/Natron/commit/4f2cb4985f1d12c8c1c8972e30af51ebbc34dd05 
waiting for the build

**Comment by devernay** [comment]
it was also using freetype from /usr/X11R6

**Comment by devernay** [comment]
looks better now, please close if the next build is ok

**Comment by olear** [comment]
Works with latest snapshot.

**Comment by blackearth2014** [comment]
Hello Guys,

This version Natron-201603042358-4f2cb4985f1d12c8c1c8972e30af51ebbc34dd05 is working  like brie cheese on a baguette bread with a side of jam.

**Comment by devernay** [comment]
@blackearth2014 thanks !
