### ISSUE TITLE
Cutom parameters not animatable

### ISSUE THREAD

**Issue by mrhowardjones** [MrKepzie/Natron#1211]
Natron version 2.0.0 RC
(as tested)
Create write node
Add custom parameters
1 - Test - Checkbox
2- TestB- Checkbox
3 TestC - Integer

Test was created with 'Animates' Off - Close. Then back into turn animates on. Using setkey doesn't add a key
TestB was created with 'Animates' On. Again no keyframes appear when setKey
TestC same as above but different parameter

**Comment by MrKepzie** [comment]
Can you try on a more recent build ? I cannot reproduce the issue here:

http://downloads.natron.fr/Mac/snapshots/

http://downloads.natron.fr/Linux/snapshots/64bit/files/

http://downloads.natron.fr/Windows/snapshots/64bit/files/

**Comment by mrhowardjones** [comment]
Hi

Works fine in this build
Natron-201603040904-3fbd2815666fcce01daa4ce116b1907dad81e000.dmg <http://downloads.natron.fr/Mac/snapshots/Natron-201603040904-3fbd2815666fcce01daa4ce116b1907dad81e000.dmg> 2016-Mar-04 14:01:43

Thanks

> On 4 Mar 2016, at 15:28, Alexandre Gauthier <notifications@github.com> wrote:
> 
> Can you try on a more recent build ? I cannot reproduce the issue here:
> 
> http://downloads.natron.fr/Mac/snapshots/ <http://downloads.natron.fr/Mac/snapshots/>
> http://downloads.natron.fr/Linux/snapshots/64bit/files/ <http://downloads.natron.fr/Linux/snapshots/64bit/files/>
> http://downloads.natron.fr/Windows/snapshots/64bit/files/ <http://downloads.natron.fr/Windows/snapshots/64bit/files/>
> —
> Reply to this email directly or view it on GitHub <https://github.com/MrKepzie/Natron/issues/1211#issuecomment-192323000>.
> 


-- 



*A X I S V F X*

The Bottle Yard Studios

Whitchurch Lane

Bristol BS14 0BH

 

axis-vfx.com

**Comment by mrhowardjones** [comment]
Hi

Works fine in this build
Natron-201603040904-3fbd2815666fcce01daa4ce116b1907dad81e000.dmg 2016-Mar-04 14:01:43

Thanks

**Comment by MrKepzie** [comment]
Ok
