### ISSUE TITLE
[reformat node] size not preserved on save/load

### ISSUE THREAD

**Issue by thugcee** [MrKepzie/Natron#1214]
Version: tags/2.0.0-RC6 at commit 6da4c9ff375a14a8d86fae8be51d3c492ce6431f

To reproduce: 
- create new project
- add some reader and reformat node, then connect them
- change reformat size to something custom
- save project
- load project
Size will be reset to default values.

Extremely annoying in projects with many reformats.

**Comment by MrKepzie** [comment]
Was already fixed in dev builds, you can download latest snapshots to get the fix.

**Comment by thugcee** [comment]
Ok. thx :)
