### ISSUE TITLE
Grayscale+Alpha PNGs are not read correctly.

### ISSUE THREAD

**Issue by devernay** [MrKepzie/Natron#1215]
PNGs may be stored with "grayscale+alpha":
http://www.libpng.org/pub/png/book/chapter08.html#png.ch08.div.5.5
https://www.w3.org/TR/PNG-DataRep.html#DR.Alpha-channel

a few examples can be found in Natron sources:
https://github.com/MrKepzie/Natron/blob/workshop/Gui/Resources/Images/natronIcon256_linux.png

Natron reads them as "Alpha" component images, and puts the Intensity channel in another layer, without applying the color transfer function(s).

It should instead output a single-layer RGBA image, with
R=G=B=transfer(I)
Alpha=A

**Comment by devernay** [comment]
Another example can be found in the excellent [PNGSuite](http://www.schaik.com/pngsuite/) ; 
http://www.schaik.com/pngsuite/tbbn0g04.png

**Comment by devernay** [comment]
Note that In OIIO, 2-channel images are by default I+A:
https://github.com/OpenImageIO/oiio/blob/master/src/libOpenImageIO/formatspec.cpp#L154

An "I" channel from OIIO should be remapped to R+G+B

**Comment by MrKepzie** [comment]
Fixed by https://github.com/MrKepzie/openfx-io/commit/337be5d9f88223ff9b19eb2f486fa72c74b27595
