### ISSUE TITLE
[reformat node] changing size does not update pipeline

### ISSUE THREAD

**Issue by thugcee** [MrKepzie/Natron#1216]
Version: tags/2.0.0-RC6 at commit 6da4c9ff375a14a8d86fae8be51d3c492ce6431f

To reproduce:
- add reformat to your pipeline
- set *type* to *box*
- change size x or y values - pipeline will not be updated, I have to change some other value to get it updated

**Comment by MrKepzie** [comment]
Fixed in dev builds.
