### ISSUE TITLE
Shuffle layers seems odd

### ISSUE THREAD

**Issue by mrhowardjones** [MrKepzie/Natron#1218]
Shuffling an incoming motion.backwards channel doesn't appear to give results I would expect. Happy it's me but  all I get is what is in the blue channel rather than RGB _> A.r A.Backward.Motion.U A.b.

See below example.
 Using
Natron-201603070855-47b9d4769ceab35f5fb6c560b2a3968d1bcd232a.dmg

**Comment by MrKepzie** [comment]
Can you be a little bit more specific? How do we reproduce? I removed the inlined XML because it was unreadable, if you wish to attach a project please upload it somewhere else

**Comment by mrhowardjones** [comment]
I was hoping tha XML would have shown you anyway.
Simple example I tested...

1) read in or create a moving image (I used a text with animated text)
2) add and view a frameBlend set to -2, 2 in Frame range min,max (numbers aren’t that relavant)
3) set the 'output layer' of the frameBlend to backward.motion
4) change the viewer to display backward.motion.UV

You should now see yellow test as you would expect.

5) set the viewer back to sRGB
6) add and view a shuffle node
7) set red -> A.backward.motion.U
8) set green -> A.backward.motion.V
9) set blue -> A.b

I would expect to see the frameblended image in R,G and the original image in B.
Instead R,G are blank and I only see B

Hope that helps. Where should I send XML project stuf?


Howard Jones
Visual Effects Supervisor
m: 07973 265624 | e: howard@axis-vfx.com | w: www.axis-vfx.com

> On 11 Mar 2016, at 09:54, Alexandre Gauthier <notifications@github.com> wrote:
> 
> Can you be a little bit more specific? How do we reproduce? I removed the inlined XML because it was unreadable, if you wish to attach a project please upload it somewhere else
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/MrKepzie/Natron/issues/1218#issuecomment-195302033>.
> 


-- 



*A X I S V F X*

The Bottle Yard Studios

Whitchurch Lane

Bristol BS14 0BH

 

axis-vfx.com

**Comment by MrKepzie** [comment]
Was a bug indeed

**Comment by mrhowardjones** [comment]
Thanks

We’re hoping to use Natron for our 3D artists to do look comp and of course the shuffle node is a key tool here for EXRs

Howard

> On 11 Mar 2016, at 14:59, Alexandre Gauthier <notifications@github.com> wrote:
> 
> Was a bug indeed
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/MrKepzie/Natron/issues/1218#issuecomment-195401273>.
> 


-- 



*A X I S V F X*

The Bottle Yard Studios

Whitchurch Lane

Bristol BS14 0BH

 

axis-vfx.com

**Comment by MrKepzie** [comment]
Stable release is scheduled for later today, and should provide enough stability to work!

If you encounter any issue, make sure to keep us informed,

Thanks

**Comment by mrhowardjones** [comment]
Many thanks

Works well!

Howard

> On 11 Mar 2016, at 15:36, Alexandre Gauthier <notifications@github.com> wrote:
> 
> Stable release is scheduled for later today, and should provide enough stability to work!
> 
> If you encounter any issue, make sure to keep us informed,
> 
> Thanks 
> 
> > On 11 Mar 2016, at 16:33, mrhowardjones <notifications@github.com> wrote:
> > 
> > Thanks
> > 
> > We’re hoping to use Natron for our 3D artists to do look comp and of course the shuffle node is a key tool here for EXRs
> > 
> > Howard
> > 
> > > On 11 Mar 2016, at 14:59, Alexandre Gauthier <notifications@github.com> wrote:
> > > 
> > > Was a bug indeed
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub <https://github.com/MrKepzie/Natron/issues/1218#issuecomment-195401273>.
> > > 
> > 
> > 
> > -- 
> > 
> > 
> > 
> > *A X I S V F X*
> > 
> > The Bottle Yard Studios
> > 
> > Whitchurch Lane
> > 
> > Bristol BS14 0BH
> > 
> > 
> > 
> > axis-vfx.com
> > —
> > Reply to this email directly or view it on GitHub <https://github.com/MrKepzie/Natron/issues/1218#issuecomment-195417200>.
> > 
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/MrKepzie/Natron/issues/1218#issuecomment-195418894>.
> 


-- 



*A X I S V F X*

The Bottle Yard Studios

Whitchurch Lane

Bristol BS14 0BH

 

axis-vfx.com
