### ISSUE TITLE
shuffle channel select request

### ISSUE THREAD

**Issue by mrhowardjones** [MrKepzie/Natron#1219]
Shuffle Red channel appears to set the channel you wish to shuffle from. Although this seems ok - unfortunately it means you have to select red first otherwise if you select after it resets the other selections.

Would it work better if there was a channel selection parameter that you had instead. It then set all RGBA at the same time once, then allowed you to change how you liked?

**Comment by MrKepzie** [comment]
Thing is if you would then change every channel individually, the "main" layer menu would potentially no longer be in sync with the channels, e.g:

R --> Color.G
G --> Color.G
B --> Color.G
A --> 1

Layer --> Beauty

**Comment by devernay** [comment]
There is now a "Set GBA from R" checkbox to toggle setting all channels from red
