### ISSUE TITLE
feature request: comp stack node

### ISSUE THREAD

**Issue by jhelmsie** [MrKepzie/Natron#1221]
I'm inspired by your development of Natron and the access you are giving the world to quality compositing tools.  Congratulations!

I'm contacting you to propose a new comp stack node:  [CompNodeMockup_2016_02_24](https://www.dropbox.com/s/300pbwqdehqg79j/CompNodeMockup_2016_02_24.jpg?dl=0)

Some benefits are:
-significantly reduce the number of nodes in a graph
-provide logical pre-comp groupings with inputs that can be quickly reordered
-add some of the benefits of the layer based interface in After Effects, without the poor handling of the alpha channel, and keep the industry familiarity of the Nuke interface  (the best of both interfaces)

Features list:
-multiple rgba+ inputs
-multiple matte inputs
-rgba+ output
-interface similar to roto/paint in Nuke
-columns/options for user_defined_name, on/off, solo(not shown in mockup), uncommitted pause, comp operation, mix, frame range, frame offset, source name(hard coded to input), mask or inverse mask
-drag and drop reorder

Thank you for reading and considering!

**Comment by devernay** [comment]
![compnodemockup_2016_02_24](https://cloud.githubusercontent.com/assets/3778071/13600917/798112a4-e52c-11e5-8fe9-f8dbd231f9bf.jpg)

**Comment by jhelmsie** [comment]
Feature list addition:
-Mix is keyable (updated mockup [here](https://www.dropbox.com/s/7h6q8htpf1q70u2/CompNodeMockup_2016_03_08.jpg?dl=0) )

**Comment by MrKepzie** [comment]
There's very little to do actually to add this since it's very much like Rotopaint with the "Reveal" input except that in this case you would have the mask taken from a mask input instead of the paint brush and everything would be summed up in the table

**Comment by jhelmsie** [comment]
I've update the mockup with notes for clarity.  I hope this is helpful to you.  Thank you for your efforts!

![compnodemockup_w_notes_2016_06_27](https://cloud.githubusercontent.com/assets/17719263/16435846/ea95e25c-3d4d-11e6-8013-9c152fcb86a6.jpg)

**Comment by devernay** [comment]
This issue was moved to NatronGitHub/Natron#144
