### ISSUE TITLE
Crash reporter: Enable SIGABRT handler on OSX

### ISSUE THREAD

**Issue by devernay** [MrKepzie/Natron#1222]
This would allow crash reporting on a frozen Natron using 'kill -ABRT' on the process (see https://github.com/MrKepzie/Natron/issues/1198 for an example)

Just remove `if (!IsOutOfProcess())` at [exception_handler.cc:635](https://chromium.googlesource.com/external/google-breakpad/+/master/src/client/mac/handler/exception_handler.cc#635)

trivial patch also available at:
https://breakpad.appspot.com/7744002/

**Comment by olear** [comment]
Added with https://github.com/MrKepzie/Natron/commit/c78a465066cacea4f0a5b9a107d1ff73320181eb
