### ISSUE TITLE
Feature Request: Frame Range Column in "Progress" tab

### ISSUE THREAD

**Issue by PostPollux** [MrKepzie/Natron#1226]
I think it would be great, if the render Progress table had a "Frame Range" column showing the Range in numbers and a "colorspace" column.

Because this is something I sometimes forget and Natron doesn't ask you if you hit render. So from time to time I end up with a wrong frame range. If it's displayed there, this could help to immediately see the mistake.
Do you think this is a reasonable addition or would you rather keep the interface clean?

**Comment by olear** [comment]
Available in latest snapshots.
