### ISSUE TITLE
Tuttle OFX missing in latest build

### ISSUE THREAD

**Issue by tobkum** [MrKepzie/Natron#1228]
### Problem

Tuttle Plugins are not included anymore in latest Build (March 11, 2016)

**Comment by MrKepzie** [comment]
We do not include them anymore because it is hard to maintain and most of them have a replacement bundled in Natron which is faster and better maintained.

**Comment by tobkum** [comment]
Oh, sorry... didn't know that. It's a pity though, I'm looking for a way to add Text to a composition without having to save it as an image first.

**Comment by MrKepzie** [comment]
There's a Text node in Natron in the Draw menu.

**Comment by tobkum** [comment]
I got Lightwrap, Radial, Ramp, Rand, Rectangle, Roto and RotoPaint but no text there.

**Comment by MrKepzie** [comment]
Then you are missing some plug-ins. Do you have Natron2/Plugins/OFX/Plugins/Arena.ofx.bundle ?
In Natron do you have the "Extra" menu with a small magic wand  ?

**Comment by tobkum** [comment]
The path does exist in \Natron\Plugins\OFX\Natron\Arena.ofx.bundle, but the menu in Natron is not there

**Comment by MrKepzie** [comment]
Which platform are you using ?

**Comment by tobkum** [comment]
Win64

**Comment by olear** [comment]
Try clearing the plugin cache (see cache menu).

**Comment by MrKepzie** [comment]
Did you install with the installer or with the no-installer version ? If not, please re-try with the installer. 
We are going to re-package tomorrow all the binaries with various fix regarding the installer before we announce the release officially.

**Comment by tobkum** [comment]
I did previously use the online installer (http://downloads.natron.fr/Windows/releases/64bit/files/Natron-Windows-x86_64bit-online-release-setup.exe).
Just did a re-installation using the normal one (http://downloads.natron.fr/Windows/releases/64bit/files/Natron-2.0.0-stable-Windows-x86_64bit-setup.exe) - same result.

**Comment by MrKepzie** [comment]
Okay this is an issue with the package;) we will fix it for the official release of tomorrow.

**Comment by tobkum** [comment]
Awesome, thanks! Keep it up :)

**Comment by olear** [comment]
I have the Arena plugins on Windows 7 here, sure it's just not a cache issue?

**Comment by tobkum** [comment]
Latest update fixed it, thanks!

**Comment by devernay** [comment]
@tobkum If there are any other TuttleOFX plugins you are missing, please tell us. Because of its numerous dependencies, TuttleOFX is hard to install, but we could port a few plugins if needed (their plugins are overall quite good)

**Comment by sozap** [comment]
Hello !
I found the Tuttle ID keyer very handy. There is now a pyplug in natron that deals with blender ID pass, but, the Tuttle ID one as a few feature that are nice, like the possibility to add several mask with one node.
Maybe it's doable with a pyplug ...

And finally, I haven't used the tuttle color transfert yet, but it looked like a great tool too !
