### ISSUE TITLE
update to sourceforge.net ? natron stable 2.0

### ISSUE THREAD

**Issue by manuelsongokuh** [MrKepzie/Natron#1230]
hi
when i click update from dialog "New version"
there is " you can download it from Sourceforge." but it is old link..
maybe will be from 'download.natron.fr' ?

> "Updates for Natron are now available for download. You are currently using Natron version 2.0.0 - Release - build 0. The latest version of Natron is version 2.0.0 - Release - build 1.
> You can download it from Sourceforge."

this is correct?
this dialog is from natron stable 2.0 

this is question. it is not the bug

**Comment by MrKepzie** [comment]
Known, a similar ticket was opened on this.

**Comment by manuelsongokuh** [comment]
ok thank you :+1:

**Comment by manuelsongokuh** [comment]
hi, check in github natron check link to sourceforge, i find 3 old links..

INSTALL_WINDOWS.md
https://sourceforge.net/projects/natron/files/Natron_Windows_3rdParty.zip/download

tools/deprecated/build-plugins.bat
https://sourceforge.net/projects/natron/files/Natron_Windows_3rdParty.zip/download 

tools/deprecated/build-natron.bat
https://sourceforge.net/projects/natron/files/Natron_Windows_3rdParty.zip/download

ok thank you
