### ISSUE TITLE
start to render, after 1 minute go crash without "Crash Reporting"...?

### ISSUE THREAD

**Issue by manuelsongokuh** [MrKepzie/Natron#1231]
hi
maybe is a bug.

i do simple node, and render to jpg sequences, and start to render..after 1 minute go to crash..but without sending "Crash Reporting.." 
natron is close after 1 minute of render..

i can send you ntp:
https://gist.github.com/manuelsongokuh/9a9f0e5528eb3afdb153

**Comment by MrKepzie** [comment]
Well given that you are trying to render 19K x 10K images, I'd toss that you ran into memory issues. Basically all the cores of your CPU are trying to render at least a frame but each frame requires probably something like 4GiB+ of RAM (the Merge needs actually 3 images to work at least). So you add that for each of your core and you've got it. 

First you should try with the *Nmber of parallel renders* setting to 1.

**Comment by MrKepzie** [comment]
Secondly you do not take advantage of the Transforms concatenations, you should put the 2 Transforms 1 after the other so that only the bottom one would render.

**Comment by MrKepzie** [comment]
Also, can you try using *Natron-bin* directly and not Natron, in the Natron2/bin directory, and launch it from a terminal, e.g:

cd ~/Natron2/bin
./Natron-bin

It should print the backtrace when crashing in the console, report it back here (only if it crashes)

**Comment by manuelsongokuh** [comment]
sorry for late, ok i will test it that you wrote. i will back here..

**Comment by manuelsongokuh** [comment]
hi
i tested..

first test:
natron-bin - without "First you should try with the Nmber of parallel renders setting to 1".
Natron go Crashed after 3 render image sequence.
Konsole (terminal) nothing debugging..like as nothing feedback only "start" natron and after start to write (render) nothing to print the backtrace.

second test:
natron.sh + "First you should try with the Nmber of parallel renders setting to 1".
Natron does not go to Crash, working as fine. long time render but worked.

end of test.

instead _"Secondly you do not take advantage of the Transforms concatenations, you should put the 2 Transforms 1 after the other so that only the bottom one would render."_ i dont understand.. :-(..

version of Natron is :e6ef3e4fcd889edb6ec6a901bd9f938bdebd06a3.

**Comment by olear** [comment]
Maybe you run out of memory? Then the system will just kill Natron, so no crash report.

Run 'top' or 'watch free -m' from another terminal and see what happens.
