### ISSUE TITLE
Python saveProject and saveProjectAs should not ignore input on GUI mode

### ISSUE THREAD

**Issue by mangopipeline** [MrKepzie/Natron#1235]
### Problem
the current implementation of this methods is some what short sided...
in asset management and pipeline work sometimes we need to publish and version the file from with the app this might mean saving comp_v1 as comp_v2 etc....

currently in gui mode there is no way to save the file to a custom location and having the projectName attribute update....

we could do a saveTempProject but that requires reopening the comp file.
**Expected behavior:** [What you expected to happen]
#Project is c:\comops\natron_v1.ntp
app1.saveProject('c:\comps\natron_v2.ntp")#save an rename the active app projectName param

**Actual behavior:** [What actually happened]
#Project is c:\comops\natron_v1.ntp
app1.saveProject('c:\comps\natron_v2.ntp")#save an rename the active app projectName param

#input is ignored and the file overwrites it self, or pops up a window if it's never been saved...

**Comment by MrKepzie** [comment]
Will fix for 2.0.1

**Comment by mangopipeline** [comment]
yay!!!
