### ISSUE TITLE
Rotos are not displayed in Dopesheet

### ISSUE THREAD

**Issue by PostPollux** [MrKepzie/Natron#1238]
### Problem

Rotos are not displayed in the Dopesheet

**Expected behavior:** [What you expected to happen]
I would like to see the Keyframes of my roto in the Dopesheet

**Actual behavior:** [What actually happened]
No rotos there...
### Steps to Reproduce
1. create a roto
2. animate it
3. open the dopesheet
### Versions
- **Natron version/commit** (they can be retrieved from the About Window): 
  tags/2.0.0 at version ca2c00bc5393b8c37197746e9a858d76cd969034
- **OS version:** 
  Windows 7

**Comment by MrKepzie** [comment]
This is because it's not implemented

**Comment by devernay** [comment]
This issue was moved to NatronGitHub/Natron#146
