### ISSUE TITLE
Natron crashes as soon as you key something in the roto node

### ISSUE THREAD

**Issue by PostPollux** [MrKepzie/Natron#1239]
### Problem

Natron crashes as soon as you hit "set key" on any parameter of the roto node. The autokeying of the shape works without problems.

### Steps to Reproduce

1. create a roto-node
2. create a roto shape
3. try to keyframe any parameter

### Versions

* **Natron version/commit** (they can be retrieved from the About Window): 
tags/2.0.0 at version ca2c00bc5393b8c37197746e9a858d76cd969034

* **OS version:** 
Windows 7

**Comment by MrKepzie** [comment]
Was fixed in https://github.com/MrKepzie/Natron/commit/9c4bcd2f5fb1f755bf5dffb8c488731711008e3f
