### ISSUE TITLE
Feather Roto Bug

### ISSUE THREAD

**Issue by PostPollux** [MrKepzie/Natron#1240]
### Problem

The Alpha of rotoshapes are buggy, when the feather areas are overlapping! 

**Expected behavior:** [What you expected to happen]
Perfectly smooth blending.

**Actual behavior:** [What actually happened]
### Steps to Reproduce
1. Make a roto
2. pull out the feather points
3. order them so that two feather areas are overlaping and look at the alpha

![bug](https://cloud.githubusercontent.com/assets/9008901/13853646/f52894e4-ec67-11e5-8281-0f137f61f3b8.jpeg)

In Nuke it looks like this:
![nuke_overlap](https://cloud.githubusercontent.com/assets/9008901/13860575/5af34db6-ec89-11e5-91b4-32c74db42545.png)
### Versions
- **Natron version/commit** (they can be retrieved from the About Window): 
  tags/2.0.0 at version ca2c00bc5393b8c37197746e9a858d76cd969034
- **OS version:** 
  Windows 7

**Comment by MrKepzie** [comment]
It's known, we have not yet identified if this is due to Cairo (the vector graphics library we use) or not

**Comment by devernay** [comment]
This issue was moved to NatronGitHub/Natron#147
