### ISSUE TITLE
Re-write ReadFFMPEG to be up to date with ffmpeg.c

### ISSUE THREAD

**Issue by manuelsongokuh** [MrKepzie/Natron#1244]
hi

i testing natron, i find strange 3 messages errors:
1 yellow warning:
rendered rectangle (0,0)-(960,540) contains NaN values.They have been converted to 1.

2 red error:
-... detected deconding stall, possibile file corruption
-... failed to seek frame: Operation not permitted

see my record screen
http://sendvid.com/7di9ka2c

the file footage MXF:
https://mega.nz/#!D0ojBJQA!W476CDKWyBbDgQWucTaQt0WDBr8OmvJX9tT20Wdt8oM

natron version is  4926612acbedc2831cb7617173a2cf0bf29063c6.

**Comment by olear** [comment]
FFmpeg has problems reading MXF files from Canon, this results in several issues. At the moment we are not sure how to resolve this (seems to be an issue with the codec), so I recommend you re-encode the footage in a more supported format, or just use an image sequence.

**Comment by manuelsongokuh** [comment]
hi olear
yes that is sure for image sequences, this is know, but i port to natron report bug issue, so natron will be best stable for future like as quality software ok?

i write here issue like as memo for issue for remember for future ok?

**Comment by devernay** [comment]
ReadFFmpeg will be rewritten from the ground up

**Comment by manuelsongokuh** [comment]
ok thank you devernay

**Comment by manuelsongokuh** [comment]
thank you for change title of issue..

**Comment by devernay** [comment]
see also https://github.com/MrKepzie/openfx-io/issues/15

**Comment by devernay** [comment]
stripped-down ffplay: https://github.com/devernay/ffplay

**Comment by devernay** [comment]
This issue was moved to NatronGitHub/Natron#148
