### ISSUE TITLE
Feature Request : Adding Scaling and rotation value in tracking node.

### ISSUE THREAD

**Issue by UttamPal** [MrKepzie/Natron#1246]
# Feature Request

Hi,

As i am tracking a footage with tracker its giving only x and y position. for scaling and rotation we have to do it manually.

![scale value in tracking node](https://cloud.githubusercontent.com/assets/17508717/13869343/961d4c46-ecf9-11e5-87d3-69a970b75a71.JPG)

If it can be done it will be very helpfull and saves much time. 

thanks

**Comment by MrKepzie** [comment]
Will be in the new tracker for 2.1
