### ISSUE TITLE
Python API Feature Request: add .sample(channel, x, y) to nodes?

### ISSUE THREAD

**Issue by ghost** [MrKepzie/Natron#1248]
Nuke has [`.sample(channel, x, y)` method](https://www.thefoundry.co.uk/products/nuke/developers/63/pythondevguide/image_data.html), would be nice to have it in Natron as well.

As for now, is there any different way to get a color of a pixel in Natron? Maybe a node that gives an array of ColorTuples?

Thanks!

**Comment by procedural** [comment]
Umm... ?

**Comment by MrKepzie** [comment]
I don't know what do you have in mind when using this but bear it mind it will require a rendering from the node and might be extremely slow if the image is not in the cache. 
Currently we do not provide means to access image pixels

**Comment by procedural** [comment]
>I don't know what do you have in mind when using this

Originally, I wanted to convert a color pixel have to [0-255] format, viewers show only [0.0-1.0]... But one can imagine other usage cases.

**Comment by MrKepzie** [comment]
Will add this

**Comment by JuusoKaari** [comment]
Any news on this one?

I would use this to create auto-crop tool with this idea:
1) Reformat image to 1px height horizontal line
2) Sample pixels to python
3) Get first non-zero values from start & end
4) Same for vertical space
5) Create the crop

**Comment by devernay** [comment]
@JuusoKaari this should be an OFX plugin. The Python API is not appropriate for this kind of task. Or use python inside an OFX plugin.
I never tried this, but it may do the job: https://libraries.io/github/gatgui/ofxpp
See also the discussion at https://forum.natron.fr/t/generate-content-from-pure-python-node/405

**Comment by JuusoKaari** [comment]
Thanks Devernay for the links! 
I really should look into the ofx for many other needs, but this particular thing I solved quite nicely with ImageStatistics -node & python by running a loop of pixel coordinates to the analyze area coordinates (while area size is set to a single 1x1 pixel), and storing the max value (i.e. the pixel rgb value) to a tuple.

**Comment by devernay** [comment]
This issue was moved to NatronGitHub/Natron#149
