### ISSUE TITLE
User Parameters: Tooltip of Group params get lost

### ISSUE THREAD

**Issue by PostPollux** [MrKepzie/Natron#1250]
### Problem
The tooltips of groups parameters get lost after export to a PyPlug. Looking in the exported file I find the following:
param.setHelp("")

### Steps to Reproduce

1. create a nodegroup
2. add a group param
3. type in some tooltip
4. export as PyPlug

### Versions

* **Natron version/commit** (they can be retrieved from the About Window): 
3783cc7130cd0f0cd482cae532d20d68f03fbd00

* **OS version:** 
Linux Manjaro

**Comment by MrKepzie** [comment]
I'm unable to reproduce here with these steps. 
1. Create a group node
2. Click Manage User Parameters
3. Add a "Group" parameter and set a tooltip
4. Export to PyPlug

**Comment by PostPollux** [comment]
mh, strange I now tested it here at workon windows and it works....
I will look into it on my linux system again, when I'm at home, maybe something else went wrong.

**Comment by MrKepzie** [comment]
Any news ?

**Comment by PostPollux** [comment]
No sorry, I hadn't had any time to test it. But I have a guess.
It was an older comp that I opened. So the group with it's tooltips had been created in an older version of Natron. Maybe that's the reason why something went wrong with the export. I'll test it again asap. Btw. groups still can't be edited...

**Comment by PostPollux** [comment]
I can't reproduce it, if I create a new PyPlug from scratch. So I guess you can close this one. I think, it was because it was a file created with an older Natron version...
