### ISSUE TITLE
reformat node loose parameter after saving/loading project

### ISSUE THREAD

**Issue by iscream75** [MrKepzie/Natron#1252]
### Problem

reformat node loose parameter after saving/loading project

**Expected behavior:**

remember the setting

**Actual behavior:** [What actually happened]
setting is reseted to 640*480

 

### Steps to Reproduce

1. [First Step]
create a reformat node , set it to the project resolution,save
2. [Second Step]
open your project
3. tadaaa!!

You may submit a link to any screenshots/videos that can be used to understand how to reproduce the issue.

### Versions

* **Natron version/commit** (they can be retrieved from the About Window): 
* **OS version:**

**Comment by MrKepzie** [comment]
Thought I fixed this, will check again.

**Comment by MrKepzie** [comment]
What version of Natron have you used ? I'm unable to reproduce the bug.
