### ISSUE TITLE
unknown media type error on installation

### ISSUE THREAD

**Issue by cg-cnu** [MrKepzie/Natron#1253]
### Problem

While installing natron v2.0.1-64bit on centos 7 am getting this error

Transaction test succeeded
Running transaction
  Updating   : Natron-2.0.1-1.x86_64     
Checking GCC compatibility for Natron ...

Unknown media type in type 'all/all' 
Unknown media type in type 'all/allfiles' 
Unknown media type in type 'uri/mms' 
Unknown media type in type 'uri/mmst' 
Unknown media type in type 'uri/mmsu' 
Unknown media type in type 'uri/pnm' 
Unknown media type in type 'uri/rtspt' 
Unknown media type in type 'uri/rtspu'

### Steps to Reproduce

1. Install Natron v2.0.1-64bit on centos 7

### Versions

* **Natron v2.0.1-64bit ** (they can be retrieved from the About Window): 
* **Centos 7:** 

But, natron is working fine after installation.

**Comment by olear** [comment]
Not an error. We run update desktop applications/mime on post install, what you see is the verbose output from the system commands. The best we can do is to redirect the output to /dev/null.
