### ISSUE TITLE
render fail

### ISSUE THREAD

**Issue by iscream75** [MrKepzie/Natron#1254]
render fail when preference is set to " render in a separate process"

**Comment by MrKepzie** [comment]
Can you specify steps to reproduce ? It does not fail here

**Comment by iscream75** [comment]
check render in a separate process option in the preferences, click render

**Comment by olear** [comment]
Works here using 2.0.1. Do you have an example project, or a way to replicate the issue with minimal nodes?

**Comment by iscream75** [comment]
the project 
https://drive.google.com/open?id=0B0i8DBtwQZ0-TmFWcjRhNEVuRWs

**Comment by iscream75** [comment]
minimal setup that fail
https://drive.google.com/open?id=0B0i8DBtwQZ0-UVhWT2xaT0UzaTg
proof : 
![000226](https://cloud.githubusercontent.com/assets/16254684/14043923/2c5ce140-f28a-11e5-8573-9d29a497489b.jpg)

**Comment by olear** [comment]
You don't have permissions to write to C:\

**Comment by iscream75** [comment]
what about D:/  
![000228](https://cloud.githubusercontent.com/assets/16254684/14044681/877cb880-f293-11e5-85fd-fe76c245adb4.jpg)

**Comment by olear** [comment]
If the rendering works in your home folder, but not in D:/whatever, you have a permission problem.

**Comment by olear** [comment]
Hmm, confirmed issue on Windows.

**Comment by MrKepzie** [comment]
fixed for 2.0.2
