### ISSUE TITLE
Alpha of roto shape gets cropped by its bounding box

### ISSUE THREAD

**Issue by PostPollux** [MrKepzie/Natron#1257]
And now the second:

### Problem
If the bg-input of the roto node is not connected the alpha will be cropped by the bounding box of the roto shape. I really can't imagine in which case you would want to have such a behavior. It took me a while until I figured out, that I have to connect the background input.
https://goo.gl/photos/i4DvcvG7xFEDFCpv7

**Expected behavior:** [What you expected to happen]
The Alpha data should be present in the whole image, not just in the area of the bounding box of the roto shape. So if there is no background connected, it should be the format of the project settings.

### Steps to Reproduce

1. create a roto node and shape
2. connect an invert node
3. watch the alpha of the invert node. Probably not, what you wanted...

### Versions
* **Natron version/commit** (they can be retrieved from the About Window): 
3783cc7130cd0f0cd482cae532d20d68f03fbd00

* **OS version:** 
Linux Manjaro and Windows

**Comment by MrKepzie** [comment]
This is related to https://github.com/MrKepzie/Natron/issues/224#issuecomment-200470648
Please note Frederic comment
