### ISSUE TITLE
Keyframing issue with rotos

### ISSUE THREAD

**Issue by PostPollux** [MrKepzie/Natron#1258]
Ah, yes, there was another important one:

### Problem
If I move a point on the spline, only this point gets keyframed in Natron, not the whole shape. This can lead to some unexpected interplations! Because if you move the whole shape in keyframe 1, then a few frames later just move two points which creates keyframe 2, and later on in keyframe 3 rotate the whole shape, all points but the two from keyframe 2 will interpolate between keyframe 1 and 3. But normally you would expect the whole shape to interpolate from keyframe 2 to keyframe 3. Some points interpolating different from others is definetely confusing!

https://goo.gl/photos/kk7ZKwbQ9Rto8fYB6

**Expected behavior:** [What you expected to happen]

Each keyframe should keyframe the whole shape, so that the whole shape is interplating from one keyframe to the next...

### Versions

* **Natron version/commit** (they can be retrieved from the About Window): 3783cc7130cd0f0cd482cae532d20d68f03fbd00

* **OS version:** 
Linux Manjaro and Windows

**Comment by MrKepzie** [comment]
Hmmm this is the case, all points are interpolated, whenever a key is set, all control points have a keyframe set on them. I will check what's going on, probably a bad interpolation mode chosen
