### ISSUE TITLE
TimeOffset RoD proble

### ISSUE THREAD

**Issue by JuusoKaari** [MrKepzie/Natron#1259]
### Problem

RoD (Region of Definition) won't offset when using TimeOffset -node.

**Expected behavior:** TimeOffset should affect RoD as well.

**Actual behavior:** The actual pixels offsets correctly in time, but RoD stays in place and crops the footage.

### Steps to Reproduce

1. Create any footage with animated RoD.
2. Add TimeOffset node and set offset value.
3. View the TimeOffset end result

![timeoffset_bbox_bug](https://cloud.githubusercontent.com/assets/17428352/14032424/6f87a87a-f21b-11e5-98ff-7fbab280bbd3.PNG)

### Versions

* **Natron version/commit** Stable 2.0 (5cf760179b8dc95e75fec3e281ea38b0f98bd0f6)
* **OS version:** Windows 10 64 bit

**Comment by MrKepzie** [comment]
Do you confirm that it only happens if  the generator (here Checkerboard1) RoD is set to the project format ?

**Comment by devernay** [comment]
fixed by https://github.com/devernay/openfx-misc/commit/b8fdcbe712d0554354a09b462973932d335954e3
