### ISSUE TITLE
WriteFFMPEG presets

### ISSUE THREAD

**Issue by MrKepzie** [MrKepzie/Natron#126]
I would like to add presets to the WriteFFMPEG node so that the list of parameters is less disturbing for the end user.
We would have to choose from the huge list of codecs/containers a (smaller) list of "presets", i.e: working formats which are known to provide good quality and are used widely.
I lack knowledge in most useful video formats that are used for post-production so I'm wondering if someone could come-up with a list of presets (codec/format/bitrate, etc…) (that must be available from the huge list existing already!).

I would then use this list to create the presets in the plug-in.
If people react fast enough we can incorporate this for the v1.

**Comment by devernay** [comment]
There are now presets in WriteFFmpeg (DNxHD is still disabled because it has color shifting, but we have ProRes, and a few lossless codecs).

Audio track may be supported in the near future.

XDCAM presets should come soon.
