### ISSUE TITLE
Roto manipulation "pause" Natron

### ISSUE THREAD

**Issue by iscream75** [MrKepzie/Natron#1260]
### Problem
Roto manipulation "pause" Natron

**Expected behavior:** [What you expected to happen]
I expect it to work near real time
**Actual behavior:** [What actually happened]
unusuable

### Steps to Reproduce
draw some roto shapes
select all point
move the gizmo
natron stop to respond, refresh or anything for 5 seconds then the gizmo is release somewhere or hooked to the mouse

See this video : 
https://drive.google.com/open?id=0B0i8DBtwQZ0-Vk9FSkd2V29WYUU

### Versions
win 7 x64 / gtx970 / natron 2.01 : 3783cc7130cd0f0cd482cae532d20d68f03fbd00.

**Comment by MrKepzie** [comment]
I cannot reproduce this bug
