### ISSUE TITLE
FeatReq: frame processing viewer options

### ISSUE THREAD

**Issue by iscream75** [MrKepzie/Natron#1261]
I think we should have 3 more option in the viewer
[No downsampling] : , so each calculated and cached tiles are relevant for the final result
[Full frame processing] so we can pan zoom in/out without recalculating anything
[aggressive caching] : you sometime need it for a short amount of time

**Comment by manuelsongokuh** [comment]
this is helpfully ...

**Comment by devernay** [comment]
should go with the Proxy mode rewrite.
see https://github.com/MrKepzie/Natron/issues/1314

**Comment by devernay** [comment]
I personally do not see what you mean by " [Full frame processing] so we can pan zoom in/out without recalculating anything". Do you mean calculate a full frame in low-resolution, and draw it in the background when panning/zooming?

**Comment by iscream75** [comment]
I mean that whatever the zoom level or displayed area, process the full
frame at full resolution. Once rendered and in cache the frame can be paned
zoomed, playback/viewer cache should obey this option too.
It make the display less interactive but you don't need to process things
when no parameter change. Hope it make sense.
Le 25 juin 2016 11:06 AM, "Frédéric Devernay" <notifications@github.com> a
écrit :

**Comment by MrKepzie** [comment]
Implemented

**Comment by lehuan5062** [comment]
Hello,
How can I activate the "full_frame_processing" mode?

I see a gear button on top of the viewer saying "when checked, the viewer will render the image in its entirety and not just visible portion". Is it the full frame processing? If it is, I checked it and the cache still re render when I'm zooming though.
