### ISSUE TITLE
[question] add minor feature for "keep orientation" or "rotate"?

### ISSUE THREAD

**Issue by manuelsongokuh** [MrKepzie/Natron#1262]
### Problem

maybe is missed to natron..OPTION for orientation readOIIO from image..

 * this is not a Crash.
 
#  *  solution: 1
### checkbox in panel of readOIIO..
,
,
#  *  solution: 2
### add node transform.... (this is add stuff..?)

# 
,

### Steps to Reproduce

1. [open Natron]
2. [add read]
3. [here]

i test:
gwenview: rotated
gimp: ask me rotate or keep orientation
showFoto: rotated
Krita: rotated
photoQT:keep orientation
Blender (UV/image editor) keep orientation
Natron: keep orientation

screenshot:
![natron-keep-orientation-rotated](https://cloud.githubusercontent.com/assets/12126929/14044975/449f90fc-f296-11e5-8521-c95fdd44ed9f.png)
![natron-keep-orientation-rotated-2](https://cloud.githubusercontent.com/assets/12126929/14044986/5b21ce62-f296-11e5-9935-acf9a7424dca.png)

### Versions

* **Natron 3783cc7130cd0f0cd482cae532d20d68f03fbd00.
* **OS version: linux

thank you for create to NATRON...

**Comment by MrKepzie** [comment]
This is called the Reformat node.
