### ISSUE TITLE
Natron as Flipbooker (enhancement) [Add cmd line parameters]

### ISSUE THREAD

**Issue by nicholascarroll** [MrKepzie/Natron#1265]
Natron is a good flipbooker. Once it loads it is really fast and it accepts a lot of file types. Please implement command line arguments for read file start and end frames, and frame rate, so that from terminal it can be called, something like 

> natron myfile####.exr 1-100 24

EXAMPLE USE CASE
You can configure Natron to be the Animation Player for Blender (Blender Preferences > System). This allows a convenient way to play the render output and if you want then save it and comp using Natron instead of the Blender compositor. This already works but...
...WITHOUT THIS ENHANCEMENT
you have to manually adjust the frame range in Natron, because it plays all frames matching the mask myfile####.exr, and that can include frames from previous renders.

**Comment by olear** [comment]
This could be scripted:
```shell
#!/bin/sh
NATRON="Natron"
TMP="/tmp/flipbook$$.py"
SEQ="$1"
FPS="$2"
FSTART="$3"
FSTOP="$4"

if [ -z "$SEQ" ] && [ -z "$FPS" ] && [ -z "$FSTART" ] && [ -z "$FSTOP" ]; then
  echo "Usage: flipbook.sh image_sequence fps start_frame end_frame"
  exit 1
fi

cat <<EOF >> "$TMP"
import NatronGui
reader = app.createNode("fr.inria.openfx.ReadOIIO")
viewer = app.getViewer("Viewer1")
reader = app.ReadOIIO1
reader.filename.set("${SEQ}")
reader.customFps.set(True)
reader.frameRate.set(${FPS})
viewer.setFrameRange(${FSTART},${FSTOP})
#viewer.connectInput(0,reader)
EOF

$NATRON -l "$TMP"
rm -f $TMP
exit 0

```
The only problem is that I don't know how to connect a node to a viewer ...

**Comment by nicholascarroll** [comment]
Yes that is a better way, thanks. I will try to expand on that, with Blender as use case. I'll upload what I make here.

**Comment by nicholascarroll** [comment]
looks like there is a bug attaching viewer to *readers*

**Comment by nicholascarroll** [comment]
I had a play and realized that in OSX the best way to do this is with the *open* command:
`open -a natron myimage.exr`
If you were passing in a script it would be:
`open -a natron -l myscript.py myimage.exr`
So it probably would be best to implement the framerange and fps params compiled into the natron binary.

Cheers

**Comment by nicholascarroll** [comment]
I noticed that Natron has a universal launch shell script now, and also I realized its of only marginal benefit to have OSX specific functionality for the open command. So, is it actually best to put this in the binary or just use the universal shell script?

**Comment by nicholascarroll** [comment]
Closing this because it the solution by olear is acceptable.

**Comment by mangopipeline** [comment]
While Olear solution is good, I'm not sure it should be acceptable, as this is very much tied to the the os...
people will have a need for this on all OS, windows for example would require a much different .bat solution.

A better solution might be to put together a python script, or a second binary that could simplify natron gui down to via more dedicated viewer like...

**Comment by nicholascarroll** [comment]
OK I will reopen this so that @MrKepzie can comment. My main concern about using Natron as a flipbooker is the startup time of the application.

**Comment by mangopipeline** [comment]
Yes it's a fair enough concern, I think if there was a option in the executable to launch in "fast" mode that be great. it would be a much larger scope, but ideally the frame flipper would not need all the same components as full on natron...
I like you think that with all the open source frame flippers having t been abandoned, Natron could be super useful in this space. and even if the startup is a bit slow, it would be a descent trade of for an open source solution :)

**Comment by devernay** [comment]
This issue was moved to NatronGitHub/Natron#151
