### ISSUE TITLE
Primatte OFX Fine Tuning Sliders bug

### ISSUE THREAD

**Issue by nicholascarroll** [MrKepzie/Natron#1266]
### Problem

In Primatte, when moving the *Fine Tuning Sliders* rapidly, the *From Tune* and *To Tune* flick over to displaying zero values, but the underlying value is still correct. 

**Expected behavior:**
The field should still display the colour in R, G, B fields.
<img width="400" alt="expected" src="https://cloud.githubusercontent.com/assets/1062708/13543474/aa93a42a-e2bf-11e5-86c6-9df07e743432.png">

**Actual behavior:**
All the R, G, B fields in this field go to zero.
<img width="400" alt="expected" src="https://cloud.githubusercontent.com/assets/1062708/13543484/ba1d7a38-e2bf-11e5-972d-416175dd1933.png">

### Steps to Reproduce

1. Get a key (using the Auto-Compute button or by picking the colour with Operation 'Select BG Color')
2. Set the Operation to 'Fine Tuning Sliders'
3. Go to the Expert tab.
4. Click on a pixel. This will set the values of *From Tune* and *To Tune*
5.  Move the L-poly (or M-poly or S-poly) slider fairly rapidly
The From Tune and To Tune suddenly go to zero!

### Versions
Natron Version 2.0.0 Snapshot RC4 
OSX 10.10.5

### Related Issue
#421 Color Knob bugs (Primatte OFX plugin Fine Tuning sliders dont work)
#1199 (closed to reopen fresh as this bug)

**Comment by MrKepzie** [comment]
Ok will check

**Comment by MrKepzie** [comment]
I cannot reproduce as of now. We will release a snapshot for 2.0.2 soon

**Comment by nicholascarroll** [comment]
ok

**Comment by nicholascarroll** [comment]
this looks fixed in latest snapshot.
