### ISSUE TITLE
Primatte Naked Viewer Clicks bug

### ISSUE THREAD

**Issue by nicholascarroll** [MrKepzie/Natron#1267]
### Problem
Any clicking in the viewer registers in Primatte but it would be a lot nicer if the control key was needed, like with other plugins. 

Without this fix, users keep accidentally passing clicks into Primate operations. Primatte is based around the idea of selecting an operation and then clicking in the viewer. But you also need to move around the viewer, move the wipe control etc, and although it the *Undo* works, Primatte can sometimes 'lose the plot' and you have to start again.  Also, it is best when plugins work in a consistent way.

The workaround is to minimise the Primatte panel in Natron when you are not performing a Primatte operation.

**Expected behavior:**
Clicking in the viewer should not pass the pixel value to Primatte unless Control/Command is held down.

**Actual behavior:** 
With all Primattes 'operations', naked clicks in the viewer update Primatte.
### Steps to Reproduce

1. In Primatte select any operation, say, *Select BG Color*
2. Click in the viewer /without holding Control/Command/ and Primatte set that pixel value as the BG colour

### Versions
Primatte version 5.1
Natron version 2.0 RC4
OSX 10.10.5

### Related Issue
#1199 (where this was first mentioned and discussed along with other issues)

**Comment by MrKepzie** [comment]
Generally this is on the plug-in side that this is done. There isn't much we can do about it! 

The only thing that could be doable on our side is to **NOT** issue a call to the penDown() action if Command/Control is not held, but that would be specific just for that plug-in....

**Comment by nicholascarroll** [comment]
Red Giant needs to fix it, thanks for your response. I am fine with the workaround. 

Many thank MrKepzie.
