### ISSUE TITLE
Primatte Doesn't Refresh Viewer after Update

### ISSUE THREAD

**Issue by nicholascarroll** [MrKepzie/Natron#1268]
### Problem

In Primatte, for most operations based on clicking in the viewer, you have to refresh the viewer each time to see the result.

**Expected behavior:**
Viewer should automatically update.

**Actual behavior:**
You pick a colour in the viewer and it doesn't change, until you refresh the viewer.

### Steps to Reproduce

1. In Primatte, choose *Select BG Colour* 
2. Click in the viewer on the background colour
3. Nothing happens! Or so it seems...
4. Refresh the viewer. You will see your selection applied - the background colour is keyed out.

Try different operations and some do have this problem, some do not.

### Versions
Primatte 5.1
Natron 2.0 RC4
OSX 10.10.5

### Related issue
This was originally mentioned in  #1199 along with other issues.

**Comment by MrKepzie** [comment]
I fixed this issue, however note that the same issue applies when you press the "Auto-Compute" button, because the property kOfxParamPropEvaluateOnChange is set to false on the AutoComputeEval button, hence when you click on it, Natron doesn't request for a render.

**Comment by nicholascarroll** [comment]
thanks
