### ISSUE TITLE
Preferences Option for Auto Dot Note when adding Write or Viewer Node (Enhancement)

### ISSUE THREAD

**Issue by nicholascarroll** [MrKepzie/Natron#1269]
### Problem

When adding a *Write* node, a *Dot* node is automatically added for you. No thanks! 
[EDIT: PLEASE ALLOW USER TO TOGGLE THIS VIA PREFS AND ALSO FOR VIEWERS]

**Expected behavior:** 
When adding a *Write* node, don't automatically add a *Dot*.

**Actual behavior:** 
Whenever you add a *Write* node, it always comes with a free *Dot* :-(

### Steps to Reproduce

1. Add a *Write* node
2. The *Dot* is automatically added

### Versions
Natron versions since before 2.0 and up to recent snapshots of RC4
OSX 10.10.5

**Comment by MrKepzie** [comment]
ok

**Comment by nicholascarroll** [comment]
Sorry, I should not presume that it's not useful per how others work. What i should be asking for is that this behaviour can be toggled via preferences. So that it would still go to the right hand side, but just no dot, and same for viewers.

**Comment by nicholascarroll** [comment]
thanks
