### ISSUE TITLE
LUE grading toolset for natron

### ISSUE THREAD

**Issue by mash-graz** [MrKepzie/Natron#1270]
Mads Hagbarth Lund wrote a very nice grading add one for nuke, that is freely available:

http://hagbarth.net/?p=1001

it would be very nice, if we could use this toolset in natron too.
a port to natron doesn't look trivial. some needed API features are missing. but it could be a very useful practical test case to iron out compatibility issues and natron shortcomings.

using LUE with natron could be very useful to many users, because it doesn't work on the non-commercial edition of nuke and its artificial python restrictions.

**Comment by PostPollux** [comment]
Wow, I didn't know LUE, but it looks very good. Would be pretty amazing to have something like this in Natron as this would be a good grading solution for the Linux users out there...

**Comment by devernay** [comment]
This issue was moved to NatronGitHub/Natron#152
