### ISSUE TITLE
saveProject api call seems to be broken...

### ISSUE THREAD

**Issue by mangopipeline** [MrKepzie/Natron#1272]
### Problem
0n 2.0.1 saveProject was changed so that in gui mode a supplied path would not be ingored and instead the file would save in the given location...

this works well the first time a file is saved, but after that the file will no longer save.

Describe the problem or suggestion here.

**Expected behavior:** [What you expected to happen]
if i save an untitled file via app.savePrjoect(r'c:\file_v1.ntp') and then i save again using app.saveProject(r'c:\file_v2.ntp') the file should be renamed to file_v2.ntp and there should be a file in the file system to match

**Actual behavior:** [What actually happened]
first file is saved, but subsequent call to saveProject do nothing

### Steps to Reproduce

1. open natron to untitled scene
2. run code app1.saveProject(r'c:\temp\file1.ntp')
3. after file is saved run code app1.saveProject(r'c:\temp\file2.ntp')

### Versions

Natron version 2.0.1 Release.
windows 10

**Comment by MrKepzie** [comment]
Will fix for 2.0.2
