### ISSUE TITLE
Python Api save project crashed with unicode strings....

### ISSUE THREAD

**Issue by mangopipeline** [MrKepzie/Natron#1273]
### Problem
if the path passed to natron is a unicode string example u'c:\\temp\\filename.ntp' natron explodes into death....

**Expected behavior:** [What you expected to happen]
file should save
**Actual behavior:** [What actually happened]
natron dies

### Steps to Reproduce

1. open natron to untitles scene
2. run code app1.saveProject(u'c:\\temp\\myfile.ntp')
3. watch natron die

### Versions
natron 2.0.1 release
windows 10

**Comment by MrKepzie** [comment]
Will check

**Comment by MrKepzie** [comment]
Fixed
