### ISSUE TITLE
crashed ever times..see crash ID

### ISSUE THREAD

**Issue by manuelsongokuh** [MrKepzie/Natron#1274]
see report  
Crash ID = 666842be-8708-d787-30e31192-7042e15d
Crash ID = 361db062-bb5a-69b8-56d41c68-49030705
Crash ID = 408d7dca-1f33-b6bb-66f53d2d-2ce35095
Crash ID = 430e8077-d8d5-31e2-7ef5b284-3bdf52a8

version natron is 2.0.1

**Comment by olear** [comment]
So, what are you doing? And what plugins are you using?

**Comment by manuelsongokuh** [comment]
here file ntp(zip)
[tutorial-sw-2016.ntp.zip](https://github.com/MrKepzie/Natron/files/195485/tutorial-sw-2016.ntp.zip)

**Comment by olear** [comment]
Thanks, will check. It's probably the Polar node.

**Comment by manuelsongokuh** [comment]
i did viewer connect to merge and not go to polar but that is crashed..without passed to node polar...you can find true problem ok?
thank you

**Comment by olear** [comment]
It's either Roll or Polar, since the crash is in ImageMagick (Core). I know that Polar had some issues in the past. Will try to find the bug.

**Comment by manuelsongokuh** [comment]
ok, i need node: roll and polar, module..this is new tutorial for natron vs adobe effect after contribute for all to use Natron.. ok?

**Comment by olear** [comment]
Could you try this : http://downloads.natron.fr/~olear/OFX/openfx-arena/Arena.ofx.bundle-2.1.0-trunk-Linux-x86-release-64.tgz (backup existing Arena.ofx.bundle)

**Comment by manuelsongokuh** [comment]
i did this trunk arena and backup original arena of 2.0.1
but it is crashed:
Crash ID = 5dc11228-7a80-4980-66a10e94-6ca15624

**Comment by manuelsongokuh** [comment]
[vokoscreen-2016-03-31_20-20-50.mkv.zip](https://github.com/MrKepzie/Natron/files/198330/vokoscreen-2016-03-31_20-20-50.mkv.zip)

**Comment by olear** [comment]
The problem is in the Polar node, and it happens when I use the distort function from Magick++
```
magick/resample.c:273: DestroyResampleFilter: Assertion `resample_filter->signature == 0xabacadabUL' failed.
```
Only happens on playback, not while rendering. Will try to find a solution, at best a workaround.

**Comment by olear** [comment]
The problem seems to be threads (OpenMP) related, if I force the plugins in your project to 1 thread I get no crash. So currently I will check if this problem is related to all or just some plugins, and disable threading where needed. This will sadly give a performance penalty, but rather that then stability issues. Will also contact the ImageMagick devs to see if they have any suggestions/fixes.

**Comment by manuelsongokuh** [comment]
hi
thank you for testing for magick++ and openmp thank you again, but this is good sound for find bug or problem, this is important for future fix bug to became in stable. this is true good news. then i will wait for find fixed i will back testing for tutorial ok? for now i will use 1 thread for moment ok?

**Comment by olear** [comment]
Try this: http://downloads.natron.fr/~olear/OFX/openfx-arena/Arena.ofx.bundle-2.1.0-trunk2-Linux-x86-release-64.tgz

Should resolve the crash (I hope).

**Comment by manuelsongokuh** [comment]
i will back my home and testing on night ok?

**Comment by manuelsongokuh** [comment]
hi
i'm back here, tested 5 minutes the result is not crashed..WOW..
i need try "stress" testing long time. i will back here to confirm resolved or not ok?
:+1:

**Comment by olear** [comment]
Great, I will make sure the changes are part of Natron 2.0.2.
