### ISSUE TITLE
Crash when Render With No Writer

### ISSUE THREAD

**Issue by nicholascarroll** [MrKepzie/Natron#1275]
### Problem

I didn't realize I had no write node and hit Render. Natron crashed. 

**Expected behavior:**
Nothing, or a message that there is no writer.

**Actual behavior:**
crashes

 * If your problem is a crash in an official release/snapshot, please include verbose output from the application [crash report](https://github.com/MrKepzie/Natron/files/196935/6805AABB-1AC4-4146-AF72-0C559BF0ED23.zip)
 
### Steps to Reproduce

1. don't add a writer
2. hit *Render all Writers*
3. Crash bang! 
Reproduces every time.

### Versions
v2.0 rc4 9 march dev build
OSX 10.10.5

**Comment by nicholascarroll** [comment]
[crash report](https://github.com/MrKepzie/Natron/files/196935/6805AABB-1AC4-4146-AF72-0C559BF0ED23.zip)

**Comment by olear** [comment]
This was fixed in 2.0.1 if I'm not mistaken

**Comment by olear** [comment]
Confirmed fixed in 2.0.1.
