### ISSUE TITLE
shuffle loose mapping if source lost

### ISSUE THREAD

**Issue by korabkoff** [MrKepzie/Natron#1276]
### Problem

If natron can't find source (multyLayered EXR ) from read node, suffle node loose it's settings.

**Expected behavior:** [What you expected to happen]
I expect shuffle store it's mapping in case of loosing source file giving a chance to find new path to the EXR file.

**Actual behavior:** [What actually happened]

For example I want move project to another location, collect all files and open in different environments. Or network disk with source EXR lost because of network issues in time of opening file. In result all shuffle nodes need to be setup one more time - 10 to 50 times actually (((.

### Steps to Reproduce

1. Open Natron, Load EXR in read node and extract some layers with shuffle. Save file.
2. Change EXR location or name. Load saved file. Look at shuffle settings - it is reset to default.

### Versions
Natron version 2.0.0 RC.
OS: Win7 x64

**Comment by MrKepzie** [comment]
It's know, for 2.0.2 layers menus and channel menus are now "persistant" and you can copy paste safely any portion of graph without loosing settings.
