### ISSUE TITLE
Embed IPython Shell in Natron (enhancement)

### ISSUE THREAD

**Issue by nicholascarroll** [MrKepzie/Natron#1278]
### Problem

Would be really good to embed IPython shell in Natron.
IPython has many conveniences like: autocomplete, object introspection, filename completion, good history recall, using your external editor, reference previous outputs as variables, and special features  for lazy people.

**Without this Enhancment** 
For the occasional scripter these conveniences can make the difference between being able to write the script or not.

If not IPython, even a basic python shell would be good enough, because IPython can be run from within it:

```
import IPython
IPython.start_ipython(argv=[])
```

**Comment by nicholascarroll** [comment]
The script editor and console should be using the same session. So that the function to execute the script should send the text to the console. Like in the python mode of emacs, not like how blender works.

**Comment by devernay** [comment]
This issue was moved to NatronGitHub/Natron#153
