### ISSUE TITLE
Time on the text node incorrect result

### ISSUE THREAD

**Issue by mccartnm** [MrKepzie/Natron#1283]
Hello again!
I've set up a preview generator script and am seeing improper results from the text node when using a high frame number cut.

Expression:
`ret = str(frame)`

Expected after evaluation (frame on the timeline):
`1132933`

Received:
`132930.0`

It's rounding down to the tens place. Wondering if we're hitting a limit on the `frame` value casting. Something like that.

**Comment by olear** [comment]
Seems like the "limit" is 999999.
![framelimit](https://cloud.githubusercontent.com/assets/7461595/14376900/c9ad2ecc-fd6c-11e5-9dcf-dfc83db16608.png)

**Comment by MrKepzie** [comment]
is it a python limit or an issue in image magick ?

**Comment by olear** [comment]
Has to be python, as the node outputs what it gets.

**Comment by mccartnm** [comment]
I found a workaround but it isn't pretty. (Calling `render()r` every frame in order to set the frame number right before). EXR->Temp EXR with proper frame extracted from the file (ouch)->.mp4.

These are production shots so I can't adjust their values but I would love to see the node handle it. Unless there is another way to query for the frame in an expression?

**Comment by MrKepzie** [comment]
Think i've found the bug

**Comment by MrKepzie** [comment]
This is fixed for 2.0.2

**Comment by mccartnm** [comment]
Excellent!
