### ISSUE TITLE
Suggestion - Replace help comment in expression pop-up for linking

### ISSUE THREAD

**Issue by ThomasMorley-T3D** [MrKepzie/Natron#1285]
Please ask questions ("how do I...?") on the [forum](http://forum.natron.fr), not by filing issues.

Make concrete suggestions for fixing the code ("here is a patch") by filing
a [pull request](https://github.com/MrKepzie/Natron/pull/new/master), not an issue.

### Suggestion

The animation button on properties hvae been removed on Natron 2.0 please replace the "help" comment on the expression pop-up to reflect the new "Hold Ctrl button and then drag the parameter field to create a link"

### Versions

Natron 2.01

Linux Mint 17.3

**Comment by ThomasMorley-T3D** [comment]
![screenshot from 2016-04-09 23 46 26](https://cloud.githubusercontent.com/assets/11800663/14408134/5888992e-fead-11e5-9d1c-892d54f19a92.png)

**Comment by MrKepzie** [comment]
fixed
