### ISSUE TITLE
Issue reporter fails: Request Entity Too Large

### ISSUE THREAD

**Issue by scribblemaniac** [MrKepzie/Natron#1287]
### Problem

When trying to submit an error report, either with natron or manually at http://breakpad.natron.fr/form/, the server returns a error.

**Expected behavior:**
Upon submitting I expect that it will say something like "Thanks for your help! :smile:"

**Actual behavior:**
When submitting through Natron, a Dialog called "Dump Unloading" pops up with the following text:
```
Network error: (299) Error downloading http://breakpad.natron.fr/submit - server replied: Request Entity Too Large
Dump file is located at /var/folders/fn/4myzbqz57fv1s5q5r07cl64r0000gn/T/7088ECA3-A064-4167-9D5A-D5546FC64612.dmp
You can submit it directly to the developers by filling out the form at

http://breakpad.natron.fr/form/?product=Natron&version=2.0.1 Release&id=7088ECA3-A064-4167-9D5A-D5546FC64612

Please add any comment describing the issue and the state of the application at the moment it crashed.
```

When I follow the link and attempt to submit it manually, I get a "413 - Request Entity Too Large" error.

### Steps to Reproduce

1. Attempt to submit a .dmp file of size 243KB.

### Versions

Natron version 2.0.1 Release
Mac OS X 10.11.4

**Comment by olear** [comment]
Should be fixed, sorry for the inconvenience.

**Comment by scribblemaniac** [comment]
I can confirm that this has been fixed. Thank you for your prompt response!
