### ISSUE TITLE
WriteFFmpeg drops last few frames

### ISSUE THREAD

**Issue by ngilles** [MrKepzie/Natron#1288]
### Problem

When rendering using libx264 in the output of a WriteFFmpeg, the last few frames aren't getting written to the output file. In my case I have an input video of 255 frames, but the resulting output gets "truncated" at 233 frames. When rendering to some other types (i.e. images) I successfully get all the frames.

### Versions

* **Natron version/commit :** 2.0.1 - 3783cc7130cd0f0cd482cae532d20d68f03fbd00
* **OS version :** Fedora 23

**Comment by MrKepzie** [comment]
It's a known issue in 2.0.1, will be fixed in 2.0.2 (to be released soon)

**Comment by olear** [comment]
Should be fixed in latest RB-2.0 snapshot, @ngilles could you test and confirm?

http://downloads.natron.fr/Linux/snapshots/RB-2.0/64bit/files/
