### ISSUE TITLE
"A recent auto-save of ... was found" dialog uses the wrong font

### ISSUE THREAD

**Issue by devernay** [MrKepzie/Natron#1289]
Bug present in the master branch

Probably a stylesheet issue ?

**Comment by olear** [comment]
Looks good (like any other dialog in Natron) on Linux:
![autosave](https://cloud.githubusercontent.com/assets/7461595/14561253/46490584-0315-11e6-87f3-528340d56d7f.png)

**Comment by devernay** [comment]
Looks wrong on Mac. Can you test on Windows?
The dialog "An auto-save was restored succesfully" is also affected

**Comment by devernay** [comment]
it seems to be wrong only on some OSX versions... weird

**Comment by olear** [comment]
Could it be different fontconfig/freetype setup/configuration?

**Comment by MrKepzie** [comment]
for what I remember it started to be like this after this commit: https://github.com/MrKepzie/Natron/commit/94cbc81ffc219d1ff87a2196c9537eb7e0094c65
