### ISSUE TITLE
Is there any way to achieve the functions like "vReveal"

### ISSUE THREAD

**Issue by j16180339887** [MrKepzie/Natron#1291]
I got some blurry old videos recently.

I found that "vReveal" can fix the resolution and quality of an old video.

Is there any way to achieve the functions like "vReveal" does ?

Thanks.

**Comment by devernay** [comment]
There are lots of free and commercial plugins around to do that job inside Natron (denoising, deblurring, resizing...), so there is no simple answer to that question. If you learn how to use Natron (there are a few tutorials around), you will probably find the answer by yourself.
