### ISSUE TITLE
Render progress bar doest'n work

### ISSUE THREAD

**Issue by korabkoff** [MrKepzie/Natron#1292]
During render progress bar doest'n update as well as time remaining - NA

### Versions

Natron version 2.0.1 Release.
OS: Mac osx El Capitan version 10.11.4 (15E65) 
MacBook Pro (13-inch, Late 2011) 
Graphic: Intel HD Graphics 3000 512 MB

**Comment by MrKepzie** [comment]
Not very explicit. It works well here. Can you describe the problem and/or provide a video/ screenshot ?

**Comment by korabkoff** [comment]
Progress bar dosn't updated during rendering. On screenshot rendering sequence at frames 10+ and no sighn of that in progressbar
http://clip2net.com/s/3x1qTkP

**Comment by olear** [comment]
Unable to replicate on OSX 10.6 using Natron 2.0.1.

So Natron renderes everything, but Progress stays as Queued on your installation?

**Comment by korabkoff** [comment]
Exactly!

**Comment by MrKepzie** [comment]
unable to reproduce on snapshots
