### ISSUE TITLE
read from write checkbox in write node

### ISSUE THREAD

**Issue by korabkoff** [MrKepzie/Natron#1293]
It is common workflow to create read from just rendered write. There is even a lessons to create read node and copy parameters from write with Python for nuke.

**Comment by devernay** [comment]
In Natron, you can create a Read node and link it to the Write node using its "sync" input. You can even link the filename parameter to this of the write node. Does that fulfill your needs?

**Comment by korabkoff** [comment]
In repeatedly used complex scripts it perfectly fine. But for rapid developing and testing purpose it is to slow and overwhelming with excessive parameters.

**Comment by MrKepzie** [comment]
Implemented in 2.1
