### ISSUE TITLE
Shorter Channel selector dropdown list with channel knobs for each layer

### ISSUE THREAD

**Issue by korabkoff** [MrKepzie/Natron#1296]
Currently it is a very annoying to select particular channel in grade, shuffle etc. in times of working with  layers in .EXR. In case of 20 layers it is 80 channels to scroll down (((
![natron_channel-selector_current](https://cloud.githubusercontent.com/assets/16881668/14629792/c7a4c768-0611-11e6-85d4-c445dc7e41f1.jpg)

It can be just list of layers with knobs for each channel 
![natron_channel-selector_enhancement](https://cloud.githubusercontent.com/assets/16881668/14629903/8648fab8-0612-11e6-8f50-5f8b5ffa24fa.jpg)
![natron_channel-selector_enhancement_minimal](https://cloud.githubusercontent.com/assets/16881668/14629902/8648ed52-0612-11e6-91cb-60ae676e381a.jpg)

**Comment by devernay** [comment]
This issue was moved to NatronGitHub/Natron#155
