### ISSUE TITLE
Proxy mode for rendering to disk

### ISSUE THREAD

**Issue by JuusoKaari** [MrKepzie/Natron#1314]
### Problem

I'd want to render out my comp in proxy mode to files on disk (for example to check it half res on Premiere timeline), but the only way to do so seems to be playing it in the viewer when Writer node is active. I mainly like to render my stuff from commandline, so it would be great to be able to use the proxy rendering without the GUI as well.

**Expected behavior:** I could launch my commandline render with a proxy parameter like:
`NatronRenderer -w MyWriter -proxy 2 /Users/Me/MyNatronProjects/MyProject.ntp`
which would use 1/2 proxy mode. And then `-proxy 4` would make it 1/4 etc.
### Versions
- **Natron version/commit** May 11 2016 from the source code branch tags/2.0.3 at version c4fc51c.
- **OS version:** Windows 10

**Comment by MrKepzie** [comment]
Fair enough, I can add that to the write node and command line arguments. 
Note that with Natron 2.1,  the write node does no longer render while rendering with the viewer and only renders when a render is explicitly requested. Also there is a new "Read File"  checkbox to read-back the file from disk to check that the file was correctly written.

**Comment by devernay** [comment]
We will refactor the way proxy rendering is working in Natron (probably for 2.2)

**Comment by devernay** [comment]
see also https://github.com/MrKepzie/Natron/issues/1314

**Comment by JuusoKaari** [comment]
Are there any estimates when we might see this feature come alive? Still aiming at 2.2 release?

**Comment by devernay** [comment]
This issue was moved to NatronGitHub/Natron#156
