### ISSUE TITLE
iDistort rgb multiply problem

### ISSUE THREAD

**Issue by JuusoKaari** [MrKepzie/Natron#1315]
### Problem

IDistort node changes also rgb values in Natron 2.0.3.

**Expected behavior:** IDistort should only push pixels in 2d space based on uv channels.

**Actual behavior:** In addition to pushing pixels it multiplies the source input rgb with the uv input alpha.

### Steps to Reproduce

1. Create checkerboard 
2. Add iDistort with SeNoise in the uv input
3. Checkerboard rgb gets multiplied by the noise alpha channel

### Versions

* **Natron version/commit** May 11 2016 from the source code branch tags/2.0.3 at version c4fc51c.
* **OS version:** Windows 10

**Comment by hyperfx** [comment]
I can verify this happens on Windows 7, as well. However, by plugging my source footage into the UV of the iDistort, the darkening does not happen. So maybe this is more related to the SeNoise node and what it's outputting?

**Comment by JuusoKaari** [comment]
Yes, if there is only RGB in the UV input, this does not happen, but with RGBA input it multiplies the source RGB with Alpha from the UV input. SeNoise outputs RGBA. Easy way to work around this is to insert 1 to Alpha in the UV data (with shuffle node for example) before the iDistort.

**Comment by devernay** [comment]
This is a feature, not a bug!
Many UV maps also contain an alpha channel, and some UV maps are even premultiplied (thus the "Unpremult UV" checkbox.
Isn't the tooltip on the "Alpha Channel" choice clear enough? Do you want to suggest another UI?
Simply select "1" as the Alpha Channel to disable this feature.
