### ISSUE TITLE
Placement of playback buttons

### ISSUE THREAD

**Issue by hyperfx** [MrKepzie/Natron#1317]
### Problem

The buttons are too far apart.

**Expected behavior:** The playback buttons should be neatly arranged next to each other so we don't have to move the mouse pointer across the screen to easily jump around the shot.

**Actual behavior:** The playback buttons are dispersed along the entire toolbar under the viewer. The first and last frame buttons are at far ends, play is in the middle, and step forward and backward is off to the right side of the increments buttons.

Could they all be closer together?

![natron_time_buttons_01](https://cloud.githubusercontent.com/assets/5239056/15414317/59637584-1dee-11e6-9493-12ad9d71d5c3.jpg)

* **Natron version/commit** 2.0.3 release 
* **OS version:** Windows 7

**Comment by olear** [comment]
Like this?:
![untitled](https://cloud.githubusercontent.com/assets/7461595/15450144/80b59d54-1f94-11e6-879d-81f3542a5798.png)

Will commit if ok for "everybody".

**Comment by devernay** [comment]
Looks good to me! (hi Sean, thanks for contributing!)

**Comment by devernay** [comment]
plz commit to 2.0 if possible

**Comment by olear** [comment]
Ok, should I also move the step buttons?

**Comment by olear** [comment]
![untitled2](https://cloud.githubusercontent.com/assets/7461595/15450380/4acd0c08-1f9a-11e6-9c4d-ff6999533171.png)

Also moved the step buttons, now looks more logical (in my opinion).

**Comment by blackearth2014** [comment]
The latter is the best layout and less mouse movement.

**Comment by hyperfx** [comment]
Spectacular, thank you! Perfect!

**Comment by nicholascarroll** [comment]
also the in/out points, you would usually set these at the same time, so that would mean they should be next to each other.
