### ISSUE TITLE
Using ReadFFmpeg prevents Natron 2.0.3 process to shutdown

### ISSUE THREAD

**Issue by JuusoKaari** [MrKepzie/Natron#1319]
### Problem

If I have loaded anything with ReadFFmpeg node during a Natron session, closing the GUI window won't close the Natron-bin.exe process. Problematic it becomes as it also happens in commandline renders - although they finish succesfully and all frames get written to the disk, the process just hangs there at 100% not closing, thus not responding to my "render farm" python script.

**Expected behavior:** Using ReadFFmpeg wouldn't prevent closing down the process.

**Actual behavior:** Using ReadFFmpeg prevents Natron 2.0.3 process to shutdown

### Steps to Reproduce

1. Open Natron 2.0.3
2. Load anything with ReadFFmpeg node
3. Try to close the program

### Versions

* **Natron version/commit** May 11 2016 from the source code branch tags/2.0.3 at version c4fc51c
* **OS version:** Windows 10

**Comment by MrKepzie** [comment]
Works fine on os x with crash reporter enabled

**Comment by MrKepzie** [comment]
Can you check on linux ?

**Comment by olear** [comment]
It's a Windows issue.

**Comment by MrKepzie** [comment]
I cannot reproduce on Windows in debug mode with breakpad enabled on RB-2.0. I read a video with ReadFFmpeg and everything is fine

**Comment by MrKepzie** [comment]
Hmm I cannot even reproduce on the release 2.0.3 on Windows 7 with a basic graph setup ReadFFMPEG --> WriteFFMPEG. I tried both GUI and command line and everything went fine

**Comment by olear** [comment]
That's odd. I tested the 2.0.3 release build and a master build on Friday. I just added a video file and closed Natron, the terminal window never quits (also tried without crashreporter, same result).

**Comment by MrKepzie** [comment]
It's either a library version (i didnt update ffmpeg for a while) or something in windows configuration that's different

**Comment by MrKepzie** [comment]
Was fixed and is scheduled for 2.0.4
