### ISSUE TITLE
ReadNode and external plugins

### ISSUE THREAD

**Issue by devernay** [MrKepzie/Natron#1320]
https://github.com/olear/openfx-arena/issues/236

If I use read plugins not bundled with Natron I'm unable to load the supported images through 'r' or Image/Read:

`ReadNode.cpp:594: void Natron::ReadNodePrivate::refreshPluginSelectorKnob(): Assertion `fileKnob' failed.`

Either don't associate external read plugins with files or fall back to 2.0 behaviour if plugin is not part of the ReadNode?

master branch.

**Comment by MrKepzie** [comment]
what plugin triggers this ?

**Comment by olear** [comment]
Any plugin not added in the ReadNode.(https://github.com/MrKepzie/Natron/blob/master/Engine/ReadNode.cpp#L157).

**Comment by MrKepzie** [comment]
So which one in particular it is

**Comment by olear** [comment]
Currently the only Read plugin I have that's not "added" to the ReadNode is ReadPDF, you can test with that.
