### ISSUE TITLE
Render via ffmpeg throwing 'Picture size 0x0 is invalid'

### ISSUE THREAD

**Issue by mccartnm** [MrKepzie/Natron#1321]
Hey crew,

Working on more preview generating and going from exr -> mov but the NatronRenderer.exe isn't liking the mov format and some of the codecs when in the terminal. I have have an exr (zip1 compression) piping into the WriteFFmpeg node and have the render threads set to 1. In the GUI with the same settings everything runs fine and the result is fantastic but when used via script the error above gets shot out and no rendering happens.

Let me know if there's something else you need or want me to try.
Cheers

**Comment by mccartnm** [comment]
Note:
The format: (index 5) QuickTime / MOV [mov]
The Codec: (index 2) apcn Apple ProRes 422

**Comment by MrKepzie** [comment]
Please indicate platform. Can you also send the project so we can debug it at natron-contact@inria.fr

**Comment by olear** [comment]
Tried to re-produce but ProRes422 works fine from the terminal on Natron 2.0.3 in Windows here, also tried various input formats.

What version of Natron are you using?

**Comment by mccartnm** [comment]
I wish I could but it's on an internal production network. I work for StereoD in Toronto. We're using Windows 7 machines with Natron Encoded Version: 20001

**Comment by mccartnm** [comment]
Ahh well it's just tough to get the newest versions in house

**Comment by olear** [comment]
2.0.1 introduced a couple of bugs when using WriteFFmpeg, you should upgrade to 2.0.3 if possible.

**Comment by mccartnm** [comment]
Right on! Good to know. Thanks for the heads up I'll try to bring it in now.

**Comment by mccartnm** [comment]
Okay brought it in. Now The WriteOIIO is occasionally giving of a persistant message:
`rendered rectangle (0, 0)-(551,420) contains NaN values. They have been converted to 1`

I'm sure that's more about my setup than anything. But the 0x0 error still persists too.

Full error:
`[IMGUTILS @ 000000006254e580] Picture size 0x0 is invalid`

I removed the python to actually set the format and size and it does go through the render but the file is corrupt (~256bytes) I'll keep testing to see what I can find.

**Comment by mccartnm** [comment]
Ahh my script seemed to have the formatType set improperly so I believe that was the heart of my issue. that combined with 2.0.3 seems to have given me what I need to finish off the task. Thank you again for your help.
