### ISSUE TITLE
Unsupported file extension: mp4

### ISSUE THREAD

**Issue by nicholascarroll** [MrKepzie/Natron#1322]
In the write node, I set the output to mp4. but it gives an error that it is not a supported coded.

In WriteOIIO it is there in the dropdown list but it errors with 'Unsupported file extension: mp4'
In WriteFFmpeg the *Format* dropdown has mp4 in the list of values but when selected says 'error: the selected codec is not supported in this container'.

This is on Linux, Natron 2.0.3.

**Comment by nicholascarroll** [comment]
I set the extension to .mov and chose AVC1 and it did write out without error. However, the FPS on the resulting file is at 29.7 even though i set it to 30. And the file doesn't play properly: it just shows the first frame as it plays through. The file size however is what I expected.

**Comment by nicholascarroll** [comment]
This failed because the codec inside was the default - Prores 4444. Set it to  h.264/mpeg-4 and it writes OK. I'll close this cos I can see similar issue was logged before and could not be fixed because of framework limitations.

**Comment by devernay** [comment]
fixed in c6798de
