### ISSUE TITLE
Warning when writing a sequence to single image file

### ISSUE THREAD

**Issue by nicholascarroll** [MrKepzie/Natron#1324]
When writing image files sequences, like jpg, exr, dpx etc, the user needs to put the numbering mask in, eg:

So into the filename
myfile.exr
they need to add the mask #### so it looks like this:
myfile.####.exr

But if they forget, start their render, and go off to lunch, they will come back and find all their frames were overwritten onto the same file.

It is easy for the application to recognize this user error and do something about it. I suggest raising a warning message when they hit Render, to say "you are writing multiple images to a single image file". Or, automatically recognize that it has just written to a file, and in the same render, should not write to the same file, but instead should create a new file with an automatically generated number.

**Comment by MrKepzie** [comment]
Implemented
