### ISSUE TITLE
Most parameters are not responding to mouseover or keyboard changes in 2.0.4 release

### ISSUE THREAD

**Issue by blackearth2014** [MrKepzie/Natron#1327]
I am on a Mac and I recently downloaded Natron 2.0.4 release. I notice this issue with the Transform node that some of the boxes for value inputs does not respond. The Transform node's scale parameters responds to mouseover and keyboard changes. Then I had later tried some other nodes with the same issue. The knobs to change the valus works fine, but the manual inputs are not functioning properly.

**Comment by olear** [comment]
Confirmed.

**Comment by olear** [comment]
The bug is in the KnobDouble's, Int's work fine.
