### ISSUE TITLE
Problem grabbing output arrow of read node

### ISSUE THREAD

**Issue by nicholascarroll** [MrKepzie/Natron#1328]
### Problem

The output arrow that comes out the bottom of every node is *very* short. Sometimes the text of the read node filename overflows onto it and then you can't grab the arrow with your mouse. 

**Expected behavior:** 
Expect that the arrow is 'on top' of the text so that you can still grab it, or that it comes out a bit longer.

**Actual behavior:**
When you grab the arrow it grabs the node instead. See the included screenshot. 

### Steps to Reproduce

1. Find an image file 
2. read it into natron. 
3. try to pull the output arrow and it will only move the node
screenshot attached

### Versions
natron 2.0.3
linux mint
![screenshot from 2016-06-04 12 50 25](https://cloud.githubusercontent.com/assets/1062708/15797223/164fb510-2a54-11e6-83ae-fc75f664ea07.png)

**Comment by olear** [comment]
So, I can make the arrow longer, but it does not solve the issue. Even if the arrow is not covered by the text, dragging it will move the node, if you drag the tip of the arrow it works. 

But this is not a workable solution as the length of the arrow is fixed, and if you get a really long filename it will cover the arrow again.

![nodearrow](https://cloud.githubusercontent.com/assets/7461595/15801085/c9b74b6e-2a8a-11e6-9ee0-2dd4a2fd41dc.png)

The best solution will of course be to limit the content of the node to the boundaries, or scale the node to the content.

Will see what I can do. A quick workaround would be to just remove the filename from the node, to be honest I don't see the big need for the filename in the node.

**Comment by nicholascarroll** [comment]
Maybe an option to truncate the long text and show the full text in a tooltip? Then, people could go ahead and write really lengthly descriptions in the *Label* field on the node tab. A tooltip would also have the benefit of letting you read a node's description without zooming in.

For this specific issue perhaps the answer is simply for the user to revert to keyboard shortcuts. Looking through the Shortcuts Editor I don't find any existing shortcut to connect nodes. Also, when nodes are close together you can't access their arrows. Below is a screenshot showing how the blueNode, which has the same inputs as the redNode, is surrounded and you can't grab its arrows. So I would like to propose here a shortcut to grab node inputs/output arrows. And that would solve this issue. 

![screenshot from 2016-06-05 13 54 30](https://cloud.githubusercontent.com/assets/1062708/15803524/2dcb1cda-2b25-11e6-93fe-298b8e47e80a.png)

I propose the way the shortcut would work is you hover over the node, then hit some key (ambidextrous, perhaps y or u). This brings up a menu listing the inputs and outputs, like this:
  | Source|
  | Mask  |
  | Output|
And then you click on you want to attach it to your mouse, the same as if you had grabbed that arrow with your mouse.

**Comment by manuelsongokuh** [comment]
hey,
sorry i'm interesting this issue, but i need talk this issue:
this is actual natron
![node-arrow-01-fix](https://cloud.githubusercontent.com/assets/12126929/15892373/a1cfa2c6-2d79-11e6-9e6b-684b3bd0c9f6.png)


this is propose
![node-arrow-02-fix](https://cloud.githubusercontent.com/assets/12126929/15892436/e4ef9b60-2d79-11e6-9daa-ac767ef00287.png)
this is for help handing with mouse, little  the arrow longer, this is good for intuitive (mouse).

instead for long letter in label will be good idea:
![node-arrow-03-fix](https://cloud.githubusercontent.com/assets/12126929/15892670/45b887ee-2d7b-11e6-9ef2-9a030b1d1c9c.png)
this is reducer letter limit from box.

 this is pop-up balloon (style natron)
![node-arrow-04-fix](https://cloud.githubusercontent.com/assets/12126929/15892689/614d8432-2d7b-11e6-8a45-37a6beb22862.png)

is not it bad idea..?

**Comment by nicholascarroll** [comment]
@manuelsongokuh  I thought pop-up balloon ('tooltip') at first then I realized that its not really needed because you zoom in and out fast and easily. I agree the output arrow is too short and I think there should be a setting *Output Arrow Length* in  *User Parameters > Nodegraph*.

What do you think of my proposal above to have a shortcut key to pop up the arrows?

**Comment by MrKepzie** [comment]
The thing is that the shortcut you describe requires first a keyboard interaction and then mouse interaction. We need 2 in 1 here it's either keyboard all the way or mouse all the way

**Comment by nicholascarroll** [comment]
Or is this issue maybe of no real impact? In every case, when you wanted to grab the output arrow of a node, you could simply have grabbed the input of node you wanted to connect to.

The case I put above, of nodes being so close together, doesn't happen either because you can zoom right in, grab it, and zoom out while still holding it.

So I will close this issue.

**Comment by olear** [comment]
The arrows are a usability issue, but it's no blocker.
