### ISSUE TITLE
Add preference to display drive letters instead of network share name

### ISSUE THREAD

**Issue by Phantom-Studio** [MrKepzie/Natron#1332]
Hello,
it would be nice to add a feature who allow relative network path for readers and writers.

Let me be a bit more precise, in current version 2.0.5 when i pick a file for a read node (Z:/My_project/file.exr), natron replace it by \\My_Server\My_project\file.exr  

It is not an issue for most user i think, but in our company, we work in multiples offices, and we sync the files between servers, and our servers do not have the same name.

So when in office A the path \\My_Server\My_project\file.exr is correct it is not in office B where it should be \\My_Server_2\My_project\file.exr

Is there a way to add an option in preference to let us choose if we want to use NetworkDrives or full network path ?

**Comment by MrKepzie** [comment]
Can't you make a project variable that contains \My_Server\ and replace all file paths as such:

    [MyServerVariable]\My_project\file.exr

You then just have to update the MyServerVariable to point to the correct location. 

We could add a preferences to show driver letters instead of server names but at first it felt like driver letters would be more local than a server name;)

**Comment by Phantom-Studio** [comment]
Yes we can do this, but honestly we don t want to do this for each comp, even it s quick to do it s take time. 
And it will not be efficient for us .
On all our offices , we have the same letter for network drive .
We use mixed os for rendering (win7,fedora23/osX) and we have path mapping in deadline who replace z:/ by /mnt/work or /Volumes/work, 
So a variable in natron project will not be the most efficient way ,

If i am not clear, i can be more precise in french , let me know .
