### ISSUE TITLE
not work to warn for new version 2.0.2..why?

### ISSUE THREAD

**Issue by manuelsongokuh** [MrKepzie/Natron#1333]
Hi I do reopen this issue, not close PLEASE! Before feedback me please!
then I repeat:
-my preferences is enable to check for new version.
-Natron 2.0.2 did not "warn me if there is new version" so I ask here WHY NOT WORK IT?

same problem Natron 2.0.1
same problem Natron 2.0.2
now Natron is 2.0.5 but I used from NatronSetup then what is problem from?
ONE OF YOU TRY NATRON 2.0.2 Enable check if new version and nothing warn it so that is problem.. 
Do you understand?

 No close here not close here not close here, do you understand?thank you

**Comment by olear** [comment]
So, it seems that 2.0.1/2.0.2/2.03 don't work when checking for updates, I see "Checking for updates..." in the splashscreen, but that's it. I did check the master branch and it works fine there.

Btw, don't create new issues for existing ones, we will see your comments even if it's closed.

**Comment by MrKepzie** [comment]
This is fixed upstream, so I close this bug report.

**Comment by manuelsongokuh** [comment]
Here that is it!!! I was reason!! Finally there are feedback...thank you but please don't to be poor feedback ok?because Notre same issue and it did close as fast so this is not gentle ok?to be calm and patience because I want NATRON to be best and stable ok?thank you

**Comment by manuelsongokuh** [comment]
i'm back here because there is problem for Natron version 2.0.5 Release NOT WORK FOR NEW VERSIONE 2.1 AND 2.1.1..
i will new issue or here discussion ?

**Comment by olear** [comment]
I will check the issue tomorrow. Worked last time I tested it, but seems broken (again).

**Comment by manuelsongokuh** [comment]
ok i'm stop version 2.0.5 nothing warn me for new version (2.1 or 2.1.1)..
