### ISSUE TITLE
Project settings are not visible.

### ISSUE THREAD

**Issue by lcenzoredl** [MrKepzie/Natron#1334]
### Problem

If you don't use properties bin, you can't see the project settings. Project setting displays only in properties bin.

### Steps to Reproduce

1. Close the Properties Bin tab.
2. Ctrl+DoubleClick on any node to open it's properties in a separate window - it ok
3. Try to open Project Settings in menu or press S hot key - nothing happens.

You may submit a link to any screenshots/videos that can be used to understand how to reproduce the issue.

Here the link to my layout, I use it in Nuke - https://dl.dropboxusercontent.com/u/697415/censored.nl

Actually I have 2 additional requests, which is use full when you working without Properties Bin:

1. Open node's properties in a separate window with simple DoubleClick or with Ctr+Click - not with Ctrl+DoubleClick like now.

2. Opened window must have a size which contains all it's properties. For now it works only after you open node's properties second time.

### Versions

Natron 2.0.5, Windows 7 x64.

**Comment by MrKepzie** [comment]
Good feedback, will fix the project properties. 
For the additional request 1. I don't know what you suggest because currently double clicking is already reserved for opening a panel in the properties bin. Should it make it floating automatically if the properties bin is not visible ?

2. is a bug

**Comment by lcenzoredl** [comment]
Hello!

About double click, yes it work when you have a properties bin already
opened. But I prefer work without it, to have more space for large network
and image.
So, to open properties of a node I need to press ctrl and double click to
open window with properties.
I think it would be better open window with double click only, without ctrl
or if I press CTRL I want to use single click (Ctrl+Click)

I hope you understand my interpretation of English language :)

I try to integrate Natron to our pipeline, so I think I can send more feed
back to you.

Thank you!

Сб, 11 июня 2016 г. в 16:47, Alexandre Gauthier <notifications@github.com>:
