### ISSUE TITLE
Where is the SlitScan OFX Misc plugin?

### ISSUE THREAD

**Issue by zalavariandris** [MrKepzie/Natron#1335]
There is s SlitScan plugin listed in the mist ofx blugins.
I checked it inside the Natron plugins folder, and the misc.ofx.bundle contains the png files for the slit scan plugin, but still there is no button to create a slitscan node.
I am on OSX, Natron version 2.0.5.

**Comment by MrKepzie** [comment]
The slitscan node is unimplemented and not available;)
