### ISSUE TITLE
kOfxParamPropParametricInteractBackground not supported

### ISSUE THREAD

**Issue by devernay** [MrKepzie/Natron#1336]
### Problem

Note that this property is only for ParametricParams, and should be used as the background for the curve editor. The Natron code seems to mix this with parameter interacts (which replace the parameter GUI completely), since the same getCustomOverlayInteractEntryPoint function is used for both (this one is NOT an overlay, but a background interact!)

The ColorLookup plugin, when compiled in debug mode, sets this property, but the draw function is never called by Natron.

Related issue:  https://github.com/MrKepzie/Natron/issues/450
### Versions

* **Natron version/commit** (they can be retrieved from the About Window): master
* **OS version:**

**Comment by MrKepzie** [comment]
It is working now
