### ISSUE TITLE
Feather a shape inward does not work

### ISSUE THREAD

**Issue by chrishuf** [MrKepzie/Natron#1337]
Not sure if this is a bug or a feature request :)
Feathering a shape inward does create a solid shape
![feather_bug](https://cloud.githubusercontent.com/assets/8084022/15987009/ea42914c-3019-11e6-98c2-ef86b068e4d5.jpg)

Thanks for all the efforts you put in this project

**Comment by MrKepzie** [comment]
Negative feather have never been working in Natron, this is because of the renderer we use internally.  See related issue https://github.com/MrKepzie/Natron/issues/1240

**Comment by chrishuf** [comment]
Not sure if this would help, but what about using the feather points as the shape ponits and the original points as the feather endpoints as soon as the feather is inward ? or is this hard to program ?

**Comment by devernay** [comment]
@chrishuf rather hard to program, because feather points could alternatively go in/out.
A new Roto rendering engine is in preparation for 2.2

**Comment by devernay** [comment]
This issue was moved to NatronGitHub/Natron#157
