### ISSUE TITLE
Preview on read file menu freeze Natron 2.1.0 snapshot

### ISSUE THREAD

**Issue by adallafontana** [MrKepzie/Natron#1338]
Natron-201606091348-a9589bee606d7950f302553f95b59a00a0cea992-Linux-x86_64bit

OS Ubuntu 16.04

Tested on 2 machines:

Read -- select file on menu -- open preview -- Natron freeze ( no automatic bug report because I need force exit)

**Comment by MrKepzie** [comment]
It's probably already fixed, we will retrigger a new snapshot

**Comment by adallafontana** [comment]
Ok, I close this issue, in case it persist yet, I will revert on.
tnx
