### ISSUE TITLE
No suitable decoder found

### ISSUE THREAD

**Issue by nitsch** [MrKepzie/Natron#1344]
I just updated from a working x64 Windows installation of Natron 2.0.2 to version 2.0.5 using Natron's maintenance tool. I updated all of the components. Now I am getting "No plugin capable of decoding XXX files was found" as in #630, no matter which image types I am trying to load in a Read node. It worked fine with 2.0.2 prior to the update.

**Comment by MrKepzie** [comment]
Try a clean install, we probably updated a DLL in our build but forgot to update the tag in the updates so you still have the old DLLs. If still failing, post again.

**Comment by olear** [comment]
Open NatronSetup, select 'Package Manager', remove 'Natron Libraries', next, update, restart. Select 'Package Manager', add 'Natron Libraries', next, update, finish.

Now try running Natron again.

**Comment by MrKepzie** [comment]
Will close as this is not an issue related with the code

**Comment by nitsch** [comment]
@olear That does not seem to work. The package manager says it will remove the libraries but never does so.

@MrKepzie I am having trouble registering to download the installer. I am just redirected to empty pages all the time, not receiving any confirmation emails either. I am a bit pressed for time right now, so I cannot pursue this any longer. It seems that version 2.0.5 will have to wait for now. ;-) I will give it another try when I have more time.

**Comment by olear** [comment]
Send me an email (olear at dracolinux dot org) with your username on natron.fr and I will manually reset your account.

**Comment by nitsch** [comment]
@MrKepzie You might want to reopen this. The problem remains, even with a fresh install of Natron 2.0.5 x64 (thanks for the help @olear) on this Windows 7 machine.

I still had the installer for 2.0.1 x64 on my disk, so I installed that for testing and that version works. Updating to 2.0.5 breaks the Read node again.

**Comment by olear** [comment]
That's odd. I just installed 2.0.5 (installer+portable) on Win7 x64 and the Read node works fine here.

Could you try removing HOME_FOLDER/AppData/Local/INRIA ?

**Comment by nitsch** [comment]
Removing that AppData directory did it. Thanks.
