### ISSUE TITLE
Master Beta Snapshot: PNG Sequence loading errors

### ISSUE THREAD

**Issue by blackearth2014** [MrKepzie/Natron#1346]
Master beta Snapshot (Natron-201606151150-17e02a773a12cca87332d93c59b6b461dc6c9330) is having trouble loading my png sequence. Some files won't load past 70-80 frames.

![master snapshot - readoiio bug](https://cloud.githubusercontent.com/assets/7956901/16087780/3aff9730-32f2-11e6-8959-c089eb0bef29.png)

**Comment by MrKepzie** [comment]
Can you be more explicit ? Some pngs of your sequence some others don't ?

**Comment by blackearth2014** [comment]
I am sorry. I was on a conference call and typing at the same time. The attached image is an online sequence I use to test Natron's tracker node. The ReadOIIO node recognizes the length of the sequence but when the play button pressed, it only loads the first 75 frames and that error pops up. The previous Master beta snapshot didn't have this problem.

![hcw_archaeological_dig_hd 0000](https://cloud.githubusercontent.com/assets/7956901/16089029/6d095644-32f7-11e6-994a-80e3b894de3f.png)

**Comment by MrKepzie** [comment]
In the Read node, you have a "Decoder" parameter where you can select which decoder internally is used for PNG. By default now it is our own ReadPNG and not ReadOIIO. You can try with both and see if it differs.

**Comment by MrKepzie** [comment]
Can you give me a link to this PNG sequence  ?

**Comment by blackearth2014** [comment]
Here iy is http://www.hollywoodcamerawork.com/greenscreenplates.html.

**Comment by blackearth2014** [comment]
The ReadOIIO works great. How in the future will anyone know which one to use? Is there something in PNG meta data that we should be looking for so that I can make it known on NatronNation?

**Comment by MrKepzie** [comment]
Omar, can you screencast the bug because I'm not able to reproduce on my mac

**Comment by blackearth2014** [comment]
Here are the screencasts you have requested.

link 1 @ https://youtu.be/k1UA3V-4VNI - using the reformat node with the default decoder
link 2 @ https://youtu.be/EoesJeGYjbs - using the default decoder

**Comment by olear** [comment]
This should be resolved, I'm not able to replicate using latest master using the same image sequence. Please test a new snapshot when it's uploaded.

**Comment by olear** [comment]
Close, see #1353
