### ISSUE TITLE
Master Beta Snapshot: Tracker update is not analyzing the frames when buttoned pressed

### ISSUE THREAD

**Issue by blackearth2014** [MrKepzie/Natron#1348]
The updated tracker node is not analyzing the frames. The attached image is a screenshot of how the viewer looks after to seconds. I am using a clip from my iphone.

![tracker node wont track](https://cloud.githubusercontent.com/assets/7956901/16089338/99b43802-32f8-11e6-9f45-d073a07324f7.png)

**Comment by bonalex01** [comment]
I second this but with slightly different behavior (v2.1 build june 2nd)
For me it usually starts tracking then when it fails (changing target) then SOMETIMES it won't restart. It may be  related with the value of the "enable" checkbox of the tracker that has been automatically set to "false" when track stopped.
Restarting tracking at a keyframe/ a non keyframe already tracked/ a non keyframe non tracked seems to influence behavior of tracking restart too.
User interface issue is "play" button becomes orange then falls back to grey without anything happening. Red color of "play" arrow is not of obvious meaning either
So it might be also a user (me) and/or documentation issue to understand the meaning of orange and red :-)
But this new tracker seems to be a great addition to me.

Sorry if this report is too long, it is nearly my first post on github, so I may not be aware of some good practices

**Comment by MrKepzie** [comment]
@blackearth2014 It was just a small bug with the button that wouldn't work due to today recent changes. I fixed it. 

@bonalex01 I added a Auto-Key Enabled parameter to enable/disable to the auto-keying of the Enabled parameter which may be undesired. By default it is turned off.
