### ISSUE TITLE
Natron-201606151308-1a... dosen't start

### ISSUE THREAD

**Issue by adallafontana** [MrKepzie/Natron#1349]
version: Natron-201606151308-1a14f8493e896c984cc0afe6b539ef9f03fd6638-Linux-x86_64bit

OS Ubuntu 16.04

Natron Version 2.1.0
Copyright (C) 2016 the Natron developers
>>>Use the --help or -h option to print usage.<<<
Py_GetProgramName is /home/aleubu5/Natron2/bin/Natron
Py_GetPrefix is /home/aleubu5/Natron2
Py_GetExecPrefix is /home/aleubu5/Natron2
Py_GetProgramFullPath is /home/aleubu5/Natron2/bin/Natron
Py_GetPath is /home/aleubu5/Natron2/bin/../lib/python2.7:/home/aleubu5/Natron2/bin/../Plugins:/home/aleubu5/Natron2/lib/python27.zip:/home/aleubu5/Natron2/lib/python2.7/:/home/aleubu5/Natron2/lib/python2.7/plat-linux2:/home/aleubu5/Natron2/lib/python2.7/lib-tk:/home/aleubu5/Natron2/lib/python2.7/lib-old:/home/aleubu5/Natron2/lib/python2.7/lib-dynload
Py_GetPythonHome is ../lib
Python library is in /home/aleubu5/Natron2/lib/python2.7/site-packages
Failed to connect local socket to IPC_COM

**Comment by olear** [comment]
Known issue, the latest Linux snapshot don't start due to WritePNG.

**Comment by adallafontana** [comment]
ok, I waiting the next one.
