### ISSUE TITLE
retime error

### ISSUE THREAD

**Issue by humbabanon** [MrKepzie/Natron#1350]
Please ask questions ("how do I...?") on the [forum](http://forum.natron.fr), not by filing issues.

Make concrete suggestions for fixing the code ("here is a patch") by filing
a [pull request](https://github.com/MrKepzie/Natron/pull/new/master), not an issue.

### Problem

     Retime error when using more than two keys on speed curve

Describe the problem or suggestion here.

**Expected behavior:** [What you expected to happen]

     Have an image sequence input that loops, use the retime function vary the apparent speed of the animation over time using key-frames on the speed slider. May use various values for retime with various interpolations on the time graph for the speed. 

**Actual behavior:** [What actually happened]

     retime function behaves as expected until a third value for the speed is keyed, at which point the output from the function is blank and the function causes the error "retime1 error: getFramesNeeded action failed". If interpolation of all the key-frames are changed to "constant" then the function will work, but if any point has a non-constant interpolation the function will cause an error with more than 2 key-frames. 

 * If your problem is a crash in an official release/snapshot, please include verbose output from the application
 from a terminal if possible.  If you also submitted a crash report, indicate the CrashID if possible.
 
 * If you need to report a compilation issue, please create a [gist](https://gist.github.com)
 that contains the _full_ verbose build log.
 
 * If your problem is a crash in a build that you made yourself, please create a [gist](https://gist.github.com)
 that contains a _full_ backtrace.

### Steps to Reproduce

     open an image sequence (png used here) and place a retime function in the output path. Add two key-frames with different speeds. Then add a third key-frame at which point an error will appear on the retime function. Go to curve editor and change the interpolation of the key-frames to constant and the error should cease.

You may submit a link to any screenshots/videos that can be used to understand how to reproduce the issue.

     http://i.imgur.com/QnRlNmD.png

### Versions

* **Natron version/commit** (they can be retrieved from the About Window):
     2.0.5 release 
* **OS version:**
     Linux Mint (mate) 17.2

**Comment by MrKepzie** [comment]
Was fixed
