### ISSUE TITLE
Option in preferences to descrease nodes size and disable nodes icons. To save up space in graph

### ISSUE THREAD

**Issue by Ambassy** [MrKepzie/Natron#1357]
Every time i launch natron for a complex compo i think about decreasing the size of nodes in node graph. 
Can we have an option in preferences where i can go and set some size like 20*12 
 to decrease the nodes size in graph and disable node icons please. So that when i set smaller size the nodes occupy a small space in the graph. This feature can be a space saver in case of larger comps

But this might not change the usual default, this must be set by a user if he wills.

**Comment by sozap** [comment]
If it's in user's preferences, when someone will open your comp on another computer, all the node will be messed up , don't they ? Maybe a per-project settings ?

**Comment by nicholascarroll** [comment]
Node icons can be already be disabled Preferences > Appearance > Node Graph *Display plugin icon on nodegraph*

**Comment by devernay** [comment]
This issue was moved to NatronGitHub/Natron#158
