### ISSUE TITLE
Roto with jagged edges

### ISSUE THREAD

**Issue by bonalex01** [MrKepzie/Natron#1358]
### Problem

Roto has jagged edges, seemingly generated in the anti-aliasing area

**Expected behavior:**
Roto edges should be smoothly antialiased even without feather

**Actual behavior:** [What actually happened]
just a guess: It looks like the ramp in intensity of the anti aliasing would be inverted. Pixels are computed in the right place but intensity is "inverted"

![jagged_roto01](https://cloud.githubusercontent.com/assets/7674649/16227531/57db3c60-37b1-11e6-86f0-e020aa1fb48d.jpg)

 ### Steps to Reproduce
1. create any roto with oblique lines
2. zoom in to have a close look
### Versions

natron 204,210 Windows

**Comment by MrKepzie** [comment]
This is a known bug in cairo, the library we use to rasterise the shapes. This is related to #1240

**Comment by devernay** [comment]
This issue was moved to NatronGitHub/Natron#159
