### ISSUE TITLE
Transform interact in Roto difficult to manipulate when hidden by roto shapes

### ISSUE THREAD

**Issue by bonalex01** [MrKepzie/Natron#1360]
FEATURE REQUEST

The transform gizmo is very GOOD and far superior to Nuke's one. But in roto when the area selected is very small it becomes difficult to locate the cursor inside the gizmo to switch in "MOVE_X/Y" mode.
An easy solution might be to enable   the "MOVE_X/Y" everywhere except on the hotspots of the gizmo. 
(This can interfere with the bug of resized handles in the roto node)

### Steps to Reproduce

1. select some very close vertices of a roto
2. enable the transform box
3. try to move those vertices without zooming in the view

### Versions

204 210 Windows

**Comment by MrKepzie** [comment]
I don't understand the issue, can you make a screencast illustrating the issue ?

**Comment by MrKepzie** [comment]
I cannot reproduce this bug

**Comment by MrKepzie** [comment]
Ok, you can now hold CTRL to force interaction of the Transform over the roto-shapes
