### ISSUE TITLE
TRACKER choose the algo

### ISSUE THREAD

**Issue by bonalex01** [MrKepzie/Natron#1362]
FEATURE REQUEST

the ability to choose from several algos in Natron  2.0 was very GOOD with the information explaining their strong points. If it's "easy" to get this back in Natron 2.1 it may be welcome.
If the Blender engine is completely different then it's definitely NOT a priority request.

** version
210

**Comment by MrKepzie** [comment]
Libmv works completely differently, there is a single algorithm so it's not possible to have it back;)
