### ISSUE TITLE
ROTO MotionBlur

### ISSUE THREAD

**Issue by bonalex01** [MrKepzie/Natron#1365]
FEATURE REQUEST
I can't seem to find an option to enable the motion blur for the rotos. I mean the motion blur for the motion of the vertices themselves.
It's really cumbersome to cheat with a directional blur (expression linked with a tracker) after the roto node.

I used to think it was a tough one as it was missing on the first versions of NUKE.
But I realize that it might be achievable by cheating the interpolation of the point/feather_point of each vertex. This might not be the best implementation (overall and concatenation wise furthermore) but probably pretty cheap.

**Comment by MrKepzie** [comment]
It is almost implemented but unfinished, see #1008
