### ISSUE TITLE
REMOVE ANIMATION

### ISSUE THREAD

**Issue by bonalex01** [MrKepzie/Natron#1366]
### Problem

when "Remove Animation" is triggered for a specific knob

**Expected behavior.**
the value that is kept is the value at the current time be it a keyframe or not

**Actual behavior:**
it falls back to some strange value that is not even the underlying value before keyframes were created.

### Versions

* **Natron version/commit** (they can be retrieved from the About Window): 210
* **OS version:** windows

**Comment by bonalex01** [comment]
a WORKAROUND is as below
duplicate node remove animation then copy value from the duplicate node.

**Comment by MrKepzie** [comment]
Fixed for 2.1
