### ISSUE TITLE
CORNER PIN

### ISSUE THREAD

**Issue by bonalex01** [MrKepzie/Natron#1367]
BEHAVIOR / BUG

### Problem
The 'copy "To" Points' button copies the whole animation instead of the values at the current time.

**Expected behavior:** [What you expected to happen]
Copying values at the current time is the expected behavior as it allows to easyly create a reference frame.
The behavior is made problematic due to the bug "REMOVE ANIMATION" that doesn't work.

### Versions

* **Natron version/commit** 210
* **OS version:** Windows

**Comment by MrKepzie** [comment]
I think the bug is rather than the remove animation feature is not working properly. It is expected that a copy should copy the entire state of the parameter isn't it ?

**Comment by devernay** [comment]
We can make two buttons:
* Copy "To" Points (Values)
* Copy "To" Points (Animated)
does that sound OK?
