### ISSUE TITLE
Wrong copy/paste keys behavior in dopesheet and curve editor

### ISSUE THREAD

**Issue by bonalex01** [MrKepzie/Natron#1368]
### Problem
Copy /paste keys doesn't work well either in DOPESHEET or CURVE EDITOR

**Expected behavior:** [What you expected to happen]
Select a bunch of keyframes on MULTIPLE TRACKS
copy paste and the animation is copied on the same track NAMES (as long as they are opened and selected in the DOPESHEET/ANIMATION EDITOR)

It's important to be able to paste on knobs with same names on another Node. (e.g. to copy animation from a cornerpin to another cornerpin.
DISPARITYKILLER We had a more specific bug with DisparityKiller where animation was swapped between 2 of the channels of the cornerpin.

Probably the only case when we should be able to "dumb" paste the keys is when source is only one curve AND to only one curve.

**Actual behavior:** [What actually happened]
paste in the DOPESHEET: keyframes are created but values are all zeros
paste in CURVE EDITOR error "you must select a curve first" even if only ONE track is involved at copy and the same track is selected at paste

BEHAVIOR/DOCS The paste (that is partially working in dopesheet) pastes time offseted according to current time slider this is very GOOD. Can this be overridden to "absolute paste mode" with some keyboard shortcut modifier ? CTRL+ALT+V or whatever.

### Steps to Reproduce

1. select keys on multiple tracks
2. paste

### Versions

* **Natron version/commit** (they can be retrieved from the About Window): 204 210
* **OS version:** Windows

**Comment by MrKepzie** [comment]
So now you can paste relative (CTRL+V) or absolute (CTRL+SHIFT+V). The value is also preserved (won't be 0). You must select in the tree on the left the knob's dimension onto which to paste the keyframes (you can select multiple knobs).
