### ISSUE TITLE
Shadertoy doesn't works, Natron-201606212010

### ISSUE THREAD

**Issue by adallafontana** [MrKepzie/Natron#1369]
Natron-201606212010-3618ea8c8d8b99562aabd09e1bfa859408a9a306-Linux-x86_64bit

Failed to create an instance of net.sf.openfx.Shadertoy:
Error: Description (kOfxActionLoad and kOfxActionDescribe) failed while loading net.sf.openfx.Shadertoy.

**Comment by olear** [comment]
This has been fixed, next snapshot will feature a working Shadertoy.
