### ISSUE TITLE
NatronRenderer filename number warning ref issue  #1324

### ISSUE THREAD

**Issue by nicholascarroll** [MrKepzie/Natron#1372]
After implementation of warning about not having a numbered writer filename, issue  #1324, if you use NatronRenderer command, then it presents that warning. Right after, it says 'Natron said Yes', which seems positive, however it then hangs. At least it did on mine.
It was on OSX 10.10.5 dev snapshot 15 june 16

**Comment by olear** [comment]
This has been fixed.
