### ISSUE TITLE
paramSetValue* triggers render too soon

### ISSUE THREAD

**Issue by devernay** [MrKepzie/Natron#1373]
### Summary

paramSetValue* calls inside the generic Begin/End Instance Changed actions should not trigger a render until EndInstanceChanged is reached.

Besides, all instance changed action have to be done before calling render.

(Some of the things mentionned below may already work this way in Natron, but I am listing the full expected behavior for reference)

### Problem

If a param is kOfxParamPropEvaluateOnChange, a paramSetValue in the current version of Natron triggers an *immediate* kOfxImageEffectActionRender, and probably also a kOfxActionInstanceChanged, even if it is made inside a kOfxActionBeginInstanceChanged/kOfxActionEndInstanceChanged pair

**Expected behavior:**

- The instanceChanged and render calls should be delayed until kOfxActionEndInstanceChanged is reached. http://openeffects.org/documentation/reference/ch13s06.html

- first, *all* the setValue calls that were made inside the kOfxActionBeginInstanceChanged/kOfxActionEndInstanceChanged pair should trigger a *group* of kOfxActionInstanceChanged that are made inside a *single* kOfxActionBeginInstanceChanged/kOfxActionEndInstanceChanged pair (to avoid triggering even more renders if there are even more paramSetValue* calls during this sequence)

- once the stack of instancechanged calls to process is empty, a render can be triggered.

That way, we minimize the number of useless renders (which are trivially obsoleted by the next paramSetValue), and make everything more interactive.

### Versions

* **Natron version/commit** (they can be retrieved from the About Window): master
* **OS version:**

**Comment by MrKepzie** [comment]
Fixed in https://github.com/MrKepzie/Natron/commit/df35ff5757513c94a53147dcab5fc0c54794c676
