### ISSUE TITLE
CornerPin 4 non selectable

### ISSUE THREAD

**Issue by blackearth2014** [MrKepzie/Natron#1383]
When adjusting the CornerPins in the "From" editor to reshape the connected image, Pin 4 is not allowing me to select it to do a recompute.

![cornerpin 4 non selectable](https://cloud.githubusercontent.com/assets/7956901/16435918/aec3768a-3d67-11e6-84e9-2658d503f0f9.png)

One time it worked and the other times it won't highlight or nonthing.

**Comment by MrKepzie** [comment]
Can you describe the steps to reproduce ? I can't seem to be able to

**Comment by blackearth2014** [comment]
Today's snapshot seemed to have fixed it.
