### ISSUE TITLE
Tracker: CenterViewer & Track Marker Focus

### ISSUE THREAD

**Issue by blackearth2014** [MrKepzie/Natron#1387]
The CenterViewer button is not engaging or working when tracking. Also, when a marker is inserted, it gets deselected. You have to select it again in order to track.

**Comment by MrKepzie** [comment]
To me the center viewer button works correctly, though it only works during tracking. I will fix the second part

**Comment by blackearth2014** [comment]
Is the Center Viewer feature when the square window pops up and it is only the tracker moving. If so, then I misunderstood the meaning compared to Blender lock to track feature.

**Comment by MrKepzie** [comment]
Center Viewer means that the window of the viewport will follow the track motion while tracking.
