### ISSUE TITLE
Natron-201606302040 Text OFX works only 1 of 3  

### ISSUE THREAD

**Issue by adallafontana** [MrKepzie/Natron#1388]
Natron-201606302040-28d56cdd2df4509c5b2c6aff747ec1698aaa4b8c-Linux-x86_64bit

Error while creating node net.fxarena.openfx.Text: Could not create effect instance for plugin

Failed to create an instance of fr.inria.openfx.TextFX:
Error: Description (kOfxActionLoad and kOfxActionDescribe) failed while loading fr.inria.openfx.TextFX.

**Comment by olear** [comment]
Seems to be an issue with ImageMagick on Linux, will fix.

**Comment by olear** [comment]
This has been fixed.

**Comment by adallafontana** [comment]
On last today shapshot:

Failed to create an instance of fr.inria.openfx.TextFX:
Error: Description (kOfxActionLoad and kOfxActionDescribe) failed while loading fr.inria.openfx.TextFX.

and the Arena ofx text node isn't present

**Comment by olear** [comment]
I just tested the latest snapshot, works fine. Could you try clearing the plugin cache.

**Comment by adallafontana** [comment]
Ok I have cleaned the cache and now I have 1 text node, is it correct so?
Now textOFX is the default.

**Comment by olear** [comment]
That is correct, TextFX has been renamed to TextOFX and the old plugin has been deprecated (but is still available for old projects).
