### ISSUE TITLE
Shadertoy/Auto.Params are 0.0 by default

### ISSUE THREAD

**Issue by adallafontana** [MrKepzie/Natron#1390]
If I load a fragment shader script with uniforms parameters when I click on auto parameter the widgets will be created but only with 0.0 value, the uniform value are not respected.

![uniform](https://cloud.githubusercontent.com/assets/8054856/16544291/e3f17216-4100-11e6-9174-6a6c94e83422.jpg)

**Comment by devernay** [comment]
do you expect Auto. Params to set the default velue and *also* reset to the default value? I was not sure when I coded it.

**Comment by adallafontana** [comment]
I do expect that the values of the "uniforms" will be reported on the widgets of the node, now the widget are created with value "0.0" and we must  correct  manually the values, will be better if the Auto.Params do it for us.   :)

**Comment by devernay** [comment]
if you right-click on each param you can reset it to its default value.
I did not set the value, because you may not want all the values to be reset each time you modify the shader (for example you change the max value).
I will add a button "Reset Param. Values", is that OK?

**Comment by adallafontana** [comment]
> if you right-click on each param you can reset it to its default value.

good to know

> I did not set the value, because you may not want all the values to be reset each time you modify the shader (for example you change the max value).

I don't understand the issue, I explain what I do, so you can imagine if is correct or not:

- Load the fragment script (....or write one) with uniform value.
- Click on Auto.Params and the automatic function create a widget on the node with the value wrote on script e.g. uniform float Samples = 256; now I have a new filter-node with all widgets value setup to default and that I can modifying and animate with keys trought the widgets.

1 - if the shaders doesn't have problem and I don't need to re-write/re-compile what is the issue in this scenario?
2 - If I'm writing a new shader and I'm compile it every time for test it, if I change the uniform during this time what is the issue in this case?
3 - If the issue is that every time I reopen the project with one shadertoy node inside , the widget value come back to default, then so is a big issue. 

 >I will add a button "Reset Param. Values", is that OK?

For me is too much add another button, just to know the command right-click.
If there is a issue for automatic reset the value when the widget are created, for me is perfect so, don't touch more.

tnx

**Comment by devernay** [comment]
actually they are not created when the shader is compiled: they are just hidden.
if you take a look at the "extra parameters" group, the default value is there.
It is difficult to know if you are compiling a new shader, or if it is a modification of the old one. For example, if you change the name of one parameter, should it reset all parameters to their default values?
The reset params values button is next to the auto params button, and avoids right-clicking on each param.

**Comment by adallafontana** [comment]
Ok good.

thank you

**Comment by adallafontana** [comment]
Tested the new button on 2.1.0 today: well done!

thank you
