### ISSUE TITLE
OFX cache writing is not safe against multiple concurrent Natron processes

### ISSUE THREAD

**Issue by mccartnm** [MrKepzie/Natron#1393]
Hey crew,

Not sure if this has been addressed. Picked up this issue when using Natron on a linux farm (Red Hat) setup when a single blade would pick up more than one job at a time. This is fairly common and may just need a small adjustment to the cache file using the pid or something of the sort.

From the developer who debugged it:
> Natron was overwriting ~/.cache/INRIA and ~/.config/INRIA on every invocation...writing to the same file at the same time, resulting in a truncated file (strace indicates that it reads the file, and then just writes it out again, if it has something — only if it’s not there does it scan the OFX directory for missing bits).  This made some OFX plugins disappear off the face of the planet for subsequent runs. 

Hope this helps.
Cheers!

**Comment by MrKepzie** [comment]
Yeah basically these are cache locations written to by Natron, we could lock the OFX plug-ins cache, however locking the entire disk cache would require some synchronisation scheme between instances and would not bring you that much: Natron is designed to take advantage of the full compute power of one farm node, (CPU should cap to ~95%/100% across all cores) so there's no real advantage to make 2 instances run over the same node

**Comment by mccartnm** [comment]
In the setup of the farm we're running there can be upward of ~10,000 individual jobs submitted in a single day between all departments. It's a bit of a unique situation but the blades will pick up multiple jobs to handle the load. They are rather monstrous machines - 48 physical processors, 128gigs RAM - so we aren't worried too much about performance.

Locking the OFX plug-ins cache would most likely solve our problem. The instances, since running headless, don't actually need to cache. Is there a way to tell Natron to not use them at all? The jobs are scripted and standalone (Which is awesome by the way. Very happy with the Python API. It's been extremely helpful).

**Comment by MrKepzie** [comment]
The disk cache is only used if using the Viewer or the DiskCache node. For all the rest it is unused.

**Comment by MrKepzie** [comment]
This will most likely go into 2.1.1

**Comment by menssimia** [comment]
On non-Windows systems, the alternative is to write the file out to the same location, but with a unique extension (pid?), and replace the old cache file out with it once the write is done using unlink and rename. The file replace is atomic, from a filesystem level, and other natron instances won't see an incomplete file.

On Windows, this is a self-solving problem, because the file will be locked during the write.
