### ISSUE TITLE
Hide autosave file (enhancement)

### ISSUE THREAD

**Issue by nicholascarroll** [MrKepzie/Natron#1398]
Every project file ends up with an autosave and a lock file next to it.  The folders start to look untidy.

Suggested is to put the lock file in the system temp. Or allow it to be specified as a path in prefs. I would want to put autosaves in ~/.Natron.

**Comment by devernay** [comment]
The autosave should be removed whenever you save the project, and the lock file should disappear when you quit Natron. If it's not the case, then it's a bug (can you please check?).
They both should lie in the same directory as the project file, because this may be a network directory, perhaps shared with other users.

**Comment by nicholascarroll** [comment]
The lock file stays after exit but this is on my Natron installs which are 2.1.1 for OSX and 2.1.0 for Linux.  I don't have a more recent build. 

OK so the lock file seems quite handy there where you can see that someone has that open.
But why have the autosave there, isn't it only of value for the local user?

**Comment by nicholascarroll** [comment]
There are more little problem with the lock, autosaves, beyond this issue, which might be best to write down here so they can be fixed in one fell swoop. These problems have been there along time in Natron:
(1) When you exit Natron and choose to discard your changes, when you re-open Natron it has not discarded it because it then restore it!
(2) Very often when saving you are warned that you are overwriting a different file in another session. I get that alot and its ALWAYS wrong. If there isn't another session with a file open it should not tell me there is!

These little glitches have been there along time in Natron and I really can't understand why they havn't been fixed long ago.

**Comment by devernay** [comment]
This issue was moved to NatronGitHub/Natron#162
