### ISSUE TITLE
allowing more complex frame range

### ISSUE THREAD

**Issue by Phantom-Studio** [MrKepzie/Natron#1404]
Hello, 

###current behavior
currently in write node we can set manual frame range, with an iput and an output with eventually a step.

###feature request
it would be nice to be able to render more complec frame range
for exemple  frame 10 to 20 , then 45 to 100, , and finally the frame 150.
In order to do that we could use the following syntax in an input field :
 10-20,45-100,150

Is it possible to implement ?

**Comment by MrKepzie** [comment]
Duplicate of https://github.com/MrKepzie/Natron/issues/1039 
It works only in command line for now, 
See https://github.com/MrKepzie/Natron/issues/1016
