### ISSUE TITLE
Lightwrap issue

### ISSUE THREAD

**Issue by kittumvkm** [MrKepzie/Natron#1405]
### Problem

Describe the problem or suggestion here.

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

 *Lightwrap not working properly, if we on checkbox for generate only wrap, its not generating. if we play with check boxes in lightwrap its not showing result.

pyside plugins not working previous version, if we prepare latest version py side plugins are not working in older versions and natron script also not opening older version in latest version. 
### Versions
- **Natron 2.0.2, 2.1.2 (they can be retrieved from the About Window): 
- **OS version: window7

**Comment by MrKepzie** [comment]
Hmm I cannot reproduce the bug, the light wrap is working great here.

**Comment by sozap** [comment]
I've also noticed some issues in PyPlug, sometime the operation of Merge node is not set correctly...
If I add a ID_Matte pyplug, the node Merge1 has a copy operation instead of difference. Even if the node show difference in the node title.
I've seen the same issue sometimes with other pyplug but haven't investigate that much.

**Comment by sozap** [comment]
Hum, sorry , in fact that was an old pyplug that I added to my repository (made from coyhot) some time ago. I need to see if that still append with new pyplugs.

**Comment by kittumvkm** [comment]
Natron2.1.2 window7, i installed different systems which i downloaded natron2.1.2 for windows .exe and .zip archive of portable both having same issue with light wrap. play with the checkbox at viewer not showing any result.

**Comment by MrKepzie** [comment]
Can you show a screenshot of your project setup ?

**Comment by kittumvkm** [comment]
![generateonlywrap_disable_lbw_enableglow](https://cloud.githubusercontent.com/assets/19346387/17367200/b611cc78-59ac-11e6-809b-569c950bf32b.jpg)
![generateonlywrap_disable_lbw](https://cloud.githubusercontent.com/assets/19346387/17367201/b63a6cbe-59ac-11e6-80bb-406491abb723.jpg)
![generateonlywrap](https://cloud.githubusercontent.com/assets/19346387/17367202/b646d56c-59ac-11e6-9d04-9560b3797a9a.jpg)
![wrapvisible in only one in this](https://cloud.githubusercontent.com/assets/19346387/17367203/b66420ae-59ac-11e6-89ec-2dda83021978.jpg)

**Comment by kittumvkm** [comment]
check the images, i was attached, light wrap visible in last image only remaining three images light wrap output is blank. so can you please notice this issue.

**Comment by MrKepzie** [comment]
I'm unable to replicate with the same graph

**Comment by devernay** [comment]
can you please attach a zip of a project demonstrating the issue, or send it to us by email?

**Comment by devernay** [comment]
This issue was moved to NatronGitHub/Natron#164
