### ISSUE TITLE
Shortcut settings not saving

### ISSUE THREAD

**Issue by nicholascarroll** [MrKepzie/Natron#1406]
### Problem

Changes in the shortcut editor are not getting saved.

### Steps to Reproduce

1. Go to Preferences > Shortcut Editor > Viewer
2. In shortcut for First Frame (default is control left arrow) press Clear and enter Home and Validate
3. Restart and its back to how it was

### Versions
2.1, 2.2
on OSX and Linux

**Comment by olear** [comment]
fixed in fe4618e1ac3b73f9217d039f51f1c88856b31406

**Comment by nicholascarroll** [comment]
is it possible to get a build of this ? or any way to set shortcuts? because its too long to wait on 2.2

**Comment by olear** [comment]
Will be part of 2.1.3. Don't know when that will be released.

Workaround: Set config in a prior version, or edit the config file by hand.

**Comment by nicholascarroll** [comment]
yes that will be fine, please advise what's the file?
