### ISSUE TITLE
Better location for the Disable Checkbox (enhancement)

### ISSUE THREAD

**Issue by nicholascarroll** [MrKepzie/Natron#1407]
The *Disable* checkbox is on every Effect in the *Node* tab. Would be better if it was out in the open where you could conveniently toggle it. Can it please be moved to the header of the Effect window or thereabouts?

This is for when you are working close up in the viewer with the Effect window floating and the node graph is hidden.

**Comment by olear** [comment]
A trivial "fix", something like this?:
![disablenode](https://cloud.githubusercontent.com/assets/7461595/17415317/b0c16eb2-5a89-11e6-904d-8b56e265cf2e.png)

Everybody on board with this modification? Move other knobs?

**Comment by devernay** [comment]
I don't think this is a good idea to move it there. It is already easily accessible in the node graph ('d' key), and this shortcut also works in the properties panel for the selected node.

The annoying thing, though, is that you cannot change the selected node by clicking on a properties panel, see #1410

**Comment by olear** [comment]
Ok, #1410 seems like a better option.

**Comment by nicholascarroll** [comment]
Ok. Well, i suppose the Mix parameter is equivalent.

**Comment by devernay** [comment]
setting mix to 0 will make the node passthrough - same as disabling it, so yes it is equivalent, but mix is not always present.
