### ISSUE TITLE
Arrow key moves the Roto shape

### ISSUE THREAD

**Issue by nicholascarroll** [MrKepzie/Natron#1408]
### Problem

When you select a roto shape and press left or right arrow (next/previous frame), it moves the shape. This is very confusing.

**Expected behavior:** 
In the viewer the keys bound to next/previous frame should take precedent. So the default previous frame is _Left Arrow_ and even if you have a roto shape selected that key should still only move to the previous frame. 

**Actual behavior:**
The _Left Arrow_ / previous frame key moves the roto shape around.
 You have to deselect the shape to use the left/right keys to change frame.
### Steps to Reproduce
1. load a frame sequence
2. add a roto node
3. add a new roto shape
4. click on the roto shape to select it
5. press the left or right arrow key and it moves the shape.
### Versions

2.1.1
- **OS version:** 
  Linux

**Comment by devernay** [comment]
This may be confusing, but it is very helpful, and comes from an early feature request #29

**Comment by nicholascarroll** [comment]
ABSOLUTELY NOT FRED. There I was late last night getting a job finished for a client today and i hit arrow, arrow, and the roto bezier shape moves, but I thinking, its moved because that's the next frame. Do you see what I mean? 
BAD IDEA!

**Comment by nicholascarroll** [comment]
*Nudge* can be a distinct key binding and that would resolve this issue.

**Comment by nicholascarroll** [comment]
#29 does not intend to say that *Nudge Roto* should be the same keybinding as *Next/Last Frame*

**Comment by devernay** [comment]
What do you think could be a right key combination, then (@hyperfx any opinion on this?) ?
Maybe shift + arrows, as suggested in #29?

**Comment by nicholascarroll** [comment]
As long as its a separate keybinding should be fine.

**Comment by hyperfx** [comment]
I agree with Nick. I have the same issues all the time, nudging the roto and then having to nudge it back, move the mouse down to the node view, then arrow key to move to the next frame. I love the idea of having mask nudge tools, but I strongly agree with Nick, they should be something else, like Shift + Arrow or CTRL + arrow. Something that's easy for the opposite hand to easily get to.

**Comment by nicholascarroll** [comment]
no workaround ATM because you can't customize shortcuts in the current release (2.1.2). Ref #1406

**Comment by nicholascarroll** [comment]
@MrKepzie  whoops shift + arrow conflicts with 'Go to frame plus increment'. Sorry, can it be something else?

**Comment by MrKepzie** [comment]
My concern is that all combinations of arrow + some modifier is already taken by the timeline.

**Comment by nicholascarroll** [comment]
you can just leave it empty by default.

**Comment by hyperfx** [comment]
Having it be something would be certainly useful. Nudging is really, really useful. Nicholas, are you saying the user should just set it to whatever they want?

**Comment by nicholascarroll** [comment]
yes of course but this ticket is about its default value and im saying set it to anything but not the player controls.

**Comment by hyperfx** [comment]
Agreed, just wanted to be sure I understood.

**Comment by CameraRick** [comment]
Sorry if I'm late to the party, I just noticed this issue.
I now saw that arrow keys without modifier won't move the shape anymore, which I think is good. When I hold the Shift-Key and press the arrow keys, the shape (or the point I selected) will move; but ONLY when I let go of Shift. That means it stays the way it is as long as I do the operation, and only changes when I release the keys which is a bit hard for nudging operations (not seeing that in real time).

I have a suggestion though, the Numpad. 2, 4, 6 and 8 on the Numpad are not used by anything yet I think (at least nothing happens when pressing them) and are perfect for nudging.

**Comment by nicholascarroll** [comment]
I agree with numpad. generally pro users are on full sized keyboard.

**Comment by devernay** [comment]
Related issue: #47 (nudging curves and parametricparams)

**Comment by MrKepzie** [comment]
Ok, I switched it to numpad 2 4 6 8. The user can still change the shortcut in the shortcut editor.

**Comment by nicholascarroll** [comment]
@MrKepzie this seems to be ordinary number keys not numpad.
