### ISSUE TITLE
Retime Reverse doesnt work

### ISSUE THREAD

**Issue by nicholascarroll** [MrKepzie/Natron#1411]
### Problem
Retime doesnt work with the *Reverse*

**Expected behavior:** 
Plays clip backwards
**Actual behavior:** 
Shows only one frame - the first  - the whole time.

### Steps to Reproduce

1. add  reader
2. add retime
3. click *Reverse* enabled
4. no good!

### Versions
natron 2.1
osx and linux

**Comment by blackearth2014** [comment]
Have you tried version 2.1.2? I was using the Retime node in reverse last night. I didn't have any problems with it. Well, none that I have noticed. I am on the Mac.

**Comment by nicholascarroll** [comment]
thanks I'll give it a crack now

**Comment by nicholascarroll** [comment]
Got 2.12 and It is indeed fixed! thanks
