### ISSUE TITLE
IDistort / STMap doubles output values when there is no alpha channel present in the UV input

### ISSUE THREAD

**Issue by eeder68** [MrKepzie/Natron#1412]
### Problem

The output values of the IDistort / STMap nodes (which are the same plugin) are multiplied by 2 when the selected alpha channel of the UV input is not present. Alpha obviously gets set to 2, as choosing 'Unpremult UV' divides the UVs by 2.

I had a look at the code of openfx-misc/Distortion/Distortion.cpp, and it seems that mysterious value of 2 originates from line 537 where the integer channelIndex is returned as a double value if the field img is a nullptr.

```
532    double getVal(unsigned channel,
533                  const PIX* p,
534                  const PIX* pp)
535    {
536        if (!_planeChannels[channel].img) {
537            return _planeChannels[channel].channelIndex;
538        }
539        if (!p) {
540            return pp ? pp[_planeChannels[channel].channelIndex] : 0.;
541        }
542
543        return p[_planeChannels[channel].channelIndex];
544    }

```
Unfortunately I haven't got quite into the handling of multi planes in Natron yet, to understand why there is no complaint about the selected alpha channel missing, even though there seems to be a check around line 1062.

Also, selecting a constant 0 or 1 for the alpha doesn't seem to work.

### Steps to Reproduce

Here's a simple Natron script that reproduces the problem:
[IDistortDoubledOutput.ntp.zip](https://github.com/MrKepzie/Natron/files/405778/IDistortDoubledOutput.ntp.zip)

### Versions

* **Natron version/commit**
This software was compiled on Jul 19 2016 from the source code branch tags/2.1.2 at version e6652d8.
The bundled openfx-io plugins were compiled from version acb90ed.
The bundled openfx-misc plugins were compiled from version 4daa7ad.
The bundled openfx-arena plugins were compiled from version a720f08.

* **OS version:** 
Ubuntu 14.04.1 LTS
3.13.0-37-generic #64-Ubuntu SMP Mon Sep 22 21:28:38 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

**Comment by devernay** [comment]
bug introduced in https://github.com/devernay/openfx-misc/commit/b30ce093e920
fixing it.
