### ISSUE TITLE
Natron Cannot See Primatte Plugin (Linux)

### ISSUE THREAD

**Issue by nicholascarroll** [MrKepzie/Natron#1419]
### Problem

On Linux, Natron does not load the plugin [Primatte](http://www.primatte.com/downloads/files/PrimatteWEBInstaller_linux64_ofxv2.tar.gz) version 4 64 bit node locked.

**Expected behavior:**
Primatte should appear in the toolshelf. This works on OSX but not Linux.

**Actual behavior:**
Seems like Natron does not see it. I tried telling Natron to impersonate Nuke, Sony Vegas, and cleared the Plugins Load cache nothing seems to work. I checked all the permissions it looks fine.

### Steps to Reproduce

1. Download http://www.primatte.com/downloads/files/PrimatteWEBInstaller_linux64_ofxv2.tar.gz
2. cd primatte, sudo ./install.sh
3. Start up Natron, look for plugin 'Primatte'. It's not there.

Please advise any diagnostics needed.

### Versions
Natron 2.1.x
Ubuntu 16.04

**Comment by olear** [comment]
It requires gcc3, install the gcc3 compat library (if you have it). On CentOS/Fedora the package is called compat-libstdc++-33.

**Comment by nicholascarroll** [comment]
On Ubuntu:
sudo apt-get install libstdc++5 libstdc++5:i386

**Comment by devernay** [comment]
@nicholascarroll can you please signal this to your Primatte friends so that they put this in their FAQ?

**Comment by nicholascarroll** [comment]
Yes I did - cheers.

**Comment by olear** [comment]
They should probably move to GCC4 as well. No distro uses v3 anymore, the oldest still maintained distro version is CentOS/RHEL 5 and they have 4.1.2 as default (with 4.4 as an option).

**Comment by nicholascarroll** [comment]
comme toujours, linux est pas donné assez de pâturages
Primatte has gone to Red Giant now who doesn't support Linux
=-(
