### ISSUE TITLE
ImageStatistic bug Natron 2.1.2 on Win10 ?

### ISSUE THREAD

**Issue by SebaBugna** [MrKepzie/Natron#1420]
When I push button "Analyze Sequence", it analyzes only the first frame and then freezes. If I click somewhere else Natron crashes.
It doesn't allow to Clear Sequence either.
In previous versions I used this tool without any problem.

the "Analyze Frame" button works fine.

I'm working on Win10.

Here´s a screen capture with the issue
http://sendvid.com/cxgkmmvk
### Versions

*Natron 2.1.2 
Windows 10 (Recently installed clean version )

**Comment by olear** [comment]
When you say it worked in previous Natron versions, did you use the same Windows version? Or did this happen after you did a OS (re)install?

Unable to replicate on Linux, and it also works on Windows 7.

**Comment by SebaBugna** [comment]
In a previous laptop I had Win10 and Natron 2.0, and it was working.

**Comment by olear** [comment]
Could you try 2.0.5 and see if that works for you?

Just tested Win10 in VirtualBox, a bit slow (analysing) but works.

**Comment by SebaBugna** [comment]
couldn´t find Natron 2.0.5 installer.
If you have a link I´ll try it as soon as I can. thanks.

**Comment by MrKepzie** [comment]
Does this still happen ?
