### ISSUE TITLE
add transform widget to pyplug user parameters

### ISSUE THREAD

**Issue by sozap** [MrKepzie/Natron#1421]
That would be very great to be able to display widget on the viewer for 2D coordinates params of pyplugs.
Exactly like the shadertoy node do for mouse position.

I guess this is planned at some point, as it have many applications and allow some pyplug to be way more interactive.
Consider this as a reminder then...

Cheers !

**Comment by MrKepzie** [comment]
Already possible, see http://natron.readthedocs.io/en/master/devel/PythonReference/NatronEngine/Double2DParam.html#NatronEngine.NatronEngine.Double2DParam.setUsePointInteract

**Comment by sozap** [comment]
Awesome ! Sorry then...
If I understand correctly, I can't set it when I create an user parameter on the interface ?
That would be great to have , because one dumb guy like me may assume it's not there.

Just a question, If I want to create a pyplug that show the widget by default , should I need to add a line in the .py script ?
Or I just need to set it up using the script editor and it will be included by default when I export the pyplug ?

Thanks for your time !

**Comment by MrKepzie** [comment]
There's just no checkbox in the dialog to create a new parameter.
When you create your new parameter, then call this in the script editor:

    app.MyNode.MyParam.setUsePointInteract(True)

Currently the PyPlug exporter does not export it, so you need to add this to the PyPlugExt.py script and hand write this.

I will fix this so that it can be auto-exported.

**Comment by sozap** [comment]
Perfect, thanks !
Having a checkbox in the dialog would be awesome and avoid much confusion. It's a bit sad that something like that is a bit burried and not directly exposed to the user.

anyway , now that I know that I'll make nice pyplug that will throw some pony into the community !
