### ISSUE TITLE
TextOFX node flickers

### ISSUE THREAD

**Issue by max-krichenbauer** [MrKepzie/Natron#1422]
### Problem

If the font family value of the TextOFX node is changed, it will start flickering,
in that in random frames it will display only small boxes instead of text.
This persists even when resetting "to default", or setting keyframes or expressions on the value.
[natron_text_test.zip](https://github.com/MrKepzie/Natron/files/453589/natron_text_test.zip)

**Expected behavior:**
The TextOFX node should generate text in the font selected in every frame.

**Actual behavior:**
In random frames, the node generates tiny boxes.

### Steps to Reproduce

1. Create a Text node
2. Change the "Font Family" value
3. Press play in the viewer or render the output to video file.

### Versions

* **Natron version/commit** 
2.1.2, compiled on Jul 19 2016 from the source code branch tags/2.1.2 at version e6652d8.
 
* **OS version:** 
Windows7

**Comment by olear** [comment]
I'm able to replicate parts of this issue, I do not get flickering. This only happens on Windows and may be related to the Windows font engine (could also be a deployment issue related to pango/cairo).

Will try to fix as soon as possible

**Comment by max-krichenbauer** [comment]
Thank you for the super quick reply!
I also noticed some more strange behavior:
if I change the font family, it's as if a keyframe has been set on that value,
(meaning that the font will change after that frame)
even if no keyframe / animation is present.

**Comment by olear** [comment]
Do you get warnings in the terminal window? This could be a fontconfig cache issue.

**Comment by max-krichenbauer** [comment]
You're right, sorry I had not noticed before.
I get:

(Natron-bin.exe:2080) Pango-WARNING **: All font fallbacks failed!!!!

**Comment by olear** [comment]
Thanks, this is a deployment issue. I will try to find out what's wrong.

**Comment by olear** [comment]
Fixed in https://github.com/olear/openfx-arena/commit/cb4016fc653586d57d8f8e408e618f404f7771c9

**Comment by max-krichenbauer** [comment]
Thank you!
Could you please send me a compiled version?
I don't have the system set up to build it from source.

**Comment by olear** [comment]
I currently don't have a end-user build available. The text node is part of a larger bundle, and that (bundle) has to be rebuilt and prepared for deployment in order to be usable on your installation.

I can trigger a snapshot build of Natron later today.

**Comment by max-krichenbauer** [comment]
That would be awesome! Thank you!

**Comment by olear** [comment]
2016-09-06 10:51:00 RB-2.1 snapshot installer/archive or newer should have the fixes, you can find them on our download page.

**Comment by max-krichenbauer** [comment]
It works! Thanks so much!
Do you have a paypal account where I can "invite you to a virtual beer" or something! :-D

By the way: it still seems like changing the font family in a later frame creates a kind of "hidden keyframe", meaning that frames before that will not be affected by the change until you go to frame one, reset the font family value and set the desired value again.

**Comment by olear** [comment]
Are you sure you don't have a keyframe on the 'font family' somewhere?

**Comment by max-krichenbauer** [comment]
Well, it appears as if I'm setting keyframes, but I'm not intentionally setting them and they don't show up in the timeline.
Here is a video of what I mean. At the end you can see the font change at frame 50 without there being a keyframe.
[text_test.zip](https://github.com/MrKepzie/Natron/files/458060/text_test.zip)

**Comment by olear** [comment]
I'm able to replicate, will find a fix.
