### ISSUE TITLE
Multiopen file reader (creating multiple readers from one file dialog)

### ISSUE THREAD

**Issue by nicholascarroll** [MrKepzie/Natron#1423]
Please support selection of more than one file or sequence in the _Open Sequence_ window. So that we can create several readers at the same time:
1. press 'r' in the nodegraph
2. select three sequence listings
3. click _Open_ button
4. three Read nodes get created

also if you could select a directory and all inside get opened

low priority and just a convenicence

**Comment by devernay** [comment]
This issue was moved to NatronGitHub/Natron#165
