### ISSUE TITLE
Full crash when trying to open up certain groups

### ISSUE THREAD

**Issue by CameraRick** [MrKepzie/Natron#1429]
### Problem

I tried to build some PyPlugs. For this I started a group and build my tree from there, creating user-controls and expression-link everything together. After closing and re-opening the software (e.g. after a normal crash or a normal restart of the machine), I can't access some of these Groups anymore, Natron crashes as soon as I hit the button. 
Naton crashes completely, usually I didn't receive the crash-support window, the console doesn't list any info either. Ironically I received the crash-repot window now when doing a screencast of the issue (see below)
This won't happen with all scripts and groups, only some (bigger ones).
I attached a script where this happens (note: this script depends on the "SeExprSimple" Node from the latest snapshot, but it also happens with other groups entirely build in the latest stable version)

You can get around this when copying the group into a new script, but then all expressions etc are vanished and the tool needs heavy rework.

[160912_Natron_crashingGroup.zip](https://github.com/MrKepzie/Natron/files/468218/160912_Natron_crashingGroup.zip)
[160912_Natron_crashingGroup_crashdump.zip](https://github.com/MrKepzie/Natron/files/468243/160912_Natron_crashingGroup_crashdump.zip)

**Expected behavior:** the group should open so it can be edited

**Actual behavior:** crashes

### Steps to Reproduce

1. Open up the attached script
2. double click the Group, "lp_Despill"
3. hit the button for opening up the group
4. Crash

Here's a link to a screencast so you can see my steps. Note that the tool works fine and as expected so far: https://youtu.be/QtZvR5inpnY

### Versions

* **Natron version/commit** Natron 2.1.2 as well as Natron 2.1.2 Snapshot (201609091041)
* **OS version:** Windows 10 Pro (tested on two PCs), Ubuntu 16.04.1 (VM)

**Comment by MrKepzie** [comment]
The copy/paste issue is fixed. Anyway I noticed you use a lot of expression, note that regular links are much faster. To do so, right click on a parameter on a node inside the group and select "Create alias on group". This will make a copy of the parameter on the group node itself with everything setup correctly with a hard-link instead of a (slow) expression.

**Comment by CameraRick** [comment]
Yes, I use Expressions much, out of habit :) I will try to reduce it, so it gets only used when I need to modify the value :)

Anyways, any insights why I can't open them up anymore? Or can I use the latest snapshot, copy them into a new script and work again, as the copy/paste is fixed?

**Comment by MrKepzie** [comment]
The crash is in Qt we are trying to figure out why

**Comment by MrKepzie** [comment]
Got fixed

**Comment by CameraRick** [comment]
I just checked the 20h snapshot, it works!
Thank you very much! :)
