### ISSUE TITLE
loading project time

### ISSUE THREAD

**Issue by ramellij** [MrKepzie/Natron#1432]
Hello,

I found a big difference in time when I open a .ntp file with network drive paths in the read file nodes and without. So I made two natron projects for the same compositing on my local drive C:\WIP\, sources and project files all inside. 
- On the first one all read nodes are linked to the sources by a network drive (accessible for the renderfarm) : \\WORKSTATION-PC\WIP\
- On the second one my read nodes are directly linked to the sources (only my workstation have access) : C:\WIP\

The second one opens very quickly while the second takes 1 minute at least. 
Did you experience it and do you know what it could be ?

Thanks for your help
JR

Windows7, Natron 2.1.2

**Comment by olear** [comment]
We know about this issue, for some reason there is a ~1 min delay when adding files from SMB.

**Comment by MrKepzie** [comment]
Note that this is a windows only issue

**Comment by ramellij** [comment]
Ok thanks for the fast response !
Do you know when version 2.2 will be release and if this known issue will be fixed ?

**Comment by MrKepzie** [comment]
Currently this is not identified whether the slowness comes from within Natron or Qt. If it's fixed it should be made available on version 2.1.x, and also be included in 2.2.
Note that version 2.2 is not expected for at least a few weeks onwards

**Comment by ramellij** [comment]
Then I'll be patient. Thank all of you for your great work !

**Comment by ramellij** [comment]
Same problem with 2.1.3, but you already knew it ;)

**Comment by MrKepzie** [comment]
Should be fixed now for 2.1.4

**Comment by ramellij** [comment]
Thanks !
