### ISSUE TITLE
2.1.3 SeGrain dosen't work/load

### ISSUE THREAD

**Issue by adallafontana** [MrKepzie/Natron#1433]
Tested on ubuntu 16.04 Natron 2.1.3

Error while creating node net.sf.openfx.SeGrain: Could not create effect instance for plugin

**Comment by blackearth2014** [comment]
I second this. The SeGrain node is definitely needed now.

**Comment by devernay** [comment]
Sorry about that. I added the possibility to have "static" grain now and made a mistake.

The snapshot should be ready in an hour or so.

@adallafontana please test DenoiseSharpen (e.g. on your green screen footage) and report in https://github.com/devernay/openfx-misc/issues/44
