### ISSUE TITLE
Drag & dropping video files should not be recognized as sequences

### ISSUE THREAD

**Issue by manuelsongokuh** [MrKepzie/Natron#1438]
hi
i write here and is not crash or issue, but i have many problem for me only.
i tell you:
my camcorder canon FX105 records 3 hours, and canon save video in file limit size 1,9GB (problem from filesystem FAT32) then result my video time 3 hours and canon did separated video in file sequence.
example
### 

file:///TVG/2016-01-28-TESTIMONIANZE-SILENZIOSE/NASTRO/A/CONTENTS/CLIPS001/AA0002/AA000201.MXF
file:///TVG/2016-01-28-TESTIMONIANZE-SILENZIOSE/NASTRO/A/CONTENTS/CLIPS001/AA0002/AA000202.MXF
file:///TVG/2016-01-28-TESTIMONIANZE-SILENZIOSE/NASTRO/A/CONTENTS/CLIPS001/AA0002/AA000203.MXF
file:///TVG/2016-01-28-TESTIMONIANZE-SILENZIOSE/NASTRO/A/CONTENTS/CLIPS001/AA0002/AA000204.MXF
file:///TVG/2016-01-28-TESTIMONIANZE-SILENZIOSE/NASTRO/A/CONTENTS/CLIPS001/AA0002/AA000205.MXF
file:///TVG/2016-01-28-TESTIMONIANZE-SILENZIOSE/NASTRO/A/CONTENTS/CLIPS001/AA0002/AA000206.MXF
file:///TVG/2016-01-28-TESTIMONIANZE-SILENZIOSE/NASTRO/A/CONTENTS/CLIPS001/AA0002/AA000207.MXF
file:///TVG/2016-01-28-TESTIMONIANZE-SILENZIOSE/NASTRO/A/CONTENTS/CLIPS001/AA0002/AA000208.MXF
file:///TVG/2016-01-28-TESTIMONIANZE-SILENZIOSE/NASTRO/A/CONTENTS/CLIPS001/AA0002/AA000209.MXF
file:///TVG/2016-01-28-TESTIMONIANZE-SILENZIOSE/NASTRO/A/CONTENTS/CLIPS001/AA0002/AA000210.MXF
file:///TVG/2016-01-28-TESTIMONIANZE-SILENZIOSE/NASTRO/A/CONTENTS/CLIPS001/AA0002/AA000211.MXF
file:///TVG/2016-01-28-TESTIMONIANZE-SILENZIOSE/NASTRO/A/CONTENTS/CLIPS001/AA0002/AA000212.MXF
file:///TVG/2016-01-28-TESTIMONIANZE-SILENZIOSE/NASTRO/A/CONTENTS/CLIPS001/AA0002/AA000213.MXF

so Natron will can open video sequence? for now natron is not supported..so i do question you, will be good idea for video sequence in node read auto?

**Comment by MrKepzie** [comment]
No, it should be using EDL, see https://github.com/MrKepzie/Natron/issues/1170

**Comment by devernay** [comment]
@manuelsongokuh you can create as many readers as necessary and use the AppendClip node to concatenate the sequences

**Comment by manuelsongokuh** [comment]
thank you for AppendClip, but not work for multi-files from dolphin (kde5) selected 14 files drag in result error of read..

**Comment by manuelsongokuh** [comment]
![screenshot_20160923_112123](https://cloud.githubusercontent.com/assets/12126929/18780908/f04d83b4-817f-11e6-9e9d-c04841705bd9.png)

**Comment by manuelsongokuh** [comment]
![screenshot_20160923_112242](https://cloud.githubusercontent.com/assets/12126929/18780951/1b19b946-8180-11e6-9882-c18f6a35ecb6.png)

**Comment by MrKepzie** [comment]
It error because you are trying to use hash tags (###) for videos.. which does not work.

**Comment by manuelsongokuh** [comment]
i did not write ### and i use drag and drop in natron..

**Comment by olear** [comment]
If you drop files and they are in a sequence, Natron will automatically add ### even if it's video files.

**Comment by MrKepzie** [comment]
This is a bug then, it should not apply the sequencing to video files
On 23 Sep 2016, at 14:56, Ole-André Rodlie <notifications@github.com<mailto:notifications@github.com>> wrote:


If you drop files and they are in a sequence, Natron will automatically add ### even if it's video files.

**Comment by manuelsongokuh** [comment]
Thank YOU!!

**Comment by manuelsongokuh** [comment]
hi, i'm back here
i try my other project for to use appendclip, but clips are strange (like as not work to show, result error message, and bad frame from clips..but this is a bug or problem from video footage MXF?

then i will try to EDL but natron is sopported EDL (is work as fine?).

thank you

**Comment by manuelsongokuh** [comment]
hi, i find problem of appendclip..can check it?
see screenshot: 
![natron-bad-appendclip-01](https://cloud.githubusercontent.com/assets/12126929/22785688/a3a2524c-eed5-11e6-98bb-61b78ad717ae.png)

there are rgba from layer 7 until 14 layer..

this problem is reproduce error clips..i want to change from rgba to rgb... but i cant change it..

**Comment by devernay** [comment]
This issue was moved to NatronGitHub/Natron#166
