### ISSUE TITLE
TextOFX - can't read fontfile from a custom path

### ISSUE THREAD

**Issue by JuusoKaari** [MrKepzie/Natron#1439]
### Problem

I would like to store my font files in the project folder rather than the system font folder.
When moving a Natron project from computer to computer it is fairly impractical to manually check what fonts were used, include those in the transfer, and manually insert the fontfiles to the new computer.

In the old Text node had this "Custom font" field, and I wish the new TextOFX would also incorporate this.

![custom_font](https://cloud.githubusercontent.com/assets/17428352/18668766/144bcede-7f40-11e6-9368-47f383026040.PNG)

### Versions

* **Natron version 2.1.3 Release.**
* **Windows 10**

**Comment by olear** [comment]
I will see what I can do.

**Comment by olear** [comment]
![customfont](https://cloud.githubusercontent.com/assets/7461595/18676539/3baf5c50-7f56-11e6-9d0e-4ca3d04603f4.png)

Is this acceptable? You add a custom font and the font combo box is regenerated and you can choice your custom font from the combo box? I can also change this to be a custom font directory instead of just one font(?)

**Comment by JuusoKaari** [comment]
Oh, wow! That was fast.

Yes I think adding a single custom font file will do just fine.

Thank you so much! Is there any estimates on the 2.2 release date, or will this be available as a snapshot build?

**Comment by olear** [comment]
Not 100% done yet, need to test a bit more first, but seems to work ok. Will be available in a snapshot soon(-ish).

**Comment by olear** [comment]
Fixed in https://github.com/olear/openfx-arena/commit/b26233473fc51f1b2a2be5f153a0e3ac78eadcf0
