### ISSUE TITLE
copy / paste error in group node..natron 2.1.3

### ISSUE THREAD

**Issue by manuelsongokuh** [MrKepzie/Natron#1447]
-start natron
-add 4 nodes READ for video
-add 1 Node AppendClip
-connects 4 read to AppendClip
-add 1 node GROUP 
-select nodes: 4 reads + node AppendClip and press keyboard Ctrl + C
open windows of group1
press keyboard ctrl + V and result error

see screenshot error..

![screenshot_20160923_111131](https://cloud.githubusercontent.com/assets/12126929/18780602/9c89b6b8-817e-11e6-9c10-f19c07ce1c8c.png)

**Comment by MrKepzie** [comment]
I fixed the bug for 2.1.5

**Comment by manuelsongokuh** [comment]
thank you!
