### ISSUE TITLE
Write node doesn't replace the old file, just writes over the same space (EXR)

### ISSUE THREAD

**Issue by troywilliams1** [MrKepzie/Natron#1449]
### Problem

**Expected behavior:** Overwriting an already written output file with any **smaller** project output (reformated) size will result in a smaller data footprint of that written file over the already written file.

**Actual behavior:** When writing over a pre-existing file to a smaller size the data footprint remains the same, which implies the overwritten file has trailing data from the previous write. A file of size 1024 (square) with filesize of 3.5mb when resized to 256(square) will retain the same file size of 3.5mb. When saving separately as a new file (new name) the data footprint changes to a smaller size.
### Steps to Reproduce
1. New Project, set size to 1024x1024
2. Place solid image
3. Place Radial
4. Render as EXR at size 1024x1024
5. Notice Filesize of output file
6. Open Project settings, resize to 256x256
7. Insert reformat before Write node
8. Reformat to size 256x256
9. Render again at size 256x256
10. Notice that filesize is the same
11. Click write node and save as separate file (new name)
12. Notice that new file has smaller data footprint
### Versions
- **Natron version/commit** (they can be retrieved from the About Window): 
  Natron version 2.1.4 Release.
  This software was compiled on Sep 20 2016 from the source code branch tags/2.1.4 at version f74f4c9 using GNU C++ version 5.3.0 with OpenMP 201307 targetting Intel x86-64 for Unix Environment.
  The bundled openfx-io plugins were compiled from version 9ebe780.
  The bundled openfx-misc plugins were compiled from version e9f080d.
  The bundled openfx-arena plugins were compiled from version f4773da.
- **OS version:**  Windows 8 64-bit

**Comment by devernay** [comment]
Seems to be working now.
Writing an HD file:
```
$ iinfo toto.exr; ls -la toto.exr
toto.exr : 1920 x 1080, 4 channel, float openexr
-rw-r--r--  1 devernay  staff  152172 24 avr 12:08 toto.exr
```
overwriting with a 640x480 file:
```
$ iinfo toto.exr; ls -la toto.exr
toto.exr :  640 x  480, 4 channel, float openexr
-rw-r--r--  1 devernay  staff 33637 24 avr 12:09 toto.exr
```

**Comment by troywilliams1** [comment]
This bug is still a problem, I am seeing this behavior in version 2.3.14, should I file a new bug report? The problem of bit depth is also not affecting the data size, as referenced in the forum post here: https://discuss.pixls.us/t/trying-to-convert-32f-exr-image-to-16f-exr-image/8831

**Comment by devernay** [comment]
It may be a windows-only issue. I can reopen the bug, but I won't have time to fix it

**Comment by devernay** [comment]
Fixed, see https://github.com/NatronGitHub/Natron/issues/666
