### ISSUE TITLE
Remember Minimize state when reopening project

### ISSUE THREAD

**Issue by nicholascarroll** [MrKepzie/Natron#1450]
### Problem

Please preserve state of minimized any node window was minimized when reopening closed projects. This is causing serious inconvenience for project files that have Primatte nodes, because Primatte accepts any click on the viewer and _minimize_ is the only way to prevent that.

Minimize node window affects functionality, not just layout.

**Expected behavior:** 
Remember if node was minimized so if you are using Primatte, it stays minimized.
**Actual behavior:**
The minimized Primatte nodes are set to open, which changes the functionality.
### Steps to Reproduce
1. Minimise a node
2. Close the project
3. Reopen the project
4. the node should be still minimised
### Versions
- **Natron version/commit** 
  2.1.4
- **OS version:** 
  Ubuntu 16.04 and OSX 10.11

**Comment by devernay** [comment]
This issue was moved to NatronGitHub/Natron#168
