### ISSUE TITLE
Deleting any Node in a Group breaks Expressions

### ISSUE THREAD

**Issue by CameraRick** [MrKepzie/Natron#1453]
### Problem

If I have a Node with an Expression inside a Group and delete any other Node (not referenced by said Expression), it breaks the Expression (indicated by a red cross next to it). When you edit the Expression and save it again it sometimes picks up work again, but not always. Restarting the script solves it too.
Hovering over the red cross next to the Expression inidicates that the Error is due to the deleted node.
 
**Expected behavior:** the Expression shouldn't be bothered at all (unless it got referenced inside the Expression)

**Actual behavior:** it breaks Expressions, making working on Groups/PyPlugs a bit frustrating at times

### Steps to Reproduce

1. Create a Group with at least two Nodes, for example Blur1 and Blur2 (not including inputs/output)
2. Create a Userknob of any kind
3. Expression-Link a value of a Node inside the Group to the Userknob, e.g. the size of Blur1
4. optional: Adjust the Userknob to check that the Expression works
5. Delete the second Node, e.g. Blur2, and try adjusting the Userknob again. The linked value will get back to default and display a red cross next to it

I made a screencast to show the issue: https://youtu.be/nQO0_k9VGks
(sorry for the colored font, some weird transcoding issue)

### Versions

* **Natron version/commit**: Natron version 2.1.4 Snapshot (from 20160928)
* **OS version:** Windows 10 Pro
I noticed this issue on older non-snapshot versions as well as on OSX 10.10.5

**Comment by CameraRick** [comment]
I just noticed, it's enough to rename a node, not even deleting it.

**Comment by MrKepzie** [comment]
I'm triggering a snapshot so you can confirm it fixes the issue

**Comment by CameraRick** [comment]
Had a quick look over it, seems like it doesn't happen anymore! Thank you very much! :)
