### ISSUE TITLE
Feature Request: Completion Meter for Taskbar Icon

### ISSUE THREAD

**Issue by alicelookingglass** [MrKepzie/Natron#1454]
Blender has the feature that shows a render completion meter on the taskbar icon (Windows) while it is minimized.  I have come to rely on this feature rather heavily for my various workflows, and I would absolutely love it if Natron could do the same.

(I hope I put this feature request in the right place)

Thanks for all your amazing work!

**Comment by alicelookingglass** [comment]
Is this difficult to implement?  I'd only asked because it seems so common in numerous other software.

**Comment by devernay** [comment]
This issue was moved to NatronGitHub/Natron#169
