### ISSUE TITLE
ColorLookup curve editor broken on OS X

### ISSUE THREAD

**Issue by emptyflask** [MrKepzie/Natron#1460]
### Problem

The ColorLookup curve editor appears to be displaying random data from the video card. It flashes and changes, sometimes displaying part of the desktop, Chrome, etc.
After messing with it for a while, I discovered that toggling between full-screen and window mode seems to clear it up.

![Screenshot](https://cloud.githubusercontent.com/assets/28287/19063223/71424402-89c6-11e6-8366-8fbe69cff0cc.png)

### Steps to Reproduce

1. Create an input node
2. Attach a ColorLookup
3. Stare into the abyss
4. Toggle full-screen mode to properly display the curve editor

### Versions

* **Natron version/commit**: 2.1.4 release and latest 2.1.5 snapshot (201610021717)
* **OS version:** OS X Yosemite 10.10.5
* **GPU**: NVIDIA GeForce GT 650M 1024 MB

**Comment by blackearth2014** [comment]
I can verify this. It's the same thing on my Mac(10.10.5)

**Comment by MrKepzie** [comment]
Will be fixed in 2.1.5

**Comment by devernay** [comment]
not yet fixed in 2.1.5, reopening
