### ISSUE TITLE
Natron Crashed on launch: 

### ISSUE THREAD

**Issue by blackearth2014** [MrKepzie/Natron#1462]
Natron crashes on launch with this snapshot "Natron-201610061753-63c7549eff482176e3860ccadd2fffaff59e6dbe" when I double click on its icon.

![natron crashes](https://cloud.githubusercontent.com/assets/7956901/19179537/78763cac-8c2c-11e6-9493-8a7005508c50.png)

In order to get it to run properly is to run it in terminal mode. The xt below is what is printing to screen when launched from the terminal.

"
Last login: Fri Oct  7 01:12:39 on ttys000
OBrowns-iMac:~ obrown$ /Volumes/Natron/Natron.app/Contents/MacOS/Natron-bin ; exit;
Natron Version 2.1.5
Copyright (C) 2016 the Natron developers
>>>Use the --help or -h option to print usage.<<<
Py_GetProgramName is /Volumes/Natron/Natron.app/Contents/MacOS/Natron-bin
Py_GetPrefix is /Volumes/Natron/Natron.app/Contents/MacOS/../Frameworks/Python.framework/Versions/2.7
Py_GetExecPrefix is /Volumes/Natron/Natron.app/Contents/MacOS/../Frameworks/Python.framework/Versions/2.7
Py_GetProgramFullPath is /Volumes/Natron/Natron.app/Contents/MacOS/Natron-bin
Py_GetPath is /Volumes/Natron/Natron.app/Contents/MacOS/../Frameworks/Python.framework/Versions/2.7/lib/python2.7:/Volumes/Natron/Natron.app/Contents/MacOS/../Plugins:/Volumes/Natron/Natron.app/Contents/MacOS/../Frameworks/Python.framework/Versions/2.7/lib/python27.zip:/Volumes/Natron/Natron.app/Contents/MacOS/../Frameworks/Python.framework/Versions/2.7/lib/python2.7/:/Volumes/Natron/Natron.app/Contents/MacOS/../Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin:/Volumes/Natron/Natron.app/Contents/MacOS/../Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac:/Volumes/Natron/Natron.app/Contents/MacOS/../Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages:/Volumes/Natron/Natron.app/Contents/MacOS/../Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk:/Volumes/Natron/Natron.app/Contents/MacOS/../Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-old:/Volumes/Natron/Natron.app/Contents/MacOS/../Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload
Py_GetPythonHome is ../Frameworks/Python.framework/Versions/2.7/lib
Python library is in /Volumes/Natron/Natron.app/Contents/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages
Info: init.py script not loaded (this is not an error)
Info: initGui.py script not loaded (this is not an error)
2016-10-07 01:17:18.727 Natron-bin[32451:235841] modalSession has been exited prematurely - check for a reentrant call to endModalSession:
2016-10-07 01:18:07.325 Natron-bin[32451:235841] modalSession has been exited prematurely - check for a reentrant call to endModalSession:
2016-10-07 01:18:44.147 Natron-bin[32451:235841] modalSession has been exited prematurely - check for a reentrant call to endModalSession:
logout

[Process completed]
"

**Comment by olear** [comment]
Snapshots released yesterday was primarily aimed at Windows for testing a couple of bugs there. The 2015-10-05 snapshot for Mac still works. We will release a new batch of snapshots soon.
