### ISSUE TITLE
My systems are working two slow while viewing and Rendering

### ISSUE THREAD

**Issue by kittumvkm** [MrKepzie/Natron#1465]
Hi,

My system are working two slow while i am viewing and Rendering through natron, Below i am giving my system detail, is it my system having proper openGL version is there or not? check and provide proper openGL version for below configuration systems.
### Problem

Describe the problem or suggestion here.

**Expected behavior:** In my system, nuke is working very well, viewing and rendering but natron not that fast.

**Actual behavior:** While we do viewing we need to wait 10-15 mins of time. While Rendering, Render time was taking 1 to 2 Hr of time.
### Versions
- **Natron version/commit** (they can be retrieved from the About Window): 
  Natron 2.1.2
- **OS version:** 
  Windows8, Ram: 8GB, Graphic card Geforce210

OpenGL version showing in natron Libraries:

Python 2.7.11 
Qt 4.8.7 / 4.8.7 
Boost 1_60 
OpenGL , GLSL 
Cairo 1.14.4 / 1.14.4

**Comment by olear** [comment]
Need at bit more information. Are you rendering to image sequence or video? Do you have an HDD or SSD? Is the rendering using all cores on your CPU (100%)? Any reason for not using the latest version? And, could you give us a screenshot of your nodegraph? How many cores do your have (and GHz)?

**Comment by kittumvkm** [comment]
Core: 4, 3.20GHz, HDD storage, Ram: 8GB, Its using all cores for rendering. in this i am using ID_Genarator pyplug, i was created, i used ID_Genarator for Material ID Pass from Maya. (Info pass, EXR frames).

I am attaching my work flow screen shots, and you deleted my another request for ID generator pass script. please help me for ID generator pyplug. its very important for me.
![1](https://cloud.githubusercontent.com/assets/19346387/19244412/d7c9d384-8f39-11e6-8b8f-7bbce94b7f24.JPG)
![02](https://cloud.githubusercontent.com/assets/19346387/19244413/d7d12b52-8f39-11e6-863b-b244fc6d235d.JPG)

**Comment by kittumvkm** [comment]
Core: 4, 3.20GHz, HDD storage, Ram: 8GB, Its using all cores for rendering. in this i am using ID_Genarator pyplug, i was created, i used ID_Genarator for Material ID Pass from Maya. (Info pass, EXR frames).

I am attaching my work flow screen shots, and you deleted my another request for ID generator pass script. please help me for ID generator pyplug. its very important for me.
1
02

**Comment by olear** [comment]
If the renderer is using ~100% of your CPU then the viewer will be slow while rendering. Pushing play in the viewer is like rendering (but usually at a smaller scale).

Regarding the pyplug, I recommend you visit the forum for help (http://forum.natron.fr/c/development/python).
