### ISSUE TITLE
Viewer doesn't update

### ISSUE THREAD

**Issue by ElDirector** [MrKepzie/Natron#1468]
I'm not a coder, just a user.  I'm working on putting together a course that will bring lots of attention to the project, but I have to keep waiting to record the trainings due to stability.  By that I mean, the often times, even in small scripts of 20 nodes or less, the viewer fails to update.  Sometimes I can get around this by manually viewing each node in the script, but sometimes even that doesn't work.  I'm running Windows 10 on an Acer Aspire V, 8 gigs RAM.  I've tried both official "stable" releases as well as nightly builds.  At this point new features are secondary to me to getting the program stable for professional use.  I just need one rock solid version that is reliable and dependable to get things going.  

Most recently, this has been observed in 2.1.3, 2.1.4, and 2.1.5

**Comment by olear** [comment]
Have you tested 2.1.6?

**Comment by MrKepzie** [comment]
Closing as not a very detailed bug report.
