### ISSUE TITLE
PyPlugs load Natron 2.1.6 + Win10 64bit

### ISSUE THREAD

**Issue by marcmantra** [MrKepzie/Natron#1472]
I try to load the natron community PyPlugs and copying by hand on CommonFiles or using the installer, Natron only detect some of them.

### Problem

Natron 2.1.6. don't load all community PyPlugs

I expect that Natron, by hand or with installer, load all the PyPlugs.

LOST: Vignette, SSAO, ReShade, ReFlect, PM_VectorBlur, lp_Tweaky, lp_Despot, LightWrap_Simple, EdgeBlur, Defocus, ChromaticAberrationPP, Chromatic_Aberration.

### Versions

Natron 2.1.6 64bit
Windows 10 64bit

![loadcacheclean](https://cloud.githubusercontent.com/assets/18398652/19597628/fe09fd26-9795-11e6-89f9-55f5af24a89f.JPG)
![whatpyplugs](https://cloud.githubusercontent.com/assets/18398652/19597627/fe09e2b4-9795-11e6-905a-a04ecc0c1477.jpg)

**Comment by olear** [comment]
Just tested Win10 Pro and are not able to replicate, also (as you know) tested Win7 Pro/Enterprise, works fine there as well.
![win10](https://cloud.githubusercontent.com/assets/7461595/19597963/292ecd86-9798-11e6-8be4-5a044542c44b.png)

**Comment by marcmantra** [comment]
I will test it at home where I have a windows 7 Pro

**Comment by blackearth2014** [comment]
Does this community PyPlugs work for the Mac and if so, where can I get them?

**Comment by olear** [comment]
@blackearth2014 : https://github.com/NatronVFX

**Comment by devernay** [comment]
@marcmantra also try with a snapshot, they give much more information in the console. There also was a bug in 2.1.6 if you have PYTHONPATH set (it is sometimes set by third-party python installers)

**Comment by blackearth2014** [comment]
Thanks Olear

**Comment by marcmantra** [comment]
Still don't work for me, I downloaded the last snapshot and the result, using or not an Absolut Path for Pyplugs, is the same. Sorry MrKepzie but I want a solution, I need to reopen the issue
![snapshot_info](https://cloud.githubusercontent.com/assets/18398652/19695640/44c68364-9ae4-11e6-94d9-1b044da2aa32.JPG)
