### ISSUE TITLE
Crashes while rendering...

### ISSUE THREAD

**Issue by Chromatamata** [MrKepzie/Natron#1474]
Please ask questions ("how do I...?") on the [forum](http://forum.natron.fr), not by filing issues.

Make concrete suggestions for fixing the code ("here is a patch") by filing
a [pull request](https://github.com/MrKepzie/Natron/pull/new/master), not an issue.

Hi. I love Natron but I have a really severe problem. The program crashes nearly every time during a render. The crashes are random. Ie. They never occur at the same place in the render process. It can be at anywhere from 0% through to 99%. Very very occasionally, renders complete to 100% but it has only happened a few times. It mostly just crashes. I have tried using many different codecs and different container files. I doesn't help. I have tried moving all the files involved in the project onto the computer's main hard drive. It doesn't help. I have tried installing Natron and rendering on a second computer. It doesn't help. I have tried installing the latest version of Natron and I have also tried  using previous versions. It doesn't help. It seems to be worse, the more complex the nodal structure and the longer, therefore the render time. The problem is so bad that I cannot use Natron as an effective rendering tool... which is sad because I would like to. If it would just render it would be AMAZING! Both computers that I have tried had Windows 7 installed. I have tried using Natron 2.1.2, 2.1.6 and 2.1.7.
### Problem

Describe the problem or suggestion here.

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]
- If your problem is a crash in an official release/snapshot, please include verbose output from the application
  from a terminal if possible.  If you also submitted a crash report, indicate the CrashID if possible.
- If you need to report a compilation issue, please create a [gist](https://gist.github.com)
  that contains the _full_ verbose build log.
- If your problem is a crash in a build that you made yourself, please create a [gist](https://gist.github.com)
  that contains a _full_ backtrace.
### Steps to Reproduce
1. [First Step]
2. [Second Step]
3. [and so on...]

You may submit a link to any screenshots/videos that can be used to understand how to reproduce the issue.
### Versions
- **Natron version/commit** (they can be retrieved from the About Window): 
- **OS version:**

**Comment by devernay** [comment]
Did natron propose to send a bug report? did you send it? did you write some text in it that would make it recognizable?
Did you try rendering to frames in separate files (eg TIF, TGA, EXR) instead of video?
Do crashes happen when you just press play in Natron?

**Comment by Chromatamata** [comment]
Natron did not propose I send a bug report so I have not send one. I have not tried rendering frames to image format as that takes up a lot of space without time compression but I can try if you need me to. I have never had a crash when I press play in Natron...  not yet anyway. :-)

**Comment by Chromatamata** [comment]
Hang on. That is incorrect. I just left Natron in 'play' mode for an extended period and it did eventually crash. This is the error message I got. It is the same as the message I often get when it crashes during a render.
![natron 1](https://cloud.githubusercontent.com/assets/23139963/19831362/b118cdfc-9e53-11e6-9c70-8455b2d65b23.jpg)

**Comment by Chromatamata** [comment]
Ok. I have now tried rendering to tiff images, The same thing happens. The render fails and Natron crashes. I got this report from the dos window: 
![image](https://cloud.githubusercontent.com/assets/23139963/19898422/07446e8a-a0b0-11e6-982d-e25b4ae56adb.png)

**Comment by MrKepzie** [comment]
Could you record a video from starting Natron to the crash ? And can you also keep the console window in the screen recording if possible

**Comment by Chromatamata** [comment]
Hi. I really want to help solve this issue but I'm not sure exactly what you want me to do and why. I don't have facilities to screen capture and my computer is definitely running too slow when Natron is rendering to screen capture a video. In fact it runs so slow once I start to render that the mouse pointer lags behind any attempt I make to move the mouse. I can tell you what is written in the console window, there is never anything but a long line of reports saying 'No errors'. If you are trying to see at what point the program fails... it is totally random as I have said. I have checked to make sure I have enough RAM and I have more than enough. I have also checked that I have the right version of Open GL and I do. I don't get how this is working on Windows for other people... unless they never render the project.... :-/ If I can provide any more information, please let me know. :-)

**Comment by MrKepzie** [comment]
First off, you can adjust the number of threads rendering in the preferences if your machine starts lagging. Other than that, if you do no have a crash window, this likely indicates that the process is taking too much memory. Could you monitor the memory taken by Natron from the windows task manager and report how much memory Natron uses at the point of the crash (compared to how much available RAM you have)

**Comment by Chromatamata** [comment]
Ok. At the moment, my settings are at their defaults. ie. 0 or 'guess' for all thread options and whatever is set for memory usage also. The program says the optimum number of render threads for my computer is 4. I have done what you asked and here are the results: I have 4Gb of RAM in total. When I start rendering, RAM usage by Natron slowly climbs and reaches an average of around 2,700,000Kb/1024=2637Mb/1024=2.57Gb. Processor usage hovers around 95%. The total amount of RAM used by all applications averages around 3.8Gb. This is all while Natron is rendering properly. When Natron reports it has crashed in the console window, the RAM usage by the program drops slightly to around 2,500,000Kb and then rises again to around 2,700,000Kb as the program freezes and stops rendering. Processor usage falls to 4% at this point and the total of all used RAM remains high at around 3.8Gb until I force Natron to close. I hope this helps solve the problem. :-)

**Comment by MrKepzie** [comment]
Try to set the "Number of parallel renders" setting to 1 or 2, and then try again. 4GB of RAM is very slow for Natron. If you have a processor with a lot of cores it will try to render a lot of stuff concurrently, requiring more RAM.

**Comment by Chromatamata** [comment]
Ok. I will try and change the settings and see what happens. Do you think buying more RAM would fix the problem then and also speed up rendering?

**Comment by MrKepzie** [comment]
I am sure of it. 8GB is a minimum, 16GB to be comfortable, 32GB to have greatest perfs.

**Comment by devernay** [comment]
@Chromatamata Did changing the setting solve the issue?

**Comment by Chromatamata** [comment]
No... I have taken the number of parallel render as low as 1, like was suggested and that doesn't help. The program still crashes while rendering. Very annoyingly, I have now spent good money on a RAM expansion card for my computer so that I now have 8 Gb of memory (the maximum my computer can hold)... and  IT STILL DOESN'T WORK!!! Natron still crashes randomly during each render!!! Even with 8 Gb of RAM and parallel renders set to '1'.  It runs a bit quicker before it crashes but that's all that has been achieved!

**Comment by Chromatamata** [comment]
Ok... I want to give you another update that may help get to the bottom of this problem. I have managed to work around this problem in a very laborious way. My project was just over 4500 frames long. If I divide my project into lengths of 1000 or less then join the resulting files together later losslessly using external software, I am usually able to get through a render without a crash even with the simultaneous thread set to 4! (Not always but usually). In other words, none of the information being processed by Natron is causing a crash nor is the processing of any particular part of my project too data intensive for Natron to handle. As a programmer, myself, I would have to conclude, therefore that the likely cause of this problem is a memory leek. The longer the program runs and processes data, the more likely it is to crash... so something isn't being tidied up properly in memory. If that is the case, the trouble with that, as I'm sure you're aware, is that it may or may not be your fault. It may be some poor handling of memory you have programmed in by accident or it may well be something the language you are writing Natron in causes by itself or it could even be something Windows is doing wrong with the allocation of memory resources. Most people may not be encountering this problem as most people may be using the Linux or Mac version of your program which may implicate Windows as being at fault. If it is a memory leek and it isn't your own code's fault... it probably won't be possible to fix this. I hope I'm wrong as I LOVE NATRON. In fact, I may be addicted to it and want to continue using it without all these extra time consuming steps. :-)

**Comment by Kabouik** [comment]
I am having a similar issue on Linux (Solus x64, Natron 2.3.3, 8 GB of RAM). Every single attempt to render a video makes my computer hang and become totally unresponsive (can't even move the cursor) after a few percents of the rendering process.

I suspect the issue is due to Natron eating all the RAM, as I know 8 GB is not much for encoding. However, what I'm trying to encode is just 60 still images resized to 1920x1080 and saved in a compression format (JPG), so nothing too heavy and the final video shouldn't be too big either. I have 4 GB or swap in addition to the RAM.

I have tried using only one core for rendering or changing the encoding speed in the Writer settings, but no success either, it always ends up in a hard reboot or, more rarely, a Natron crash (but I'm not offered to send a report). **I wouldn't mind a slower rendring, especially with this small project, any idea how I could achieve that and tell Natron to prioritize memory usage instead of rendering speed?**

**Comment by Kabouik** [comment]
I managed to render the video but it took 4.5 hours (including freezes of the computer for more than one hour sometimes, I hesitated aborting with a hard reboot) and that was after expanding my swap to 22 GB in addition to the 8 GB RAM. The final video was only 3.9 MB in size in "High quality 1080p mp4" so such memory use seems a bit excessive (although there was some interpolatation/blending/retime in the process, which could admittedly be a bit demanding).

**Comment by devernay** [comment]
all temporary images in Natron are 32bit float. RAM is certainly useful in this situation
