### ISSUE TITLE
SmoothBilateral node error

### ISSUE THREAD

**Issue by marcmantra** [MrKepzie/Natron#1475]
Working compositing 3d renders on EXR 16bit I need to clean grain and I use SmoothBilateral node. Natron detects a problem and a new window appears, see attached image.

I use Natron 2.1.7 official release. Windows 10 64bits.
It happens while I'm working and appear when I load a new image sequence.
![bilateral_issue](https://cloud.githubusercontent.com/assets/18398652/19936663/899d9b86-a11e-11e6-8a58-8fa2ec2029e9.jpg)

**Comment by devernay** [comment]
Probably fixed, can you please check again?
