### ISSUE TITLE
Expression links in Shuffle won't work, nor be saved

### ISSUE THREAD

**Issue by CameraRick** [MrKepzie/Natron#1480]
### Problem

When I try to Expression-Link of the outputX of a shuffle, the Expression will return the right values but the value won't change. Furthermore, when you save the script and re-open it, the Expression is gone entirely.

HOWEVER, when not an Expression but a simple number is written in there, it returns the correct result. It's still not saved in the script.

Here's a video of the issue: https://youtu.be/ez9FrdVyVP8

**Expected behavior:** Expression should return the right result, and be saved :)

**Actual behavior:** Expression doesn't work and isn't saved

### Steps to Reproduce

1. Create a Shuffle and a custom-knob inside a group (I used pulldown)
2. Expression-Link the outputX of the Shuffle to the knob (I used an if/else)
3. See how it doesn't work out
4, Save the script, reopen
5. See the Expression beeing gone

### Versions

* **Natron version/commit** Natron 2.1.7 as well as 2.1.8. Snapshot from 161105
* **OS version:** Windows 10 Pro, but happened also on OSX 10.9.5 (only tested 2.1.7 there)

**Comment by MrKepzie** [comment]
will check

**Comment by nicholascarroll** [comment]
I have been having a very similar problem of expressions disappearing when saving, but in read nodes. on linux natron 2.1.6 and 2.1.7.
