### ISSUE TITLE
May be some Natron 3 will be based on JSON (instead of XML)?

### ISSUE THREAD

**Issue by timurhai** [MrKepzie/Natron#1481]
Less data, more human-readable.
Much more easy to parse/manipulate within Python.
Just Python dict() can be easy be represented by JSON and vice versa.

For examople:
If `app1.getProjectParam('projectPaths').getValue()` will return JSON, i can just:
    
    paths = json.loads((app1.getProjectParam('projectPaths').getValue())
    
And will have a much more comfortable object like you have in the code:
std::map<std::string, std::string> projectPaths;

Instead of parsing this:
`<Name>OCIO</Name><Value>/cg/soft/natron/2.1.7/Resources/OpenColorIO-Configs/blender</Value>`

What do you think?

**Comment by olear** [comment]
Natron 2.2 will use yaml.

**Comment by MrKepzie** [comment]
See https://forum.natron.fr/t/what-about-having-a-pyplug-repository/1027/30?u=mrkepzie

**Comment by timurhai** [comment]
O! Great!

JSON, YAML no matter (yaml even less size and readable), but XML - sucks for data!
 - but not for markup :)

But why Python API function `getProjectParam('projectPaths').getValue()` returns some not Python-native data? Why you translate it is some other format instead of writing `std::map<std::string, std::string>` directly to Python `dict`?

**Comment by MrKepzie** [comment]
Because there's no "dict" parameter natively, parameters are of base types **string**, **int**, **bool** or **double**. To implement the "dict" parameter we actually encode in the internal string the table with XML. 

We could add a function to the PathParam object to get the Python dict for convenience instead of parsing it manually if you want, because we already have such function available for c++

**Comment by timurhai** [comment]
Yes, `dict` is not a base type, but it is much more comfortable to operate with `dicy` in Python, instead of xml (even yaml).
For now, i already parse xml, and created an own function that returns project paths as `dict`. But i think that it will be much more comfortable for developers in feature to get something w/o any parsing.
If you do not want to return `dict` for some reason, you can return more "base" types, as an array of tuples of 2 strings, for example. But `dict` is more "user-friendly", i think, for example we can simple check for some key (path) w/o iteration.

**Comment by MrKepzie** [comment]
I added a function (in the master branch, will be out in 2.2) to retrieve the content of the table: http://natron.readthedocs.io/en/master/devel/PythonReference/NatronEngine/PathParam.html#NatronEngine.NatronEngine.PathParam.getTable
