### ISSUE TITLE
in Roto node, buttons for "remove keyframe" and "remove all keyframes" are next to each other

### ISSUE THREAD

**Issue by rebuilder** [MrKepzie/Natron#1483]
As per title, the buttons for removing one keyframe in a spline's animation and removing ALL animation from the spline are right next to each other. Undo doesn't seem to work if you accidentally press "remove all", so misclicking by a few pixels can result in a *lot* of work lost.

**Comment by MrKepzie** [comment]
Undo/Redo is implemented in 2.2. It will soon be available (end of november). Report back if it's not working by then
