### ISSUE TITLE
Disabled merge node passes wrong input through (IMO)

### ISSUE THREAD

**Issue by rebuilder** [MrKepzie/Natron#1484]
When creating a merge node with a node already selected, Natron defaults to connecting the selected node to the "A" input. Being used to Nuke, this seems backward to me. Now, you can switch this behaviour in the settings, but the problem is, doing so seems to also switch which input is passed through if the node is disabled. 

With the merge node connects to A input setting on, a disabled merge node will output whatever is connected to the A branch of the node, not the B branch. This seems very counterintuitive, since the merge operator's most common function is to add A over B, meaning B is the main branch.

**Comment by MrKepzie** [comment]
This is a preferences, in the Nodegraph tab. You probably have it checked even though by default it is uncheck (thus connect to B by default). It used to be the opposite like a year and a half ago but must have kept the old preferences.

**Comment by rebuilder** [comment]
Sorry, I wasn't clear.

I turned on the preference under nodegraph on purpose, because I prefer the Nuke-like behaviour of a new merge node created after a selected node automatically connecting the selected node to the A branch. This is fine.

IMO, when the merge node is disabled, it should NOT pass through the A branch even with this preference enabled. For example, think of the mix slider: 1 = full effect of compositing A over B, and 0 = B only. Why, then, does disabling the node return A?

**Comment by MrKepzie** [comment]
Oh ok I understand, so you want the auto-connect to A.
It seems indeed like a bug, the disabled input should always be B for merge.

**Comment by rebuilder** [comment]
OK, thanks!
