### ISSUE TITLE
Can't pick color for new stroke in rotopaint

### ISSUE THREAD

**Issue by rebuilder** [MrKepzie/Natron#1485]
In the rotopaint node, with the brush tool selected, the color box next to the color wheel above the viewer should let you pick a color from the viewer like color boxes everywhere else do. This does not seem to work. Clicking on the box does not add a dropper icon to the box, and ctrl-clicking in the viewer doesn't change the color.

**Comment by MrKepzie** [comment]
This is already fixed in 2.2
