### ISSUE TITLE
Rotopaint: Can't choose lifetime for strokes before drawing them

### ISSUE THREAD

**Issue by rebuilder** [MrKepzie/Natron#1486]
The Rotopaint node seems to lack a way to set the lifetime of strokes before you draw them, meaning you have to select each stroke after making them and change the lifetimes individually. Nuke has a dropdown menu in the rotopaint toolbar above the viewer with the relevant lifetime options - this seems like a good solution for Natron as well.

**Comment by devernay** [comment]
This issue was moved to NatronGitHub/Natron#172
