### ISSUE TITLE
Cannot find pyside_qtcore_python.h when building

### ISSUE THREAD

**Issue by theSoenke** [MrKepzie/Natron#1491]
### Problem

Building natron fails because it cannot find pyside_qtcore_python.h

I have pyside-devel installed and pyside_qtcore_python.h can be found at /usr/include/PySide/QtCore/pyside_qtcore_python.h

**Expected behavior:** [What you expected to happen]
pyside_qtcore_python.h should be found in /usr/include/PySide/QtCore

**Actual behavior:** [What actually happened]
natron cannot find pyside_qtcore_python.h

### Versions

* **Natron version/commit**  2.1.7 / 3644052235e83c9de69d7ced8f540fa2c417c1e6
* **OS version:** Solus

**Comment by olear** [comment]
pkg-config probably can't find PySide. Check the name of the .pc file of PySide on your system and add the info to a custom config.pri (see README for Linux).

**Comment by theSoenke** [comment]
Thanks for your quick response the .pc file was in /usr/lib/pkgconfig/pyside.pc
