### ISSUE TITLE
Write and Read nodes reset settings when input in filename field is changed

### ISSUE THREAD

**Issue by rebuilder** [MrKepzie/Natron#1492]
Natron 2.1.7:
Example:

Create a write node, select Cineon colorspace. 

Later on, update the write node's filename to e.g. a new version number.
The colorspace field is reset! Also, if frame range is set to "manual", the input boxes for start and end vanish, although the previously entered numbers are still used for rendering.

Same issue regarding the colorspace exists with read node.

**Comment by devernay** [comment]
# Expected behaviour

Natron should get the values for all parameters (including hidden parameters such as "ocioInputSpaceSet" for readers and "ocioOutputSpaceSet" for writers) and restore these in the newly-created plugin.

**Comment by devernay** [comment]
Reader/writer now keep most user-visible parameters. Create a new reader/writer if you want these to be set automatically.
