### ISSUE TITLE
Enhacement: "Officially" support for tuttleofx  

### ISSUE THREAD

**Issue by triceratops1** [MrKepzie/Natron#1494]
Tuttleofx is popular at VFX community, but has some issues:
* Incompatibility issues: Some plugins  are incompatible with Natron #1417 

* Pseudoabandon,  somme distros (Arch for example)  has very updated versions of gcc (gcc6) and boost,  and these updates breaks tuttleofx      

For it, i coinsider useful "natronize" the tuttleofx code; thanks.

**Comment by olear** [comment]
We bundled Tuttle (on Linux) back in v1.x when the plugin selection in Natron was limited. But after the release of v2.x we gained enough plugins that we didn't need to bundle Tuttle anymore.

Tuttle (on Linux) is compatible with Natron, you just need to build it (Tuttle) "right". If you build both Natron and Tuttle from source (on the same system) everything should work perfectly, but if you want to use the binaries Tuttle offer on the official Natron binaries you will get dependencies conflict. We follow the VFX platform CY2015 specs, something the rest of the VFX community also (should) do. So it's up to Tuttle to provide binaries "to spec" (but I think most users of Tuttle build it from source(?)).

I might consider maintaining a binary build of Tuttle "customized" to the Natron builds sometime in the future (put I will get a very low priority).

**Comment by triceratops1** [comment]
thanks

**Comment by devernay** [comment]
Also note that most TuttleOFX plugins do not support fully OpenFX.

**Comment by triceratops1** [comment]
@devernay  tuttle is "abandoned"?  
i see at this page that uses gcc 4

**Comment by olear** [comment]
@triceratops1 Tuttle is actively maintained.
