### ISSUE TITLE
Question: How could i install plugins (Compiled)

### ISSUE THREAD

**Issue by triceratops1** [MrKepzie/Natron#1495]
How could i install python plugins at Natron (if i've installed a Natron from source, instead of bundles)  

i share an example 
https://github.com/NatronVFX/natron-plugins

**Comment by olear** [comment]
Copy PLUGIN_NAME.p* to /usr/share/Natron/Plugins

**Comment by triceratops1** [comment]
@olear  but i can't find this folder.

i've installed with
https://aur.archlinux.org/packages/natron/    

this is the pkgbuild https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=natron

**Comment by olear** [comment]
http://natron.readthedocs.io/en/master/devel/natronpath.html

The community plugins also have an installer.

**Comment by triceratops1** [comment]
@olear this is the beta version??

even arch doesn't has it   
https://www.archlinux.org/packages/extra/i686/imagemagick/

**Comment by olear** [comment]
@triceratops1 I guess you meant to post in https://github.com/NatronVFX/openfx-community/issues/2 ?

https://aur.archlinux.org/packages/imagemagick-full/ , Not a beta, been stable for a long time.

**Comment by triceratops1** [comment]
pd i could ghet troubles if i force  the instalation (/usr/share/Natron/plugins)  because this pkgbuild doen't make it

**Comment by olear** [comment]
Why should the pkgbuild make it? If you want to use the python plugins use the installer or copy the plugins manually to /usr/share/Natron/Plugins or your home folder, see http://natron.readthedocs.io/en/master/devel/natronpath.html

**Comment by triceratops1** [comment]
that means:
Natron reads by default this folder (even if doesn't exist)     ?
