### ISSUE TITLE
Nodes do not seem to cache

### ISSUE THREAD

**Issue by rebuilder** [MrKepzie/Natron#1496]
I'd expect a node that's been rendered by plugging it into the viewer to get cached so that operations after that do not require re-rendering everything upstream. Especially I'd expect this to happen when "force caching" is checked under the node's settings. 

Example:
Create a Plasma node. Plug that into a DirBlur node with "scale" set to 2. This should take a second to render. 

Add a Noise node, and merge the two with a plus, plugging the Noise into the A input and the DirBlur into B. Connect viewer to DirBlur, wait until it finishes rendering. Connect viewer to the Plus node. Everything in the B input is rendered again.

The same occurs with "force caching" set for the DirBlur node.

Is my understanding of how caching works flawed?

**Comment by MrKepzie** [comment]
It should only re-render what it has not rendered. Images may be wiped out the cache if you reach the limit though; but on a simple graph like this, this is unlikely.
It works as you describes. If it does not, please provide a screen recording or a step by step recipe to reproduce the bug. I'm unable to do so wit the steps you given me (on 2.1.8 latest snapshot). 

Could you try to download the latest 2.1.8 snapshot and test?

**Comment by rebuilder** [comment]
I get the same results with the latest snapshot. Here's a screencast:

http://sendvid.com/t9j29km8

There seem to be some glitches in the video, with the desktop showing through in horizontal blocks - this is probably to do with the recording process, not Natron.

**Comment by rebuilder** [comment]
On further testing this seems to be a DoD-related issue. The dirblur of course pushes the domain of definition far outside the viewer bounds. Adding a crop after DirBlur seems to fix this.

**Comment by MrKepzie** [comment]
It's a small bug indeed in the computation of the RoI. Will be fixed in next snapshot.
