### ISSUE TITLE
EdgeDetect node produces -infinity values

### ISSUE THREAD

**Issue by PostPollux** [MrKepzie/Natron#1497]
### Problem

EdgeDetect node produces NaN Values if the "Mix" value of a following color correction node "Gamma" or "Grade" is set to 1

The following video shows that issue in the current edge blur pyplug, but you can easily reproduce it outside the edge blur in the nodegraph with any png file.
https://goo.gl/photos/QStXd6vhn1Xa5tkA9

### Steps to Reproduce

1. load a png
2. connect edge detect
3. set edge detect to alpha channel only
4. Add a "Gamma" or "Grade" node and connect it to the edge detect
5. notice the NaN warning. If you now change the mix value of the gamma or grade node, it dissappears. It's only present with the value set to 1

### Versions

* **Natron version/commit** 2.1.8 release
* **OS version:**  Linux Manjaro

**Comment by devernay** [comment]
f*** I thought I had fixed that one

**Comment by devernay** [comment]
workaround until 2.1.9: set filter to quadratic

**Comment by devernay** [comment]
Fixed in the latest snapshot
