### ISSUE TITLE
Numeric fields in node settings with expressions show last digits, not first, of multidigit numbers

### ISSUE THREAD

**Issue by rebuilder** [MrKepzie/Natron#1498]
The numeric fields in node settings seem to show the least significant digits of numbers.

### Steps to Reproduce
1. Create Constant node.
2. Enter the following expression for Color:
100000/3.1 and close the expression editor window
3. Mouseover the numeric box indicating the value for Color.

Alternatively:
1. Create Constant node.
2. Directly enter 100000/3.1 as the value for Color
3. Do not mouseover the numeric box

Results: 
The numbers displayed are "58.065", with the first 5 halway cutoff as it doesn't fit into the number box.

Expected results:
As the result of the expression, as checked by sampling colors from the viewer, is 32258.06445,
The numbers displayed should be "32258."

### Versions
Natron version 2.1.8 Release.
Linux Mint 17, Cinnamon desktop environment

![selection_011](https://cloud.githubusercontent.com/assets/404648/20354123/d06e373e-ac25-11e6-9cbb-b90af52f5a81.png)

**Comment by MrKepzie** [comment]
The idea is that you can quickly edit the expression when clicked instead of Right-Click and Edit Expression.

**Comment by rebuilder** [comment]
That sounds fine. The main issue was that it's hard to see what value is being output by the expression. Not a big deal of course, the curve editor for example is more useful for that purpose, but maybe something for the low-priority fixes list.

**Comment by devernay** [comment]
Can you please post a screenshot? I can't reproduce it. Also, please follow the guidelines for submitting. Please edit your first message.

**Comment by rebuilder** [comment]
Updated with screenshot

**Comment by devernay** [comment]
thanks

**Comment by devernay** [comment]
Ok, confirmed.
- set the expression to "32258.06445"
- when the mouse hovers the text entry, the cursor goes to the forelast character (why ???)
- it should just select the expression, and when the mouse leaves reformat it as a normal number

**Comment by devernay** [comment]
This issue was moved to NatronGitHub/Natron#174
