### ISSUE TITLE
Transform "center" resets when node input is changed

### ISSUE THREAD

**Issue by rebuilder** [MrKepzie/Natron#1501]
When a transform node has it's "center" value changed to e.g. allow rotating around a specific point, and the transform is then reconnected to either the same input node or a different one, the "center" parameter changes.

**Expected behaviour:**
No value in the transform nodes settings should change when the input is changed.
**Actual behavior:** 
When the input is changed, a transform node's Center parameter gets a new value.

### Steps to Reproduce

1.Create a roto node. Draw a shape. 
2.Add a transform after the roto.
3. ctrl-drag the transform widget in the viewer to move it to e.g. a feature on the roto you want to rotate around.
4. change the rotation value to something other than 0
5. Disconnect the transform from the roto, then reconnect it. Note the centerpoint you set is no longer where it was before disconnecting.

You may submit a link to any screenshots/videos that can be used to understand how to reproduce the issue.

### Versions

* **Natron version/commit** :
Natron 2.1.8 Release 
* **OS version:** 
Linux Mint 17, Cinnamon desktop environment

**Comment by devernay** [comment]
will fix.
center will only be reset  if it was not modified since the node creation.

**Comment by devernay** [comment]
fixed by https://github.com/devernay/openfx-misc/commit/73f474fca3ed8015498cd2cb001f8c9ef69dc62b
