### ISSUE TITLE
[Roto-rectangle] feature is missed: radius of corners...?

### ISSUE THREAD

**Issue by manuelsongokuh** [MrKepzie/Natron#1504]
hi

i see, there is missed the radius of corner (roto-rectangle) like as example from inkscape:

![url](https://media.inkscape.org/media/doc/tutorials/shapes/shapes-f02-en.svg.png)

name: radius of corner or roundes corner..

is there it? or for next version..?

thank you

**Comment by MrKepzie** [comment]
Just mask it with a radial or a crop with softness > 0

**Comment by manuelsongokuh** [comment]
hi,
my mind is blocked..
crop with softness > 0 this is true for job with natron..?!
mask it with a radial....never i see this functional from natron..
uhm.. okay.. i do use this strange step for effect..

i'm not understand that aftereffect has it like universal functional base feature..

but i'm not angry or bad feel.. only: I did not expect this from natron..
but my opinion that "rounded corner" is fundamental or standard for all software.. instead for "crop with softness > 0" this is shocked for me.. 

but for now i will use this strange mode, i hope for future will be new feature standard, i'm not insult you and natron developers ok?
only i'm shock..ok..okay..

**Comment by MrKepzie** [comment]
Natron is not a motion graphics dedicated software, unlike After Effects. If one day we change our roadmap to a motion graphics dedicated software, we will change our mind. We can't let feature requests opened forever knowing we will not implement them because we focus on something else.

**Comment by CameraRick** [comment]
> but my opinion that "rounded corner" is fundamental or standard for all software.. 

Definately not for this kinda Software, looking at Nuke or Fusion (which are closest).
Dan Sturm felt the same as you and wrote about that in his Blog, there was a Link to another Blog which did a nice Gizmo for Nuke. You should look that up and see if you can replicate it to a PyPlug in Natron. Sorry I'm on mobile so I have no links.

If you struggle with that, I might see if Natron can do what that Guy did in Nuke.

**Comment by MrKepzie** [comment]
thank you for backing up;) If you can put references to alternatives and workaround, you are welcome.

**Comment by CameraRick** [comment]
I'm on  computer now :)

Dan Sturms original blog entry: https://doingthatwrong.com/home/real-roundrects-nuke
And here's the further link, from Erwan Leroy: http://erwanleroy.com/nuke-tool-rounded-rectangle-tutorial/

I have no idea if Natron can Expression-link the points and handles of Rotos, if it can then it's a piece of cake to make something desired

**Comment by manuelsongokuh** [comment]
hi, 
first to all: 
if i wrote bad information to natron.. sorry, but i want not to write to bad information, so i want to feedback here to understand how will be best to situation like as here case " rounded corner" so to knowledge ok? 
thst liks from camerarick is interesting, and i'm not good python.. only to question here ok?
thank you for share opinions..

**Comment by CameraRick** [comment]
You don't need to know Python to build a PyPlug, I build a few and couldn't write three proper lines of Code :)

I will try to look into such a PyPlug, no idea when and if I will be able to though.

**Comment by devernay** [comment]
I may do it, it's not difficult, but it's low priority

**Comment by manuelsongokuh** [comment]
@MrKepzie : why title of natron github wrote:
![question natron-aftereffect](https://cloud.githubusercontent.com/assets/12126929/20447251/2707ded8-adde-11e6-87bf-1d006c02374b.png)

for this reason, i wish to try natron will be cool "compatibility" battle cool..

thank you to @CameraRick for links, it is helpful!

thank yo to @devernay 
i hope this "try" new little feature for entry natron..

:+1: :100:

**Comment by CameraRick** [comment]
"Similar" isn't "same", there are lots of things that Natron can't do that AE can, yet even more interesting, Natron can do a lot of things that AE can't :)
That beeing said, I'd like to point out that After Effects also has not really the options you show in the first entry, you can do simple round corners and the radius is clumsy to set up, and only manually changable after you created the shape.
Unfortunately, Natron can not (yet?) expression-link single points of a Roto like in the blog post I talked about earlier.

However, if you only want that behaviour from AE, you can simply hack any rectangular shape with a blur and a grade; just place a blur after the shape, and after that a grade which has the black point at around .5 and the white point at .501 or so; also, clip the whites, and if you want to keep the colour deactivate RGB and only use it on the Alpha, enabling the (un)premult option at the bottom. Then increase the blur to get rounded corners, fully adjustable... :)
I build a sample setup for this: 
[161119_Natron_RoundedRectangleHack_v01.zip](https://github.com/MrKepzie/Natron/files/601407/161119_Natron_RoundedRectangleHack_v01.zip)

**Comment by manuelsongokuh** [comment]
hi @CameraRick 
a thing that i want to understand:
-how does a person know this step (roto>blur>grade)..? from where is learn from what? (documentation?blog?trainning?university?high school?..)

-if if if if person does not know this step and what does he will do...how...?
maybe because person use most software where are there similar or standard functional: shape, text, rounded corner, or other example: alignment, snap, (this is example).

i know natron as nuke, this is ok for me, but natron is not easy to learn for new user? so i'm new user and never to use nuke, i use aftereffect base but aftereffect is there "little easy" for new user.  but i respect to Natron is extreme professional this is ok, i'm agreed.

so i'm new user for natron so i begin hard to learn but with long time.. 1 year to use natron but is not easy for me because i must to know before what i will want to create in natron because natron is based nodes..

so an example if natron has functional rounder corner this mean: new user will has not problem with natron so natron will many functional "to help to new user and expert", so i wish all people will use natron for expert and for new user, target: natron is be attract to all people.. so i think: natron will be need to use for (little) new user and (many) for expert..

but i want not discussion this.. i try to say my opinion, nothing "to force" ok?

try to read quote from **Don't Make Me Think**:
“They consist largely of people expressing strongly held personal beliefs about things that can’t be proven” ― Steve Krug, Don't Make Me Think
this quote connect to example functional (simple) rounde corner.. but is not unique (rounded corner) are there others functional..ok?

i want not influence to all you:i said you.  i do thinking my opinion ok?

try to read quote from **Don't Make Me Think**:
“They consist largely of people expressing strongly held personal beliefs about things that can’t be proven” ― Steve Krug, Don't Make Me Think
this quote connect to example functional (simple) rounde corner..but is not unique (this rounded corner) are there others functional..ok?

i want not influence to all you.. i do thinking my opinion ok?

**Comment by CameraRick** [comment]
Understanding of tools, or better call it beein creative with error solving. In the end it's trial+error

This is not a designated way to create rounded rectangles, it's a hack that gives you a similar result. A workaround. Everything has to be learned, that's why we are using forums and the likes, no? To learn and help :)
If you really need mainly motion graphics, I'd really recommend to more look into After Effects. I'm not saying Natron can't do most of the things, but it's far more intuitive, easy etc in AE; it's much better suited for that. Just like Natron is better suited for other things where AE sucks. You should understand Natron more as a compositor.

Natron isn't as easy to pick up as After Effects, but no body said it was easy :) there are dozens of courses online, "Nuke for After Effects users". Even The Foundry offers one, for free. You should watch that, because most of the things and I guess all of the concepts apply for Natron as they do for Nuke. 

I also think Natron lacks a few things. But the same goes for Nuke or AE; in Natron and Nuke, you have the ability to easily build your own tools that do what you need. For example, you could just build a PyPlug from my script and have rounded corners available easily anytime. Again, that isn't as easy or intuitive as After Effects, but only because something's easy doesn't mean it's good. And, there's always After Effects you can still use.

That example script from me was meant to show you that only because there's no dedicated function, it doesn't mean you can't do it. Just a different way of doing things.

Anyways, this somehow more feels like a discussion to have in a forum, not in a bug report on GitHub, so sorry for using it like that :/
The issue was assigned and will be solved some day, so everything is good :)

**Comment by manuelsongokuh** [comment]
thank you @devernay
