### ISSUE TITLE
Bug: Git hans up at natron

### ISSUE THREAD

**Issue by triceratops1** [MrKepzie/Natron#1505]
i am trying to upgrade natron
but i only get this log

fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed  

i am using this https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=natron

**Comment by olear** [comment]
We don't support or maintain the packages on Arch. Please contact the maintainer.

**Comment by triceratops1** [comment]
i fount this bug againt (i've downloaded BY HAND)

git clone -b 2.1.8 git://github.com/MrKepzie/Natron.git
Cloning into 'Natron'...
remote: Counting objects: 114935, done.
remote: Compressing objects: 100% (863/863), done.
fatal: read error: Conexión reinicializada por la máquina remota    
fatal: early EOF
fatal: index-pack failed

**Comment by olear** [comment]
Works fine here, check your internet connection (or maybe github has issues where you are, nothing we can do about it).
