### ISSUE TITLE
Bug: Compilation impossible

### ISSUE THREAD

**Issue by triceratops1** [MrKepzie/Natron#1506]
Tag: 2.1.8

https://gist.github.com/triceratops1/7ca0d47197589a443d2da6b955ba1d14

**Comment by olear** [comment]
Please read the documentation https://github.com/MrKepzie/Natron/blob/master/INSTALL_LINUX.md#openfx

**Comment by triceratops1** [comment]
no, i'm downloading these libraries  (openfx, google-test, googlemock and sequenceparser)
