### ISSUE TITLE
bundle a colour unmixing keyer enhancement

### ISSUE THREAD

**Issue by nicholascarroll** [MrKepzie/Natron#1508]
The recently published colour unmixing keying method from Disney is sure to be the new standard in keying. The paper is here: http://zurich.disneyresearch.com/~taydin/pdf/yagiz_tog16.pdf

The paper provides plenty of evidence that this method works extremely well most of the time.  Please develop a colour unmixing keyer to bundle in Natron.

**Comment by devernay** [comment]
Are you ready to spend 4 to 13 seconds per HD frame on that (using an optimized C++/CUDA implementation) ?

Quoting the paper:
> For  a  1080p  frame,  our  current  C++/CUDA  implementa-
> tion  typically  requires  10  seconds  for  local  color  estimation  (as-
> suming 8 dominant colors), another second to propagate the local
> color model to the following frame, and approximately 3 seconds
> for color unmixing. Thus, at this resolution, the total computation
> time for a still image is 13 seconds, which drops to 4 seconds per
> frame for image sequences.

Closing this issue (this represents too much work for us for a very small gain in quality and a high loss in efficiency)

**Comment by nicholascarroll** [comment]
It is able to do despill better than a professional can do, unless they resort to pixel painting. I would rather let the GPU do the work for me, and I thing other users would agree. 

Also colour unmixing may have other useful applications.
