### ISSUE TITLE
Shuffle node passes wrong channels

### ISSUE THREAD

**Issue by rebuilder** [MrKepzie/Natron#1509]
### Problem
When you have two image streams connected to a shuffle node, the shuffle node does not pass through the correct channels unless all channels are manually set, instead of using the nodes default settings.

**Expected behavior:** [What you expected to happen]
Shuffle node should pass the channels selected in its settings.
**Actual behavior:** [What actually happened]
If you select the components to be passed through as described in the procedure below, the shuffle node selects all channels from the B input, and none from A.

### Steps to Reproduce
1. create two noise nodes, with different sigma values so we can tell them apart.
2. For channel R, select "B.r"
3. For channel B, select "A.b".
4. Since in step 2 the shuffle switches all channels to come from B, you should now have: "B.r", "B.g", "A.b"
5. Note the B channel from input B is still passed through, not the one from input A.
6. Now, for channel G, select "A.g" and then "B.g" again - the shuffle node should now output the correct channels.

### Versions

* **Natron version/commit** (they can be retrieved from the About Window): 
Natron version 2.1.8 Release.
Also: Natron version 2.1.9 Snapshot, version 9e95ea9 
* **OS version:** 
Linux Mint 17

**Comment by devernay** [comment]
nice catch!
