### ISSUE TITLE
Rotopaint: Strokes are only rendered in frame most recently drawn in

### ISSUE THREAD

**Issue by rebuilder** [MrKepzie/Natron#1510]
Describe the problem or suggestion here.

When drawing strokes with a lifetime of 1 in rotopaint, and drawing strokes in different frames, only the frame with the most recently drawn strokes shows any strokes.

**Expected behavior:** [What you expected to happen]
Strokes should be rendered for all frames where they are drawn
**Actual behavior:** [What actually happened]
Drawn strokes stop getting rendered if new strokes are drawn in a different frame.

### Steps to Reproduce

1. Create rotopaint node
2. Draw a stroke with the default pencil tool in e.g. frame 1
3. Step to e.g. frame 2, draw another stroke.
4. Step back to frame 1, notice the bounding box of the stroke is shown, but no stroke is visible.
5. Draw another stroke in frame one, the first stroke drawin in step 2 reappears. However, strokes in frame 2 are now invisible.

### Versions

* **Natron version/commit** :
Natron 2.1.9 Snapshot, version  9e95ea9 
* **OS version:** 
Linux Mint 17

**Comment by MrKepzie** [comment]
This is because the lifetime of strokes is set to "Single Frame" by default. You may change it. The real bug is that the bounding box is showing up.

**Comment by rebuilder** [comment]
It should still display in the frame its lifetime is set to, right? The issue here is that if I draw a stroke with a lifetime set to frame 1, then draw a stroke in frame 2, again with a corresponding single frame lifetime, the stroke in frame 1 no longer gets rendered, even if viewing frame 1.

**Comment by MrKepzie** [comment]
This indeed was a bug
