### ISSUE TITLE
viewer: format of project not show, is it normal?

### ISSUE THREAD

**Issue by manuelsongokuh** [MrKepzie/Natron#1512]
hi

i find strange: when i set project setting format size is 1920x1080, in viewer is ok, (area size from setting)
i add node read png big size, but i cant to see the true area 1920x1080, where is it?
is it strange or is it normal..? maybe i'm wrong human?

![screenshot_20161125_140014](https://cloud.githubusercontent.com/assets/12126929/20626081/8eef994e-b317-11e6-9134-bff6b38790d5.png)

**Comment by MrKepzie** [comment]
Natron does not show the project format anymore, just the Format of the input.
