### ISSUE TITLE
Old PyPlugs have duplicated inputs after reload of natron project

### ISSUE THREAD

**Issue by PostPollux** [MrKepzie/Natron#1515]
### Problem
When I use PyPlugs, save my file and reopen it, some of the pyplugs have duplicated inputs that don't work at all. I guess it has something to do with the old plugin-format as the already converted pyplugs bundled with Natron seem to work fine.

**Expected behavior:** [What you expected to happen]
No duplicated inputs

### Steps to Reproduce

1. put in some pyplugs into the nodegraph
2. save your file
3. close natron and reopen the file
4. Some pyplugs now have duplicated inputs

Video with demonstration:
https://goo.gl/photos/AUWvEBKjmTqy4fDz9

### Versions

* **Natron version/commit**  
Natron 2.1.8 Release

* **OS version** 
Linux Manjaro

**Comment by devernay** [comment]
@PostPollux can you please attach a faulty PyPlug?

**Comment by PostPollux** [comment]
Sure. Just tested it again under 2.1.9 with Windows and the issue is still present. I think it's with all the pyplug from https://github.com/NatronVFX/natron-plugins
But as I tested it right now with three of them, I attach them here: 
[testPyPlugs.zip](https://github.com/MrKepzie/Natron/files/682033/testPyPlugs.zip)

**Comment by MrKepzie** [comment]
Hmm I cannot reproduce here:

![screen shot 2017-01-03 at 13 07 34](https://cloud.githubusercontent.com/assets/4058448/21607328/aa561534-d1b5-11e6-9a75-009780a95111.png)

**Comment by PostPollux** [comment]
Strange. I have that issue under Windows and Linux with Natron version 2.1.9
Did you save and reopen the file? No idea why it works on your side...

**Comment by sozap** [comment]
I've got the same issue here on Linux with Natron 2.1.9

**Comment by sozap** [comment]
I've tried to investigate a bit into this but I can't find something...
![capture du 2017-01-06 12-42-48](https://cloud.githubusercontent.com/assets/9614046/21716930/1ac71aa2-d40e-11e6-98ea-16465f7ee360.png)

- Everytime the project is saved and reloaded every node inside the PyPlug is duplicated

- If the PyPlug is converted to a group, then it's getting ok...

- In my natron config I set the Pyplug folder to my git repository of the comunity plugins .

- I've created some test Pyplugs outside this folder and they seems to work fine.

- In the .ntp file it's obvious that the nodes gets duplicated, try to look for "ID_Pass"
[test.ZIP](https://github.com/MrKepzie/Natron/files/689814/test.ZIP)

#totalmystery

**Comment by olear** [comment]
In RB-2.2 I can't seem to get duplicated inputs, but additional inputs (like mask) seems a bit odd.

Normal:
![1515-1](https://cloud.githubusercontent.com/assets/7461595/21718736/a0bb463c-d419-11e6-86e9-134362e1faee.png)
Mask is at the right and hidden if I don't hover the node.

Save and reopen project:
![1515-2](https://cloud.githubusercontent.com/assets/7461595/21718756/c064f122-d419-11e6-9490-3195cec3fa78.png)
Mask input has now moved and is not hidden anymore.

**Comment by PostPollux** [comment]
Ok, I again investigatet this issue for a while and I think I have found what's causing it!!!

The problem seems to occur, when a PyPlug is located in a subfolder!

I did the following test:
1. I removed all the pyplugs from the community plugins repository.
2. I just copied the orton.py  to   myHomeDirectory/.Natron
3. I started natron, placed the orton plugin, saved the script, opened it again. Everything looks ok.
4.  then I created a new folder in this directory.  (myHomeDirectory/.Natron/Orton) and moved the orton.py to this directory. I then opened the exact same file which I created in step 3. Bam! There are the duplicated inputs.

It's also reliably reproducible if you just create a new  pyplug and put it in a subfolder.
I hope this helps!

**Comment by sozap** [comment]
Hey very well done PostPullux , this as driven me mad for a while !

**Comment by MrKepzie** [comment]
Ok I fixed it, mainly the bug was because it wouldn’t restore properly the PyPlug (it wouldn’t find the file) if it was in a subdir of a path set in the plug-ins search paths.
It also fixes the input positioning issue when reloading.

**Comment by PostPollux** [comment]
Cool! Thank you so much for fixing!
