### ISSUE TITLE
Roto bounding box doesn't follow the bezier shape when transformed

### ISSUE THREAD

**Issue by sozap** [MrKepzie/Natron#1516]
### Problem
when I draw a roto shape and I transform it using the transform tab, the bound box of the shape stay in the original place rather than surrounding the shape.

**Expected behavior:** [What you expected to happen]
It's more logical that the bounding box follow the shape

**Actual behavior:** [What actually happened]
I've made a screenshot to illustrate the point : 
![roto_bbox](https://cloud.githubusercontent.com/assets/9614046/20689798/6719e82c-b5c7-11e6-972c-185e207e4c70.jpg)

### Versions

* **Natron version/commit** (they can be retrieved from the About Window): 
Natron version 2.1.8 release

* **OS version:** 
Linux Debian

**Comment by devernay** [comment]
This issue was moved to NatronGitHub/Natron#178
