### ISSUE TITLE
Spaceship demo project does not load (3.0)

### ISSUE THREAD

**Issue by devernay** [MrKepzie/Natron#1519]
### Problem

```
Error while loading project: OpenGL renderer kCGLRendererIntelHDID has 288 MB of VRAM and 256 MB of texture 
No matching pixel format exists for renderer kCGLRendererIntelHDID 
OpenGL renderer kCGLRendererGeForce8xxxID has 512 MB of VRAM and 489 MB of texture 
OpenGL renderer kCGLRendererGenericFloatID is not accelerated 
Found OpenGL Renderer: NVIDIA GeForce GT 330M OpenGL Engine , Vendor: NVIDIA Corporation , OpenGL Version: 2.1 NVIDIA-10.2.12 310.90.10.05b20 , Max. Texture Size 8192 ,Max GPU Memory: "488.3 MB" 
setting OCIO= "/Users/devernay/Development/Natron/App/build/Debug/Natron.app/Contents/Resources/OpenColorIO-Configs/blender/config.ocio" 
ERROR: Project loader: Error while loading project: Unrecognized or damaged project file
Error: Could not load project.
```

### Versions
This software was compiled from the source code branch master at version d9dcaf1 using Clang version 8.0.0 (clang-800.0.42.1) targetting Intel x86-64 for Mac OS 10.12.0-10.12.1.

**Comment by rebuilder** [comment]
The spaceship demo project seems to need a bit of reworking anyway - the example of unpremultiplied workflow no longer works, as the read node now also provides output premult settings, which default to premultiplied. Presumably this wasn't the case when the project was created.

**Comment by olear** [comment]
@rebuilder  It's an example project from v1. We use it to check compatibility with old projects, and it's part of the unit tests (which fails due to this issue btw).

**Comment by devernay** [comment]
This issue was moved to NatronGitHub/Natron#180
