### ISSUE TITLE
getClipPrefs is called on disactivated nodes, and format is applied

### ISSUE THREAD

**Issue by devernay** [MrKepzie/Natron#1520]
### Steps to Reproduce

1. Reader<-Reformat<-Viewer
2. disactivate the reformat, the format is still changed

### Versions

* **Natron version/commit** (they can be retrieved from the About Window): 2.1.9
* **OS version:**

**Comment by MrKepzie** [comment]
Fixed in master

**Comment by devernay** [comment]
Is it possible to fix it in the 2.1 branch? (master has too many bugs to be usable for now)
