### ISSUE TITLE
Crash if Natron is closed while playback is running

### ISSUE THREAD

**Issue by rebuilder** [MrKepzie/Natron#1521]
### Problem
When  the viewer is running playback, and Natron is closed, the program will crash. I've submitted a report with CrashID:

093094b3-1173-3375-3f4802c1-77a42b56

### Steps to Reproduce

1. Create an SENoise node in a new project, connect viewer to it and press play.
2. Without pressing "stop", close Natron. Don't save (I don't think this matters, but it's what I did)
3. Natron will crash.

### Versions

* **Natron version/commit** 
2.1.9
* **OS version:** 
Linux Mint 17

**Comment by devernay** [comment]
This issue was moved to NatronGitHub/Natron#181
