### ISSUE TITLE
Roto shape

### ISSUE THREAD

**Issue by ramellij** [MrKepzie/Natron#1522]
Sometimes roto shape points and curve disapear when you zoom on. And sometimes when I try to select multiple points of a shape I get or nothing or a wrong selection. It really makes me loose time :(

My plate is a 4,6K EXR footage and I'm working with Natron 2.1.9 stable release on windows 7 pro 64 bit. 

Thanks for your help
JR

**Comment by devernay** [comment]
can you make a screencast showing the problem maybe?

**Comment by ramellij** [comment]
![15284805_10154803536463216_3378270071612340729_n](https://cloud.githubusercontent.com/assets/12991885/20848916/81ef2a94-b8d4-11e6-901c-caeee9b5e145.jpg)
![15194519_10154803535348216_2111089397474848505_o](https://cloud.githubusercontent.com/assets/12991885/20848917/820a14e4-b8d4-11e6-815e-a24b6aa33776.jpg)

**Comment by devernay** [comment]
can you either attach or send us a project with just the roto node (we don't need the input images) ?

**Comment by ramellij** [comment]
Hello, 
Sorry for the delay I was busy. 
Here the comp file : https://we.tl/pPvKYqTs0y
I used tracker nodes to help my rotho that's why the .ntp file is so huge (maybe that's the problem). Good thing whould be to cache those data outside, it takes long time to open. 

Thanks for your help
JR

**Comment by MrKepzie** [comment]
Can you describe what's wrong in detailed? I opened the project here and I can see the roto shapes fine

**Comment by devernay** [comment]
about the heavy roto shapes: we will probably add a shape simplification function to the next version.

**Comment by ramellij** [comment]
an exemple : https://we.tl/nSj82pVymV

**Comment by ramellij** [comment]
it seems related to the transform node : https://forum.natron.fr/t/roto-shape-disappears/1241/4

**Comment by devernay** [comment]
This issue was moved to NatronGitHub/Natron#182
