### ISSUE TITLE
Roto circle not perfect

### ISSUE THREAD

**Issue by mray** [MrKepzie/Natron#1524]
**Using Natron 2.1.7 Release on Ubuntu 16.10**

Pressing SHIFT while dragging a roto ellipse should result in a perfect circle. I just noticed it does not, it is close, but not perfectly round between the four control points.

![selection_025](https://cloud.githubusercontent.com/assets/164785/20854610/a04904d0-b8f5-11e6-9e67-f64c12c02609.png)

**Comment by devernay** [comment]
The bezier control points should be:

    P_0 = (0,1), P_1 = (c,1), P_2 = (1,c), P_3 = (1,0)

with c = 0.551915024494 

See http://spencermortensen.com/articles/bezier-circle/

Alex, can you plz check and put that reference in the code?

**Comment by devernay** [comment]
btw, if you want real circles with proper antialiasing, the Radial plugin from Natron >= 2.1.8 is the way to go (set softness=0)

**Comment by devernay** [comment]
![image](https://cloud.githubusercontent.com/assets/3778071/20978166/306b6e4e-bca8-11e6-9eb9-2fbdffabc762.png)
