### ISSUE TITLE
Natron 2.1.9 Reader seems to break EXR input on file open.

### ISSUE THREAD

**Issue by B4adle7** [MrKepzie/Natron#1528]
### Natron 2.1.9 EXR Reader (or possibly Reader in general?)

EXR Reader nodes seem to error upon open in Natron 2.1.9, even though they are valid.

**Expected behavior:** Open your composite using EXR image sequence(s) as input and they work.

**Actual behavior:** Open a saved composite file, one that you had just been using, and even rendered with, EXR Read nodes are RED stating invalid images. You can create a brand new Read node, and load in the exact same image sequence into it, and it is valid. Until you save that file and re-open. Now that Read node is erroring. No crashing.

### Notes:

Still need to test further to really identify. 
Installed. 2.1.9
Re-installed 2.1.9
Upgraded 2.1.8 to 2.1.9
Have not confirmed on other machines or other Natron users yet.
Due to time constraints, un-installed and re-installed Natron 2.1.8 in order to continue processes.

### Steps to Reproduce

1. Create a small composite using an EXR or EXR image sequence as input.
2. Save that file.
3. Re-open that same file and see if the EXR Read node is valid.
4. Rinse
5. Repeat

### 2.1.9

* **Can add later when time to re-install happens.**
* **Windows 10 x64 Pro**

**Comment by MrKepzie** [comment]
You should use the Read node to open EXR files, using the ReadOIIO decoder. The ReadEXR decoder should not be used (and is not used by default since it is deprecated)

**Comment by B4adle7** [comment]
Oh, has been a while.
Just a quick follow up.
Where at all was ReadEXR mentioned in the bug report?
What is a ReadEXR decoder?
The post was about how the Read node had failed on the EXRs.
Old post, hopefully this doesn't reopen it.
