### ISSUE TITLE
Playback set to stop behaves a bit confusing

### ISSUE THREAD

**Issue by PostPollux** [MrKepzie/Natron#1530]
### Problem

When the playback behaviour is set to "stop" the playback stops at the outpoint, but as soon as you click somewhere earlier in the timeline it immediately plays back again. 

Video:
https://goo.gl/photos/4bwzpkxKhiuo65Pn8

**Expected behaviour:** [What you expected to happen]

Either: 
completely stop, so that it doesn't start again, if I click in the timeline 

or: 
The red stop button should remain, so that there is an indication that it still tries to run and that you can cancel the playback.

### Versions

* **Natron version/commit** (they can be retrieved from the About Window): 
Natron 2.1.9 Release

* **OS version:** 
Linux Manjaro

**Comment by devernay** [comment]
@MrKepzie should be easy to fix, can you take a quick look?
