### ISSUE TITLE
Feedback on three issues I can not reliably reproduce

### ISSUE THREAD

**Issue by PostPollux** [MrKepzie/Natron#1531]
### Problem
I worked on a project animating some neurons. While working on this project I stumbled across several issues that I just couldn't reliably reproduce. I spent hours to trace down those bugs, but in the end it didn't help. Still no clue how to reproduce them.
Maybe someone else has those problems, too. Or maybe even an idea what causes them and how the solution could look like.

So here is a video where I talk about the 3 issues I ran into:
https://goo.gl/photos/BEhQtmdQB1fw9yf46

Any idea? 

### Versions

* **Natron version/commit** (they can be retrieved from the About Window): 
Natron 2.1.9 Release

* **OS version:** 
Linux Manjaro

**Comment by PostPollux** [comment]
ok, here I just caught another one! Or maybe the same one but with other nodes. You can see it live in this video: 
https://goo.gl/photos/nmbtHd4MHeSXbCYc6

It's behaving similar to the first I explained in the video before. When I hover over the viewer it get's stuck again. Sorry I forgot to show it in the video. It's important to note, that you can't just reproduce those errors by building the same node graph again. If I build it step by step in a seperate graph in order to find the bug, it doesn't appear. And I don't think it's the glow pyplug, as it works in other comps and as something similar happend with the color correct and grade as mentioned in the first video. So maybe it's something more general with updating the properties bin and the viewer. It's always one thread being 100% busy with the whole UI freezing. 
This bug is a real showstopper!

**Comment by devernay** [comment]
I think the plugins that are open in the properties bin have their inputs cached. So that's probably a cache bug.
@MrKepzie what do you think of these bugs? Can you take a look at these?
I ish we could have working master-branch snapshots, because the engine was completely rewritten, so except for fixing obvious bugs there is little chance we fix anything in the cache system of the 2.1 branch.

**Comment by devernay** [comment]
BTW @PostPollux in such cases you can also send us a downloadable link to a working project (we probably just need one frame)

**Comment by devernay** [comment]
This issue was moved to NatronGitHub/Natron#183
