### ISSUE TITLE
Nodes missing when build from source

### ISSUE THREAD

**Issue by theSoenke** [MrKepzie/Natron#1532]
### Problem
Nodes missing when build from source

**Expected behavior:**
All nodes are available when build from source

**Actual behavior:**
I build Natron from source and have the problem that nodes are missing as you can see in the screenshot.

![natron-nodes](https://cloud.githubusercontent.com/assets/1757301/21081088/82ea9d92-bfbf-11e6-8763-c368dbdc4593.png)

I've used the latest release 2.1.9 https://github.com/MrKepzie/Natron/releases/download/2.1.9/Natron-2.1.9.tar.xz

The release tarball contains all required openfx dependencies right? Any idea whats the issue or i'm doing wrong?

Thanks

**Comment by olear** [comment]
The nodes are external projects.

* https://github.com/MrKepzie/openfx-io
* https://github.com/devernay/openfx-misc
* https://github.com/olear/openfx-arena

**Comment by theSoenke** [comment]
Thanks for the clarification
