### ISSUE TITLE
Time remaining display in progress window don't handle hours correctly

### ISSUE THREAD

**Issue by noccy80** [MrKepzie/Natron#1534]
### Problem

The time remaining column in the progress window don't seem to handle hours correctly. The whole hours aren't effectively subtracted from the minutes when displaying.

**Expected behavior:** 119 minutes would be displayed as "1 hour 59 minutes"

**Actual behavior:** 119 minutes is displayed as "1 hour 119 minutes"

### Steps to Reproduce

1. Create or load a project and set it up so that will take over an hour to render
2. Render the project, and pay attention to the displayed remaining time in the progress window.

### Versions

* **Natron version/commit:** 2.1.9 (issue observed since at least 2.1.7)
* **OS version:** Ubuntu 16.04 (x64)

**Comment by MrKepzie** [comment]
This was already reported and fixed https://github.com/MrKepzie/Natron/issues/1529
