### ISSUE TITLE
Feature Request: Improved Feedback on Noise Reduction "Sample" Quality

### ISSUE THREAD

**Issue by marcdraco** [MrKepzie/Natron#1540]
Noise reduction is really good but the one thing it lacks (once again, this is from my experience with NEAT Video - that's how they style it, I'm not shouting) is a hint that your sample area is screwy in some way, shape or form.

For example if one of the channels is potentially clipped (hard 0 or hard 1.0) OR if the are contains other oddities - such as details - NEAT warns you that this might blow your noise profile.

I'm a big fan of NEAT, Vlad and his team have done an awesome job and I was happy to pay for my licence but since you've already got a pretty good denoiser, it never hurts to take a hints from other designers.

**Comment by devernay** [comment]
This issue was moved to NatronGitHub/Natron#185
