### ISSUE TITLE
Doesn't read .MTS from my camera

### ISSUE THREAD

**Issue by kepkin** [MrKepzie/Natron#1541]
I can't read files from my camera in .MTS format (while all other applications read it flawlessly). You can download a small example:
https://drive.google.com/file/d/0B5fHyf95881BOF9kdHNTYW9fMk0/view?usp=sharing

**Expected behavior:**
I can see my source video in viewer and apply other nodes.

**Actual behavior:**
Viewer is black, and I see a red bar with error in top of viewer window.
`Read1 error: FFmpeg Reader detected decoding stall, possible file corruption`
Here is output in terminal:
````
[h264 @ 0x7f84ac6612a0] reference picture missing during reorder
[h264 @ 0x7f84ac6612a0] Missing reference picture, default is 2147483647
````

### Steps to Reproduce

1. Add read node (here is [example video](https://drive.google.com/file/d/0B5fHyf95881BOF9kdHNTYW9fMk0/view?usp=sharing) 8mb )
2. Connect viewer
3. Try to play video

### Versions

* Natron version 2.1.9 Release.
* Ubuntu 15.10

**Comment by devernay** [comment]
The ffmpeg reader has several issues and will be completely rewritten.
In the mean time, you can transcode your videos on the command-line using ffmpeg (a ffmpeg binary is provided with Natron if you don't have one) to a format/codec which is more suitable (mov container is OK, and prores and dnxhd are much better for post-production work)
see https://trac.ffmpeg.org/wiki/Encode/VFX

**Comment by devernay** [comment]
This issue was moved to NatronGitHub/Natron#186
