### ISSUE TITLE
Roto Bezier weird behaviour when you manipulate bezier shape keyframes

### ISSUE THREAD

**Issue by ridlimod** [MrKepzie/Natron#1542]
### Problem

When you remove a keyframe of a Roto Shape in the properties panel it seems to be removed ok, but it still has some influence on the shape key. When you move another keyframe on Curve Editor, it seems to be restored, except for some glitches on feather render. Also if you move a keyframe on the Curve Editor and then undo the move by Ctrl-Z, it seems to be restored too, but the glitches become even weirder. I've attached a video showing the issues. 

### Steps to Reproduce

1. create a Roto Shape
2. make 3 keyframes separated 25 frames from each other
3. delete the first keyframe from Properties Panel or Curve Editor
4. play

Video with much more detail:
[weirdroto.mp4.zip](https://github.com/MrKepzie/Natron/files/689784/weirdroto.mp4.zip)

### Versions

* **Natron version/commit**:
Natron version 2.1.9 Release 
Arch Linux with KDE Plasma
Windows 10 Updated
macOS Sierra 10.12.2

**Comment by MrKepzie** [comment]
I thought we squashed that bug already. I will investigate again.

**Comment by MrKepzie** [comment]
This is fixed, will be available in 2.1.10 and next snapshot

**Comment by devernay** [comment]
2.2 actually

**Comment by ridlimod** [comment]
Ok, great guys!!
