### ISSUE TITLE
Change default plugin directory

### ISSUE THREAD

**Issue by theSoenke** [MrKepzie/Natron#1543]
Is there a way to change the default plugin directory from /usr/OFX/Plugins to something like /usr/share/OFX/Plugins? Changing the path in Engine/Settings.cpp did not work for me

**Comment by MrKepzie** [comment]
Just add it in the UI in the Preferences. This is not in Natron this is in openfx/HostSupport and I advise against changing it since it is written in the OpenFX standard specification.
