### ISSUE TITLE
Natron fills all the RAM when rendering

### ISSUE THREAD

**Issue by rezemika** [MrKepzie/Natron#1544]
Hello, I am a new user a Natron (which I love). Compositing works well, but during the rendering, Natron fills quickly all the RAM available until the whole computer freezes (at approx 80%), even with simple projects.

It happens with Natron 1.2.9 on my both computers : 

- the first, under Fedora, with a FX-8350 and 16Go RAM ;
- the second, a laptop under Xubuntu 16.04 with a Core I3 and 8Go RAM.

I tried with a very simple project where I merge two solids (a black and a white) and the render completed successfully. However, the render of a project where I change the scale and the blur of a text freezes around 50%.

In the settings, I allow Natron to take up to 85% of the RAM. I tried with one or two rendering process without success.

PS : I apologize for the English mistakes.

rezemika

**Comment by MrKepzie** [comment]
Try to reduce the number of Parallel Render threads in the Preferences/Threading. 
Natron requires a lot of RAM, do not run other heavy applications in the background. 
These problems should be solved in the next major release but for now the only way is to reduce the number of threads.
