### ISSUE TITLE
Writer node records

### ISSUE THREAD

**Issue by ramellij** [MrKepzie/Natron#1546]
Hello 

How can I disable the write node to save and export constantly my viewport frame ?
For example : when you render a shot and then navigate to a certain frame ou can go check the render of that same frame and see its proxy result. I don't know if that's clear :)

I'll try to make you a video
JR

**Comment by devernay** [comment]
you want to render a single frame with the write node?

**Comment by ramellij** [comment]
No a sequence but the writer continue to export every frame I cache in the viewport so even after a complete export your sequence is modified just by using Natron. 
a better video resolution : https://we.tl/HqII8ZhxpX

**Comment by ramellij** [comment]
all I do in the video is connect and disconnect one merge node in Natron Node Graph and reload the EXR sequence in after effect whithout rendering.

**Comment by devernay** [comment]
This issue was moved to NatronGitHub/Natron#188
