### ISSUE TITLE
Can't "save as" 

### ISSUE THREAD

**Issue by ramellij** [MrKepzie/Natron#1548]
Hello, 
I can't "save as" anymore. Natron freezes anytime I try to save a new project (even when it's empty without nodes). 
I reinstalled it, removed appdatas, restart everything and it continues to freeze. I can't work on a new project I just can open old ones :(

Please help
JR

**Comment by MrKepzie** [comment]
Can you give some more details as to when does it freeze ? During the file dialog ? After clicking open on the file ?

**Comment by ramellij** [comment]
there is no file dialog, it freezes just before

**Comment by MrKepzie** [comment]
This is probably because the favorite configuration in the file dialogs contains a location that is invalid (maybe a network location). 
It can be cleared by going in the windows registry:

HKEY_LOCAL_MACHINE\INRIA\Natron

or

HKEY_CURRENT_USER\INRIA\Natron

**Comment by ramellij** [comment]
ok, do you know on windows the complete path to access that file ?

**Comment by MrKepzie** [comment]
This is not a file, this is in the registry. You can delete everything under the directories I pointed to you.
In the next version of Natron we will store this in a local file.

**Comment by ramellij** [comment]
I removed all path I had in the file dialog (cause I still can use a reader node) but it changes nothing. 
I found a file dialog reg_binary in HKEY_CURRENT_USER/Software/INRIA/Natron but it's impossible to read for a human eye ;)

**Comment by ramellij** [comment]
WOW IT WORKED !!!

**Comment by ramellij** [comment]
I just removed the complete registry folder and now it pops up as it should

**Comment by ramellij** [comment]
So it means we can't save network path in file dialog ?
It would be great if we could (as Maya) switch with the Native OS file Dialog.

**Comment by MrKepzie** [comment]
The native file dialog does not allow to retrieve image sequences. The real issue is that it crashed, but I'm unable to reproduce on my end

**Comment by ramellij** [comment]
yes but like after effect you could have just one little button to specify if it's a file or a sequence you are selecting.

**Comment by ramellij** [comment]
But as it works I can't complain ;)

**Comment by MrKepzie** [comment]
This has been fixed anyway for next minor release
