### ISSUE TITLE
Python API picks up deleted nodes

### ISSUE THREAD

**Issue by mangopipeline** [MrKepzie/Natron#1549]
### Problem

It seems that if a node is created and then deleted the api is still picking up this node.
this makes it hard to write scripts for asset management.

**Expected behavior:** [What you expected to happen]
if I create a node and then delete it, the api should no list it.

 
### Steps to Reproduce
1. open natron to an empty scene
2. create a read node
3. delete the read node
4.run the following snippet and watch the node get listed even tho it has been deleted in the gui

import NatronGui as NE
nApp = NE.natron.getActiveInstance()
rT = 'fr.inria.openfx.ReadOIIO'
print [c for c in nApp.getChildren() if str(c.getPluginID()) == rT]

### Versions
2.1.8

**Comment by MrKepzie** [comment]
Internally, nodes have an "activated" state, so that when the user undo, they are back again in the node graph. We cannot remove them entirely from Python when they are in this state, but I can add a Python functions to check this state.

**Comment by mangopipeline** [comment]
To me it would make more since that getChildren only return active nodes... this is how most sdk work, like nuke maya, max etc.

It would also be great if changing properties on a deleted node raised an exception, like "this node no longer exists"

The isNodeDeleted method you mention above would still be very helpful as variables could still point to a deleted object, and a td might want to check the node before doing processing on it.

Thanks for looking into this, the API is coming along nicely.

**Comment by devernay** [comment]
I agree with @mangopipeline , getChildren should return active nodes only, and the idea of an exception whenever an inactive node is modified in some way is also a nice guard against possible errors.

**Comment by MrKepzie** [comment]
It's fixed in RB-2.2

**Comment by mangopipeline** [comment]
this is still broken in 2.2.6

**Comment by mangopipeline** [comment]
nApp.getChildren()
is still returning deleted nodes nodes
and node.getParam('activated') is returning None

you mentioned added a method to query activate state?
could you share a snippet? thank you!

**Comment by MrKepzie** [comment]
See http://natron.readthedocs.io/en/master/devel/PythonReference/NatronEngine/Effect.html#NatronEngine.NatronEngine.Effect.isNodeActivated

**Comment by mangopipeline** [comment]
will do thanks!!!

**Comment by mangopipeline** [comment]
Does this only work on Natron 3?
looking at the docs i think this should work....
```
import NatronGui as NE
nApp = NE.natron.getActiveInstance()
print  [c for c in nApp.getChildren() if c.isNodeActivated()]
```

getting the following error...

`'NaronEngine.Effect' object has no attribute 'isNodeActivated'`

this thing really messes with any form of asset management... :(

**Comment by MrKepzie** [comment]
Yes it's only in 3 sorry for the confusion. I don't quiet understand your issue, here it works very well:

- I create new project, I only have a Viewer1
- I create a Blur1 node
- I remove the Blur1 using the backspace key
- I execute the following:

    print  [c.getScriptName() for c in app1.getChildren()]

I get this:
    [u'Viewer1']

I undo, I now get this:

    [u'Viewer1', u'Blur1']

**Comment by mangopipeline** [comment]
cool,
I think the problem might be with creating the read node via script....
if i make the nodes by hand, they work as i would expect...
but when python makes and populate the read node, it's another story

let me try to get a better example that we can replicate...
in the mean time you can see a video of the problem i'm having here...

https://drive.google.com/open?id=0B3Irm8-2LgJsekFuVzNSd1dfN28

**Comment by mangopipeline** [comment]
1)make project
2)run this code

```
import NatronGui as NE
nApp = NE.natron.getActiveInstance()

rT = 'fr.inria.openfx.ReadOIIO'

path =  r"X:\358_infiniti_spinifex\04_sequences\103\001-010\2d\publish\comps\comp_master\v0002\fullres\103_001-010_comp_master_v0002.####.dpx"
path.replace('\\','/')

#create the node here
node = nApp.createNode(rT)
node.getParam('filename').set(path)

#print the number of read nodes in the scene
readNodes =  [c for c in nApp.getChildren() if str(c.getPluginID()) == rT]
print 'number of reads in the scene',len(readNodes)
```
3)notice the print statement 'number of reads in the scene 1'
4)delete the create read node by hand and run the code agein
5)notice the print statement ''number of reads in the scene 2'

if you continue to create the read node via script and deleting by hand the number of read nodes continues to increase

**Comment by mangopipeline** [comment]
so maybe the but is with the createNode method...

**Comment by mangopipeline** [comment]
just following up were you able to replicate the problem with my last code sample?
maybe the way i create my read nodes is wrong?

**Comment by mangopipeline** [comment]
maybe i should open it up as a new issues?
