### ISSUE TITLE
hitting "yes" in "New Pyplug Version" dialog immediately overwrites the script file

### ISSUE THREAD

**Issue by PostPollux** [MrKepzie/Natron#1550]
### Problem

If I open a script, that uses an outdated PyPlug and then hit "yes"  in the "New Pyplug Version" dialog, your original file gets immediately overwritten. 
I think that's dangerous. What if the new version causes some problems or even break your script? You can't go back in this case, because the original file doesn't exist anymore!

I mean I could easily imagine myself hitting "yes" to test if everything works fine. Then if there are no problems I would save the script, so that it now uses the new pyplugs. But of course if it causes problems, I wouldn't save the script, but close natron and hit "no" the next time opening it.

![warning](https://cloud.githubusercontent.com/assets/9008901/22105037/7811785e-de42-11e6-80ee-41417d1dfaa4.png)
Btw: There is a typo. PyPlyg -> PyPlug

**Expected behavior:** [What you expected to happen]
I think it would be better, if it didn't save the file immediately and you have to do it manually. Or at least it should warn you that it's overwriting your script. But I would prefer the manual approch.

### Steps to Reproduce

1. Save a script with a pyplug
2. Now increase the version of the pyplug
3. open the script again. There should be the warning now.
4. hit "yes". Now your original script has already been replaced. You can confirm this by either look in the .ntp file itself, or close natron and loading the script again and noticing no warning popping up anymore.

### Versions

* **Natron version/commit** (they can be retrieved from the About Window): 
Natron V 2.2

* **OS version:** 
Linux Manjaro

**Comment by MrKepzie** [comment]
It is known and fixed in version 3: When loading a Pyplug, if a more recent version is installed, a warning will be displayed, exactly like OpenFX plug-ins.
