### ISSUE TITLE
minor Version in PyPlugs broken?

### ISSUE THREAD

**Issue by PostPollux** [MrKepzie/Natron#1551]
### Problem

If I have a PyPlug and hover the questionmark in the properties bin it always says something like: "name version 2**.0**" which implies there are minor version numbers for PyPlugs.

Also, if I look into the .ntp file there is a tag for minor version:

`                <item>
			<Plugin_label>versionTest1</Plugin_label>
                        <Plugin_script_name>versionTest1</Plugin_script_name>
                        <Plugin_id>versionTestd</Plugin_id>
                        <PythonModule>/home/johannesw/.Natron/versionTestv1.py</PythonModule>
                        <PythonModuleVersion>1</PythonModuleVersion>
                        <Plugin_major_version>1</Plugin_major_version>
                        <Plugin_minor_version>0</Plugin_minor_version>`

But when I export a PyPlug and put something like "2.5" in the version text box and then look at the exproted .py file I noticed it had been altered to just 2.
If I then manually change it to 2.5 and save it, everything works, but inside natron hovering the questionmark it still says 2.0. And if I save the script and look into this file the result is also:

`<Plugin_major_version>2</Plugin_major_version>
<Plugin_minor_version>0</Plugin_minor_version>`

So I think if PyPlugs are supposed to support minor versions, then it's broken, if not, maybe it would be better to change 2.0 to 2 (hovering the questionmark) and give a hint of not supporting minor versions in the tooltip when exporting the pyplug.

### Versions

* **Natron version/commit** (they can be retrieved from the About Window): 
Natron 2.2

* **OS version:** 
Linux Manjaro

**Comment by MrKepzie** [comment]
There are no minor versions for PyPlugs in version 2.2. In Natron 3 there will be.
