### ISSUE TITLE
360 VR aware nodes

### ISSUE THREAD

**Issue by alcomposer** [MrKepzie/Natron#1552]
This feature request is for the ability to allow current spacial effects (Denoise, blur, sharpen etc) to function within a VR contex.  Nodes could either be specialist for VR - or utilise current nodes- with an added VR boolean.  These nodes would take into consideration the equirectangular image space, and it's distortion at the top and bottom poles.  This is to say for example bluring would have to be different closer to poles than at equator to make up for the extreme difference in mapping.

Also spacial nodes would obviously need to calculate blur (as an example) based on a "wrap around" of the image in spherical space.

I have a great interest in using Natron with Blenders VR Cycles rendering, and as such would be interested in compositing VR EXR's using Natron.

Further down the track when Natron gets 3D compositing it would also be fantastic to be able to have VR included as well.  However that is not included in this FR.  

This FR is simply for 2D VR compositing tools, which will still be useful in the future for bluring VR backgrounds or denoising VR renders/ footage.

A VR 360 equirectangular rotating node (VR panning) would also be useful- but this is already possible with a shadertoy script.

Please contact me if you require more info.

Cheers
Alex

**Comment by devernay** [comment]
This is a lot of very secific development: either do it yourself, find someone who does it for you, or pay for this development (and check out the price of the 360VR options in commercial software).
We certainly won't do this in the open source version
