### ISSUE TITLE
Add an extra input to EdgeBlur node

### ISSUE THREAD

**Issue by sozap** [MrKepzie/Natron#1553]
EdgeBlur node is a great addition, however I would find it even better if we can have an external input for the edge detection instead of using the Alpha channel of the main input.

General usage for me go like this : 
Merge Foreground over Background (so the alpha is taken from Bg and is pure white) , then with a shuffle node I put back the Foreground alpha after the merge. Do the edge blur to soften the transition between Fg and Bg. Then with another Shuffle set the alpha back to full white.
Maybe I miss some good practice here but that force me to use two extra shuffle node to do the blur.

It would be better to have the alpha as another input that can be taken directly from the Fg.
Or a toggle button that can enable current workflow or the one that I would like.

I can look into doing that change as it's a Pyplug.

Thanks, 

### Versions

Natron 2.2.1

**Comment by devernay** [comment]
I agree. There should be a "Matte" input.

**Comment by devernay** [comment]
What do you think about this one?

[EdgeBlur2.py.zip](https://github.com/MrKepzie/Natron/files/723996/EdgeBlur2.py.zip)

Unfortunately, PyPlug versions are badly supported in Natron 2, so changing EdgeBlur would break old projects

**Comment by sozap** [comment]
Hey, that look more efficient to me like this...
What do you think about having a checkbox enabled by defaut that use the source alpha (old behaviour) and when disabled it switch to the new one... So when updating nothing breaks ?

Anyway if this one is included in version 3 that's not a big issue at all

Thanks !

**Comment by devernay** [comment]
get it from https://raw.githubusercontent.com/devernay/openfx-misc/master/CImg/Blur/EdgeBlur.py

**Comment by devernay** [comment]
you can overwrite the version in the binary distribution with this one
