### ISSUE TITLE
info HSL 

### ISSUE THREAD

**Issue by GladiatorFX** [MrKepzie/Natron#1554]
In the info HSL, H (Hue) has only two values integer: 0-1.
Theoretically should have values ​​from 0 ° to 360 ° or at least values ​​normalized floating point (as happens for SL).

I am not referring to any particular node. I refer to the info HSL alongside the RGB info down to the viewer.

Natron 2.2.1

**Comment by devernay** [comment]
fixed in 2.2.2 (coming soon)
