### ISSUE TITLE
Natron is not reading image sequences form Apple FCPX and Apple Motion apps.

### ISSUE THREAD

**Issue by blackearth2014** [MrKepzie/Natron#1556]
**Problem**

Getting an error when reading an image sequenced files rendered from Apple FCPX & Motion.

**Expected behavior:**
Read image sequences from Appe FCPX ad Motion without error the same as previous versions of Natron did.

**Actual behavior:**
The OFX message bar at the top of the viewer is red and says "Failure to find requested layer in file" Natron's Read node will load a single image from the sequences but not the sequence itself.

![screen shot 2017-01-23 at 12 58 54 am 2](https://cloud.githubusercontent.com/assets/7956901/22193207/bfc72366-e107-11e6-997c-b200d7b792af.png)

**Steps to Reproduce**

To reproduce use a rendered an image sequence from Apple FCPX & Motion. I can upload if required.

**Natron version/commit**
v 2.2.1
OS version:
Mac OS X Yosemite 10.10.5

**Workaround**

I load the files into Blender's VSE timeline and render out the image sequences from there and then I am able to read them in Natron.

**Comment by spartacruz** [comment]
This also happen to me!

The different is, I've images seq files rendered from Autodesk Flame.

I also test on another suite (like NukeX) and the sequence is fine.

Natron version/commit
v 2.2.1
Windows 7 Professional 64bit

Could someone tell us whats the problem it is?

**Comment by devernay** [comment]
@blackearth2014 can you reduce the size of the image sequence (check if the bug appears with only 10 frames) and upload it somewhere?

**Comment by blackearth2014** [comment]
Fred,

There are 10 frames from my Nature2Nature project in black & white.

[Nature By Nature.zip](https://github.com/MrKepzie/Natron/files/724214/Nature.By.Nature.zip)

**Comment by devernay** [comment]
OK I get the bug. Will fix tomorrow!

**Comment by blackearth2014** [comment]
Major thanks Fred.

**Comment by devernay** [comment]
fixed in 2.2.2 (coming soon)
