### ISSUE TITLE
NatronRenderer does not return when enableCrashReports=false

### ISSUE THREAD

**Issue by shutdown256** [MrKepzie/Natron#1559]
Hi,
NatronRenderer process (with script file as parameter) will not terminate after `Write1 ==> Rendering finished` and just hangs. This only happens when **enableCrashReports** is set to **false**. I have managed to reproduce this issue both on Windows 7 and Debian 8 under Natron 2.2.2

**Comment by nicholascarroll** [comment]
see also issue #1198

**Comment by devernay** [comment]
good catch, Nicholas, they are probably related

**Comment by devernay** [comment]
This issue was moved to NatronGitHub/Natron#189
