### ISSUE TITLE
Recent projects under file menu not displayed correctly

### ISSUE THREAD

**Issue by rebuilder** [MrKepzie/Natron#1560]
### Problem

Under "Open Recent" in the file menu, the filenames of recent files are not displayed correctly

**Expected behavior:**
The filename of the recent project should be displayed
**Actual behavior:** 
The name of the directory containing the project is displayed. If I have a project in /home/user/projects/comp.ntp , it is listed as "projects".

### Versions

* **Natron version/commit** Natron 2.2.2 version 6d43554 
* **OS version:** Linux Mint 17, Cinnamon Desktop.

**Comment by PostPollux** [comment]
I can confirm this under windows 10 with Natron 2.2.2

**Comment by devernay** [comment]
fixed in https://github.com/MrKepzie/Natron/commit/9cae55f282c7f081f33df5b1f694954292f56ce5 , will be in 2.2.3
