### ISSUE TITLE
Shuffle node passes wrong channels

### ISSUE THREAD

**Issue by rebuilder** [MrKepzie/Natron#1561]
### Problem
When selecting shuffle node channels, Natron appears to pass them correctly but in fact does not.

**Expected behavior:** 
When you switch the default value of a shuffle dropbox, e.g.  set "R" from "A.r" to "B.r", the node switches all inputs to come from the B input. Expected behaviour is for all channels passed through to be from the B side.

**Actual behavior:** 
Natron appears to pass the correct channels, however, upon reloading the project, the shuffle node's settings are changed so that the dropdowns that were automatically set to B inputs are now referring to the default A inputs again. 

### Steps to Reproduce

1. In a project, create two constants with different color values (for clarity) and connect them to the inputs of a shuffle node
2. For "R", select "B.r" Note the rest of the dropdowns also change to point to the corresponding B channels.
3. Save the project, close and reopen it.
4. Check the settings of the shuffle node. The inputs you didn't set manually have reverted to their default state.

### Versions

* **Natron version/commit** Natron 2.2.2 version 6d43554
* **OS version:** Linux Mint 17

**Comment by PostPollux** [comment]
I can confirm this, too.  Win10 / Natron 2.2.2
