### ISSUE TITLE
Feature Request - motion-prediction re-timing

### ISSUE THREAD

**Issue by marcdraco** [MrKepzie/Natron#1562]
This was written by one of the chaps behind the excellent (if slightly buggy) Kdenlive

http://slowmovideo.granjow.net/

I wonder if the core can be incorporated into Natron at some future time?

**Comment by devernay** [comment]
No time to do it now. May be in a future version.
There are also commercial plugins which do it much better than slowmovideo.
Slowmovideo warped images the wrong way last time I checked - negative backward warp instead of forward warp, which causes artifact on motion boundaries.

**Comment by marcdraco** [comment]
Thanks for pointing that out (saves me time, no pun intended).

I'm looking for a totally FOSS re-timer for our open movie project - so I'll have to work around it.

Marc
