### ISSUE TITLE
Viewer switches to rotopaint node when painting and viewing different node

### ISSUE THREAD

**Issue by rebuilder** [MrKepzie/Natron#1563]
### Problem
When viewing a node downstream from a rotopaint node, and painting in the rotopaint node, the viewer will switch to display the output of the rotopaint. This makes it very difficult to edit masks and keys with rotopaint.

**Expected behavior:** [What you expected to happen]
The viewer should not automatically switch

**Actual behavior:** [What actually happened]
Viewer switches unexpectedly to display rotopaint node.

**Comment by MrKepzie** [comment]
This is known and not going to be fixed in version 2: this can lead to glitches and bugs which are not possible to be fixed in that version. In Natron 3 it will be possible. Note that this was already reported before https://forum.natron.fr/t/rotopaint-to-viewer/1211
