### ISSUE TITLE
UI feels slow + needs clean up

### ISSUE THREAD

**Issue by freder** [MrKepzie/Natron#1566]
hi,

new natron user here.
version `2.2.2`
on macos `10.12.3`

I have a few first impressions concerning the UI that I want to share with you.

---

## UI feels slow

example: scrolling long lists is very, very slow — and I'm on a brand new macbook pro.

<img width="251" alt="screen shot 2017-01-27 at 15 36 08" src="https://cloud.githubusercontent.com/assets/724844/22374431/6a639e16-e4a6-11e6-991c-4d8426ff75b7.png">

---

## low-res icons

the icons look pixelated on a retina display.

<img width="452" alt="screen shot 2017-01-27 at 15 35 42" src="https://cloud.githubusercontent.com/assets/724844/22374458/8ee0c58e-e4a6-11e6-978d-3a2bf5546190.png">

---

## misc

here and there are cases like this, where things aren't properly aligned, for instance.

<img width="900" alt="screen shot 2017-01-27 at 15 35 16" src="https://cloud.githubusercontent.com/assets/724844/22374491/ac194fc2-e4a6-11e6-94eb-9f2260fef12a.png">

**Comment by devernay** [comment]
- UI feels slow: the popup menu you mention is pretty useless anyway. This is Qt, so we cannot do much on this side.
- low-res icons: won't be fixed before Natron 4. This doesn't affect the use of Natron anyway. The viewer should be hires too in Natron 4.
- misc alignment: yes, we know, we we have limited resources to fix this kind of very small bug. Please submit a patch and we will gladly include it.

**Comment by erson** [comment]
There might be some low level stuff to do.

Take a look at this blog post. 
http://x64dbg.com/blog/2017/03/18/caching.html

**Comment by devernay** [comment]
This issue was moved to NatronGitHub/Natron#190
