### ISSUE TITLE
ReelSmartMotionBlur renders only first frame

### ISSUE THREAD

**Issue by mifth** [MrKepzie/Natron#1570]
Hi,

I'm testing RSMB for Natron. I downloaded free linux version. And Natron renders only first frame with RSMB. Is this Natron issue?

My test: https://youtu.be/yxA5LzVZSOY
My scene [natron_test.ntp.zip](https://github.com/MrKepzie/Natron/files/743386/natron_test.ntp.zip)

### Steps to Reproduce

1. Install RSMB http://revisionfx.com/products/rsmb/natron/
2. open my scene 
[natron_test.ntp.zip](https://github.com/MrKepzie/Natron/files/743386/natron_test.ntp.zip)

3. Play RSMB node

### Versions
2.2.3

**Comment by mifth** [comment]
I had a discussion with Revision team:

"Apply the time|Frame Range plugin before RSMB
You will see it says 1 to 1 in your project 
Change it with Frame Range (the out point) - does it work now?
It does here

Pierre"

If I add Frame Range node before RSMB then all will be ok.
![selection_010](https://cloud.githubusercontent.com/assets/2251298/22532762/55820890-e8fa-11e6-9302-8234b8c0eb94.png)


We can close the issue. Or possibly there can be some improvements for Natron?

**Comment by devernay** [comment]
Thanks to Pierre for solving this!

Closing it:

- You can also get the framerange information of a connection from the Info tab of each node in the properties panel
- "Constant" is a generator and thus can be given a frame range in its parameters. it is 1-1 by default.
- The default framerange of an image sequence or video is the range of the sequence
- "Merge" outputs the union of its input frame ranges, so this issue usually doesn't happen with RSMB
