### ISSUE TITLE
Crash Report 11fe9eae-221c-1a41-25929b5a-1427324f

### ISSUE THREAD

**Issue by mkel** [MrKepzie/Natron#1571]
ntp file that renders in headless NatronRenderer in OSX and Windows, always crashes around 30% progress on Linux (Natron-2.2.3-1.x86_64.rpm)

**Comment by MrKepzie** [comment]
Seems to be related to the Text plug-in and freetype

**Comment by mkel** [comment]
Thanks, I'll investigate that.
