### ISSUE TITLE
Export curve to ACSCII gives only zeros

### ISSUE THREAD

**Issue by Eneen** [MrKepzie/Natron#1573]
I've tried to export curve to ASCII from ColorLookup node and file is containing coordinates but value is always 0.0.
I've got small suggestion here. Maybe it's worth to implement here curve standard from RawTherapee. Here is example:

> Spline
0 0
0.098 0.055
0.207 0.215
0.273 0.334
0.336 0.461
0.461 0.67
0.547 0.776
0.625 0.847
0.699 0.897
0.785 0.94
0.863 0.97
0.935 0.99
1 1

It contains both XY coordinates, not only "Y-values". Thinking about dividing X axis when loading and saving is somewhat weird and not really accurate.

Natron v. 2.2.3, Windows 10.

**Comment by devernay** [comment]
RawTherapee's format is not consistent with natron's internal representation (which are bezier).
If you wan the curve with its control points and tangents there are two solutions:
- use the python API
- save a preset (button "settings and preset" in the titlebar of the properties panel). The presets are XML in Natron 2 and will be YAML in Natron 3 (more readable and less verbose)

**Comment by Eneen** [comment]
Sure, I know, suggestion was to use X+Y coordinates to avoid dividing when exporting and importing, one step less to make mistake. But if YAML is easier to read maybe that option will not be required anymore...

**Comment by devernay** [comment]
fixed by https://github.com/MrKepzie/Natron/commit/af0c39c1973835508c9916d8a1c2c29de6565d72 https://github.com/MrKepzie/Natron/commit/5019e6950d2173f0fe8c2ffef801fe06dfed93f0 https://github.com/MrKepzie/Natron/commit/976962fd71d6d53675308e6ead049da9d7238690
