### ISSUE TITLE
Drag and drop images from network locations (Bug, Windows)

### ISSUE THREAD

**Issue by Celeborn2BeAlive** [MrKepzie/Natron#1574]
### Problem

On windows, dragging and dropping images from a network location to the node graph does not work properly.
I actually observed two cases:
1. If the network location is not mounted, it can be manually overcome
2. If the network location is mounted, Natron seems to crash and I must kill it

**Expected behavior:**

Creation of a functional "Read" node when I drag and drop an image from a network location.

**Actual behavior:**

Case 1:
A "Read" node is created but with a wrong file path that must be edited manually to get the image loaded.
For exemple, if the windows path of the file is "\\a\b\c\image.exr", the node is created with "/a/b/c/image.exr" as file field. This must be edited to "//a/b/c/image.exr".

Case 2:
The program stop to respond and must be killed.

### Steps to Reproduce

1. Open Natron and create a new project.
2. Drag and drop an image from a network location to the graph.
3. *Case 1 only*: At that point a "Read" node is created but the image is not loaded.
4. *Case 1 only*: You can edit the field to add the missing "/" at the beginning to get the image loaded.

### Versions

* Natron 2.2.2 Release, compiled from branch tags/2.2.2 at commit 6d43554
* Windows 7 Pro

Thank you for the support, Natron is really great :)

**Comment by devernay** [comment]
This issue was moved to NatronGitHub/Natron#193
