### ISSUE TITLE
Crop node:"reformat" setting does not reformat

### ISSUE THREAD

**Issue by rebuilder** [MrKepzie/Natron#1575]
### Problem
Checking the checkbox for "reformat" in crop node does not change the format of the output.

**Expected behavior:** [What you expected to happen]
The output format of the node should change to match the crop selected
**Actual behavior:** [What actually happened]
The output format remains the format of the input stream.

 ### Steps to Reproduce

1. Create a checkerboard node
2. Connect checkerboard to a crop node
3. Use crop node to crop away some of the checkerboard, and check "reformat" in the crop node.
4. See output in viewer - the format displayed remains whatever the project format is.
5. Write the output of the crop to disk with a write node. For "Format Type" in the Write node, select "input format". 
6. Read the file just written out back in. Note that the file's pixel dimensions correspond to the format of the project, with black around the cropped part. It does not seem to be possible to write out a cropped image without black borders.

### Versions

* **Natron version/commit** 2.2.4 version cb4c91a 
* **OS version:** Linux Mint 17

**Comment by devernay** [comment]
This is normal: if the extent is not "Format" or "Project". I will make it more clear in the doc. This is because the size parameter can be animated, but the format can not be animated.
see https://github.com/devernay/openfx-misc/blob/79bacbbab43478de3b7098cc680afb1628097879/Crop/Crop.cpp#L723

**Comment by devernay** [comment]
fixed in https://github.com/devernay/openfx-misc/commit/9140d2cb9e6f9f588a01538384facde5f25584ba

**Comment by rebuilder** [comment]
OK, thanks for the clarification.

I still think this seems a little clunky. 

Simply not using reformat in crop, and instead adding a noop after the crop node with extent set to size, and the coordinate values linked from the crop upstream, and set format checked results in behaviour that is much more akin to what I personally would expect. I'll make a pyplug out of it I guess.
