### ISSUE TITLE
bug or crash: natron is strange [2.2.4]

### ISSUE THREAD

**Issue by manuelsongokuh** [MrKepzie/Natron#1580]
i dont know where is problem from..

see screenrecord  01 :
[natron-crash-bug-01.zip](https://github.com/MrKepzie/Natron/files/783841/natron-crash-bug-01.zip)

see screenrecord  02 :
[natron-crash-bug-02.zip](https://github.com/MrKepzie/Natron/files/783842/natron-crash-bug-02.zip)

file NTP
[COMPOSITE.zip](https://github.com/MrKepzie/Natron/files/783844/COMPOSITE.zip)

reproduce ever times..

**Comment by manuelsongokuh** [comment]
other screenrecord 03: 
[natron-crash-bug-03.zip](https://github.com/MrKepzie/Natron/files/783897/natron-crash-bug-03.zip)

there is other strange preview in viewer, node text is not correct..
my computer is dual intel xeon E5-2620 v3 204GHz
32 GB ram
opensuse 42.2 64bit

**Comment by devernay** [comment]
This issue was moved to NatronGitHub/Natron#194
