### ISSUE TITLE
Conflicting key bindings. Number keys used for nudge roto and tracker

### ISSUE THREAD

**Issue by nicholascarroll** [MrKepzie/Natron#1582]
This relates to issue #1408, which had the numpad keys made the default for nudge roto and nudge tracker markers. However this introduced a new bug which is that it is not the numkeys but the ordinary number keys. 

ACTUAL BEHAVIOUR
The ordinary number keys are the default and changes to the default wont save.
EXPECTED BEHAVIOUR
The numpad keys should be the default and it should be possible to change the default
PLATFORM
This is on Ubuntu 16.04, Natron 2.1.9.

IMPACT
The ordinary number keys are used to switch viewer. Users do this constantly so if they dont deselect the roto shape they accidentally nudge it. 

NO WORKAROUND!
This problem cannot be fixed by changing this default value because the change to the default is somehow not working. 

SUGGESTION FOR A QUICK AND EASY FIX
Perhaps just leave the default for this blank and the user can set their own default. I say that to try and make it easy as possible for someone to fix this soon.

**Comment by devernay** [comment]
should be fixed in the next snapshot, please test

**Comment by nicholascarroll** [comment]
OK, going to test this now on linux

**Comment by nicholascarroll** [comment]
With this snapshot 2018-3-31 the roto is no longer interfering with the previous/next frame arrow keys. 
The results are several facts:
1. The ordinary number keys are no longer the default: GOOD! We can work fine with this.
2. The default is not the number keys, it is an unrecognized key combination. Trying to set a numpad key does not work, it only assigns the normal number key there.
3. I assigned a key combination (control + left arrow) to nudge roto left and it worked great.  
4. Still can't save the assignments: Despite saving the key settings before closing the preferences window, after restart of natron, the key assignments have reverted to the default.

**Comment by devernay** [comment]
This issue was moved to NatronGitHub/Natron#195
