### ISSUE TITLE
OpenFX Plugin Search Paths not working in Natron 2.2.5

### ISSUE THREAD

**Issue by SebastianBugna** [MrKepzie/Natron#1584]
Problem:

I'm building Plugins based on openfx-misc plugins. 

When I build them, I usually added the path to the .ofx.bundle in Natron in Prencences>Plugins> 
and add my e.g Linux-64-release directory path to the OpenFX Search Plugins path.

In the last version of Natron this feature doesn't work as expected.

Instead I had to work with symbolic links beetwen the .ofx.bundles and the /usr/OFX/Plugins path.

Im working in Linux with Natron 2.2.5.

**Comment by devernay** [comment]
fixed by https://github.com/MrKepzie/Natron/commit/b9cd33dd2336401a53fce3c137ee795fbb2b2f7f
