### ISSUE TITLE
Natron sometimes crashes when trying to edit bezier roto

### ISSUE THREAD

**Issue by Eneen** [MrKepzie/Natron#1586]
It sometimes happen, not always, and I was unable to generate report.
Natron crashes when trying to click on bezier control point adjustment node or point of "soft adjustment node".
Natron v.2.2.5, Windows 10.

**Comment by devernay** [comment]
Did the crash reporter send an automatic report? can you paste the crash ID in this issue next time this happens? Or maybe make a screencast so that we can reproduce the bug?

**Comment by Eneen** [comment]
Automatic report appeared only once but I wasn't sure what was that and canceled it. I won't miss it next time.

**Comment by Eneen** [comment]
I'm unable to generate crash report. When I test crash (in preferences) crash report window doesn't appear. Do I have to configure something else for this to work?

**Comment by devernay** [comment]
This issue was moved to NatronGitHub/Natron#196
