### ISSUE TITLE
Natron removes some frames in the viewer.

### ISSUE THREAD

**Issue by mifth** [MrKepzie/Natron#1587]
Hi. If I switch Transform node on/off - Natron will remove some frames from the viewer.
Could you check it, please?

Natron 2.2.5

Test https://www.youtube.com/watch?v=QaeFIdzdu_Q

[nat.zip](https://github.com/MrKepzie/Natron/files/833950/nat.zip)

**Comment by devernay** [comment]
This is probably a cache issue. Does hitting "refresh" in the viewer render the right frame? Does rendering the sequence work OK?
The cache will be totally different in the next Natron major version, so I doubt we will spend time fixing this one, unless it's an easy fix (I'll let @MrKepzie take a look at the video and project)

**Comment by mifth** [comment]
I tried to refresh. This did not help. I also tried clear all cache. It did not help too.
I guess this is because of retime or time wrap nodes... They use cache from other frames. Possibly this cache was not cleared.

**Comment by devernay** [comment]
This issue was moved to NatronGitHub/Natron#197
