### ISSUE TITLE
Suggestion: Write node should not have premult settings

### ISSUE THREAD

**Issue by rebuilder** [MrKepzie/Natron#1588]
### Problem

Premultiplication should be handled explicitly in the nodegraph before writing out to disk. Currently what is written can look different from what is seen in the comp if user neglects to check what premultiplication settings are used. For example, when writing out DPX, I do not generally check what the alpha channel contains before writing out, since I don't intend to write alpha out anyway. This has resulted in a good deal of rerendering, and also makes it necessary to do the repetitive chore of checking premult settings for every write node before rendering.

**Expected behavior:**
File written out should match what user sees in viewport.
**Actual behavior:** 
File written out may be premultiplied if user forgets to alter premultiplication settings from the default where premultiplication is not desired.

**Comment by devernay** [comment]
What the user sees does not contain alpha, unless you have a transparent screen.
If you click on the "checkerboard" icon in the viewer, you may have a better idea of what is seen in the viewer.
The problem is that the premultiplication is often wrong. By default, "Input Premult" is set to the premultiplication state of the input (see the "Info" tab of the writer node), but your graph probably doesn't set the premult correctly.
If that's the case, either:
- fix your graph
- insert a noop node that fixes the premult state before writing
- or manually set the "input premult" setting.

Please check your graph and report

**Comment by rebuilder** [comment]
This is certainly a user preference issue. Personally, I'm used to handling premultiplication explicitly with premult/unpremult nodes, and generally find a workflow where nodes try to guess what state I want my data to be in error-prone. 

As far as the write node is concerned, in most cases the user can tell if an image is premultiplied by alpha by simple visual inspection: Does the image look as expected? If there's a lot of black, whoops, you premultiplied when you didn't want to.

In general there are cases where I don't always pay attention to what the alpha is set to at certain points in a comp's flow. A bad habit perhaps, but sometimes it's more expedient. Also the way edgeblur for example works has led me to sometimes have my comp in a state where the alpha doesn't match the rgb data.

A workaround, if you wish to keep the premult settings in the writer node, would be for the viewer to display the data as it will appear after writing. So if premult is on in the writer, the RGB channels shown in the viewer when connected to the writer should be premultiplied.

**Comment by rebuilder** [comment]
I'd like to add that once the user has manually selected a setting for premult in a write node, that setting should not change any more automatically. Currently, if a node is added upstream of the write node, the premult setting will often change to the default, automagic value, leading to incorrect renders.

**Comment by devernay** [comment]
This issue was moved to NatronGitHub/Natron#198
