### ISSUE TITLE
"Crash reporter process does not seem to be responding anymore. This pipe IPC_COM might be used somewhere else."

### ISSUE THREAD

**Issue by GMaxera** [MrKepzie/Natron#1590]
### Problem

I'm running an instance of Natron 2.2.4 on background on an headless server machine.
All the frame are rendered correctly but for some reason before exiting NatronRendered process stuck indefinitely and it prompt the following message:

"Crash reporter process does not seem to be responding anymore. This pipe IPC_COM might be used somewhere else."

Is there a way to disable the crash reporter ?

**Expected behavior:**
Exit the process in someway. Not to hung forever

**Actual behavior:** 
It hung forever without any error message
 
### Versions

* **Natron 2.2.4** 
* **OS version: Debian 8 without UI**

**Comment by MrKepzie** [comment]
Run NatronRenderer-bin (next to NatronRenderer) directly.

**Comment by GMaxera** [comment]
Using NatronRenderer-bin solved the problem.
Thanks.

**Comment by devernay** [comment]
Are you running several NatronRenderer in parallel? note that this is unsupported in Natron 2 (will be in Natron 3)

**Comment by GMaxera** [comment]
Yes, I do... since Natron 2.0.0-RC1 ... and always worked perfectly.

**Comment by devernay** [comment]
This issue was moved to NatronGitHub/Natron#200
