### ISSUE TITLE
Write node: when changing from image format to video format, first dimension of "quality" is wrongly set to 100

### ISSUE THREAD

**Issue by devernay** [MrKepzie/Natron#1591]
the "quality" param in WriteOIIO and  WriteFFmpeg refer to different things and have different dimensions (1 vs 2).

Natron sets the first dim of the "quality" param in WriteFFmpeg to the "quality" param of WriteOIIO, which is wron.

Expected behavior:
Parameters should not be saved when changing the encoder plugin.

Will do the 2.2.6 release as soon as this is fixed

**Comment by MrKepzie** [comment]
a4f90a61a597fe3f660e8b8e203fe0777b09dc50
