### ISSUE TITLE
Color Dialog on linux (QColorDialog)

### ISSUE THREAD

**Issue by nicholascarroll** [MrKepzie/Natron#1592]
## Problem
In Linux the colour dialog is square and shows 8 bit RGB numerical controls. It is difficult to work with that because the viewer shows RGB values in floating.

Also, it would be nice if it were a colour wheel instead of a square.

![screenshot from 2017-04-01 12-16-10](https://cloud.githubusercontent.com/assets/1062708/24580824/061f8404-16d5-11e7-826c-adce45b25c88.png)

**Expected behavior:** 
show floating values  for R,G,B controls in the picker.

**Actual behavior:**
It shows 8 bit, and you have to figure out what value that is. In a *Roto* node, there is no colour picker dropper thingo so it is quite time consuming to get that colour.

### Versions
Natron 2.x
Ubuntu 16.04

**Comment by MrKepzie** [comment]
Well it's the native Qt dialog, we didn't get time to come up with a better one. A repository https://github.com/azerupi/NatronColorSelector  was started by @azerupi to provide proper color selectors for Natron but he never got time to make it. 
We are too much hands in the engine right now to get anything done on the gui. 
However If you want to contribute to the NatronColorSelector repo we would gladly then integrate it in Natron.

**Comment by nicholascarroll** [comment]
OK I will do that.

**Comment by nicholascarroll** [comment]
OK I  was able to put together a proposed design. It uses the triangle HSV wheel like in Gimp and Krita. Here is a screenshot. 
![colorpickerdesign](https://cloud.githubusercontent.com/assets/1062708/25775699/bd88c3b0-3270-11e7-87d2-2c0473ce90d8.png)

It is using this toolkit
https://github.com/mbasaglia/Qt-Color-Widgets
I suggest this design instead of the earlier one by @azerupi because the triangle shows a larger visual area where you see all variations of saturation and luminance as you turn the hue dial.

This is as far as I can take this because I don't know C++ or QT. But I suppose it is fairly simple to code it for someone who does know these.

**Comment by nicholascarroll** [comment]
The widget is GPL 3 but comes with a special exception to allow it to go in a GPL 2 codebase:
https://github.com/mbasaglia/Qt-Color-Widgets/blob/master/LICENSE-EXCEPTION

**Comment by sozap** [comment]
Hey,
It's nice to see this tackled !
Everything from the original is there except custom colors, but that's may not be needed...
Here is my design thoughts , I guess everything isn't necessary , it's already better than what we have.

- why two colors at the bottom of the wheel ? ( black and red ) if it's old value vs new one it's ok...
- is it possible to show colors inside the ramps ? R -> a red ramp...
- what about having value ranging from -1 to 1 instead of 0 / 1 , when that makes sense ?

It would be great to have longer ramps (to have more fine tune) but that would mess the clean organisation that we have here... Maybe a more vertical one, like in Nuke IIRC...

Anyways that's just suggestions , I don't see anything that must be done, only suggestions...

Thanks a lot !

**Comment by nicholascarroll** [comment]
why two colors at the bottom of the wheel ? ( black and red ) if it's old value vs new one it's ok...
> yes before and after
is it possible to show colors inside the ramps ? R -> a red ramp...
> yes they will show. the screenshot is only the layout in QT Designer
what about having value ranging from -1 to 1 instead of 0 / 1 , when that makes sense
> 

I chose horizontal sliders to fit the numerical field in nicely. fine tuning will be good however i am just wanting to start with the basics: float instead of 8 bit and a wheel instead of a square. 

@MrKepzie , @devernay are you OK about the license?

**Comment by sozap** [comment]
> what about having value ranging from -1 to 1 instead of 0 / 1 , when that makes sense : 

Sometimes you need to input negative color values, like in the grade node Black Point, White Point.
So maybe V,R,G,B needs to have a soft range between -1 and 1 . Or we can have a soft range of 0 -> 1 but we can input negative values or values higher than 1 in the numerical field.

I totally agree with you, it's better to have an improvement now rather than waiting for the perfect design, it's already better now ! 

Thanks !

**Comment by devernay** [comment]
The license is actually LGPL (not GPL), so it's OK, but it seems to be Qt5. We probably should use the native Natron sliders (with a colored ramp background) to get the scale: sometimes the color range is -1..1 (Grade), sometimes it's 0..1 (eg Constant).
It's also probably better to have an inline version, as in Nuke 8 and later (click pops an small inline color dialor, Ctrl or Cmd-click pops a more complete dialog window).
We probably could also incorporate the LCH values that have been recently incorporated into GIMP 2.9 https://discuss.pixls.us/t/gimp-2-9-now-has-an-lch-hue-chroma-tool-plus-lch-color-sliders/4335?u=patdavid

**Comment by nicholascarroll** [comment]
It's also probably better to have an inline version....
> my priority is to change those sliders from 8 bit to float. Pretty small task but it will be my first QT project and I have been very distracted trying to get the rent paid.

....as in Nuke 8
> Maybe but can you explain this design choice?  Writing thus about the design choice is perhaps boring but it proves that you have thought about it. I will pick this matter up in a forum topic now.

**Comment by nicholascarroll** [comment]
here http://forum.natron.fr/t/good-artists-copy-great-artists-steal/1623

**Comment by nicholascarroll** [comment]
Hi @devernay the Natron slider is that Gui/ScaleSliderQWidget.h ?

**Comment by nicholascarroll** [comment]
My design is wrong! The triangle colour picker is good for when you are choosing a colour that you would then paint with. But in Natron you are looking at your image while you adjust the colour. So I am going to revert to @azerupi's wheel.

**Comment by nicholascarroll** [comment]
Hey guys I have decided to not to try and code this or anything else that requires C++. The language is just took complicated. While I have not found this actual task too difficult, and Qt is pretty good, nevertheless its only a really small task for someone who has got years of Qt under their belt, like the Natron core team. Since I am not going ahead with C++ personally, there is not much point in me doing this widget and then supporting it. 

So I will remain just the requestor on this issue and I hope the design i propose is clear - a simple colour wheel with sliders for V,H,S and then R,G,B. The V slider should be right next to the colour wheel so that it is easy to access. It might be worth experimenting with tying the V to the mousewheel.

I think this is an important issue for everyone who uses Natron on Linux.

**Comment by nicholascarroll** [comment]
When it comes to being able to contribute code, j'ai mon cul entre deux chaises = I   C++ is not nice to the amateur.

**Comment by nicholascarroll** [comment]
I won't be building this - don't know C++. But I hope someone does soon.

**Comment by devernay** [comment]
This issue was moved to NatronGitHub/Natron#201
