### ISSUE TITLE
/opt/Natron2/bin/postinstall.sh: 51: /opt/Natron2/bin/postinstall.sh: Syntax error: end of file unexpected (expecting "fi")

### ISSUE THREAD

**Issue by zebus3d** [MrKepzie/Natron#1593]
sudo dpkg -i natron_2.2.6_amd64.deb
/opt/Natron2/bin/postinstall.sh: 51: /opt/Natron2/bin/postinstall.sh: Syntax error: end of file unexpected (expecting "fi")
/opt/Natron2/bin/postinstall.sh: 52: /opt/Natron2/bin/postinstall.sh: Syntax error: end of file unexpected (expecting "fi")

My solution:
This work for me: https://paste.ubuntu.com/24295683/
**I have added two fi.**

When run Natron get:
/usr/bin/Natron: línea 42: error sintáctico cerca del elemento inesperado `fi'
/usr/bin/Natron: línea 42: `    fi'
sudo vim /usr/bin/Natron **and deleted 2 fi**, now works well...

**Comment by MrKepzie** [comment]
Thanks this has been fixed
