### ISSUE TITLE
Issue with retime and it’s curve

### ISSUE THREAD

**Issue by Lucki** [MrKepzie/Natron#1597]
https://forum.natron.fr/t/issue-with-retime-and-its-curve/1267

### Problem

> Hi,
> I've tried to use the retime node with the curve editor, but can't get the expected result.
> 
> I have 3 key points in a row. The first and third key point is at 1 - the video should play in normal speed before and after these key points.
> The middle key point has any value > 1. All key points are on smooth interpolation, so I expect the video to slowly increase and decrease it's speed after/before the middle key point.
> http://i.imgur.com/hDrPU81.png
> 
> But the result is not the one I've expected. I get the same result as when I set the first and second key point to constant interpolation. From the first to the second key point the speed stays at 1 and at the second key the speed is instant at the maximal value and is constant high to the third key point, where the speed returns instant to 1 again. However, the value of the current speed in the retime properties seems to correctly interpolate.
> http://i.imgur.com/7dEjI3R.png
> 
> This looks a bit like [this](https://github.com/MrKepzie/Natron/issues/1350), but there's no crash and the issue is marked as fixed.
> I've tried this with Natron 2.1.9.
> I hope this works, here is a minimal example: http://www.xup.in/dl,54744935/retime-bug.ntp/ or [retime-bug.zip](https://github.com/MrKepzie/Natron/files/943314/retime-bug.zip)
> 
> Is this known or the expected behavior? Doesn't retime work with anything other than constant interpolation?

**Expected behavior:** I expect the video to slowly increase and decrease it's speed after/before the middle key point.

**Actual behavior:** From the first to the second key point the speed stays at 1 and at the second key the speed is instant at the maximal value and is constant high to the third key point, where the speed returns instant to 1 again.

### Steps to Reproduce

1. Automated:
1.1. Download and open this minimal example: http://www.xup.in/dl,54744935/retime-bug.ntp/ or [retime-bug.zip](https://github.com/MrKepzie/Natron/files/943314/retime-bug.zip)
1.2. Click play.
2. Manual:
2.1. Have 3 key points in a row. The first and third key point is at 1. The middle key point has any value > 1.
2.2. Click play.

### Versions

* **Natron version**: 2.1.9 - 2.2.7
* **OS version:** Arch Linux

**Comment by Lucki** [comment]
This even works with a negative value.

**Comment by devernay** [comment]
This should be fixed in the forthcoming snapshot. Please test and report.

**Comment by Lucki** [comment]
Fixed it, thanks.
