### ISSUE TITLE
Suggestion for resolving unknown symbols as string variables

### ISSUE THREAD

**Issue by ArashPartow** [MrKepzie/Natron#1600]
I've noticed you guys have made extensive changes to ExprTk's unknown_symbol_resolver component and parse_symtab_symbol method to accommodate what I believe is the resolution of unknown symbols into string variables.

I've gone ahead and added that ability to do so in the unknown_symbol_resolver via its interface. The solution involves the parser, when invoking the USR callback, to pass in the primary symbol table (first registered symbol table) - the user can decide based on their business logic how to treat the unknown_symbol, its type and default value added them to the primary symbol table, then return where the parse_symtab_symbol will be invoked again, where hopefully the then unknown symbol will be correctly resolved. 

**Note:** you don't have to add the symbols to the primary symbol table. As an example if you pass another symbol table to the USR which is also registered with the expression being parsed, it should work too, as the parse_symtab_symbol process will look at all registered symbol tables.

---------

Here is the section of the documentation that describes the new feature:

https://github.com/ArashPartow/exprtk/blob/master/readme.txt#L2887

----------

That being said, because the changes seem quite extensive and will subsequently require testing from your end, I'll leave it up to you guys to decide if you want to merge it in or not. 

Just wanted to let you know that the functionality was available.

**Comment by MrKepzie** [comment]
The changes I made were indeed to allow the USR to resolve string and also vector variables.
In Natron we have thousands of variables the user can potentially use (any parameter of any node) so we rely heavily on it.
I will integrate the changes and check they work.
Also, I couldn't find what was the proper way to create a new vector variable ? There only seem to be a add_vector method but no create_vector method.

**Comment by MrKepzie** [comment]
Implemented in https://github.com/MrKepzie/Natron/commit/018ee852f9151864acee4d30e2a769771160d435
This works, however it crashes if I try to return a vector that was resolved with the USR. 

I do the following in the USR:

                std::vector<double> vect(4);
                if ( isFailureRetCode(stat) ) {
                    vect[0] = vect[1] = vect[2] = vect[3] = 0.;
                } else {
                    const RectD& rod = results->getRoD();
                    vect[0] = rod.x1;
                    vect[1] = rod.y1;
                    vect[2] = rod.x2;
                    vect[3] = rod.y2;
                }

                bool ok = symbol_table.add_vector(unknown_symbol, vect);

It crashes then when calling value() on the expression object when trying to dereferencing the node data in populate_value_list():

    expr_as_vec1_store_[i] = branch_[i].first->value();

**Comment by ArashPartow** [comment]
> I guess this is because the vector is local and was not copied as it is done in create_variable

That's most likely the reason.

The create_variable/create_string routines were made available as helpers - a create for vector is problematic for a few different reasons.

That being said it is best to manage one's own memory and just pass references to the symbol_table.

Now that all the business logic for resolving the symbol is completely isolated in the callback you can decide exactly how to allocate memory for the types more consistently. Perhaps some kind of allocator object or some such.

**Comment by MrKepzie** [comment]
I store it alongside other per-thread data (such as functions) and it works fine now. Thank you for your help!

**Comment by ArashPartow** [comment]
Excellent keep up the good work!

**Comment by MrKepzie** [comment]
@ArashPartow Just notifying you, I'm not sure you get notified when it is closed

**Comment by ArashPartow** [comment]
There's no range checking at this time for either strings or vectors - essentially similar behavior to arrays and std::vector in C++

There is a change I've been working on that can add range checking to the vector and string nodes as a compile time option (ifdef), but it's not ready yet for production as it is a little buggy.

I'll ping you when it's done and you can merge it in.

**Comment by ArashPartow** [comment]
I've made a minor change that will perform a compile-time range check for certain vector expressions.

https://github.com/MrKepzie/Natron/pull/1601

**Comment by MrKepzie** [comment]
Alright thanks I'll take a look at it. 
It's very important that if the user types something in, the application does not crash as a result otherwise we will get bug reports
