### ISSUE TITLE
Node graph: node bounding box too large in some cases

### ISSUE THREAD

**Issue by rebuilder** [MrKepzie/Natron#1604]
### Problem
When a node's name/label overflows the node's box in the node graph, the bounding box used for determining what the user wishes to select when clicking seems to expand as well. This means that dragging noodles off e.g. read nodes is usually a bit of hassle, since clicking on the noodle near the node in question can actually result in selecting the node.

It's a small  thing, but adds up to a bit of extra frustration over time.

**Comment by psxx** [comment]
This so called small thing has not been fixed for over a year, lol (based on origin date of your post).
And maybe it depends on system but in my case (Windows 10 / 1709, Natron 2.3.8) it makes Natron absolutely unusable thingy.

Caution! GIF contains pure devastation:
![screencast-2018-03-22](https://user-images.githubusercontent.com/21136/37791679-e6030e30-2e1a-11e8-9e0b-66c7289fad01.gif)

**Comment by devernay** [comment]
Easy workaround: do it the other way, connect the downstream node to the read node.Sorry but I have no time to fix this.This is open source software, so you can also try to fix it yourself.Le 22 mars 2018 19:51, Pavel Skripkin <notifications@github.com> a écrit :This so called small thing has not been fixed for over a year, lol (based on origin date of your post).
And maybe it depends on system but in my case (Windows 10 / 1709, Natron 2.3.8) it makes Natron absolutely unusable thingy.
Caution! GIF contains pure devastation:

**Comment by devernay** [comment]
OK. fixed
