### ISSUE TITLE
Read nodes created via python don't seem to delete properly.

### ISSUE THREAD

**Issue by mangopipeline** [MrKepzie/Natron#1606]
### Problem
If i make a read node via python and then i manually deleted,
the node disappears from the gui but is very much still present in the graph.
getChildren will still list this node, which greatly complicates the ability of accurately managing read nodes via python.

**Expected behavior:** [What you expected to happen]
if we create nodes via python, when the artist deletes them.
getChildren should no longer see them.

**Actual behavior:** [What actually happened]
getChildren return nodes that have been deleted by the user.

### Steps to Reproduce
1)make project
2)run this code

```
import NatronGui as NE
nApp = NE.natron.getActiveInstance()

node = nApp.createNode( 'fr.inria.openfx.ReadOIIO')

readNodes =  [c for c in nApp.getChildren() if str(c.getPluginID()) == rT]
print 'number of reads in the scene',len(readNodes)
```
3)notice the print statement 'number of reads in the scene 1'
4)delete the newly created read node by hand and run the code again
5)notice the print statement ''number of reads in the scene 2'

if you continue to execute the code and delete the read node, you will notices the number of read nodes in the scene continues to grow.

I have verified that the read node returned by getChilren are instances of the previously deleted nodes.
creating the node by hand does delete it properly, so this seems to be a bug related to how nodes are created via python.

### Versions

* **Natron version/commit** (they can be retrieved from the About Window): 
Natron version 2.2.6 Release.

* **OS version:** 
windows 10

**Comment by mangopipeline** [comment]
Hey Guys...
have you had a chance to replicate this?
i see it  was marked as a bug...
I"m guessing it on the to do list?
Thanks!

**Comment by MrKepzie** [comment]
Not yet

**Comment by mangopipeline** [comment]
Thanks allot it works great now by the way!
it took me some time to get back into natron testing...
the change on the read node class name messed me up a little, but i appreciate you fixing it!!!
thanks a ton man :D
