### ISSUE TITLE
Long time to load

### ISSUE THREAD

**Issue by wireinet** [MrKepzie/Natron#1610]
helllo!  I  Love Natron! But very  long time to loading...about 10 minutes...abnormal.
long time loading in "fontconfig cache..." if i not mistake.
But this is a half of loading problem... when i see loading splash screen - i don't see anything else on my screen! Because focus always on top of the screen!

**Comment by MrKepzie** [comment]
This is an issue on windows of fontconfig, nothing we can do on our end. This bug has already been reported to fontconfig developers a long time ago but nothing has been done since I guess.

**Comment by wireinet** [comment]
Hmm, starange, don't you think? So until you get used with it...But you can not use fontconfig? The same blender also uses the fonts, but it loaded instantly..

**Comment by MrKepzie** [comment]
Blender does not uses fontconfig, they coded their own font management system, which has its drawbacks.

**Comment by wireinet** [comment]
I understand, thank you for the answers!
