### ISSUE TITLE
Animating multi-dimension parameters difficult/impossible when set to "single dimension for all parameters"

### ISSUE THREAD

**Issue by rebuilder** [MrKepzie/Natron#1611]
RGBA sliders default to 4 dimensions exposed. When wanting to animate all values in e.g. a multiply node, I set the node to collapse all values to one. This can be keyed in one keyframe, but when trying to set another key in another frame, the values re-expand to 4 dimensions and can not be collapsed again.

**Expected behavior:** [What you expected to happen]
When a node is set to collapse parameters, the values should stay collapsed.
**Actual behavior:** [What actually happened]
Values re-expand upon keying.
### Steps to Reproduce

1. Create a multiply [color] node and click the button labeled "4" to collapse parameters to a single value.
2. Set a keyframe for the value.
3. Switch to a different frame. The values will have re-expanded to 4 params. Collapsing the values can be done by clicking the relevant button ("4") twice, and the slider can be dragged to set a new value, but only once. Subsequent attempts to collapse values on the current frame  have no effect.

### Versions

* **Natron version/commit**Natron 2.2.7, version 61853f8
* **OS version:**  Linux Mint 17

**Comment by devernay** [comment]
This issue was moved to NatronGitHub/Natron#204
