### ISSUE TITLE
Rotopaint issue: stroke attributes are lost when changing visibility

### ISSUE THREAD

**Issue by Pere2** [MrKepzie/Natron#1612]
### Problem
Rotopaint node:
Switching layer visibility off, makes stroke attributes to be superseded, in practice destroying rotopaint work.

Also applies to cloning, in this case even clone shifts are superseded .

### Steps to Reproduce

1. paint, clone, etc.
2. switch layer visibility off. Notice stroke attributes are replaced.
3. switch layer visibility on. Rotopaint result has changed.

### Versions
Windows release 2.2.7

Painting----hiding----unhiding:
![rotopaint1](https://cloud.githubusercontent.com/assets/28137305/25521003/5c0d830a-2bfe-11e7-8682-d1e3e64d0ef3.jpg)

Cloning----hiding----unhiding:
![rotopaint2](https://cloud.githubusercontent.com/assets/28137305/25521021/66145be4-2bfe-11e7-8eef-6a14068aa405.jpg)

**Comment by devernay** [comment]
This issue was moved to NatronGitHub/Natron#205
