### ISSUE TITLE
Transform-Node ERROR when "amount"-key implies "scale x = 0" at any frame

### ISSUE THREAD

**Issue by Quecksilberstreif** [MrKepzie/Natron#1617]
### How I stumbled upon the problem:

**Expected behavior:** I expected my project to render.

**Actual behavior:** The very same project always crashed exactly at 61% when rendering. Nothing I did seemed to fix it. But a lot of thinking and trying finally managed me to find the source of the problem:

### Steps to Reproduce

1. Create a node graph with a checkerboard followed by transform followed by a writer
2. Set frame range in project settings to 1-1
3. Set scale to -1 and amount to 0.5 in the transform node
4. render

~~1. Create any simple node graph.
2. Have the node graph include a [transform]-node.
3. Have the [transform]-node set a transformation of Scale ~~x~~ = -1
4. Set first key-event of [transform]-node to be "amount = 0", the second to be "amount = 1"
5. Connect node to viewer or writer.
6. Rendering will lead to a full crash at frame when "amount = 0.5" and "Scale x = 0".
Trying to view the graph in the viewer will lead to this particular frame not appearing in the preview.~~

### Notes
* I tried to provoke a similiar "Scale x = 0" -conflict by repeating the same problem with setting the keys directly on the "Scale x"-property instead of the "amount"-property. This seems to solve the problem.
* If I remember correctly the ERROR can also be avoided by just setting the first key to the first frame. Though if it is at any frame after that the problem relyable seems to persist.
* My bet on how to fix the bug: Probably someone forgot to check for a divide-by-zero or null-parameter error when changing the scale indirectly using "amount" instead of "scale x" directly in combination with animation starting at a frame later than the first.
* If this is correct it could be an indicator for smelly code structure.

### Versions

* **Natron version/commit**: Natron Version 2.2.5
* **OS version:** Windows 10

![bug report](https://cloud.githubusercontent.com/assets/28061646/26406846/d0a834ee-4099-11e7-89ea-f82f11868d5f.png)

**Comment by devernay** [comment]
should be fixed by https://github.com/devernay/openfx-supportext/commit/fec723380b2f80b4d2fd5739a4f64363e44d7180 and https://github.com/MrKepzie/openfx-io/commit/c398bc781712ac599287af5d17ada159d01011f7

**Comment by devernay** [comment]
fixed in 2.2.8
