### ISSUE TITLE
[proposal] rotation inside bloom node

### ISSUE THREAD

**Issue by Eneen** [MrKepzie/Natron#1618]
Currently glare effect (sunstars) can be done using bloom node with size option e.g. 0.5x0.0 but requires rotation of whole image (using transform node) by different angles for each "ray" and then second rotation to get normal image. current workflow:

source

transform transform transform
     |               |              |
bloom       bloom      bloom
     |               |              |
transform transform transform

merge

When image is rotated by non 90deg and rotated back quality is degraded on sharp edges no matter what filter is used. My proposal is to add rotation option inside bloom node working only on processed pixels, not on original image. On "Bloomed" pixels quality degradation will not be visible and original image will be intact. Additionally it would require less nodes so should be faster. Proposed workflow:

source
bloom bloom bloom
merge

**Comment by devernay** [comment]
all pixels are processed. To make a "directional bloom" you have no other way than rotate + bloom + rotate.
This is exactly what is don inside the "angleblur" pyplug, except angleblur uses Blur, not Bloom.

If you want to get the bloom effect only on bright areas, you could extract a matte of the bright areas (eg using Keyer), then apply your sunstars effect on the masked image, and then merge it over the original.

Closing this issue
