### ISSUE TITLE
Issue installing on Ubuntu 17.04

### ISSUE THREAD

**Issue by DeathCamel57** [MrKepzie/Natron#1619]
### Problem

Describe the problem or suggestion here.

**Expected behavior:** Natron installs
**Actual behavior:** `/opt/Natron2/bin/postinstall.sh: 4: /opt/Natron2/bin/postinstall.sh: Syntax error: ";;" unexpected`
 
* Verbose output does not work, results in an unexpected end of file
![Screenshot](https://cloud.githubusercontent.com/assets/1226646/26750267/11c76cde-47ec-11e7-9ad7-95d3dd60b45c.png)

### Steps to Reproduce

1. Download the latest Deb release of Natron from the official site ([link](https://downloads.natron.fr/Linux/releases/64bit/files/natron_2.2.8_amd64.deb))
2. Run `sudo dpkg -i natron_2.2.8_amd64.deb`

![Screenshot](https://cloud.githubusercontent.com/assets/1226646/26750263/fb3df9ce-47eb-11e7-8ad8-fc65811d319a.png)

### Versions

* **2.2.8** (they can be retrieved from the About Window): 
* **Ubuntu 17.04 zesty** 
* **`Linux DeathCamel57 4.10.0-21-generic #23-Ubuntu SMP Fri Apr 28 16:14:22 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`**

**Comment by MrKepzie** [comment]
Will be fixed soon in a re-packaging

**Comment by MrKepzie** [comment]
It's been re-packaged, can you re-try ?

**Comment by MrKepzie** [comment]
Fixed

**Comment by DeathCamel57** [comment]
Thank you, the new package works properly!
