### ISSUE TITLE
Rotopaint issue: color picking

### ISSUE THREAD

**Issue by Pere2** [MrKepzie/Natron#1622]
Rotopaint node:

Pick stroke color from viewer does not work for solid paint brush. It starts working however as soon as you creates a pencil stroke.

Pick stroke color from viewer does work for pencil. It stops working however as soon as you creates a brush stroke.

Natron release 2.2.8
Windows 10

**Comment by devernay** [comment]
This issue was moved to NatronGitHub/Natron#206
