### ISSUE TITLE
'hide all parameters without modifications' hides too much

### ISSUE THREAD

**Issue by freder** [MrKepzie/Natron#1625]
### Problem

![natron-hide](https://user-images.githubusercontent.com/724844/27177177-b7fdb2f6-51c5-11e7-9014-5b2c78654c0d.gif)

hiding parameters without modifications is a handy feature, but in this case it also hides the *render* button, which makes the node unusable.
(this might be true for other buttons and other nodes, but I haven't checked.)

**Expected behavior:** *render* button remains visible

**Actual behavior:** *render* button disappears

---

natron `2.2.8`
macOS

**Comment by devernay** [comment]
fixed by https://github.com/NatronGitHub/Natron/commit/061d0e9906310f15ad89b5a91f93576a6d6bc30c
