### ISSUE TITLE
Little error in /usr/bin/Natron

### ISSUE THREAD

**Issue by ponceto** [MrKepzie/Natron#1631]
When launching Natron from the command-line, there is a little error : 

`/usr/bin/Natron: ligne 137 : [: = : opérateur unaire attendu`

### Problem

Describe the problem or suggestion here.

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

 * If your problem is a crash in an official release/snapshot, please include verbose output from the application
 from a terminal if possible.  If you also submitted a crash report, indicate the CrashID if possible.
 
 * If you need to report a compilation issue, please create a [gist](https://gist.github.com)
 that contains the _full_ verbose build log.
 
 * If your problem is a crash in a build that you made yourself, please create a [gist](https://gist.github.com)
 that contains a _full_ backtrace.

### fix

enclose $help with double qutotes, like this:

```
if [ "$help" = 1 ]; then
    echo "Usage: $1 [-u|--update] [-p|--portable] [-n|--nocrashdump] [-d|--debug] <options>"
    echo "Full usage:"
fi        
```

### Versions

* **Natron 2.x - Linux**
* **Linux Mint 18.x**

**Comment by devernay** [comment]
fixed, will be in 2.3.0 (out tomorrow), thanks
