### ISSUE TITLE
natron2.2.9 ：The write node color space is incorrect

### ISSUE THREAD

**Issue by AlphaFase** [MrKepzie/Natron#1639]
### Problem

The write node color space is set to linar, rendering the color space incorrect

### Versions

Natron 2.2.9 for win64

    Natron version/commit (they can be retrieved from the About Window):
    OS version:

--------------------------------------------------------------
The above is automatic translation using translator

**Comment by devernay** [comment]
Thanks for the report. Can you please be more specific? What is the file name in your write node? Did you use a custom OCIO configuration (in Preferences/Color Management, by setting the OCIO environment variable, or by setting the OCIO variable in the project settings)? Or did you use one of the standard OCIO configs (which one?)
Is this issue still present in 2.3.0?

**Comment by githob605608886** [comment]
Ocio default settings
 write node file name as jpg
Natron 2.3.0 view can not be show normally, so I do not know

os : win64


English is not good, the above content using Google translation

**Comment by githob605608886** [comment]
Ofx support is not very perfect, nuke denoise node display is not normal, mocha ofx can not be used, need nuke open once to initialize, sapphire plugin often crash

**Comment by devernay** [comment]
should be fixed. OFX support in Natron is very good, the problems usually come from the plugins.
