### ISSUE TITLE
Natron 2.3 doesn't like cin and jpg

### ISSUE THREAD

**Issue by groslaine** [MrKepzie/Natron#1642]
### Problem

In Natron 2.3 the read (or the viewer) doen't diplay .cin files and jpg sequence. The same files are easely read in Natron 2.2.8

### Steps to Reproduce

1. Add a read node and select a .cin or jpg sequence
2. Add a viewer

### Versions

* **Natron 2.3
* **OS version:** Windows 10

**Comment by MrKepzie** [comment]
This is a known bug that was already reported on Windows in version 2.3, please downgrade to 2.2.9 or wait for 2.3.1
