### ISSUE TITLE
EXR files 'read' into Natron are Black and will not write out

### ISSUE THREAD

**Issue by troywilliams1** [MrKepzie/Natron#1643]
### Problem

Describe the problem or suggestion here.

**Expected behavior:** When reading in an EXR file that has data, the file should read in correctly and show all proper information. 

**Actual behavior:** Currently reading in an EXR file will show up black in the viewer and will not write out, sampling data in the viewer shows 0,0,0,0, when first connecting up a write node to the viewer an error is printed out "Write1 error: Host did not requested any layer to render".

### Steps to Reproduce

1. Open Natron
2. Create read node
3. Seek out an EXR file that has data
4. Notice that when connected to the viewer the result is black
5. Ctrl+LMB the viewer, notice that the sampled data is 0,0,0,0
6. Create a write node
7. Connect up the output of the read node and connect the write node to the viewer
8. Notice error "Write1 error: Host did not requested any layer to render"

You may submit a link to any screenshots/videos that can be used to understand how to reproduce the issue.

### Versions

* **Natron version/commit** (they can be retrieved from the About Window): 

This software was compiled from the source code branch tags/2.2.2 at version 51b0294 using GNU C++ version 5.2.0 with OpenMP 4.0 targetting Intel x86-64 for Unix Environment.
The bundled openfx-io plugins were compiled from version 5f69331.
The bundled openfx-misc plugins were compiled from version f51c977.
The bundled openfx-arena plugins were compiled from version a731e9c.

* **OS version:** 

Windows 8.1 Enterprise 64 Bit
Intel i7-3820
32 GB ram
Nvidia Geforce GTX 760

![image](https://user-images.githubusercontent.com/18218357/28581998-84ff190c-7129-11e7-9454-0da7dc88f13a.png)

![image](https://user-images.githubusercontent.com/18218357/28582058-bd16fe4a-7129-11e7-9974-aca12a812e02.png)

**Comment by MrKepzie** [comment]
It's a known issue in Natron 2.3.0 on Windows only. It is fixed and will be available in Natron 2.3.1. I suggest you switch to Natron 2.2.9 in the meantime. See https://github.com/MrKepzie/Natron/issues/1642
