### ISSUE TITLE
Alpha change in  2.3.1	

### ISSUE THREAD

**Issue by Pere2** [MrKepzie/Natron#1648]
### Problem

Some behavior of alphas in 2.3.1 has changed from version 2.2.9.
I dont know wich one is the right way, but the previous behavior was quite useful.

### Steps to Reproduce
In 2.3.1. merge 3 images  with a single node:

![untitled140](https://user-images.githubusercontent.com/28137305/28712575-effa7210-738b-11e7-9e82-ec4cd538a87d.jpg)

Apply a roto to the upper image (alpha displayed)

![untitled141](https://user-images.githubusercontent.com/28137305/28712822-e0645b6c-738c-11e7-965b-8cd54d277f69.jpg)

When you do the same in 2.2.9. you get this alpha:

![untitled142](https://user-images.githubusercontent.com/28137305/28712989-977741b6-738d-11e7-9434-0c512f9ed482.jpg)

Here is an example of a 2.2.9 project:

![untitled144](https://user-images.githubusercontent.com/28137305/28713102-08babf6a-738e-11e7-92ff-5b03481f9f1f.jpg)

when loaded in 2.3.1:
![untitled143](https://user-images.githubusercontent.com/28137305/28713127-21b22116-738e-11e7-8bdf-5d38278cb7a4.jpg)

**Comment by MrKepzie** [comment]
This looks like a bug, we made some changes to the Merge node code, I'll look into it

**Comment by devernay** [comment]
please test with the latest snapshot

**Comment by devernay** [comment]
this should be fixed in 2.3.2 (that bug fix justified the minor release)
