### ISSUE TITLE
Add Ubuntu PPA and Debian repo

### ISSUE THREAD

**Issue by Sunderland93** [MrKepzie/Natron#1651]
Hello. I made PPA repository for Ubuntu, with Natron and all needed dependency's. PPA currently provides packages for Ubuntu 17.04 and 17.10

https://launchpad.net/~samoilov-lex/+archive/ubuntu/natron

**Comment by mikhailnov** [comment]
Please update the PPa to Natron 2.3.1...
Good job, thank you.

**Comment by mikhailnov** [comment]
The deb package at Natron website seems to have a ststic ffmpeg, if yours uses the system ffmpeg, that is interesting

**Comment by Sunderland93** [comment]
I will update packages to 2.3.1 soon. Yes, packages in PPA uses system library's, including FFmpeg

**Comment by Sunderland93** [comment]
Packages updated. I also create Debian 9 repo for Natron https://software.opensuse.org//download.html?project=home%3ASunderland93%3Anatron&package=natron

Currently I work on add Ubuntu 16.04 support in PPA

**Comment by devernay** [comment]
@Sunderland93 Nice work! Thanks for these. We need more people like you to help spread the use of Natron!
Note that these binaries won't be able to report crashes to our server.
Did several users validate these repos and do they work fine?
Did you compile openfx-misc with OpenMP support?
Can we add links to these repos on the linux download page? (are ther
Can we also point to you as the official maintainer of these repos?
Can you give us contact information (which can be displayed along these links), and can we add you to the list of Natron contributors (in the About window) and how would you want to appear in this list (name only, or name and contact) ?

**Comment by mikhailnov** [comment]
Can you please symlink /usr/bin/natron to the main executable , so that it was easy to run Natron via CLI?
https://stackoverflow.com/questions/9965717/debian-rules-file-make-a-symlink

**Comment by mikhailnov** [comment]
It seems that your build of Natron checks for updates on launch, but in case of updates it will send the user to the Natron's website, not your repository, I think. Maybe you can patch the link and send the user to the ppa page at launchpad or disable autoupdates checkings by default? The second variant sound more UNIX-way

**Comment by Sunderland93** [comment]
@devernay 

> Did several users validate these repos and do they work fine?

I don't know, but in all may setups it works fine.

> Did you compile openfx-misc with OpenMP support?

No, but openfx-io compiled with it.

> Can we add links to these repos on the linux download page? (are ther
Can we also point to you as the official maintainer of these repos?

Yes, of course :)

> Can you give us contact information

My name is Aleksey Samoilov, samoilov.lex@gmail.com

>  and can we add you to the list of Natron contributors (in the About window) and how would you want to appear in this list (name only, or name and contact) ?

Well, if you're add me as a maintainer of repo's, it will be better to indicate the full contact details

**Comment by Sunderland93** [comment]
@mikhailnov 

> Can you please symlink /usr/bin/natron to the main executable , so that it was easy to run Natron via CLI?

Done

> It seems that your build of Natron checks for updates on launch, but in case of updates it will send the user to the Natron's website, not your repository, I think. Maybe you can patch the link and send the user to the ppa page at launchpad or disable autoupdates checkings by default? The second variant sound more UNIX-way

Ok, but I don't know where in the code of Natron  is an update check

**Comment by mikhailnov** [comment]
`$ grep -EinHr 'natron.fr/download' 
Documentation/source/guide/getstarted-installation-linux.rst:40:Navigate to http://natron.fr/download and download the latest version. This documentation will assume that you downloaded the installer (our default and recommended choice).
Documentation/source/guide/getstarted-installation-linux.rst:118:Natron also has RPM and DEB packages, these are recommended for multi-user installations or for deployment on more than one machine. You can find more information on our website at http://natron.fr/download .                                                                                                                                                                                                                                                                             
Documentation/source/guide/getstarted-installation-mac.rst:29:Navigate to http://natron.fr/download and download the latest version.
Documentation/source/guide/getstarted-installation-windows.rst:34:Navigate to http://natron.fr/download and download the latest version. This documentation will assume that you downloaded the installer (our default and recommended choice).
Engine/AppInstance.cpp:510:               .arg( QString::fromUtf8("<a href=\"https://natron.fr/download\">"
`

**Comment by Sunderland93** [comment]
@mikhailnov Ok, but I don't understand how to disable check's for updates. I tried to delete all code referenced to autoupdate, but build failed.

**Comment by Sunderland93** [comment]
Packages updated. Added support for Ubuntu 16.04 and Linux Mint 18.x

**Comment by dev31** [comment]
Please update the PPa to Natron 2.3.4...
Good job, thank you.

**Comment by devernay** [comment]
This issue was moved to NatronGitHub/Natron#215
