### ISSUE TITLE
Transform Node Preview Widget causes frequent crashes

### ISSUE THREAD

**Issue by unfa** [MrKepzie/Natron#1652]
### Problem
I experience severe crashes when changing position or scale with the Transform Node using it's widget in the Preview Pane.

Using number fields so far didn't cause a single crash.

### Versions

Natron 2.3.1

OS: Linux Mint 18.2
Kernel: 4.10.0.30-lowlatency
Hardware: Ryzen 7 1700, Nvidia GTX 1060.

Here's my project file along with source images (3 PNG images):
[natron project.zip](https://github.com/MrKepzie/Natron/files/1209362/natron.project.zip)

**Comment by devernay** [comment]
the crash reports gives nothing (crashes deep inside libc). Does unchecking "interactive update" change anything?

**Comment by devernay** [comment]
Crash reports (internal use):
https://natron.fr/crash-reports/?r=60061da7-10ec-abd4-1545f504-6ccaaef8 
https://natron.fr/crash-reports/?r=3b923224-91e7-6d73-5786dbae-2684d8b6
https://natron.fr/crash-reports/?r=0d4f24e7-b746-17f0-7a0c4800-64e5e70c

**Comment by devernay** [comment]
This issue was moved to NatronGitHub/Natron#213
