### ISSUE TITLE
Joinviews does not work on secondary channels

### ISSUE THREAD

**Issue by nrehberg** [MrKepzie/Natron#1653]
While joinviews correctly copies the left rgba input into the left view and the right into the right view, on secondary channels only the right input is present on both views. I guess something like the allPlanes option from other nodes is missing.

Example attached. Check ChannelA after the joinviews.

[natronJoinViewsError.ntp.zip](https://github.com/MrKepzie/Natron/files/1212011/natronJoinViewsError.ntp.zip)

Natron version 2.3.1 Release.

**Comment by MrKepzie** [comment]
It's a known problem that is already fixed for Natron 3, but which would require major edits to integrate into Natron 2

**Comment by devernay** [comment]
closing
