### ISSUE TITLE
Error during installation proccess (OpenFX Extra Plugins)

### ISSUE THREAD

**Issue by gustblima** [MrKepzie/Natron#1654]
### Problem
I'm trying to install natron, but i'm getting this error:
![image](https://user-images.githubusercontent.com/1727703/29130757-31df43bc-7d01-11e7-9ac2-c1d87a5cfa79.png)

### Steps to Reproduce

1. Just try to install with extra fx plugins
![image](https://user-images.githubusercontent.com/1727703/29130855-706c820c-7d01-11e7-86ce-0ac7721fed40.png)

### Versions

* **Natron version/commit**: 2.3.1
* **OS version:** Windows 10

**Comment by devernay** [comment]
is anybody else getting this problem?

**Comment by TiptopdoVR** [comment]
Yeah, get the same error, then i  updated to the newest 7 zip version. everything is ok now.

**Comment by devernay** [comment]
Natron installer should provide its own 7zip

**Comment by devernay** [comment]
This issue was moved to NatronGitHub/Natron#214
