### ISSUE TITLE
[proposal] Reduce default UI font size to 8px

### ISSUE THREAD

**Issue by Eneen** [MrKepzie/Natron#1655]
Currently 11px font is pretty large even for my 2560x1440 screen. I think it's useful for 4k. Here i screenshot how Natron looks after reducing font size. Font used: Tahoma, but looks great using Noto on Ubuntu too. With smaller font there is plenty of usable free space and interface looks more sleek.
![8px_font_ui](https://user-images.githubusercontent.com/25537418/29218045-d38e3aa2-7eb3-11e7-9016-3e7248c194ca.jpeg)

**Comment by devernay** [comment]
11pt is very reasonable, and users with very good eyes or not enough screen space can always change the font size in the Natron preferences. I don't see the point in having such a small font size by default. The default should be readable for all users.
