### ISSUE TITLE
Natron's breakpad crash reporter blocks Safari and Mail on macOS

### ISSUE THREAD

**Issue by deein** [MrKepzie/Natron#1662]
Hi dear MrKepzie,

I have an issue with Natron, when I launch it my safari can't open any pages. But when I close Natron, thats works.

I don't know if its a know issue.

Tell me if I can help you with some log files or something else. :)

[EDIT] It also blocks Mail.app from displaying message contents

**Comment by devernay** [comment]
I first thought this was a joke, but no... Natron blocks loading an URL in Safari (10.1.2 on macOS Sierra here) by clicking on a bookmark or entering an URL, and as soon as one quits Natron, The URL loads!
Tested with Natron 2.0.5-2.3.2 on macOS Sierra.
Frankly, this looks like an OS or Safari bug, unless someone gives me a clue

**Comment by devernay** [comment]
The bug is related to breakpad - the crash reporting system. This is a serious issue.

To disable completely the crash reporter, type the following in a terminal:
```
cd /Applications/Natron.app/Contents/MacOS
mv Natron-driver Natron-driver.orig
ln -s Natron-bin Natron-driver
```
Safari works fine after that.

**Comment by devernay** [comment]
Should be fixed by switching to crashpad, see https://github.com/MrKepzie/Natron/issues/1223 https://github.com/NatronGitHub/Natron/issues/145

**Comment by devernay** [comment]
This issue was moved to NatronGitHub/Natron#219
