### ISSUE TITLE
Natron does not warn when saving or rendering to full disk

### ISSUE THREAD

**Issue by rebuilder** [MrKepzie/Natron#1664]
### Problem

When saving a project file, Natron does not warn if the disk being written to is full. Likewise, if rendering, Natron does not warn when the disk is full. This is especially bad for saving projects, since the result will be a corrupt project file.

**Expected behavior:** 
Natron should warn if there is insufficient space to write to disk.
**Actual behavior:** [What actually happened]
No warning is given.

### Versions

* **Natron version/commit** 
2.3.2 c9b0375
* **OS version:** 
Linux Mint 17

**Comment by unfa** [comment]
So currently Natron will quietly fail to save a working project file?

**Comment by devernay** [comment]
see also https://github.com/NatronGitHub/Natron/issues/192

**Comment by devernay** [comment]
This issue was moved to NatronGitHub/Natron#220
