### ISSUE TITLE
Question,  what prefers Natron (CPU)?

### ISSUE THREAD

**Issue by nyancat18** [MrKepzie/Natron#1665]
A a cpu  with  many cores, even if they are "weak"  (FX 8350/Ryzen 5 1600x/Ryzen 7 1800X/ Ryzen TR 1950X)

B a CPU with  fewer but stronger cores (Ryzen 5 1500X/I5 7600K/I7 7700K/Intel I9)?

**Comment by MrKepzie** [comment]
After testing, it works currently better with option B.

**Comment by nyancat18** [comment]
thanks :)
