### ISSUE TITLE
[proposal] Add Film-like curve adjustment to keep constant hue

### ISSUE THREAD

**Issue by Eneen** [MrKepzie/Natron#1666]
During regular curves adjustment hues are shifted especially blues and yellows. This problem can be solved using Film-like curve originally created by Adobe:

> (So how does actually Adobe’s tone curve work? It’s an RGB curve where the tone curve is applied on the largest and smallest value, and then the middle value is adapted to keep a constant hue as defined by RGB-HSL/HSV. In terms of look and saturation increase it’s very similar to a pure RGB curve, more so than a HSL-L curve or HSV-V curve, but some color shift problems are avoided.) 
from: https://www.ludd.ltu.se/~torger/dcamprof.html#tone_curves

This feature is implemented in RawTherapee.
http://rawpedia.rawtherapee.com/Exposure#Film-Like

Additional reading:
http://scribble-jpc.blogspot.com/2012/09/in-search-of-perfect-color-new-tone.html

Source (AdobeToneCurve)
https://github.com/Beep6581/RawTherapee/blob/dev/rtengine/curves.h
https://github.com/Beep6581/RawTherapee/blob/dev/rtengine/curves.cc

**Comment by devernay** [comment]
Hi,
I'm not a color specialist, but from what I understand a Film-Like curve would be a single curve (not separate r,g,b curves)

relevant code seems to be here:
https://github.com/Beep6581/RawTherapee/blob/3ff2519302e3bc529b111462a4697ac4dfba30c4/rtengine/curves.h#L919
and here:
https://github.com/Beep6581/RawTherapee/blob/3ff2519302e3bc529b111462a4697ac4dfba30c4/rtengine/curves.h#L974

The UI could be a "Film-Like" checkbox in the ColorLookup plugin that would execute the above code when applying the master curve. Is that what you would expect too ?

**Comment by Eneen** [comment]
Yep, under RawTherapee you just choose what type of curve you want. Screen attached.
As sidenote (maybe it matters here too): to speed up color correction I always use clamp before using ColorLookup node on final stage.
![filmlike_curve_rawtherapee_choosebox](https://user-images.githubusercontent.com/25537418/31219929-1d58e3c2-a9bf-11e7-886b-46c2c0810283.jpeg)

**Comment by devernay** [comment]
does it make sense to add other Rawtherapee curve modes (weighted standard, luminance, etc...) or are these useless?
would an RGB histogram be also useful?

**Comment by Eneen** [comment]
Personally I use only filmic, but I'm purist. For sure adding all (if easy) would be great. E.g. I saw people using weighted standard for shadows and filmic for highlights.

**Comment by Eneen** [comment]
RGB histogram: very useful.

**Comment by devernay** [comment]
will be in next snapshots/releases

**Comment by Eneen** [comment]
Thank you so much!

**Comment by devernay** [comment]
did you test it in the last snapshot? does it work as expected?

**Comment by Eneen** [comment]
Filmic for sure. I wil test other, but need to prepare file to compare with raw therapee.

**Comment by Eneen** [comment]
As far I was able to mimic curves from RT all available modes give same result visually. Only difference I've spotted is that Natron lacks two modes: Saturation and Value Blending and Perceptual.
