### ISSUE TITLE
Natron 2.3.2 crashes with antialias and defocus from natron-plugins

### ISSUE THREAD

**Issue by Eneen** [MrKepzie/Natron#1667]
Natron version: 2.3.2
Platform: Windows

It was working fine before version 2.3.2, but now it doesn't. It or crashes or stalls Natron or gives such message:
> [00:45:44.634] FXAA_Alpha: Can not render: OpenGL 2.0 or GL_ARB_texture_non_power_of_two is required.

I get same thing with defocus:
> [00:47:44.801] Defocus: Can not render: OpenGL 2.0 or GL_ARB_texture_non_power_of_two is required.

Sidenote: it crashes when I zoom in my project to get 1:1 preview

**Comment by MrKepzie** [comment]
Means OpenGL driver on your graphic cards is not high enough. You can enable software OpenGL rendering by checking the optional dependency during the installation of Natron, or move the opengl32.dll file located in Natron/bin/mesa to Natron/bin

**Comment by Eneen** [comment]
But I've got GTX 1050Ti with current (2017.08) drivers. How come it doesn't support current opengl?

**Comment by Eneen** [comment]
Ok, current drivers give same result:
`FXAA_Alpha: Can not render: OpenGL 2.0 or GL_ARB_texture_non_power_of_two is required.`

But screenshot tells I've got such extension:
![gl_arb_texture_non_power_of_two_bug](https://user-images.githubusercontent.com/25537418/31014184-ea9b2570-a519-11e7-9371-f34008d231ce.jpg)

**Comment by devernay** [comment]
Can you please post a zipped Natron project that shows the problem?

**Comment by Eneen** [comment]
Sure. I've sent you project via wetransfer. Antialias node is used on upper-left segment with ID mask file after keyer and invert. Currently it's disabled - I use blur instead. Please just disable blur and enable antialias to reproduce issue.

**Comment by devernay** [comment]
Sorry, I couldn't grab the file on time. Can you test with Natron 2.3.3?

**Comment by devernay** [comment]
Can you please test with the latest version (2.3.10) ?

**Comment by devernay** [comment]
This issue was moved to NatronGitHub/Natron#221
