### ISSUE TITLE
ZDepth

### ISSUE THREAD

**Issue by AHubl** [MrKepzie/Natron#1668]
Hello I found the Plugin Defocus when i was on my way to solve my issue with the DoF in Natron, sadly its only for controlling the "Bokeh-Effect" in the image and not the distance blur... will their be a solution for Depth of Field in an offical release thats easy to handle like in Nuke? i think its an important basic :)

https://www.youtube.com/watch?v=vWRo_x3okdQ

**Comment by devernay** [comment]
Please try the Shadertoy plugin in the 2.3.3 snapshots. Blur presets now have a "Modulate" input to adjust the blur size. You just have to compute the right blur size (eg using an SeExpr node to compute the blur size from depth).
It is not totally accurate, but should work rather nicely.
A real ZBlur plugin requires some work, see https://github.com/MrKepzie/Natron/wiki/Google-Summer-of-Code-GSoC-ideas#zdefocus

**Comment by devernay** [comment]
This issue was moved to NatronGitHub/Natron#222
