### ISSUE TITLE
Too many inputs created when creating a Group from a node with optional inputs (Merge, RotoPaint)

### ISSUE THREAD

**Issue by AlphaFase** [MrKepzie/Natron#1669]
### Problem

There is a problem with the grouping

**Expected behavior:** I create a rotopaint node by pressing P in the node editor, and there should be only one input node

**Actual behavior:** There are numerous rotopaint nodes within the group

### Steps to Reproduce

1. press "P" key
2. Select the rotopaint node, then press ctrl + G
3. Enter the group

You may submit a link to any screenshots/videos that can be used to understand how to reproduce the issue.

### Versions

* **Natron version** :  Natron version 2.3.2 Release.
* **OS version:**  win10 x64

**Comment by devernay** [comment]
This is because RotoPaint has many optional inputs. It also happens with Merge.
I think that Natron should create input nodes for optional inputs *only* if they are connected.

**Comment by devernay** [comment]
This issue was moved to NatronGitHub/Natron#223
