### ISSUE TITLE
New build error

### ISSUE THREAD

**Issue by nyancat18** [MrKepzie/Natron#1676]
distro: manjari 64

Libs
fontconfig: 2.12.6
qt: 4.8.7.22
python2-pyside: 2.4.6
shiboken: 2.4.3
boost: 1.65.1
cairo: 1.15.8
openimage-io 1.7.17 
opencv 3.3.0
pixman: 0.34
expat: 2.2.4

natron version: 2.3.2

buildlog
https://p.teknik.io/Raw/HA1P6

**Comment by MrKepzie** [comment]
Please go on the forums to get help for build issues, this issues tracker is for bugs related to the software itself. Build instructions are online, if nothing works, follow the travis continuous integration script which successfully build the software from scratch.

**Comment by nyancat18** [comment]
tested from git (master)  

https://p.teknik.io/Raw/24vFt

**Comment by nyancat18** [comment]
i'm  testing a gapped build process (make -j7 to -j2)
