### ISSUE TITLE
Boost error makes Natron impossible to build

### ISSUE THREAD

**Issue by nyancat18** [MrKepzie/Natron#1677]
OS arch / manjaro testing
Boost boost 1.65.1
Arch: 64

https://p.teknik.io/cBhje

**Comment by MrKepzie** [comment]
You forgot to link against boost system and boost thread in config.pri:
boost {
 INCLUDEPATH += /opt/local/include
 LIBS += -L/opt/local/lib -lboost_thread-mt -lboost_system-mt
}

Please read build instructions and report build issues on forum

**Comment by nyancat18** [comment]
testing :)

**Comment by nyancat18** [comment]
/usr/bin/ld: cant find -lboost_thread-mt
/usr/bin/ld: cant find -lboost_system-mt

**Comment by nyancat18** [comment]
i'm testing this (thanks for give me an idea) 
https://askubuntu.com/questions/486006/cannot-find-boost-thread-mt-library

**Comment by nyancat18** [comment]
WORKED  (with   your enhacement and askubuntu idea)

THANKS
