### ISSUE TITLE
Time > SlitScan node alwasy uses RetimeMap A channel

### ISSUE THREAD

**Issue by unfa** [MrKepzie/Natron#1678]
The Time > SlitScan node seems to always use the Alpha channel of RetimeMap input - I had to use a Shuffle node to use an R channel instead, even though there's an option in the GUI to pick the channel - it seems to be ignored though.

Can anybody confirm this?

**Comment by devernay** [comment]
will check

**Comment by devernay** [comment]
is fixed for the next versions (2.x and 3.x)
