### ISSUE TITLE
OpenFX: Failure to read OpenFX plug-ins cache: XML parsing error : unclosed token

### ISSUE THREAD

**Issue by lulu1315** [MrKepzie/Natron#1679]
hello
I'm rendering Natron projects using afanasy using 4 nodes.
after a while , randomly , I noticed black images.
looking at the log of these pictures I have this message : 

NATRON = '/shared1/apps/Natron/Natron-2.3.2/Natron'
Natron Version 2.3.2
Copyright (C) 2013-2017 INRIA and Alexandre Gauthier-Foichat
>>>Use the --help or -h option to print usage. Restoring the image cache...
Loading plugin cache...
OpenFX: loading GMIC_arrayfaded v1.0
OpenFX: loading GMIC_arraymirrored v1.0
..... (loads all plugins)
OpenFX: loading net.sf.cimg.CImgBilateralGuided v2.0
Error while loading OpenGL: X11: Failed to open display
OpenGL rendering is disabled. 
Failed to connect local socket to IPC_COM
Info: init.py script found and loaded at /shared1/apps/cgru/plugins/natron/init.py
Loading PyPlugs...
Loading project: /whatever.ntp
[19:08:14.580] OpenFX: Failure to read OpenFX plug-ins cache: XML parsing error at line 8973:6: unclosed token
[19:08:16.375] Project: ERROR: The node net.sf.openfx.GradePlugin version 2.0 was found in the script but does not exist in the loaded plug-ins.

the images renders black.

so it seems to be a problem with the OpenFX plug-ins cache getting corrupted.
all the nodes are rendering with the same user , the default cache is pointing to ~/.cache/INRIA/Natron

I changed the cache directory (in preferences/Caching) to point to /var/tmp so that each node writes to a unique place but the OFXLoadCache/ directory stays in the home dir , only DiskCache and ViewerCache are created.

so I don't know if it's a bug or a feature (OFXLoadCache not following the Cache dir parameter)
and why the OpenFX plug-ins cache gets corrupted.
This is particularly happening when I use GMIC plugins ...

thanks in advance for any hint
luc

### Versions
Natron version 2.3.2 Release
Description:    KDE neon User Edition 5.10
Release:        16.04
Codename:       xenial

**Comment by devernay** [comment]
please attach your OFX plugin cache (it's an xml file, zip it)

**Comment by devernay** [comment]
i supposed you tried clearing the plugins load cache and relaunching?

**Comment by lulu1315** [comment]
absolutely.I will try to regenerate a corrupted one.

**Comment by devernay** [comment]
FYI it is usually because of a plugin that has bad characters in the plugin description which break the XML. I will have to:
- fix the doc of that plugin (because it will definitely break Nuke which uses the same plugin cache)
- fix the HostSupport library to better handle this character

**Comment by lulu1315** [comment]
[OFXCache_2.3.2_Release_0.zip](https://github.com/MrKepzie/Natron/files/1355551/OFXCache_2.3.2_Release_0.zip)

**Comment by lulu1315** [comment]
remains after a bad render ...

**Comment by devernay** [comment]
where is the error, according to the console message? 8973:6 ?

**Comment by lulu1315** [comment]
yes

**Comment by devernay** [comment]
and if you move away GMIC.ofx.bundle from /mnt/autofs/shared1/apps/Natron/Natron-2.3.2/Plugins/OFX/Natron/GMIC.ofx.bundle does it still crash?

**Comment by lulu1315** [comment]
I'm switching to 2.3.3 atm.I will try that.

**Comment by lulu1315** [comment]
this one is with the GMIC plugin / Natron 2.3.3
error log is : 
[13:29:37.323] OpenFX: Failure to read OpenFX plug-ins cache: XML parsing error at line 18252:6: unclosed token
[13:29:37.323] OpenFX: Failure to read OpenFX plug-ins cache: XML parsing error at line 18252:6: unclosed token
[13:29:37.907] Project: ERROR: The node GMIC_engrave version 1.0 was found in the script but does not exist in the loaded plug-ins.
[OFXCache_2.3.3_Snapshot_0.zip](https://github.com/MrKepzie/Natron/files/1355613/OFXCache_2.3.3_Snapshot_0.zip)

**Comment by lulu1315** [comment]
rendering without the gmic plugins and Natron 2.3.3 works fine ... 
will do some more renders and  let you know
thanks for your help
luc

**Comment by devernay** [comment]
If fixed the next versions of Natron (2.3.3 and 3.0) so that

- The OFX Plugin cache is stored at the same place as the disk cache
- The OFX Plugin cache is only written if the plugins changed (it used to be systematically written at each start of Natron, so that the cache could be corrupted for another Natron trying to read the cache at the same time)

The snapshot system is down at this time, but we will try to rebuild a snapshot before the weekend.

**Comment by lulu1315** [comment]
thank you.just for curiosity , is 3.0 already available somewhere ?

**Comment by devernay** [comment]
it's not stable enough yet. It's almost a complete rewrite. We hope to get a stable release by the end of the year.

**Comment by lulu1315** [comment]
cool."bon courage" for that.luc
