### ISSUE TITLE
[request/question] Any plan to support CMake? 

### ISSUE THREAD

**Issue by archenroot** [MrKepzie/Natron#1680]
Guys, I have been waiting for stuff like this for ages watch you for some time and see you really progress.

I mainly work on Gentoo system where we compile anything that is compilable :-), as we have almost fully automated ebuild classes for CMake system (and others as well), I wanted to ask you if you plan to support CMake or any standard building system which might make compilation easy.

I note that I didn't build Natron from github yet, but now started examining possible ways how to adopt it into Gentoo ecosystem.

So looking into this document, it will be also quite easy to adopt:
https://github.com/MrKepzie/Natron/blob/master/INSTALL_LINUX.md

Again maybe it is my personal preference to do think in CMake way.

Thanks for answer.

**Comment by devernay** [comment]
We won't break what works for now. Building Natron with QMake works. Building the plugins with Makefiles works.
If someone wants to contribute CMakeLists we will gladly integrate these. There is a cmake branch in https://github.com/devernay/openfx but it never really worked.
