### ISSUE TITLE
Cant run natron

### ISSUE THREAD

**Issue by nyancat18** [MrKepzie/Natron#1684]
Branch: master
commit

190095a3ac525a6afbba95992f2006500fb28866

log

Natron
Natron Version 3.0
Copyright (C) 2013-2017 INRIA and Alexandre Gauthier-Foichat
>>>Use the --help or -h option to print usage.<<<
Fontconfig configuration file  does not exist, not setting FONTCONFIG_PATH 
Py_SetProgramName("Natron")
Info: init.py script not loaded (this is not an error)
Info: initGui.py script not loaded (this is not an error)

**Comment by nyancat18** [comment]
pd run as root dont fix it

**Comment by devernay** [comment]
Natron 3 is not ready for general use. Please use Natron 2.3 (release or snapshots)
