### ISSUE TITLE
Lines connecting the nodes are hard to see on UDF display

### ISSUE THREAD

**Issue by Amiense** [MrKepzie/Natron#1685]
Noodles, the lines connecting the nodes, are very hard to see on an UHD display. Especially while working on a 15.6" laptop and there's no highlighting just like in Nuke. No issues in other applications, which is why I'd like to keep the display at that resolution. An additional preference setting would be helpful.

I'm aware of solving the node graph colour outlined here https://forum.natron.fr/t/customizing-colors-of-the-node-graph/15223 But I'd like to keep that one and set my noodle color to white. Also went into mainstyle.qss but without success.

**Comment by devernay** [comment]
TODO: add preferences for noodle thickness and color

**Comment by devernay** [comment]
This issue was moved to NatronGitHub/Natron#226
