### ISSUE TITLE
Sync Natron playback to JACK transport

### ISSUE THREAD

**Issue by unfa** [MrKepzie/Natron#1686]
Natron doens't provide any audio functionality. Often one would like to sync animation to sound or just have audio playback synced to Natron to get a better understanding of the whole project.

One way to achieve this without implementing any audio functionality in Natron would be to provide JACK transport sync.

That would allow people to use Natron with Ardour or other JACK-aware pro-audio tools to play in sync - allowing integrating Natron in audio-centric workflows without having it to handle any audio at all.
Blender can be used the same way for animating, with synced audio playback from other programs.

JACK Transport details:
http://www.jackaudio.org/files/docs/html/transport-design.html

**Comment by devernay** [comment]
great idea.
Any documentation on how to use it in Blender?

**Comment by unfa** [comment]
I'm not sure if this is what you're asking for, but here's a little guide on how to use that function in Blender:
https://audaspace.wordpress.com/2010/02/21/jack-transport

**Comment by sirjohndfox** [comment]
@unfa What do you use at the moment to composite? I'm Wanting to make animation.captions for my music.

**Comment by unfa** [comment]
I'm usually going for Natron, however I've had a problem recently with a project so I had to switch to Blender.

If you want to create animated text for music (lyrics video?) I'd suggest going for Blender, however it's not an easy thing to do if you don't have any experience with it.

**Comment by devernay** [comment]
This issue was moved to NatronGitHub/Natron#227
