### ISSUE TITLE
Cannot render past frame 775

### ISSUE THREAD

**Issue by unfa** [MrKepzie/Natron#1687]
I've created a rather simple animation in Natron, but I cannot render it out.
Approximately halfway though rendering from the GUI fails, and NatronRendered quits. I have no idea why is that - I haven't seen such problem yet.

Here's the project file: 
[01_002.zip](https://github.com/MrKepzie/Natron/files/1417428/01_002.zip)

I'm running Natron under Linux Mint 18.2. Tested on two machines - same result.

**Comment by unfa** [comment]
Looks like the problem was caused by a Lens Distortion node (used here to add chromatic aberration). When I disabled that node, the whole thing rendered fine for the first time.

I figured that out by looking at the graph while Natron was rendering - the Lens Distortion node seemed to take a long time to process so I tired disabling it.

I tried using the commandline to get more information, but I got nothing. I wonder how can I debug such problems?

**Comment by devernay** [comment]
I'll take a look at it. It seems to be a memory problem.
Can you please give me the command-line options for NatronRenderer, or do I just use the default params (starts 
In the mean time, did you try to use the STMap output of LensDistortion? See the LensDistortion documentation: http://natron.readthedocs.io/en/master/plugins/net.sf.openfx.LensDistortion.html

**Comment by devernay** [comment]
My other advice is: be careful with anything generated out of the project extent. For example, if you put a Blur after an effect that extends the RoD (eg LensDistortion), Natron will actually generate an image much larger than the project, and thus eat a lot of memory. You should insert Crop nodes wherever you see the RoD has grown but you will not need it. This is especially true before and after the lensdistortion nodes. Inspect your graph, and wherever the RoD goes beyond format (Roto2 is the main culprid).
Do you think I should add the "Expand RoD" and "Crop to Format" parameters to LensDistortion? (for the doc of these params, see the Blur node)

**Comment by devernay** [comment]
here's the fixed project (added two crops)
[01_002_fixed.zip](https://github.com/MrKepzie/Natron/files/1431288/01_002_fixed.zip)
next snapshot on linux and mac has the new LensDistortion option + I fixed the "time remaining" display
