### ISSUE TITLE
 import psycopg2 segfaults Natron windows 10

### ISSUE THREAD

**Issue by mangopipeline** [MrKepzie/Natron#1688]
Please ask questions ("how do I...?") on the [forum](http://forum.natron.fr), not by filing issues.

Make concrete suggestions for fixing the code ("here is a patch") by filing
a [pull request](https://github.com/MrKepzie/Natron/pull/new/master), not an issue.

### Problem

While testing Natron to see if we could connect it to a postgreSQL DB we found that importing psycopg2
quits out Natron, with no warning or error messages.
it's a total crash out.

As far as pipeline this is a complete show stopper goes...

### Steps to Reproduce

1. install psycopg2 lib to a python path Natron can see
2. execute the following code

import psycopg2

### Versions
Natron Version 2.3.2
Windows 10

**Comment by devernay** [comment]
You should try:
- install pip with using the natron-python binary that comes with Natron (only snapshots ATM)
- install psycopg2 using this pip.
There is not guarantee though, as it may require a compiler and lots of other stuff.
I think the best solution would be that we ship MariaDB, PostgreSQL and SQlite3 python adapters with Natron. Just filed https://github.com/MrKepzie/Natron/issues/1694
