### ISSUE TITLE
Immovable nodes wen are placed in the title blackdrop node area.

### ISSUE THREAD

**Issue by tebicap** [MrKepzie/Natron#1689]
There are some nodes that I cant move with the mouse after i put them on the title backdrop area.
Apparently the issue only affects ROTO cloned nodes.

A link with the issue (video), and the file project: https://drive.google.com/drive/folders/0ByzCdzO0jRwGOWZ6LTBRdC11Mm8?usp=sharing

Natron version: 2.3.2 Release
OS version: Ubuntu 17.10. 64bits

(sorry if my english is bad)

**Comment by devernay** [comment]
fixed by https://github.com/NatronGitHub/Natron/commit/eb2933602415d51ab38a41059764dd4785b35e55
