### ISSUE TITLE
[FEATURE REQUEST] Viewer orientation

### ISSUE THREAD

**Issue by tebicap** [MrKepzie/Natron#1690]
FEATURE REQUEST
Viewer orientation

Sometimes I need to work vertical videos for mobile devices, it would be great to add an orientation view option in the viewer node/pane. Actually I have to do a rotation and resizing of the entire project before to send it to the viewer node (for fix to the view area).

(sorry if my english is bad)

**Comment by devernay** [comment]
Actually, you should rotate everything just after the readers, and rotate again before the writers if you really want a rotated video (which is strange to me).
I don't thing this feature request makes sense, since adding two rotations fixes everything.

**Comment by tebicap** [comment]
that i need is only a rotated preview (as if I was watching vertical content on a smartphone). The writers must not be rotated (with Exif metadata i can set the orientation at playing). Actually I do the rotation just before the viewers, but an scale is needed too (to fit entire fotage in the visible area viewer) and this consumes machine resources.

**Comment by devernay** [comment]
Actually you should use Reformat and check the "turn" checkbox to turn 90 deg counterclockwise. to turn 90 degrees clockwise you should use flip+flop+turn.
I will be possible to have a "rotating viewer" in Natron 3.
