### ISSUE TITLE
Natron 3 link fails on linux-i386 due to MangledOSMesa32

### ISSUE THREAD

**Issue by devernay** [MrKepzie/Natron#1692]
### Problem

https://ci.inria.fr/natron/job/natron-github-master-any/slave=natron-centos-64-i386/lastBuild/consoleFull 
```
/usr/bin/ld: /opt/Natron-sdk/osmesa/lib/libMangledOSMesa32.a(glapi_libglapi_la-glapi_x86.o)(.text+0x5): unresolvable R_386_32 relocation against symbol `_gl_DispatchTSD'
```

**Comment by bn0785ac** [comment]
@devernay at linux64   i've got some segfaults *build, but doesnt run*

**Comment by devernay** [comment]
what do you mean? what doesn't run? Natron or the Shadertoy plugin?

**Comment by devernay** [comment]
fixed by https://github.com/devernay/osmesa-install/commit/322232856f6eb10d96de3fe80a14e458b9629b17
