### ISSUE TITLE
Bloom node - allow X/Y offset between blur pases

### ISSUE THREAD

**Issue by unfa** [MrKepzie/Natron#1695]
I was recently creating animated fire effect in Natron, and I've figured out I am missing one option in the Bloom Node.

To make a proper "flaming text" effect I need to blur and offset vertically the text, then distort the composite blurred layers with an animated SeNoise (also should have an animated Y translation, shifting up).

I could do this with a bunch of blur, transform and merge nodes, but I could also do it with a single bloom node if it would allow an X/Y offset between blur passes:

![image](https://user-images.githubusercontent.com/491704/32777477-87021e38-c936-11e7-943f-082b705f67a1.png)

**Comment by devernay** [comment]
you probably want a pixel-dependent XY offset, though, which means an SeNoise has to be in between
