### ISSUE TITLE
ColorLookup No work, no normal operation

### ISSUE THREAD

**Issue by AlphaFase** [MrKepzie/Natron#1696]
### Problem

There is a problem with the ColorLookup node
Ubutnu16.04: no work, no crash, but black screen, no modification of attributes
Windows7-10: program crash

### Steps to Reproduce

1. add "Read" Node
2. add "ColorLookup" Node
3. Adjusting "ColorLookup" node attributes
4. bug collapse

### Versions

* **Natron version/commit** (they can be retrieved from the About Window):  2.3.3
* **OS version:** 
*  > ubuntu16.04(x86_x64) 
* > windows7(x86_x64) 
* > windows10(x86_x64)

**Comment by devernay** [comment]
This issue was moved to NatronGitHub/Natron#229
