### ISSUE TITLE
Feature request: Animated Wave Node

### ISSUE THREAD

**Issue by hellocatfood** [MrKepzie/Natron#1698]
As described here https://forum.natron.fr/t/animated-wavy-text/1887 it is not possible to animate the wave node without having to move the input text/image or changing the amplitude or length of the wave.

Could it be possible to animate the wave without having to change these settings? It could borrow concepts from Blender's Wave Modfier, where the animating of the wave is automatic and the user specifies the height/width/length of the wave

![screenshot from 2017-11-21 13-41-49](https://user-images.githubusercontent.com/151947/33075589-f8c8c41e-cec1-11e7-9a7d-92354eed03b5.png)

**Comment by devernay** [comment]
The Wave plugin uses that function of ImageMagick: http://www.imagemagick.org/Usage/warping/#wave

And, unfortunately, 
Basically the "-wave" operator does not (at this time) allow you to specify an offset for the start of the sine function. This can be rectified however by adding, then removing, an image offset using "-splice". 

The solution I have involves an SeExpr node with the following RGB script:
```
cpixel(1,frame,x,y+x2*sy*sin(2*3.1416*(x/sx - x3)/x1),2)
```
set the number of scalar params to 3.
x1 is the wavelenth
x2 is the amplitude
x3 is the phase shift in pixels (which is missing from the Wave plugin)

**Comment by hellocatfood** [comment]
Thanks. It's a shame this can't be in the Wave node but your work around works.

I also had to copy it to the Alpha Script to get an alpha channel
