### ISSUE TITLE
Feature suggestion: add V-Log Colourspace

### ISSUE THREAD

**Issue by CameraRick** [MrKepzie/Natron#1699]
### Problem

With Varicams and GH5s beeing all over the place, making the V-Log curve available as colourspace inside of Natron would make quite a lot of sense.
I have found no way to add V-Log to the Colourspaces as I'd do in Nuke, still I feel like it should be shipped with it anyway :)

The formula is:
`x >= 0.181 ? pow(10.0, ((x - 0.598206) / 0.241514 )) - 0.00873 : (x - 0.125) / 5.6`

This is straight from Panasonics whitepaper: http://pro-av.panasonic.net/en/varicam/common/pdf/VARICAM_V-Log_V-Gamut.pdf

I do happen to  have a vlog.spi1d that represents this curve on my computer, but I have NO IDEA where I got it from, so sharing it might not be possible (after all, it's only values though)

**Comment by devernay** [comment]
V log is available with the aces 1.0.1 opencolorio config. You can get vlog
and vgamut from there.

**Comment by CameraRick** [comment]
But then you have to work in ACES which is not really convenient für everyone, no? I mean if there's another way I'd add it manually in my version, but so far I found none.

**Comment by devernay** [comment]
I added the vlog curve to the current snapshots, but I have no idea how to implement v-gamut correctly

**Comment by CameraRick** [comment]
Thank you very much :)

Hm, I also have no idea how one could implement V-Gamut, yet I think V-Log as a curve is more important to begin with. In Nuke, you can transform Gamuts within the normal Colorspace node utilizing a matrix; I have no idea how easy or hard it is to implement such a matrix, as that could be used by anyone reading the whitepapers

**Comment by CameraRick** [comment]
I downloaded the latest Snapshot from today, it's not in the list. Do I look wrong?

[https://i.imgur.com/ZJr2T1y.png](https://i.imgur.com/ZJr2T1y.png)

**Comment by devernay** [comment]
packaging mistake, sorry.

**Comment by devernay** [comment]
v-log and v-log+v-gamut are now in the default config.ocio

**Comment by CameraRick** [comment]
Just saw it in action, I appreciate it. Thanks for doing this small stuff even though there's much bigger bugs to fix!

**Comment by devernay** [comment]
Which bugs are "much bigger" in your opinion? There doesn't seem to be any blocking bug anymore in 2.3.

**Comment by CameraRick** [comment]
I worded that wrong, I more meant "general issues" :) yet I may have to re-open a bug report as it seems it still doesn't work, will have to check over Easter weekend. My PC has a hard time entering GitHub these days, no idea why, so I may have to type from phone :S
