### ISSUE TITLE
Gimp XCF file format

### ISSUE THREAD

**Issue by blackearth2014** [MrKepzie/Natron#17]
Can Natron read Gimp's multi-layer image format. I use for all of my graphics and matte painting work on the Mac. It would save a lot of time to be able to have this feature.

**Comment by olear** [comment]
Getting old, will start to look into a XCF/PSD reader with layers. Can't give any time frame since I'm very busy this summer, but have usually weekends free.

**Comment by blackearth2014** [comment]
Great

**Comment by olear** [comment]
I'm able to extract layers, is the complete image required(what you see in gimp)? If so will take some more effort.
![testxcf](https://cloud.githubusercontent.com/assets/7461595/7668367/ec1fd2be-fc34-11e4-8347-27b945214954.png)

Still a long way from a complete plugin, just testing.

**Comment by olear** [comment]
Sorry for the late reply, but got some time today to make a proper read node, stuff seems to work, and I can soon provide a ReadXCF and ReadPSD plugin.

**Comment by blackearth2014** [comment]
Thanks

**Comment by olear** [comment]
I did however notice that exporting to PSD from GIMP produces better image in Natron than loading the XCF... Could be some merge option used in the XCF or something.

**Comment by olear** [comment]
Current state:
![screenshot-10](https://cloud.githubusercontent.com/assets/7461595/8274618/629895b2-1895-11e5-86c5-74205f8ca4d9.png)
![screenshot-11](https://cloud.githubusercontent.com/assets/7461595/8274619/65791450-1895-11e5-852b-f224a70539b3.png)

**Comment by MrKepzie** [comment]
I'm closing this since it's taken care of in openfx-arena

**Comment by olear** [comment]
Still not complete, but soon.
