### ISSUE TITLE
Texture node: rename Gradient/Regular to Gradient/Linear

### ISSUE THREAD

**Issue by hellocatfood** [MrKepzie/Natron#1700]
In the Texture node the backgrounds you can choose aer Gradient/Regular and Gradient/Radial.

I think the former should be changed to Gradient/Linear as it more accurately describes the type of gradient and is in keeping with software such as GIMP, Inkscape and Blender.

**Comment by devernay** [comment]
This issue was moved to NatronGitHub/Natron#230
