### ISSUE TITLE
std::bad_alloc on frame 1

### ISSUE THREAD

**Issue by betaredex** [MrKepzie/Natron#1702]
### Problem

Rendering always immediately fails on a certain project (which involves a transform node being used to pan around a static image)

**Expected behavior:** Rendering to complete successfully

**Actual behavior:** Rendering failed

Error log:
```
-> % ./Misc/Natron/bin/NatronRenderer-bin -d Editing/Bonezone/relics.ntp
Restoring the image cache...
Loading plugin cache...
Info: init.py script not loaded (this is not an error)
Loading PyPlugs...
Loading project: /home/ebrock/Editing/Bonezone/relics.ntp
Write1 ==> Rendering started
Error while rendering: std::bad_alloc
Write1 ==> Rendering finished
```

### Versions

* **Natron version** 2.3.3
* **OS:** Void Linux

Thanks in advance

**Comment by betaredex** [comment]
Alright, I've narrowed down the source of the error to the transform node (maybe the scaled image eats too much memory?)

**Comment by betaredex** [comment]
The problem turned out to be the Angle Blur node, which i was forced to remove for the project to render correctly.

**Comment by devernay** [comment]
Did you try adding a Crop node just after the nodes that expand the RoD a lot (e.g. angleblur)?
AngleBlur generates content outside of the project bounding box.

**Comment by devernay** [comment]
This should be fixed by https://github.com/NatronGitHub/openfx/commit/19ae07da61973276d5b98db73db884580e89ea5c
Can you please test on the next snapshot?

**Comment by betaredex** [comment]
It was a while ago, but I think I got it to work by cropping it and rendering the project a few hundred frames at a time. I'll try it on the new build when I get a chance.
