### ISSUE TITLE
Color Correction Ranges are clamped from 0-1

### ISSUE THREAD

**Issue by RichardULZ** [MrKepzie/Natron#1703]
### Problem
On the Color Correction node, the highlight selection range is clamped from 0-1. 
This makes softly selecting and grading highlights of exr renders or hdr images hard.

**Expected behavior:**
Using the highlight control of color correct to softly pull down bright highlights on exr renders, by extending the highlight range above 1

**Actual behavior:**
The highlight range is clamped and will stop increasing power on values over 1

### Steps to Reproduce

1. Create a Color Wheel with edge value 0
2. Create a Color Correct node and set the **master gain** to **2.0**
3. Create another Color Correct node and set the **highlight gain** to **0**
4. Go to the ranges tab and set the **highlight range** to **x0.9 y0** and **x1.1 y1**

You will see an edge where the adjustment starts to darken values over 0.9, but will not increasingly darken values over 1, any rgb value over 1.1 should be black.

![natron cc issue](https://user-images.githubusercontent.com/34431457/33816018-f117a8d2-de9a-11e7-8cd6-a25552ce6f99.JPG)

### Versions
* **Natron version/commit**: 2.3.3 Release
* **OS version:** Windows 7 x64

**Comment by devernay** [comment]
great bug report, thanks for the effort

**Comment by devernay** [comment]
please test with the latest build.

**Comment by RichardULZ** [comment]
WOW! That was fast and it works flawlessly! Huge workflow improvement. Will be making more bug reports in the future.
