### ISSUE TITLE
Color Correction Master saturation overrides Highlight and shadow

### ISSUE THREAD

**Issue by RichardULZ** [MrKepzie/Natron#1706]
### Problem
On the Color Correction node, Master saturation will not work as expected with highlight and shadow adjustments. 

**Expected behavior:**
Using the Master saturation at the same time as highlights and shadow controls, 
master saturation should act the same as creating a saturation node after highlight and shadow adjustment.

**Actual behavior:**
If master saturation is 0, highlight and shadow will be disabled, if saturation is above 1, the highlight and shadow effect is multiplied.

### Steps to Reproduce

1. Create a Color Wheel with **edge value 0**
2. Create a Color Correct node and set the **highlight gain** to **0** and **Shadow gain** to **4**
3. Change the **master saturation** between 0 and 4.

Bringing saturation to 0 will fade off the highlight correction.
Bringing saturation to 2 will multiply the power of highlight correction.

The example file has 2 outputs, the right is the steps mentioned above, the left is doing highlights on one node, and saturation on another node afterwards.

![sat](https://user-images.githubusercontent.com/34431457/33868892-85f6bf40-df6a-11e7-9482-d2c050b73830.jpg)
[CCSaturationntp.zip](https://github.com/MrKepzie/Natron/files/1550374/CCSaturationntp.zip)

(might be a tad trickier than clamped ranges... good luck)

### Versions
* **Natron version/commit**: 2.3.4 Release
* **OS version:** Windows 7 x64

**Comment by devernay** [comment]
fixed in the next snapshot
