### ISSUE TITLE
RotoPaint node doesn't remember "single" Life Time setting

### ISSUE THREAD

**Issue by Eneen** [MrKepzie/Natron#1707]
![rotopaint_single_lifetime](https://user-images.githubusercontent.com/25537418/33988203-02cb26aa-e0c4-11e7-9560-e2561799c3e0.gif)

1. Create empty project
2. Add RotoPaint
3. Draw simple bezier
4. Select Bezier1 and set Single
5. Deacticate Bezier one by clicking inside empty RotoPaint node space
6. Click Bezier1 again

Sidenote: seems like it's switching from "Single" to "From start"

Natron 2.3.4 Release
Windows 10

**Comment by devernay** [comment]
fixed by https://github.com/NatronGitHub/Natron/commit/161368b83842e240fb5f6fbe8ad596a7dbb65d4d
