### ISSUE TITLE
Adjusting User-Parameters crashes Natron (on OSX)

### ISSUE THREAD

**Issue by CameraRick** [MrKepzie/Natron#1708]
### Problem
https://youtu.be/JGmyh9_FHAQ

See video for better presentation. When I try to adjust User Parameters, e.g. change defaults of knobs or adjust starting of new lines, Natron crashes as soon as I close the User-Parameters dialogue box.
Tested in Natron 2.3.4 and the Snapshot from 171215, 1:10h

**Expected behavior:** [What you expected to happen]
- changes are processed and Natron doesn't crash

**Actual behavior:** [What actually happened]
- Natron crashes

 * If your problem is a crash in an official release/snapshot, please include verbose output from the application
 from a terminal if possible.  If you also submitted a crash report, indicate the CrashID if possible.
I have no idea how to start Natron with verbose output :(
Crash ID = 43F9C238-78CB-4D43-8B1F-65150231A856

### Steps to Reproduce

1. Create User-Parameters for e.g. a PyPlug
2. Create a Parameter, e.g. picking a knob inside the Pyplug
3. Change a default value on this knob
4. Close the User-Parameters window
5. Crash

Like here: https://youtu.be/JGmyh9_FHAQ

### Versions

* **Natron version/commit**: 2.3.4 stable, 2.3.5 Snapshot (171215, 1:10h)
* **OS version:** OSX 10.11.6

**Comment by CameraRick** [comment]
I quickly tested on Win10 Pro, here it doesn't crash. Seems to be an OSX issue then!

**Comment by devernay** [comment]
This issue was moved to NatronGitHub/Natron#232
