### ISSUE TITLE
Crash Report 35d8ce24-bf40-41e2-9a4a-5d536ba5bce8

### ISSUE THREAD

**Issue by fabiof17** [MrKepzie/Natron#1709]
Please ask questions ("how do I...?") on the [forum](http://forum.natron.fr), not by filing issues.

Make concrete suggestions for fixing the code ("here is a patch") by filing
a [pull request](https://github.com/MrKepzie/Natron/pull/new/master), not an issue.

### Problem

Describe the problem or suggestion here.

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [Shadertoy Median Filter made Natron to crash]

 * If your problem is a crash in an official release/snapshot, please include verbose output from the application
 from a terminal if possible.  If you also submitted a crash report, indicate the CrashID if possible.
 
 * If you need to report a compilation issue, please create a [gist](https://gist.github.com)
 that contains the _full_ verbose build log.
 
 * If your problem is a crash in a build that you made yourself, please create a [gist](https://gist.github.com)
 that contains a _full_ backtrace.

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

You may submit a link to any screenshots/videos that can be used to understand how to reproduce the issue.

### Versions

* **Natron version/commit** 2.3.4: 
* **OS version:** Windows 7

**Comment by devernay** [comment]
https://natron.fr/crash-reports/?r=35d8ce24-bf40-41e2-9a4a-5d536ba5bce8

Is it fixed in 2.3.6?

**Comment by fabiof17** [comment]
Yes. Tested it today, it works now.
Thanks.

2018-03-07 17:47 GMT+01:00 Frédéric Devernay <notifications@github.com>:
