### ISSUE TITLE
Gaffer Support

### ISSUE THREAD

**Issue by DGMurdockIII** [MrKepzie/Natron#1710]
don't now if you have heard of gaffer but I would like it supported in this app if not here this is what it is Gaffer is an open source application framework designed specifically for creating tools for use in visual effects production. It builds on top of the Cortex libraries, adding a flexible node-based computation framework and a user interface framework for editing and viewing node graphs.

https://github.com/GafferHQ/gaffer7

http://www.gafferhq.org

https://forum.natron.fr/t/gaffer-support-in-natron-please/1911

**Comment by devernay** [comment]
This issue was moved to NatronGitHub/Natron#233
