### ISSUE TITLE
ReadNode with Frame Mode: Time Offset 

### ISSUE THREAD

**Issue by AntohaRDNS** [MrKepzie/Natron#1711]
### Problem

If  save project, that contain Read node(s) with option Frame Mode: Time Offset,
after loading project all this nodes doesn't work due: "Failure to find request layer in file" Error.

- Use single/multi channel exr - sequences 
- Reload button doesn't fix problem

P.S. Thanks for the amazing program!

**Expected behavior:** [What you expected to happen]

- All broken Read nodes, after reloading doesn't have any output layers

### Steps to Reproduce

1. Create new project
2. Create Read Node with option Frame Mode: Time Offset. Set some offset
3. Load some exr sequence.
4. Save project
5. Reopen project

### Versions

* **Natron version/commit** (they can be retrieved from the About Window): 
2.3.4
* **OS version:** 
macOS 10.12.6

**Comment by devernay** [comment]
bug happens with any offset? positive or negative?

**Comment by AntohaRDNS** [comment]
Hello! 
ERROR: I have issue with positive offset if (sequence: 140 frames, offset: 183 frames) 
NO ERROR : I don't have issue with positive offset  if (sequence: 140 frames, offset: 60 frames)
It seems that error appear only if offset > sequence length



>Понедельник, 15 января 2018, 12:40 +03:00 от Frédéric Devernay <notifications@github.com>:
>
>bug happens with any offset? positive or negative?
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


С уважением 
Антон

**Comment by devernay** [comment]
ok thanks, I will test this
