### ISSUE TITLE
Custom dither patterns

### ISSUE THREAD

**Issue by hellocatfood** [MrKepzie/Natron#1712]
Does Natron have any way to use custom dither patterns in the Quantize node? Currently the node has various Ordered Dither options, and I'd like to specify my own pattern.

For illustration please see the below examples:

Imagemagick has an overview of how to create your own dither patterns http://www.imagemagick.org/Usage/quantize/#od_posterize

GIMP has/had a plugin that can allow you to pick an image have it be a dither pattern http://gimpchat.com/viewtopic.php?f=11&t=1409&start=10#p17160

Imagemagick also lets you use symbol patterns/frames from a gif as the pattern http://www.imagemagick.org/Usage/quantize/#diy_symbols

It would be great if we could have more control over dithering in Natron.

**Comment by devernay** [comment]
You should use either ShaderToy, SeExpr, or GMICExpr for such a function. There are many shadertoy dithering examples on the web.

**Comment by devernay** [comment]
won't fix. Someone has to contribute this, for example using shadertoy or seexpr.
