### ISSUE TITLE
Pre-compiled binaries doesn't exist

### ISSUE THREAD

**Issue by 1xinghuan** [MrKepzie/Natron#1716]
Hi,
I tried to compile natron on windows and followed the instructions. But the pre-compiled binaries doesn't exist:
![_20180110011311](https://user-images.githubusercontent.com/33982538/34750289-55095284-f5e1-11e7-9a27-43acf1348763.png)

Also in **openfx-io**, the pre-compiled static binaries and "Compiling-OpenColorIO-static-on-Windows" link doesn't exist:
![_20180110011325](https://user-images.githubusercontent.com/33982538/34750390-c93c58d6-f5e1-11e7-85c3-296c6b65753f.png)

**Comment by devernay** [comment]
Yes I know, these instructions are outdated...
If someone manages to update these, we will integrate the changes.

**Comment by devernay** [comment]
This issue was moved to NatronGitHub/Natron#234
