### ISSUE TITLE
Bad network paths on symlink provided to OCIO.

### ISSUE THREAD

**Issue by Narann** [MrKepzie/Natron#1719]
Hi and thanks for Natron, we try to use it at work.

### Problem

Natron seems to badly resolve network paths in Windows when providing it to OCIO.

We use natron over the network. Full path:

    C:\app\inria\natron\2.3.4\bin\Natron.exe

This:

    C:\app\inria\natron

...is a symlink to:

    \\srvapp\app\inria\natron

When we put a reader we have:

![image](https://user-images.githubusercontent.com/659708/35214537-c2db5706-ff61-11e7-8daf-9a90707de0ec.png)

Note the `C:/app/inria/UNC/svrapp/natron/2.3.4...` depict being correctly displayed into the project setting window.

We tried to override `OCIO` env var explicitly to an explicity path but no luck. The only "working" solution is to have a `.ocio` locally and point on it with the environment variable.

We use the portable version.

### Steps to Reproduce

(Not tested but I guess, sorry for this)

Download the [portable version](https://downloads.natron.fr/Windows/releases/64bit/files/Natron-2.3.4-Windows-x86_64bit-no-installer.zip). Put it into a folder accessible through the network. Let's say `\\myserver\\natron`.

Locally, create a symlink to this location:

    mklink /d C:\mynatron \\myserver\\natron

Start Natron in `C:\mynatron\bin\Natron.exe` and read an `.exr` file.

### Versions

This software was compiled from the source code branch tags/2.3.4 at version c64f157 using GNU C++ version 7.2.0 with OpenMP 4.5 targetting Intel x86-64 for Unix Environment.
The bundled openfx-io plugins were compiled from version 4cc07f9.
The bundled openfx-misc plugins were compiled from version 99a9628.
The bundled openfx-arena plugins were compiled from version 47f3c07.

Windows 7.

Thanks in advance,

Dorian

**Comment by devernay** [comment]
When you set the OCIO env var to a custom OCIO, what happens? Does it work for a local OCIO config? does it work for a remote OCIO config?

**Comment by Narann** [comment]
Thanks,

> When you set the OCIO env var to a custom OCIO, what happens?

If I set `OCIO` env var to an absolute path:

* If the path is "with symlink in it" (in our case: `C:\app\inria\natron\2.3.4\Resources\OpenColorIO-Configs\blender\config.ocio`): same problem (the message box).
* If the path is local (`C:\Users\<user>\my_config\config.ocio`): No problem.

> Does it work for a local OCIO config?

Yes, setting the `OCIO` path to a fully local path works.

> does it work for a remote OCIO config?

I just tested to put a fully network path (no symlink): `\\server\natron\Resources\OpenColorIO-Configs\blender\config.ocio` and it works, no message box and I can see my images.

So the problem is with symlinks using network: Local symlink pointing to network location. In our situation local symlink is `C:\app\inria\natron` pointing to network location `\\srvapp\app\inria\natron`.

**Comment by devernay** [comment]
This issue was moved to NatronGitHub/Natron#236
