### ISSUE TITLE
Disable all nodes inside Backdrop

### ISSUE THREAD

**Issue by ElDirector** [MrKepzie/Natron#1720]
Would it be possible to allow for the disabling of a backdrop node?  If I want to disable an entire section of a script, it would be faster to select the backdrop and hit D rather than having to select all the nodes (this is especially problematic with larger scripts).

Using a Mac trashcan here at my day job and it doesn't seem to be a feature.

**Comment by devernay** [comment]
Alternative: make a group rather than a backdrop. A group can be disabled.
I agree, though, that disabling a backdrop as a whole would be a very nice feature.

**Comment by devernay** [comment]
implemented
