### ISSUE TITLE
Rotopaint bug (Mac version)

### ISSUE THREAD

**Issue by ElDirector** [MrKepzie/Natron#1721]
### Problem

I use Natron on all three platforms.  I've noticed an issue that only appears on Mac when using rotopaint.  If I'm using the Clone tool to paint out something, we need to use Shift and Command to modify our brush.  The problem I'm running into is that after I make a stroke, the modifiers do not work and the tool just keeps painting, rather than changing the brush.  I have to select a different tool from the rotopaint node, then click back on the clone tool to re-enable Shift/Command to change the brush.  I have not noticed this on Windows or Linux, just Mac, and it has been common with the last few versions, including the latest.  Running OSX 10.12.6

**Comment by devernay** [comment]
I can't reproduce this on 2.3.6. Can you please explain more precisely (or post a screencast).

**Comment by ElDirector** [comment]
Seems to be okay so far with 2.3.6  I'll make a recording though if anything changes
