### ISSUE TITLE
Option to "Clear" the project

### ISSUE THREAD

**Issue by ElDirector** [MrKepzie/Natron#1722]
Feature request: I often find myself bouncing between 4-6 Natron scripts a day at work.  Currently I have to either close the entire application and relaunch or I can open the next project, then switch back to the first instance of Natron and close it.  It would be really cool if there was a "Clear" command under the File menu that would basically set you up with a new blank project ala Nuke without creating a whole new instance of the app or a new set of windows.  I've tried the "Close Project" command but it shuts down Natron completely.

**Comment by devernay** [comment]
You want us to implement something which will just save you *one* click? OK, 4 clicks per day...
Notes:
There's actually only one instance of Natron running.
The "Clear" menu item in Nuke doesn't follow any UI guidelines, so I don't see the point in adding this.
What platform are you on? On the mac, an application doesn't close when you close the last window. Nuke and Natron don't follow the macOS UI guidelines.

**Comment by ElDirector** [comment]
I guess my wording is wrong.  I do see how it only opens the once instance, but it brings up a new window/UI.  Part of my frustration is that my default layout has the viewer broken off onto a second monitor.  Unfortunately, this detail is not saved with the layout no matter how many times I tried.  So if I have a project open and click New Project, I get two new windows opening on my main monitor and I have to go place them again where I want.  Same if I open a second project.  Both windows open on the main screen, and I have to sort through them figuring out which is for what project and what goes where.  
If the layout file could "remember" which windows I have on what monitors and put them back there each time, that would make things faster and easier.

**Comment by devernay** [comment]
Does this workaround do the job for you?
- File/Save Project As... save the current project to your new project
- In the nodegraph, Ctrl-A (or Cmd-A on Mac) selects all nodes
- Delete all nodes

**Comment by devernay** [comment]
This issue was moved to NatronGitHub/Natron#237
