### ISSUE TITLE
Value trimming problem.

### ISSUE THREAD

**Issue by Banzovin** [MrKepzie/Natron#1723]
Please ask questions ("how do I...?") on the [forum](http://forum.natron.fr), not by filing issues.

Make concrete suggestions for fixing the code ("here is a patch") by filing
a [pull request](https://github.com/MrKepzie/Natron/pull/new/master), not an issue.

### Problem

Describe the problem or suggestion here.

This is a moderately serious problem.

When exporting a python plug-in I discovered that Natron is not consistently evaluating floating point values over 3 digits past the decimal point if the values are close to one another leading to problems upon attempted use of the plug-in. I experienced this problem with both Grade nodes and Clamp nodes while trying to make a python plug-in

These are two examples of what I would type or paste in Natron:
1. Values I typed in Natron Clamp node:  Minimum: 0.12, Maximum: 0.120000000001
2. Values I pasted in Natron Clamp node and then changed:  Minimum: 0.120000000001, Maximum: 0.120000000001 Changed to:  Minimum: 0.22, Maximum: 0.220000000001

**Expected behavior:** [What you expected to happen]

Expected values in exported py-plug-in file, and values I expect when the plu-in is used in Natron:
1. Minimum: 0.12, Maximum: 0.120000000001
2. Minimum: 0.22, Maximum: 0.220000000001

**Actual behavior:** [What actually happened]

The actual behavior varies depending on when and what state it was in when it was exported, but I'm including all the outcomes I've seen, and include my suspicion of the cause.

What the python file will contain:
1. One of the following: A. Minimum: 0.12, Maximum: 0.120000000001, B. Minimum: 0.12, Maximum: 0.12, C. Minimum: 0.12, Maximum: 0.120
2. One of the following: A. Minimum: 0.22, Maximum: 0.220000000001, B. Minimum: 0.22, Maximum: 0.220, C. Minimum: 0.220, Maximum: 0.220000000001, D. Minimum: 0.220, Maximum: 0.220

In Natron, upon use of the plug-in, I get one of the following:
1. A. Minimum: 0.12, Maximum: 0.12, B. Minimum: 0.12, Maximum: 0.120
2. A. Minimum: 0.22, Maximum: 0.22, B. Minimum: 0.22, Maximum: 0.220, C. Minimum: 0.220, Maximum: 0.220

What I believe might be the cause of this problem:
In no situation does Natron restore the full value of a given node field to the actual values originally entered & saved, and because Natron only seems to restore the first 3 floating point digits of any floating point value when it reconstructs the node graph, if the developer/user then re-exports a plug-in they reworked, Natron exports the new 3 digit trimmed values breaking those node data fields on the new export.

This problem has only been tested on the Windows Version of Natron 2.3.4 at this point, but because of the nature of this problem I believe it likely to exists for other platforms as well.

**Comment by devernay** [comment]
You can check the actual values in the PyPlug, it's just a text file (and so is the natron project file too).
I don't think we round to 3 digits, but maybe we don't save all (16) significant digits. 8 digits should be enough for most human beings, so we probably only save 8 digits or so (I don't remember). Most software do the same when saving text files.
Be careful about what is called "underflow" in numerical computation:
- 1e-8 is below what is called "FLT_EPSILON", so that, when using 32-bit floating point computation, 1 + 1e-8, i.e. 1.00000001 is strictly equal to 1
- 1e-16 is below what is called "DBL_EPSILON", so that, when using 64-bit floating point computation, 1 + 1e-16 i.e. 1.0000000000000001 is strictly equal to 1

My suggestion is to never use numbers that are so close to each other.
Keep away from FLT_EPSILON, mainly because parts of the computation (especially if it is GPU-based) may be done in 32bits floating point.
Actually, in Natron (and in Nuke, and probably in all compositing software), images are stored internally as 32-bit floating point, so that an image containing 0.120000000001 everywhere is *strictly* equal to an image containing 0.12.

Always make sure that in your workflow the numbers are as close to the [0,1] range as possible.

**Comment by Banzovin** [comment]
I have checked the py file. That is how I know that something was going wrong. I have 12 clamp nodes, and all the digits were modified to have two digit minimum set to a something like 0.12 and the maximum set to 0.120001.  Originally when I started having issues I had the maximum floating point value for the number set to 0.120000000001, and when I rechecked the py file the first time after reducing the number of 0's it hadn't changed from 0.120000000001 even though I physically changed the values in Natron, and reexported the py plug-in. So I then relaunched Natron and checked their values and they were all truncated with the exception of -0.000000000001 as that was noted as -1e13. This was the point things go wonky, because I discovered one of the values: 0.12 wasn't like the others. I checked the py file, and it was just minimum 0.12 and maximum 0.12. I fixed the broken one and reexported, and other values broke. Ultimately I went into the py file and manually set them all. Deleted the pyc, and relaunched Natron, every thing seems to work now. My speculation for why it broke was based off the odd, and inconsistent results I was getting in the py file after export. I quite litteraly had this break on me 3 or 4 times in different ways, and it was only when I started looking at the py file that I started realizing Natron was being inconsistent with how it exported the values. In truth I'm not sure the exact reason, only that it happened repeatedly till I fixed it with a python editor.

**Comment by Banzovin** [comment]
Oh, and here is a weird thing, prior to my messing with the python file, Natron was showing -0.000000000001 as 1e-13 but this morning as I write this, I relaunched Natron, and it's showing the full value of -0.000000000001. Why does the result change from launch to launch?

**Comment by devernay** [comment]
Can you please check the next windows snapshot (which should be available ~4h from now) ?
The Natron UI now always shows the full precision values. I agree that the previous behavior was misleading.
I also checked that numbers are written to the natron project and pyplug with full precision.

However, be careful that images are stored as 32-bit float, which have and there is probably no 32-bit float value between 0.12 and 0.120000000001 (32-bits floats have at most 7 significant digits).

**Comment by Banzovin** [comment]
I will check. The purpose of the values was as a cutoff threshold for transitioning from one color to another with as much precision as possible.  I intentionally had the numbers that low so if there were a  gradual slope  the transition point would remain as consistent and possible. A few early tests with slightly lower values and a log gradient slop ended up with minor pixel variations. So I increased the precision.

**Comment by devernay** [comment]
fixed by https://github.com/NatronGitHub/Natron/commit/b47b545653dcec63c6c8e22b03b593ac77fe2de5
