### ISSUE TITLE
Roto Bug or Issue on Mac

### ISSUE THREAD

**Issue by ElDirector** [MrKepzie/Natron#1725]
### Problem

Running 2.3.4 on Mac trashcan.  I've had an ongoing issue with roto.  Let's say I use the ellipse tool to make a circular selection.  It's made of four points.  I want to move all four points at once, so I left click and drag to select all the points.  Now I move my mouse to the center of the roto shape until the cursor becomes a "D Pad" looking icon from a Game Boy (+).  Now I can click and move the roto shape to it's new keyframe.  So far so good.  I jump ahead to the frame where I want to do the next keyframe.  My shape is still selected.  I move my mouse to the center of the shape, it turns into the icon indicating I can move the entire shape but now it doesn't work.  Instead it feathers one of the points.  So I hit CMD Z, then have to redraw my selection box around the points.  Then it works.

Just like with the roto paint issue, I have to basically change my selection and then reselect it every time I want to move the entire rotoshape.  

I'd be happy to make a video of the issue and share it here if that would help.

**Comment by ElDirector** [comment]
I've figured out that the issue is whenever I click on the timeline to go to a new frame, the feather handles on the roto shape flip inward, rather than staying neutral.  So when I move the mouse to the center of the shape, while the mouse is activated for moving the entire shape, it instead grabs one of the feather handles.  Seems like the feather handles should remain off when the entire shape is selected.

**Comment by devernay** [comment]
This issue was moved to NatronGitHub/Natron#238
