### ISSUE TITLE
Tracker bugs on Mac

### ISSUE THREAD

**Issue by ElDirector** [MrKepzie/Natron#1727]
Sorry post again, but I keep finding bugs on the Mac version that don't exist for me on Windows or Linux.  

The issue I'm having now involves the tracker.  When I track a shot and export a transform, everything works fine the first time.  If I want to go back and add another track point, the tracker freezes when I click the track forward button.  The button turns from blue to red, but nothing else happens.  No frame advancement, no tracking.  

I can save and reopen the project, and it might work 7 times out of 10.  If I try to create a new tracker, the same problem happens.  The tracker basically does nothing.  I've tried this in three projects with three different sources of footage and I still get the same issue.

**Comment by devernay** [comment]
is this bug still present in 2.3.6?

**Comment by ElDirector** [comment]
Yes

**Comment by devernay** [comment]
you'll have to tell me the exact sequence of operations you are doing, because I cannot reproduce it.
Also, try reducing the number of render threads to 1 in the preferences if the bug still happens, and tell me if it changes anything

**Comment by devernay** [comment]
I need feedback to look into this

**Comment by ElDirector** [comment]
I have not checked in 2.3.8 yet, but will do so today

**Comment by devernay** [comment]
This issue was moved to NatronGitHub/Natron#239
