### ISSUE TITLE
Viewer Glitch on Mac

### ISSUE THREAD

**Issue by ElDirector** [MrKepzie/Natron#1728]
This is another glitch that had been ongoing for me, but seems to happen a lot more when using the tracker, so maybe it's tied to that.  If I zoom in to place trackers and then zoom back to full frame, either manually or by hitting F, the viewer fails to redraw.

Clicking refresh viewer doesn't work, neither does selecting a new frame.  Must close and re-open project.

![screen shot 2018-02-13 at 15 11 57](https://user-images.githubusercontent.com/22898215/36179283-92a64908-10d0-11e8-86b4-0c84a3323fd6.png)

**Comment by devernay** [comment]
what about:
- disactivating the tracker node
- closing the tracker properties panel
?

**Comment by devernay** [comment]
feedback?

**Comment by ElDirector** [comment]
Sorry for the late getting back to you.  The recommendations you suggested did not work for me.

**Comment by devernay** [comment]
This issue was moved to NatronGitHub/Natron#240
