### ISSUE TITLE
Blur node wrong "Expand RoD" result

### ISSUE THREAD

**Issue by fabiof17** [MrKepzie/Natron#1732]
### Problem

The Expand RoD of the Blur node still crops pixel at the very borders.
It's something i had noticed for quite a long time.

**Expected behavior:** Display all the blurred pixels

**Actual behavior:** Pixel on the edges are cropped.

### Steps to Reproduce

1. Draw a roto
2. Add a Blur node

### Screenshot :
![bug](https://user-images.githubusercontent.com/24624414/36756044-43e22e4c-1c0e-11e8-9695-20b1f43fe3fd.jpg)

### Versions

* **Natron version/commit** : 2.x.x
* **OS version:** Windows / Linux

**Comment by devernay** [comment]
That's normal behaviour. The Gaussian filter is actually an IIR (infinite impulse response) filter, so the blurred pixels actually occupy an infinite area. We had to cur somewhere, and that somewhere is at 99.5% or something like that. We use the same cutoff as Nuke btw

**Comment by fabiof17** [comment]
You're absolutly right.
For some reasons it wasn't that obvious in Nuke. Anyway...
I just noticed that as i am currently struggling with RoDs in Natron.
I'm always expecting Natron to behave exactly like Nuke, which is obviously not the case.
But that's another discussion.
