### ISSUE TITLE
Read node: Loop behaves unexepectedly

### ISSUE THREAD

**Issue by virtualritz** [MrKepzie/Natron#1734]
Using Natron 2.3.7 on MacOS.
[EcoBinLoop.ntp.zip](https://github.com/MrKepzie/Natron/files/1822884/EcoBinLoop.ntp.zip)

I have an EXR frame sequence with frame numbers from 200..296 that loops.
My **Project Settings** have **Frame Range** **first** set to **0** and **last** to **300** (shouldn't **first** and **last** be capitalised btw.?)
On my **Read** node **First Frame** is set to **200** with **Hold** and **Last Frame** is set to **296** with **Loop**.
**Frame Mode** is set to **Starting Time** and **Starting Time** is set to **0**.

This all works dandy for frames 0..96 in the project's timeline.

But when I set the timeline to frame **97**, I would expect Natron to request frame 200 on the **Read** node again (start of the EXR sequence, **Loop** set on **Read** node).

But Natron requests frame **194**! Example project attached.

Am I missing something obvious here?

Beers.

**Comment by devernay** [comment]
probably a bug, will look into it

**Comment by devernay** [comment]
fixed in the latest snapshots, and in the next version (2.3.8)

**Comment by virtualritz** [comment]
Cheers!
