### ISSUE TITLE
Cannot Import Video Files Generated From OBS to Natron

### ISSUE THREAD

**Issue by swarnimarun** [MrKepzie/Natron#1735]
I am not sure this is a Natron only problem but I tried using Blender instead and it worked, so was unable to think of reason why Natron shouldn't. 

### Problem

Whenever I tried to import a video file recorded from OBS to Natron it keeps giving me Read ERROR.

**Expected behavior:** To read the video so.

**Actual behavior:** Got Read Error.

### Steps to Reproduce

Just Create a Video using OBS and try import it into Natron. 

Link to the screenshot:  https://imgur.com/a/mwYPK
Link to a test-vid file: https://drive.google.com/open?id=17YNeE9Eqpfbx0ro6lIWrKJnE5-n_yA-W

### Versions

* **Natron version/commit**: 
Natron version 2.3.7 Release.

* **OS version:** 
Windows 10 64-Bit Pro

**Comment by devernay** [comment]
It's a known issue, sometimes the last frames of H264 sequences cannot be read. The ReadFFmpeg plugin would have to be rewritten.

**Comment by devernay** [comment]
Workaround: decode your video to individual frames, eg using ffmpeg.

**Comment by steincodes** [comment]
So it's a Windows only problem? Read about it in the issues. Sigh, Linux lacks quite a few of my favorite tools to a transition is unlikely. Unless I start writing software.
And, already used a workaround, dropped Natron from to-learn list will wait for it to get more ironed out. As OBS is quite integral for my workflow so converting files every time seemed like a hassle. Although I ended up writing a decoder(video to frame) for my current project(lots of files).

And how much longer do you think it will take to rewrite the FFmpeg reader plugin, it doesn't seem too difficult, still I have no experience programming this sort-of-stuff so I might be work.??

**Comment by devernay** [comment]
probably a dup of #1701

**Comment by devernay** [comment]
This issue was moved to NatronGitHub/Natron#241
