### ISSUE TITLE
Dots size.

### ISSUE THREAD

**Issue by fabiof17** [MrKepzie/Natron#1739]
Could they be much smaller. They are designed to organize the flow graph, not to be that much visible.

**Comment by ElDirector** [comment]
That's a nice idea!

**Comment by CameraRick** [comment]
I'd love to set the size in project settings (just like arrow thickness, wink wink). Reason beeing that when I'm zoomed out, I sometimes even have issues grabbing them at the current size, the "hitbox" seems to be quite small

**Comment by devernay** [comment]
Mouse has to be on the dot, just like every other node. Some want it smaller, some want it bigger... We made the current size choice based on existing practice, which seems reasonable. That's low priority for meLe 1 avr. 2018 00:24, lucas pfaff <notifications@github.com> a écrit :I'd love to set the size in project settings (just like arrow thickness, wink wink). Reason beeing that when I'm zoomed out, I sometimes even have issues grabbing them at the current size, the "hitbox" seems to be quite small

**Comment by devernay** [comment]
This issue was moved to NatronGitHub/Natron#242
