### ISSUE TITLE
PyPlugs nodes color.

### ISSUE THREAD

**Issue by fabiof17** [MrKepzie/Natron#1740]
After being exported, PyPlugs don't retain their node color. It may be due to the fact that they are scanned before the GUI is being instanced. That may sound of a small importance, but it would be nice to have them to have their own color, like all the other nodes.

**Comment by devernay** [comment]
if you give me he python command to change a node's color, I'll gladly add it.

**Comment by devernay** [comment]
(I don't think there is one, but maybe I missed it)

**Comment by fabiof17** [comment]
NatronEngine.Effect.setColor(*r*, *g*, *b*)

Set the color of the node as it appears on the node graph. Note that
calling this function will in background mode will do nothing and should
not be used.


http://natron.readthedocs.io/en/master/devel/PythonReference/NatronEngine/Effect.html#NatronEngine.NatronEngine.Effect.setColor



It works when use in Natron in the Script Editor, but not as a Callback.

2018-03-25 18:52 GMT+02:00 Frédéric Devernay <notifications@github.com>:

**Comment by devernay** [comment]
done!

**Comment by fabiof17** [comment]
THAT'S a real good news.
Thanks a lot.

2018-03-26 18:57 GMT+02:00 Frédéric Devernay <notifications@github.com>:
