### ISSUE TITLE
3.0:  Lot of spam at logs

### ISSUE THREAD

**Issue by bn0785ac** [MrKepzie/Natron#1742]
Commit: https://github.com/NatronGitHub/Natron/commit/14791a9bc8d732643471e90cce5c5a10b5592806

i got many ERROR 1282 in glEnd 

but i can work

**Comment by devernay** [comment]
I know, and if you can help find where it comes from you're welcome?Le 25 mars 2018 03:34, bn0785ac <notifications@github.com> a écrit :Commit: NatronGitHub/Natron@14791a9
i got many ERROR 1282 in glEnd
but i can work

**Comment by devernay** [comment]
fixed by https://github.com/NatronGitHub/Natron/commit/1760296f937a62e939685494c411025f51ead3c0 and https://github.com/NatronGitHub/Natron/commit/eca60eb646b9bda43c6b42b942d7f9981b5cbf0f

**Comment by devernay** [comment]
BTW, if you managed to compile 3.0, feel free to contribute
