### ISSUE TITLE
Speed up Natron by freezing postage stamps.

### ISSUE THREAD

**Issue by fabiof17** [MrKepzie/Natron#1743]
I've noticed that Natron updates frame stamps at every frame.
Wouldn't it be a clever a simple way to speed up Natron to have an option to actually freeze frame stamps. They would just display the first frame of the comp, instead of refreshing every frame stamp at every frame. It may not be significant when there are only 2-3 of them, but with like 20-30 reads or any node having the frame stamp option activated, that could make a significant difference.

Just an idea.

**Comment by devernay** [comment]
Can be done by just disabling the previews or using the turbo mode button
