### ISSUE TITLE
OCIO: Color space menu bug

### ISSUE THREAD

**Issue by ndeboar** [MrKepzie/Natron#1744]
### Problem

Using a OCIO config that does not use the default names for color spaces breaks the color space menus on the read/write node.

**Expected behavior:**
https://drive.google.com/open?id=16CfopimuHpFVYi_kLYHVqVO1CtTXhZIf

**Actual behavior:** 
https://drive.google.com/open?id=1Mwk6YBy5RTAqPH6T4PSExvRDosf2bpOp

The issue seems to be that Natron does not use the OCIO colorSpaces under Project Settings: LUT, where you set the defaults for the read nodes. 
https://drive.google.com/open?id=1fyqONcE7DZFNEE32rnbbfc_IKYMdkPue

### Steps to Reproduce

1. Use a OCIO config that does not have a color space named "sRGB", for example Blender Filmic 
https://github.com/sobotka/filmic-blender
2. Load a 8 bit image, like a PNG.

### Versions

* **Natron version/commit** 2.3.8
* **OS version:**  Windows 7

**Comment by devernay** [comment]
The LUT preferences are not colorspace specifications, these are just LUTs for compressing data on 8 / 16 bits and are not really used in most projects. The preference name is wrong, really.

Sorry, but if the config.ocio misses srgb, Natron won't make one for you. If you use an external config.ocio, you should know what you are doing.
BTW, the default OCIO config in Natron also has filmic.

**Comment by ndeboar** [comment]
Hey,

This is an acceptable OCIO workflow in Nuke. Nuke allows you to select default color spaces for various input types (linear/8bit/log/float) using OCIO color spaces, regardless of what they are named. 

For example:
http://help.thefoundry.co.uk/nuke/10.5/content/comp_environment/configuring_nuke/using_ocio_config_files.html

What do you define as 'you should know what your doing'? This is exactly how I ran things in Nuke, so I am not trying to reinvent the wheel. 

Ta,

Nick

**Comment by devernay** [comment]
Well, Natron isn't Nuke, sorry about that (but you can pay for Nuke if you prefer it - I get exactly $0 from developing and maintaining Natron, please keep that in mind).
In Natron those items in the preferences are just 1D LUTs, not color spaces, and they concern internal data types, not file data types : this has nothing to do with readers, just the fact that some OpenFX plugins may be able to process 8-bit only.

In Natron, the reader tries to do its best to guess the right colorspace from the OCIO config and the file type (eg PNG would be sRGB, whereas H.264 HD would be rec709).
If there's a colorspace called sRGB, then it will pick it for PNG.

I tried to make more clear what these settings are for in https://github.com/NatronGitHub/Natron/commit/94955f97e35d3a6105211f2fbeb30305126b4780
