### ISSUE TITLE
No Icon in window list (Linux Mint 18.3)

### ISSUE THREAD

**Issue by mihi4** [MrKepzie/Natron#1745]
Please ask questions ("how do I...?") on the [forum](http://forum.natron.fr), not by filing issues.

Make concrete suggestions for fixing the code ("here is a patch") by filing
a [pull request](https://github.com/MrKepzie/Natron/pull/new/master), not an issue.

### Problem

Describe the problem or suggestion here.

**Expected behavior:** To see the Natron icon in the window list (Linux)
![noicon](https://user-images.githubusercontent.com/37828365/37952620-af03526c-31a0-11e8-9050-00796bb0d93e.png)

**Actual behavior:** No icon shown

Looks like the file "natron_logo.png" is missing in 2.3.8's root directory. Since I had a backup of the 2.3.7 directory, after copying the file to 2.3.8, the icon is showing.

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

You may submit a link to any screenshots/videos that can be used to understand how to reproduce the issue.

### Versions

* **Natron version/commit** 2.3.8
* **OS version:**  Linux Mint 18.3

**Comment by devernay** [comment]
can you please be more specific? I have no problem on my system (Ubuntu 16.04)

- which version did you download (portable or installer)
- where did you install it?
- what was the full path of the missing file?

BTW, all the versions are archived on sourceforge in case you ever need an older version

**Comment by mihi4** [comment]
Hi, Frederic!
First, thx a lot for all the work you're doing on Natron, and sorry for being too unspecific.
- which version did you download (portable or installer
Linux installer, 64bit

- where did you install it?
/home/michi/bin/Natron2

-what was the full path of the missing file?
it's directly in the install root directory, /home/michi/bin/Natron2/natron_logo.png

It was missing in the 2.3.8 installation, but available in the 2.3.7.

I just backupped it to keep my plugins available, just in case... :)

**Comment by devernay** [comment]
This issue was moved to NatronGitHub/Natron#243
