### ISSUE TITLE
Write1 Error

### ISSUE THREAD

**Issue by legoruss1** [MrKepzie/Natron#1746]
when I go to render a 360 video mp4 as a mp4 after stabilizing it, I get an error: Write1: can only render RGBA or RGB components images
components image is currently rgb32f. Shot on a Nikon Keymission 360
TELL ME WHAT YOU NEED

**Comment by devernay** [comment]
ideally, a project that fails

**Comment by devernay** [comment]
@legoruss1 can you help and provide a sample project that fails?

**Comment by devernay** [comment]
This issue was moved to NatronGitHub/Natron#244

**Comment by legoruss1** [comment]
https://1drv.ms/u/s!AndYJsfTjc6Rlq1QNDhCRtrBirA1-Q here is a onedrive link to a sample video
