### ISSUE TITLE
Links break when Node is copied

### ISSUE THREAD

**Issue by CameraRick** [MrKepzie/Natron#1748]
### Problem

When making a copy of a Node, links (e.g. the used channels) break. The links don't work and I can also not unlink them anymore, they stay in the state from when the copy was made. It's not adjustable either, neither through Expressions nor UI

See here: https://youtu.be/FLiSgHZsOpM

**Expected behavior:** 
Links should be properly copied, or I should at least have the ability to unlink and relink again.

**Actual behavior:**
It breaks completely.

### Steps to Reproduce

1. Create two nodes, e.g. Blurs
2. Link the R channel selector of Blur1 to Blur2
3. Copy Blur2
4. See that Blur2_1 has no working R channel selection anymore

### Versions

* **Natron version/commit**: Natron 2.3.9
* **OS version:** Windows 10 Professional

**Comment by devernay** [comment]
probably won't fix this one

**Comment by devernay** [comment]
This issue was moved to NatronGitHub/Natron#245
