### ISSUE TITLE
Grade Node appears to lockup with large images 2.3.9

### ISSUE THREAD

**Issue by ThomasMorley-T3D** [MrKepzie/Natron#1750]
Please ask questions ("how do I...?") on the [forum](http://forum.natron.fr), not by filing issues.

Make concrete suggestions for fixing the code ("here is a patch") by filing
a [pull request](https://github.com/MrKepzie/Natron/pull/new/master), not an issue.

### Problem

Describe the problem or suggestion here.

Natron locked up when trying to preview or render a project with a Grade Node hooked up to a large image.

**Expected behavior:** [What you expected to happen]
Preview fine, render fine

**Actual behavior:** [What actually happened]

Locks up after random mount of frames.

 * If your problem is a crash in an official release/snapshot, please include verbose output from the application
 from a terminal if possible.  If you also submitted a crash report, indicate the CrashID if possible.
 
 * If you need to report a compilation issue, please create a [gist](https://gist.github.com)
 that contains the _full_ verbose build log.
 
 * If your problem is a crash in a build that you made yourself, please create a [gist](https://gist.github.com)
 that contains a _full_ backtrace.

### Steps to Reproduce

1. see video
2. [Second Step]
3. [and so on...]

You may submit a link to any screenshots/videos that can be used to understand how to reproduce the issue.

https://www.facebook.com/tommorleyoswego/videos/10214976160294236/?t=159

### Versions

2.3.9

* **Natron version/commit** (they can be retrieved from the About Window): 
* **OS version:** 
Ubuntu Studio 17.10 - verified on 2 machines.

**Comment by devernay** [comment]
I will need a sample project to look that up

**Comment by devernay** [comment]
@ThomasMorley-T3D can you send me a project that fails?

**Comment by devernay** [comment]
This issue was moved to NatronGitHub/Natron#246
