### ISSUE TITLE
2.3.10  gives errors

### ISSUE THREAD

**Issue by bn0785ac** [MrKepzie/Natron#1752]
Version: 2.3.10

Last safe version: https://github.com/NatronGitHub/Natron/commit/7da90f3f855d880572a9214445ba861a884a9132

Buddy commit (example)
https://github.com/NatronGitHub/Natron/commit/f61e5761875c135bbefebf19390b83063b54c0b7

```
Info: init.py script not loaded (this is not an error)
Info: initGui.py script not loaded (this is not an error)
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
Caught segmentation fault (SIGSEGV) from thread Thread (pooled)(0x7f2aa0008b10), faulty address is 0x7f2af5663a48 from 0x38

Parent is shutting down, bye...

```

Boost: 1.66
GCC: 7.3 (20180312)
Clang: 6
Kernel: 416

**Comment by devernay** [comment]
probably already fixed: https://github.com/NatronGitHub/Natron/commit/570fb054d840904125ae811e9913fd2113124566
