### ISSUE TITLE
Matrix 3x3 bug ?

### ISSUE THREAD

**Issue by fabiof17** [MrKepzie/Natron#1753]
### Matrix 3x3 bug ?

Nuke's 3x3matrix setup to :

-2 | -1 | -2
  0 | 0 | 0
  2 | 1 | 2

Needs to be setup like this in Natron, to get the same result :

 2 | 1 | 2
  0 | 0 | -1
-1 | -1 | -2

- Expected behavior :  To output the same result.

- Actual behavior :  Doesn't output the same result.

- Question :  Which one has an issue ?

### Versions

* Natron version/commit : *2.3.9*
* OS version : *Win/Linux*

**Comment by devernay** [comment]
I'll change it to behave like Nuukes
