### ISSUE TITLE
Docking a tab makes app to just quit

### ISSUE THREAD

**Issue by fabiof17** [MrKepzie/Natron#1755]
### Problem

Trying to grab a tab to dock it somewhere else makes Natron to just quit.

### Versions

* **Natron version/commit** : snapshot 2.3.10 (04-04-2018)
* **OS version**  : Linux ( CentOS 7 - Xfce )

**Comment by fabiof17** [comment]
Ok

Le jeu. 5 avr. 2018 à 08:24, Frédéric Devernay <notifications@github.com> a
écrit :

**Comment by devernay** [comment]
@fabiof17 did you test it?

**Comment by devernay** [comment]
This issue was moved to NatronGitHub/Natron#247
