### ISSUE TITLE
could you make a flatpak for natron?

### ISSUE THREAD

**Issue by chemel9** [MrKepzie/Natron#1759]
Hi, I really appreciate your work , is a good application

could you make a flatpak for natron?
in this way, users can install the application in any linux distribution

please.
thank you.

**Comment by devernay** [comment]
I can't (no time for this), but anyone who knows how to do this from a directory tree can give me the recipe, and I could integrate that in the build system

**Comment by devernay** [comment]
This issue was moved to NatronGitHub/Natron#251
