### ISSUE TITLE
Feature Request: Full GPU (CUDA) support

### ISSUE THREAD

**Issue by ElDirector** [MrKepzie/Natron#1760]
I have a 980Ti that I would like to be able to use to do some heavy lifting and processing.  Is GPU support like that on the horizon?  Currently Natron only sees my dual D700's on the Mac here at work (which are practically useless)

**Comment by devernay** [comment]
On which OS?
Is the 980Ti your main GPU (the one you use for your display)? Or is it a secondary card? This is probably an easy issue to fix, because places in Natron where the OpenGL context is created are easy to find.

**Comment by ElDirector** [comment]
It's only used for rendering and processing.  No displays are hooked up to it.  OSX Sierra.

**Comment by ElDirector** [comment]
It's only used for rendering and processing. No displays are hooked up to it. OSX Sierra.

**Comment by ElDirector** [comment]
Accidentally hit close and comment....  Sorry

**Comment by devernay** [comment]
I don't have a mac pro with 2 graphics cards. can you please tell me if "OpenGL Extensions Viewer" (free, Mac App Store) shows your card as one of the "Renderers"?

**Comment by ElDirector** [comment]
It only shows one of the D700's or Apple software renderer.

**Comment by devernay** [comment]
That means we cannot access it through OpenGL, but only cuda, and Natron does not yet support cuda

**Comment by ElDirector** [comment]
Good to know.  Thanks!

**Comment by devernay** [comment]
This issue was moved to NatronGitHub/Natron#252
