### ISSUE TITLE
 enable integration with Bountysource for this issue tracker?

### ISSUE THREAD

**Issue by WPFilmmaker** [MrKepzie/Natron#1761]
Synfig devs proposed this on Opentoonz here on github, I am copying their idea and ask for implementing such feature here too. AFAIK Natron is developed mostly by 1 person, therefore this would be useful to boost the development. If one user would want a feature he/she can add a small bounty to make t more attractive for devs. Please refer to: https://github.com/opentoonz/opentoonz/issues/1908 to have it integrated. +1 if you like the idea

**Comment by devernay** [comment]
Very good idea, but would it attract more developers? The bottleneck resource for the moment is (my) time, not money.

**Comment by WPFilmmaker** [comment]
@devernay I am not a coder so I don't know whether it will or not, but maybe it is worth a try? Synfig Studio has managed to attract a few occasional developers who claimed bounties, maybe it could work well for feature requests and simple tasks?Leaving you time for higher priority bugs?

**Comment by devernay** [comment]
This issue was moved to NatronGitHub/Natron#253
