### ISSUE TITLE
Hiding rarely-used parameters: live switching  between expert-normal-easy modes

### ISSUE THREAD

**Issue by devernay** [MrKepzie/Natron#1765]
There are many rarely used Natron parameters, and I think there should be a way to easily hide those, or even to switch to an easy mode where only essential parameters are visible.

All parameters and buttons in the GUI are concerned, as well as items in the Natron preferences. We are not talking about remodeling the GUI to make it look like AE or anything existing, but just about hiding parameters or buttons.

Please review all parts of the UI and preferences and give your thoughts about what should be hidden in the normal or easy modes.

After that, We will need help implementing it.

Anyone with some Qt knowledge can help on this one.

We will do that in RB-2.3, the current stable branch, and porting it to 3.0 will also require some work.

**Comment by ElDirector** [comment]
Overall, I don't the the interface is cluttered or confusing, with the exception of the viewer.  My suggestions are
Hidden in Easy Mode:
Viewer: Gain and Viewer Gamma, Proxy Mode, “When checked, the viewer will render the image in it’s entirety….”, Viewer inputs A, B and merge operation.

For normal mode, bring back the Gain and Gamma and Proxy

**Comment by CameraRick** [comment]
For me the viewer is unusably buggy when I don't render the whole image, so I activate it by default. Hiding what could be a quick solution to a beginners problem can be dangerous.

I also don't feel the interfacw is cluttered and buttons are there for reasons; if we get rid of two buttons not much space is saved after all. The gain/gamma sliders are somewhat essential I think; even AE has a gamma slider. And have you seen AEs viewer? It's also cluttered with buttons, and still people feel it's more accessible than Natron. I think dumbing down the UI is not the right way to achieve this

**Comment by devernay** [comment]
I was also talking about plugins. Don't you think some plugins have many rarely used parameters?

**Comment by CameraRick** [comment]
Definately, but that usually means I don't use them. Hiding those can just be frustrating while debugging an undesired behaviour.

The GUI is rather complex, I get that. But dumbing it down by hiding functionality that might cause issues can't be the solution IMHO. Because the same is true for "simpler" software like AE or Fusion, dozens of buttons you may simply not use

**Comment by devernay** [comment]
This issue was moved to NatronGitHub/Natron#255
