### ISSUE TITLE
replacement of images

### ISSUE THREAD

**Issue by vijayyadla** [MrKepzie/Natron#1769]
how do I replace the one image / node with another image / node.

When we are trying to replace one image with another image its getting Merge node (Ctrl+Shift+Mouse drag).  It is fine.  

When we use "Ctrl+Shift+Mouse drag" in Nuke, we can replace the images / nodes.

We should replace more images in Production level.  So without replacement option of images, we are not able to work on Natron.

My request is, is there any way to replace one image with another image without getting Merge node in Natron as in Nuke ?

Regards,
Vijay

**Comment by revast** [comment]
Wrong Repository.
All open issues were moved to https://github.com/NatronGitHub/Natron/issues
https://github.com/NatronGitHub/Natron is the official repository for the community-maintained version of Natron and all of its plugins.

**Comment by devernay** [comment]
closing, see https://github.com/MrKepzie/Natron/issues/1766
