### ISSUE TITLE
Reformat Node: Stop in render

### ISSUE THREAD

**Issue by vinavfx** [MrKepzie/Natron#1770]
When I make an animation from the outside of the frame until the image is completely in frame, the viewer stops and in the rendering it also stops, but that only happens when I add a reformat to the image,
with the Resize node this does not happen.

Natron version 2.3.14 Release.
![reformat](https://user-images.githubusercontent.com/40272695/47318065-74676c80-d621-11e8-90d4-5e9e010eb0c1.jpg)

**Comment by vinavfx** [comment]
![reformat](https://user-images.githubusercontent.com/40272695/47318113-96f98580-d621-11e8-8b13-b000d6d1bbf4.jpg)

**Comment by revast** [comment]
Wrong Repository.
All open issues were moved to https://github.com/NatronGitHub/Natron/issues
https://github.com/NatronGitHub/Natron is the official repository for the community-maintained version of Natron and all of its plugins.

**Comment by devernay** [comment]
closing, see https://github.com/MrKepzie/Natron/issues/1766
