### ISSUE TITLE
Roto Paint 64 brush limit

### ISSUE THREAD

**Issue by solloron1** [MrKepzie/Natron#1772]
Please ask questions ("how do I...?") on the [forum](http://forum.natron.fr), not by filing issues.

Make concrete suggestions for fixing the code ("here is a patch") by filing
a [pull request](https://github.com/MrKepzie/Natron/pull/new/master), not an issue.

### Problem

Describe the problem or suggestion here.
When using the rotopaint node you are only able to use 64 brush objects under the layer. After that they will not appear anymore.

**Expected behavior:** [What you expected to happen]
To continue painting after 64 brush objects

**Actual behavior:** [What actually happened]
At brush object 65 it does not appear on the frame and does not appear at render time either

 * If your problem is a crash in an official release/snapshot, please include verbose output from the application
 from a terminal if possible.  If you also submitted a crash report, indicate the CrashID if possible.
 
 * If you need to report a compilation issue, please create a [gist](https://gist.github.com)
 that contains the _full_ verbose build log.
 
 * If your problem is a crash in a build that you made yourself, please create a [gist](https://gist.github.com)
 that contains a _full_ backtrace.

### Steps to Reproduce

1. [First Step]
Load video and add a rotopaint node
2. [Second Step]
Start painting on the frames. After you get 64 brush objects the paint will not appear anymore. Nor display on playback
3. [and so on...]

You may submit a link to any screenshots/videos that can be used to understand how to reproduce the issue.

### Versions

* **Natron version/commit** (they can be retrieved from the About Window): 
* **OS version:** 
Natron custom build for Arch Linux Kernel 4.20
& Natron 2.3.4 Windows 7 Pro

**Comment by devernay** [comment]
If you are drawing that many strokes, you should probably switch to using gimp/photoshop and export the bitmap.
Is it a static drawing, or do you draw on video?
Rotopaint is very expensive in terms of rendering (behind rotopaint is a hidden graph with lots of Merge nodes).
So if your brush strokes are not animated, use the right software.
A workaround if you still want to use rotopaint is to daisy-chain rotopaint nodes.

**Comment by devernay** [comment]
dup of https://github.com/NatronGitHub/Natron/issues/321
