### ISSUE TITLE
Can't load MP4 

### ISSUE THREAD

**Issue by jsimmonstx** [MrKepzie/Natron#1773]
Linux Mint 18.04
Natron v2.3.14 Release

Does Natron support MP4 file reading? I can't get any mp4 to load.

**Comment by devernay** [comment]
It may or may not. MP4 is a container, and the codec can be anything. you should run `ffprobe` on your file and port the result here. Note that even so, the video file reader has some issues with some formats. ReadFFmpeg has to be rewritten, this is a longstanding issue.
If you can cut a very short excerpt (a dozen of frames should be OK) and attach the file to this issue, this will definitely help.

**Comment by devernay** [comment]
see also https://github.com/MrKepzie/Natron/issues/529

**Comment by devernay** [comment]
closing this issue. Please follow the instructions above and post an issue in https://github.com/NatronGitHub/Natron/issues
related issues: https://github.com/NatronGitHub/Natron/issues/241 https://github.com/NatronGitHub/Natron/issues/231 https://github.com/NatronGitHub/Natron/issues/148
