### ISSUE TITLE
Error while creating node fr.inria.openfx.WriteFFmpeg 

### ISSUE THREAD

**Issue by binoysarker** [MrKepzie/Natron#1774]
Hello I am a beginner in Natron and I have installed Natron 2.3.14 from the software centre of linux mint 19.1 and installed this in my linux mint system. But when i create a write node and try to save this as mp4 format then it shows this error.

### Problem

Error while creating node fr.inria.openfx.WriteFFmpeg: Write2 error: writer was configured for unavailable codec.

**Expected behavior:** [I accept this should save the file]

**Comment by AnasR7** [comment]
> Hello I am a beginner in Natron and I have installed Natron 2.3.14 from the software centre of linux mint 19.1 and installed this in my linux mint system. But when i create a write node and try to save this as mp4 format then it shows this error.
> ### Problem
> 
> Error while creating node fr.inria.openfx.WriteFFmpeg: Write2 error: writer was configured for unavailable codec.
> 
> **Expected behavior:** [I accept this should save the file]

I have the same issues when I create a node writer.

**Comment by devernay** [comment]
Can you try with the official binaries we distribute (either 2.3.13 or 2.3.14)? I don't know who built that binary, but this is probably a packaging issue.

**Comment by AnasR7** [comment]
> Can you try with the official binaries we distribute (either 2.3.13 or 2.3.14)? I don't know who built that binary, but this is probably a packaging issue.

I use flatpak and is  2.3.14 version.

maybe is a flatpak issue?

**Comment by devernay** [comment]
Maybe @Sunderland93 can help with the flatpak issues?
@binoysarker are you using flatpak, or the binaries from github?

**Comment by Sunderland93** [comment]
It seems like Flathub's FFmpeg issue. @AnasR7 can you please test official binary?

**Comment by AnasR7** [comment]
> It seems like Flathub's FFmpeg issue. @AnasR7 can you please test official binary?

okay, got it.

**Comment by devernay** [comment]
closing, see https://github.com/MrKepzie/Natron/issues/1766
