### ISSUE TITLE
Error while creating node fr.inria.built-in.Write: No plugin capable of encoding mp4 was found.

### ISSUE THREAD

**Issue by dionaditya** [MrKepzie/Natron#1779]
I am beginner with natron. I have issue with error like this
Error while creating node fr.inria.built-in.Write: No plugin capable of encoding mp4 was found.

Natron 2.3.14
OS: manjaro 4.14

How I can fix this issue

**Comment by MattMadness** [comment]
I have this same issue and would like to know how to fix it.

**Comment by devernay** [comment]
ask here: https://discuss.pixls.us/c/software/natron/27
or post an issue here: https://github.com/NatronGitHub/Natron/issues
most probably, you are not using our binary distribution, so please test first with the binary releases that we distribute: https://github.com/NatronGitHub/Natron/releases

**Comment by MattMadness** [comment]
> ask here: https://discuss.pixls.us/c/software/natron/27 or post an issue here: https://github.com/NatronGitHub/Natron/issues most probably, you are not using our binary distribution, so please test first with the binary releases that we distribute: https://github.com/NatronGitHub/Natron/releases

I used the binary installer from the releases page and it worked great! Thanks for your solution!
