### ISSUE TITLE
NATRON write node error "file is not open"

### ISSUE THREAD

**Issue by donatoa** [MrKepzie/Natron#1782]
Please ask questions ("how do I...?") on the [forum](http://forum.natron.fr), not by filing issues.

Make concrete suggestions for fixing the code ("here is a patch") by filing
a [pull request](https://github.com/MrKepzie/Natron/pull/new/master), not an issue.

### Problem

Describe the problem or suggestion here.

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

 * If your problem is a crash in an official release/snapshot, please include verbose output from the application
 from a terminal if possible.  If you also submitted a crash report, indicate the CrashID if possible.
 
 * If you need to report a compilation issue, please create a [gist](https://gist.github.com)
 that contains the _full_ verbose build log.
 
 * If your problem is a crash in a build that you made yourself, please create a [gist](https://gist.github.com)
 that contains a _full_ backtrace.

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

You may submit a link to any screenshots/videos that can be used to understand how to reproduce the issue.

### Versions

* **Natron version/commit** (they can be retrieved from the About Window): 
* **OS version:**

**Comment by donatoa** [comment]
Can someone help me understand why NATRON write node keeps giving the error "file is not open"
when I try to write a .mov or any video files?

**Comment by devernay** [comment]
If you do not give us more information, we won't be able to help. Try writing frames instead of a video file first. Closing this issue, as it misses information. Feel free to resubmit one with more info
