### ISSUE TITLE
can not add Tracks (Tracker node)

### ISSUE THREAD

**Issue by ulluulluullu** [MrKepzie/Natron#1793]
Hello,

it's my second day using Natron (first experience with compositors) and I've stumbled about a problem with the Tracker Node that's seemingly mundane but I just can't figure it out.

I've been following a tutorial on how to stabilize videos using the Tracker node but after I read in the mp4 (gameplay video I recorded via GeForce Experience) file, put in the Tracker node and connect it to the video file, **I just can not add any tracks.**

When clicking on the addTrack tile nothing happens, the cursor does not change into the expected green rectangle and clicking in the viewer does not create a track.

Using the recommended shortcut CTRL+ALT+LeftClick does not work.

Adding a track via the little "+ tile" in the Properties Tab does indeed result in a track, I can not see it in the viewer though, nor am I able to use the trackNext functions for the following frames. Instead trying to use the trackNext function at this point results in crashing Natron.

So far I've rewatched the same tutorial video multiple times, as well as others, to see if I forgot something. I have tried to use multiple different mp4 files. I also have completely reinstalled Natron.
I've looked through all the posts on here containing the "Tracker" term but couldn't find the same problem/solution.
Not sure how to add logs or anything of the likes if needed. Feel free to ask for any further information. 
Would appreciate any help!

ullu

**Comment by devernay** [comment]
did you connect the viewer to the tracker node?

You should submit your bugs to https://github.com/NatronGitHub/Natron/issues

**Comment by devernay** [comment]
also see the explanation here: https://github.com/NatronGitHub/Natron/issues/744
