### ISSUE TITLE
Make a new color dialog

### ISSUE THREAD

**Issue by mifth** [MrKepzie/Natron#185]
Hello guys.

Nuke has powerful Color Grading feature to use negative values for color sliders. Thi is most usable feature for color correcting Black and White values. Could you add it to Natron too?
You can just add simple sliders from +1 to -1. That will be good enough.

Here is how it looks in Nuke. It's really powerful: http://i.imgur.com/vFlyyIu.png
here how it looks in Natron. No possibility to use negative values: http://i.imgur.com/jZkTl9d.png

If it will be added - color correction in Natron will be superpowerful.
As a proposal it could be like this in Natron: http://i.imgur.com/JxMU2wH.png

Thanks.

**Comment by nicholascarroll** [comment]
Can the new colour dialog also please have these advantages:
1. Can be left open and stay on top while still letting you use the rest of the application
2. Multiple colour dialogs can be open at once.

**Comment by manuelsongokuh** [comment]
@MrKepzie : 
i can add more information for [Qt library]? or you are interesting code in c++ and openCV? or use to Qt request?

**Comment by manuelsongokuh** [comment]
@MrKepzie 
it's possible spit code for widget for "Color_KnobGui" from file knobguitypes, this mean will be easy to change if dialog color will growths, right? file "color_knobgui" is big lines code..?

i dont know if will be good if add file *.ui for qt design or not?

other ask: can use it qt quick (qml) or avoid to use qt quick (qml)?

**Comment by manuelsongokuh** [comment]
see there is other Qt but is not color dialog but can read code for beautiful curve rgb ..but it's base example and can learn it and modify ok?

https://mega.nz/#!a5UkSYBK!nuDo7YZ3igkU_pm7vqINlUznDIYG5Ob52TO55A_M5RY

**Comment by devernay** [comment]
This issue was moved to NatronGitHub/Natron#80
