### ISSUE TITLE
OpenEXR multi layers

### ISSUE THREAD

**Issue by blackearth2014** [MrKepzie/Natron#20]
I have a blender openexr file with 3 layers of data.  How can I read those layers in to Natron.  The image infer button recognizes the layers but I can accessing.

**Comment by dgsantana** [comment]
Multi layer is buggy, just some of the layers appear, and can't access the normal RGBA.

**Comment by MrKepzie** [comment]
Please see https://github.com/MrKepzie/Natron/issues/962 , send us a sample exr file to reproduce the bug

**Comment by dgsantana** [comment]
Here it is. Change the .jpg to .zip
![plano_01_0000](https://cloud.githubusercontent.com/assets/2750212/10489206/f2302b10-7293-11e5-8d66-dc0a008e5681.jpg)
