### ISSUE TITLE
GroupNode Proposal

### ISSUE THREAD

**Issue by mifth** [MrKepzie/Natron#208]
Hello.

i have a  proposal to make a GroupNode. Blender and Houdini composers have such nodes. They are very useful. I can make a group of nodes and use them as one GroupNode. And the main feature is - i can make instances of entire group of nodes.

It's very powerful.
Nuke does not have GroupNode. But Blender and Houdini have it.

Here test video in blender: http://youtu.be/lnp1OApNX7Q

Here is explanation:
http://i.imgur.com/m6PZTe1.png
http://i.imgur.com/4P81BP4.png

And here how it can be in Natron:
GroupNode - http://i.imgur.com/hFPcdZa.png
Inside of groupNode (if we doubliclick at it) - http://i.imgur.com/5iyJOr5.png

**Comment by MrKepzie** [comment]
Already implemented for v1.1
