### ISSUE TITLE
CG Comping Feature Requests

### ISSUE THREAD

**Issue by mantissa-** [MrKepzie/Natron#234]
Hi,

Just noticed a few basics I use a lot in my workflow seem absent, so i thought I'd make a quick list.
I'm sure some of them might have already been mentioned, this is just my two cents.

- Hue Shift / Correct Node
- Glow
- Blur
- Ability to save a collection of nodes as a tool for re-use
- Select in preferences which directory to use for disk cache / limit cache size
- Ability to change interface font sizes (They're a bit on the large side right now)

Cheers,

M.

**Comment by MrKepzie** [comment]
So far everything is implemented from the original request, closing.

**Comment by mifth** [comment]
Sorry, Glow and HueShift are implemented too?

**Comment by devernay** [comment]
Doesn't HSVTool cover hueshift?

**Comment by mifth** [comment]
@devernay HueShift works like Curves. Based on Hue - we can change saturation/lightness and other stuff. This is very usable tool in video composing.

In nuke it looks like this: https://i1.creativecow.net/u/61655/lookfamiliar.jpg
