### ISSUE TITLE
Sprite Sheets support Proposal

### ISSUE THREAD

**Issue by mifth** [MrKepzie/Natron#238]
Hi devs.

I have one ineteresting proposal to support Spritesheets. They can be usefull for Games video promotions. To create a video promotion using game content. Sprite sheets are heavily used in games.

It would be cool if a Reader can use its animations.
http://i.imgur.com/0nkxpKA.png
http://i.imgur.com/eIm0CSG.png

Sprite sheets use 1024, 512, 256, 2048 pixel sizes.

**Comment by devernay** [comment]
should be a plugin (the inverse of a ContactSheet plugin, actually)
