### ISSUE TITLE
Tracker Offset

### ISSUE THREAD

**Issue by mifth** [MrKepzie/Natron#256]
Hello.

This is a question about offset for the tracker. Nuke has cool feature to offset the tracker. But i can't find such a feature in Natron's tracker. 
Do we have it? Or could we add the offset in future?

Here is simple demo of the Nuke's Tracker Offset. http://youtu.be/FrTbh-aZzmo
This feature heavily usable in production to get right result when target moves away from the screen. We can just retarget with offset and continue tracking.

In Nuke the offset will be made with Ctrl+LeftClick.

Thanks.

**Comment by MrKepzie** [comment]
Implemented
