### ISSUE TITLE
Matte Overlay: Request

### ISSUE THREAD

**Issue by blackearth2014** [MrKepzie/Natron#274]
Can we get a matte overlay feature in the channel display bar?

**Comment by devernay** [comment]
Can you be more specific? What should it do, what should it look like?

**Comment by blackearth2014** [comment]
This is another photoshop feature to quickly see a mask that was selection by showing RED. It is not needed now as I got to learn Natron better. I can just press A for alpha. Job done.

**Comment by MrKepzie** [comment]
Implemented
