### ISSUE TITLE
Random Value looped Generator Node: Request

### ISSUE THREAD

**Issue by blackearth2014** [MrKepzie/Natron#294]
There are many times I use the roto node to mask out shapes, letters and other artwork for animation. It is very time consuming to generate a believeable random motion on the X&Y axises. Can we get a random value generating node to create a looped random motion for any transform node that is connected to a ReadOIIO node or roto shape.  

It will be nice if same node can be used also generate looped random colors for a grade node.

**Comment by MrKepzie** [comment]
You can write expressions in the curve editor (or for parameters) using random() to create believable motion.

**Comment by blackearth2014** [comment]
Okay. Now all I need now is to learn how to write expressions.

**Comment by MrKepzie** [comment]
http://natron.readthedocs.org/en/workshop/paramExpressions.html

**Comment by blackearth2014** [comment]
Big thanks.
