### ISSUE TITLE
Tile Node: Request

### ISSUE THREAD

**Issue by blackearth2014** [MrKepzie/Natron#295]
Can we get a Tile Node that will generate an array of images in a row, column or both? When merging multiple artworks together, I would like to be able to create a repeated image(s) of merged images.

**Comment by adallafontana** [comment]
I know that is not a final solution but for now can be a possibility:
![screenshot from 2015-03-09 20 13 31](https://cloud.githubusercontent.com/assets/8054856/6562432/648099d6-c699-11e4-8c71-aa84eb912590.jpg)

Code for SeExpr:

R=fmod(u, 1/4);
G=fmod(v, 1/4);
color=[R,G,0];
color

The scale UV on STMap will be 4, ....for 16x16 tiles: 1/16   and scale 16.

I hope will be in the future assign some custom widget for control the value outside the SeExpr.

**Comment by olear** [comment]
I can probably make one, please list features :) (what you would like to control, be realistic ;) )

**Comment by blackearth2014** [comment]
I only want to take an image and have control to repeat it in columns, rows or both at the same time. I would like the ability to space the tiles images with alpha channels in both directions. For example, I have multiple trees and foliage to comp together in an image and want to generate many at a time without using an overflow of transform nodes to do it.

**Comment by olear** [comment]
Ok, will make a test plugin later tonight.

**Comment by blackearth2014** [comment]
Good looking

**Comment by olear** [comment]
Ok?
![magicktile](https://cloud.githubusercontent.com/assets/7461595/7220066/2618c622-e6bb-11e4-8977-e0ad6df82158.png)
https://github.com/olear/openfx-arena/commit/fbe0813bacb53f0faf8e19a839fbcf952b90e2c1

**Comment by blackearth2014** [comment]
You did it. Big Thanks.

**Comment by olear** [comment]
>This would be very useful. Being able to have the tiles flip and mirror (controllable) would also be good.
Bonus: take the images from a folder, so that more than one can be tiled at the same time - Ordered Alphabetically or randomly, or in a row/column pattern.

Still wanted?

Flipping the tiles should not be a problem, but how do you want it?  Using images from a folder should also be doable (alphabetical, if you want a pattern just rename the files(?)).

**Comment by blackearth2014** [comment]
Do it all if you can.

**Comment by sozap** [comment]
Hello,
If that's not too complicated an option as an integer to time-offset trough the sequence would be handy to make some contact sheet...

ex :
if set on 0 , it's like the current behaviour...
if set on 1 , the first title would be the current frame, the second current frame + 1 , third = cur frame +3.
if set on 2, first title = cur frame , second = cur frame + 2
ect...

that's just a suggestion !

**Comment by olear** [comment]
Noted, will do some more testing with the Tile plugin tomorrow.

**Comment by olear** [comment]
Got some free time....
![screenshot-1](https://cloud.githubusercontent.com/assets/7461595/7785800/f06daa4a-01a1-11e5-8149-205b2f19dafb.png)

https://github.com/olear/openfx-arena/commit/4418457e4cd731aabb3cf9c4d9cc1efb30de1902

May still need some work, but the basics is there.

**Comment by sozap** [comment]
That's great ! 
thank you very much, I'll test it when a build is ready !

**Comment by olear** [comment]
I'm not going to do a build just yet, but if you are on Linux, you can build from trunk and test:
```
git clone https://github.com/olear/openfx-arena
cd openfx-arena
git checkout trunk
sh deploy.sh
```
Copy Arena.ofx.bundle-VERSION/Arena.ofx.bundle to /usr/OFX/Plugins or <some path>/Natron/Plugins.
