### ISSUE TITLE
Wand Mask Node: Request

### ISSUE THREAD

**Issue by blackearth2014** [MrKepzie/Natron#301]
I was doing a project with Digital Fusion today and I notice a node called wand.  It works like the color selection tool in photoshop and gimp. The node allows you to pull certain range of mattes that are not possible using general chromakeyers. See the attached screen capture.  The right side of the photo shows the node result and panel property operators.

![wandmasknode](https://cloud.githubusercontent.com/assets/7956901/4858571/dc26e51e-60df-11e4-972f-afbdc304231f.jpg)

**Comment by devernay** [comment]
What are the parameters/inputs to that wand node? Is there an online doc for that node?

**Comment by blackearth2014** [comment]
No documentation that I can find. It was a like the wand tool in Photoshop that allowed you to do a selection mask. The best way I can think of its operation in Natron is developing a hybrid between HSVTool and Photoshop Wand Selection Tool.

![wand_no_background](https://cloud.githubusercontent.com/assets/7956901/8828165/c1a875b4-305e-11e5-96ce-6b617fcc82d8.jpg)

**Comment by blackearth2014** [comment]
Fred,

With the HSVTool with the Src Analysis Rectangle node feature in Natron, The Wand request is no longer needed or necessary. So I cam closing my request.
