### ISSUE TITLE
MathCompositingNode-with custom widgets

### ISSUE THREAD

**Issue by adallafontana** [MrKepzie/Natron#304]
I try to explain what I would love to have in a compositing software.
First: the basic compositing is simply a mathematical operation apply to pixel: +-*/
the input image is mapped to a uv space (someone call xy).
This one is only an example, I used the channel color with same operation + and - (...with clamp, tnx for this new essential node) for "despill" a green color, I use a similar in Nuke/Shake/Blender.
Shuffle Div Channel-->Operations-->Shuffle Union Channel
![despill](https://cloud.githubusercontent.com/assets/8054856/4875573/9ed9b93c-629e-11e4-9812-59557df1e135.jpg)
All those nodes present in this composition are coded on RendermanSL, OSD, GLSL,..... in simply a bit of line code, exclude the input/output just two:   

float4 color = tex2D(InputSampler, uv);     #input pixel/sample image map to uv 

float mask = clamp(color.g-mix(color.r, color.b, 0.5), 0, 1);
color.g = color.g-mask;
     
return color;      #array output color[R,G,B,A]

I have created this for my Lighrworks custom node (HLSL PixelShader).
RSL, OSD, GLSL,..... have also more functions, sin(), cos(), abs(), sqrd(),.... with little difference about language; eg. random() someone call rand() others rnd() and so on, but basically really similar.
Division on channel can be an array like color.r, color.g, color.b, color.a or
color[0],color[1],color[2],color[3], etc....
So now, what I ask?
A "super" node with the possibility of insert a compositing via math for simplified the tree nodes or create a macro or custom effects (....without compile OXF plugin).
With the possibility of mapping image on deformed uv you can simple create a Tile effect or Lens deform, noise warp, Blur......
![seexpr](https://cloud.githubusercontent.com/assets/8054856/4875582/ecf43778-629e-11e4-829f-058c33205c95.jpg)
On Tuttle plugin exist a node call SeExpr.
SeExpr is a powerful library created from Disney for parametric noise texturing and more, more, more.
In Tuttle SeExpr you can generate nice noise fx and gradients animated thru time/frame and more stuff and compose on layers via math operation.
For now you don't  have a custom widget for controll $var on code, I ask this one at the developers of Tuttle.
SeExpr could be the way for have what I ask but there is a big problem,
SeExpr don't have the possibility for now (....master branch) of the manage of pixel/sample images. 

Is it only on my fantasy, or there is a possibility that create this "super Node".
On Autodesk Composite(Toxik) was present a similar way, Shake and Nuke thru custom widgets and code have too (...not like I would love).

**Comment by adallafontana** [comment]
>You’re just asking for an expression node much like in Nuke to operate on pixels. Once python scripting will be available we could do easily such a node to operate on the image directly.

I'm not 100% sure but I don't believe is possible now manage image RGB/UV with that version of Natron Python, I'm here now to ask you a Color Expression Node that is more close to my idea and to my first request of this thread.

**Comment by devernay** [comment]
See also https://github.com/tuttleofx/TuttleOFX/issues/355

**Comment by MrKepzie** [comment]
implemented
