### ISSUE TITLE
Masks: downstream injection: request

### ISSUE THREAD

**Issue by blackearth2014** [MrKepzie/Natron#308]
In nuke if you connect a roto node to a mask input, you have the ability to inject that mask downstream in the script.  These feature minimizes the to run long pipes and constant scaling up/down to connect masks or even duplicate masks nodes.

**Comment by MrKepzie** [comment]
Ok now that multi-plane is implemented, do you still think that this 'inject' feature is useful ? I read everywhere that is really optional and rarely used

**Comment by blackearth2014** [comment]
No, not at all.

**Comment by MrKepzie** [comment]
So we close it then ?

**Comment by blackearth2014** [comment]
when will the multi-plane node be available?

**Comment by MrKepzie** [comment]
It’s called the Shuffle node

**Comment by blackearth2014** [comment]
I only see the basic shuffle node parameters. I must be missing that snapshot for the updated multiplane features.

**Comment by MrKepzie** [comment]
You need to have multi-layered EXR files in input to see them in the shuffle node.

**Comment by blackearth2014** [comment]
I just realized that. I just experimented with one. But I am not able to see my other channels when I switch them in the shuffle node, nor in the layer channel under the viewer tab. See attached image. Am I doing something wrong. It is Blender's Multilayer file.

![screen shot 2015-03-16 at 4 30 11 am](https://cloud.githubusercontent.com/assets/7956901/6662734/472ac8a6-cb95-11e4-9e40-c4e1a0499447.png)

**Comment by blackearth2014** [comment]
I did another comparison with Nuke with the same setup. see attached images for references.

![screen shot 2015-03-16 at 4 38 48 am 2](https://cloud.githubusercontent.com/assets/7956901/6662842/9f8c3a10-cb96-11e4-893b-03eb5315ab61.png)

![screen shot 2015-03-16 at 4 38 48 am](https://cloud.githubusercontent.com/assets/7956901/6662843/9f9188ee-cb96-11e4-991c-15d6de739d5f.png)

**Comment by MrKepzie** [comment]
Please send me your sample file, there might something going wrong because your workflow seems correct

**Comment by adallafontana** [comment]
Omar in your screenshot seem that the alpha in Nuke is B  in Natron the alpha is 1.

**Comment by blackearth2014** [comment]
This Natron-snapshots-1d526ae5db80dcea45feb8a439217e6d40e88f5d fixed the problem. Thanks.

**Comment by blackearth2014** [comment]
Will Natron's merge node get this multi-plane feature as well. Nuke's merge and shuffle nodes has this feature.

**Comment by MrKepzie** [comment]
I don't think so, only shuffle should be needed
