### ISSUE TITLE
Roto Paint Node : Request

### ISSUE THREAD

**Issue by Montaire** [MrKepzie/Natron#309]
Roto Paint Node is something like Photoshop for movies.
It is really useful for small adjustments ,object removal,  and matte correction.
The fallowing video explains pretty well its functionality:
https://www.youtube.com/watch?v=2gYDb494YW4

**Comment by MrKepzie** [comment]
Please see https://github.com/MrKepzie/Natron/issues/35, it will probably make it for 2.0
