### ISSUE TITLE
TextOIIO Displays Incorrectly On Zoom In

### ISSUE THREAD

**Issue by elveatles** [MrKepzie/Natron#311]
I just downloaded 1.0 RC3 for Windows 64 bit.
Trying to place text (TextOIIO) when zoomed in shows obvious visual bugs. Either the text is in the wrong place, it's stretched and repeated, or it's not even visible.
Here's an example:
![natron-text-bug](https://cloud.githubusercontent.com/assets/1939423/4962298/182fa7ce-66dc-11e4-975d-5685135f54c0.jpg)

**Comment by olear** [comment]
Seems to work here (CentOS 6.6+Natron 1.2.1+openfx-io latest), I don't get any artifacts when zooming.

**Comment by MrKepzie** [comment]
You have to compile with kSupportsTile = 1 (at the start of the OIIOText.cpp file)

**Comment by olear** [comment]
Ahh, ok.

**Comment by olear** [comment]
Hmm, rebuilt in release mode with #define KSupportTile 1, didn't see any artifacts. Also rebuilt in debug mode, looks ok there as well. Maybe I'm doing something wrong, sorry for the noise if this is a known bug.

**Comment by MrKepzie** [comment]
When zooming in/out you should see the text incorrectly changing scale, don’t you ? Nobody changed the code since it was detected so I doubt it is fixed

**Comment by olear** [comment]
Yeah, didn't notice due to cache. I see a minor scale change when zooming.

**Comment by olear** [comment]
Noticed that I have the scale issue in https//github.com/olear/openfx-magick as well, I also forked OIIOText (https://github.com/olear/openfx-test) and replaced OIIO with Magick, still scale issues.

**Comment by olear** [comment]
Only happens if Viewer != 100%

If Viewer is 100% when adding OIIOText or MagickText then I have no scaling issues when zooming.

**Comment by MrKepzie** [comment]
This is because of the render scale parameter. There must be something not taking the render scale into account somewhere

**Comment by olear** [comment]
If I set renderscale to 0 in plugin, then it works in Natron.

**Comment by olear** [comment]
Build with renderscale disabled: https://github.com/olear/openfx-arena/releases/tag/MagickText-v1.1

**Comment by MrKepzie** [comment]
TextOIIO is going to be removed in v2 Release in favour of the text plug-in(s) in openfx-arena
