### ISSUE TITLE
Blender like Back Drop:Request

### ISSUE THREAD

**Issue by Montaire** [MrKepzie/Natron#317]
Blender can display its viewer node in the "NodeGraph"'s background.
It would be a really useful, because screen space is just never enough and even nuke lack this ability.
![backdrop](https://cloud.githubusercontent.com/assets/9551575/4981578/5d5d1c16-690a-11e4-8c30-678bc9c7bc46.PNG)

**Comment by manuelsongokuh** [comment]
@MrKepzie 
this ![image ](https://cloud.githubusercontent.com/assets/4058448/4984585/49e92a92-6925-11e4-98ad-0f6d0d2834d4.png)

is very COOL perfect for Natron target professional compositor!
incredible!!!

i hope natron like that...UAO....
but i dont know if will does in feature...?
i dont know, but  decisione is MR KEPZIE creator of natron..
:+1:

**Comment by olear** [comment]
personally I don't like the new Smoke interface, maybe I'm too conservative ..... :)

**Comment by manuelsongokuh** [comment]
@olear 
i like because is clear large GUI, but not "copy" smoke, but give me a think different, i'm nut sure for natron.. need to test test if GOOD or problem GUI space ok?

i need to ask to change graphics design for natron, because actual is bad color,like contrast too, there is not sweet and calm for my eyes..
example background of viewer is BLACK it's total bad like aggressive..need gray-dark like as lightweight, but before i need creare a concept for design UI for natron (color, style) not graphics (icon, design) but i need free time for report ok?

but smoke is not BAD, very GOOD because have all tools in one viewer this is not BAD ok?

**Comment by olear** [comment]
I like the "standard" composite UI, like in Shake, Nuke etc. Moving away from that is not what I prefer, it would also alienate users from other comp software.

But, this is a discussion for a later version... :)

**Comment by MrKepzie** [comment]
This should definitely be an option that can be switched off. Transparent widgets can be a pain to work with. We could propose specific controls that the user can choose to be overlayed onto the viewer

**Comment by olear** [comment]
As long as it's optional, no problem.

**Comment by blackearth2014** [comment]
Thats is a good Idea.

**Comment by manuelsongokuh** [comment]
hello i'm back here, see screenshot natron actual:
![crop2](https://cloud.githubusercontent.com/assets/12126929/8696689/ca4dd170-2aee-11e5-90a9-a27eb1191df1.png)

zoom 
![crop](https://cloud.githubusercontent.com/assets/12126929/8696695/d52cc54c-2aee-11e5-93e9-536b12ae4017.png)

design graphical is not good..
need fix it.. see my example design base of natural natron:
![image10](https://cloud.githubusercontent.com/assets/12126929/8696706/0154dfce-2aef-11e5-92d0-c20dc9f4cff8.png)
![crop1](https://cloud.githubusercontent.com/assets/12126929/8696710/07472b62-2aef-11e5-815c-b3970edc4119.png)


see compare:
![crop2](https://cloud.githubusercontent.com/assets/12126929/8696689/ca4dd170-2aee-11e5-90a9-a27eb1191df1.png)![image10](https://cloud.githubusercontent.com/assets/12126929/8696706/0154dfce-2aef-11e5-92d0-c20dc9f4cff8.png)
![crop](https://cloud.githubusercontent.com/assets/12126929/8696695/d52cc54c-2aee-11e5-93e9-536b12ae4017.png)![crop1](https://cloud.githubusercontent.com/assets/12126929/8696710/07472b62-2aef-11e5-815c-b3970edc4119.png)

**Comment by manuelsongokuh** [comment]
there are error design:
![need-cancel-1](https://cloud.githubusercontent.com/assets/12126929/8696989/9c6a9790-2af1-11e5-94f1-b3d7e27e6e1c.png)
![crop4](https://cloud.githubusercontent.com/assets/12126929/8696992/a61efc68-2af1-11e5-9ee1-0dda2128ce41.png)

**Comment by nicholascarroll** [comment]
I like this too: maybe overlay the nodegraph over the viewer and use a mode keybinding to switch between them.

**Comment by devernay** [comment]
This issue was moved to NatronGitHub/Natron#82
