### ISSUE TITLE
AJA, Matrox and Black Magic Design

### ISSUE THREAD

**Issue by blackearth2014** [MrKepzie/Natron#32]
Will there be in far future versions to support companies like AJA monitoring hardware and converters.

My NLE such as Editshare Lightworks supports them and I will be Natron as the Helper App. It would be nice if I can monitor through the same hardware.

**Comment by cbenhagen** [comment]
Seems like @blackearth2014 was talking about using an AJA, Matrox or BMD device to look at Natrons output right?

But processing live input form such a device could be very interesting too. GStreamer handles BMD devices very well if that helps.

**Comment by MrKepzie** [comment]
I was thinking about it too.
With @devernay we have an idea for a live reader node and more generally a live mode for Natron. This would not require much work to do.

**Comment by cbenhagen** [comment]
Oh these are awesome news! Sadly i do not have any C++ skills (yet). But i could help with python and packaging, building or testing stuff.

I have access to an AJA Io XT, BMD UltraStudio Mini Recorder and Monitor and a Magewell xi100dusb-sdi and diverse Cameras/Monitors to test I/O.

**Comment by blackearth2014** [comment]
I wasn't think of the live input processing, just playback so I see what lightworks sees. Now that we are on the subject, I can see great potential for a feature like than for realtime green screen keying and compositing. Thats if what you were talking about. The tv show "Once Upon A Time" or "Game of Thrones" has a similar processes were as the director can see how the green screen set of actors look in the composited environment while filming on set.

**Comment by devernay** [comment]
This issue was moved to https://github.com/NatronGitHub/Natron/issues/32
