### ISSUE TITLE
display bugs on menus

### ISSUE THREAD

**Issue by ghost** [MrKepzie/Natron#322]
There are weird artifacts above all menus (right clics menu, file menu... ).
![display_bug](https://cloud.githubusercontent.com/assets/9819909/5086378/e5ce28da-6f1b-11e4-9a04-aef67878f025.png)

I could not make a snapshot of it but i made a snapshot of the same problem happening on the splashscreen.

I am running Natron RC3 on Linux Mint 17 64 bits. Graphic card : Nvidia GT 590

**Comment by devernay** [comment]
This issue was moved to NatronGitHub/Natron#83
