### ISSUE TITLE
Depth Tools

### ISSUE THREAD

**Issue by blackearth2014** [MrKepzie/Natron#332]
Will it be possible to get a depth tool node when the Deep Data Nodes get developed. I want to covert a 2d image into a depth map greyscale.  Silhouettefx has this ability. You can see an example at http://www.silhouettefx.com/ under the S3D tab.

**Comment by devernay** [comment]
If that trick (ramp + guided bilateral) works, do you think It should be i tegrated as a single node (or maybe a pyplug)?

**Comment by blackearth2014** [comment]
I didn't get it to work. Maybe I was doing something wrong. A pynode should be sufficient.

**Comment by sozap** [comment]
the thing is, that depending on the image you want to convert depth to, the gradient need to be different. Also you may want to add masks, or tweak the grayscale image very differently.
So it's difficult to think of a general pyplug that can do the job on most cases.
Maybe that trick can be explain on a Natron Cookbook wiki next to the documentation, with cool tips and tricks were users can learn more on what to do with nodes rather that what nodes do...

**Comment by devernay** [comment]
This issue was moved to NatronGitHub/Natron#88
