### ISSUE TITLE
Viewer Grid Overlays: Request

### ISSUE THREAD

**Issue by blackearth2014** [MrKepzie/Natron#334]
Is it possible to get a grid overlay that is viewer independent. I am merging multiple imagines together on a surface and I like to use a grid to align and snap the images on screen. Photoshop and Gimp calls it show grid and snap to grid.

Thanks,
Omar

**Comment by devernay** [comment]
This feature request needs to be discussed a bit more. How useful would it be? What priority should we give to it?

**Comment by blackearth2014** [comment]
It is a request that can wait until you have time.

**Comment by devernay** [comment]
This issue was moved to NatronGitHub/Natron#84
