### ISSUE TITLE
Basic Enhancement

### ISSUE THREAD

**Issue by fossilsmedia** [MrKepzie/Natron#347]
Hi, 

I run a small studio in India, and I was very keen and was excited to see that something like this is initiated in vfx(composting vertical). 
Thanks for initiating things. Not only students or amateur but also we ,small young start ups and studio like us, also get benefits. 

However my team and I tried hands on natron to execute a small project and we found some discomfort at some places. As a matter of fact , we understand that you guys are developing all possibilities so we thought to share my suggestion and query. 

A) First i would like some development in roto feature 
   1) if we put a bezier point without dragging handles and close the shape 
      then we found we have to select and set manually to smooth points in   
      the middle option of right side toolbar and the can press "D" to 
      smooth , it would be great if something more handy can be develop or 
      please correct me if solution is already there and i am unaware. 

   2) Please add feature in roto bezier to adjust feather handle separately. 
      currently i found it is parented with bezier handle, by that i mean , 
      if we try to tweak feather handle to adjust motion blur then roto 
      shape also get change. 

B) Can you please add edge blur feature  ? 

C) Can you please add Basic grain feature with grain size and intensity   
   feature separate for RGB 

Again i would like to mention , i really see great possibility whit natron 
and have a lot expectation. 

Thanks for such a app. awaiting for some good responce 

Regards

**Comment by devernay** [comment]
Please post a separate issue for regrain, with links to all kinds odf documentation/ publications/ look-alikes

**Comment by devernay** [comment]
fixed by https://github.com/MrKepzie/openfx-io/commit/1caad63121652c1a157efd49405fe35d271a15fa
there is now a grain node (called SeGrain), which is very similar to NUke's Grain gizmo.

**Comment by devernay** [comment]
Just added the EdgeBlur pyplug based on EdgeDetect.
Should be in the next snapshot.
