### ISSUE TITLE
Roto Enhancement / Switch direction curve-feather

### ISSUE THREAD

**Issue by adallafontana** [MrKepzie/Natron#348]
I can manually change point-by-point but will be useful have a command for switch all point normal direction together.
Useful for "sub-inside" mask.

![screenshot_roto](https://cloud.githubusercontent.com/assets/8054856/5424167/71b36938-82e4-11e4-9456-cca6d81ddccc.jpg)

**Comment by devernay** [comment]
This issue was moved to NatronGitHub/Natron#91
