### ISSUE TITLE
Roto paint

### ISSUE THREAD

**Issue by blackearth2014** [MrKepzie/Natron#35]
Can the roto node get roto paint features for cloning and painting out objects.

**Comment by MrKepzie** [comment]
Just for the update, I have started working on it. I make no promise as to whether it will be included in Natron 2 though

**Comment by blackearth2014** [comment]
Take your time Alex. We are not going anywhere.

**Comment by blackearth2014** [comment]
By the way, will the roto paint implementations have a cloning capabilities and frame offset cloning as well?

**Comment by MrKepzie** [comment]
yeah

**Comment by MrKepzie** [comment]
And the strokes will be editable with controls points as bezier curves. They will also be able to be animated much like current shapes

**Comment by blackearth2014** [comment]
Cool Breeze

**Comment by MrKepzie** [comment]
This is up for testing
