### ISSUE TITLE
Request: Tonemap Node

### ISSUE THREAD

**Issue by mantissa-** [MrKepzie/Natron#362]
Hi,

I've been using a custom node in Nuke for a while that adds "Filmic" tonemapping to my toolset.
Is there anyway I could convert this Nuke version to a Natron compatible one?
I wouldn't mind trying to do it myself but really I don't know where to start. :)
My programming skills aren't the greatest, but I'd gladly put the time in to get it working.

Can anyone help / guide me through the process?
The original code for the Nuke & Fusion versions can be found here:
https://corona-renderer.com/forum/index.php/topic,1807.0.html

I've been using this for CG comping and it's a great tool to have, if I could get this working I'd seriuosly consider using Natron as my daily compositor for a lot of stuff.

Cheers!

**Comment by MrKepzie** [comment]
Hi, since now PyPlugs (equivalent of Nuke gizmos) are available, you can for sure reproduce this effect.

**Comment by mantissa-** [comment]
Hi,

I just had a look at the new nightly build.
How would I go about using this?

In Nuke I can just paste the code in the Node Graph and it makes a gizmo.
But I'm having trouble finding the right way to get started in Natron.

Cheers,

M.

**Comment by MrKepzie** [comment]
http://natron.readthedocs.org/en/workshop/groups.html

**Comment by mantissa-** [comment]
Missed that, thanks! :)
