### ISSUE TITLE
roto shape clamp issue

### ISSUE THREAD

**Issue by adallafontana** [MrKepzie/Natron#364]
![clamp_mask](https://cloud.githubusercontent.com/assets/8054856/5561725/01975d80-8ded-11e4-89b2-7a4e6bce7c5c.jpg)
If I use a multi-compositing rotoshape node with roto at opacity=1 all works right but if I modify the opacity I have a "clamped" effect on feather.
Ohter thing, there is not a quick way on roto node for invert mask, on Color value there is only a 3 (RGB) color not 4 (+Alpha) to invert this value.

**Comment by MrKepzie** [comment]
See https://github.com/MrKepzie/Natron/issues/377, it will be fixed by the enhancement
