### ISSUE TITLE
roto eye/hide/activated overwrite command issue

### ISSUE THREAD

**Issue by adallafontana** [MrKepzie/Natron#365]
on roto when you select a mask you have some option: opacity, feather, etc.... and Activated boolean on/off.
On list of roto shapes there is a icon "eye" for each shape, generally symbol of hide/un-hide but if I change state of this icon also the activated state change.
If you have many roto shapes on one node is useful hide some shape for edit other but without disable the hidden.

**Comment by MrKepzie** [comment]
I see, we'll see if we have time to add it at some point

**Comment by MrKepzie** [comment]
Implemented, the eye now just hide / show the overlay, but the "Activated" param, controls the render.
