### ISSUE TITLE
Viewer not resetting back to 100%

### ISSUE THREAD

**Issue by zendorf** [MrKepzie/Natron#366]
This is a reproducible bug on my machine under Win7/64bit using v1.0.0

When I fullscreen the viewer by pressing space and I use alt/middle mouse to zoom the display above or below 100%. If I then hit alt/1 to bring it back to 100%, it does this correctly but the percentage indicator stays stuck at the previous percentage, instead of displaying 100%.

Also a related problem, is that sometimes if I hit alt/1 the viewer doesn't resize at all until I then press middle button while over the view window, when it then pops back to 100%.

Note, this behaviour will also happen at times, when the viewer is not fullscreened.

**Comment by MrKepzie** [comment]
fixed
