### ISSUE TITLE
Better memory management ?

### ISSUE THREAD

**Issue by rcspam** [MrKepzie/Natron#368]
Thanks to code Natron,

My Linux station is a i7/920 2.6ghz / 6 Gigas of memory.
I know that Natron requires many memory, but if i want to compose a simple work with tga or tiff picture (15 Mo), zoom in and anime some texts on it (3 transform nodes, 2 merge nodes, 200 frames / 30 fps), the memory is rapidly filled.
The work becomes impossible.
If i use Nuke for the same work. half of the memory is enough all along this simple compositing.
Is there a parameter that i have forget or memory will be manage better in the future ?

Cheers and happy end of year !
Rcspam

**Comment by MrKepzie** [comment]
Hi,
We could add a "no-burn" mode where only 1 parallel frame would be rendered at a single time and a "make it burn" mode to turn on the heat.

**Comment by rcspam** [comment]
Hi MrKepzie,
Cool ! But what mode choose as default ? Unless an automatic setting for this mode depending of the memory amount !

**Comment by rcspam** [comment]
Oh I almost forgot; Happy New year to the Natron Developpers and to Natron on the best road as possible. ;)

**Comment by MrKepzie** [comment]
Happy new year to you too;) 
I've testing quiet a lot and I'm unable to reproduce those memory overflows.We'll ship v1.0.1 with some bug fixes, hopefully it solves the problem for you.
