### ISSUE TITLE
CurveEditor selection filter enhancement

### ISSUE THREAD

**Issue by adallafontana** [MrKepzie/Natron#375]
Personally I don't need a complex system of selection filter, just the possibility to visualize all animated node like now, plus the option to visualize only the selected nodes in NodeGraph.

Will be nice have also the possibility of alfa-numeric priority on list of animated node, so all merge/roto..../or-user-named nodes will be displaying together.

If just exist those possibility you have hide very well!!  :)

**Comment by MrKepzie** [comment]
You'd like a search field to filter some nodes in the curve editor ?

**Comment by adallafontana** [comment]
![curve](https://cloud.githubusercontent.com/assets/8054856/5602143/c985f2ba-9339-11e4-9800-398bfda6fe6b.jpg)
No, personally I think "search field" is useful only if you have hundred of node called similar with keyframe animation, not so probable on composition.
I mean simple have the correspondence between NodeGraph selection and CurveEditor selection, if I select 1 node on NodeGraph and in the curveeditor that node becomes yellow I'm happy just so, is more simple/fast looking for yellow that write in search field.

**Comment by fPaglia** [comment]
I would really appreciate a search filter indeed!!!
And a "show only selected node" option would be really cool too.
Of course all three condition:
any node, selected node, filtered data are very useful for different use
cases:

any node: to compare animation of each node (well to me this is more
important in a dopesheet viewer)
selected node: this will help focus on what to animate instead of anything
else
filtered curve: this would be extremely useful for motion graphic or search
a single specific curve think of a series of transform node with lot of
curve animated and you want just edit the x pos value... (this is an
invaluable plus)!!



2015-01-03 11:27 GMT+01:00 Alessandro Dalla Fontana <
notifications@github.com>:

> [image: curve]
> <https://cloud.githubusercontent.com/assets/8054856/5602143/c985f2ba-9339-11e4-9800-398bfda6fe6b.jpg>
> No, personally I think "search field" is useful only if you have hundred
> of node called similar with keyframe animation, not so probable on
> composition.
> I mean simple have the correspondence between NodeGraph selection and
> CurveEditor selection, if I select 1 node on NodeGraph and in the
> curveeditor that node becomes yellow I'm happy just so, is more simple/fast
> looking for yellow that write in search field.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MrKepzie/Natron/issues/375#issuecomment-68590184>.
>



-- 
Francesco Paglia
Vfx and Production Supervisor

mobile  +39 347.82.12.473
e-mail   f.paglia.80@gmail.com

**Comment by adallafontana** [comment]
Yes Francesco you are right, 
I have only consider the time of Alexander and I have "shooted low", to have a correspondence between Graph and Curve will be much just now.

**Comment by fPaglia** [comment]
Grazie Alessandro! :)

In fact I'm extensively using this filtering method in blender an it is
incredibly powerful!
 Il 03/gen/2015 13:39 "Alessandro Dalla Fontana" <notifications@github.com>
ha scritto:

**Comment by adallafontana** [comment]
...maybe one first step could be have the fold-all command just as context menu.
In Natron we displaying the curves only for the selected node each time, we have the confused interface only  when we have many node on Curve Editor and many of those unfold, is tedious fold all manually.
With "fold-all" or better "fold-all unselect" I "clear" the interface in one click, more or less is the same that have "show only selected node".
Merge this with the possibility to select node directly to the NodeGraph and we will have I think one big step, also because in NodeGraph we have the "find" command.

**Comment by MrKepzie** [comment]
I implemented a filter where you can just CTRL + F to just display filtered curves.

**Comment by adallafontana** [comment]
I saw but we must write exactly the entire name for filter the node, you should insert the same search field of the NodeGraph or the search Link with most rapid choise.
Other thing, is not possible insert a double click or other command for open the property of node direct from CurveEditor?
Now with double click unfold the node but IMHO don't have much sense, exist a arrow for that, instead a double click for display property on property pannel will be most useful.

thanks

**Comment by MrKepzie** [comment]
It filters all node names “containing” the filter.
I could add the double-click thing

**Comment by adallafontana** [comment]
The last snapshot is right now!
![right](https://cloud.githubusercontent.com/assets/8054856/5695084/25bb3ada-998f-11e4-8c9b-aee6fbf1919d.jpg)

On filter field I write just two letter and this filter the name that containing them + double click and I have the property from CurveEditor.

right, nice work.

tnx

alessandro
