### ISSUE TITLE
Copy/paste/link/import -> project/node to other | enhancement

### ISSUE THREAD

**Issue by adallafontana** [MrKepzie/Natron#376]
Last issue/enhancement of 2014 (europe-paris-rome). Happy new year. :)

In Natron there is the possibility of import/export setting node for create templates setting or copy and paste value between projects, good.
But if not just exist, will be nice have the possibility to import one project in  others, I have tried with simple copy/paste nodes but without result.

**Comment by MrKepzie** [comment]
You'd be happy to see that this is for a very near future: 
![screen shot 2015-01-02 at 12 35 52](https://cloud.githubusercontent.com/assets/4058448/5595762/f95ea798-927b-11e4-9814-5e48a01ce73d.png)

**Comment by adallafontana** [comment]
wow! ... 
Is it a node/linked project or a like/close Gizmo?
Is "User" (..that I see) the user widget like/close to Nuke?

**Comment by MrKepzie** [comment]
The group is exactly like Nuke gizmos. Except that the syntax will be Python 3 based.
The User parameters widget work exactly like in Nuke (you can make new parameters in a dialog, remove them and arrange them).

**Comment by fPaglia** [comment]
That's awesome!
Can't wait to use them!

2015-01-02 13:37 GMT+01:00 Alexandre Gauthier <notifications@github.com>:

> The group is exactly like Nuke gizmos. Except that the syntax will be
> Python 3 based.
> The User parameters widget work exactly like in Nuke (you can make new
> parameters in a dialog, remove them and arrange them).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MrKepzie/Natron/issues/376#issuecomment-68523954>.
>



-- 
Francesco Paglia
Vfx and Production Supervisor

mobile  +39 347.82.12.473
e-mail   f.paglia.80@gmail.com

**Comment by MrKepzie** [comment]
I close this as it has no point keeping it opened since we've already planned it
