### ISSUE TITLE
Roto Node Layers | enhancement

### ISSUE THREAD

**Issue by adallafontana** [MrKepzie/Natron#377]
On roto node I can divide shapes in layers, good.
Layers have 2 options: hive/disable, lock -> on/off for all shape in the layer, well.
Why not extend to layers also the others option of the shapes: blending, overlay color, color?
The system of roto will have more features, example:
one layer with "N" shapes "clear" in blending an other shape or other layer with contained "N" shapes.

**Comment by MrKepzie** [comment]
These features for layers would then change the config for all bezier inside that layer ? Like the lock ? I'm not sure this is a "much needed" feature

**Comment by adallafontana** [comment]
![layer](https://cloud.githubusercontent.com/assets/8054856/5602091/6b9dcfc2-9336-11e4-8bf7-541c8125ec2b.jpg)
Not, I mean have the layer option independent to the shape inside of it.
Eg. 1 layer with inside 2 shapes, 1 square and 1 circle that "clear" a part of it. 
After I create a 1 most big square in other layer, if I have only 1 shape I can simple blending clear, xor, etc... but if I want clear an ipotetic composition of multishape inside this layer I can't, because layer is not a group of nested shapes. I don't know if I explain what I mean.

Anyway is not essential for working in many case, is usefull only if you have 1 complex (..for complex I mean 3-4 shapes) composition of shape inside a layer that must clear other complex layer.

**Comment by MrKepzie** [comment]
We will add it, though it requires some changes to the internal rendering part of the Roto node. It will in the same time fix the bug https://github.com/MrKepzie/Natron/issues/364

**Comment by devernay** [comment]
Is this issue fixed?

**Comment by MrKepzie** [comment]
This is not an issue, to fix it we need to modify the roto so that each layer is backed up by a Merge node so that we could do composition of whole layers over other layers

**Comment by devernay** [comment]
This issue was moved to NatronGitHub/Natron#89
