### ISSUE TITLE
particle system

### ISSUE THREAD

**Issue by martialgallorini** [MrKepzie/Natron#378]
is there a way to integrate a particle system into Natron ?
Maybe sharing particle management from Blender ?

Just a thought, i just don't know if it is possible nor recommanded.

Thanks a lot for your nice work y the way ! I started using Natron in my everyday job along with Blender and seem very promising even if i am more in need for Motion Graphics tools than Compositing ones. But i am trying to use Natron whenever possible instead of After Effects.

Thanks again.

**Comment by MrKepzie** [comment]
There’s a Genarts plug-in called particleIllusion. You can try it out.
Anyhow, this is unlikely that we start now making a particle system, unless some developers are joining and focusing on that.

**Comment by MrKepzie** [comment]
This is a java library, Natron is C/ C++

**Comment by MrKepzie** [comment]
Unfortunately a particle system is very unlikely to be implemented by us (core developers) soon. 
However if you know talented C++ developers who want to contribute a particle system, then they are more than welcome to make it;)
I'll close this, we'll make sure to communicate if someday we decide to make one in our roadmap.
