### ISSUE TITLE
update tool do not update?

### ISSUE THREAD

**Issue by fPaglia** [MrKepzie/Natron#380]
Hi, 
I'm trying to use the maintenance tool in my ubuntu install but it says no new build since 22-12-2014.

I tried all the mirror present in the settings panel
Is it ok or am I missing something?

**Comment by MrKepzie** [comment]
The build machine is down and I’m not able to access it until monday.
I just started a local build that will make updates available, so you can have a new build until monday at least.

**Comment by fPaglia** [comment]
OK! :)
do you have  an url to add in the repolist of the maintenance tool?

2015-01-03 16:45 GMT+01:00 Alexandre Gauthier <notifications@github.com>:

> The build machine is down and I’m not able to access it until monday.
> I just started a local build that will make updates available, so you can
> have a new build until monday at least.
>
> > On 3 Jan 2015, at 16:40, Francesco <notifications@github.com> wrote:
> >
> > Hi,
> > I'm trying to use the maintenance tool in my ubuntu install but it says
> no new build since 22-12-2014.
> >
> > I tried all the mirror present in the settings panel
> > Is it ok or am I missing something?
> >
> > —
> > Reply to this email directly or view it on GitHub <
> https://github.com/MrKepzie/Natron/issues/380>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MrKepzie/Natron/issues/380#issuecomment-68598769>.
>



-- 
Francesco Paglia
Vfx and Production Supervisor

mobile  +39 347.82.12.473
e-mail   f.paglia.80@gmail.com

**Comment by MrKepzie** [comment]
Nope, it will be the same. It’s just that the build machine is not running indefinitely, I just triggered it once from my local computer but will not let it go for more than 1 build.

**Comment by fPaglia** [comment]
OK
thanks

2015-01-03 16:52 GMT+01:00 Alexandre Gauthier <notifications@github.com>:

> Nope, it will be the same. It’s just that the build machine is not running
> indefinitely, I just triggered it once from my local computer but will not
> let it go for more than 1 build.
>
> > On 3 Jan 2015, at 16:50, Francesco <notifications@github.com> wrote:
> >
> > OK! :)
> > do you have an url to add in the repolist of the maintenance tool?
> >
> > 2015-01-03 16:45 GMT+01:00 Alexandre Gauthier <notifications@github.com>:
>
> >
> > > The build machine is down and I’m not able to access it until monday.
> > > I just started a local build that will make updates available, so you
> can
> > > have a new build until monday at least.
> > >
> > > > On 3 Jan 2015, at 16:40, Francesco <notifications@github.com>
> wrote:
> > > >
> > > > Hi,
> > > > I'm trying to use the maintenance tool in my ubuntu install but it
> says
> > > no new build since 22-12-2014.
> > > >
> > > > I tried all the mirror present in the settings panel
> > > > Is it ok or am I missing something?
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub <
> > > https://github.com/MrKepzie/Natron/issues/380>.
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/MrKepzie/Natron/issues/380#issuecomment-68598769>.
>
> > >
> >
> >
> >
> > --
> > Francesco Paglia
> > Vfx and Production Supervisor
> >
> > mobile +39 347.82.12.473
> > e-mail f.paglia.80@gmail.com
> > —
> > Reply to this email directly or view it on GitHub <
> https://github.com/MrKepzie/Natron/issues/380#issuecomment-68598900>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MrKepzie/Natron/issues/380#issuecomment-68599000>.
>



-- 
Francesco Paglia
Vfx and Production Supervisor

mobile  +39 347.82.12.473
e-mail   f.paglia.80@gmail.com

**Comment by MrKepzie** [comment]
It has been updated, ring the bell if it doesn't work

**Comment by fPaglia** [comment]
just completed the update.
everything went fine

commit 3e0634ed7401ed053e9c849558ba86699fb8b99f.



2015-01-03 19:33 GMT+01:00 Alexandre Gauthier <notifications@github.com>:

> Closed #380 <https://github.com/MrKepzie/Natron/issues/380>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MrKepzie/Natron/issues/380#event-213690701>.
>



-- 
Francesco Paglia
Vfx and Production Supervisor

mobile  +39 347.82.12.473
e-mail   f.paglia.80@gmail.com
