### ISSUE TITLE
RunScript -> Error while creating node

### ISSUE THREAD

**Issue by adallafontana** [MrKepzie/Natron#382]
Was time that I would like ask for this one,
what is "RunScript".
Now if I click on this tool I have an error message: Error while creating node, but I can remember that tool worked in old beta.

p.s. ...nice the new icons ;)

**Comment by sozap** [comment]
Hi,

I've allready asked this question : https://groups.google.com/forum/#!searchin/natron-vfx/runscript/natron-vfx/m6bKX2ZWBno/w_WIaSeqHLAJ
It's to trigger external applications , to sum up ...

**Comment by MrKepzie** [comment]
fixed
