### ISSUE TITLE
Create PPA or request for debian repo. adding

### ISSUE THREAD

**Issue by mbnoimi** [MrKepzie/Natron#385]
May you please create a [PPA](https://launchpad.net/ubuntu/+ppas) for Ubuntu based distros OR make a request for adding Natron to debian repositories?

**Comment by MrKepzie** [comment]
We do not provide a PPA currently, we should make a request then. If someone could do it, that would help.

**Comment by devernay** [comment]
We don't have time for this, but I guess anyone with a little bit of Debian knowledge could help on this task. Anyone willing to help?

**Comment by olear** [comment]
I can probably make a debian package (I already made rpm support for CentOS/RHEL/Fedora, but didn't send the files upstream). Don't have any experience with ppa. I can also get Natron included in the BSD ports/pkgsrc, and probably Slackware and Archlinux.

Note that if/when Natron is included in mainstream distros you will get many different versions floating around, that could making the debuging harder. Also note that some distro only update software on major versions (if say Debian 8 includes Natron 1.2, then they will not include 2.x before Debian 9 (several years later). etc etc.

But again, this is something to be discussed after v2.

**Comment by olear** [comment]
We now support RPM/DEB on releases, will add repo support in a later version.

**Comment by olear** [comment]
We now have an APT repository.

Add repository:
```
sudo echo “deb https://downloads.natron.fr/Linux/releases/apt stable main” > /etc/apt/sources.list.d/natron.list
wget https://downloads.natron.fr/Linux/GPG-KEY
sudo apt-key add GPG-KEY
```

Update:
```
apt-get update
```

Install:
```
apt-get install natron
```

Only tested on Ubuntu, but should work on any distro with apt as package manager.

**Comment by Theverat** [comment]
Thanks for your work.
Two things:
* `sudo echo ... > ...` does not work, see e.g. https://serverfault.com/questions/540492/sudo-echo-bla-etc-sysctl-conf-permission-denied
* I had to remove the quotation marks in `/etc/apt/sources.list.d/natron.list`, otherwise I would get the error "type »“deb« in line 1 of ... is not known"

**Comment by olear** [comment]
Note that the repo for RPM and DEB are currently shutdown (well, they still exists but are not updated and the package manager will get a 404 when trying to download the actual package), the packages are still available, but you must download them manually from https://natron.fr/download.

This is related to the download modifications on the website.

**Comment by Theverat** [comment]
Strange, it worked for me after I applied the changes described in my comment.
But maybe it's an outdated version, it says 2.0.5. I'm not sure what's the current one, I'm a newcomer to Natron.

**Comment by mash-graz** [comment]
> Note that the repo for RPM and DEB are currently shutdown (well, they still exists but are not updated and the package manager will get a 404 when trying to download the actual package), the packages 
are still available, but you must download them manually from https://natron.fr/download.

to you really see manual download as an improvement? :(

**Comment by devernay** [comment]
Find a Ppa maintainer, or do it youtself. and voila.We have no time to maintain these.Reminder: natron is open source.Le 27 janv. 2017 7:10 PM, mash-graz <notifications@github.com> a écrit :
Note that the repo for RPM and DEB are currently shutdown (well, they still exists but are not updated and the package manager will get a 404 when trying to download the actual package), the packages
are still available, but you must download them manually from https://natron.fr/download.

to you really see manual download as an improvement? :(

**Comment by mash-graz** [comment]
> Find a Ppa maintainer, or do it yourself. 

a posted an reminder to https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=775490

IOhannes has already articulated his willingness to maintain this application for the debian community. 
please, support him!
