### ISSUE TITLE
many occasional core dump 

### ISSUE THREAD

**Issue by fPaglia** [MrKepzie/Natron#387]
Hi guys,  in the latest weeks I experienced tons of crash like the following: 

/home/francesco/bin/natron: line 31:  4815 Segmentation fault      (core dumped) $DIR/bin/Natron -style fusion $*
francesco@define-R4:~/Documents/Opam-projects/Sekat/scene/sc01/motionGraphic$ natron 
/home/francesco/bin/natron: line 31:  5021 Segmentation fault      (core dumped) $DIR/bin/Natron -style fusion $*
francesco@define-R4:~/Documents/Opam-projects/Sekat/scene/sc01/motionGraphic$ natron 
/home/francesco/bin/natron: line 31:  5767 Segmentation fault      (core dumped) $DIR/bin/Natron -style fusion $*

In fact I never lost almost anything thanks to the auto save on crash that recover up to last one or two action  but it's quite annoying...
Just in the latest hour I experienced 5/6 crash... not counting the amount of the whole day!

There is no clear reproducible situation I can report...
it can happen adding a bezier in a roto node as well as a grade node, or hitting play...
it just happen randomly...

**Comment by MrKepzie** [comment]
Are you using the snapshots ?

**Comment by MrKepzie** [comment]
That would help if you could run Natron like this:

./Natron.sh -debug

from times to times (it will be much slower) but will print a nice useful trace for us when it crashes, the lines you pasted are of no use for us

**Comment by fPaglia** [comment]
Hi Alex!
Ok no problem next time I'll start natron in debug mode.
Same kind of crash happen with the release version as well as the snapshot
(and snapshot in some way appear more stable)

2015-01-06 23:04 GMT+01:00 Alexandre Gauthier <notifications@github.com>:

> Are you using the snapshots ?
> On 06 Jan 2015, at 22:58, Francesco <notifications@github.com> wrote:
>
> > Hi guys, in the latest weeks I experienced tons of crash like the
> following:
> >
> > /home/francesco/bin/natron: line 31: 4815 Segmentation fault (core
> dumped) $DIR/bin/Natron -style fusion $*
> > francesco@define-R4:~/Documents/Opam-projects/Sekat/scene/sc01/motionGraphic$
> natron
> > /home/francesco/bin/natron: line 31: 5021 Segmentation fault (core
> dumped) $DIR/bin/Natron -style fusion $*
> > francesco@define-R4:~/Documents/Opam-projects/Sekat/scene/sc01/motionGraphic$
> natron
> > /home/francesco/bin/natron: line 31: 5767 Segmentation fault (core
> dumped) $DIR/bin/Natron -style fusion $*
> >
> > In fact I never lost almost anything thanks to the auto save on crash
> that recover up to last one or two action but it's quite annoying...
> > Just in the latest hour I experienced 5/6 crash... not counting the
> amount of the whole day!
> >
> > There is no clear reproducible situation I can report...
> > it can happen adding a bezier in a roto node as well as a grade node, or
> hitting play...
> > it just happen randomly...
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MrKepzie/Natron/issues/387#issuecomment-68942520>.
>



-- 
Francesco Paglia
Vfx and Production Supervisor

mobile  +39 347.82.12.473
e-mail   f.paglia.80@gmail.com

**Comment by MrKepzie** [comment]
I close this, re-open when you got some infos

**Comment by fPaglia** [comment]
Ok, I'll reopen it when I have something to show about!
The strange thing is that I started in debug mode and got no crash for
hours on the same shot where they were really frequents...
playback took ages to load 50 frms but it worked...

2015-01-07 18:41 GMT+01:00 Alexandre Gauthier <notifications@github.com>:

> Closed #387 <https://github.com/MrKepzie/Natron/issues/387>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MrKepzie/Natron/issues/387#event-215423863>.
>



-- 
Francesco Paglia
Vfx and Production Supervisor

mobile  +39 347.82.12.473
e-mail   f.paglia.80@gmail.com
