### ISSUE TITLE
Snapshot today version don't read the video file length - bug. 

### ISSUE THREAD

**Issue by adallafontana** [MrKepzie/Natron#388]
If I try to read a new video file o open a saved project all video property is set on -2 to +2 frame.

**Comment by adallafontana** [comment]
also readOIIO is down, is not possible read image sequence too

**Comment by adallafontana** [comment]
..and with version 1.00 I can't open project seved with snapshot 1.01.

**Comment by MrKepzie** [comment]
I'll look into it

**Comment by MrKepzie** [comment]
We were trying a fix to something but it turns out not to work, I reverted it.
