### ISSUE TITLE
Roto +1feather enhancement

### ISSUE THREAD

**Issue by adallafontana** [MrKepzie/Natron#389]
On Natron Roto shape you can edit feather, exist a command Shift-E for delete all feather, good.
Seem not exist a command or key-shortcut for create feather all together, example in Blender just hold Shift key an move one feather for create all with same size.
When you have a simple shape with few points is easy but with complex shape is tedious create feather on each point after drawn the bezier shape,...and in rectangular and circle shape could be useful for create the perfect symmetrical feather around the shape.

thx

alessandro

**Comment by MrKepzie** [comment]
You could just use the feather distance parameter

**Comment by adallafontana** [comment]
..but this create a feather point arround the shape?

**Comment by MrKepzie** [comment]
No, but why do you need the points if you want a perfect “symmetric” feather around your shape ? you are not going to edit them by hand, are you ?

**Comment by adallafontana** [comment]
yes you are right, for the symmetrical I'm forcing the idea a little bit....
but I mean this one:
![feather](https://cloud.githubusercontent.com/assets/8054856/5666662/89365fd4-9761-11e4-86e4-b7b976d69352.jpg)
I have this pretty complex shape, I start draw the bezier, after I need create all feather points because after I will go to animate them, link to a tracker etc... I start with very little feather for enlarge after the feather when I need.
I can do (and I did...) manually but will be nice to have a command like in Blender to do this in a fast way.
I ask..... ;)

**Comment by adallafontana** [comment]
Ok Alexander for explain better the problem, is not for that stupid shape in particular, is because I do the same work for other 10 after.

**Comment by MrKepzie** [comment]
It’s really a 2 minute job to add this for me so this is not a problem

**Comment by adallafontana** [comment]
thank you.

a.

**Comment by MrKepzie** [comment]
We will probably implement it when we will make some other changes to the roto internal rendering (such as fixing the bug pointed in https://github.com/MrKepzie/Natron/issues/377

**Comment by devernay** [comment]
Is this fixed?

**Comment by devernay** [comment]
This issue was moved to NatronGitHub/Natron#92
