### ISSUE TITLE
tracker name / tracker selection - enhancement

### ISSUE THREAD

**Issue by adallafontana** [MrKepzie/Natron#390]
![tracker](https://cloud.githubusercontent.com/assets/8054856/5691307/3d8886a6-98c0-11e4-9103-da0124f7cb29.jpg)

If I change the name of the tracker on tracker node this not refresh on Curve Editor.
The selection of single tracker on tracker node is not synchronized with the selection of Curve Editor (...will be useful if this one will happen).
In Curve Editor the tracker appear like a "single" point tracker not like a point child of the tracker node, this one can create confusion when you have more that one tracker node, all tracker in curve editor is call TrackerPM_1_0, 1, 2, 3, 4.....TrackerPM_2_0, 1, 2, 3, 4.....
In addition if you rename a tracker node containing some traker point, when you reopen the project we will have the old tracker disconnected and one new empty but with new name.
Without the possibility of synchronize selection, post-rename etc.... could be hard work with complex composition.

**Comment by MrKepzie** [comment]
Thanks for the detailed report, i'll fix all this for the 1.0.1 patch

**Comment by adallafontana** [comment]
also with duplicate animated node this happen, I have Dissove1 with keyframe, duplicate alt-C:
on NodeGraph and Properties the node is automatic rename Dissove1.1, on CurveEditor I have two nodes called Dissolve1

**Comment by MrKepzie** [comment]
I fixed the name bug for trackers and Dissolve. 
I didn't synchronise the selection between node graph and curve editor, instead I added a filter for nodes in the curve editor.
