### ISSUE TITLE
tracker offset -> pattern offset -> suggest

### ISSUE THREAD

**Issue by adallafontana** [MrKepzie/Natron#391]
![pattern](https://cloud.githubusercontent.com/assets/8054856/5691518/b9260eaa-98ca-11e4-9471-ba54be9e8bb0.jpg)
I don't know how you have thought the implement of tracker offset but maybe a solution could be change the offset only of the pattern and search area, I did a test, the center of the tracker is on flat area and the pattern over the eye, the tracker follow the pattern/eye.
All is hard to setup now and the tracking really slow (...maybe because the system see a large searching area, I don't know...) but could be a solution just with the ctrl-key->move pattern area.

**Comment by MrKepzie** [comment]
tracker offset was already requested

**Comment by mifth** [comment]
Yeah, it was here https://github.com/MrKepzie/Natron/issues/256
Thanks for implementing.
