### ISSUE TITLE
Curve Editor -> zoom in/out issue | enhancement

### ISSUE THREAD

**Issue by adallafontana** [MrKepzie/Natron#392]
![zoom](https://cloud.githubusercontent.com/assets/8054856/5691848/2a88da9a-98db-11e4-9283-e521d71e9582.jpg)

In the Curve Editor the zoom in/out is automatic refresh each time we select something, for me is annoying issue. The zoom (..and pan) size chosen should be remain unchanged until I to do something else: zoom, move or presse F for framing all.

**Comment by MrKepzie** [comment]
implemented
