### ISSUE TITLE
Wacom tablet improve in 1.01 snapshot

### ISSUE THREAD

**Issue by adallafontana** [MrKepzie/Natron#393]
You have implement the features for zoom with middle+alt command for Wacom or other tablet users in NodeGraph and CurveEditor, really nice thank you ;)

But in CurveEditor there is another important feautures: with Ctrl+mouse-wheel(zoom) I can scale the X size of CurveEditor UI, how can I do this with wacom?

Other little issue, Ubuntu and other Gnome users have the problem of Alt (use from the system for some over-command...) so the shortcut for zoom with wacom is Ctrl+alt+middle, this sequence of key is just occupied.

**Comment by MrKepzie** [comment]
We can't use another shortcut in Natron just because of Ubuntu, instead you should deactivate this shortcut from Ubuntu or configure your wacom

**Comment by adallafontana** [comment]
yes sure, not pretending this, but there is a short cut for do this with wacom?
For scale: zoom-wheel for mouse is ALT+middle for wacom (....now I press hold CTRL+ALT+middle)
For x-scale only: with mouse is CTRL+zoomwheel, for wacom what is it CTRL+ALT+middle?
tnx

**Comment by MrKepzie** [comment]
We made some slight adjustments: You don't need to hold alt anymore to zoom with your pen. 
Also for the curve editor, the direction in which you zoom will change the aspect ratio of the window, like in Nuke.

**Comment by adallafontana** [comment]
...you are the man, works!
thank you.
I don't open a new issue for this but ....give a look to the "space" command for enlarge the panel, with viewer and property panel works how you aspect, but not with Node Graph and doesn't works with curve editor.

**Comment by adallafontana** [comment]
...and offten (not always) we need click on the windows for right select the panel to enlarge, should be only a mouse over I think.

tnx
