### ISSUE TITLE
Some roto advices

### ISSUE THREAD

**Issue by fPaglia** [MrKepzie/Natron#396]
In the latest weeks I had the chance to use Natron to work on this video:
https://www.youtube.com/watch?v=8KOgRgqjq-0

I mainly used natron for the compositing of the CG over live video starting from min 1' to the end.
I extensively cleaned up the red roof and had to remove a drone from many aereal shot.

I had the chance to extensively use the roto tool and have to say it was quite painful to the shapes.
Roto got lot of improvement since its beginning but there are still lot of chances to improve the usability in the animation side.

Maybe it  is only me who find the following behavior not so "friendly" so would be very useful to discuss with other user their feeling about what I'm going to say:

1.  __point selection:__  there is no way to distinguish point selected of a shape from unselected (all are fully yellow) if we could see a difference in selection we would easily change the selection itself if needed 
2. __priority of the modification:__ once a selection of some point is made it's really hard to edit that selection (especially if the bounding box is small) instead I always end up to move the entire shape causing an unwanted change on the entire shape - this is very frustrating to me...
3. __presence of the bounding box:__ in many cases where there are lot of points in a small area the bounding box is seriously annoying and disturbing the correct placing of the shape, can we simply hide it in some way?
4. __impossibility of edit two aligned point:__ have you tried to select 2 points vertically or horizontally aligned then tried to move them? I'm still not able to do it and have to select one point at time to perform such a simple action, also if I try to move a point in the selection it moves just that point (that still sounds strange to me)  
5. __no chance to change the center of the bounding box:__ if you want to perform a simple rotation form a center that is different from the "original" center of the bounding box you can't this would be a real major plus
6. __the RGB value information are lost__:if you duplicate a roto node, try this: 
a. set the roto node to rgba
b. create a couple of shape 
c. set the color of each shape to a value different from 1,1,1,1
d. duplicate the node 
e. the newly created node has fully white shapes
7. __hitting Z__ to create from a linear shape a bezier always __ends in to big handles__ that have to be rearranged manually instead of having a nice smoth shape (that would be much more apreciated)
8. __negative feather__ return some sharp crop not really following the real shapes 
9. __keyframe display is very difficult__ if we could see only the keyframe of the selected shape in the timeline would be more than awesome! Actually the only way to understand which key is related to which shape is to use the keyframe editor in the properties panel.
10. __the left button requires a double click to perform an action:__ wouldn't be much more easy to have a simple click select the button and hold click open the panel with all the option? 
11. __more flxibility in feature interchange__: it would speed up the pipeline if we can easily move through the edit possibilities like: 
a. create a shape
b. set the cursor in add mode
c. add a point
d. without change the cursor move the point just create somewhere else
12. If natron crashes from time to time it loses the tracking of some point/shape (that have been already saved before)  

That's all for now, hope to hear as much feedback as possible :)
Later!

**Comment by adallafontana** [comment]
I agree 1, 2, 3, 4, 11.
6, 8, 12 seem a bug.

5 ok I understand what you mean, but for me is no so important, not for how I'm working with roto, move also the pivot for me is only one more complication, just scale rotate on center and move where is right.

7 I don't have particular problem with this behavior, but I understand the issue if you want regular shape with round angle.

9 I don't have particular problem with this and you can display keyframe on the Curve Editor divided for shapes, generally the only post-edit that I do and I want is delete some keyframe, now we can do this on property and curve editor.

10 If you mean on property panel yes is true but I don't remember the issue to resolve this.

**Comment by adallafontana** [comment]
Anyway on roadmap I read Roto paint, I don't know what will be possible achieve with this tool in Natron but I think some issue will be resolve from this.

**Comment by fPaglia** [comment]
>
> 5 ok I understand what you mean, but for me is no so important, not for
> how I'm working with roto, move also the pivot for me is only one more
> complication, just scale rotate on center and move where is right.
>
> As I see from some printscreen you made I'd like to hel you better figure
out why it would be very powerful for your workflow: You have lot of
figures moving around and in many cases this small addition will be a huge
time saver.
Let me give you a quick example: when you have to roto an arm for instance,
you could simply set the center of the arm selection to the elbow and
quickly   re-target all the shape in a matter of second instead of guess a
rotation, re-position then re-rotate back and forth as many time as needed,
I'm quite used to human rotoscoping and in this particular case it's a
invaluable plus to me.


> 7 I don't have particular problem with this behavior, but I understand the
> issue if you want regular shape with round angle.
>



> 9 I don't have particular problem with this and you can display keyframe
> on the Curve Editor divided for shapes, generally the only post-edit that I
> do and I want is delete some keyframe, now we can do this on property and
> curve editor.
>
A per "selected shape" display will again speed up the processes especially
if you want to make something rough and do a second pass refine (this is
mostly true with simple mask with almost static object and you have to
quickly prototype and just once the concept is approved you finalize the
sequence)


> 10 If you mean on property panel yes is true but I don't remember the
> issue to resolve this.
>
If you use the button on the viewer to switch between "create bezier", "add
point" and "select" you always end up opening its relative panel to select
the appropriate tool, most of the time you are not interested in other tool
than the showed one and actual behavior slow down the process due to the
doubled action
set button
find and set value
edit

insted of
set button
edit

  Hope those explanation better clarify my ideas.
Anyone else would like to contribute to the discussion? :)


> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MrKepzie/Natron/issues/396#issuecomment-69577764>.
>



-- 
Francesco Paglia
Vfx and Production Supervisor

mobile  +39 347.82.12.473
e-mail   f.paglia.80@gmail.com

**Comment by MrKepzie** [comment]
Francesco: There are shortcuts (q d v) for tool buttons of the Roto

**Comment by fPaglia** [comment]
Hey Alex!
Yes I do know and use them :)
This suggestion aims to find a better user experience in the use of this
buttons.


2015-01-13 10:17 GMT+01:00 Alexandre Gauthier <notifications@github.com>:

> Francesco: There are shortcuts (q d v) for tool buttons of the Roto
> > On 13 Jan 2015, at 09:53, Francesco <notifications@github.com> wrote:
> >
> > >
> > > 5 ok I understand what you mean, but for me is no so important, not
> for
> > > how I'm working with roto, move also the pivot for me is only one more
> > > complication, just scale rotate on center and move where is right.
> > >
> > > As I see from some printscreen you made I'd like to hel you better
> figure
> > out why it would be very powerful for your workflow: You have lot of
> > figures moving around and in many cases this small addition will be a
> huge
> > time saver.
> > Let me give you a quick example: when you have to roto an arm for
> instance,
> > you could simply set the center of the arm selection to the elbow and
> > quickly re-target all the shape in a matter of second instead of guess a
> > rotation, re-position then re-rotate back and forth as many time as
> needed,
> > I'm quite used to human rotoscoping and in this particular case it's a
> > invaluable plus to me.
> >
> >
> > > 7 I don't have particular problem with this behavior, but I understand
> the
> > > issue if you want regular shape with round angle.
> > >
> >
> >
> >
> > > 9 I don't have particular problem with this and you can display
> keyframe
> > > on the Curve Editor divided for shapes, generally the only post-edit
> that I
> > > do and I want is delete some keyframe, now we can do this on property
> and
> > > curve editor.
> > >
> > A per "selected shape" display will again speed up the processes
> especially
> > if you want to make something rough and do a second pass refine (this is
> > mostly true with simple mask with almost static object and you have to
> > quickly prototype and just once the concept is approved you finalize the
> > sequence)
> >
> >
> > > 10 If you mean on property panel yes is true but I don't remember the
> > > issue to resolve this.
> > >
> > If you use the button on the viewer to switch between "create bezier",
> "add
> > point" and "select" you always end up opening its relative panel to
> select
> > the appropriate tool, most of the time you are not interested in other
> tool
> > than the showed one and actual behavior slow down the process due to the
> > doubled action
> > set button
> > find and set value
> > edit
> >
> > insted of
> > set button
> > edit
> >
> > Hope those explanation better clarify my ideas.
> > Anyone else would like to contribute to the discussion? :)
> >
> >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/MrKepzie/Natron/issues/396#issuecomment-69577764>.
>
> > >
> >
> >
> >
> > --
> > Francesco Paglia
> > Vfx and Production Supervisor
> >
> > mobile +39 347.82.12.473
> > e-mail f.paglia.80@gmail.com
> > —
> > Reply to this email directly or view it on GitHub <
> https://github.com/MrKepzie/Natron/issues/396#issuecomment-69713068>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MrKepzie/Natron/issues/396#issuecomment-69715788>.
>



-- 
Francesco Paglia
Vfx and Production Supervisor

mobile  +39 347.82.12.473
e-mail   f.paglia.80@gmail.com

**Comment by adallafontana** [comment]
>out why it would be very powerful for your workflow: You have lot of figures moving around and in many cases this small addition will be a huge time saver. Let me give you a quick example: when you have to roto an arm for instance, you could simply set the center of the arm selection to the elbow and quickly re-target all the shape in a matter of second instead of guess a rotation, re-position then re-rotate back and forth as many time as needed, I'm quite used to human rotoscoping and in this particular case it's a invaluable plus to me.

Francesco I had know what you meant, but the bounding-box now is not per shape but per selection points, is not so "physical" ...like in other system. After could be true what you said but for experience the pivot of the animated roto shape is not so unchanged like a pivot of a arm in the 3d rig. Anyway for me any improvement is good, just not complicate too,
I prefer speed and stable over all.

**Comment by adallafontana** [comment]
The really short-cut that I would like on Roto Shape are the same of Blender UI: R (rotate) S (scale) G (grab) without using the bounding box and click on viewer in a too little arrow; just move the cursor with hold press keys. Blender in this one has more "instinctive approach" to do the things in UI, less mathematically, statically way, I love this approach over any other software 3D and not.
But is not possible have all.... the Blender compositor is too disjointed in many others parts for to be good  ;)

**Comment by MrKepzie** [comment]
Francesco, in order: 

1) I just made selected points coloured in green now

2) I added a button to disable the mouse click capture of the bounding box for any click made within it. 
When unchecked, you can only click on the crosshair to move the points

3) I guess it's the same as 2

4) Just zoom-in ? 

5) We'd have to add all the equivalent of what's inside the Transform node parameters to the Roto node. That's some stuff that was requested already if I remember well. I haven't had a chance to do it.

6) Bug fix incoming

7) The smoothing depends on your zoom level, maybe the value is not good as a default, I made it smaller

8) This is something we're aware of. The internal rendering cannot support it as of right now. Once we make the changes for the other opened bug with roto blending, this will also fix this.

9) We should make it per bezier, like for the tracker

10) Been fixed already

11) A bit in the vague;) I let you discuss for potential ideas

12) I'll look into it

**Comment by MrKepzie** [comment]
@fPaglia Feel free to give us feedback on the Roto in 1.1 , most of the points above have been implemented

**Comment by fPaglia** [comment]
@MrKepzie I was very sick the past few days, just downloaded the latest update!
I'll test asap thanks for your addition!
Later!
Francesco

**Comment by fPaglia** [comment]
Here we are!
tested commit d6df5bdffc7f094ea316a57d55b0441938772a56. 
In order again:
1) Much better thanks!
2) it seems not working here can't see the difference
3) Well it goes in the same direction.. so no real change found, but an option to hide the bounding box would be great
4)Zoom in? If the 2 point are far from each other is impossible to see what to do. Zoom in can't allow me to find the center of a bounding box that lies in the same place where the edges of the bounding box are... 
Here an example: This condition do not allow you to edit/animate both vertex at the same time without moving the entire shape... I got crazy trying to clean up sharp straight edges from the latest work I made
![sample_screeshot](https://cloud.githubusercontent.com/assets/5074015/5793459/7317d9ae-9f44-11e4-9237-16b43bc89503.png)

5) Yes already requested just a reminder :)
6) waiting for the bug fix
7) ok now seems better, however a better solution could be to follow the bezier itself instead of a zoom level... Shake is a very powerful reference for this 
8) thanks
9)Thanks for this much better
10) thanks it works fine but the right click isn't that intuitive I think (maybe and hold of a second on the button would be better)
11) Ok I'll write a better post later
12) thanks for this

I'm waiting for a new build to se if (2/3/4) can be "fixed" by this new button but must admit we have to spend a bit more time to make the edit of a selection more efficient.
Later!

**Comment by adallafontana** [comment]
>10) thanks it works fine but the right click isn't that intuitive I think (maybe and hold of a second on the button would be better)

I like right click for open the submenu but I think should to have another + option e.g. press the little arrow for open the menù could be a solution.

Now if we press the arrow we have a scroll but is a scroll at  blind way, doesn't make sense if you don't know the right click option.

**Comment by fPaglia** [comment]
2015-01-19 11:09 GMT+01:00 Alessandro Dalla Fontana <
notifications@github.com>:

> 10) thanks it works fine but the right click isn't that intuitive I think
> (maybe and hold of a second on the button would be better)
>
> I like right click for open the submenu but I think should to have another
> + option e.g. press the little arrow for open the menù could be a solution.
>
> Now if we press the arrow we have a scroll but is a scroll at blind way,
> doesn't make sense if you don't know the right click option.
>
> —
>

How does the majority of the softwares behave?
Right click is present just in that sole button or not?...
If this is an exception I think it's not the best design solution...


-- 
Francesco Paglia
Vfx and Production Supervisor

mobile  +39 347.82.12.473
e-mail   f.paglia.80@gmail.com

**Comment by manuelsongokuh** [comment]
hello

ROTO needs mode in orthographical  with snap in square? or shape show information details:
example roto in rectangle:
point 1:x,y
point 2:x,y
point 3:x,y
point 4:x,y

this is possible?

**Comment by manuelsongokuh** [comment]
or add GRID snap?

**Comment by devernay** [comment]
@manuelsongokuh why not use the Rectangle plugin?

**Comment by manuelsongokuh** [comment]
@devernay rectangle plugin is same of ROTO?..
ok.. i wil...

**Comment by manuelsongokuh** [comment]
rectangle for me it's fine..
