### ISSUE TITLE
Transform linked to tracker point issue

### ISSUE THREAD

**Issue by adallafontana** [MrKepzie/Natron#398]
![tracker_link](https://cloud.githubusercontent.com/assets/8054856/5711387/6bc58c6c-9aaa-11e4-846e-505c0f6d5624.png)

If I link a translate value of a Transform node I have this strange behaviour:
the center of transform instead "going" over the tracker point linked, go at double distance far away like if the offset was inverted.

tnx

**Comment by blackearth2014** [comment]
May I ask why would you need to link a transform node to a tracker.  The transform will follow whatever translation animation from the exported tracker analyzer.  This works quite well as an attached to source or mimic movement type. Apple Motion has this kind of tracking analysis export.

**Comment by adallafontana** [comment]
Sorry but I don't understand what do you mean exactly Omar.
I have 1 simple tracker that follow the girl, I need copy/link the translate movement of tracker to one image that must follow the movement of the girl, I can use for do it corner-pin with only one point, or a transform node.
In this case I prefer Transform because I need animate manually also the scale and rotate.
Tracker for Translate xy.
Scale and rotate manually.

I can't use coner pin linked to the tracker for the xy movement and after
a Transform node for scale rotate because in this way I can have only the motion blur of the scale rotate but not the motion blur of the movement xy.

With only one transform node I can have all, movement and motion blur.

![tracker](https://cloud.githubusercontent.com/assets/8054856/5712568/be9f537e-9ab3-11e4-96b5-a8b79d48c0a6.jpg)

**Comment by adallafontana** [comment]
Anyway you can seen on the first screenshot, the value of the tracker point and the xy of the transform node are equal (....like must be if I link), but the rectangle is not in same space position, I only ask why, and also why double distance.

**Comment by blackearth2014** [comment]
Okay. I understand a little better now.

This is your season
Omar Brown
Blessed House Media

On Jan 12, 2015, at 5:55 PM, Alessandro Dalla Fontana <notifications@github.com> wrote:

Anyway you can seen on the first screenshot, the value of the tracker point and the xy of the transform node are equal (....like must be if I link), but the rectangle is not in same space position, I only ask why, and also why double distance.

**Comment by MrKepzie** [comment]
You re just copying the animation to the translate param. However the transform applies relative to its center ( the center of the overlay). We did not implement export to transform yet and you should rather use CornerPin

**Comment by adallafontana** [comment]
Ok I understand the problem:
the 0-0 of the Translate value in Transform node is not refer to the "Center" value but to the left-down-corner 0-0, and here we are right, the misunderstanding born when I connect the Transform node to the overlay with size different of the size of the project, eg. project HD,
overlay 1024x1024, connect the transform node, on "Center" I read 512-512 the effective center of my image-overlay, but if I link or copy and paste value from others, tracker or so on, the 0-0 is not refer to size of overlay (1024x1024) but always to the 0-0 of project size (HD) or better to the absolute space value 0-0.
Just to know this one and all works right you don't need to implement nothing more about link/copy.

Anyway:
overlay -> transform_1(for change offset) ->transform_2 (linked to something).

For me you can close, just to know if is correct visualizing the center of the Transform like the center of the node connected and not like it's absolute value.
