### ISSUE TITLE
Maintenance tool problems

### ISSUE THREAD

**Issue by fPaglia** [MrKepzie/Natron#400]
Hey Alex, this morning the maintenance tool says: bad hash for org.tuttleofx.plugins.

Here a reference picture:
![hasherror](https://cloud.githubusercontent.com/assets/5074015/5719655/a3b948fa-9b1a-11e4-95d4-7f49c99cae0a.png)

**Comment by MrKepzie** [comment]
Sometimes it happens, next commit should fix it.
In the meantime you can download a “fully bundled” snapshot here:

http://sourceforge.net/projects/natron/files/snapshots/linux64/repo/Natron_Linux_bundle_snapshot_x86-64bit.tgz/download <http://sourceforge.net/projects/natron/files/snapshots/linux64/repo/Natron_Linux_bundle_snapshot_x86-64bit.tgz/download>

**Comment by fPaglia** [comment]
thank you, I'll wait for next commit :)
