### ISSUE TITLE
ColorCorrect node - (De)Saturation bug

### ISSUE THREAD

**Issue by romanvolodin** [MrKepzie/Natron#402]
ColorCorrect node with Saturartion = 0 works weird. Colors should be absolutly gray I guess.

![cc_saturation_bug](https://cloud.githubusercontent.com/assets/9511905/5741227/e181a2bc-9c1a-11e4-9d27-6e7d1ccffda6.png)

Some info:
Natron version 1.0.0 Release .
This version was generated from the source code branch workshop at commit 0c6a4ee12348a436e89f58f246eb332fbb10684e.
OS: Xubuntu 14.10 x64

**Comment by MrKepzie** [comment]
This has been fixed for the next version
