### ISSUE TITLE
Snapshot linux 14/01 doesn't read sequence with no 0001 file number

### ISSUE THREAD

**Issue by adallafontana** [MrKepzie/Natron#403]
If I try create a new readOIIO file and I try read a sequence e.g. 422-670  I have a error message and the read node with 1-1 that I can't change

**Comment by adallafontana** [comment]
...instead with sequence file that start with 00000 I can read without problem

**Comment by MrKepzie** [comment]
This is been fixed, wait for ~30min for the update

**Comment by adallafontana** [comment]
![error](https://cloud.githubusercontent.com/assets/8054856/5754909/f18fc4c0-9c9e-11e4-97a5-662f528cc136.jpg)
hum... not.
Now also with readFFmpeg I have some issue, I read a file like 1-1 and I can't change that.
The error said invalid image but if I read single image file I can read, is only a problem of frame-range

**Comment by MrKepzie** [comment]
Yes I forgot to apply the fix for the Ffmpeg reader

**Comment by adallafontana** [comment]
on last update persist the issue for image sequence that doesn't have frame 0001 etc....
for readFFmpeg all is right and fix

**Comment by adallafontana** [comment]
The error log said this one when I try read the file:
Natron_File_Dialog_Preview_Provider_Readerfr.inria.openfx.ReadOIIO: An error occured while changing parameter File
