### ISSUE TITLE
UNC paths under Windows

### ISSUE THREAD

**Issue by ogre** [MrKepzie/Natron#404]
It seems natron for windows has trouble loading sequences through UNC paths, I had to use drive letter P: and do a search-replace later in text editor.

More, you can't provide UNC path as an argument to natronrenderer.exe - the error message is "ERROR: Natron :Filename has no path. It must be absolute."

Fixing this will make natron more crossplatform :)

**Comment by MrKepzie** [comment]
I'll try to debug it on windows. Where  do you need a search replace in a text editor ?

**Comment by ogre** [comment]
W dniu 2015-01-16 o 11:00, Alexandre Gauthier pisze:
>
> I'll try to debug it on windows. Where do you need a search replace in 
> a text editor ?
>
>
I created my composition on windows machine, using p: drive letter for 
sequences.
To render this comp under linux I had to edit .ntp file and replace 
'p:/' with '//hal/Projects'.
Luckyly natron stores forward slashes for windows paths.

**Comment by GurayGursoy** [comment]
Not sure if its related but I cannot open any kind of file dialogue in Natron.

"Open Project"  or a "Reader" node shuts down Naton immediately.

tried on Natron 1 and 1.1 32/64 bits on Windows 8.1 64bit.

**Comment by MrKepzie** [comment]
Closing see #409 . Crash of the file dialog might be related too.

**Comment by ogre** [comment]
Great !
I'd love to try, do I have to build latest natron for myself, or is there any automated nightbuild/CI ?

**Comment by MrKepzie** [comment]
Arlight, in this commit https://github.com/MrKepzie/Natron/commit/398bfd586279485253d340f1ca13d3fa60164663 the file dialog will now automatically replace the drive letter by the network share name when clicking OK. Note that in the view, you will still see the network share by its mapped drive letter.

**Comment by MrKepzie** [comment]
There's no snapshots yet on windows, we'll set them up soon

**Comment by ogre** [comment]
Is this supposed to work in 1.2.0 (89ed3731e92fbd73dfc667fa9c780ceca23d6eb1) ?
I still can't navigate filebrowser and load UNC paths.

-thanks

**Comment by MrKepzie** [comment]
The file browser does not support it, but once you click OK it will translate the path with the drive letter to a UNC path.

**Comment by ogre** [comment]
W dniu 2015-02-11 o 21:39, Alexandre Gauthier pisze:
>
> The file browser does not support it, but once you click OK it will 
> translate the path with the drive letter to a UNC path.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/MrKepzie/Natron/issues/404#issuecomment-73959978>.
>
  OK thanks, I get it now.
Still:
     - drag'n'dropping from an UNC path window does not work
     - drag'n'dropping from a drive letter path window does not replace 
to UNC path
However it is now minor inconvinience rather than a stopper.

**Comment by MrKepzie** [comment]
Yes we did not implement it for the drag&drop. We could though, I'm just adding a note in my very very very long list of todo list.

**Comment by ogre** [comment]
W dniu 2015-02-11 o 21:49, Alexandre Gauthier pisze:
>
> Yes we did not implement it for the drag&drop. We could though, I'm 
> just adding a note in my very very very long list of todo list.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/MrKepzie/Natron/issues/404#issuecomment-73961757>.
>
Much appreciated :)
