### ISSUE TITLE
ReadOIIO doesn't read any sequence file that not have frame "0"

### ISSUE THREAD

**Issue by adallafontana** [MrKepzie/Natron#405]
All kind of file image sequence on Natron 1.1 Linux.
Is it only my problem?

**Comment by MrKepzie** [comment]
Please post a test case because here everything works fine even for sequences not starting at 0.

**Comment by adallafontana** [comment]
https://www.dropbox.com/s/khp8yxpj1rem8oi/POINT_ENG_NO_0000.zip?dl=0
![seque](https://cloud.githubusercontent.com/assets/8054856/5774269/54253e44-9d6c-11e4-905c-4e8d6e0f57f4.jpg)

with sequences that has frame 0 I can read only in Absolute  in [Project] doesn't works.
with sequences hasn't frame 0 I can't read in all ways.

https://www.dropbox.com/s/6t6qcyeenpadz23/test_frame_range.ntp.zip?dl=0

**Comment by MrKepzie** [comment]
You’re sequence reads just fine here. Are you sure you are using Natron v1.1 ?
Btw your project is empty

**Comment by MrKepzie** [comment]
![screenshot from 2015-01-16 10 59 39](https://cloud.githubusercontent.com/assets/4058448/5774534/3224e436-9d6f-11e4-8895-684a6576ec30.png)

**Comment by adallafontana** [comment]
please try save the project and load the sequence file like relative [Project] 

I have try move the sequence on desktop, but nothing, in absolute I can read but not in [Project] 
and with some other sequence with more frame I have a error message

**Comment by adallafontana** [comment]
...yes sure 1.1.0. This issue is started when you have implement frame-rang on Project property panel.

**Comment by MrKepzie** [comment]
Right, the issue is fixed here https://github.com/MrKepzie/Natron/commit/7cd26e0736070ceb505b4d45791543393b6fc86a
This is a bug when you use any variable like [Project] before a filename, I'll patch the download version of 1.1
