### ISSUE TITLE
Pine Corner Bug

### ISSUE THREAD

**Issue by rcspam** [MrKepzie/Natron#407]
Is it a bug ?

It's impossible to put the corners of the picture on CornerPin points.

![natron - gg ntp - _001](https://cloud.githubusercontent.com/assets/10021906/5778489/f6dae858-9d9b-11e4-9ee0-7b1855974951.png)

**Comment by blackearth2014** [comment]
It looks like your corner pins are in the wrong order or somehow there was a transform performed on the image. Your project is 1920*1080HD but your image is 1553*715. Where is the Background image that you are trying to corner pin your image to.

**Comment by MrKepzie** [comment]
This is not a bug, your corner pin from points are not set to the original image 4 corners.

**Comment by rcspam** [comment]
Ooops! Sorry !
