### ISSUE TITLE
Secondary window always "on top"

### ISSUE THREAD

**Issue by Farmfield** [MrKepzie/Natron#411]
So I run dual monitors and I noticed that if I set it up as I have in Nuke with main UI with node graph, curves and properties on the left and drag the viewer to it's own window on the right monitor, it's always "on top" - no other apps, explorer windows, color pickers, everything, will non pop over the natron 32nd window.

**Comment by MrKepzie** [comment]
This is a known bug

**Comment by MrKepzie** [comment]
Fixed in https://github.com/MrKepzie/Natron/commit/7802ecc8d4ae5ab1b2628c7f7aca776b87d466fd

**Comment by Farmfield** [comment]
Awesome work, Alexander. And as a Nuke comper I'm blown away with the work you guy's have done, looking forward to doing lots of work with Natron. :)
