### ISSUE TITLE
1.1.0 and 1.0 crash when opening filebrowser... bug

### ISSUE THREAD

**Issue by piripi** [MrKepzie/Natron#413]
hi there,

just wanted to try out natron, look really promising!

BUT when i opened once the read node, an point to my nas drive, it dies instantly!

and since that does the same, when just opening the filebrowser of the readnoade...
unusible...

when i drag and drop the files in it works, but saving, opening anythings causes crash... :(

is this common problem?

i'm on win 8.1 all updates installed...
i believe the nas drive is the problem?

cheers
![natron](https://cloud.githubusercontent.com/assets/1345918/5842236/76a5339e-a1a3-11e4-8752-e43d025594e8.jpg)

**Comment by MrKepzie** [comment]
Yes see  #404,  #409 will fix it.

**Comment by MrKepzie** [comment]
See #404 , UNC paths are now working on Windows

**Comment by MrKepzie** [comment]
Regarding the file browser crash, I cannot reproduce it on Windows 7 even with a Network drive, so I guess the issue is elsewhere, probably Windows 8 related. A video of the crash would help.

Was the crash arising in prior versions of Natron (pre 1.0 ? )

**Comment by GurayGursoy** [comment]
Here is a video of read node and file browser crash on my win 8.1 64bit

https://www.dropbox.com/s/0xhj3fhcfmhmwow/natron_1.1_win8_crash.avi?dl=0

Same thing happen on Natron 1.0 64bit , Natron 1.1 32/64 bits
I haven't tested Natron pre 1.0 ...sorry

Hope that helps!

**Comment by MrKepzie** [comment]
Hi, I'm having a hard time to see on your video what folder opens-up first when the file dialog appears. Can you tell me which directory is loaded first ? And more important can you list the content of the directory (the name of files + sub-directories). That might be a bug with a file name that Natron does not understand well

**Comment by GurayGursoy** [comment]
Hi,
Since it's the first time Natron runs on my computer, she tries to open the Users/Guray folder which has lots of files and folders including Desktop.Downloads,Documents...etc.
The file and folder list would be very long in this case.
But you suspicion might be true, because there are probably files and folders that has spaces in them and ones that have turkish characters in them.
is there a settings file I can edit to point Natron into a "safer" folder?

**Comment by MrKepzie** [comment]
Yes but this is in the windows registry.
You have to take the following steps:

In the start menu, in the “search”  area, type “regedit”.

The settings file recording the place where to open up the file dialog first will be stored in:

HKEY_LOCAL_MACHINE\INRIA\Natron

or

HKEY_CURRENT_USER\INRIA\Natron


In there you should find something named “LastLoadSequenceDialogPath” and “LastOpenProjectDialogPath"
These point to the location to open first for respectively, the "open sequence" and "open file” dialogs.

You can change it to point to anywhere you’d like.


Note that if you’re unsure of the steps to take, consider not doing it as modifying the registry might prevent some other applications from working.

**Comment by GurayGursoy** [comment]
Well that worked :)
I've changed the "LastLoadSequenceDialogPath" "LastOpenProjectDialogPath" "LastSaveProjectDialogPath" "LastSaveSequenceDialogPath 

I've found those under;

HKEY_CURRENT_USER\SOFTWARE\INRIA\Natron

and changed the values from empty to "C:\tmp\" without quotes

That opens the dialogue window alright but there are still some weird things going on :)
When I add a "read" node it first shows my drive letters on the right panel (should be the contents of C.\tmp\) and after 3 seconds it shows the contents of the C:\tmp\
I can only see my C: drive on the left panel (I've also have D: which I run natron.exe from )
also after the dialogue window shows I navigate to the same folder it couldn't display before..and it did! No crashes on any folder yet.
And also I have a folder which holds a sequence of 6715 .tga files which Natron took very long time to show (but it did in the end)

Thanks for the help!

**Comment by MrKepzie** [comment]
> Well that worked :)
> I've changed the "LastLoadSequenceDialogPath" "LastOpenProjectDialogPath" "LastSaveProjectDialogPath" "LastSaveSequenceDialogPath
> 
> I've found those under;
> 
> HKEY_CURRENT_USER\SOFTWARE\INRIA\Natron
> 
> and changed the values from empty to "C:\tmp\" without quotes
> 
> 

good
> That opens the dialogue window alright but there are still some weird things going on :)
> When I add a "read" node it first shows my drive letters on the right panel (should be the contents of C.\tmp) and after 3 seconds it shows the contents of the C:\tmp\
> 
This is because the dialog view is refreshed before the content of the dialog is loaded hence there’s a latency if your folder is full of images

> I can only see my C: drive on the left panel (I've also have D: which I run natron.exe from )
> 

The left panel doesn’t list drives, instead it is a “favourite” window where you can add bookmarks yourself by drag&dropping them.
> also after the dialogue window shows I navigate to the same folder it couldn't display before..and it did! No crashes on any folder yet.
> 

When it was crashing before, did the folder it was trying to open actually exist ?
> And also I have a folder which holds a sequence of 6715 .tga files which Natron took very long time to show (but it did in the end)
> 
> 

I’m aware of it, the algorithm underneath to display sequences is just iterating over all files to build sequence patterns and it can take a while for huge sequences.
The best thing to do in that case is to type the sequence name directly in the line-edit without using the file dialog.

**Comment by GurayGursoy** [comment]
Ok :) I've used the computer icon from the "look in " dropdown menu and dragged my D: drive to left panel. It adds two favorites (not important but wanted to mention) I've deleted one and D: drive is accessible  :) Thanks

The folder it crashed existed and it was my Users folder which holds a lot ( more than 150K ) files. And as for the registry value; it was empty and I've changed it to another existing folder.

**Comment by piripi** [comment]
wow thnaks alot!! now it works great!!! i changed typed in a temp path :)

will test soon more!

very nice!

cheers
piripi

**Comment by MrKepzie** [comment]
does it still happen to you ?

**Comment by piripi** [comment]
hi thanks for the mail!

nope i change the regedit stuff, form now it did not crash because of 
opeing files any more :)

cheers
piripi

**Comment by MrKepzie** [comment]
Since what version of Natron did you start using it ? My guess is there was a crappy value recorded in your registry making crash Natron

**Comment by piripi** [comment]
first i tried was 1.0...
  since that i had the pronlem of crashing when opening files or readnode...
now works great with the regedit fix

thanks
