### ISSUE TITLE
Natron closes EVERY TIME when moving the CurveEditor Timeline Needle

### ISSUE THREAD

**Issue by ChanderRuzzi** [MrKepzie/Natron#414]
Hello, how are you doing?
As some of you may know, I'm making my first Natron Tutorial and already notified you by tweet.
In this tutorial I'll have to animate a lot of "Mix parameters" of the "Merge Nodes". So I have to do this on the CurveEditor, but EVERY TIME I try to move the Needle that guides the frame of the timeline inside of the CurveEditor, Natron closes! 
This is a much needed function at least for me and I'll tend to use it a lot for my tutorials.
If it's not a problem and you guys  can help me with that, It would be great.
I'm using Linux Snapshots version.
Thanks for reading, and I hope Everything works fine! :)

You can see what I'm talking about on the attached image:
![crash](https://cloud.githubusercontent.com/assets/10161251/5849740/cb98e1c0-a1d0-11e4-8c84-89075e2cee38.jpg)

**Comment by blackearth2014** [comment]
Chander,

Until this gets resolve, you can drag on the time time to get the same scrolling play-head. Just make sure that your timeline and curves are normal for full view.

**Comment by MrKepzie** [comment]
Hello Chander,

This is a bugged I introduced in the first version I uploaded online when 1.1 was released. A couple hours afterwards, a new build has been re-uploaded with the fix. 
Just re-downloading Natron again should fix it.

**Comment by ChanderRuzzi** [comment]
Ok, as I was using the online installer of the snapshot version and wasn't getting any updates on any of the mirrors, I just installed the Bundle Version and it's now working again.
Thank you guys! :+1:
