### ISSUE TITLE
Switching Viewer inputs

### ISSUE THREAD

**Issue by kirang4e** [MrKepzie/Natron#416]
Hello
While working,I give multiple inputs to viewer node,to compare my  comp flow.
in Natron,Its changing to wipe mode.so every time I have to goto viewer and manually choose nodes in "A / B" tab. I can't access it from node graph.
![ntrvwr](https://cloud.githubusercontent.com/assets/10396656/5853661/9696606c-a24b-11e4-8465-7067537d3806.png)

I request you to change it something like this.
*Don't to change it to wipe mode by default.
*Can access viewer input pipe,directly by keyboard shortcut. say for ex: If I pres 3,viwer should show noise node output directly.So that I can easily switch between inputs.

1 more request:
I can't copy/paste nodes from one script to another.It need to use windows clipboard I guess. 

Thank you

**Comment by MrKepzie** [comment]
Preferences—> Viewers —> uncheck “Automatically enable wipe”. 

Copy/paste across projects has been implemented for the next version already.
