### ISSUE TITLE
Viewer is incorrect when plugin returns an empty RoD

### ISSUE THREAD

**Issue by devernay** [MrKepzie/Natron#417]
A plugin may have an empty RoD (e.g. RectangleOFX after https://github.com/devernay/openfx-misc/commit/4d522459af7b6e2ae5e8b6a39f9cdf00ed3dfc10 when no input is connected and mix = 0 or color0.a = color1.a = 0.).

In this case, the viewer shows the last image rendered with a non-empty RoD and the infobar shows a non-empty RoD, whereas nothing should be shown.

**Comment by MrKepzie** [comment]
fixed
