### ISSUE TITLE
Readers should have an optional input

### ISSUE THREAD

**Issue by devernay** [MrKepzie/Natron#418]
One may want a Reader to read the image *after* a previous node in the graph (which writes an image to disk) has executed.
It is impossible because the output of a node cannot be connected to a Reader (whereas the input of a node can be connected to a Writer for the same reason)

**Comment by AurelyenD** [comment]
Should'nt a Writer be able to behave as a Reader ?
Adding a checkbox in the Writer to force him to read the images files, 
and not process upstream information.
This is a "Nuke-like" feature though.

**Comment by MrKepzie** [comment]
I guess Writers should have an output and a "Read from file" parameter

**Comment by devernay** [comment]
@MrKepzie was this fixed?

**Comment by MrKepzie** [comment]
no

**Comment by devernay** [comment]
and now?
This is necessary for the RunScript node to work

**Comment by devernay** [comment]
@MrKepzie can you take a peek at this one?
RunScript node is totally useless without this
