### ISSUE TITLE
File .ntp with space in the path...

### ISSUE THREAD

**Issue by rcspam** [MrKepzie/Natron#419]
Hi,
When Natron is call with a 'ntp file' in argument (from the command line or from the desktop), it can't find it when there is a 'space' somewhere in the path (directories or files).
OS: Linux
Version Natron 1.1
Regards

**Comment by MrKepzie** [comment]
You must probably escape the "spaces" with a backslash.

**Comment by MrKepzie** [comment]
E.g  ~/Library/Application\ Support/

**Comment by rcspam** [comment]
No, escape space or put file between quotes as well, produce same problem.
With graphics interface, drag the file on Natron icon is the same...

PS; About this, can you add a %U parameter to the exec option in Natron.desktop file while installation under linux. This would allow Natron to possibly appears in the context menu of xml file and to drag file on its icon.

**Comment by MrKepzie** [comment]
Fixed in python branch:: https://github.com/MrKepzie/Natron/commit/59dca5db2187abdc5a623ad990771712b4a65a14

**Comment by rcspam** [comment]
Hi Alexandre,

I have install the last snapshot (02-07-2015)
The bug is not completely remove:
If open a file (with space) from the natron menu: no problem.
If  open it from the command line: 'error' natron take only the end of the name file.
If  drag and drop it on the natron icon app: same 'error' as above (Of course, i 've add  a '%U' parameter to my natron.desktop file).
And finally no %U parameter, which is cool for end user, in the Exec line of natron.desktop file.
So this bug is always here;) Sorry
Regards

**Comment by MrKepzie** [comment]
The fixed was applied to the python branch, the snapshots are redirecting to the workshop branch. We will merge workshop into python very soon now.

**Comment by rcspam** [comment]
Ok sorry, Is this bug is the than #433, because files with à,è,é.... have the same issue like with 'space'.
