### ISSUE TITLE
Color Knob bugs (Primatte OFX plugin Fine Tuning sliders dont work)

### ISSUE THREAD

**Issue by nicholascarroll** [MrKepzie/Natron#421]
Tested Primatte OFX plugin. Works except for Fine Tuning Sliders. 
To reproduce: 
1. Select operation Fine Tuning
2. Select the colour either by sampling in the viewer or in the from/to colour field
3. Drag any of the fine tuning sliders (large/medium/small)
4. The selected colour will change/reset - it should not

The problem does not occur if you enter the slider value directly in the numerical field next to the slider.

This defect is present in at least versions 0.96 to 1.1.

**Comment by devernay** [comment]
Does this plugin require a licence to run?

**Comment by devernay** [comment]
there are at least two bugs in the color knobs and/or multidimensional knobs
- color knobs should not be editable when disabled (no picker, no switch to "slider" mode, slider should be disabled)
- when setValue is called with different values and the knob is in "slider" mode, it should switch to "XD" mode. The reverse is not true: switching to slider mode should be done by the user (to avoid flicker).

**Comment by MrKepzie** [comment]
https://github.com/MrKepzie/Natron/commit/e861332f2430bdd2e74341be3fce453449f9d90c
