### ISSUE TITLE
Splash screen freeze

### ISSUE THREAD

**Issue by synk-a-dynka** [MrKepzie/Natron#423]
A few times the splash has frozen for me at "creating thumbnails".
No progress and splash window can't be closed, staying on top of everything on my desktop.
I can't find any process to kill, can't kill with xkill either.
Only way to get rid of splash is rebooting computer which can be a huge time and focus waste if there is other work going on at the machine...

Ubuntu 14.04, 64bit.
Intel® Core™ i7 CPU 960 @ 3.20GHz × 8
GeForce GTX 480/PCIe/SSE2

**Comment by MrKepzie** [comment]
Clearing plugin load cache from the menu might help.

Otherwise open a terminal:

killall -9 Natron

**Comment by synk-a-dynka** [comment]
Thank's will try first option if this happens again.
There was no Natron process to kill.
