### ISSUE TITLE
Problem with frame sequence

### ISSUE THREAD

**Issue by adiser81** [MrKepzie/Natron#424]
Hello. After updating ceased normal boot sequence of frames. And he began to slowly work interface Node Graph. On the accompanying video, I showed these faults. (OS Windows7x64). http://youtu.be/xFMWnk8I0os

**Comment by MrKepzie** [comment]
Are you on windows 64 ?

**Comment by adiser81** [comment]
Yes

**Comment by adiser81** [comment]
Windows7 x64

**Comment by adiser81** [comment]
And do not operate the load path in the "Relative to Project" and "Relative to OCIO." Gives an error: Invalid image file ....

**Comment by adiser81** [comment]
to update today, everything worked fine. After the upgrade can not work with sequences.

**Comment by adiser81** [comment]
Here's another video http://www.youtube.com/watch?v=iYGvRYq4j08

**Comment by MrKepzie** [comment]
Can you try downloading this version: https://transfert.inria.fr/fichiers/f3e7c35b60dfa110b3cec4e96df6135b/Natron_Windowsx86_64bits_v1.1.0.zip

And tell me if it fixes those problems

Please do not spread this version.

**Comment by adiser81** [comment]
This problem is gone but not completely. Video attached.  http://youtu.be/xm1HD0h7ZNo

**Comment by adiser81** [comment]
Interface continues to slow down and Timeline always starts with the 1st frame, even if you specify a sequence from 50 to 119 frames.

**Comment by MrKepzie** [comment]
Can you try clearing completely the cache (from the menu)

**Comment by adiser81** [comment]
Done. Did not help.

**Comment by MrKepzie** [comment]
What do you mean slow down ? 
The timeline starts with the first frame because in your project settings the frame range must be set to 1--X

Try changing it .

You can also set a custom frame range on the viewer which should not be necessarily the same as the project frame range.

**Comment by adiser81** [comment]
In the next video I show how it looks. http://youtu.be/FpwMMlLzI5U

**Comment by MrKepzie** [comment]
The grey range of the timeline is the range defined in the project settings.

For the node graph, i'm aware of this problem but I fail to understand at what point it starts occurring ?

Does it do it for you right away when you start Natron ? Can you determine at what point it starts doing it ?

**Comment by adiser81** [comment]
I will try to define it in the process. Now while I know that Nodegraph will slow down unexpectedly.

**Comment by sozap** [comment]
I'm experiencing the same issue on linux 64 bits.
For me it's not when I open my project, but after a few minutes the nodeGraph is not refreshing in realtime...
It's appending on a big project with lots of nodes and footages, for smaller ones (1 read and 5 to 10 nodes) it doesn't seems to show up. I've got a lot of ram (32Go) and also a lot of CPU cores (24 IIRC) it's at work so I don't know exactly the computer specs ...
I'll try to see if I can get more clues

**Comment by MrKepzie** [comment]
https://github.com/MrKepzie/Natron/commit/b7dc5693454168f034b7bc7887e777edbc376a82
