### ISSUE TITLE
setValue or setValueAtTime with no effect should not trigger instanceChanged

### ISSUE THREAD

**Issue by devernay** [MrKepzie/Natron#425]
When a setValue or a setValueAtTime doesn't change anything, it should not trigger an instanceChanged action.

Different cases have to be considered, depending wether the parameter is animated or not, and there exists a keyframe at current time or not.

**Comment by MrKepzie** [comment]
https://github.com/MrKepzie/Natron/commit/b7dc5693454168f034b7bc7887e777edbc376a82
