### ISSUE TITLE
kFnOfxParamPropGroupIsTab doesn't work as expected

### ISSUE THREAD

**Issue by devernay** [MrKepzie/Natron#427]
there should be one tabwidget for each hierarchy level

a tabwidget may be inside a group or inside a tabwidget, if the group has a group as parent.

example: TuttleImageStatistics

**Comment by MrKepzie** [comment]
Fixed in python branch

**Comment by devernay** [comment]
maybe backport to workshop?

**Comment by MrKepzie** [comment]
trop de changements pour faire un backport
