### ISSUE TITLE
Segmentation fault (roto?)

### ISSUE THREAD

**Issue by synk-a-dynka** [MrKepzie/Natron#429]
I get Segmentation faults very often in a scene. It started after I added a roto. Deleting the roto doesn't get rid of the problem.
An earlier version of the file is alright, the difference is the roto layer and some Transformation animation.

debug dump:
http://pastebin.com/3xbKm19B

The faulty file (without source material of course...):
https://dl.dropboxusercontent.com/u/2811229/TEMP/Lilla-snigel_comp-hela-natron_1.5_dual-viewer.ntp

**Comment by MrKepzie** [comment]
Thanks for the dump, i see the problem and will fix it asap 

The bug is from an image fetched from the cache

**Comment by MrKepzie** [comment]
https://github.com/MrKepzie/Natron/commit/b7dc5693454168f034b7bc7887e777edbc376a82
