### ISSUE TITLE
Blender's 8/16bit Tiff files won't open

### ISSUE THREAD

**Issue by blackearth2014** [MrKepzie/Natron#431]
Tiff files rendered out in Blender shows up black in Natron. The Tiff files opens up in all the other compositing apps.

**Comment by MrKepzie** [comment]
please send us a sample

**Comment by blackearth2014** [comment]
It was a Sean Kennedy issue from Facebook NatronNation Group.  This is his message "I can't at the moment, it's for a feature film. NDA and all that." I will let him Know that you are requesting something.

**Comment by MrKepzie** [comment]
Can you then render an image in Blender and give it to me so I can try (I don’t have blender ATM and a limited internet connection)

**Comment by blackearth2014** [comment]
I sent you the file through facebook NatronNation Group. Tiff files can't be uploaded here.  I believe this might be an PC issue. I have loaded the file on my Mac and it works. It was Natron 1.1.0 first release on my PC that the tiff files didn't load. I hope this helps.

**Comment by MrKepzie** [comment]
This is already fixed.
