### ISSUE TITLE
Loading files form folders with "Ä Ö Ü" does not work

### ISSUE THREAD

**Issue by DFVFX** [MrKepzie/Natron#433]
Hey! Im absolute new to Natron.
My 1st try was to import a file from a folder that includes the characters "ä ö ü".
It didn´t work! Natron does not show anything.
Importing the same files from an other folder (without germany special-charactes) works!

**Comment by MrKepzie** [comment]
I will look into it

**Comment by MrKepzie** [comment]
Are you on MacOSX Yosemite by any chance ?

This is a bug introduced by Apple with OS X 10.10. 
https://bugreports.qt.io/browse/QTBUG-40449

Qt has no bug fix yet for it, maybe we should include it ourselves .

**Comment by DFVFX** [comment]
Im on Windows 7 64BIT

**Comment by MrKepzie** [comment]
Is this not working only when drag&dropping or with the file dialog too ?

**Comment by DFVFX** [comment]
In both cases. The IO-Node is just black.
When i load the same file from a location without ÄÖÜ its okay!

By the way- why cant i edit in real-time?
Its an AVI-File. Compressed with lagarith losless-codec and a frame size of 1152x576px @23,976FPS.
All the other tools give me real-time-playback and scrubbung. Natron not :/.

I have an AMD FX 4100 with 4x3,6 GHz, SSD Systemdrive, 16GB-RAM, 2 Nvidia GPUs (440GT and 780GTX).

**Comment by MrKepzie** [comment]
Natron is not a VLC media-like application, it reads images and convert them to 32bit fp for loss-less image editing. 
What happens is that most video software  read images as 8bit, hence is almost 4x faster.

I do not recommend the usage of video files for compositing as they are generally not using lossless codecs and not the few codecs that are, are read slower than if it were an image sequence in the first place.

**Comment by DFVFX** [comment]
I know ... just compared to Fusion. 
What is interesting ... in Fusion i can also see the caching process (green mark in timeline).
In Natron there are green markers, too, but they directly disappear like the cache is direcly deleted during scrubbing. What means, it seems that caching is not working right? Maybe there is something i have to set-up?

**Comment by MrKepzie** [comment]
No, scrubbing in Natron is actually implemented this way:

- everytime you move the mouse, a new render is triggered
- if the mouse moves again, it aborts all previous ongoing renders (hence the green markers disappearing), renders that ended successfully are not removed from cache though
This is for efficiency of the memory pool that we did that.

**Comment by DFVFX** [comment]
Ah i understand ... That means i have to render the actual changes and then i can proceed with this output? Or will previous render results be deleted from cache and the output rerenders everything?
What i think would be the best workflow is when caching would be permanently till i made any changes.There is no need for rerendering when no changes werde done?

**Comment by MrKepzie** [comment]
Caching is permanent, its just that when you scrub, the frames that are no longer pointing to the current time of the timeline will abort rendering, hence the green marker disappearing.

**Comment by MrKepzie** [comment]
This is fixed
