### ISSUE TITLE
Feature request: Option to force viewer mouse action

### ISSUE THREAD

**Issue by nicholascarroll** [MrKepzie/Natron#434]
If an OFX plugin reads the mouse click on viewer and does not allow deactivating that, you cannot then grab the wipe control. So please allow a modifier key to prevent mouse click from passing through to the plugin.

**Comment by MrKepzie** [comment]
Just close the settings panel of the plug-in (or minimise it) and the overlay won’t catch anything. 
You can quickly close the panel by hovering your mouse over the panel and pressing escape.
