### ISSUE TITLE
TextOIIO -> return doesn't work

### ISSUE THREAD

**Issue by adallafontana** [MrKepzie/Natron#435]
In TextOIIO return for newline text doesn't work .
But in TuttleText node too.

**Comment by devernay** [comment]
Someone should work on a real text node... see https://github.com/MrKepzie/Natron/wiki/Google-Summer-of-Code---GSoC-2015-ideas

**Comment by olear** [comment]
Newlines works in openfx-magick and openfx-test, but I hit #311  

Couldn't find any info regarding OIIO render_text and newlines.

**Comment by olear** [comment]
https://github.com/olear/openfx-arena/releases/tag/MagickText-v1.0

**Comment by adallafontana** [comment]
Hi Olear,
I tried to install in the right place on linux/Ubuntu 14.04, but Natron 2.0 doesn't see the plug-in:

/usr/OFX/Plugins/Text.ofx.bundle

**Comment by olear** [comment]
https://github.com/olear/openfx-arena/issues/24#issuecomment-98066275

**Comment by adallafontana** [comment]
aah! under Write :) 
I looked in all others...
ok works thank you.

**Comment by olear** [comment]
Yeah, it's a generator so it's located in the 'Image' category :)

**Comment by MrKepzie** [comment]
btw there still seem to be the issue with the render scale, have you got any clue what’s going on ?

Also make sure your “Implode” and “Swirl” plug-in are not generators: they are filters. Otherwise Natron will not propose the same hints when auto-connecting in the node graph and stuff

**Comment by olear** [comment]
Don't know about the render issue yet, will fix the other plugins later.

**Comment by MrKepzie** [comment]
@olear We will use the text plug-in in arena from 2.0 on

**Comment by olear** [comment]
Please use the 'Text' branch, since the rest of the plugins have third-party issues. Did you get ImageMagick working in VS?
