### ISSUE TITLE
curve editor -> bug when I try move selection points

### ISSUE THREAD

**Issue by adallafontana** [MrKepzie/Natron#438]
when I try to move in x-y more than one point selected in box selection, often I lose some points on "street" and the undo doesn't works, the points lose them position forever.

**Comment by MrKepzie** [comment]
Can you post a video show casing the bug ?

**Comment by adallafontana** [comment]
https://www.dropbox.com/s/fuq1ifce0pd84yh/bug.zip?dl=0

obvious if you are in huge zoom doesn't happen so often, but if you need move some point on large space or a big selection this happen often.

**Comment by adallafontana** [comment]
after second 15 there are some attempts to undo to initial state but without success

**Comment by MrKepzie** [comment]
Thanks I'll look into it

**Comment by MrKepzie** [comment]
I fail to reproduce the bug on my side

**Comment by MrKepzie** [comment]
https://github.com/MrKepzie/Natron/commit/0d82c5ed2cf497b93da6311e527cdf87ed5e3f23 fixes it
