### ISSUE TITLE
NodeGraph/CurveEditor: full screen windows -> spacebar issue

### ISSUE THREAD

**Issue by adallafontana** [MrKepzie/Natron#440]
If I use spacebar key for enlarge windows to full screen with NodeGraph and CurveEditor the property panel hold on screen.

**Comment by MrKepzie** [comment]
This is wanted so that you can still change parameters while having the node graph and curve editor expanded

**Comment by adallafontana** [comment]
Ok no problem if you and other like so....., but IMHO doesn't have sense, spacebar key in hystory of node based compositor, Shake, Nuke... enlarge the windows to full screen and the compositors use this command for fast/quick view of keyframe, select, move, and so on, if you are working like you said is better create a specific layout on two screen.

thanks

a.

**Comment by MrKepzie** [comment]
I don't think this is a bug, maybe if more people have the same feeling we can make something about it, I'm not closed to changing it but I close the thread on the issue tracker, you should open a thread on the forums for it I think
