### ISSUE TITLE
color sample linear space -> issue

### ISSUE THREAD

**Issue by adallafontana** [MrKepzie/Natron#441]
![screenshot from 2015-02-04 10 15 28](https://cloud.githubusercontent.com/assets/8054856/6037733/00907fc4-ac57-11e4-9e18-592949f49249.jpg)
In linear space workflow the color in the selected color box doesn't corrisponde of color in the viewer, in the preference is flag the color picker in linear space but on/off doesn't change.

**Comment by MrKepzie** [comment]
The “Linear color picker” option is when clicking on the viewer with the picker:
If checked, the colour will be sampled as linear and the R,G,B[,A] color will be set to the linear value.
If unchecked, the colour will be in the colour-space of the Viewer (i.e sRGB)

The colour dialog on the other hand in in sRGB colour-space hence when picking a colour from the dialog, this will be sRGB
