### ISSUE TITLE
Range in Project Setting

### ISSUE THREAD

**Issue by rcspam** [MrKepzie/Natron#443]
Hi,

The WriteFFmpeg node does not care the project setting range ( locked or not locked)
It take the range of the longest ReadOIIO node. Is it a bug or normal.
On the other hand, after render, the frame numbers in the read nodes are locked.
Regards

**Comment by MrKepzie** [comment]
Use the parameter "Frame range", and set it to "Project frame range". By default it is on "Union of input ranges" which is what you describe.
