### ISSUE TITLE
Natron crashes when playing image sequence with ffmpeg

### ISSUE THREAD

**Issue by jharog** [MrKepzie/Natron#444]
Using natron 1.1.0, commit ee0230f14894a13468f0cb97270fbf68646fb419.
If I open a jpeg image sequence with the ReadFFmpeg reader instead of the
readOIIO one Natron crashes as soon as I start to play the sequence.

**Comment by MrKepzie** [comment]
Fixed in https://github.com/MrKepzie/openfx-io/commit/9c8483d9bac40c69d73bc3aa5752e6f5ae611680
