### ISSUE TITLE
Merge more than two inputs?

### ISSUE THREAD

**Issue by crydalch** [MrKepzie/Natron#446]
Hello! I just tried out Natron recently, and really enjoyed it so far! One thing I noticed that's pretty frustrating (leads to many more nodes than necessary): Merge only supports two inputs.

![2015-02-05--1423188007_screenshot](https://cloud.githubusercontent.com/assets/458856/6073298/3fc19c5e-ad61-11e4-82e4-3b4375de98dd.png)

Is this a limitation of MergeOFX/TuttleMerge? Or does it have to do with the Natron Core?

Thanks!

**Comment by adallafontana** [comment]
I think all node based compositor works like this and is what I aspect from Natron, but maybe I don't understand what do you mean exactly.

**Comment by sozap** [comment]
It's the same behaviour of nuke or blender compositor...
only 2 inputs for merge nodes and a mask

**Comment by crydalch** [comment]
In Nuke you can merge more than two inputs (only image I could find, don't have access to Nuke anymore):

![tu4-1](https://cloud.githubusercontent.com/assets/458856/6084913/32583440-adea-11e4-94dc-127197a11d06.jpg)

I didn't realize it was considered a 'bad practice' until now, as I've done that many times when creating some blur/glow/intensity in Nuke.

**Comment by sozap** [comment]
My bad, I've used nuke for a long time, but never used that feature...
in fact I don't think it's a bad practice , but I found better to tweak each merge separately...
But for some cases that could become handy to merge a lot of things altogether,

You've changed my point of view so easily, now I feel dirty ....

**Comment by devernay** [comment]
The result of merging with more than two inputs in Nuke is:
A3*(A2*(A1*B)))
where * is the merge operation. It is thus 100% equivalent to cascading Merge nodes.
The problem is mainly UI: Natron doesn't "hide" additional inputs with a small handle to get the next one, as Nuke does. See for example the Switch node in Natron. I could easily add this functionality in Merge, but the Merge node in Natron would then have a zillion inputs, unless @MrKepzie does something.

**Comment by crydalch** [comment]
What if Merge had a parameter on it, to dynamically create (or unwide) the multiple A inputs? Would that me much easier that modifying the Natron core to hide all unconnected inputs except 1?

**Comment by MrKepzie** [comment]
It has to be done in Natron directly, it cannot be dynamically set from the plug-in

**Comment by MrKepzie** [comment]
I will try to add it for 2.0

**Comment by crydalch** [comment]
Awesome, I look forward to putting it through its paces! Thanks!

**Comment by MrKepzie** [comment]
Implemented

**Comment by crydalch** [comment]
Finally tested this out on a snapshot build, and it works **perfectly**! Thank you so much, and kudos on implementing it so well and so quickly!

![screenshot-area-2015-02-26-224612](https://cloud.githubusercontent.com/assets/458856/6408466/8faa3fe2-be09-11e4-8850-b28ef8203d10.png)

Cheers!
