### ISSUE TITLE
BackDrop -> limited title line text space -> enhancement

### ISSUE THREAD

**Issue by adallafontana** [MrKepzie/Natron#447]
I don't know how is setup the automatic return but IMHO there is too little space and is not relative to the BackDrop size. 
![screenshot from 2015-02-06 09 01 00](https://cloud.githubusercontent.com/assets/8054856/6076147/294630ec-addf-11e4-899a-93e433815fd2.jpg)

**Comment by MrKepzie** [comment]
Please take a look at the matter once the python branch will be merged into workshop as we changed quite a lot of stuff regarding backdrop's layout.

**Comment by adallafontana** [comment]
Ok thanks, I will waiting
