### ISSUE TITLE
Disable Node shortcut (D) is not responding: Natron-snapshots-02-06-2015-20-42 Mac

### ISSUE THREAD

**Issue by blackearth2014** [MrKepzie/Natron#449]
The disable node shortcut (D) is not responding sine Natron-snapshots-02-06-2015-20-42 Mac release. Also the edit menu command is not responding either.

**Comment by adallafontana** [comment]
confirm, linux too

**Comment by MrKepzie** [comment]
Works fine here, wait for the next snapshot and confirm please.

**Comment by adallafontana** [comment]
b592f92dd5f22687539270b3a6954c26afb2143b works right.

**Comment by blackearth2014** [comment]
It works good now.
