### ISSUE TITLE
Color Plot Feature: ColorLookup Node

### ISSUE THREAD

**Issue by blackearth2014** [MrKepzie/Natron#450]
Is it possible to get a color plot feature in the ColorLookup node? I use this node as a secondary color screen suppression. It would be nice to be able to plot a hue on the curve(s) to know where to modify the color on the curve.

![colorlookup_node](https://cloud.githubusercontent.com/assets/7956901/6100696/48a83fac-afe2-11e4-977d-b26190838da7.png)

**Comment by devernay** [comment]
We can draw something in the back of this curve, such as a histogram, using:

http://openfx.sourceforge.net/Documentation/1.3/ofxProgrammingReference.html#kOfxParamPropParametricInteractBackground

But each curve modifies a wide range of hues, so I don't see what color could be drawn at each point

**Comment by blackearth2014** [comment]
Okay. I guess I would need to see how it looks. Thanks.

**Comment by devernay** [comment]
Are you asking for an equivalent to Nuke's HueCorrect?

**Comment by blackearth2014** [comment]
Yes, Nuke's HueCorrect Node is exactly what I am asking for.

**Comment by Montaire** [comment]
I would like to see something like that in Natron too.

**Comment by blackearth2014** [comment]
Fred here is a video link of a process that I was also requesting for the cololookup node. It is a process that can be done in davinci resolve. This is the link at http://youtu.be/syceHd54kSg.

**Comment by devernay** [comment]
Implemented in 2.1.0
