### ISSUE TITLE
Spline deformer -> enhancement

### ISSUE THREAD

**Issue by adallafontana** [MrKepzie/Natron#452]
I know there are many other stuff to be do before but I believe doesn't exist nothing like a OFX plugin on free and commercial side for it.

**Comment by devernay** [comment]
This is one of the projects we are proposing for google summer of code. Check out the wiki on github ( in progress)

**Comment by devernay** [comment]
I think we now have a spline warper / gridwarp in openfx-arena. Can someone confirm?

**Comment by olear** [comment]
I added it on the todo for next arena release, not done a lot of code yet.

**Comment by mifth** [comment]
Hi.
Sorry for a question. Is Splinewarp/Gridwarp in Natron now?
https://www.youtube.com/watch?v=SthlyRNXbkU

**Comment by devernay** [comment]
This issue was moved to NatronGitHub/Natron#95
