### ISSUE TITLE
Histogram not updating sometimes

### ISSUE THREAD

**Issue by Montaire** [MrKepzie/Natron#455]
I realized it does show the viewer, but failed to update.
I connected the viewer node to an another reader and Natron froze.
Also I loaded up the file again and I cant reproduce the error.

**Comment by Montaire** [comment]
After some testing I realsied the setMaster setRGB... buttons make the update fail.

**Comment by MrKepzie** [comment]
This is fixed now, we'll probably release a small revision patch to the release 1.2 to apply it
