### ISSUE TITLE
TextOIIO - No Overlay Controls: Natron v1.2 Viewer

### ISSUE THREAD

**Issue by blackearth2014** [MrKepzie/Natron#458]
The TextOIIO node doesn't have it overlay viewer controls like previous versions.  You now have to use a transform node to adjust the XY positions. Also, the text doesn't wrap to the next line after a hard return node end of first line wrap.

![textoiio_overlay](https://cloud.githubusercontent.com/assets/7956901/6130911/88c18172-b116-11e4-9261-0923660540a1.png)

**Comment by adallafontana** [comment]
..confirm on linux too.

**Comment by MrKepzie** [comment]
Known issue, we've broken a few overlays by trying to be more inline with other OpenFX hosts regarding shadows drawing.

**Comment by MrKepzie** [comment]
This is fixed.
