### ISSUE TITLE
linked color on property panel -> enhancement

### ISSUE THREAD

**Issue by adallafontana** [MrKepzie/Natron#459]
![linked](https://cloud.githubusercontent.com/assets/8054856/6150309/d06603f6-b20e-11e4-9cd2-386a0dd91f51.jpg)
will be nice have the linked value on property panel colored in different tint (green?), now is the same blu of animated keyframe, so now we don't know what value are animated on nodes and what are linked.

**Comment by MrKepzie** [comment]
Linkage on Python branch is using expressions and is greenish.

**Comment by adallafontana** [comment]
Ok tnx, but is avaible for a test this branch? I don't understand if we need compile own or will be in the next snapshot.

**Comment by devernay** [comment]
The 2.0 snapshots will soon be available, please be patient
