### ISSUE TITLE
RGBA Tiffs files: Not reading in Natron v1.2

### ISSUE THREAD

**Issue by blackearth2014** [MrKepzie/Natron#461]
Sean Kennedy and I are having the same issues as before with our PC's trying to read theTiff 8/16bit RGB or RGBA files rendered out of Blender. Natron reads all other RGBA Tiff files from other apps.

**Comment by hyperfx** [comment]
Here are the exact TIFs I used to find this problem.

This one has no alpha channel and was rendered from Blender.
https://www.dropbox.com/s/q70a7ek40m43b8f/Blender_TIFF_no_alpha.tif?dl=0

This one has an alpha channel and was rendered from After Effects.
https://www.dropbox.com/s/dtc5tpsuugulehk/AfterEffects_TIFF_w_alpha.tif?dl=0

The Blender TIF does not open in Natron, but does open in After Effects, Blender, Photoshop, Nuke, and even Dropbox displays it.

The After Effects TIF opens in Natron, complete with the alpha channel.

**Comment by adallafontana** [comment]
![screenshot from 2015-02-12 10 10 26](https://cloud.githubusercontent.com/assets/8054856/6164452/af4f873c-b29f-11e4-9ee5-2a108d79f9a1.jpg)

I can open those tif file on linux.

**Comment by blackearth2014** [comment]
It is the Natron PC version that is not opening to Tiff files correctly.

**Comment by adallafontana** [comment]
Ah! ok for PC you mean Win, sorry.

**Comment by MrKepzie** [comment]
It is probably because of a mis-compiled OpenImageIO, I will take a look at it

**Comment by MrKepzie** [comment]
Ok I fixed it, this was because of a mis-compiled libtiff. We will soon release a 1.2.1 minor patch including small fixes.

**Comment by hyperfx** [comment]
Awesome, thanks Alex!! 

Date: Sat, 14 Feb 2015 01:50:11 -0800
