### ISSUE TITLE
multiple nodegraphs

### ISSUE THREAD

**Issue by gitwipo** [MrKepzie/Natron#463]
It would be useful to have more then one Nodegraph pane in the window layout. So that you can show the Node tree on more locations simultaneously without jumping around.

**Comment by MrKepzie** [comment]
This is already addressed with Groups in the Python branch. Just wait a little bit till it makes it into the release.

**Comment by Machiel-B** [comment]
Is there a way to reopen a a group nodegraph after you close the tab?

**Comment by MrKepzie** [comment]
Shift + Double click on the group. We will add a button soon in the settings panel

**Comment by Machiel-B** [comment]
Awesome! thanks
