### ISSUE TITLE
Git tags: do not add your project name in the tag

### ISSUE THREAD

**Issue by akien-mga** [MrKepzie/Natron#464]
Hi,

I see that since version 1.0.0, you use the ```Natron-$version``` scheme for your git tags. The problem with this is that GitHub automatically creates archives and directories named ```$repo_name-$tag```, so for your latest release it becomes ```Natron-Natron-1.2.0```, which is slightly redundant.

If I guess correctly, I suppose you use such tags so that the project name appears in the tag tarball that can be retrieve via curl or wget, e.g.: ```https://github.com/MrKepzie/Natron/archive/Natron-1.2.0.tar.gz```

If that's your main (valid) concern, please note that with GitHub's API, you can use this syntax instead:
```https://github.com/MrKepzie/Natron/archive/$tag/$whatever_you_want.tar.gz```, so you (and distributors) could use this link to have a well-named tarball (and subsequent extracted folder) if your tag was simply "1.2.0" instead of "Natron-1.2.0": ```https://github.com/MrKepzie/Natron/archive/1.2.0/Natron-1.2.0.tar.gz```

The extracted folder would still be named ```$repo_name-$tag```, i.e. in this scenario "Natron-1.2.0".

So much text for such a little detail, but hey :-)

**Comment by MrKepzie** [comment]
Hi, thanks for the report, we'll do that.
