### ISSUE TITLE
FR - 2.5d relight tool

### ISSUE THREAD

**Issue by benjamintomad** [MrKepzie/Natron#467]
Hi there,

So far I can already get some pretty good results with the available feature set, it's great!
But right now, I'm missing a relighting tool based on a normal pass. Is there any chance to see it added some time? A widget ala Blender would be pretty nice.

Thanks

**Comment by sozap** [comment]
In fact you don't need this that much, you can separate RGB channels from your normal pass and use that to do your relighting... you can invert mix together or color correct these layer to get as many light directions as you like .
Just my two cents :)

**Comment by mifth** [comment]
Relight tool is vector direction. it uses all rgb channels to create a new vector direction lighting. it‘s a bad idea to use rgb separetely.

good feature request.
@FR could you add a screenshot af the relight node so that Natron devs can understand the feature correctly?

**Comment by benjamintomad** [comment]
Hi everyone,

Here are some screenshots of different implementations. You can find some more advanced relighting tools on Nukepedia but the ones I'm showing here have the advantage of being fast and not relying on a 3d space that Natron has not (yet?). Of course, a more obvious advantage for Blender and Fusion is that you can fully test them for free.

Here you can get the screenshots and the scenes for Blender and Fusion, just re-link monkey_BTY and monkey_NRM. For Blender, just hit F12.
https://drive.google.com/folderview?id=0BxN8TwNaQzJhfkFnd2dFOTE1RUVrMDRzSTRNcUtOQWVIMThRNmc0SjBEYTM5NTB0TU1RbUk&usp=sharing

Can't provide the Nuke scene as I don't remember where we got this gizmo in the first place and our Comp supervisor is out for a few days...

The tool in Fusion is called "Shader" you can find it in the "Deep Pixel" category or simply use ctrl-space to find it like Tab in Nuke and Natron. You'll have to use a channel boolean first to feed in the normal channel. 
The interface in Blender is really nice but it's limited to diffuse shading while Fusion has more options to offer.

Hope you guys will get inspiration from those. 

Cheers, keep up the good work!

![relightblender](https://cloud.githubusercontent.com/assets/7934813/6226847/9cc95982-b699-11e4-843b-e9965f1ffecc.jpg)
![relightfusion](https://cloud.githubusercontent.com/assets/7934813/6226846/9cc89b6e-b699-11e4-8ef9-3b62106fe881.jpg)
![relightnuke](https://cloud.githubusercontent.com/assets/7934813/6226848/9cc99672-b699-11e4-8456-7413deddc88b.jpg)

**Comment by MrKepzie** [comment]
If you manage to provide us with the content of this Gizmo this could help us to provide you a tool matching it. We are not going to implement a 3D space right now, we have much things left to do in the 2D side. Bear in mind that most operations in Nuke are in fact 2D: relighting as I see it in your screenshot does not require a 3D space to work, a normals pass from Blender could do the trick.

**Comment by benjamintomad** [comment]
Actually I was thinking about that tool from a 2D point of view. Indeed it seems a bit overkill to ask for a 3D space so early and I guess it wouldn't be faster than a good old normal pass anyway.
I'll send you a gizmo by the end of the week if I can get my hands on it.

**Comment by benjamintomad** [comment]
Here's the gizmo : https://drive.google.com/file/d/0BxN8TwNaQzJhclg2elVTUUNwZ1U/view?usp=sharing
We lost track of its origin so I don't know who to credit for it :/ 
I'll dig a little and let you know if I find who did it

**Comment by MrKepzie** [comment]
Since we have the SeExpr node that provides equivalent and more functionalities than the Expression and MergeExpression nodes of Nuke, I guess you could make your own Natron PyPlug based on that Gizmo. I took a look and there are no nodes that is missing from Natron's distribution that should stop you from creating it.

**Comment by benjamintomad** [comment]
Nice! I'll have a look at that as soon as I can.

Thanks!

**Comment by adallafontana** [comment]
Is only an example for use SeExpr with the normal pass of blender:
![screenshot from 2015-03-22 08 50 22](https://cloud.githubusercontent.com/assets/8054856/6768530/2fd1456e-d071-11e4-88bc-b9fd74e1a686.jpg)

Cg=color1; #surface color
Nn=[Cs[0],Cs[1],Cs[2]]; #normal

Ln1=norm([-pos1[0],pos1[1],x1]); #light position1
color=Cg*clamp(dot(Ln1, Nn)*color2, 0, 1); #light1

Ln2=norm([-pos2[0],pos2[1],x2]); #light position2
color+=Cg*clamp(dot(Ln2, Nn)*color3, 0, 1); #light2

color

...anyway will be nice have the position 3D on SeExpr, for do this I have used 1 scalar for Z.

**Comment by MrKepzie** [comment]
Nice, just use a color parameter to get a  3D position

**Comment by adallafontana** [comment]
![screenshot from 2015-03-22 18 34 16](https://cloud.githubusercontent.com/assets/8054856/6770536/d80270a4-d0c2-11e4-8763-21e316da7604.jpg)

test with diffuse+specular(phong)
the specular exponent is control with x3


```
Nn=[Cs[0],Cs[1],Cs[2]]; #normal

Ln1=norm([pos1[1],pos1[0],-x1]); #light position1
color=clamp(dot(Ln1, Nn)*color2, 0, 1); #light1

H1=(-Ln1+-Nn)/length(Ln1+Nn);

color+=clamp((dot(H1,Nn)^(10*x3))*color3,0,1); #light2specular

color

```

**Comment by MrKepzie** [comment]
Can you show me which param is linked to what and the expression… there’s not enough info here

**Comment by adallafontana** [comment]
https://drive.google.com/file/d/0B76m0pSas0ilVVZ3Q1FBNUZ0eFU/view?usp=sharing
![relight_test](https://cloud.githubusercontent.com/assets/8054856/6770676/d995833e-d0c7-11e4-8e7f-e56fa219142c.jpg)

**Comment by juancarlosgzrz** [comment]
What about 3D now? I'ts been 3 years.
