### ISSUE TITLE
proxy mode seems don't work with proxy file

### ISSUE THREAD

**Issue by legaia** [MrKepzie/Natron#468]
proxy mode with proxy file seems don't working.

I create read with image sequence.
I add proxy sequence in Proxy File attribute (with an image with wrote "proxy" above).
I active proxy mode in the viewer, don't work, don't display sequence with "proxy"  above.

I 'm forgetting something ?

**Comment by MrKepzie** [comment]
You need to input a non-proxy file in **addition** to the proxy files. 
The proxy files will be read automatically according to the viewer zoom level and/or proxy level.
