### ISSUE TITLE
"Error while creating node" - Latest Mac OSX Snapshot

### ISSUE THREAD

**Issue by YogaFlame** [MrKepzie/Natron#469]
Hello, I was interested in trying the latest snapshot version of Natron for Mac OSX. I have it downloaded and installed but every time I open it (blank project) I get the following pop-up box:
"Error while creating node fr.inria.built-in.Viewer: declarePythonFields(): attribute app1.Viewer1 is not defined"

And when I try to add another node, say, Roto, I get the same thing:
"Error while creating node net.sf.openfx.RotoPlugin: declarePythonFields(): attribute app1.Roto1 is not defined"

Is there something I'm missing or is this an error? 

Thanks!

**Comment by Tungee** [comment]
Same here!

2015-02-17 16:35 GMT+01:00 YogaFlame <notifications@github.com>:

**Comment by MrKepzie** [comment]
Hi, the build server for MacOSX is not yet ready and I will publish when it will be available.

**Comment by Tungee** [comment]
Thank you!

2015-02-17 18:35 GMT+01:00 Alexandre Gauthier <notifications@github.com>:
