### ISSUE TITLE
Natron Allows Multiple Writes With Same Name and Path?

### ISSUE THREAD

**Issue by bvjgcigh** [MrKepzie/Natron#471]
Not sure if this should be addressed as an issue, but Natron basically allows for multiple write nodes with the same filenames and paths to be rendered out at the same time- producing a video file (which is obviously messed up). 

Perhaps, when hitting "Render all writers" or "Render all selected writers", if the user has multiple write nodes with the same filenames and paths, a warning message should be displayed. Also, same applies for incompatible codecs with containers and etc... I know the developers are working very hard on Natron- creating an impressive piece of software and that this is a very minor issue that the user can easily bypass by simply knowing what is compatible, but I just thought I'd put it out there. 

Natron 2.0.0 Snapshot from around the time this was posted.

**Comment by devernay** [comment]
There are many ways to write the same file using a different path (symbolink link, network mount, etc.).
This is really a user issue, and i don' t see how to check for such user mistakes in a portable and consistent way. Closing it for now.
