### ISSUE TITLE
Crash when loading a project

### ISSUE THREAD

**Issue by MircoBerlin** [MrKepzie/Natron#472]
Hi everyone,

I tried to load a project that I saved with no luck, neither in 1.1.0 or 1.2.0.
This also applies for me to all examples from the webpage.

I'm on WIN7, 64BIT, 6 GBRAM, i3 Processor.

It hangs at around 75% of the loading process than it crashes and I need to close 
it.

thanks for your help!

**Comment by MircoBerlin** [comment]
![9](https://cloud.githubusercontent.com/assets/11054139/6241675/9deda718-b721-11e4-8d2f-94baccd2b3e6.gif)

**Comment by MrKepzie** [comment]
Hi can you send me the project please ?

**Comment by sozap** [comment]
I've got the same issue here, with a project saved yesterday with the python build...

here is my file : https://drive.google.com/file/d/0B09O4xQL4oOLWC0taGFVbFR0NkE/view?usp=sharing

the commit : 14106e4597d1466693fbda2c9a7b0bac437dd7d8

console output : 
./Natron : ligne 31 : 10306 Erreur de segmentation  $DIR/bin/Natron -style fusion $*

**Comment by MrKepzie** [comment]
Can you paste the result starting Natron with 

./Natron -debug

**Comment by sozap** [comment]
here we go :

http://pastebin.com/nuwbc0P6

system : linux mint 64

**Comment by MrKepzie** [comment]
Note that your problem @sozap is the same as  #470 and not the same as @MircoBerlin here

**Comment by MrKepzie** [comment]
Anyway @sozap  I fail to reproduce the crash, the project loads fine here

**Comment by sozap** [comment]
arf you're lucky then :D maybe I haven't got the good snapshot, or it may be a cache problem ?

**Comment by MircoBerlin** [comment]
ok, I have a temp solution right now, I COULD load it ONLY when Natron is closed and I do a double-click from outside of Natron on the Project-File (NTP).

**Comment by MrKepzie** [comment]
Sadly without the faulty file there's nothing I can do to assist you

**Comment by bvjgcigh** [comment]
I'm not sure if this is the same person, but a vaguely remember someone saying that they were having the same problem with loading all Natron files (including the examples).

**Comment by MrKepzie** [comment]
@MircoBerlin Without your project there's nothing I can do to assist you.

**Comment by MrKepzie** [comment]
I'm going to close this as without an answer we cannot assist you unfortunately.
