### ISSUE TITLE
snap v. 2.0 7543c -> expression freeze Natron

### ISSUE THREAD

**Issue by adallafontana** [MrKepzie/Natron#473]
I tried this expression on Transform node but this freeze Natron: 

cos(Transform1.rotate.get() / 180)

Freeze, not crash, so I need kill the processes and I have not -debug output.

**Comment by MrKepzie** [comment]
Don’t set this expression on the rotate parameter otherwise you have an infinite loop!
You cannot set a value with an expression on rotate and also get the value, this is a vicious cycle

**Comment by adallafontana** [comment]
Sure you are right, for simple expression just insert: cos(frame/5)*100
because as implicit to that param
Transform1.get.... is only for link, right?

ok I understand you can closed this issue, sorry.
