### ISSUE TITLE
snap v2.0.0  f35733... crash on link expression insert

### ISSUE THREAD

**Issue by adallafontana** [MrKepzie/Natron#474]
import random;
r = random.random()
ret =  r*thisNode.qwerty.get()

###################################à

~/Natron$ ./Natron -debug
Natron
Version: 2.0.0
Copyright (C) 2015 the Natron developers
>>>Use the --help or -h option to print usage.<<<

Segmentation fault (core dumped)

####################################################à

https://www.dropbox.com/s/yvlz3lc0c4ox8uy/random_shake.ntp.zip?dl=0

![screenshot from 2015-02-18 14 01 06](https://cloud.githubusercontent.com/assets/8054856/6247619/d11feace-b776-11e4-8261-af9d3faa1852.jpg)

**Comment by MrKepzie** [comment]
Fixed, there was definitely a bug.
