### ISSUE TITLE
Floating property windows don´t "undo"

### ISSUE THREAD

**Issue by sirdavid32** [MrKepzie/Natron#479]
Floating Property panels (specifically Sapphire Lens Flare) doesn´t "undo" settings on knobs if the panel is a floating window.

**Comment by MrKepzie** [comment]
Undo in Natron is context dependant. There are several undo stacks hence if your properties window has focus, it should receive undo/redo events, however if the node graph (or any other widget with undo/Redo support) gets the focus, it will set the undo stack of the latter as the active one. I hope this answers your issue.

**Comment by sirdavid32** [comment]
Thanks! quick answer. Another issue is going on: on floating windows, if the settings are longer than the window, there should be a scroll bar to the right to "scroll down" the settings. Right now, even if I resize the window of the plugin properties, I still can´t see "the bottom settings" on the Property panel while it´s attached anywhere on the layout, shows this scrollbar. But not for the floating windows..

**Comment by sirdavid32** [comment]
No, it wasn´t solved. Saphire lens flare (the longest setting dialogue for a floating window) won´t even allow to resize floating window to see below settings.. There´s no scrollbar.
