### ISSUE TITLE
Image Sequences only loading first frame

### ISSUE THREAD

**Issue by paulchambers3D** [MrKepzie/Natron#480]
Posting here as others have noted on the forum.

Attempting to load EXR image sequences in the latest public build. Sequences are recognized in the file browser but only load the first image.

In my case I have 3 and 4 padding, e.g: 001, 0001.

**Comment by MrKepzie** [comment]
Can you try using one of the snapshots builds ? https://natron.inria.fr/snapshots/

**Comment by paulchambers3D** [comment]
I'll give it a try this weekend and let you know.

**Comment by paulchambers3D** [comment]
Just used the latest public release (Feb 19th build) and the issue is now resolved. Many thanks. And continued praise on this fantastic project in development. I'll be following closely!
