### ISSUE TITLE
snap c0b7920fbb4fe302bc2bebb8a464d7ec19eab0fe flicker rotonode+colorcorrect/gamma/grade....

### ISSUE THREAD

**Issue by adallafontana** [MrKepzie/Natron#482]
If I use one of a color correct node, gamma, grade etc.... with a roto shape I have an evident flickering,
sometime in ram preview always in render file.

https://drive.google.com/file/d/0B76m0pSas0ilQy1nR1QwcUVzRk0/view?usp=sharing

**Comment by MrKepzie** [comment]
I cannot reproduce with your project. Can you post a video ?

**Comment by adallafontana** [comment]
"I cannot reproduce with your project"

...today me too! 
I don't know, yesterday the issue was present, now when I opened the file to make video all works right, also in others file where I had the issue.
I went crazy for one day to understand the problem, no words..., you can close in case I write again.
Maybe was enough reboot the system.

**Comment by MrKepzie** [comment]
Ok, do not hesitate to reopen if it reoccurs

**Comment by socketbind** [comment]
I'm facing the same problem and I wish I could provide some specifics but it seems that color correction +   a roto mask can make the picture flicker randomly. I'm facing this issue on Ubuntu 14.04.2 LTS x64 with Natron 1.2.1 and I'm rendering using a WriteFFMPEG node (AVI, Loseless HuffYUV codec). Sometimes I can render with zero problems other times it just flickers between the enabled/disabled state.
