### ISSUE TITLE
How to render correctly an mp4 with .h264?

### ISSUE THREAD

**Issue by sirdavid32** [MrKepzie/Natron#485]
Hi, I´ve tried various settings to render a 1920x1080 and 2048x1152 movies. I´d like to output an mp4. I´m a win7 x64 user. I´ve configured iPod H.264 MP4(mpeg-4 part 14) (ipod) , Advanced - codec: Mpeg4 part 2 and I get chopped video (blocky video). And If I try .h264 from the first option and on advanced - codec: Quicktime, I get an error - it cannot render. As so with any other combination regarding .h264 from the first compression menu.

Please help me output a file as .mp4 and using .h264 as compressor. Thanks.

**Comment by MrKepzie** [comment]
Please post this on the forums. We are aware that the WriteFFMPEG node is not very user-friendly to find out a good export format. I would recommend exporting an image sequence and then doing the conversion with ffmpeg in command line
