### ISSUE TITLE
snap cb12d1dee.... DPX issue

### ISSUE THREAD

**Issue by adallafontana** [MrKepzie/Natron#487]
with this snapshot and dpx output I can't write dpx file without alpha channel like before (I have a shuffle node with RGB before to force it), if I have Opaque option active the rendering is realy slow, with Premulyiply and unmultiply is normal/fast, what is change? I just have ask for this but I renew the request, will be nice have a alpha force option in the write output.

**Comment by MrKepzie** [comment]
There was a bug in the Shuffle node and if the output was:

A.r
B.g
A.b
A.a

It would only consider the A image.
If the shuffle was in this configuration, then it was a bug. 
The next snapshot should have the fix

**Comment by MrKepzie** [comment]
Does it still happen ?

**Comment by adallafontana** [comment]
I did a test now, all seem right, I can write dpx without alpha also without force it with shuffle.
you can close

thanks
