### ISSUE TITLE
Color Correction Node saturation not working

### ISSUE THREAD

**Issue by Montaire** [MrKepzie/Natron#489]
The saturation property only working well in the master channel. 
Changing it in the Shadows/Midtones/Highlights makes the RGB fall apart
![screenshot](https://cloud.githubusercontent.com/assets/9551575/6316246/c9dffbb2-ba20-11e4-9b9e-a554de41889b.PNG)
I tested in Nuke and Fusion, and there, just the saturation changes.

**Comment by blackearth2014** [comment]
I can second this issue. Sadly, I notice this back at version 1.0, but forgot about it due to a workaround.

**Comment by MrKepzie** [comment]
I fixed it, it should be available after https://github.com/MrKepzie/Natron/commit/69e301df5f752aacc853e947fae124d77a331539
