### ISSUE TITLE
group name issue

### ISSUE THREAD

**Issue by adallafontana** [MrKepzie/Natron#491]
https://drive.google.com/file/d/0B76m0pSas0ilVlEzdkw3ZEtwVXc/view?usp=sharing

If I change the name of group this is changed only in the "label", if I create an expression with drag & drop a animation value the name remain Group1, is it right so?

**Comment by MrKepzie** [comment]
Yes this is right, the script name of a node is not meant to be changed, see http://natron.readthedocs.org/en/workshop/scriptvslabel.html <http://natron.readthedocs.org/en/workshop/scriptvslabel.html> .
The label on the other hand is what is visible on the GUI so this is fine to change it to whatever you want.
You can also change the script name of a node with the http://natron.readthedocs.org/en/workshop/PythonReference/NatronEngine/Effect.html#NatronEngine.NatronEngine.Effect.setScriptName <http://natron.readthedocs.org/en/workshop/PythonReference/NatronEngine/Effect.html#NatronEngine.NatronEngine.Effect.setScriptName> function
but beware it has to be compliant with a python variable name, and cannot be taken by any other node in which case you might break other functionalities.

**Comment by adallafontana** [comment]
ok thanks
