### ISSUE TITLE
Last Snapshot (02-21-2015) linux: Nodes can't load at startup...

### ISSUE THREAD

**Issue by rcspam** [MrKepzie/Natron#492]
Hi,
Last snapshot (02-21-2015) linux: Nodes can't load at startup...
![error while creating node_001](https://cloud.githubusercontent.com/assets/10021906/6318221/9c72c992-ba85-11e4-84db-0c6d86d4e56f.png)

If i load a project, this happens for all nodes.
Regards

**Comment by MrKepzie** [comment]
Linux distro ? 32/64 bit ? Have you touched anything to the installation ? You should have a Natron/lib/python3.4 folder and a Natron/Plugins/PySide folder.

**Comment by rcspam** [comment]
Linux 64 .  The 02-21-2015 Snapshot has lib/python3.4 folder but
 no Plugins/PySide folder.
I've installed  the last from today, same issue: lib/python3.4 folder but
no Plugins/PySide folder.
Sorry, perhaps maybe it was an oversight.


2015-02-22 15:29 GMT+01:00 Alexandre Gauthier <notifications@github.com>:

**Comment by MrKepzie** [comment]
Yes this is a bug in the build server, I’m fixing it right now

**Comment by MrKepzie** [comment]
should be ok now

**Comment by rcspam** [comment]
You mean: "output=[ r, g, b, a];"  ? 
See it in next Snapshot ?

**Comment by rcspam** [comment]
No, there will be 2 separate expressions because SeExpr does not allow to output more than a 3-dimensional vector.

So there will be a RGB expression and a separate alpha expression. The latest should only output the alpha component, will the former should output the RGB (as usual), so it would be:


RGB expr:  

color = [r, g, b]
color

alpha expr:

alpha = As
alpha

**Comment by rcspam** [comment]
In this case how to apply an expr to As, i mean for example, as i ask 
before, redirect color channels to alpha channel etc...
Sorry for my misunderstanding here.
