### ISSUE TITLE
Viewer key to turn off all overlays in a viewer ("q")

### ISSUE THREAD

**Issue by devernay** [MrKepzie/Natron#495]
There should be a key to turn off all overlays (including RoD display) and just show the image in the current viewer.
The "q" key seems to be a good choice.
Natron should display a text in the viewer to notify that overlays are off.
This is a per-viewer setting.

**Comment by fPaglia** [comment]
Isn't this behaviour already assigned to the "o" shortcut?
Il 22/feb/2015 14:21 "Frédéric Devernay" <notifications@github.com> ha
scritto:
