### ISSUE TITLE
ctrl+click+move on a node should move all nodes upstream and Ctrl+shift+click should select them

### ISSUE THREAD

**Issue by devernay** [MrKepzie/Natron#497]

**Comment by AurelyenD** [comment]
Yep, very helpful options when cleaning and ordering the trees...

**Comment by devernay** [comment]
Any chance this could be implemented for 2.0?

**Comment by devernay** [comment]
Should be implemented in 2.2, see http://forum.natron.fr/t/for-sake-of-natron-even-before-3d-system-suggested-priority-list/965/3

**Comment by devernay** [comment]
This issue was moved to NatronGitHub/Natron#97
