### ISSUE TITLE
last snapshot going in crash at launch

### ISSUE THREAD

**Issue by adallafontana** [MrKepzie/Natron#499]
~/Natron$ ./Natron -debug
Natron
Version: 2.0.0
Copyright (C) 2015 the Natron developers
>>>Use the --help or -h option to print usage.<<<

Segmentation fault (core dumped)
*** Segmentation fault
Register dump:

 RAX: 000000000497ac20   RBX: 0000000003450cc0   RCX: 00007f90291aa7f8
 RDX: 00007f90291aa818   RSI: 00007fff1e62501e   RDI: 00007f90291aa818
 RBP: 00007fff1e62501e   R8 : 0000000000000000   R9 : 0000000000000000
 R10: 0000000000000000   R11: 0000000000000000   R12: 00007f90291aa818
 R13: 0000000000000000   R14: 0000000000000000   R15: 0000000000000000
 RSP: 00007fff1e624de8

 RIP: 0000000000000060   EFLAGS: 00010206

 CS: 0033   FS: 0000   GS: 0000

 Trap: 0000000e   Error: 00000014   OldMask: 00000000   CR2: 00000060

 FPUCW: 0000037f   FPUSW: 00000000   TAG: 00000000
 RIP: 25eaa8fe   RDP: 1e6250dc

 ST(0) 0000 0000000000000000   ST(1) 0000 0000000000000000
 ST(2) 0000 0000000000000000   ST(3) 0000 0080008000800080
 ST(4) 0000 0000000000000000   ST(5) 0000 0000000000000000
 ST(6) 0000 0000000000000000   ST(7) 8000 8000000000000000
 mxcsr: 1fa5
 XMM0:  000000000000000000000000f0000000 XMM1:  000000000000000000000000f0000000
 XMM2:  000000000000000000000000f0000000 XMM3:  000000000000000000000000f0000000
 XMM4:  000000000000000000000000f0000000 XMM5:  000000000000000000000000f0000000
 XMM6:  000000000000000000000000f0000000 XMM7:  000000000000000000000000f0000000
 XMM8:  000000000000000000000000f0000000 XMM9:  000000000000000000000000f0000000
 XMM10: 000000000000000000000000f0000000 XMM11: 000000000000000000000000f0000000
 XMM12: 000000000000000000000000f0000000 XMM13: 000000000000000000000000f0000000
 XMM14: 000000000000000000000000f0000000 XMM15: 000000000000000000000000f0000000

Backtrace:

**Comment by MrKepzie** [comment]
You forgot the Backtrace didn't you ? We can't use it without the backtrace.

**Comment by adallafontana** [comment]
no backtrace... finish so.
I try relaunch.....

**Comment by adallafontana** [comment]
without -debug:

./Natron: line 31: 11319 Segmentation fault      (core dumped) $DIR/bin/Natron -style fusion $*

**Comment by adallafontana** [comment]
./Natron: line 31: 11319 Segmentation fault      (core dumped) $DIR/bin/Natron -style fusion $*
aleubu5@aleubu5-MacPro:~/Natron$ ./Natron -debug
Natron
Version: 2.0.0
Copyright (C) 2015 the Natron developers
>>>Use the --help or -h option to print usage.<<<

Segmentation fault (core dumped)
*** Segmentation fault
Register dump:

 RAX: 000000000595aed0   RBX: 00000000044582b0   RCX: 00007f68b42a67f8
 RDX: 00007f68b42a6818   RSI: 00007fff7d42bf5e   RDI: 00007f68b42a6818
 RBP: 00007fff7d42bf5e   R8 : 0000000000000000   R9 : 0000000000000000
 R10: 0000000000000000   R11: 0000000000000001   R12: 00007f68b42a6818
 R13: 0000000000000000   R14: 0000000000000000   R15: 0000000000000000
 RSP: 00007fff7d42bd28

 RIP: 0000000000000060   EFLAGS: 00010206

 CS: 0033   FS: 0000   GS: 0000

 Trap: 0000000e   Error: 00000014   OldMask: 00000000   CR2: 00000060

 FPUCW: 0000037f   FPUSW: 00000000   TAG: 00000000
 RIP: b0fa68fe   RDP: 7d42c01c

 ST(0) 0000 0000000000000000   ST(1) 0000 0000000000000000
 ST(2) 0000 0000000000000000   ST(3) 0000 0080008000800080
 ST(4) 0000 0000000000000000   ST(5) 0000 0000000000000000
 ST(6) 0000 0000000000000000   ST(7) 8000 8000000000000000
 mxcsr: 1fa5
 XMM0:  000000000000000000000000f0000000 XMM1:  000000000000000000000000f0000000
 XMM2:  000000000000000000000000f0000000 XMM3:  000000000000000000000000f0000000
 XMM4:  000000000000000000000000f0000000 XMM5:  000000000000000000000000f0000000
 XMM6:  000000000000000000000000f0000000 XMM7:  000000000000000000000000f0000000
 XMM8:  000000000000000000000000f0000000 XMM9:  000000000000000000000000f0000000
 XMM10: 000000000000000000000000f0000000 XMM11: 000000000000000000000000f0000000
 XMM12: 000000000000000000000000f0000000 XMM13: 000000000000000000000000f0000000
 XMM14: 000000000000000000000000f0000000 XMM15: 000000000000000000000000f0000000

Backtrace:


no the last line is "Bactrace:"
