### ISSUE TITLE
Natron python doesn't render in command line

### ISSUE THREAD

**Issue by sozap** [MrKepzie/Natron#505]
Natron version : bf7437d0d853310e643ad7c1c8a6aeb73917baff 
I've made a project with a NodeGroup in it, when rendering from the command line I've got this error message : 

graphiste@neptune ~/Bureau $ /mnt/Applications/Natron/Natron -b ./test_render.ntp 
Natron
Version: 2.0.0
Copyright (C) 2015 the Natron developers
>>>Use the --help or -h option to print usage.<<<

Restoring the image cache...
Restoring user settings...
Python: Loading LightWrap
Python: Loading Retouches Voiles
Python: Loading S01A
Python: Loading Splash Mix
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'app' is not defined
ERROR: Error while creating node: Error while creating node net.sf.openfx.CheckerBoardPlugin: declarePythonFields(): attribute app.CheckerBoard2 is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'app' is not defined
ERROR: Error while creating node: Error while creating node fr.inria.built-in.Group: declarePythonFields(): attribute app.LightWrap1 is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'app' is not defined
ERROR: Error while creating node: Error while creating node net.sf.openfx.ConstantPlugin: declarePythonFields(): attribute app.Constant1 is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'app' is not defined
ERROR: Error while creating node: Error while creating node fr.inria.built-in.Dot: declarePythonFields(): attribute app.Dot1 is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'app' is not defined
ERROR: Error while creating node: Error while creating node fr.inria.openfx.WriteOIIO: declarePythonFields(): attribute app.WriteOIIO1 is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'app' is not defined
ERROR: Error while creating node: Error while creating node net.sf.openfx.CheckerBoardPlugin: declarePythonFields(): attribute app.CheckerBoard2_1 is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'app' is not defined
ERROR: Error while creating node: Error while creating node net.sf.openfx.MergePlugin: declarePythonFields(): attribute app.Merge1 is not defined
ERROR: Project loader: Error while loading project: Failed to read the project file: Project file is missing a writer node. This project cannot render anything.
ERROR: Natron: Project file loading failed.

**Comment by MrKepzie** [comment]
This is because there’s a bug with the snapshot server. I fix it for the next snapshots.

**Comment by sozap** [comment]
great ! you're a bug serial killer :)

**Comment by MrKepzie** [comment]
should be ok now

**Comment by sozap** [comment]
hum, I'm trying with : 358d94cef0389c8a7ebdecf18a11a007b8817ba9
there are still issues : 

Restoring the image cache...
Restoring user settings...
Python: Loading LightWrap
Python: Loading Retouches Voiles
Python: Loading S01A
Python: Loading Splash Mix
ERROR: Error while creating node: Error while creating node fr.inria.openfx.ReadOIIO: declarePythonFields(): attribute app.SEA_LEFT is not defined
ERROR: Error while creating node: Error while creating node net.sf.openfx.MergePlugin: declarePythonFields(): attribute app.Merge_SEA is not defined
ERROR: Error while creating node: Error while creating node fr.inria.built-in.Dot: declarePythonFields(): attribute app.Dot1 is not defined
ERROR: Error while creating node: Error while creating node net.sf.openfx.MergePlugin: declarePythonFields(): attribute app.Merge_Bateau is not defined
ERROR: Error while creating node: Error while creating node fr.inria.built-in.Dot: declarePythonFields(): attribute app.Dot3 is not defined
ERROR: Error while creating node: Error while creating node com.revisionfx.RSMB: declarePythonFields(): attribute app.RSMB1 is not defined
ERROR: Error while creating node: Error while creating node net.sf.openfx.ShufflePlugin: declarePythonFields(): attribute app.Shuffle2 is not defined
ERROR: Error while creating node: Error while creating node net.sf.openfx.ShufflePlugin: declarePythonFields(): attribute app.Shuffle21 is not defined
ERROR: Error while creating node: Error while creating node net.sf.openfx.GradePlugin: declarePythonFields(): attribute app.Grade2 is not defined
ERROR: Error while creating node: Error while creating node net.sf.openfx.Invert: declarePythonFields(): attribute app.Invert1 is not defined
ERROR: Error while creating node: Error while creating node net.sf.openfx.MergePlugin: declarePythonFields(): attribute app.Merge3 is not defined
ERROR: Error while creating node: Error while creating node net.sf.openfx.ShufflePlugin: declarePythonFields(): attribute app.Shuffle1 is not defined
ERROR: Error while creating node: Error while creating node net.sf.openfx.ConstantPlugin: declarePythonFields(): attribute app.Constant1 is not defined
ERROR: Error while creating node: Error while creating node net.sf.openfx.Premult: declarePythonFields(): attribute app.Premult1 is not defined
ERROR: Error while creating node: Error while creating node net.sf.openfx.MergePlugin: declarePythonFields(): attribute app.Merge_FOG is not defined
ERROR: Error while creating node: Error while creating node fr.inria.built-in.Dot: declarePythonFields(): attribute app.Dot4 is not defined
ERROR: Error while creating node: Error while creating node net.sf.openfx.GradePlugin: declarePythonFields(): attribute app.Grade3 is not defined
ERROR: Error while creating node: Error while creating node fr.inria.openfx.ReadOIIO: declarePythonFields(): attribute app.CIEL_LEFT is not defined
ERROR: Error while creating node: Error while creating node fr.inria.openfx.ReadOIIO: declarePythonFields(): attribute app.FOG_LEFT is not defined
ERROR: Error while creating node: Error while creating node fr.inria.openfx.ReadOIIO: declarePythonFields(): attribute app.Bateau_LEFT is not defined
ERROR: Error while creating node: Error while creating node net.sf.openfx.ConstantPlugin: declarePythonFields(): attribute app.Constant11 is not defined
ERROR: Error while creating node: Error while creating node net.sf.openfx.MergePlugin: declarePythonFields(): attribute app.Merge5 is not defined
ERROR: Error while creating node: Error while creating node fr.inria.built-in.Dot: declarePythonFields(): attribute app.Dot2 is not defined
ERROR: Error while creating node: Error while creating node net.sf.cimg.CImgBlur: declarePythonFields(): attribute app.BlurCImg1 is not defined
ERROR: Error while creating node: Error while creating node net.sf.openfx.Invert: declarePythonFields(): attribute app.Invert3 is not defined
ERROR: Error while creating node: Error while creating node net.sf.openfx.MergePlugin: declarePythonFields(): attribute app.Merge6 is not defined
ERROR: Error while creating node: Error while creating node net.sf.openfx.ShufflePlugin: declarePythonFields(): attribute app.Shuffle4 is not defined
ERROR: Error while creating node: Error while creating node net.sf.cimg.CImgDilate: declarePythonFields(): attribute app.DilateCImg11 is not defined
ERROR: Error while creating node: Error while creating node net.sf.cimg.CImgBlur: declarePythonFields(): attribute app.BlurCImg4 is not defined
ERROR: Error while creating node: Error while creating node net.sf.cimg.CImgBlur: declarePythonFields(): attribute app.BlurCImg5 is not defined
ERROR: Error while creating node: Error while creating node net.sf.openfx.ColorLookupPlugin: declarePythonFields(): attribute app.ColorLookup1 is not defined
ERROR: Error while creating node: Error while creating node net.sf.openfx.ShufflePlugin: declarePythonFields(): attribute app.Shuffle3 is not defined
ERROR: Error while creating node: Error while creating node net.sf.openfx.Premult: declarePythonFields(): attribute app.Premult2 is not defined
ERROR: Error while creating node: Error while creating node net.sf.openfx.MergePlugin: declarePythonFields(): attribute app.Merge7 is not defined
ERROR: Error while creating node: Error while creating node net.sf.openfx.GradePlugin: declarePythonFields(): attribute app.Grade6 is not defined
ERROR: Error while creating node: Error while creating node fr.inria.built-in.Group: declarePythonFields(): attribute app.LightWrap1 is not defined
ERROR: Error while creating node: Error while creating node net.sf.openfx.GradePlugin: declarePythonFields(): attribute app.Grade7 is not defined
ERROR: Error while creating node: Error while creating node net.sf.openfx.switchPlugin: declarePythonFields(): attribute app.Switch1 is not defined
ERROR: Error while creating node: Error while creating node fr.inria.built-in.Dot: declarePythonFields(): attribute app.Dot10 is not defined
ERROR: Error while creating node: Error while creating node fr.inria.built-in.Dot: declarePythonFields(): attribute app.Dot11 is not defined
ERROR: Error while creating node: Error while creating node fr.inria.built-in.Dot: declarePythonFields(): attribute app.Dot12 is not defined
ERROR: Project loader: Error while loading project: Failed to read the project file: Project file is missing a writer node. This project cannot render anything.
ERROR: Natron: Project file loading failed.

**Comment by MrKepzie** [comment]
Please download the “bundled” installer, the online installer that you have probably is missing PySide and will not install it.

After installation you should have a Natron/Plugins/PySide folder, if not, this is what is causing the errors.

**Comment by sozap** [comment]
Hello,
I've installed the bundle as you said, and updated today from maintenance tool, but the issue seems still there, here is my Natron Output : 

graphiste@neptune ~/Bureau $ /mnt/Applications/Natron/NatronRenderer -b /media/Projets/Lorient/01_Lorient_Prod/03_Compo/test.ntp 
Restoring the image cache...
Restoring user settings...
OpenFX: loading fr.inria.openfx.ReadFFmpeg
OpenFX: loading fr.inria.openfx.WriteFFmpeg
OpenFX: loading fr.inria.openfx.ReadPFM
OpenFX: loading fr.inria.openfx.WritePFM
OpenFX: loading fr.inria.openfx.ReadOIIO
OpenFX: loading fr.inria.openfx.WriteOIIO
OpenFX: loading fr.inria.openfx.OIIOText
OpenFX: loading fr.inria.openfx.OIIOResize
OpenFX: loading fr.inria.openfx.OCIOCDLTransform
OpenFX: loading fr.inria.openfx.OCIOColorSpace
OpenFX: loading fr.inria.openfx.OCIOFileTransform
OpenFX: loading fr.inria.openfx.OCIOLogConvert
OpenFX: loading fr.inria.openfx.OCIOLookTransform
OpenFX: loading fr.inria.openfx.RunScript
OpenFX: loading net.sf.openfx.AddPlugin
OpenFX: loading net.sf.openfx.AdjustRoDPlugin
OpenFX: loading net.sf.openfx.anaglyphPlugin
OpenFX: loading net.sf.openfx.CheckerBoardPlugin
OpenFX: loading net.sf.openfx.ChromaKeyerPlugin
OpenFX: loading net.sf.openfx.Clamp
OpenFX: loading net.sf.openfx.ClipTestPlugin
OpenFX: loading net.sf.openfx.ColorCorrectPlugin
OpenFX: loading net.sf.openfx.ColorMatrixPlugin
OpenFX: loading net.sf.openfx.RGBToHSVPlugin
OpenFX: loading net.sf.openfx.HSVToRGBPlugin
OpenFX: loading net.sf.openfx.RGBToHSLPlugin
OpenFX: loading net.sf.openfx.HSLToRGBPlugin
OpenFX: loading net.sf.openfx.RGBToHSIPlugin
OpenFX: loading net.sf.openfx.HSIToRGBPlugin
OpenFX: loading net.sf.openfx.RGBToYCbCrPlugin
OpenFX: loading net.sf.openfx.YCbCrToRGBPlugin
OpenFX: loading net.sf.openfx.RGBToYUVPlugin
OpenFX: loading net.sf.openfx.YUVToRGBPlugin
OpenFX: loading net.sf.openfx.RGBToXYZPlugin
OpenFX: loading net.sf.openfx.XYZToRGBPlugin
OpenFX: loading net.sf.openfx.RGBToLabPlugin
OpenFX: loading net.sf.openfx.LabToRGBPlugin
OpenFX: loading net.sf.openfx.ConstantPlugin
OpenFX: loading net.sf.openfx.CopyRectanglePlugin
OpenFX: loading net.sf.openfx.CornerPinPlugin
OpenFX: loading net.sf.openfx.CornerPinMaskedPlugin
OpenFX: loading net.sf.openfx.CropPlugin
OpenFX: loading net.sf.openfx.Deinterlace
OpenFX: loading net.sf.openfx.DifferencePlugin
OpenFX: loading net.sf.openfx.DissolvePlugin
OpenFX: loading net.sf.openfx.FrameBlend
OpenFX: loading net.sf.openfx.GammaPlugin
OpenFX: loading net.sf.openfx.GodRays
OpenFX: loading net.sf.openfx.GradePlugin
OpenFX: loading net.sf.openfx.HSVToolPlugin
OpenFX: loading net.sf.openfx.ImageStatistics
OpenFX: loading net.sf.openfx.Invert
OpenFX: loading net.sf.openfx.joinViewsPlugin
OpenFX: loading net.sf.openfx.KeyerPlugin
OpenFX: loading net.sf.openfx.MergePlugin
OpenFX: loading net.sf.openfx.mixViewsPlugin
OpenFX: loading net.sf.openfx.MultiplyPlugin
OpenFX: loading net.sf.openfx.Noise
OpenFX: loading net.sf.openfx.NoOpPlugin
OpenFX: loading net.sf.openfx.oneViewPlugin
OpenFX: loading net.sf.openfx.Radial
OpenFX: loading net.sf.openfx.Ramp
OpenFX: loading net.sf.openfx.Premult
OpenFX: loading net.sf.openfx.Unpremult
OpenFX: loading net.sf.openfx.Rectangle
OpenFX: loading net.sf.openfx.Retime
OpenFX: loading net.sf.openfx.ColorLookupPlugin
OpenFX: loading net.sf.openfx.RotoPlugin
OpenFX: loading net.sf.openfx.SaturationPlugin
OpenFX: loading net.sf.openfx.ShufflePlugin
OpenFX: loading net.sf.openfx.sideBySidePlugin
OpenFX: loading net.sf.openfx.switchPlugin
OpenFX: loading net.sf.openfx.timeOffset
OpenFX: loading net.sf.openfx.TrackerPM
OpenFX: loading net.sf.openfx.TransformPlugin
OpenFX: loading net.sf.openfx.TransformMaskedPlugin
OpenFX: loading net.sf.openfx.DirBlur
OpenFX: loading net.sf.openfx.VectorToColorPlugin
OpenFX: loading net.sf.cimg.CImgBlur
OpenFX: loading net.sf.cimg.CImgBilateral
OpenFX: loading net.sf.cimg.CImgBilateralGuided
OpenFX: loading net.sf.cimg.CImgDenoise
OpenFX: loading net.sf.cimg.CImgDilate
OpenFX: loading net.sf.cimg.CImgEqualize
OpenFX: loading net.sf.cimg.CImgErode
OpenFX: loading net.sf.cimg.CImgErodeSmooth
OpenFX: loading net.sf.cimg.CImgGuided
OpenFX: loading net.sf.cimg.CImgHistEQ
OpenFX: loading net.sf.cimg.CImgNoise
OpenFX: loading net.sf.cimg.CImgPlasma
OpenFX: loading net.sf.cimg.CImgRollingGuidance
OpenFX: loading net.sf.cimg.CImgSharpenInvDiff
OpenFX: loading net.sf.cimg.CImgSharpenShock
OpenFX: loading net.sf.cimg.CImgSmooth
Python: Loading Bevel_FX
Python: Loading LightWrap
Python: Loading make_titlable
Python: Loading Retouches Voiles
Python: Loading S01A
Python: Loading Splash Mix
Python: Loading Stamp
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'app' is not defined
ERROR: Error while creating node: Error while creating node net.sf.openfx.CheckerBoardPlugin: declarePythonFields(): attribute app.CheckerBoard1 is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'app' is not defined
ERROR: Error while creating node: Error while creating node net.sf.cimg.CImgBlur: declarePythonFields(): attribute app.BlurCImg1 is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'app' is not defined
ERROR: Error while creating node: Error while creating node fr.inria.openfx.WriteOIIO: declarePythonFields(): attribute app.WriteOIIO1 is not defined
ERROR: Project loader: Error while loading project: Failed to read the project file: Project file is missing a writer node. This project cannot render anything.
ERROR: Natron: Project file loading failed.

Natron : 07d88458628a39e398414ccf9609422014e6e807

Do you think I've missed something ?

**Comment by MrKepzie** [comment]
Do you have the Natron/Plugins/PySide folder ?
If not, your installation is not good, update with this one instead:

https://sourceforge.net/projects/natron/files/snapshots/linux64/repo/Natron_Linux_bundle_snapshot_x86-64bit.tgz/download <https://sourceforge.net/projects/natron/files/snapshots/linux64/repo/Natron_Linux_bundle_snapshot_x86-64bit.tgz/download>

If it still does not work, poke me

**Comment by sozap** [comment]
yess, sadly the installation looks correct :

graphiste@neptune /mnt/Applications/Natron/Plugins $ ls
AnisotropicDiffusion.ofx.bundle  LensDistort.ofx.bundle
BitDepth.ofx.bundle              LocalMaxima.ofx.bundle
Blur.ofx.bundle                  MathOperator.ofx.bundle
CheckerBoard.ofx.bundle          Merge.ofx.bundle
CImg.ofx.bundle                  Misc.ofx.bundle
ColorBars.ofx.bundle             NlmDenoiser.ofx.bundle
ColorCube.ofx.bundle             Normalize.ofx.bundle
ColorGradation.ofx.bundle        Pinning.ofx.bundle
ColorSuppress.ofx.bundle         PushPixel.ofx.bundle
ColorTransfer.ofx.bundle         PySide
ColorWheel.ofx.bundle            Ramp.ofx.bundle
Component.ofx.bundle             Resize.ofx.bundle
Constant.ofx.bundle              rsmb.ofx.bundle
Crop.ofx.bundle                  rsmbvectors.ofx.bundle
Flip.ofx.bundle                  SeExpr.ofx.bundle
FloodFill.ofx.bundle             segment.ofx.bundle
Gamma.ofx.bundle                 Sobel.ofx.bundle
IdKeyer.ofx.bundle               Text.ofx.bundle
inpaint.ofx.bundle               Thinning.ofx.bundle
Invert.ofx.bundle                TimeShift.ofx.bundle
IO.ofx.bundle

**Comment by MrKepzie** [comment]
I tested on fresh Ubuntu 14.04, Fedora 18, Fedora 20, CentOS 6.2, Natron works fine there.

There must be an error either with the installation of Natron, or maybe because you have changed the environment variable PYTHONPATH somehow

**Comment by sozap** [comment]
My bad, It may come from our renderfarm software CGRU... thanks for your help !
