### ISSUE TITLE
Merge node(over) without alpha wrong blending.

### ISSUE THREAD

**Issue by Montaire** [MrKepzie/Natron#506]
![screenshot](https://cloud.githubusercontent.com/assets/9551575/6334229/b71f738a-bb93-11e4-9b0f-393869ba810f.PNG)
If source has no alpha, merge node not working as excepted in over, under mode.

**Comment by MrKepzie** [comment]
See https://github.com/MrKepzie/Natron/issues/490, this is already fixed.
