### ISSUE TITLE
TextOIIO Interactive - Interactive Operator

### ISSUE THREAD

**Issue by blackearth2014** [MrKepzie/Natron#508]
The interactive operator parameter in the TextOIIO node doesn't update when checked.

**Comment by MrKepzie** [comment]
The parameter should not exist anymore, instead the property of the Preferences of Natron 
"Render on editing finished only" should do the trick. However see https://github.com/MrKepzie/Natron/issues/448 , the interactive mode is not yet implemented for plug-in overlays.

**Comment by blackearth2014** [comment]
Okay thanks
