### ISSUE TITLE
Last snapshot doesn't open file in parameter (command line)...

### ISSUE THREAD

**Issue by rcspam** [MrKepzie/Natron#509]
Last snapshot doesn't open file in parameter (command line). It doesn' care.

$ .../Natron_snapshot/Natron ' 'foo.ntp'

This command line open Natron and that's all.

**Comment by rcspam** [comment]
Small correction: it's happened only when there is  'spaces' or 'special characters' in the path.

**Comment by devernay** [comment]
did you put quootes around the path?
as in
Natron "this file.ntp"
or
Natron 'that file.ntp'
?

**Comment by rcspam** [comment]
Of course...
I must use the Natron file menu ...

Speaking of which, as i suggested in #419, it should be included a "%U parameter" in the exec option in Natron.desktop file (linux) to have Natron in the application menu.

[Desktop Entry]
Version=1.0
Type=Application
Terminal=false
Name=Natron
MimeType=application/x-ntp;
**Exec=/PATH_TO_NATRON/Natron %U**
GenericName=Compositing software
Comment=Node-graph based compositing software
Icon=natronIcon256_linux
Categories=Graphics;2DGraphics;RasterGraphics;

Regards

**Comment by rcspam** [comment]
More info here:
http://standards.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html#exec-variables

**Comment by MrKepzie** [comment]
I have added the %U to the .desktop file, it will be available in the next snapshot

**Comment by rcspam** [comment]
cool ;)

**Comment by rcspam** [comment]
Sorry, last "built on March 3" snapshot doesn't solve this issue, alwaus impossible to open a file (with 'spaces' or 'special characters' in the path)...

**Comment by MrKepzie** [comment]
Works fine here:

./NatronRenderer "/Users/alexandre/NatronProjects/Folder with space/bug space.ntp"

Does render well

**Comment by rcspam** [comment]
Last Snapshot (on march 18):
No, it doesn't for me.
![screenshot1](https://cloud.githubusercontent.com/assets/10021906/6717575/bca085ac-cdad-11e4-95ea-3221294aec4d.png)
or
![screenshot3](https://cloud.githubusercontent.com/assets/10021906/6717656/7037c026-cdae-11e4-8a19-1ba9346386aa.png)

If i create a symlink, it launch...
![screenshot2](https://cloud.githubusercontent.com/assets/10021906/6717574/bc9c6d28-cdad-11e4-9a63-227d0f762375.png)

Another problem is that, i don't know why, it doesn't want to render on command line as well, because it render with GUI...

**Comment by olear** [comment]
Should work:
```
--- Natron.orig	2015-03-22 16:48:07.681132379 +0100
+++ Natron	2015-03-22 16:47:15.594132450 +0100
@@ -25,7 +25,7 @@
 
 if [ "$1" == "-debug" ]; then
   export SEGFAULT_SIGNALS="all"
-  catchsegv $DIR/bin/Natron.debug -style fusion $*
+  catchsegv $DIR/bin/Natron.debug -style fusion "$*"
 else
-  $DIR/bin/Natron -style fusion $*
+  $DIR/bin/Natron -style fusion "$*"
 fi
--- NatronRenderer.orig	2015-03-22 16:49:36.151132228 +0100
+++ NatronRenderer	2015-03-22 16:49:46.808132215 +0100
@@ -25,7 +25,7 @@
 
 if [ "$1" == "-debug" ]; then
   export SEGFAULT_SIGNALS="all"
-  catchsegv $DIR/bin/NatronRenderer.debug -style fusion $*
+  catchsegv $DIR/bin/NatronRenderer.debug -style fusion "$*"
 else
-  $DIR/bin/NatronRenderer -style fusion $*
+  $DIR/bin/NatronRenderer -style fusion "$*"
 fi
```

**Comment by MrKepzie** [comment]
I have updated the Natron.sh script.
Please download the next snapshot (in about ~1h). You will need the new installer that will be uploaded, do not use the maintenance tool from your installation

**Comment by rcspam** [comment]
Good news ;)

**Comment by rcspam** [comment]
Problem with this snapshot:
All my read nodes are disappeared after open my .ntp !!

**Comment by MrKepzie** [comment]
Update with the next one, this was a faulty build.

**Comment by rcspam** [comment]
Sorry but always no read nodes appear after last upgrade from downloaded snapshot.

**Comment by rcspam** [comment]
"Re-Hi" MrKepzle,
All is right now...
except to open files with specials character in the name (e. g. [second screenshot](https://cloud.githubusercontent.com/assets/10021906/6717656/7037c026-cdae-11e4-8a19-1ba9346386aa.png) in a precedent post), NatronRender doesn't find the file and Natron open a new project without error.

**Comment by olear** [comment]
Can you upload one of the project files with special chars?

**Comment by rcspam** [comment]
No problem:  https://dl.dropboxusercontent.com/u/2677320/D%C3%A8D.ntp
But i think it's happened because a non escape variable path somewhere...

**Comment by olear** [comment]
Hmm, first I though that the shell wrapper was the problem, but it's probably in Natron (or Qt). Will try to resolve.

**Comment by MrKepzie** [comment]
Does it still happen ?

**Comment by rcspam** [comment]
yes

**Comment by rcspam** [comment]
Only name with "éà ..." , name with space are ok !

**Comment by rcspam** [comment]
Cool thanx ;)
