### ISSUE TITLE
linking values

### ISSUE THREAD

**Issue by DrJ0nes** [MrKepzie/Natron#510]
sorry for the cross posting

yes this is a simple one but very important one.

So i guess this is more of a design thing than any thing.

the use of an interface to link values and then the need to use a pull down menu to select the value to link to is sooooooo (sorry) bad by default it does not link to the same value but to the first in the menu "R" and once again there are so many to choose from and with the menus so tightly packed it is a drain to use.

So I guess the bug is if for example you choose to link a "blur size" value to the "R" value in another node (say a blur node) the "size vale" appears to be linked but does not follow the master value hence looks like the linking is busted, a drag and drop system would fix this with the use of changing pointer icons to indicate value acceptability 

as far as I can figure out there is no drag and drop option from, copying, linking, values and animation from node to node nor can I tell if there is a way to access the expression that links these values to allow for user modification 

-adam

**Comment by MrKepzie** [comment]
This is already implemented for  Natron v2 with expressions, please check the snapshots or previous issues prior to making a new one
