### ISSUE TITLE
python expression update on ram preview and render issue

### ISSUE THREAD

**Issue by adallafontana** [MrKepzie/Natron#511]
I have create a echo frame group whith expression and bla bla bla...
https://drive.google.com/file/d/0B76m0pSas0ilYXZ6OWkxNmtJdVE/view?usp=sharing

works right only if I move the timeline curson frame by frame for create a ram preview, so I have a smooth animation: video_screen_1; but if render ram preview with play or I render a file seem that natron engine jump some frame expression update: video_screen_2.

https://drive.google.com/file/d/0B76m0pSas0ilWEotOFhUM2FsdDg/view?usp=sharing

**Comment by adallafontana** [comment]
In this one I have load the comp in the ram frame by frame and works:
https://drive.google.com/file/d/0B76m0pSas0ilVUpMZUZxdk10MUU/view?usp=sharing

I know that Natron render engine in multi process render the total frames divided in range of "x" frames, not always in "linear" sequence, 1-15 20-35 after 16-19 21-40, is good for using the 100% of CPU power, but seem like the expression update is not fast like render engine.

**Comment by MrKepzie** [comment]
This is a bug in expressions, I'm going to fix it.

**Comment by MrKepzie** [comment]
Also, since we changed the Merge so that it can accept up to 10 inputs, you might want to re-generate your python script since all the connectInput(...) calls do not point to the same input anymore (they point to A2 instead of B)

**Comment by adallafontana** [comment]
thank you.

**Comment by MrKepzie** [comment]
I just fixed it in https://github.com/MrKepzie/Natron/commit/ef66bca81aacc241428e238c04b884df755c5856
