### ISSUE TITLE
multi-output python Groups enhancement

### ISSUE THREAD

**Issue by adallafontana** [MrKepzie/Natron#512]
will be nice have the possibility of multi-output on Groups, now is possible have multi-input and create more that one Output node inside Group but the plug-out is only 1 refers to Output1: "0" in script.

**Comment by MrKepzie** [comment]
already planned

**Comment by MrKepzie** [comment]
We will put this on hold for a while, in fact this is not really needed and requires some efforts to implement

**Comment by adallafontana** [comment]
ok, ...yes is not vital.

**Comment by devernay** [comment]
This issue was moved to NatronGitHub/Natron#98
