### ISSUE TITLE
Frame Blend Node improve | enhancement

### ISSUE THREAD

**Issue by adallafontana** [MrKepzie/Natron#514]
Nice new node in the snapshot but I ask you some improve if is possible:

- Offset Frame -> now is still one frame, should be possible decide the space time between frames.
- Operation blend -> now seem to be Frame+Frame+.../NumbersOfFrame, will be nice have also Average, Plus, Min, Max, Multiply.

**Comment by devernay** [comment]
New interval parameter since https://github.com/devernay/openfx-misc/commit/5a206d4f05d5839e1572e42272f0ca281e55f891

I changed the parameters, there is no more "Number of Frames" parameter.

I'll add Operation later.
