### ISSUE TITLE
Flip Node or Transform Flip feature request

### ISSUE THREAD

**Issue by blackearth2014** [MrKepzie/Natron#518]
I would like to have the ability to flip an image horizontally or vertically without having to do it in the gimp or photoshop first. Can we get a flip node or add this feature to the transform node?

**Comment by adallafontana** [comment]
for now you can scale -1 x or y in the transform node

**Comment by blackearth2014** [comment]
Thanks. I wish I didn't have to us another transform node for scaling the whole image after the scale flip. 

Nonetheless, thanks for the workaround.

**Comment by MrKepzie** [comment]
Transformed are chained and the image will only be filtered once anyway.
