### ISSUE TITLE
Auto-Aligned node: request

### ISSUE THREAD

**Issue by blackearth2014** [MrKepzie/Natron#519]
Is it possible to implement an auto-align node to stitch together still images?

**Comment by devernay** [comment]
Hi Omar,
you mean like making a panorama?
Can you describe more precisely the use case ?

fred

**Comment by blackearth2014** [comment]
I have some stills that I have taken of a landscape from my hometown in North Carolina.  There were taken in a 180 degree angle. I want to use them as one large matte painting. Apple Shake had a node that is called Auto Aligned that stitched images in a panorama. I am doing a car driving green screen scene and want to use the images as continuous shot.

**Comment by devernay** [comment]
I think you have better control on the quality of the panorama with proper tools such as hugin or autopano. Did you try that?

**Comment by blackearth2014** [comment]
Thanks. I just downloaded the Hugin for the Mac.

**Comment by blackearth2014** [comment]
I will close this issue unless you guys decide to develop a similar Hugin/AutoPano node later down the line.

**Comment by devernay** [comment]
... panoramic *video* may be on the way, but not before a few months

**Comment by blackearth2014** [comment]
I am cool with that. The Hugin software should be suffice as a third party app.

**Comment by eliemichel** [comment]
I may be missing some update since this issue (I'm just starting to look at Natron) but there seems to be actual use case for this kind of feature:

http://help.thefoundry.co.uk/nuke/content/furnacecore/align.html

Is something similar already available in Natron?
