### ISSUE TITLE
anomaly viewer and point 

### ISSUE THREAD

**Issue by GladiatorFX** [MrKepzie/Natron#523]
I report a anomaly.
When I create a new node (grade, noise etc.) having selected the viewer node, point is created automatically as shown in the video.
The video was uploaded on youtube not listed.

https://www.youtube.com/watch?v=z2IJ-sPv2E8&feature=youtu.be

**Comment by devernay** [comment]
Hi,
which version are you using?

**Comment by GladiatorFX** [comment]
Natron 1.2.1 win64

**Comment by MrKepzie** [comment]
It's fixed in Natron 2.0
