### ISSUE TITLE
Feature Request: Fullscreen Viewer Without Undocking

### ISSUE THREAD

**Issue by OldSkoolVFX** [MrKepzie/Natron#526]
Hi ...

So far I have not found a way of making the viewer fullscreen without undocking it from the interface and floating the pane.  Redocking it is a real pain when I'm done with looking at it full screen.  It's easier to just reload the file or the layout.  Both of which are cumbersome and a waste of time.  The feature I would like is the ability to zoom a pane full screen and back without changing the pane layout.  Blender has this ability (CRL + UP ARROW) which is very useful on laptops and single screen setups where you can't dedicate a monitor to the viewer.

- Thanks

**Comment by MrKepzie** [comment]
Space bar on the viewer is not enough ? Do you want a *real* full-screen mode ?

**Comment by OldSkoolVFX** [comment]
MrKepzie ...

Sorry I did not know about the spacebar.
