### ISSUE TITLE
Natron-snapshots-4b4277ad6ce25e28319766f3f33f24d61f734f1c: Mirror Node H-Flip Error

### ISSUE THREAD

**Issue by blackearth2014** [MrKepzie/Natron#527]
The Mirror Node H-Flip has a bug. See image
![mirrornode_hflip](https://cloud.githubusercontent.com/assets/7956901/6445520/7754566e-c0d2-11e4-8517-e23aa1e27cf3.png)

**Comment by devernay** [comment]
Can you put a noop node before and another after the hflip and tell me what the info says?
Looks like rgb was misinterpreted as rgba.
Does the reader output rgb or rgba components?
Fred

**Comment by blackearth2014** [comment]
I did what you have asked and you can see the image for feedback. When I had switched the ReadOIIO output component to RGBA from RGB, everything worked well. 

![mirror-noop](https://cloud.githubusercontent.com/assets/7956901/6451771/d6556ece-c0fe-11e4-9183-b1d91f54cc6d.png)
