### ISSUE TITLE
Enhancement: wipe tool snap to mouse cursor

### ISSUE THREAD

**Issue by nicholascarroll** [MrKepzie/Natron#535]
when zooming or panning the wipe tool can go offscreen. so, it would be helpful to be able to hit a key to instantly reposition the snap tool to the mouse cursor x,y position.

**Comment by MrKepzie** [comment]
What shortcut should that be ?

**Comment by nicholascarroll** [comment]
Any key, or user selectable.

**Comment by devernay** [comment]
Is there a keystroke in nuke for this?

**Comment by nicholascarroll** [comment]
Don't think so but not sure.

**Comment by devernay** [comment]
I don't have nuke here, but Somethink derived from "center view", (ctrl-f?) would be ok

**Comment by nicholascarroll** [comment]
That makes sense.

**Comment by MrKepzie** [comment]
Implemented: bound to SHIFT+F by default
