### ISSUE TITLE
Group to Python Plugin--> alpha error

### ISSUE THREAD

**Issue by thechevre** [MrKepzie/Natron#537]
Hi everyone,

I had a strange bug while converting a Group into a python script.
That appends only with the node " CImgErode".  When i check only alpha channels in input (picture 01), and export it in python I got the RGB channels activated but not the alpha.(picture 02) 

But in the Python script I get this. That mean the Alpha channel is activated. In the other nodes I didn't have this problem. I corrected the problem by adding an expression (True) to the alpha channel before exporting in Python, but that look strange.

![01_node_params_in_group](https://cloud.githubusercontent.com/assets/11348056/6523616/aa9b49e8-c3f1-11e4-9dda-2544df43b0d8.png)
![02_the same exported in python](https://cloud.githubusercontent.com/assets/11348056/6523615/aa9afeca-c3f1-11e4-9cc9-5df126573b1f.png)

    lastNode = app.createNode("net.sf.cimg.CImgErode", 1, group)
    lastNode.setScriptName("ErodeCImg2")
    lastNode.setLabel("ErodeCImg2")
    lastNode.setPosition(509.289, -424.039)
    lastNode.setSize(104, 37)
    lastNode.setColor(0.8, 0.500008, 0.300008)
    groupErodeCImg2 = lastNode

    param = lastNode.getParam("a")
    param.setValue(True)
    del param

**Comment by MrKepzie** [comment]
I will look into it, this is most likely a bug in the project loader, these parameters have their value automatically set depending on the graph stream: i.e: what kind of pixel components pass through the graph.

**Comment by thechevre** [comment]
thank. If you want, you can take a look at the full script. (the description part of the script is not full yet)

# -*- coding: utf-8 -*-
#This file was automatically generated by Natron.
#Note that Viewers are never exported

import NatronEngine

def getPluginID():
    return "EdgeDetectWrapper"

def getLabel():
    return "EdgeDetectWrapper"

def getVersion():
    return 1

def getGrouping():
    return "/Transform"

def getDescription():
    return "Detects edges in alpha channel"

def createInstance(app,group):

    #Create all nodes in the group
    lastNode = app.createNode("fr.inria.built-in.Output", 1, group)
    lastNode.setScriptName("Output1")
    lastNode.setLabel("Output1")
    lastNode.setPosition(283.718, 118.04)
    lastNode.setSize(80, 37)
    lastNode.setColor(0.699992, 0.699992, 0.699992)
    groupOutput1 = lastNode

    del lastNode



    lastNode = app.createNode("fr.inria.built-in.Input", 1, group)
    lastNode.setScriptName("Input1")
    lastNode.setLabel("Input1")
    lastNode.setPosition(283.718, -490.79)
    lastNode.setSize(80, 37)
    lastNode.setColor(0.300008, 0.500008, 0.2)
    groupInput1 = lastNode

    del lastNode



    lastNode = app.createNode("net.sf.openfx.MergePlugin", 1, group)
    lastNode.setScriptName("Merge1")
    lastNode.setLabel("Merge1")
    lastNode.setPosition(509.289, -309.052)
    lastNode.setSize(104, 45)
    lastNode.setColor(0.300008, 0.370001, 0.775998)
    groupMerge1 = lastNode

    param = lastNode.getParam("OfxParamStringSublabelName")
    param.setValue("out")
    del param

    param = lastNode.getParam("operation")
    param.setValue(23)
    del param

    param = lastNode.getParam("userTextArea")
    param.setValue("<font size=\"6\" color=\"#000000\" face=\"Verdana\"><Natron>(out)</Natron></font>")
    del param

    del lastNode



    lastNode = app.createNode("net.sf.cimg.CImgErode", 1, group)
    lastNode.setScriptName("ErodeCImg2")
    lastNode.setLabel("ErodeCImg2")
    lastNode.setPosition(509.289, -424.039)
    lastNode.setSize(104, 37)
    lastNode.setColor(0.8, 0.500008, 0.300008)
    groupErodeCImg2 = lastNode

    param = lastNode.getParam("a")
    param.setValue(True)
    del param

    param = lastNode.getParam("size")
    param.setValue(0, 0)
    param.setValue(0, 1)
    del param

    param = lastNode.getParam("premult")
    param.setValue(True)
    del param

    del lastNode



    lastNode = app.createNode("net.sf.openfx.ShufflePlugin", 1, group)
    lastNode.setScriptName("Shuffle1")
    lastNode.setLabel("Shuffle_alpha")
    lastNode.setPosition(271.718, -1.53834)
    lastNode.setSize(104, 37)
    lastNode.setColor(0.6, 0.239994, 0.390005)
    groupShuffle1 = lastNode

    param = lastNode.getParam("outputA")
    param.setValue(9)
    del param

    del lastNode



    lastNode = app.createNode("net.sf.cimg.CImgBlur", 1, group)
    lastNode.setScriptName("BlurCImg2")
    lastNode.setLabel("BlurCImg2")
    lastNode.setPosition(507.97, -135.672)
    lastNode.setSize(104, 37)
    lastNode.setColor(0.8, 0.500008, 0.300008)
    groupBlurCImg2 = lastNode

    param = lastNode.getParam("a")
    param.setValue(True)
    del param

    param = lastNode.getParam("size")
    param.setValue(0, 0)
    param.setValueAtTime(11.9, 310, 1)
    del param

    param = lastNode.getParam("filter")
    param.setValue(0)
    del param

    param = lastNode.getParam("premult")
    param.setValue(True)
    del param

    del lastNode



    lastNode = app.createNode("net.sf.openfx.ColorCorrectPlugin", 1, group)
    lastNode.setScriptName("ColorCorrect1")
    lastNode.setLabel("ColorCorrect1")
    lastNode.setPosition(509.289, -212.184)
    lastNode.setSize(104, 37)
    lastNode.setColor(0.480003, 0.659998, 1)
    groupColorCorrect1 = lastNode

    param = lastNode.getParam("r")
    param.setValue(False)
    del param

    param = lastNode.getParam("g")
    param.setValue(False)
    del param

    param = lastNode.getParam("b")
    param.setValue(False)
    del param

    param = lastNode.getParam("a")
    param.setValue(True)
    del param

    param = lastNode.getParam("HighlightsGain")
    param.setValue(4, 0)
    param.setValue(4, 1)
    param.setValue(4, 2)
    param.setValue(4, 3)
    del param

    param = lastNode.getParam("toneRanges")
    param.setCurveColor(0, 0.6, 0.4, 0.6)
    param.setNthControlPoint(0, 0, 0, 1, 0, 0)
    param.setNthControlPoint(0, 1, 0.055538, -0.00765823, 0, 0)
    param.setCurveColor(1, 0.8, 0.7, 0.6)
    param.setNthControlPoint(1, 0, 0.124747, 0.00382911, 0, 0)
    param.setNthControlPoint(1, 1, 1, 1, 0, 0)
    del param

    param = lastNode.getParam("premult")
    param.setValue(True)
    del param

    del lastNode



    lastNode = app.createNode("net.sf.cimg.CImgGuided", 1, group)
    lastNode.setScriptName("GuidedCImg1")
    lastNode.setLabel("GuidedCImg1")
    lastNode.setPosition(509.289, -65.7554)
    lastNode.setSize(104, 37)
    lastNode.setColor(0.8, 0.500008, 0.300008)
    groupGuidedCImg1 = lastNode

    param = lastNode.getParam("a")
    param.setValue(True)
    del param

    param = lastNode.getParam("epsilon")
    param.setValue(0.086, 0)
    del param

    param = lastNode.getParam("premult")
    param.setValue(True)
    del param

    del lastNode




    #Create the parameters of the group node the same way we did for all internal nodes
    lastNode = group

    #Create the user-parameters
    lastNode.userNatron = lastNode.createPageParam("userNatron", "User")
    param = lastNode.createIntParam("ErodeSize", "Erode Size")
    param.setMinimum(-100, 0)
    param.setMaximum(100, 0)

    #Add the param to the page
    lastNode.userNatron.addParam(param)

    #Set param properties
    param.setHelp("")
    param.setAddNewLine(True)
    param.setAnimationEnabled(True)
    lastNode.ErodeSize = param
    del param

    param = lastNode.createDoubleParam("BlurSize", "Blur Size")
    param.setMinimum(0, 0)
    param.setMaximum(100, 0)

    #Add the param to the page
    lastNode.userNatron.addParam(param)

    #Set param properties
    param.setHelp("")
    param.setAddNewLine(True)
    param.setAnimationEnabled(True)
    lastNode.BlurSize = param
    del param

    param = lastNode.createChoiceParam("BlurFilter", "Blur Filter")
    entries = [ ("Quasi-Gaussian", ""),
    ("Gaussian", ""),
    ("box", ""),
    ("Trangle", ""),
    ("Quadratic", "")]
    param.setOptions(entries)
    del entries

    #Add the param to the page
    lastNode.userNatron.addParam(param)

    #Set param properties
    param.setHelp("")
    param.setAddNewLine(True)
    param.setAnimationEnabled(True)
    lastNode.BlurFilter = param
    del param

    #Refresh the GUI with the newly created parameters
    lastNode.refreshUserParamsGUI()
    del lastNode

    #Now that all nodes are created we can connect them together, restore expressions
    groupOutput1.connectInput(0, groupShuffle1)

    groupMerge1.connectInput(0, groupErodeCImg2)
    groupMerge1.connectInput(1, groupInput1)

    groupErodeCImg2.connectInput(0, groupInput1)
    param = groupErodeCImg2.getParam("a")
    param.setExpression("True", False, 0)
    del param
    param = groupErodeCImg2.getParam("size")
    param.setExpression("- int (thisGroup.ErodeSize.get () )", False, 0)
    param.setExpression("- int (thisGroup.ErodeSize.get () )", False, 1)
    del param

    groupShuffle1.connectInput(0, groupGuidedCImg1)
    groupShuffle1.connectInput(1, groupInput1)

    groupBlurCImg2.connectInput(0, groupColorCorrect1)
    param = groupBlurCImg2.getParam("size")
    param.setExpression("thisGroup.BlurSize.get()", False, 0)
    param.setExpression("thisGroup.BlurSize.get()", False, 1)
    del param
    param = groupBlurCImg2.getParam("filter")
    param.setExpression("thisGroup.BlurFilter.get () ", False, 0)
    del param

    groupColorCorrect1.connectInput(0, groupMerge1)

    groupGuidedCImg1.connectInput(0, groupBlurCImg2)
    param = groupGuidedCImg1.getParam("a")
    param.setExpression("True", False, 0)
    del param
