### ISSUE TITLE
Longer Floating windows don´t have scroll bars

### ISSUE THREAD

**Issue by sirdavid32** [MrKepzie/Natron#539]
When I used a sapphire plugin (flare) the dialogue was very long but not my screen, there is a need to make a floating window know the current workspace in order for it to determine and help the scrolling on settings on the floating window, when modifying parameters lower than the maximum floating window size.

**Comment by MrKepzie** [comment]
https://github.com/MrKepzie/Natron/issues/479 did not solve it ?

**Comment by MrKepzie** [comment]
Here it works fine: 
![screen shot 2015-03-07 at 12 09 05](https://cloud.githubusercontent.com/assets/4058448/6541176/d1942570-c4c2-11e4-83f5-8b504ad2a151.png)

Can you paste a screenshot showing what's wrong ?

**Comment by sirdavid32** [comment]
I´m on a PC, away from my regular compositing pc. Will wait until monday to
upload that pic. Thanks for posting.

On Sat, Mar 7, 2015 at 6:09 AM, Alexandre Gauthier <notifications@github.com
> wrote:

> Here it works fine:
> [image: screen shot 2015-03-07 at 12 09 05]
> <https://cloud.githubusercontent.com/assets/4058448/6541176/d1942570-c4c2-11e4-83f5-8b504ad2a151.png>
>
> Can you paste a screenshot showing what's wrong ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MrKepzie/Natron/issues/539#issuecomment-77684583>.
>



-- 
Portfolio 2013 <http://be.net/3dcinetv>
Cinema & TV production
Video Reel <https://vimeo.com/3dcinetv/reel2012>

**Comment by MrKepzie** [comment]
I just tested on Windows 7 and it works well too. I suspect that you're using Natron 1.2.1 which does not have the fix. The fix is incorporated in Natron 2

**Comment by sirdavid32** [comment]
Yes. Natron 1.2.1 is my version.

El mar 11, 2015 5:05 a.m., "Alexandre Gauthier" <notifications@github.com>
escribió:
>
> I just tested on Windows 7 and it works well too. I suspect that you're
using Natron 1.2.1 which does not have the fix. The fix is incorporated in
Natron 2
