### ISSUE TITLE
Custom Startup Natron Screen

### ISSUE THREAD

**Issue by sirdavid32** [MrKepzie/Natron#540]
I apologize if this is not a subject for this category, but I wanted to know -if possible- a consideration on the software to customize the startup/splash screen? It would be a huge punch on the entire "open source" idea. :) . The logo would always appear on top of it as transparency. You can also decide the Logo´s color for the transparency: http://imgur.com/7nT6avw
Thanks. Natron is getting real good!

**Comment by MrKepzie** [comment]
Sadly we cannot spend time on various requests like this, or at least when there will be nothing important left to do aside;) Try to compile the software yourself or find someone that can do it for you
