### ISSUE TITLE
Read FFMPEG Problem

### ISSUE THREAD

**Issue by KarstenHoehne** [MrKepzie/Natron#542]
Hello i have a problem reading a .mov file.

I get the error message: could not find video stream.
The Video file is a MPEG-4 QuickTime Container with png video inside
Blender 2.73a has no problem opening the video with alpha channel and all.

Since both problems usse ffmpeg for video decoding, i am a bit confused as to why this happens?
I tried copying the FFMPEG dlls from blender to the IO.ofx.bundle folder, but that caused the reader to not work at all anymore.

The video in question is one of the free "Muzzle Flash Smokey Rifle" file from this site:
http://footagecrate.com/all-effects.html

**Comment by MrKepzie** [comment]
Can you download  the last snapshot and see if this is resolved ? https://natron.inria.fr/snapshots/
I'm closing this as it is the same as #529

**Comment by KarstenHoehne** [comment]
First off, thanks for the quick reply.

Sorry for the duplicate, I should have looked through the other error reports more closely.

Tried the snapshot (WIndows 7, 64 BIt version btw), still the same error message. Just presented differently in the UI.

I might try the Ubuntu Version tomorrow to see if it makes a difference.
