### ISSUE TITLE
Expression Node Disable

### ISSUE THREAD

**Issue by thechevre** [MrKepzie/Natron#543]
In the Disable checkbox, I tried this expression :

 not thisGroup.FlickerTrue

(FlickerTrue is the name of a groupnode checkbox). 
The Disable checkbox doesn't change when I activate/desactivate the new checkbox.

![merge_disable_checkbox](https://cloud.githubusercontent.com/assets/11348056/6542679/6a3ed242-c500-11e4-96fb-cda26b762a85.PNG)
![merge_disable_checkbox_2](https://cloud.githubusercontent.com/assets/11348056/6542680/6a40d0ce-c500-11e4-9bf5-9a54850517d8.PNG)

**Comment by MrKepzie** [comment]
Your expression is not correct, see http://natron.readthedocs.org/en/workshop/paramExpressions.html.

It should be:
    
    not thisGroup.FlickerTrue.get()

**Comment by thechevre** [comment]
thanks. Sorry for the stupid mistake.
