### ISSUE TITLE
snap d4d4..... ram preview issue

### ISSUE THREAD

**Issue by adallafontana** [MrKepzie/Natron#545]
If I render ram preview all works right but if stop and try move the cursor of timeline Natron freezes and I must forcing the closing the application.
This doesn't happen always but frequently.

**Comment by MrKepzie** [comment]
Can't reproduce the bug

**Comment by adallafontana** [comment]
https://drive.google.com/file/d/0B76m0pSas0ilMUcyTGtjMEJmYUk/view?usp=sharing

**Comment by MrKepzie** [comment]
Can you reproduce the bug with only a reader connected to a viewer  ?

**Comment by adallafontana** [comment]
ok the problem is the FrameBlend node, without (only a reader) works

**Comment by MrKepzie** [comment]
Can you send me your project please

**Comment by adallafontana** [comment]
If you want I send you but now I'm trying now with a simple project, Reader+frameblend+viewer.
And now is gone to crash also with reader only (screenshot).
But I repeat doesn't happen always, sometime at the first ram preview other after 3-4 times of ram preview.

![screenshot from 2015-03-09 17 25 44](https://cloud.githubusercontent.com/assets/8054856/6559426/4be2dae4-c683-11e4-9b6b-7cbd631adcd9.jpg)

**Comment by adallafontana** [comment]
I have tried with other file format ProRes422 and the node mirror, same problem, I exclude the issue depend to the file, and is not FrameBlend.
I have tried with a project without reader only with generated node and I can't reproduce the bug for now.

**Comment by MrKepzie** [comment]
Still cannot reproduce on Ubuntu 14.04 with 24 cores CPU, I think this is as close as your setup can be. 
Again can you send me a complete video, from startup of Natron until it freezes so I reproduce **exactly** the same steps ?

**Comment by adallafontana** [comment]
I have reinstalled Natron with last snap commit, eliminated the .cache folder and for now seem all works right, not freeze.
Maybe the issue was in the file cache or how Natron loaded it.
For now you can close, in case I reopen a new issue.

Do you now some issue related to the 4K file and ram/memory apart
the obvious weight of the file?

**Comment by adallafontana** [comment]
I mean issue related to this or similar:
http://wiki.blender.org/index.php/Dev:Ref/Proposals/Compositor2014_p1.1_TD

Maybe is only my impression but Natron seem slow with 4K, but I think more that obvious, also if I use proxy mode active to 2 or 4.

**Comment by adallafontana** [comment]
There is a way to understand if all works right, I don't know the ram consume, the error log......

**Comment by MrKepzie** [comment]
Which processing in particular is slow ? When using 4K, it works pretty well for me here

**Comment by MrKepzie** [comment]
Ram consumed is displayed in the node graph, the errors are reported in the viewer/and or the node graph it self.

**Comment by adallafontana** [comment]
For example I load a frame sequence .tiff, only read and viewer.
Viewer in small size, I move the cursor on timeline and I haven't a re-frame, is null (still on fist frame loaded) or very slow.
There is a way for accelerate the viewer in this case, tile size or so on.

**Comment by adallafontana** [comment]
For move cursor I mean jump from one frame to other, not play

**Comment by adallafontana** [comment]
I would like test Natron/Nuke but I must use other machine where I have a trial copy.

**Comment by adallafontana** [comment]
So I did.
On my old 8 core Nuke 8.6 and Natron 2.0 have (...a not scientific) equal performance with 4K tiff sequence 8 bit.
For my curiosity, when Natron core does the re-frame of viewer how many threads uses? 1 or all available.

**Comment by MrKepzie** [comment]
All threads are used

**Comment by MrKepzie** [comment]
Can I close the
