### ISSUE TITLE
Segfault on project loading

### ISSUE THREAD

**Issue by sozap** [MrKepzie/Natron#546]
Natron version : d4d44855eb6082961c9901acd215d4ddf8e3430a

debug crash report : 

http://pastebin.com/cjZEfBnT

I can send you the project file if you want, it has a lot of nodes inside ...

**Comment by MrKepzie** [comment]
I believe it has been fixed in a recent commit. Try in ~30minutes again

**Comment by sozap** [comment]
Yes it work fine now ! thanks !
