### ISSUE TITLE
Natron-snapshots-9df62c3597e0a11c4755fcab4cad5de4c75a1a74:  Hangs on launch

### ISSUE THREAD

**Issue by blackearth2014** [MrKepzie/Natron#547]
This Snapshot hangs on launch and won't allow me to install it.

**Comment by MrKepzie** [comment]
It is probably broken

**Comment by blackearth2014** [comment]
Why is source forge still sending snapshots updates of Natron v1.2.1. It is happening more and more these days.

**Comment by MrKepzie** [comment]
Omar, you’re not clicking on the correct link … Don’t click on the “Looking for last version ? ….” link but in  the following folder:

https://sourceforge.net/projects/natron/files/snapshots/OSXUniversal/repo/ <https://sourceforge.net/projects/natron/files/snapshots/OSXUniversal/repo/>

**Comment by blackearth2014** [comment]
It comes to me in an email and it say click here for latest snapshot. Thanks.

**Comment by MrKepzie** [comment]
Just go on the page I linked when you want to download the latest snapshot, source forge is mistaken

**Comment by blackearth2014** [comment]
Here is what it look looks like when I just got an email for the latest snapshot.  There is no file to download.

![screen shot 2015-03-10 at 2 12 34 pm 2](https://cloud.githubusercontent.com/assets/7956901/6581829/c28eb94a-c72f-11e4-88db-acf45cfda647.png)
