### ISSUE TITLE
new STMap Plugin segfault

### ISSUE THREAD

**Issue by sozap** [MrKepzie/Natron#551]
Natron version : a92f7e858e315d02d12e0d26d037840966c7bdd4

OFX Misc : 201503091706 , release date : 2015 03 12

Crash Report :
http://pastebin.com/aXeQi2Sx

Anyway STMap is such a great addition to Natron, I'm just amazed that it append now ! 
Congratulations and thank you very much guys !

**Comment by devernay** [comment]
Can you send me a project that crashes?

**Comment by sozap** [comment]
that was just an openexr multilayer from blender 1950x1080 in resolution, the project was only a test with 2 read connected to the STMap...
I'll send you all the files tomorrow ...

**Comment by sozap** [comment]
Hum, my bad, it wasn't the STMap plugin, but the IDistort ...
I thought they were the same , (sorry I must be tired :) ) 
The STmap work fine, except the fact that when I plug a Transform node on the source , it get black on the STMap output, it may be a concatenation problem, because putting a grade juste between the transform and the STMap solve it...

Just because I'm curious, is the IDistort not finished ? is it a displacement map plugin ? if not what's the difference with the stmap ?

ATM they look very much the same so I get confused , sorry

**Comment by devernay** [comment]
For the difference, see the online help. They are named after their Nuke equivalents.
If you get a concatenation problem (I'll take a look at it), another solution is to put a "NoOp" with "force copy" checked.

**Comment by devernay** [comment]
fixed in https://github.com/devernay/openfx-misc/commit/e1dda005d53fce2c4e185135ff3d70b7a33f0248
