### ISSUE TITLE
snap f056b.... roto shape broken

### ISSUE THREAD

**Issue by adallafontana** [MrKepzie/Natron#554]
...doesn't generate rgba

**Comment by blackearth2014** [comment]
This Natron-snapshots-80f570e5839b26a0556168af521f06e2b7c4d292 Roto Node is not rendering the RGBA data when merged over a background image. In the viewer, the alpha channel data is presented but it only renders RGB when merged over other images. See image viewers for references.

![no_roto_alpha](https://cloud.githubusercontent.com/assets/7956901/6638123/f938dde2-c958-11e4-9d40-8da875c274fe.png)
