### ISSUE TITLE
Request: import cinemaDNG sequence (linux)

### ISSUE THREAD

**Issue by 0VerFlow** [MrKepzie/Natron#556]
Hi,first thanks for support this fantastic project :)
Is there some possibilities to import a cinemaDNG sequence of the Blackmagic cameras directly in Natron?
I work on Linux and normally I can open my RAW/cinemaDNG files with some photo workflow softwares like Darktable or Lightzone then I export tiff or PNG.
Natron have super tools for grading and this implementation can reduce the time of workflow.
Thx

**Comment by MrKepzie** [comment]
See https://github.com/MrKepzie/Natron/issues/408

**Comment by 0VerFlow** [comment]
wow Seedy Gonzales eh eh thank you...I try now with tuttleRAWreader

**Comment by 0VerFlow** [comment]
![schermata del 2015-03-12 11 33 17](https://cloud.githubusercontent.com/assets/11438406/6616181/9e1566f4-c8ab-11e4-95b3-2784c61c4443.png)
Nothing to do but I'm not sure if it is my error.I can see the DNG sequence only if I select "*" on the opensequence window but the result is that
![schermata del 2015-03-12 11 30 55](https://cloud.githubusercontent.com/assets/11438406/6616214/0eb05bd0-c8ac-11e4-914c-c6731e2fa10a.png)

**Comment by MrKepzie** [comment]
From what I know, I’m not sure this plug-in works well. At least you should get in touch with the developers of that plug-in
at https://github.com/tuttleofx/TuttleOFX <https://github.com/tuttleofx/TuttleOFX>

This issue is about creating a new libraw based reader

**Comment by 0VerFlow** [comment]
ok thank you very much.

**Comment by 0VerFlow** [comment]
Solved with that http://www.libraw.org/

**Comment by 0VerFlow** [comment]
I have installed LibRaw 0.16 Release but the issue is : TuttleRawReader can't natively read a cinemaDNG sequence,I have forced the Filter of opensequence windows to see me "all files" only read a first DNG like a single photo/frame.
![schermata del 2015-03-12 18 56 07](https://cloud.githubusercontent.com/assets/11438406/6624675/2283eb74-c8eb-11e4-928b-26b9ba3690b9.png)

Any suggestions? something wrong in library installation?
this is the result:
![schermata del 2015-03-12 18 57 36](https://cloud.githubusercontent.com/assets/11438406/6624678/2b20a3b2-c8eb-11e4-8bb5-569af576bb2c.png)

**Comment by fabiencastan** [comment]
> From what I know, I’m not sure this plug-in works well.

Please report if you have troubles.

**Comment by 0VerFlow** [comment]
I don't now why but in my case this plug-in don't read the seaquence but only the first frame.
I think isn't normal,in the opensequence windows to don't see the files .dng
https://cloud.githubusercontent.com/assets/11438406/6624675/2283eb74-c8eb-11e4-928b-26b9ba3690b9.png
