### ISSUE TITLE
version 2.0 dev build: Difficult to read node labels

### ISSUE THREAD

**Issue by nicholascarroll** [MrKepzie/Natron#558]
Node labels are very hard to read now in v 2.0 development build. I would like to request a Preferences option to disable this. The new ornamentation band on the left of each node takes valuable space away from the node name. It seems to be ornamentation only because it doesn't do anything when clicked on. 

For short node names like Write1 or Merge1 the text now only uses about half of the available width. So you have to zoom in a lot and see less of the node graph at any time than with Natron 1.2.  For a very long node name, the black text overlaying the black of the ornamentative band is illegible.

I think that colour coding nodes is the best way to make the node type visible. Human eye can distinguish many hues. So can i suggest that this be extended so that every single node type can have its own colour instead of just the node groups. In fact could automatically distribute hue to members of a category based on the category's hue. If their colour was also shown in their menu listing in the tool shelf and the tab menu it would further help reinforce what means what.

**Comment by MrKepzie** [comment]
So, what is your suggestion ? You can change the node name font, size and color from the "node" tab of the settings panel

**Comment by nicholascarroll** [comment]
My suggestion is now just to add an option to Preferences to disable the ornamental band, that's all.
I looked into using hues of 3 degrees difference and can't really distinguish them that well. 
thanks

**Comment by MrKepzie** [comment]
There is already this preference… ;)

**Comment by nicholascarroll** [comment]
Wow! Preferences/Nodegraph/Display Plugin Icon on Nodegraph
You're too good man!
