### ISSUE TITLE
Enhancement: Node Script Name as Label

### ISSUE THREAD

**Issue by nicholascarroll** [MrKepzie/Natron#559]
*Script Name* is the unique identifier of a node and is to be used in scripting but *Label* is not unique. 

If the user labels their nodes, then they want to use those label in expressions, but that is not currently possible because uniqueness is not enforced.

I can't think of a single use case where a user would be bothered by a uniqueness constraint on the Label. So can Label please be made unique or else just gotten rid of?

**Comment by MrKepzie** [comment]
The script-name needs to follow specific rules to be Python variables naming compliant. 
The user interface does not allow the user to change the script-name of any object to avoid mis-behaviors; However you can still change the script name from the python API.

The label can be freely changed by the user and is what is expected to be seen in the GUI. 

For example the user might want to name their node "My super awesome node" , unfortunately this is not a python compliant variable name.

**Comment by nicholascarroll** [comment]
The user isn't going to want to name their node "super awesome" they are going to want to give it a name that they can use in expressions :-)
People can certainly comply with rules like uniqueness and not using certain characters in the name. Please keep an open mind in the future about this one.
