### ISSUE TITLE
SeExpr u,v, fmod, input_width,.... issue

### ISSUE THREAD

**Issue by adallafontana** [MrKepzie/Natron#561]
On SeExpr I can scale and move x,y but I can't use "fmod" with them, if I use "uv" I got an error message and I don't understand how to use input/output width/height, I don't know if are broken or if I do some error. 
Is xy(uv) not enough for mapping pixel?

**Comment by MrKepzie** [comment]
First-off what’s the error ? Can you copy your expression ?

Today we’ve made many adjustments to the node, mainly:

- You can now reference the normalised coordinates of the output pixel with (u,v)
- You can now reference any input color by Cs , Cs2, Cs3, etc…
- You can now reference any input alpha by As , As2, As3, etc…

x,y is only to be used with getPixel while u,v is for content generation.
For example you can copy paste the examples on the homepage of SeExpr and they will work:

$Cs=[1.000, 0.000, 1.000]; # Sphere Color
$L1=norm([-1.3,-.3,0]); # Light Direction 1
$L2=norm([.8,-1,-1]); # Light Direction 2
$sp=[0.000, 0.000, -3.000]; # Sphere center
$d=norm([$u-.5,$v-.5,-1]); # ray direction
$o=[0.000, 0.000, 0.000]; # ray origin
$r=1.000; # sphere radius
# quadratic coefficients
$a=dot($d,$d);
$ominussp=$o-$sp;
$b=2*dot($d,$ominussp);
$c=dot($ominussp,$ominussp)-$r*$r;
# discriminant
$disc=$b*$b-4*$a*$c;
$color=0.000;
if($disc>0){ # two hit case
  # minimum ray parameter
  $t=min((-$b+sqrt($disc))/(2*$a),(-$b-sqrt($disc))/(2*$a))[0];
  if($t>=0){ # if we are in front of camera
      $Pintersect=$o+$d*$t;  # point of intersection
      $N=norm($Pintersect-$sp); # intersection normal
      # lighting
      $H1=(-$L1+-$d)/length($L1+$d);
      $color=max(dot($N,-$L1),0)*($Cs*.3+.5*max(0,dot($H1,$N))^80);
      $H2=(-$L2+-$d)/length($L2+$d);
      $color+=max(dot($N,-$L2),0)*($Cs*.3+.5*max(0,dot($H2,$N))^80);
   }
}
# return color
$color

**Comment by adallafontana** [comment]
>First-off what’s the error ? Can you copy your expression ?

The error is "....don't exist variable $u and $v...." 

> x,y is only to be used with getPixel while u,v is for content generation.

yes but generally in this kind of language you can change the x,y with a deformed uv for mapping a pixel in various way:

$x=fmod($u, .25);
$y=fmod($v, .25);
$color = getPixel(1, frame, x, y);
$color

For simple tiles effect, but now doesn't works in my installed snapshot version, because u are not recognized.
I wait the new snapshot.

thanks

**Comment by MrKepzie** [comment]
You probably don’t have the last version then because u,v work fine here

**Comment by adallafontana** [comment]
yes problably, the last version installed with maintenance is 1d526ae5... I saw now your "Public activity" and you have implemented the uv after this commit, but the maintenance is still on 1d526ae5
