### ISSUE TITLE
Natron-snapshots-b997bfffdf2318d9742788d7225254c8b5829925: Roto Node

### ISSUE THREAD

**Issue by blackearth2014** [MrKepzie/Natron#562]
In this snapshot, the roto node doesn't pass an output when it is deactivated. See attached image for reference.

![screen shot 2015-03-16 at 7 43 59 pm 2](https://cloud.githubusercontent.com/assets/7956901/6678769/329846fe-cc15-11e4-81f0-8988eabb9ff5.png)

**Comment by MrKepzie** [comment]
I'm sorry but with a simple graph Viewer-->Roto-->Reader, if you disable the Roto node you get the expected behaviour. I suspect this is the Keyer1_1 that is blacking out the image

**Comment by blackearth2014** [comment]
Thanks
