### ISSUE TITLE
shuffle issue...

### ISSUE THREAD

**Issue by sozap** [MrKepzie/Natron#563]
I want to transfer the alpha channel from one stream to another and it do nothing...
My shuffle look like this : 
A.R
A.G
A.B
B.A

the alpha is kept from the A input...
Natron version :  03a73abe1eeeda2d178436f649df278d4a5677c7

**Comment by MrKepzie** [comment]
fixed in openfx-misc

**Comment by sozap** [comment]
Hum, there are still some beetles around the corner :)
If I set a channel to 0 or 1 instead of A.R , A.G ect... I got a segfault when the image is displayed on the viewer...
Here is the crash report : 

http://pastebin.com/w5avMkPJ

Natron version : 03a73abe1eeeda2d178436f649df278d4a5677c7

**Comment by MrKepzie** [comment]
I fixed it, it was a bug in the debug version only

**Comment by sozap** [comment]
hum that was happening without the -debug flag...

**Comment by MrKepzie** [comment]
The binary though was Natron.debug and not Natron
