### ISSUE TITLE
Timeline scrubbing is slow

### ISSUE THREAD

**Issue by nicholascarroll** [MrKepzie/Natron#564]
When load a multilayer exr, and try to grab the playhead and scrub, it is much slower than clicking on the timeline or typing the the frame number in the box.

This is with v1.2.1 and also the 2.0 workshop version.

**Comment by MrKepzie** [comment]
I’ll see what I can do, basically I let this behaviour so it doesn’t burn your cpu when scrubbing by aborting rendering of frames that are no longer the current one. I can let them be computed, which will yield a “smoother” scrubbing, though it will heat the room :d
