### ISSUE TITLE
kOfxImageEffectActionGetTimeDomain on non-General plugins

### ISSUE THREAD

**Issue by nitsch** [MrKepzie/Natron#566]
Natron calls `kOfxImageEffectActionGetTimeDomain` on plugins that do not define a _General Context_ (in my case a _Filter Context_). According to the [OpenFX specs](http://openfx.sourceforge.net/Documentation/1.3/ofxProgrammingReference.html#kOfxImageEffectActionGetTimeDomain) this is not supposed to happen.

Tested in the x64 Windows release of Natron 1.2.1.

**Comment by MrKepzie** [comment]
Indeed we did not take this into account
