### ISSUE TITLE
more info on clips and effects

### ISSUE THREAD

**Issue by devernay** [MrKepzie/Natron#568]
Could the Info panel be enriched with more information, such as
- whether the effect supports tiles, multiresolution, renderscale, etc.
- info about frame ranges
- info about disconnected clips? are they optional? mandatory? what formats are supported

Natron could at least give the same info as "NoOp":
Clip Info:
Input: RGB32f (unmapped: RGBA32f)
premultiplication: Opaque
pixel order: RGBA
field order: None
not connected
discontinuous samples
pixel aspect ratio: 1
frame rate: 24 (unmapped: 25)
frame range: 1...24 (unmapped: 1...1)
region of definition: 0 0 0 0
Output: RGB32f (unmapped: RGB32f)
premultiplication: Opaque
pixel order: RGBA
field order: None
connected
discontinuous samples
pixel aspect ratio: 1
frame rate: 24 (unmapped: 25)
frame range: -2.14748e+09...2.14748e+09 (unmapped: 1...1)
region of definition: 0 0 0 0
time: 1, renderscale: 1x1

Thank you.

**Comment by devernay** [comment]
added framerate

**Comment by blackearth2014** [comment]
Thanks Fred. The more information we get in/about the pipeline the better.
