### ISSUE TITLE
3D lut import/export -> enhancement

### ISSUE THREAD

**Issue by adallafontana** [MrKepzie/Natron#570]
Is important for grading and using the same lut on Camera/monitor/video-recording

**Comment by MrKepzie** [comment]
Are the OCIO plug-ins not enough ?

**Comment by adallafontana** [comment]
I mean the possibility of read and write file .3dl .cube......
I think exist a Tuttle plugin for this but is not present in the default list that are installed with Natron

**Comment by adallafontana** [comment]
Professional camera can record file in specific log profile.
E.g. for grading the Arri Alexa file is possible download the 3dlut generated for specific camera, iso, and software (da vinci, fusion, ae, nuke etc....): 
http://www.arri.com/camera/alexa/tools/lut_generator/lut_generator/

Load 3dlut on compositing software help something but is not vital, just create a right conversion look in grade or cc node and save a preset, the very difference is the possibility of write 3dlut of your basic grade, because you can load on professional camera, monitor or recorder connected to the camera for visualize in correct way; the same image processing from log to grading with the same 3dlut.
When I read the log file on compositing apply the same 3dlut.

**Comment by devernay** [comment]
OCIOFileTransform loads 3dl and cube, and can apply them.

Why would you want to *write* a 3D Lut? There's no way to edit it anyway.

Can we close this?

**Comment by adallafontana** [comment]
>OCIOFileTransform loads 3dl and cube, and can apply them.
>Why would you want to write a 3D Lut? There's no way to edit it anyway.

Thanks for the info I was missing this, I thought would serve only for .cc, works.

Because if you are a DOP you can load some test clips in log profile, create a different "style" of grades, example: backlight, dark-scenario, flat-light-scenario, sun-contrast-light....... export  those like 3dlut and loading on your camera, when you shoot you can choose the right 3dlut for the enviroment when you are.
The camera record the file in log but you can seen on the monitor the right color, contrast etc.... when you return on studio just apply the same 3dlut for have the base for the grading.

**Comment by mangopipeline** [comment]
Was the ability to export a lut from natron ever added?
believe it or not there is a need for exporting lut out of natron...

sometimes artist deal with files where the CDL and the camera luts are totally jacked... 
or they deal with images that have been scanned from film...

in this cases a leads will create a lut by eye... i know it sounds hell of terrible... but believe me it happens...

This is why nuke actually has the ability of exporting color transformations back to different lut formats...

cheers,
Los.

**Comment by MrKepzie** [comment]
Look into the OCIOCDLTransform, it can export as a .cc file which can then be read with OCIOFileTransform

**Comment by mangopipeline** [comment]
sweeeet thanks!!!
