### ISSUE TITLE
Developer Guidelines

### ISSUE THREAD

**Issue by p2or** [MrKepzie/Natron#575]
If I want to submit code for natron, how it should looks like?

**Comment by MrKepzie** [comment]
Hi, 

What would you like to submit ? C++ ? Do you want to contribute to Natron’s core or to the plug-ins ?
The code style guide-lines are the google ones https://google-styleguide.googlecode.com/svn/trunk/cppguide.html <https://google-styleguide.googlecode.com/svn/trunk/cppguide.html>
And we use astyle to format the code correctly. Please read the readme  in the Github. 

See also https://github.com/MrKepzie/Natron/wiki/Google-Summer-of-Code---GSoC-2015-ideas <https://github.com/MrKepzie/Natron/wiki/Google-Summer-of-Code---GSoC-2015-ideas> for a list of tasks to do

**Comment by p2or** [comment]
Thanks for your reply, this solves my issue. Yes both, but at the moment I'm still trying to understand how Natron is written :) BTW: Thanks for this great tool.
