### ISSUE TITLE
First and last frame in Read Node + impossible to close "project settings" property

### ISSUE THREAD

**Issue by rcspam** [MrKepzie/Natron#577]
Hi,
1) First and Last frame sets in Read Node, don't work as expected.
Frame Range; 24, First Frame : 1, Last Frame : 30, Before and After frames set on Black.
Result: Only the first frame appears, then after, the rest of frames are black.
![natron - untitled ntp - _001](https://cloud.githubusercontent.com/assets/10021906/6843807/788e38e2-d3a6-11e4-8230-6b00b4a7c9c6.png)
![natron - untitled ntp - _002](https://cloud.githubusercontent.com/assets/10021906/6843806/788af90c-d3a6-11e4-9dc3-a16880cce584.png)

Is it a bug or do i something wrong ?

2) Impossible to close "Project Settings" property with its "self-close-button"

**Comment by MrKepzie** [comment]
It works fine here. Can you make a screen cast while reproducing the bug ? 

2) is fixed

**Comment by rcspam** [comment]
[ here is a screencast ](https://dl.dropboxusercontent.com/u/2677320/screencast-2015-03-26_14.15.02.mkv)

**Comment by rcspam** [comment]
It could be a lead or a help to resolve bug for you:
If the project is save and reopen, First and Last Frame are reset to 1.
Hope it's help....

**Comment by MrKepzie** [comment]
Fixed via https://github.com/MrKepzie/openfx-io/commit/723c001f0338fa619d308f4873bf9079eb8c83c8

**Comment by rcspam** [comment]
Is the last snapshot is update with the openfx-io fix ?
I m trying it and same result...

**Comment by rcspam** [comment]
Sorry, it's finally ok after clear all caches.
