### ISSUE TITLE
transform does not respect in OIIO1 sequence render

### ISSUE THREAD

**Issue by donkpow** [MrKepzie/Natron#579]
Ubuntu Studio 14.04, 32 bit, Natron v. 1.2.1 -- In a simple project rendering to an OIIO1 image sequence, the transform scale parameter influences the composite rather than being limited to its assigned position in the chain. A ffmpeg render to png/mov renders correctly. I have included images, ntp file, and brief txt in a zip file at https://drive.google.com/open?id=0B68fwQJbA7JXYTVxcHNOcHN5X1E&authuser=0

**Comment by MrKepzie** [comment]
I don't understand the problem, it works fine here, the results are the same whether I render to video or image sequence.

**Comment by donkpow** [comment]
Hello. The images included in the .zip file demonstrate the results. I have performed the operation on two different machines with identical results. It appears the transform node influences after merge2 instead of before merge2 when rendering with writeOIIO1. In my testing, I created two transforms and placed them before merge1. Again, the transform(s) influenced in a manner if the intention was to place transform after merge2. However, the viewer shows proper results.

 Rendering with ffmpeg has expected results. I can't get an image2 sequence  to tif with ffmpeg.
![screenshot - 03272015 - 06 18 52 am](https://cloud.githubusercontent.com/assets/10965133/6865998/129c0ef2-d44a-11e4-8c8b-e3cf61f5bebf.png)

![screenshot - 03272015 - 06 32 59 am](https://cloud.githubusercontent.com/assets/10965133/6866106/31f57f8a-d44b-11e4-92fc-68e1d203b2aa.png)


![sa1](https://cloud.githubusercontent.com/assets/10965133/6866138/a8502428-d44b-11e4-9b7d-b2818adabffd.png)

**Comment by MrKepzie** [comment]
This is not a bug: you are merging the earth with a black opaque background (0,0,0,1) under a fully transparent background (0,0,0,0): The image appears cropped, because only the portion with the opaque bg is visible. In the viewer it makes no difference because black opaque and black transparent are represented the same, but if you hover with the color picker you should see the difference between the alpha.

**Comment by donkpow** [comment]
Yet, a render with ffmpeg to png sequence in a mov container yields
anticipated results. Is that result, then, an error?

**Comment by MrKepzie** [comment]
No! This is because FFMPEG outputs RGB only, it dis-regards completely the alpha, so it does not look like a “crop"

**Comment by donkpow** [comment]
What you assume to be a "black background" is a mask.
 [image: Inline image 1]

**Comment by donkpow** [comment]
Okay, I will need time to understand. Thank you for addressing the topic
with me.
