### ISSUE TITLE
Always bug #577 (screencast)

### ISSUE THREAD

**Issue by rcspam** [MrKepzie/Natron#581]
Snapshot f01dca95d1af579d2ee3bc362563ae4b788f7208
A simple screencast is better than a long speech:
[screencast](https://dl.dropboxusercontent.com/u/2677320/screencast-2015-03-28_15.07.51.mkv)

**Comment by MrKepzie** [comment]
Fixed in https://github.com/MrKepzie/openfx-io/commit/441d34b40c95fbbf9d611dcd80d0bfc41b9edce7
