### ISSUE TITLE
Resize and crop unexpected behaviour

### ISSUE THREAD

**Issue by superrune** [MrKepzie/Natron#582]
I am trying to scale up footage temporarily, making it twice the size of my project settings. In Nuke I would either: 

1. Apply a reformat to scale up the footage or 
2. Do a transform and then expand the crop

As Natron doesn't have a reformat, I've tried all kind of combos of transforms and scales, but none seem to be able to scale up the image, as the image stays cropped to the project settings. What is the recommended way to scale the image in Natron?

Also, does Natron concatenate transforms?

**Comment by MrKepzie** [comment]
There’s the resize node.  It does not change the project format though. If you do not want the viewer to apply the clip to the project format, there’s a toggle button on top of the viewer for that. I recommend blackman-harris filter in the Resize node to upscale.
> 
> Also, does Natron concatenate transforms?
> 
Yes
