### ISSUE TITLE
Transform Node issue

### ISSUE THREAD

**Issue by rcspam** [MrKepzie/Natron#583]
Bug in Transform Node !?
 [Here a screencast](https://dl.dropboxusercontent.com/u/2677320/screencast-2015-03-31_17.56.11.mp4)

**Comment by blackearth2014** [comment]
Hey RCSPAM,

I am using version Natron-snapshots-8f4bd8d795504253f0528f3ac3d955c1edb81b19 for Mac and this what I am getting. See attached image.

![transform](https://cloud.githubusercontent.com/assets/7956901/6928833/bdfb0d8e-d7c4-11e4-940d-c8f1d8627935.png)

**Comment by rcspam** [comment]
Hi Omar
I'm enjoy to not be alone to transform nodes ;))

**Comment by rcspam** [comment]
Omar,
This has happened since several snapshots now...

**Comment by rcspam** [comment]
Omar,
I see your Text Node works well on  Mac.
Text (i have tried some fonts) in Text Node doesn't appear on Linux.
Perhaps a specific linux bug ?!
Here an screenshot:
![natron - untitled ntp - _001](https://cloud.githubusercontent.com/assets/10021906/6938541/77c14e50-d864-11e4-99f3-390131886e2f.png)

**Comment by blackearth2014** [comment]
You need to place a constant or solid node in the TextOIIO node's input in order to see what you are typing in the viewer.

**Comment by rcspam** [comment]
Yes i've understood my mistake and  just read #435.

**Comment by MrKepzie** [comment]
Can we close this ?

**Comment by rcspam** [comment]
Yes
