### ISSUE TITLE
Auto-format request

### ISSUE THREAD

**Issue by martymcfly55** [MrKepzie/Natron#584]
Hey Natron Team,

Let me start off by telling you what an awesome job you guys are doing. Really looking forward to seeing Natron reaching great heights.

While using Natron I found certain places can use some attention. They are listed below.

1. When working with different resolutions, it would be great if there is a way the bounding box can snap to actual resolution of each plates automatically. Or even an option to do so can be helpful.

I was recently working on a project with shots containing 2 different resolution. One was 4k res and another 2k. I selected the 'viewer' node and attached '1' to 2k plate and '2' to 4k plate. I haven't touched the project settings yet and Natron must have assumed the resolution of the plate which was imported first. When I switched between them I noticed that the bounding box didn't snap in place for 2k plate. It just stayed the same like 4k.

I closed Natron and interchanged the process. This time the bounding box snapped to 2k plate. But when viewing the 4k plates it gets cropped.

However there was a workaround. It was going to Project settings and changing the resolution. But this seemed to be an unnecessarily long process every time I had to just check different shots.  It would be great if there is a way the bounding box can respond in a same way like it does in Nuke.

2. When working with different frame ranges is it possible to snap the frames to the shot frame range. For now I had to change frame range manually for all the different shots.

An option similar to one's in Nuke would be great like "global", "input", "custom"

3. In the "Read" Node there are 2 colorspace option. In my opinion this can make things a bit messy. Keeping just one colorspace option is enough.

To illustrate, I had imported a alpha matte rendered out in a different software. Natron's default "File colorspace" is set at sRGB and "Output colorspace" is set at "Linear". This showed me an output which didn't look like the one that I had rendered (it was jagged and the blur was gone). Eventually I figured out the right colorspace in the "Output colorspace" and everything looked great.

But this can be an unnecessary hindrance for an artist in my opinion. One should just be able to import the renders and work on it, So a single colorspace tab can be more helpful than double. Again this is my opinion as an artist. I am not sure where the community stands on this point.

Hope to hear from you guys soon. Carry on the great work.

Cheers,
Sourav

**Comment by MrKepzie** [comment]
Hi, thanks for your report. We will consider adding an auto-format like in Nuke, but more opinions on this would be welcome.  Regarding the colorspaces though, we have by experience thought it was clearer to separate what is read from the file (the "File" colorspace) and what is the colorspace in output (the "Output" colorspace). The user should not have anything to configure anyway, it's just in case something is wrong... some TiFFs for example are rendered with incorrect meta-data so we keep those options to overcome the wrong meta datas

**Comment by souravcha** [comment]
Thanks MrKepzie. Appreciate your effort. For Auto formatting of frame ranges we can have have "tick mark" option whether to snap to the frame range of different shot or not. If its not ticked then it will assume the frame range set in the "project settings".

**Comment by sozap** [comment]
Hello !
You have the shift-C shortcut in the viewer to see your 4k plate if your project resolution is 2k.

**Comment by ultra-sonic** [comment]
+1 for this --- see my post on the mailing list with the subject: 
change viewer format to "input stream format"

**Comment by MrKepzie** [comment]
I’ve been thinking of this, but that would mean then to remove the project format from the Viewer and replace it by the  upstream Read node's format. Is the project format not at all relevant in the viewer ?

**Comment by ultra-sonic** [comment]
>
>
>
Is the project format not at all relevant in the viewer ?
>

Not for me and not for any production I was involved so far (10+ years)

Nuke doenst support this either, so I guess none of the users that switch
over will be missing that!

cheers
Oli

**Comment by MrKepzie** [comment]
Oliver,

In the meantime I spoke to some others and they said that the format switching can be confusing because the user does not really knows in the end what the write node is going to output, also the notion of project format is not really “instinctive” in Nuke: you have your viewer linked to a Read 500x500 PAR=1 and your project format set to PAL, yet you wonder why you still get a PAR of 1 everywhere at first. It takes a while to figure out that it blatantly ignores the project format and uses it rarely. 

In Natron I have implemented a useful button on the Viewer named “Clip the visible portion to the project format”. By  default this is on, hence everything outside the project format is not rendered (logical). But once you toggle it, you will be able to see everything outside of it. If you are visualising another image that has a different format, it will then display entirely, which kind of achieves what you are proposing. 

Tell me if that’s not enough, and if so, what’s the point besides being able to see the image entirely

**Comment by devernay** [comment]
Can we close this?

**Comment by martymcfly55** [comment]
Yes please. Btw was just curious when is the next version coming?
