### ISSUE TITLE
Roto minor issue - locking icon

### ISSUE THREAD

**Issue by AurelyenD** [MrKepzie/Natron#585]
Hi, 

When I lock a shape directly in the viewer, (Shift+L) it does not change the lock icon in the control bin.
The lock seems to still open.

Thanks.

Seen on Mac OSX 10.8.5, Natron version 1.2.1 Release .
This version was generated from the source code branch workshop at commit 89ed3731e92fbd73dfc667fa9c780ceca23d6eb1.

**Comment by MrKepzie** [comment]
Fixed for Natron 2
