### ISSUE TITLE
Natron crash with wrong connections...

### ISSUE THREAD

**Issue by rcspam** [MrKepzie/Natron#587]
Natron crash with wrong connections...
https://groups.google.com/d/msg/natron-vfx/oN_7CWqldLc/P-8vkjLnnU4J

**Comment by MrKepzie** [comment]
Hi, this is an issue with the plug-in TuttleColorTransfer, which is incorrectly processing while the viewer is not at a render scale of 1. You should report the issue to the developers there

**Comment by rcspam** [comment]
Done
