### ISSUE TITLE
Last Snapshot (linux) crash when open last recorded project

### ISSUE THREAD

**Issue by rcspam** [MrKepzie/Natron#589]
Last Snapshot (linux) crash when i open last ntp files:

$ ./Natron './XXX.ntp' 
Natron
Version: 2.0.0
Copyright (C) 2015 the Natron developers
>>>Use the --help or -h option to print usage.<<<

didn't know how to process Exif:PixelXDimension, type 9 x 1
didn't know how to process Exif:PixelYDimension, type 9 x 1
Found APP1 XMP! length 3834
Natron: ../FFmpeg/WriteFFmpeg.cpp :2272 : void WriteFFmpegPlugin::updateVisibility():  l'assertion « index < (int)codecsShortNames.size() » a échoué.
./Natron : ligne 31 : 22846 Abandon                 $DIR/bin/Natron -style fusion "$*"

**Comment by rcspam** [comment]
Precision apparently crash when add a transform node in a new project as well...

**Comment by MrKepzie** [comment]
The WriteFFMPEG has been extensively reworked the last days and is no longer compatible with old projects. We will increase the version of the plug-in to make sure Natron does not try to load an old version of the plug-in settings onto the new version.

**Comment by rcspam** [comment]
Would that enable to load project in order to change the non compatible read node ?

**Comment by MrKepzie** [comment]
Yes, but the Write node would then not load

**Comment by rcspam** [comment]
Great thank you

2015-04-07 14:33 GMT+02:00 Alexandre Gauthier <notifications@github.com>:

> Yes, but the Write node would then not load
