### ISSUE TITLE
Natron-snapshots-4d396d3ed9bc7feb7cc27bb900bf09a0da247ad3: WriteFFmpeg & WriteOIIO won't render

### ISSUE THREAD

**Issue by blackearth2014** [MrKepzie/Natron#590]
Since snaphots Natron-snapshots-5972bff00d65be7ee8c8ea6013c66b7d9ebd8e0c and Natron-snapshots-4d396d3ed9bc7feb7cc27bb900bf09a0da247ad3 with the new prores support, I have not been able to render any frames or movies.

4 hours ago  I was getting render errors like in the attached images. I also created a youtube video at http://youtu.be/aPpBfAKCANU. 

![screen shot 2015-04-04 at 10 22 31 pm](https://cloud.githubusercontent.com/assets/7956901/6995750/9d365a9a-db2a-11e4-8eff-c71273363fcf.png)

![screen shot 2015-04-04 at 10 24 24 pm](https://cloud.githubusercontent.com/assets/7956901/6995753/9d3e56e6-db2a-11e4-9aa4-fa0bac0c50a7.png)

![screen shot 2015-04-04 at 11 58 01 pm 2](https://cloud.githubusercontent.com/assets/7956901/6995752/9d3c00a8-db2a-11e4-9f57-76755a180c02.png)

![screen shot 2015-04-04 at 11 58 57 pm 2](https://cloud.githubusercontent.com/assets/7956901/6995751/9d3988be-db2a-11e4-9db5-9a43fda1290d.png)

If I am doing something wrong, please advise. I have already close and opened the natron script with no success.

**Comment by MrKepzie** [comment]
Fixed
