### ISSUE TITLE
Natron-snapshots-4d396d3ed9bc7feb7cc27bb900bf09a0da247ad3: ReadFFmpeg not loading video files.

### ISSUE THREAD

**Issue by blackearth2014** [MrKepzie/Natron#591]
This Natron-snapshots-4d396d3ed9bc7feb7cc27bb900bf09a0da247ad3 version and the one before it keep giving me errors when trying to open my video files captured from my iPhone and other sources. see attached image.

![ffmpeg_error](https://cloud.githubusercontent.com/assets/7956901/6997171/10c47e20-db7f-11e4-8313-3156510e8661.png)

**Comment by MrKepzie** [comment]
This is fixed already, the snapshot is probably not already up to date to the development version
