### ISSUE TITLE
MXF(Material Exchange Format) file format: container issues.

### ISSUE THREAD

**Issue by blackearth2014** [MrKepzie/Natron#594]
This Natron-snapshots-2792376f27960b822f1d687f448eb6020a20f13e version is having an issue with the MXF(Material Exchange Format) file format container support. See attached image for reference.

![mxf container](https://cloud.githubusercontent.com/assets/7956901/7013054/2b624ab8-dc84-11e4-9615-4e46264f002a.png)

**Comment by devernay** [comment]
Hi,
Why is this an issue? The error message is explicit: one cannot use qtrle codec in MXF (mov is probably the only format supported for this codec).
Closing the issue.

**Comment by blackearth2014** [comment]
Please look at the attached image an tell me which codec that you are describing to use for the mxf format.  I have tried all of them and the only one that seems to render is the MPeg2. Only VLC opens the file unless I have set the settings wrong or there is a missing codec on the Mac. I use Editshare Lights and Avid Media Composer in .mxf format with any worries of the codecs.

![which one](https://cloud.githubusercontent.com/assets/7956901/7086358/d2b07aee-df4d-11e4-93fe-4987128c9daf.png)

**Comment by blackearth2014** [comment]
I am also asking for another artist on my NatronNation facebook group. He name is chander Ruzzi. He is from Brazil and needs help with the MXF codec renders.
