### ISSUE TITLE
Natron-snapshots-8c861525d99732965b66e5cc1663eb7a3743ecab: No Alpha output for keying & Roto nodes.

### ISSUE THREAD

**Issue by blackearth2014** [MrKepzie/Natron#596]
This latest Natron-snapshots-8c861525d99732965b66e5cc1663eb7a3743ecab for Mac is not generating key alpha outputs for the follows nodes: Chromakey, Keying and HSVTool. I created additional viewers to check alpha channels and you can see that they are all black. The output alpha components menu are reading RGB instead of RGBA.  Also, if you select the other planes in the output alpha components menu on any node, the RGBA converts to RGB and you loose the ability to effect the alpha. See image for reference.

![screen shot 2015-04-08 at 12 45 10 pm](https://cloud.githubusercontent.com/assets/7956901/7050191/91a516ec-dded-11e4-8c18-39f9b4be8ea8.png)

The same issue is going on with the Roto node.  See image below for reference.

![roto_alpha](https://cloud.githubusercontent.com/assets/7956901/7050366/efeadc22-ddee-11e4-8da4-faaa187e813b.png)

**Comment by blackearth2014** [comment]
I just experimented with something that must have changed in the recent updates.  The image that I had imported load as a RGB. So no matter what I have done with the matte generating nodes, no alpha output was being generated. As soon as I changed the "Output Components" on the ReadOIIO node, the matte generating nodes produced an Alpha Output.  I don't know if this is a bug but this is my workaround.

**Comment by MrKepzie** [comment]
This has always been like that, if you read a jpg or any other image with RGB only, the output components will be RGB. The RGB components support preference should have turned it into RGBA automatically though, this is probably a bug

**Comment by blackearth2014** [comment]
You would think that I would have remembered that before I had made the issue comment. I repeated the process again and the same thing.  The RGB data is not automatically switched to RGBA when the RGB support in preference menu is clicked.  What about when you make changes to the output components to all or other layers and you loose the RGBA to RGB selected choice.
