### ISSUE TITLE
TrackerPM Node: Slow Track Update Analysis

### ISSUE THREAD

**Issue by blackearth2014** [MrKepzie/Natron#598]
I am about to do a project tutorial for my NatronNation Facebook group on tracking, chromakeying and color correction on an image sequence. I am observing that Beta v2.0 TrackPM analysis is whole lot slower than it was in Natron 1.2.1.

I have done 3 video screen capture recordings comparing blender and apple motion 2d tracking to Natron's 2d track. See links provided.

https://youtu.be/xD14OycwWtM - Apple Motion

https://youtu.be/Ar-bri16IlU - Blender

https://youtu.be/rYdx6JnR8Ig - Natron

Another issue since Natron-snapshots-d5b27dc262749ede15a6ca18f0b5129d1ada7a8a version is that when you press the reset button in the tracker node, you can't track another feature. The Score and the Mask options gets greyed out and the track forward button turns red. See image for reference.

![tracker_red](https://cloud.githubusercontent.com/assets/7956901/7104430/a1a27c88-e0ae-11e4-8937-cf9c1f4dffdf.png)

**Comment by MrKepzie** [comment]
Fixed
