### ISSUE TITLE
Bug: Autohide optional inputs only hides some

### ISSUE THREAD

**Issue by nicholascarroll** [MrKepzie/Natron#599]
In latest snapshot the autohide optional inputs is not hiding all optional inputs.
In earlier snapshots it worked better.

**Comment by MrKepzie** [comment]
Can you post a screen-cast explaining how to reproduce the bug please ?

**Comment by nicholascarroll** [comment]
OK I made a screencast and looking where i should upload it...

**Comment by nicholascarroll** [comment]
It's at http://youtu.be/qQUvWkMttDg

**Comment by MrKepzie** [comment]
In fact this is not a bug: I changed the behaviour of this option so only masks inputs get hidden, not the rest. I will change the name of this option right now so it does not confuse the user
