### ISSUE TITLE
Enhancement: Side by side

### ISSUE THREAD

**Issue by nicholascarroll** [MrKepzie/Natron#600]
The viewer has a wipe option as well as minus, over and under. It would be convenient to also have a side by side ('split screen') view here. 

Use Case:
You are zoomed in on a region and now want to view your original in a second window. You choose the option from the A-B menu 'Split Screen' and then when you zoom and pan, both views stay synchronised.

Without This Enhancment:
Without this enhancement, you would have to create another viewer then zoom and pan to get the same region. But even then, it would not follow your further panning and zooming.

**Comment by MrKepzie** [comment]
We will instead add a "Lock" button on viewers to synchronise all viewports so that whenever you zoom/pan on one, all others gets to the same portion and zoom level

**Comment by MrKepzie** [comment]
You can now synchronise viewers by clicking the Lock button
