### ISSUE TITLE
Enhancements in masks

### ISSUE THREAD

**Issue by sozap** [MrKepzie/Natron#605]
Hello,

If nothing is connected to the mask input of a node, is it possible to use directly a channel from the input layer ?
ex :If I'd like to do a grade using a special ID mask channel, ATM I can plug the mask input on the same source and select a multiplane channel. But that would be better to have it directly without the need of doing two connections...

This is not a very important feature, as it's always possible to workaround it, but it allows cleaner graphs especially with exiting multiplanes features coming along.

Thanks !

**Comment by blackearth2014** [comment]
This is something that I ask for a while back called mask injection.

**Comment by MrKepzie** [comment]
https://github.com/MrKepzie/Natron/commit/2810ccf36e05a6ce6ccfb106fb68a281e75234c7

Done in this commit

**Comment by sozap** [comment]
OMG !!

**Comment by devernay** [comment]
The way this was implemented disturbs me: the mask is disconnected in the nodegraph, but it is still connected for processing. Besides, it is impossible to know from which 
There are two solutions in my opinion:
Solution 1: make visible in the nodegraph the fact the mask comes from another input by changing the label to "Label_of_Mask (Label_of_selected_input)", and make the mask arrow always visible (not only when the node is selected or when hovering it)
Solution 2: disable this behaviour

I think solution 1 is a good way to go, do you all agree?

**Comment by blackearth2014** [comment]
Yes!! I agree.

**Comment by devernay** [comment]
This issue was moved to NatronGitHub/Natron#99
