### ISSUE TITLE
Can't open a project file from the file manager.

### ISSUE THREAD

**Issue by OldSkoolVFX** [MrKepzie/Natron#608]
I cannot click on the file in the file manager to successfully open a .NTP file.  Natron start then gives me the error message something to the effect that "project: <file name> is no such file". I can however always open them from the main file menu.  I am using Ubuntu 14,04.

**Comment by olear** [comment]
Stable or snapshot? Spaces or special chars in filename?

Tested in Thunar (filemanager), project files open in Natron here.

**Comment by OldSkoolVFX** [comment]
> Stable or snapshot? Spaces or special chars in filename?
Stable.

Underscores instead of spaces.  One of the folders in the path has [] 
around the text.  There are spaces in the names of folders in the path.  
I tried it in my 'home/<username>/' folder and it clicks open fine I 
then tried it in a folder with a space in the name '/test folder/'and it 
stated that the file was unknown again. I then put it in a folder with 
brackets around the text with no spaces '/[test]/' and it opened just 
fine.  So it's the spaces and not the brackets.  How archaic.  From the 
file menu it opens any .ntp file fine even with spaces.  It only has 
trouble from the file manager.  Unfortunately, the spaces in the path 
names are not going to change.  This is a limitation, thankfully more of 
an inconvenience instead of critical.

In addition, I tried opening a .ntp file in Nautilus (the default file 
manager) and Natron does not start at all.  Nautilus can't find it 
although it is visible in Alacart and has a .desktop file that I made 
which works fine.  It is search-able in Unity and I have it on my 
launcher which also works fine.  So that's a Nautilus issue. Possibly 
due to the lack of a .deb installer.  I really don't know.

I hope that helps.

**Comment by MrKepzie** [comment]
I made a small change, hopefully this fixes the issue https://github.com/MrKepzie/Natron/commit/5fe47225bd46af2590bb5058b514828698b95cc9

**Comment by MrKepzie** [comment]
Can you try the last snapshot and tell us if it fixed it ?

**Comment by devernay** [comment]
is this fixed?
