### ISSUE TITLE
No RGBA only RGB

### ISSUE THREAD

**Issue by nicholascarroll** [MrKepzie/Natron#609]
In april 9 build (v2.0) there was no RGBA viewer option only RGB.

**Comment by MrKepzie** [comment]
This is not a bug: This is because your tree upstream of the viewer is RGB only. You are probably reading from a RGB only file. You can create the alpha channel with a shuffle node or directly in the reader by selecting "RGBA" for output components

**Comment by nicholascarroll** [comment]
I already knew to add shuffle - that was not the problem. Here was my setup: 
  Read(RGB) -> Shuffle(RGBA) -> Viewer
In earlier builds, it worked, and I reverted to 16 Mar build in order to proceed.
I won't reopen this because I don't have a copy of your latest snapshot to test on.
