### ISSUE TITLE
Building on OS X Failed

### ISSUE THREAD

**Issue by azerupi** [MrKepzie/Natron#610]
Hi, 

I'm sorry to bother you with this, but I failed to build Natron on OS X today.

I thought I would take a look at the internals and see if I could fiddle a bit with the code, but I never got past the building stage. I followed the instructions in the INSTALL_OSX file but I got this error:

```
/usr/local/bin/qmake -spec /usr/local/Cellar/qt/4.8.6/mkspecs/macx-xcode -o Gui.xcodeproj/project.pbxproj Gui.pro
sh: python3-config: command not found
sh: python3-config: command not found
sh: python3-config: command not found
env: pkg-config: No such file or directory
env: pkg-config: No such file or directory
sh: python3-config: command not found
env: pkg-config: No such file or directory
env: pkg-config: No such file or directory
env: pkg-config: No such file or directory
sh: pkg-config: command not found
env: pkg-config: No such file or directory
sh: pkg-config: command not found
Project ERROR: Package glew not found
make: *** [Gui.xcodeproj/project.pbxproj] Error 2
```

Any idea about what I could do to resolve this? 

Anyway, congratulations for your hard work !

Mathieu

**Comment by azerupi** [comment]
I just tried on **Arch Linux** too, but I never got all the dependencies. I have installed pyside ```pacman -S python-pyside``` but when I run ```qmake``` it tells me that the pyside development package is not installed. 

The only other pyside package in pacman is for python 2 but you guys use python3 right? 

Also while I am at it, I didn't quite understand what I should put in the ```config.rpi```. Well I did understand that I should put the paths to the libs, but I am not quite sure how to do that.

I would be glad to **try** to help out with little things if I can once I get Natron built :smile: 

Cheers, 

Mathieu

**Comment by olear** [comment]
Linux:
 * https://github.com/olear/natron-linux/blob/master/installer/scripts/build-sdk.sh#L362
 * https://github.com/olear/natron-linux/blob/master/installer/natron/config.pri

Mac:
You are missing many depends, I guess the "doc" has instructions for that(?).

**Comment by azerupi** [comment]
**On OS X**
I am, but I don't know which one. I followed the instructions from the INSTALL_OSX file. So I assumed I had installed all dependencies.

>Install libraries:
```
brew tap homebrew/python
brew tap homebrew/science
brew install qt expat cairo glew
brew install pyside --with-python3
```
To install the openfx-io and openfx-misc sets of plugin, you also need the following:
```
brew install ilmbase openexr freetype fontconfig ffmpeg opencolorio openimageio
```
also set the correct value for the pkg-config path (you can also put this in your .bash_profile):
```
export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:/opt/X11/lib/pkgconfig:/usr/local/opt/cairo/lib/pkgconfig
```

I installed the dependencies with Homebrew like shown, and then I copy pasted the lines for the config.pri into my terminal.

>```
cat > config.pri << EOF
boost: INCLUDEPATH += /usr/local/include
boost: LIBS += -L/usr/local/lib -lboost_serialization-mt -lboost_thread-mt -lboost_system-mt
expat: PKGCONFIG -= expat
expat: INCLUDEPATH += /usr/local/opt/expat/include
expat: LIBS += -L/usr/local/opt/expat/lib -lexpat
EOF
```

Am I missing something? 

**On linux**

I'm sorry I am a little confused, I tried to run your script. But that is not working since it requires a file [```common.sh```](https://github.com/olear/natron-linux/blob/master/installer/scripts/build-sdk.sh#L7) and I didn't find it in your repo or in Natron itself.

**Comment by MrKepzie** [comment]
On MacOSX your config.pri should look like this:

boost {
    INCLUDEPATH += /opt/local/include
    LIBS += -L/opt/local/lib -lboost_serialization-mt
}
shiboken {
PKGCONFIG -= shiboken
INCLUDEPATH += /opt/local/include/shiboken-3.4
LIBS += -L/opt/local/lib -lshiboken.cpython-34m
}


Where /opt/local/ is the installation of your packet manager. I'm using MacPorts

**Comment by azerupi** [comment]
I was able to build with make, but not with xcode. Are there known issues with xcode?

**Comment by MrKepzie** [comment]
Nope since we are using it mainly for developing. You have to use the “Project-code.xcodeproj” and no the one generated by qmake. 
There might be bugs in the compilation order and you might need to build the “libs” target before the “Natron” target

**Comment by azerupi** [comment]
Yes that is the one I use.
The libs target builds fine, but all the other targets *(all, Natron, Tests and NatronRenderer)* fail to build.

**Comment by MrKepzie** [comment]
what's the error message

**Comment by azerupi** [comment]
I get this error **```Command /bin/sh failed with exit code 65```**

I posted a little more detailed output in an earlier post

**Comment by MrKepzie** [comment]
The output in the first post says you're using project.pbxproj. Anyway when you type in your terminal python3-config what happens ? Isn't it named python34-config ?

**Comment by MrKepzie** [comment]
If so, then do a sym link

**Comment by azerupi** [comment]
Ow I'm sorry, I thought I sent another error message but apparently I forgot to send it. My bad.

So the error I have at the moment is:

```
Ld build/Debug/Tests normal x86_64
    cd /Volumes/FilesOSX/MD/Programming/Natron/Tests
    export MACOSX_DEPLOYMENT_TARGET=10.10
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk -L/Volumes/FilesOSX/MD/Programming/Natron/Tests/build/Debug -L/usr/local/Cellar/qt/4.8.6/lib -L/Volumes/FilesOSX/MD/Programming/Natron/Tests/../Gui/build/Release -L/Volumes/FilesOSX/MD/Programming/Natron/Tests/../Engine/build/Release -L/Volumes/FilesOSX/MD/Programming/Natron/Tests/../HostSupport/build/Release -L/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks -L/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/config-3.4m -L/usr/local/Cellar/shiboken/1.2.2/lib -L/usr/local/Cellar/pyside/1.2.2/lib -L/usr/local/lib -L/usr/local/opt/expat/lib -L/usr/local/Cellar/glew/1.11.0/lib -L/usr/local/Cellar/cairo/1.14.0/lib -F/Volumes/FilesOSX/MD/Programming/Natron/Tests/build/Debug -F/usr/local/Cellar/qt/4.8.6/lib -filelist /Volumes/FilesOSX/MD/Programming/Natron/Tests/build/Tests.build/Debug/Tests.build/Objects-normal/x86_64/Tests.LinkFileList -mmacosx-version-min=10.10 -headerpad_max_install_names -L/usr/local/Cellar/qt/4.8.6/lib -F/usr/local/Cellar/qt/4.8.6/lib -L/Volumes/FilesOSX/MD/Programming/Natron/Tests/../Gui/build/Release/ -lGui -L/Volumes/FilesOSX/MD/Programming/Natron/Tests/../Engine/build/Release/ -lEngine -L/Volumes/FilesOSX/MD/Programming/Natron/Tests/../HostSupport/build/Release/ -lHostSupport -L/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/config-3.4m -ldl -L/usr/local/Cellar/shiboken/1.2.2/lib -L/usr/local/Cellar/pyside/1.2.2/lib -undefined dynamic_lookup -L/usr/local/lib -L/usr/local/opt/expat/lib -L/usr/local/Cellar/glew/1.11.0/lib -L/usr/local/Cellar/cairo/1.14.0/lib -L/usr/local/Cellar/qt/4.8.6/lib -F/usr/local/Cellar/qt/4.8.6/lib -framework CoreServices /Library/Frameworks/Python.framework/Versions/3.4/Python -framework CoreFoundation -lpyside.cpython-34m.1.2.2 -lboost_serialization-mt -lboost_thread-mt -lboost_system-mt -lshiboken.cpython-34m.1.2.2 -lexpat.1 -lGLEW.1.11.0 -lcairo.2 -framework QtOpenGL -framework QtGui -framework QtCore -framework QtNetwork -framework OpenGL -framework AGL -Xlinker -dependency_info -Xlinker /Volumes/FilesOSX/MD/Programming/Natron/Tests/build/Tests.build/Debug/Tests.build/Objects-normal/x86_64/Tests_dependency_info.dat -o /Volumes/FilesOSX/MD/Programming/Natron/Tests/build/Debug/Tests
ld: warning: directory not found for option '-L/Volumes/FilesOSX/MD/Programming/Natron/Tests/../Gui/build/Release'
ld: warning: directory not found for option '-L/Volumes/FilesOSX/MD/Programming/Natron/Tests/../Engine/build/Release'
ld: warning: directory not found for option '-L/Volumes/FilesOSX/MD/Programming/Natron/Tests/../HostSupport/build/Release'
ld: warning: directory not found for option '-L/Volumes/FilesOSX/MD/Programming/Natron/Tests/../Gui/build/Release/'
ld: warning: directory not found for option '-L/Volumes/FilesOSX/MD/Programming/Natron/Tests/../Engine/build/Release/'
ld: warning: directory not found for option '-L/Volumes/FilesOSX/MD/Programming/Natron/Tests/../HostSupport/build/Release/'
ld: library not found for -lGui
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** BUILD FAILED **


The following build commands failed:
	Ld build/Debug/Tests normal x86_64
(1 failure)
Showing first 200 notices only
Command /bin/sh failed with exit code 65
```

**Comment by olear** [comment]
@azerupi:
The Linux links was examples for how to build. I can probably make a small depends script for Arch if you need it.

**Comment by azerupi** [comment]
And my python3-config is named python3-config 

```
Hackintosh:Natron MD$ python3-config
Usage: /Library/Frameworks/Python.framework/Versions/3.4/bin/python3-config [--prefix|--exec-prefix|--includes|--libs|--cflags|--ldflags|--extension-suffix|--help|--abiflags|--configdir]
```

**Comment by MrKepzie** [comment]
Seems like the Gui lib has not been compiled in fact, can you check that the libGui.a has been produced correctly ?

**Comment by azerupi** [comment]
@olear that would be awesome ! But only if it's not too much work for you :)

**Comment by olear** [comment]
That's ok, downloading Arch now.

**Comment by azerupi** [comment]
Yes, it has.
![libgui a](https://cloud.githubusercontent.com/assets/7647338/7297713/d986ae4c-e9ca-11e4-8134-38cd486cab27.jpg)

**Comment by MrKepzie** [comment]
Ok the problem is that in Xcode we are using the "legacy" mode for the output build. Go in Preferences --->Locations ---> Derived Datas , choose Relative. Click the advandced button and select "legacy"

**Comment by azerupi** [comment]
That didn't change anything unfortunately

**Comment by MrKepzie** [comment]
Well you should have a Gui/build/Release/libGui.a , Engine/build/Release/libEngine.a etc... now. The Natron target expects those paths (this is a constraint of qmake in fact)

**Comment by azerupi** [comment]
I got no Release folder but I did get a Debug and Gui.build folder. I guess that is why it is still failing?
```Gui/build/Debug/libGui.a``` and in ```Gui/build/Gui.build/``` I have a Debug and a Release folder bot containing a Gui.build subfolder

**Comment by MrKepzie** [comment]
Make sure you clean your solution (CMD + SHIFT+ K) and remove all build folders to make sure you are not mixing old files. 
I'm worried the solution is not building because is using old files you built using the non "Legacy" system.

**Comment by azerupi** [comment]
Ok I will try that. If need be I can delete everything and clone the git repo again. I will let you know if I have any success. 

Thanks for your help (and patience) :)

**Comment by azerupi** [comment]
No, deleting my local copy of the repo and trying to build again in legacy mode didn't work. But I do not have a Release folder like you said I would. I have this:
![untitled](https://cloud.githubusercontent.com/assets/7647338/7298807/278bf212-e9d2-11e4-8e06-b4f3fdf3df48.jpg)

**Comment by MrKepzie** [comment]
I'm afraid you are trying to run the target in Release mode whilst in fact you build for Debug. 
Select the Natron target
Goto Product--> Scheme--> Edit scheme --> Run, select the Info tab and select "Debug" .

This will build the "Debug" Natron.app.
If you want all in release, then you'll have to set the libs & app schemes to Release

**Comment by azerupi** [comment]
I checked, the build configuration for every target is set to **Debug**

**Comment by MrKepzie** [comment]
Well then can you repost the error message please ?

**Comment by azerupi** [comment]
I have to leave, I will not be home for the weekend. But I can try on another mac. 

This is the error message I get:

```
Ld build/Debug/Natron.app/Contents/MacOS/Natron normal x86_64
    cd /Volumes/FilesOSX/MD/Programming/Natron/App
    export MACOSX_DEPLOYMENT_TARGET=10.10
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk -L/Volumes/FilesOSX/MD/Programming/Natron/App/build/Debug -L/usr/local/Cellar/qt/4.8.6/lib -L/Volumes/FilesOSX/MD/Programming/Natron/App/../Gui/build/Release -L/Volumes/FilesOSX/MD/Programming/Natron/App/../Engine/build/Release -L/Volumes/FilesOSX/MD/Programming/Natron/App/../HostSupport/build/Release -L/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks -L/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/config-3.4m -L/usr/local/Cellar/shiboken/1.2.2/lib -L/usr/local/Cellar/pyside/1.2.2/lib -L/usr/local/lib -L/usr/local/opt/expat/lib -L/usr/local/Cellar/glew/1.11.0/lib -L/usr/local/Cellar/cairo/1.14.0/lib -F/Volumes/FilesOSX/MD/Programming/Natron/App/build/Debug -F/usr/local/Cellar/qt/4.8.6/lib -filelist /Volumes/FilesOSX/MD/Programming/Natron/App/build/Natron.build/Debug/Natron.build/Objects-normal/x86_64/Natron.LinkFileList -mmacosx-version-min=10.10 -headerpad_max_install_names -L/usr/local/Cellar/qt/4.8.6/lib -F/usr/local/Cellar/qt/4.8.6/lib -L/Volumes/FilesOSX/MD/Programming/Natron/App/../Gui/build/Release/ -lGui -L/Volumes/FilesOSX/MD/Programming/Natron/App/../Engine/build/Release/ -lEngine -L/Volumes/FilesOSX/MD/Programming/Natron/App/../HostSupport/build/Release/ -lHostSupport -L/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/config-3.4m -ldl -L/usr/local/Cellar/shiboken/1.2.2/lib -L/usr/local/Cellar/pyside/1.2.2/lib -undefined dynamic_lookup -L/usr/local/lib -L/usr/local/opt/expat/lib -L/usr/local/Cellar/glew/1.11.0/lib -L/usr/local/Cellar/cairo/1.14.0/lib -L/usr/local/Cellar/qt/4.8.6/lib -F/usr/local/Cellar/qt/4.8.6/lib -framework CoreServices /Library/Frameworks/Python.framework/Versions/3.4/Python -framework CoreFoundation -lpyside.cpython-34m.1.2.2 -lshiboken.cpython-34m.1.2.2 -lboost_serialization-mt -lboost_thread-mt -lboost_system-mt -lexpat.1 -lGLEW.1.11.0 -lcairo.2 -framework QtOpenGL -framework QtGui -framework QtCore -framework QtNetwork -framework OpenGL -framework AGL -Xlinker -dependency_info -Xlinker /Volumes/FilesOSX/MD/Programming/Natron/App/build/Natron.build/Debug/Natron.build/Objects-normal/x86_64/Natron_dependency_info.dat -o /Volumes/FilesOSX/MD/Programming/Natron/App/build/Debug/Natron.app/Contents/MacOS/Natron
ld: warning: directory not found for option '-L/Volumes/FilesOSX/MD/Programming/Natron/App/../Gui/build/Release'
ld: warning: directory not found for option '-L/Volumes/FilesOSX/MD/Programming/Natron/App/../Engine/build/Release'
ld: warning: directory not found for option '-L/Volumes/FilesOSX/MD/Programming/Natron/App/../HostSupport/build/Release'
ld: warning: directory not found for option '-L/Volumes/FilesOSX/MD/Programming/Natron/App/../Gui/build/Release/'
ld: warning: directory not found for option '-L/Volumes/FilesOSX/MD/Programming/Natron/App/../Engine/build/Release/'
ld: warning: directory not found for option '-L/Volumes/FilesOSX/MD/Programming/Natron/App/../HostSupport/build/Release/'
ld: library not found for -lGui
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** BUILD FAILED **


The following build commands failed:
	Ld build/Debug/Natron.app/Contents/MacOS/Natron normal x86_64
(1 failure)
Showing first 200 notices only
Command /bin/sh failed with exit code 65
```

**Comment by MrKepzie** [comment]
Aight the problem is that you issued the wrong qmake call, this should be:

    qmake -r -spec macx-xcode CONFIG+=debug

**Comment by azerupi** [comment]
Right! That makes sense. I will try that when I get home :)

**Comment by olear** [comment]
https://github.com/olear/natron-linux/commit/dc993fc2cefbeeb1dbd0e4fb9c51b5c8338464a0

Build on ArchLinux:
```
pacman -S qt4 cairo glew python expat boost pixman ffmpeg opencolorio openimageio wget git cmake gcc make libxslt pkg-config
wget https://raw.githubusercontent.com/olear/natron-linux/master/installer/misc/build-natron-on-archlinux.sh
```
Now run the script as root (needed the first time to install depends), then when instructed rerun the script as user (from your homedir).

**Comment by azerupi** [comment]
@olear Worked like a charm ! Thank you :)

You should definitely put some info about this in the [INSTALL_LINUX.md](https://github.com/MrKepzie/Natron/blob/workshop/INSTALL_LINUX.md) file. This is a huge time saver for less experienced people like me ;)

**Comment by azerupi** [comment]
@MrKepzie Sorry to bother you, but I'm trying to build Natron with XCode again and it continues to fail.

I get the following error:
```
PBXCp /Volumes/FilesOSX/MD/Programming/Natron-dev/Natron/Gui/Resources/OpenColorIO-Configs build/Debug/Natron.app/Contents/Resources/OpenColorIO-Configs
    cd /Volumes/FilesOSX/MD/Programming/Natron-dev/Natron/App
    builtin-copy -exclude .DS_Store -exclude CVS -exclude .svn -exclude .git -exclude .hg -resolve-src-symlinks /Volumes/FilesOSX/MD/Programming/Natron-dev/Natron/Gui/Resources/OpenColorIO-Configs /Volumes/FilesOSX/MD/Programming/Natron-dev/Natron/App/build/Debug/Natron.app/Contents/Resources
error: remove /Volumes/FilesOSX/MD/Programming/Natron-dev/Natron/App/build/Debug/Natron.app/Contents/Resources/OpenColorIO-Configs: Directory not empty
error: couldn't remove '/Volumes/FilesOSX/MD/Programming/Natron-dev/Natron/App/build/Debug/Natron.app/Contents/Resources/OpenColorIO-Configs' after command failed: Directory not empty

** BUILD FAILED **
```

From the command line with `make` it works perfectly, but I would like to be able to build from XCode for the convenience :)

Any idea about what could be the problem?

**Comment by MrKepzie** [comment]
It seems it is not able to copy OpenColorIO-Configs to the application bundle. 
Seems like a user permissions issue, check your permissions on your dev folder.

Xcode works fine here, we use it to develop.

**Comment by azerupi** [comment]
What kind of permissions does XCode need? I am the owner of the directory so that gives me Read&Write access.

I guess it's some obscure setting that isn't set properly, but I have no idea where to look.

**Comment by MrKepzie** [comment]
I don’t know, I’d say standard 755
In a terminal:

chmod 755 /Volumes/FilesOSX/MD/Programming

**Comment by azerupi** [comment]
That doesn't seem to be the problem, I changed every directory in my working directory to chmod 755 and I still get the same error.. :confused:

**Comment by azerupi** [comment]
I have no clue why, but it works now..
Could issuing `qmake -r ../Project.pro -spec macx-xcode CONFIG+=debug` in a subdir like `build` be the reason? This time I executed the command at the root
