### ISSUE TITLE
TrackerPM: Feature Request - Lock to Track

### ISSUE THREAD

**Issue by blackearth2014** [MrKepzie/Natron#611]
Is it possible to get a lock to track feature so that the tracker stays center of view while analyzing the feature? To me it is easy to see if the tracker slips on more than 2 frames without having to check the curve animation data.

Also, can we get a tracker 2-4x zoom magnifier when placing trackers without the need to keep zooming in and out in the viewer?

Last, can we have the ability to track individual color channels as well as black and white?

**Comment by MrKepzie** [comment]
In fact we were thinking with Fred of a magnifier that could be used not only for tracking but for anything else. Aight for the viewer staying focused on a track (note this will induce a slight slowdown though)

**Comment by blackearth2014** [comment]
The TrackerPM node algorithms are already slow. If adding this feature is going to make it slower, I will retract the request. Are there any development plans to implement faster score algorithms? Or, could it be that my system is not caching fast enough?

**Comment by azerupi** [comment]
> If adding this feature is going to make it slower, I will retract the request.

Just make it optional via a checkbox ;)

**Comment by devernay** [comment]
I also think this should be an option when reviewing existing tracks. Or should we have a small subwindow in the viewer with the window around the selected track?

**Comment by blackearth2014** [comment]
We should we have a small subwindow in the viewer with the window around the selected track?

**Comment by devernay** [comment]
This issue was moved to NatronGitHub/Natron#100
