### ISSUE TITLE
Third-party plugin crash on Win64

### ISSUE THREAD

**Issue by olear** [MrKepzie/Natron#612]
Hi, started a new ofx bundle (openfx-arena) a couple of days ago, and as usual tested only on Linux (works flawless). When time to test on Windows I hit a problem, the plugin crash on Natron (1/2) when rendering of the image starts. I sadly get not feedback, so I have no idea what the problem can be, the plugins works as they should in Nuke8. I used MinGW to build the bundle, used the same toolchain and depends as in openfx-magic (works flawless on Natron in Windows). The only difference between openfx-arena and openfx-magick is that openfx-magick is based on openfx-opencv, and openfx-arena is based on openfx-io.

Nuke:
![swirl-win64-nuke8](https://cloud.githubusercontent.com/assets/7461595/7335139/cb705b00-ebaa-11e4-8e97-ceb85064b8e1.png)
Natron:
![swirl-win64-natron](https://cloud.githubusercontent.com/assets/7461595/7335140/d18beeaa-ebaa-11e4-8290-631ce587c2a4.png)
Bundle:
https://github.com/olear/openfx-arena/releases/download/0.3/Arena.ofx.bundle-Win64-test.7z

https://github.com/olear/openfx-arena/issues/1

May be an issue on my part, but though this was a bit strange since it worked on Nuke.

The bundle is compiled (static) against zlib, expat, png, freetype, fontconfig and magick++.

**Comment by MrKepzie** [comment]
Have you tried with the snapshots ?

**Comment by olear** [comment]
Tested on stable and workshop.

**Comment by MrKepzie** [comment]
I will try it out on windows

**Comment by olear** [comment]
Thanks. btw, is it possible to add a console on the Windows snapshot? Would be nice to get some output :)

**Comment by olear** [comment]
The plugin bundle also works in Sony Vegas 12.

**Comment by MrKepzie** [comment]
The problem is that you're calling the clipReleaseImage function to many times on the same Image handle. This function is called in the destructor of the OFX::Image, that means that you are deleting twice (or more) the same image object. Maybe Nuke (and other softwares) are more tolerant on this

**Comment by olear** [comment]
Ok, but it works on Linux.

**Comment by MrKepzie** [comment]
Yeah but you know memory errors tolerance is not the same across the board:) I can assure you that the issue is because you delete the image twice. Post your code in a gist if you want some help

**Comment by olear** [comment]
Ok :)

https://github.com/olear/openfx-arena/blob/master/Magick/MagickSwirl.cpp

**Comment by MrKepzie** [comment]
What 
Magick::Image magickImage(magickWidth,magickHeight,"RGBA",Magick::FloatPixel,(float*)srcImg->getPixelData());
do ?

Does it copy the source image or just make a container encapsulating the buffer ?
Writing to the source image is forbidden, the only operation allowed is to write onto the dst image on the render window specified.

**Comment by olear** [comment]
That code reads the image into a Magick::Image

**Comment by olear** [comment]
The "old" plugin uses:
https://github.com/olear/openfx-magick/blob/master/plugins/Swirl/Swirl.cpp#L178

And works.

**Comment by olear** [comment]
Will find another way to read the clip, close since not an bug in Natron.

**Comment by olear** [comment]
I'm a bit lost on this one, All I do is create a new image using the srcImg->getPixelData, all operations are done on the new image.

```
Read image based on an array of image pixels.

const size_t width_, const size_t height_, std::string map_, const StorageType type_, const void *pixels_

Magick::Image magickImage(magickWidth,magickHeight,"RGBA",Magick::FloatPixel,(float*)srcImg->getPixelData());
```

Is this wrong?

On the old plugin I used

```
gPropHost->propGetPointer(sourceImg, kOfxImagePropData, 0, &srcPtr);
Magick::Image image(width,height,"RGBA",Magick::FloatPixel,(float*)srcPtr);
```

Sorry if the question is stupid :)

**Comment by MrKepzie** [comment]
Note that you’re not allowed to read the source image beyond what you requested in getRegionsOfInterest. 
Basically if your plug-in does not support tiles, the render window will be the full image. 
Make sure this constructor of Magick::Image makes a copy of the source image.

**Comment by olear** [comment]
Forgot to add support for RGB, really a stupid mistake, sorry about that one :)

**Comment by Tungee** [comment]
Ole, is there also a OSx version or are any plans to bundle it with Natron?!
Best Regards

2015-04-29 6:33 GMT+02:00 Ole-André Rodlie <notifications@github.com>:

**Comment by devernay** [comment]
I'll work on it

**Comment by olear** [comment]
I'm currently writing a multibuild script for win/lin/bsd, should be easy to adapt.
