### ISSUE TITLE
self-build crashes on start

### ISSUE THREAD

**Issue by azerupi** [MrKepzie/Natron#613]
Hi, I got Natron to build but it crashes on startup.

In debug it says this assert fails:

```c++
assert(PyObject_HasAttrString(_imp->mainModule, "natron") == 1);
```

What does this mean?

**Comment by MrKepzie** [comment]
Probably because the PySide modules are not properly installed I guess

**Comment by azerupi** [comment]
I installed it with homebrew... :/

**Comment by MrKepzie** [comment]
well make sure PySide is compiled against Python3.4 and can be found in the python path  (it should be in the site-packages)

**Comment by azerupi** [comment]
I uninstalled PySide, when uninstalled it doesn't compile (nothing abnormal here). 
I have reinstalled PySide, and now it compiles fine. So I guess that means PySide is correctly installed.

Yet the assertion fails

**Comment by azerupi** [comment]
Maybe it is also worth mentioning that I compile in DEBUG and not in RELEASE, could that change something?

**Comment by MrKepzie** [comment]
It should not, the error is related to the fact that shiboken is not properly registering the built-in Natron python modules.
Every times I encountered this assert this was because of a wrong Python path (export PYTHONPATH) or incorrect Pyside (make sure it does not depend on Python 2.7)

**Comment by olear** [comment]
If you used the build script for Arch then pyside/shiboken is located in /opt/Natron-2.0

**Comment by azerupi** [comment]
No it worked fine on Arch, you did a really good job with the script ;) 
I'm trying on OS X, I was able to solve the previous problems I had while compiling thanks to MrKepzie. Now it compiles just fine, but it crashes before displaying any GUI.

I am using pyenv https://github.com/yyuu/pyenv to manage virtual environments with python, could that cause some trouble ?

**Comment by MrKepzie** [comment]
I have no idea, but I can assure you this issue is related to Python. Make sure that your build of Natron is linking against Python 3.4 and PySide/shibken too.

**Comment by azerupi** [comment]
I am not really sure how to do that, but you can close the issue. I know
what I should look into. If I find a solution I will get back at you so
that you can eventually make a troubleshoot section in the install page to
help others.

Thank you for your time
