### ISSUE TITLE
proposal design for node graph

### ISSUE THREAD

**Issue by manuelsongokuh** [MrKepzie/Natron#614]
hello

i start to use Natron i never to use nuke or other software composite..
so i want to give you any idea proposal design

![propostal-natron-manuel](https://cloud.githubusercontent.com/assets/12126929/7339093/77083516-ec62-11e4-82ab-4669240644b0.png)
i'm not programmer, i'm design and new natron..

but i dont know where i can send my proposal design report...
thank you

**Comment by MrKepzie** [comment]
Hi, thanks for design suggestions, you should post them on the forums instead and share opinions with the community
