### ISSUE TITLE
layout problem

### ISSUE THREAD

**Issue by kuntalmz** [MrKepzie/Natron#615]
I made a custom layout which looks like this-
![viewer](https://cloud.githubusercontent.com/assets/12135951/7346942/fb97d1da-ed00-11e4-8bf5-ddd69ac4239b.png)
but after setting it as default upon restart the viewer gets with the node graph editor!1
![no viewer](https://cloud.githubusercontent.com/assets/12135951/7346953/2532af9c-ed01-11e4-9fe0-0f0dc7a0f953.png)

**Comment by MrKepzie** [comment]
You see the top left button of the node graph pane ? (the "Manage layout for this pane" button). The orange mark indicates that this is the "viewer anchor": all viewers created will be created on this pane. When saving your custom layout, ensure that you have set the anchor on the appropriate pane.
