### ISSUE TITLE
WIPE TOGGLE: frozer or not move..

### ISSUE THREAD

**Issue by manuelsongokuh** [MrKepzie/Natron#616]
hello

i add image (read) and add trasform: "TuttleLensDistort" without connector and WIPE is blocked (i mean i cant move WIPE toggle or it's FROZER)
![natron-bug-01](https://cloud.githubusercontent.com/assets/12126929/7358940/d08b346c-ed39-11e4-88b1-69165f8e4af6.png)
i cancel "tuttlelensdistort" and WIPE TOGGLE is move and not blocked..
why? it's bug?

thank you

**Comment by devernay** [comment]
It's a TuttleLensDistort bug (their interact catches pendown even if it does nothing). Just close the TuttleLensDistort panel and it will work.
I will commit a workaround soon.

**Comment by manuelsongokuh** [comment]
thank you
