### ISSUE TITLE
Crash when you open a file dialog

### ISSUE THREAD

**Issue by ipbtaliz** [MrKepzie/Natron#617]
I have tried both the latest snapshot and v1.2.1 and, whenever I open a file dialog (like when I try to save a project), Natron will freeze and then crash just after it shows me the file dialog.
(I'm on Windows 8.1 64 bit. I've tried Natron 64bit and 32bit).

**Comment by MrKepzie** [comment]
This is a bug that has been reported quite often, and has been resolved in the past by editing the Windows registry. See https://github.com/MrKepzie/Natron/issues/413 <https://github.com/MrKepzie/Natron/issues/413>

**Comment by ipbtaliz** [comment]
Thanks for the fast reply and solution. Please consider fixing it in the future with a proper fix. Keep up the good work with Natron: it is a nice software.

**Comment by MrKepzie** [comment]
We have been unable to reproduce this particular crash (which seems to occur only on Windows), so until we can make it crash ourselves I’m not sure there’s anything we can do about it.
