### ISSUE TITLE
No OCIO Display node available

### ISSUE THREAD

**Issue by mjmvisser** [MrKepzie/Natron#619]
My apologies for opening #618, our $OCIO environment variable is indeed working correctly, so I have closed that issue. However, there does not appear to be an OCIO Display node, so it's not possible to currently use Natron in our comp workflow. We rely on OCIO's Displays and Views (and Looks) for our Viewer processes.

**Comment by blackearth2014** [comment]
mjmvisser

Do you have a screenshot of what the OCIO displays and views suppose to look like? I never heard of this workflow.

**Comment by mjmvisser** [comment]
Sure! Here's the OCIO Display node in Nuke:
![image](https://cloud.githubusercontent.com/assets/351739/7421800/bcd08f80-ef55-11e4-9e47-4122d22ef3b4.png)

The source code is actually part of OCIO (https://github.com/imageworks/OpenColorIO/tree/master/src/nuke). It has gain and gamma knobs, so can be used directly as a Viewer process. 

Displays are usually mapped to display devices, e.g. sRGB, Rec.709 or DCI P3. You set this to the actual display you are using.

Views are more abstract, representing different ways to view content in a display-independent manner. For example, we have views named "Native", "Raw" and "Shot LUT". "Native" transforms to the native colorspace of each display, "Raw" does no color transform, and "Shot LUT" is Native with OCIO Look applied.

In our show-wide Nuke init.py, we add a viewer process for the Shot LUT:

`nuke.ViewerProcess.register("a47 Shot LUT", nuke.createNode, ('OCIODisplay', 'colorspace linear/alexa display sRGB view {Shot LUT} layer rgb'))`

That way, it shows up in the nuke viewer process menu:
![image](https://cloud.githubusercontent.com/assets/351739/7422052/9b8f7816-ef57-11e4-9207-178f906d6e2e.png)

And here's what our OCIO Displays and Views look like in RV (a viewer):
![image](https://cloud.githubusercontent.com/assets/351739/7421998/3e904f50-ef57-11e4-8880-ad7056196565.png)
![image](https://cloud.githubusercontent.com/assets/351739/7422009/4d764218-ef57-11e4-9339-839eda79c490.png)

This is very typical workflow in VFX.

cheers,
-Mark

**Comment by blackearth2014** [comment]
Okay. I understand now. I've seen that before in Nuke.

**Comment by devernay** [comment]
working on it

**Comment by devernay** [comment]
implemented! closing the issue. please reopen an issue if you find a bug.
https://github.com/MrKepzie/openfx-io/commit/1440616ed17b0db3c5582b2aa1c1091e707bd3bb

Note that you can now also use OCIO contexts, see http://opencolorio.org/userguide/contexts.html
