### ISSUE TITLE
Resize: stripes appearing when changing aspect ratio 

### ISSUE THREAD

**Issue by blackearth2014** [MrKepzie/Natron#621]
The merge node won't allow me to merge a background image with the foreground image because of some aspect ratio conflict. Even with the resize node it won't allow me to merge.  See attached image for reference.

![merge issue 1](https://cloud.githubusercontent.com/assets/7956901/7455831/79d405fe-f24d-11e4-8229-b35fdd67156f.png)

**Comment by MrKepzie** [comment]
What's the FPS of your project + FPS of your readers ?

**Comment by blackearth2014** [comment]
These were still images. I will rebuilt the project.

**Comment by blackearth2014** [comment]
The problem is with SD images. I have a SD image with a resolution of 720 * 405. When I try to merge other images with or without the resize node, I get the pixel aspect ratio warnings.  I don't get them when working with the HD and above resolutions.

![pixel aspect ratio](https://cloud.githubusercontent.com/assets/7956901/7456888/2642d0ce-f256-11e4-8cfd-d4827552e91b.png)

**Comment by MrKepzie** [comment]
The Resize node in mode "Size" will not change the pixel aspect ratio meta data. Make sure to choose the "Format" mode, which will properly propagate downstream the correct PAR.

**Comment by blackearth2014** [comment]
Thanks.

**Comment by blackearth2014** [comment]
I did what you have asked and still the say problem. Just to be clear. This was never a problem  before these past 2-3 snapshots. Natron has always merged different ReadOIIO images with different PAR's. There is no problem with HD's images like I mentioned before. The issues are in the SD resolutions. I know HD is now standard in most to all cases.

Unfortunately, I still get work from those who are still holding on to their SD firewire tape cameras and doing green screen work.  Attached is the latest of my workarounds, but another issue popped up.

![just more issues](https://cloud.githubusercontent.com/assets/7956901/7460547/cb983422-f271-11e4-8696-8e487c2e5001.png)

**Comment by MrKepzie** [comment]
I think I fixed that, can you confirm with subsequent snapshots please

**Comment by blackearth2014** [comment]
As soon as the snapshot send a release I will let you know.

Thanks.

**Comment by devernay** [comment]
Comparing aspect ratios can be a bit tricky. @MrKepzie these is code for this in writeffmpeg

**Comment by blackearth2014** [comment]
Okay,

I did further testing and the problem is still there but then its not based on a resize node reconnect workaround.  The follow images will tell the story and I will comment.

This is the same issue from before.
![jpeg_before_resizenode](https://cloud.githubusercontent.com/assets/7956901/7493650/b8604286-f3d0-11e4-9547-bb8b54ead836.png)

The image below is the jpeg meta data from the image info button on the ReadOIIO.
![jpeg_metadata](https://cloud.githubusercontent.com/assets/7956901/7493649/b8603fde-f3d0-11e4-8550-2378f8a46b66.png)

The image below is the PNG meta data from the image info button on the ReadOIIO.
![png_results](https://cloud.githubusercontent.com/assets/7956901/7493647/b85b68f6-f3d0-11e4-9d5c-45d28b07e785.png)

This image is from my first workaround but due to your recent update, this is the result.
![jpeg_issueresizenode](https://cloud.githubusercontent.com/assets/7956901/7493646/b8592f96-f3d0-11e4-83d8-3a15c7dad1c7.png)


This is the workaround results of me adding and connecting a resize node to the stream and then disconnected it. Then I just reconnected the Merge node input "A" to the JPEG ReadOIIO and all is well. 
![jpeg_afterresizenode_reconnect](https://cloud.githubusercontent.com/assets/7956901/7493648/b85bcd46-f3d0-11e4-806c-6b85902b8ee9.png)

I had opened the original jpeg file in gimp and saved it as png. The same file as png worked like it did with the jpeg files a few snapshots ago.  I am assuming that there is an issue with the meta data in the header files in the jpeg file.

**Comment by MrKepzie** [comment]
Can you send me this jpg?

**Comment by blackearth2014** [comment]
Here is the file you have requested.

![blue_screen_pic](https://cloud.githubusercontent.com/assets/7956901/7501964/44110d76-f406-11e4-93af-43a5343927c8.jpg)

**Comment by MrKepzie** [comment]
The stripes are from a bug in the Resize node. 
Regarding your comp, I don't see where the bug is? You are trying to merge images with 2 different aspect ratios, we don't allow this, using a resize to match the PAR should fix it. I will try to see what's going on in the Resize bug in the meantime;
