### ISSUE TITLE
Scrollbar needed for very long list

### ISSUE THREAD

**Issue by rcspam** [MrKepzie/Natron#622]
Hi Alex,
In reference to #620, is it possible to add a scrollbar, it would be more convenient when lists are very long (e.g. lot of fonts).
Best

**Comment by MrKepzie** [comment]
Already added, you probably have an old build #620 fixes it. If you have a more recent version than the commit that fixed it and it still does not work, please re-open.

**Comment by rcspam** [comment]
I have the last "May 4 snapshot", i have only the up and down bar in the above and under of the list. No SideBar as you can see in the following screenshot:
 
![natron - untitled ntp - _001](https://cloud.githubusercontent.com/assets/10021906/7493407/db78e2c0-f400-11e4-989b-78f57eb81e5b.png)

**Comment by MrKepzie** [comment]
Yes this is intended.
If we were to add a scrollbar, we would have to completely re-implement the dropdown menu

**Comment by rcspam** [comment]
Sorry but this is not very useful for long list.
Perhaps "mouse wheel step"  could be an option appearance pref !
