### ISSUE TITLE
Crashing while Tracking

### ISSUE THREAD

**Issue by hyperfx** [MrKepzie/Natron#626]
Today I tried tracking some simple jpg frame sequences, and it's crashed on me every time. First I was using a build from April 24th, then I tried using a build from today, May 13th. Both crashed.

If there's some crash report you would like to see, just let me know how to get it.

**Comment by hyperfx** [comment]
Oh, I should also mention I'm using the Windows 64 version. I'm on Windows 7.

**Comment by MrKepzie** [comment]
We’ve been playing around and making many changes for the integration of the rotopaint, it might have broken a few things around in the meantime. I will take a look at it

**Comment by MrKepzie** [comment]
Btw what are the exact steps to make it crash?

**Comment by MrKepzie** [comment]
Aight I just pushed a commit that should fix it, I reproduced the crash on Windows 7 and now its gone.

**Comment by hyperfx** [comment]
Awesome, thanks!! The steps to reproduce were:
1 - Bring in footage
2 - Try to track something on the footage

But I guess you figured it out already. ;)

Will check the next updated daily build. Thanks again!
