### ISSUE TITLE
PNG Quicktime codec can´t be read

### ISSUE THREAD

**Issue by sirdavid32** [MrKepzie/Natron#628]
Hello I get a read error on a Quicktime .mov movie clip wich was compressed using .png codec. 
Here´s the capture of the video and codec:
![codec](https://cloud.githubusercontent.com/assets/11066585/7662571/a67a41ac-fb23-11e4-969a-435dd3568557.jpg)

And natron´s error says: ReadFFmpeg1 error: Unable to find video stream.

**Comment by olear** [comment]
Probably related to the version of ffmpeg shipped with Natron(?), you can download another version of ffmpeg (gpl) and replace the dll's shipped with Natron (Plugins/IO.ofx.bundle/Contents/Win*) if wanted.

**Comment by MrKepzie** [comment]
This will be fixed in the release of Natron 2.0, this is because currently the snapshots of the Windows are not using the last version of ffmpeg. 
In the meantime you can use other platforms (OS X,Linux) on which it works flawlessly.
