### ISSUE TITLE
Fullscreen: Error dialog on startup

### ISSUE THREAD

**Issue by olear** [MrKepzie/Natron#629]
Using fullscreen on Natron works, but not on startup, giving a error dialog.
![screenshot](https://cloud.githubusercontent.com/assets/7461595/7704671/1d3a0efc-fe40-11e4-9f06-ee623ce69bc8.png)

Confirmed in v1 and v2. Not critical, but annoying.

**Comment by MrKepzie** [comment]
qApp->activeWindow();

returns NULL, meaning you probably don’t have any window yet. Not much we can do I guess

**Comment by blackearth2014** [comment]
This happens on the Mac as well. I just click on one of my dual monitors and click ok and all is well.

**Comment by olear** [comment]
But why does the fullscreen check/apply happens before the mainwindow? This should be applied after the mainwindow is added.

**Comment by MrKepzie** [comment]
I just made this quick fix:

if (!activeWin) {
       qApp->setActiveWindow(this);
       activeWin = this;
 }

**Comment by MrKepzie** [comment]
This is because the focus is not set yet
