### ISSUE TITLE
Cascading choice menus

### ISSUE THREAD

**Issue by devernay** [MrKepzie/Natron#631]
Support for cascading choice menus was added in the OFX libraries, see
https://github.com/devernay/openfx/commit/3c8d24d82f02e23070ec89ed21725c86e71087ae

Choice menus sometimes have many entries (e.g. font menu, or the ACEX 1.0 colorspace menu with 200 entries). Cascading choice menus is a better way to present these choices.

**Comment by olear** [comment]
Nice, so fonts can be in categories, like A, B, C etc? Is it usable for testing on plugins?

**Comment by devernay** [comment]
Not implemented yet in Natron, but you can already implement it in plugins.
see https://github.com/devernay/openfx/commit/48adad9edc15da7d1f78d6a9cee48fa427ee2337

you have 
- a property on the hosts which says wther cascading menus are avalaible
- ChoiceParamDescripto::setCascading(true)

then all you have to do is use slashes to separate hierarchy levels in the menu.

This is already implemented for colorspace choice: https://github.com/MrKepzie/openfx-io/commit/d6c71c01ecd7c8a22f04625980351a3e6eb9d40a

**Comment by olear** [comment]
Ok, thanks for the info, will test.

**Comment by devernay** [comment]
Should be enabled in Natron, please test https://github.com/MrKepzie/Natron/commit/76057e6a22e6d5f442bf3ca08aa62975e4d17d8e

**Comment by olear** [comment]
Will do some testing, but I'm overloaded with regular work at the moment.
