### ISSUE TITLE
Update viewer when aborting with all tiles that were already computed

### ISSUE THREAD

**Issue by olear** [MrKepzie/Natron#632]
Hi, before v1 it was possible to change plugin params during playback, this was a nice feature. Are there any possibility to get this feature back?

**Comment by blackearth2014** [comment]
Do you have auto turbo mode on in the preference? You can also right click in the node graph select Toggle Auto Turbo from the context menu. I hope that is what you are talking about.

**Comment by olear** [comment]
Turbo is disabled. I can change params during playback but they won't apply before I stop the playback.

**Comment by blackearth2014** [comment]
Okay, I see.

**Comment by MrKepzie** [comment]
A plug-in expects that values of its parameters won’t change during a render.
While during playback, all your threads are actively rendering, and chances there is always one in a render , hence the value changes never applies until no more threads are rendering. 
In Natron 1 there was more cases where some threads would be waiting, hence more chance to have a value of a parameter changing, but now activity is a bit higher hence it almost never occurs.
The only clean solution would be to stop all threads and re-start playback, but that can be expensive. I will try to play around with that

**Comment by olear** [comment]
Understand, not an high priority or a must-have, just nice to have in some situations.

**Comment by MrKepzie** [comment]
Ole, can you recompile Natron and test with changing this line in OutputSchedulerThread.cpp line 2527:    

    _imp->scheduler->abortRendering(false) 

You change it to *true* to see if it has any effect. On my hand it almost does the same, but I guess on computers with a smaller amount of cores it should yield different results

**Comment by olear** [comment]
Will do, got three machines to test on, one with 2 cores, one with 4 cores and one with 6 cores.

**Comment by MrKepzie** [comment]
@olear Got to test ?

**Comment by olear** [comment]
Just got home, will do some tests.

**Comment by devernay** [comment]
tested?

**Comment by MrKepzie** [comment]
We
