### ISSUE TITLE
background default of Natron, my opinion...

### ISSUE THREAD

**Issue by manuelsongokuh** [MrKepzie/Natron#634]
ello

for default of natron in background needs to be "checker" because actual natron 1.2 backgrounf is BLACK that is not RIGHT because when does to start (new project natron) in viewer is empty and not BLACK (seem there are something present in viewer...right?

also other because:
my image png there is alpha and i see viewer is black..but there is button (checker) to active but is not full area of viewer...

so i will show you what is BEST for fix it in Natron:
https://cloud.githubusercontent.com/assets/12126929/7775437/788965b2-00b3-11e5-9bf0-a886a1155d69.png

this is actual natron 1.2
https://cloud.githubusercontent.com/assets/12126929/7775449/897a4724-00b3-11e5-9077-08c16672fe4c.png

it's need to fix it or not?

**Comment by MrKepzie** [comment]
The checkerboard is only applied to the visible region of the project when the stream is premultiplied.
