### ISSUE TITLE
how i can stop plasma frames?

### ISSUE THREAD

**Issue by manuelsongokuh** [MrKepzie/Natron#635]
hello

i want to stop plasma 10 frames, because plasma changed image after frame or before frame...
see my screenshot:
https://vid.me/Mn0d

thank you

**Comment by MrKepzie** [comment]
This is a random generator, read the help on the "?" button, it does not yield replicable results

**Comment by manuelsongokuh** [comment]
ok i did read help "?", there is other solution?
impossible or possible?

**Comment by olear** [comment]
Like MrKepzie said, it's random, you will never get the same result.

I can add a non-random plasma in openfx-arena if needed.

**Comment by manuelsongokuh** [comment]
hello olear,
i need because i will want to battle against AE adobe, i need first to test and will do tutorial official for natron against:
plasma is a test but it's test, then i need true is fractal noise (not-random generator) ok?
i will send you more information about fractal noise particular parameter.. ok?
manuel

**Comment by MrKepzie** [comment]
You can generate fractal noise using the SeExpr node.

**Comment by manuelsongokuh** [comment]
that SeExpr is expert for new user intro natron, i'm design video..
Ae have not like "expert for math or expression" ok?
see here video from AE:
https://vid.me/F1dH

**Comment by olear** [comment]
Seed will be added to the c++ api in the next ImageMagick release, will then make a Plasma/Texture plugin in openfx-arena.

**Comment by olear** [comment]
I added a Plasma/Texture plugin in openfx-arena with seed. Simple but should do what manuelsongoku wants(?).

**Comment by manuelsongokuh** [comment]
hello

what i want? ok, i want to create new texture from natron (or your plug ins openfx-arena) like as fractal noise (AE or EXPR) but expr is fatigue for PUT IN an expression, this mean is not good for work with natron, or example i dont create expression this mean i save expression in file txt and when i need fractal noise SO i go to open file and copy and paste in natron with expr and start to create texture? this mean is GOOD? for me is not good, best way: add new filter family texture and rich textures and direct it. for Plasma, i was to try but there is generator-random under frames, this i feel like missed or damn...
so i write where isuess for plasma, and result MrKepzie said it's generator-random, then this plasma mission is out..so i will return to olear for openfx-arena can create and respect his time free, but i want not to force, i can wait, can wait long, not problem, but i want NATRON will BE FULL COMPETITION to AE and nuke with clear and clean code and free. i believe natron will world powerfully, serving time, openfx-arena is very rapid time, i believe openfx-arena will intro natron default for future (i belive it) 

then i want to test to openfx-arena 0.6.1 or 0.7 (but where is download for test it from me?)
thnak you
