### ISSUE TITLE
Roto1 not work color fill...?

### ISSUE THREAD

**Issue by manuelsongokuh** [MrKepzie/Natron#636]
hello
i did add roto and add shape rect and rect , they are not fill full color...its bug ?
see screenshot:
![screenshot2](https://cloud.githubusercontent.com/assets/12126929/7801376/f5240fec-0323-11e5-8e77-8a6e3a6f728b.png)

version natron:
commit (1fc89c343a9fd152628ac914f7f0420a3f18340d)

**Comment by MrKepzie** [comment]
Only the alpha components are selected in the settings panel. For questions please try to ask them on the forum

**Comment by manuelsongokuh** [comment]
sorry, sorry, I’m ignorant 
i dont find documentation or guide for natron...
sorry

**Comment by MrKepzie** [comment]
No problem, there is no official documentation yet. 
The best way is to ask on the forums for now, you will have answers from users, here you will only reach developers.

**Comment by blackearth2014** [comment]
manuelsongokuh you can also join NatronNation at https://www.facebook.com/groups/NatronNation/ if you have other questions in the future.
