### ISSUE TITLE
natron 2.0 (beta) not show list of font for TEXT

### ISSUE THREAD

**Issue by manuelsongokuh** [MrKepzie/Natron#637]
hello

i cant choose any fonts, because missed sub-menu for list fonts..
from node text, see screenshot:
![schermata del 2015-05-26 18 02 23](https://cloud.githubusercontent.com/assets/12126929/7816979/effb201a-03d1-11e5-8536-1e5e3809a6b9.png)

i did check ISSUES (duplicate but not found..)
pc is linux

**Comment by MrKepzie** [comment]
please see https://github.com/MrKepzie/Natron/issues/220 before... Also from 2.0 on the openfx-arena text plug-in will be the main text plugin

**Comment by manuelsongokuh** [comment]
ok i did search in github not fount "fonts" it's strange, then i did try and worked but it's bug:
![schermata del 2015-05-26 18 24 40](https://cloud.githubusercontent.com/assets/12126929/7817341/a3591642-03d4-11e5-9e8c-0f7787dafb35.png)
i belive it's problem space of letter before "Droid Sans" and i tried "DroidSans" it's worked but move from position is not correct with mouse , maybe is bug, but will replace from openfx-arena toTextOIIO official??

thank you

**Comment by MrKepzie** [comment]
Yes the return does not work in Text, see https://github.com/MrKepzie/Natron/issues/435.
It works in openfx-arena plug-in, which will be included in 2.0
