### ISSUE TITLE
Reading from NTFS not formatted using default cluster size fails

### ISSUE THREAD

**Issue by bgks** [MrKepzie/Natron#639]
Refers to 1.2.1 Windows 64 bit (I didn't figure out how to run the V2-snapshot):

Attempts to create a ReadFFmpeg- or ReadOIIO-Reader for files on a certain NTFS-Volume throw an error «Cannot load frame». VLC or MediaPlayer play those files without problems.

A copy of the same files on a different volume can be read and viewed by Natron without problem.

The only difference I can see is: the volume that induces the error has a cluster size of 64 KiB. Actually, it is a VHDX. However another VHDX of the same size works well: formatted using the default cluster size, that is 4 KiB.

**Comment by MrKepzie** [comment]
You can try out your files on the V2 snapshot by downloading it here: https://sourceforge.net/projects/natron/files/snapshots/Windows64/

**Comment by MrKepzie** [comment]
@bgks I have updated the version of ffmpeg on the v2 snapshots. I can only assume the problem stems from there. Please try it out and give us feedback

**Comment by devernay** [comment]
@bgks is this fixed in the latest snapshot?

**Comment by devernay** [comment]
no feedback, closing the bug
