### ISSUE TITLE
Feature request - Project Graphical Timeline

### ISSUE THREAD

**Issue by NomMon** [MrKepzie/Natron#640]
To make usability better, I think that it would truly benefit Natron to have their own unique graphical timeline. Unique in a sense that it surpasses other commercial visual effects software. 

For every project there could be a separate window for a graphical timeline. (Unless, of course you have a different way of organizing your user interface.) Sound and Video files could be featured in layers. With snapping features and others that attract users. For example the ability to resize a file.

With this feature, people may be able to have better control over the time when a file is played. As Natron's uses grow and people begin to use it for bigger projects a feature like this would come in handy.

The merge tool has its advantages, but where time is concerned, I think a graphical timeline would really help and speed up project.

**Comment by MrKepzie** [comment]
Yes, this is a major feature that we may think of later on with the core team. I'm going to close it now, but don't worry we have plans to also make Natron usable for motion design as well!

**Comment by mamarilmanson** [comment]
:+1:  Even though this is a closed issue... :D
