### ISSUE TITLE
User interface glitches

### ISSUE THREAD

**Issue by devernay** [MrKepzie/Natron#641]
Please comment here if you find small user interface glitches in Natron (such as the way things are drawn in the UI, and the way keyboard/mouse/tablet is handled).

First example: the viewer/histogram/node graph/curve editor/properties tab misses a frame around its content (or at least a horizontal line under the tab itself).
![capture d ecran 2015-05-30 a 16 19 34](https://cloud.githubusercontent.com/assets/3778071/7897742/b82d9a64-06e7-11e5-821c-234665d7a8df.png)

**Comment by devernay** [comment]
Example two: tewt is not aligned vertically between parameter labels and parameter values (maybe it's just a matter of padding on the label?)

**Comment by ericshawlinux** [comment]
Is this thread still open for more user interface glitches? This one involves the bounding box selection in the node view.

What happens: The blue bounding box remains after releasing the mouse button.
![Demonstration](https://cloud.githubusercontent.com/assets/8813974/8809301/da255034-2fb5-11e5-8f9a-ce48e7a99e0c.png)

What ought to happen: The blue box should vanish and the nodes should change color to indicate the selection.

**Comment by MrKepzie** [comment]
This bug is different, this is a refreshing bug that arises at some point (I could not determine under which circumstances the refreshing is no longer correct). Generally after 5 to 15 minutes of usage, things start to not refresh any longer in the node graph, on all platforms.

**Comment by rebuilder** [comment]
Press tab to open node search box. Click outside the box or press esc to close it (I'd expect this to work) without selecting a new node to create. The list of nodes is not closed but remains. It can only be closed by clicking on a new node. The box closes, but the new node is not created. By repeating without closing the box, you can get multiple node selection boxes in view.

![selection_009](https://cloud.githubusercontent.com/assets/404648/20300172/8af69e76-ab26-11e6-998d-251647c7d813.png)

**Comment by MrKepzie** [comment]
it's been fixed in recent snapshots
