### ISSUE TITLE
HSV(L) values in viewer display: Font Size

### ISSUE THREAD

**Issue by blackearth2014** [MrKepzie/Natron#642]
HSV(L) values in viewer display fonts are too small as of Natron-snapshots-c25a5a44e1081b4e2f58f356d533e9563c7ed20d. Can you put it back to its original font size?

![pointervalues_toosmall](https://cloud.githubusercontent.com/assets/7956901/7905145/06284486-07e1-11e5-9ee6-ede749ceb702.png)

**Comment by MrKepzie** [comment]
No code has been changed in this regard, double check that the font size in the preferences is what you expect it to be
