### ISSUE TITLE
Natron-snapshots-f0814a99192f953a7130764178c00fcc04baa062: Missing Filter Nodes

### ISSUE THREAD

**Issue by blackearth2014** [MrKepzie/Natron#644]
Natron-snapshots-f0814a99192f953a7130764178c00fcc04baa062 version are missing some filter nodes.  I think I must have lost visibility of some of the other nodes after the crash from the GMICExpr node. See attached image for reference filter category.

![missing filter nodes](https://cloud.githubusercontent.com/assets/7956901/7951511/3b2750dc-0976-11e5-8f9a-3f4c3b111478.png)

The image below is an image that shows the complete list of filter nodes before the latest snapshot
"Natron-snapshots-6697fadb8399c6926a02b7580efa4a03ccb22b74"

![previous filter nodes category](https://cloud.githubusercontent.com/assets/7956901/7951560/e25a1790-0976-11e5-902e-d27f7c10fd73.png)

**Comment by blackearth2014** [comment]
Sorry going to close. The completed list showed up after 6 launches. It must have been my system.

**Comment by blackearth2014** [comment]
Sorry again. There is an issue with the GMICExpr node. Whenever GMICExpr crashes Natron with that node active, the filter category don't list all the filters in the group.

**Comment by MrKepzie** [comment]
I think this is resolved isn't it ?

**Comment by blackearth2014** [comment]
The GMICExpr Node works but if there is a crash, some of the filter nodes are not displayed in the titer category. I have to open a previous snapshot, check if the missing filters are and then reopen the current snapshot and the filters reappears sometimes.

I wanted to disable it in preferences but the image below is the result of opening the panel.  The names of the filters doesn't show.

![filter_preferences](https://cloud.githubusercontent.com/assets/7956901/8019385/46370652-0c19-11e5-88da-3e3d59ef0a8a.png)

So I finally decided to throw away the last snapshot from the my applications and install a brand new one. This time the image above shows the correct number of filters but still no name of the filters. Reference is below.

![filter- correct numbers but no names](https://cloud.githubusercontent.com/assets/7956901/8019399/08467bba-0c1a-11e5-9549-748cfc5c9eac.png)

**Comment by devernay** [comment]
Does the menu item "Cache->Clear Plug-Ins Load Cache" followed by a Natron restart fix this?

**Comment by blackearth2014** [comment]
I just did it and it works.
