### ISSUE TITLE
RotoPaint tool buttons

### ISSUE THREAD

**Issue by devernay** [MrKepzie/Natron#645]
rotopaint tool buttons behave strangely:

- a long press on a button should pop the menu (>0.3-0.5s)
- popping the menu should not select the button. Selecting a menu item or short-clicking the button should select it
- two buttons should not appear selected at the same time (click on one, right-click on the other)
![capture d ecran 2015-06-03 a 14 54 26](https://cloud.githubusercontent.com/assets/3778071/7960431/ce3381f4-0a00-11e5-84d5-5dfb9a1c10dd.png)

![capture d ecran 2015-06-03 a 14 54 35](https://cloud.githubusercontent.com/assets/3778071/7960417/b7bbd66a-0a00-11e5-8d20-2f9bdcf9e867.png)

**Comment by devernay** [comment]
only the first of the three issues was fixed, reopening

**Comment by MrKepzie** [comment]
This is fixed, you just did not recompile the rcc file containing the stylesheet
