### ISSUE TITLE
need add "search" in node graph for list of effects

### ISSUE THREAD

**Issue by manuelsongokuh** [MrKepzie/Natron#649]
hello

i wish add new search in node graph for find effect,

example when i want find "blur" SO
click menu right and click filter and click blur, this is nature of natron.

instead i wish like as effect after search effect, there is "filter" of search for save list space,
SO i write "blur" and find effect and clik to add in node graph..
this is very usefully and fast to find..

filter for search like as google research (example: when i write "bl" and result filter: "blue, blur, blank, black". 

search area in node graph..do you think this good idea?

**Comment by olear** [comment]
Push the Tab button while in the nodegraph

**Comment by manuelsongokuh** [comment]
yes, good idea for new tab name "list effect" or "search effect"?

**Comment by MrKepzie** [comment]
There is already this feature when you press Tab.

**Comment by manuelsongokuh** [comment]
Thank you 

(but i think missed: draw keyboard for all key shortcut: like as :
http://www.blenderguru.com/articles/blender-2-5-cheat-sheet/
http://www.blender.hu/tutor/kdoc/Blender_Cheat_Sheet.pdf


COOL:   http://waldobronchart.github.io/ShortcutMapper/
http://www.giudansky.com/images/downloads/blender/blender3d-shortcuts-infographic.png
