### ISSUE TITLE
Natron-snapshots-0dc23c8f07d8bb930b8f63abb9c2d977291824b8: kNatronOfxImageEffectPropChannelSelector BUG

### ISSUE THREAD

**Issue by blackearth2014** [MrKepzie/Natron#653]
This Natron-snapshots-0dc23c8f07d8bb930b8f63abb9c2d977291824b8 version is not processing the input/output channels correctly and input channel selectors are not working or missing from nodes. The image below is from Natron-snapshots-0dc23c8f07d8bb930b8f63abb9c2d977291824b8. As you can from the channel output selectors, RGB has been deselected and the Roto shape still showing its shape color. The Premult node is missing its channel output selectors.

![bad_output](https://cloud.githubusercontent.com/assets/7956901/8051755/671f54fa-0e4e-11e5-894a-acc17b71eefa.png)

The following image is from the same file using Natron-snapshots-22de19958cdc7ff9422642dda4755618d3d0dbcb from previous snapshot release. It shows the correct output and the nodes channel input/output selectors.

![correct_output](https://cloud.githubusercontent.com/assets/7956901/8051829/19475d62-0e4f-11e5-93f5-f06ba51e8ffe.png)

Has there been a change to the Roto node generating Roto shapes?

**Comment by MrKepzie** [comment]
This is a known issue, we are working on making it more consistent across plug-ins, and currently its broken. We will fix it really soon
