### ISSUE TITLE
Dropdown for kOfxImageClipPropIsMask clips

### ISSUE THREAD

**Issue by nitsch** [MrKepzie/Natron#654]
Enabling [kOfxImageClipPropIsMask](http://openfx.sourceforge.net/Documentation/1.3/ofxProgrammingReference.html#kOfxImageClipPropIsMask) for a plugin's input clip automatically adds a checkbox and a dropdown list to the plugin parameters. It allows the user to select which of the connected clip's channels (or any at all) to use as mask.

While this might make a little sense for plugins that accept only Alpha for this clip, I fail to see what the dropdown list is good for in the other cases since it does not seem to do anything. If the plugin accepts RGB(A) and is fed such a clip by the host, the dropdown selection does not alter the clip in any way.

Maybe the dropdown (and possibly the associated checkbox) should only be displayed if the plugin accepts Alpha exclusively for the mask clip.

Tested in the x64 Windows release of Natron 1.2.1.

**Comment by MrKepzie** [comment]
A mask clip can only have Alpha components on it:

http://openfx.sourceforge.net/Documentation/1.3/ofxProgrammingReference.html#kOfxImageClipPropIsMask <http://openfx.sourceforge.net/Documentation/1.3/ofxProgrammingReference.html#kOfxImageClipPropIsMask>

"Set this property on any clip which will only ever have single channel alpha images fetched from it”

**Comment by nitsch** [comment]
> A mask clip can only have Alpha components on it:
> [...]
> "Set this property on any clip which will only ever have single
> channel alpha images fetched from it”

I read that, too. But I did not understand it as "it can only be Alpha".
Weird way of putting it, but maybe you are right.

Still, wouldn't you agree that showing the additional UI elements in
Natron makes sense only for an (exclusively) Alpha clip?

**Comment by MrKepzie** [comment]
I agree, but a mask with something else than alpha is no longer a mask, curious why do you need to set this property for something that is not really a mask?

**Comment by nitsch** [comment]
> I agree, but a mask with something else than alpha is no longer a
> mask, curious why do you need to set this property for something that
> is not really a mask?

The usual: as workaround for problems with a certain host. ;)

Besides, I am still fiddling around a lot for better understanding. And
some stuff in the OpenFX specs is not really clear from the description.
So I try some of the things to see how the hosts behave.
