### ISSUE TITLE
keep group in "operation"

### ISSUE THREAD

**Issue by manuelsongokuh** [MrKepzie/Natron#655]
hello

i think better make: group of operation (actual)
![group](https://cloud.githubusercontent.com/assets/12126929/8062555/a0390164-0ed0-11e5-9904-8004349ff5df.png)

add a line for "group"
example :
________
max
min
________
color
hue
saturation
color-burn
color-dodge
________
mask
matte
________
in
out
________
overlay
soft light
hard light
pin ligh
________

because i'm confusing when i CLICK my mouse and my eyes move a lot...
i think better is group for operation of node merge and node roto 
![group1](https://cloud.githubusercontent.com/assets/12126929/8062778/d66334d4-0ed1-11e5-8f3a-91fed9fc28fe.png)

what is think about this "group"?

**Comment by devernay** [comment]
There could be three categories, see http://cairographics.org/operators/ :
- Porter-Duff Operators ("operator" submenu)
- Blend modes ("blend" submenu)
- HSL operators ("HSL" sublenu)

**Comment by manuelsongokuh** [comment]
congratulation! for fixed "group" in list!
but also that roto will "group" in list operation..?

**Comment by manuelsongokuh** [comment]
@devernay 
![image](http://www.svgopen.org/2005/papers/abstractsvgopen/porterduff.png)

**Comment by devernay** [comment]
I implemented it, and then removed it: it was not efficient for the user (more clicks)
I implemented anotger solution: you now have shortcuts for merges with the operator already selected.
Closing it.

**Comment by manuelsongokuh** [comment]
hello,
for now natron latest snapshot is removed: clear,src,src-over,dst-over,scr-in, dst-in, etc? why? maybe all operators are need...but i'm hard to try any more..."cut" from roto to image..
maybe needed documentation for preview with operators..

**Comment by MrKepzie** [comment]
We have synchronised th operators to those available in the Merge node, because internally they are the same functions used.

**Comment by manuelsongokuh** [comment]
ok through to Merge node, are you sure there are all operators complete? like as clear,etc?

other suggest: it would be better if group (like as 'line separator' for group )?

example:
---operator blend---
multiply
screen
overlay
---operator hsl---
saturation
luminosity
etc
etc
---operator clipping & mask----
clear
over
in
out
etc
etc
etc

this is example but not need "submenu" because @devernay said: "I implemented it, and then removed it: it was not efficient for the user (more clicks)"

other easy fix:
/--operator blend--\
|        multiply         |
|        screen          |
\-------overlay-------/
/--operator hsl---\
|     saturation     |
|      luminosity    |
|           etc          |
|           etc          |
\--------etc---------/
/-operator clipping mask-\
|           clear                    |
|            over                    |
|              in                      |
|             out                    |
|             etc                    |
|             etc                    |
\-----------etc ---------------/

this is ugly...  try other style.. 

thank you

**Comment by manuelsongokuh** [comment]
see other example for preview on documentation for natron:
![link](http://fog.googlecode.com/svn/wiki/images/compositing.png)
