### ISSUE TITLE
Transform bug in last snapshot

### ISSUE THREAD

**Issue by rcspam** [MrKepzie/Natron#656]
Hi,
The transform (when rotate is use, i dont know for the other transform tool) produce some bad things in the viewer and the render (writer). Here a screencast:
https://dl.dropboxusercontent.com/u/2677320/screenshot-2015-06-09_20.15.21.mp4

**Comment by MrKepzie** [comment]
Yes this is known we are moving a lot of code currently and have broken stuff with the "R" "G" "B" "A" parameters, this will be fixed shortly
