### ISSUE TITLE
can add interpolation: BOUNCE,ELASTIC,ETC?

### ISSUE THREAD

**Issue by manuelsongokuh** [MrKepzie/Natron#658]
hello,
i wish to ask you, natron will new feature for interpolation:
bounce, elastic, other mode,
see example from blender interpolation mode:
https://www.youtube.com/watch?v=pj-ADXCZ5Qo

also particular:
"easing" from blender...this is very usefully...
if natron will not have this magic, then maybe for future or never..

if natron will add new, it's not BAD, will BE powerfully!!

**Comment by MrKepzie** [comment]
We cannot add these interpolation modes easily without re-writing the interpolation engine, which we are not going to do, sorry.
