### ISSUE TITLE
Roto Paint Usability

### ISSUE THREAD

**Issue by Montaire** [MrKepzie/Natron#660]
I really waited this feature thank you!
My first insights:
1. I use this feature mostly frame by frame with different (clone)paint, its the default mode in Nuke, and it has a drop down list it would be nice to have.
![screenshot](https://cloud.githubusercontent.com/assets/9551575/8086273/e2a644a2-0f94-11e5-918a-8db6b89f38e5.png)
2. Reveal or Clone from different frame in time after ~7-8 strokes become really slow(Every stroke asks a different image from Natron?). And I tend to use a lot of really small strokes with tablet. With Nuke I can make 200+ strokes and painting still real-time, switching to an another not buffered frame,  2sec (to draw all those strokes).
3. Basic Stroke Smoothing (like Nuke or Krita) or higher polling rate. (edgy lines can be obvious for viewer) Unzoomed view more unresponsive.
4. On file loading pain toolbar and overlay not loading.
5. Disabled build up makes clone brush 1.0 hard or disables it(And I cant see any difference if checked even on lower opacity on other brushes)
6. Shift + mouse1 could change the size of the brush

**Comment by MrKepzie** [comment]
1) Ok for the first, this is still todo 
2) I don't experience these slow downs, can you tell me the steps to reproduce
3) I Don't get it
4) Bug
5) This is a bug in build-up for All effects except painting
6) Todo

**Comment by Montaire** [comment]
2. Load a movie file, draw 8 reveal stroke with time difference, change frame. [I uploaded a file](https://drive.google.com/file/d/0B9R0QJH-Ei5dMVZ6SUZjTFN6WTg/view?usp=sharing). On low zoom level it take 7-8 sec to redraw, on 100% zoom about 17 sec. (I am on windows 8.1 with 4core 8 thread i7 2.4 GHz right now.
3. If you drag your mouse really fast the stroke is not continuous, the segments are visible. Nuke and also Krita can make them continuous. if you draw on low zoom level it is more visible.

**Comment by MrKepzie** [comment]
Indeed there's a bug with the cache when using the TimeOffset causing Natron to re-render all the previous strokes in the hierarchy. I will fix it.
In the meantime 5) has been fixed

**Comment by MrKepzie** [comment]
The bug is fixed

**Comment by Montaire** [comment]
Awesome, that was quick!
I will keep testing the new build.
