### ISSUE TITLE
command line mode issues

### ISSUE THREAD

**Issue by timurhai** [MrKepzie/Natron#662]
Hi!

I tried to install linux 2.0.0 snapshot (binaries from sourceforge) on ubuntu 14.04.

As i've got from "./Natron -h", "./NatronRenderer" and "./Natron -b" should be the same, but "./Natron -b" always starts GUI.

"./NatronRenderer [args] python.py (or scene.ntp)"
always ends with:
"ERROR: Natron: Specified file does not exist"
even when file exists

ps
Great Project!
I want to do same as http://cgru.info/software/nuke

**Comment by MrKepzie** [comment]
./Natron -b
    Natron
    Version: 2.0.0
    Copyright (C) 2015 the Natron developers
    >>>Use the --help or -h option to print usage.<<<

    You must specify the filename of a script or Natron project. (.ntp)

Please read the documentation here: http://natron.readthedocs.org/en/workshop/natronexecution.html

**Comment by timurhai** [comment]
I have read.
And 1.2.1 worked with the same script (bash), but 2.0.0 always says:
"ERROR: Natron: Specified file does not exist"
( also -b launches GUI )

**Comment by MrKepzie** [comment]
That's because you are attempting to launch the shell script Natron.sh and not the binary located in /bin directly. We'll make it so it forwards to the binary the command line arguments, @olear could you take a look at this please? In The mean-time you should just use NatronRenderer if you want to render in background

**Comment by timurhai** [comment]
I checked for that scripts.
The difference between 1.2.1 and 2.0.0 is that changes launch line from
     $DIR/bin/Natron -style fusion $*
to
     $DIR/bin/Natron -style fusion "$*"

So 1.2.1. worked, but if i have a scene path with a space and place its in quotes, it should not.
2.0.0 "$*" way is not better, as it place all command line arguments in a quotes, this means that binary executable will see " -b write1 1-2 /folder/scene.ntp" as one argument, and the file " -b write1 1-2 /folder/scene.ntp" - does not exist.

Better way is to use
        $DIR/bin/Natron -style fusion "$**@**"
This way arguments with spaces and quotes will be passed correctly.

 - i made this change and it works!

ps
Afanasy already supports Natron, but only from a stand-alone dialog http://cgru.info/afstarter
The next step is "afanasy" node in Natron to store various settings and create render networks with dependencies (render back and key, then compose, for example).

**Comment by MrKepzie** [comment]
Will make that change, will be available in about half an hour in the maintenance tool;)
I think the Afanasy node can be done using the Python API
