### ISSUE TITLE
Natron disregards project frame range

### ISSUE THREAD

**Issue by synk-a-dynka** [MrKepzie/Natron#665]
Natron renders the amount of frames in the longest image sequence rather than the project frame range.

Setting frame range to 1-19 in a project with a few image sequences where the longest is 250frames the composited render from Natron is 250 frames long instead of 19.

Natron 1.2.1

**Comment by MrKepzie** [comment]
Can you check that your write node does have the appropriate settings and not “Union of the input frame ranges”

**Comment by synk-a-dynka** [comment]
Ah...
Missed that option. now it works properly. 
Sorry for reporting a non-bug. (I think this should be default though!)
