### ISSUE TITLE
Roto Node vs RotoPaint tools in Viewer

### ISSUE THREAD

**Issue by blackearth2014** [MrKepzie/Natron#667]
I don't know if this is how its suppose to work or not, but it is going to get tiresome. Rotopaint node tools work pretty good, but when you add a Roto node to do roto work, it takes over the viewer and won't release its commands to do further rotopainting with Rotopaint node unless you close out the Roto node.

Is there a way to have the ability to activate the toolset of a node once selected by double clicking on it? By doing this, it deactivates the previous node toolsets.

Better yet create an additional layer for such tools to exist at the same time in the viewer if both Roto & RotoPaint nodes are in the settings panel.

Thanks

**Comment by MrKepzie** [comment]
Sure, this is a bug, it is supposed to work as you said in case 1

**Comment by blackearth2014** [comment]
It works when you first click select, but when you go back to the rotopaint node to make a change, the roto node doesn't release it interaction.

**Comment by MrKepzie** [comment]
Can't seem to be able to reproduce, please post a screen cast

**Comment by blackearth2014** [comment]
Okay I will do it later

**Comment by blackearth2014** [comment]
The fix wasn't available until this snapshot: Natron-snapshots-cd9f3fc4f1f958b467198433423a92c80aa0f868.  Thanks.  There is a time difference when your fixes become available. This once was in a different snapshot commit than that in the folk tree.
