### ISSUE TITLE
Ubuntu: error loading sequences

### ISSUE THREAD

**Issue by fPaglia** [MrKepzie/Natron#67]
I'm experiencing many different error here while loading sequences:
1. the terminal says:
Caught exception: The specified transform file '/home/francesco/Downloads/Natron_Linux_x86-64bit_v0.9.5/share/OpenColorIO-Configs/nuke-default/luts/srgb.spi1d' could not be loaded. Invalid 'From' Tag
1. a frame sequence with a padding of 4 zeros is read like there were sparse frames (I'm shure the sequence is correct)
2. most of the time frames are read as black (maybe for the same error reported into the console)

**Comment by devernay** [comment]
fixed again by https://github.com/MrKepzie/Natron/commit/4b3529c7ebbce7271ec9197f3a7bbc9a2420710e
