### ISSUE TITLE
No more channel selector for filter plugins (blur/erode...) ?

### ISSUE THREAD

**Issue by sozap** [MrKepzie/Natron#678]
I just find that in Blur and plugins like dilate , billateral ect... have lost the option to process only R , G, B or A channel (the R,G,B,A checkboxes on the top of the node...)
That's a bit sad because it's very convenient to apply these filters only on the alpha for example...

is it a regression or just a bug ?

the merge node still have it...
Natron version : 345505d0564b64c7f6cce6b80485fb65305e5363

**Comment by MrKepzie** [comment]
Has been resolved in another issue, it must have compiled an old version of the plug-ins

**Comment by sozap** [comment]
I've just run the maintenance tool, Natron is updated but there isn't a new version available for OpenFX misc...

version : 22cef47ae4154483ba0061b8c8f8f7732be8fdad
