### ISSUE TITLE
Card3D like type of node for 2.5D compositing

### ISSUE THREAD

**Issue by blackearth2014** [MrKepzie/Natron#68]
Can we get a Card3D like type node for Nuke. This way we can create a fake perception of depth.  If I am working in HD, my 2.5D background should be 4800*2700 pixels. I can use a roto node to create a matte background painting and have each roto layers being displayed  at a distance from the camera.

Right now everything is flat.

![card3d_node](https://cloud.githubusercontent.com/assets/7956901/3453067/f2f44c4e-01be-11e4-9c2b-7bf2c9d8fda3.png)

**Comment by manuelsongokuh** [comment]
hi this issue will be close because there is new feature CARD3D natron..?

**Comment by devernay** [comment]
There is now a Card3D node in Natron, although there is no 3D space yet (which is another issue)
