### ISSUE TITLE
Rotopaint clone bugs

### ISSUE THREAD

**Issue by rcspam** [MrKepzie/Natron#680]
Hi,
Thanks and bravo for the amazing work on the rotopaint tool.
I don't know if  they are known bugs:

1. Clone an ever cloned zone, clone original image.
2. Clone rotopaint is broken after open a save ntp file.(Display only clone path)
[see screencast](https://dl.dropboxusercontent.com/u/2677320/screenshot-2015-06-16_10.30.48.mp4)

3. A very light pressure pen cause some artifacts.
[see screencast](https://dl.dropboxusercontent.com/u/2677320/screenshot-2015-06-16_10.38.31.mp4)

Another little bug about color popup menu in "info zone viewer":
![selection_003](https://cloud.githubusercontent.com/assets/10021906/8179068/5aebaca8-1414-11e5-8b86-658c95755961.png)

**Comment by rcspam** [comment]
Sorry for my mistake about 1. (background clone ;)

**Comment by MrKepzie** [comment]
3) was fixed in https://github.com/MrKepzie/Natron/commit/a3d70d35fc045a98d9c061a5db7ff592240d720c

**Comment by MrKepzie** [comment]
Every point is fixed, just wait for the next snapshot

**Comment by rcspam** [comment]
The font colors in popup window are not solved ;)

**Comment by MrKepzie** [comment]
I will fix that on Linux next week

**Comment by rcspam** [comment]
Ok, thanx

**Comment by MrKepzie** [comment]
I don't have the blue background gradient on Linux either, can you confirm it still does not work with a recent snapshot ?

**Comment by rcspam** [comment]
Last snapshoy: always the issue.
