### ISSUE TITLE
Natron-snapshots-a6da5fc92128c1906d8b53decb262d8c08d2f0dd: RotoPaint Shortcut & Node Connection Hints

### ISSUE THREAD

**Issue by blackearth2014** [MrKepzie/Natron#684]
Natron-snapshots-a6da5fc92128c1906d8b53decb262d8c08d2f0dd: RotoPaint Shortcut & Node Connection Hints are not responding.

This video link will show the small bug in the use connection hint at https://youtu.be/2v8_hImsH3Y.

**Comment by MrKepzie** [comment]
This has been fixed
