### ISSUE TITLE
Installer's 'Run Natron Now' runs different version of Natron

### ISSUE THREAD

**Issue by crydalch** [MrKepzie/Natron#687]
When I download the nightly installer and run it, at the end of the installation I see the **Run Natron** option toggled on. When I let Natron run that way, it runs a different version of Natron than the one I just installed. I can't tell if it's running Natron from the default install location (seems likely), or what, but it's definitely not running it from the just-installed directory.

Thanks!

**Comment by MrKepzie** [comment]
Please open the issue here https://github.com/olear/natron-linux

**Comment by olear** [comment]
It's a known issue with the qt installer, will try to find the bug.
