### ISSUE TITLE
Natron maintenance tool Linux

### ISSUE THREAD

**Issue by rcspam** [MrKepzie/Natron#689]
Something is wrong since 2 days with the upgrade manager.
Impossible to download update components (problem with Updates.xml)...
![download error_001](https://cloud.githubusercontent.com/assets/10021906/8250843/95f08174-1677-11e5-9886-42275299b191.png)

**Comment by MrKepzie** [comment]
Just download a new version of the bundle instead: http://sourceforge.net/projects/natron/files/snapshots/linux64/repo/Natron_Linux_bundle_snapshot_x86-64bit.tgz/download

**Comment by rcspam** [comment]
It is really broken the last two one do not work

**Comment by rcspam** [comment]
This is always broken ! I must direct-download the brundle each time you update sourceforge... It's not really cool !

**Comment by olear** [comment]
Probably a bad mirror, try another ...
![screenshot-23](https://cloud.githubusercontent.com/assets/7461595/8369752/c77a88e2-1bbe-11e5-80d2-033e3d0b1e7c.png)

**Comment by rcspam** [comment]
Ok thanks.
Mime was http://softlayer.... for some time. "The king is dead .Long live the king" ;)
