### ISSUE TITLE
CURVES: import,export, knowledge...ACV,TEXT

### ISSUE THREAD

**Issue by manuelsongokuh** [MrKepzie/Natron#693]
hello

the curve is very powerfully to use it...
i show you..if natron will needs or not?

the curve is from node "ColorLookup" right?
i did research google, i found more importants informations:
Gimp, photoshop, AE, have curves:
-  *.ACV is proprietary Adobe for photoshop and AE
-  text file is for GIMP (it's open source)

-----------------------------------
there are interesting information:
forum gimp:
http://www.gimpchat.com/viewtopic.php?f=9&t=5541
(there is file download named: "Curves.7z" is text curve for gimp )

there is "converter" from acv to text (GIMP)
http://registry.gimp.org/node/27003
(https://github.com/suapapa/suapapa_snippets/blob/master/acv2gimp.py)

gimp how import and export:
http://docs.gimp.org/en/gimp-tool-curves.html

COOL information from 1996!!
https://www.ledet.com/margulis/Makeready/MA21-Defanging.pdf

COOL other information:
http://www.alternativephotography.com/wp/negatives/curve-corner-photoshop-curves

then... what do i want to say you?
i dont know if the curve is usefully or nothing..
you can see and reflect, if "ColorLookup" can IMPORT/EXPORT file acv and text?

that "Curves.7z" in natron what will happen? will be COOL?
for ACV can converter under python..that natron supported python...CAN WORK IT?

i think this issue is interesting for all you?
i HOPE YES!

**Comment by manuelsongokuh** [comment]
http://ineedchemicalx.deviantart.com/art/Beatles-curves-301382918?q=gallery%3ATodoRecursos%2F37796717&qo=10

http://igotthelook.deviantart.com/art/Photoshop-Curves-02-acv-195300422?q=gallery%3AIGotTheLook%2F26670447&qo=4

http://igotthelook.deviantart.com/art/Photoshop-Curves-01-acv-195217290?q=gallery%3AIGotTheLook%2F26670447&qo=5

http://dianadebord.blogspot.it/2013/11/free-photoshop-curve-vintage-creamy.html

**Comment by MrKepzie** [comment]
It can currently import/export to ASCII file format, the same that is used in Nuke. There is no plan yet to load other file formats

**Comment by manuelsongokuh** [comment]
ok, how i will import/export to ASCII?

**Comment by devernay** [comment]
Does this feature request cconcern only the colorlookup curves, or curves in natron in general?
You can also check out the OCIOFileTransform and OCIOLookTransform plugins

**Comment by manuelsongokuh** [comment]
@devernay 
Of right to ask me, i wanted to say, its for colorlookup, i mean convert from color curve (original) to change color under ASCII (gimp, photoshop curve) Like as import and export..
Maybe i'm not explain well ..?

**Comment by manuelsongokuh** [comment]
@devernay 
i did tried: OCIOlooktransform: it's not stuff.
i did tried: OCIOfiletransform: it's OK but not worked with file of GIMP and ACV...
file of gimp TXT: 
gimpchat.com/download/file.php?id=6911&sid=9dc36bdbd67ff799df5f94be93a7364c
you try downlaod curve.7z and try with natron..
in gimp worked with curve.7z..

**Comment by devernay** [comment]
The problem is that gimp curves are meant for 8-bit sRGB images, and they use GIMP's own language, which is pretty complicated to parse (just unzip the package and examine each on the files).
GIMP curves would have to be converted to a more common curve type, like spi1d, which can be loaded with OCIOFileTransform

The only way I can think of, to do that, is to generate a linear ramp in sRGB, apply the curve in GIMP, save the resulting image, read the image from a homemade software and write the spi1d file (which is an easy and readable format). Note that spi1d curves would also be usable in most software.

This is not a Natron issue, sorry.

**Comment by manuelsongokuh** [comment]
Ok, im happy for clear informactions, spi1d : there are examples so i will can read it..
For linear ramp : im interessing but there is any documentations?
