### ISSUE TITLE
Merge node and the Viewer

### ISSUE THREAD

**Issue by ramellij** [MrKepzie/Natron#695]
Hello, 

First thanks a lot for all the work you have done to make this great open source software. I love it !

I don't know if it's a real issue or just a decision made by you... My problem : in my composition tree, when I diseable one of my merge node by clicking the "D" shortcut, to see what it does without, instead of seeing the result of the end of my tree (by the B pipe) I see just the node I wanted to exclude (the input A of the same merge node). So it makes me see exactly the oposite that I wanted. 
To make it work I have instead to go into my merge node and put the mix value to 0. Not the fastest way.

Thanks
JR

**Comment by MrKepzie** [comment]
On the latest snapshots it should return the B input, we had the issue back in 1.2.1

**Comment by ramellij** [comment]
With the windows snapshot version of 2015-06-18 it doesn't work.

**Comment by MrKepzie** [comment]
Make sure that in your preferences in the Nodegraph the parameter "Merge node connect to A input” is unchecked

**Comment by ramellij** [comment]
Wow! I didn't know that option :/ Problem solved.
Thanks MrKepzie !
