### ISSUE TITLE
need to enhancement for SNAP...(question)

### ISSUE THREAD

**Issue by manuelsongokuh** [MrKepzie/Natron#697]
hello
i think missed: snap to viewer of project..
i try to explain (my english poor)
when i add [rectangle or roto or read] and i need help me: snap from my mouse point (case rectangle or roto ) TO side of viewer (left or right or top or bottom), this snap is very usefully for any to help me as save my time(job) a lot...it's right or not?

It is as valid for roto and rectangle and read node SNAP to side of viewer project..

maybe my question is not good but when i work with natron is very important and NEW for me and fantastic natron!

**Comment by MrKepzie** [comment]
I guess you are after that https://github.com/MrKepzie/Natron/issues/584

**Comment by manuelsongokuh** [comment]
ok thank you

**Comment by manuelsongokuh** [comment]
sorry i'm doubt, that #584 talk about SNAP? or i'm wrong?
