### ISSUE TITLE
Aliasing artefacts in < 1.0 opacity Roto masks

### ISSUE THREAD

**Issue by StepanDav** [MrKepzie/Natron#700]
Natron snapshot build (official, not mine), at 1803fd31dfc4f0b14cb136204bab2604fe8cb574.

http://i.imgur.com/WtGjQFH.png

Steps to reproduce:
1) Create a Solid foreground, color = black.
2) Create a Solid background, color = white.
3) Create a Roto, use Bezier tool to create some arbitrary shape.
4) Use Merge to merge foreground (step #1) over background (step #2) and use the roto (step #3) as mask.
5) Observe correct rendering.
6) Change the Opacity of the Roto layer from 1.0 to 0.4.
7) Zoom in on the edge of the Roto, observe defects.

Additionally, when I close Natron and reopen it, I do not get the black foreground rendered at all at some zoom levels, but I cannot reproduce that reliably enough.

**Comment by MrKepzie** [comment]
I fixed the bug where it sometimes does not render the shape on project load. Though for the edge line, I need some more time to narrow it down (this is due to cairo)

**Comment by devernay** [comment]
This is a known bug in cairo: the interior of the shape is rendered using a Bezier path. The feather is rendered using Coons patches. Both use different rendering algorithms, which don't give exactly the same contours.

One way to fix this is to render everything with Coons patches. This is partially implemented but requires more testing.

Another way is to render everything in Cairo with opacity=1, and then multiply the opacity when converting to floating-point image.

**Comment by MrKepzie** [comment]
Fixed
