### ISSUE TITLE
Natron Snapshot does not start on OSX 

### ISSUE THREAD

**Issue by MarcRose** [MrKepzie/Natron#701]
Natron snapshot ( dernière version et version anterieure ) ne démarre pas sur OSX 10.9.5, intel core i5.
Au démarrage, il bloque sur "restoring the image cache". Utilisation de la memoire à 99%  et Natron ne répond plus. 
Cordialement

Traduction Google:
Natron snapshot (latest version and older version) does not start on OSX 10.9.5, Intel Core i5.
At startup, it blocks about "restoring the image cache". Using the memory to 99% and Natron unresponsive.
Cordially.

**Comment by MrKepzie** [comment]
Please remove all folders in /Users/<user>/Library/Caches/INRIA/Natron

**Comment by MarcRose** [comment]
thank you a lot
