### ISSUE TITLE
multiplane priority when merging nodes

### ISSUE THREAD

**Issue by sozap** [MrKepzie/Natron#703]
Is it possible to add an option to the merge node to select which planes to keep when doing an operation (like with the bounding box option) ?
I'm doing a simple operation like a merge on both RGBA channels of the B and A branch.
For now it seems that the planes are kept from the A branch and I think generally it's better to keep planes from the main branch (B).

A least if it's possible to just keep the B ones instead of the A ones ? It will be already great.
the best would be a option to choose (A , B, or union) witch planes to keep.
In the union case, if the 2 planes share the sames names it can keep the B ones for examples.

In my case, I want to store some ID mask in the B branch in some planes, and when I merge it with something else I loose my masks... But I think there are other cases when it's going to be problematic.

What do you think ?

**Comment by MrKepzie** [comment]
Can you post a screencast of the issue? I don't fully understand the problem

**Comment by sozap** [comment]
Here we go : 
https://www.youtube.com/watch?v=FT3tcxJNT2g&feature=youtu.be

I've also demonstrated another issue : the missing possibility to select a plane as a mask if the mask input is empty...

Having the possibility to color correct (or something else) something using ID mask planes can be very effective in complex nodetree . In my example it's not very obvious because there are only a few nodes. But if the tree was bigger and the correction append at the end, it can become a mess to redirect the ID masks...

I hope that make sense now :)

**Comment by MrKepzie** [comment]
I'm going to fix the bug, the other one is a feature request already opened and requires some work to do, can't promise anything
