### ISSUE TITLE
Custom cursors in OFX

### ISSUE THREAD

**Issue by nitsch** [MrKepzie/Natron#704]
RotoPaint from the `workshop` branch is an example of a plugin using a custom cursor. Is it possible with OFX interacts to change the cursor like this or is this just a feature of the built-in plugins in Natron?

It does not seem as if OFX interacts allow for custom cursors but I may be overlooking something.

**Comment by MrKepzie** [comment]
This is built-in: we explicitly disable the Qt cursor and draw it with OpenGL instead. 
There is no way for the plug-in to let the application know what kind of cursor it wants, maybe this should be an extension to the overlay interacts suite

**Comment by devernay** [comment]
You can draw your own cursor with OpenGL too in your overlay code, but the window system cursor will always be visible. the reason is that no plugin "owns" the cursor, and mouse actions are shared between plugins. We have to figure out how to do this cleanly and propose an OFX extension
