### ISSUE TITLE
No set key in menu and undo import curve in the curve editor

### ISSUE THREAD

**Issue by rcspam** [MrKepzie/Natron#710]
If a key is set in one dimension, there is no possibility to set a key to the other by the menu:
![natron - untitled ntp - _001](https://cloud.githubusercontent.com/assets/10021906/8402967/d8e2e6ae-1e40-11e5-88d6-0444f03d317f.png)

After import a curve in  the curve editor and undo it, the previous curve is remove.

Just a little enhancement?! Is it possible, as in Nuke, to preset the 'import/export curve menu' with the previous/last sets (file, start, increment...) to simplify the import when several test. Thanks

**Comment by rcspam** [comment]
Another issue: Natron add an offset on 6 images when import curve

**Comment by MrKepzie** [comment]
https://github.com/MrKepzie/Natron/commit/b247e8063279f15cbe70701cadd9048b27411123

**Comment by rcspam** [comment]
Thank you FlashDev ;)
