### ISSUE TITLE
The GodRays node doesn't work

### ISSUE THREAD

**Issue by mypixhell** [MrKepzie/Natron#711]
Erro message 
![crash](https://cloud.githubusercontent.com/assets/7987608/8406634/8922f6fe-1e5e-11e5-8621-44f45ef330ec.jpg)

**Comment by MrKepzie** [comment]
Fixed via https://github.com/devernay/openfx-misc/commit/bf3a936e87979afee37ab36c2d613bfe31c5f491

**Comment by rcspam** [comment]
When play with some Transform operations in the node crash Natron (Linux last snapshot)

**Comment by MrKepzie** [comment]
I just fixed it

**Comment by mypixhell** [comment]
Impec ;-) J'ai commencé un node pour faire des flares, le voici en pièce
jointe

2015-07-01 12:02 GMT+02:00 Alexandre Gauthier <notifications@github.com>:

> I just fixed it
