### ISSUE TITLE
Linux: Missing Plasma plugin

### ISSUE THREAD

**Issue by olear** [MrKepzie/Natron#712]
Hi, noticed that the Plasma plugin from openfx-misc is not included with the binaries any longer, could be more(?). I built Natron+plugins from my natron-linux and Plasma shows up, must be something done in the fork?

**Comment by MrKepzie** [comment]
I don’t see why it is not in there, the Makefile is the same for any build. I will check tomorrow what’s up

**Comment by olear** [comment]
It's the same for me, on natron-linux the openfx-opencv plugins don't show up, but they do on your fork. 

Will also try to find out why ...

**Comment by olear** [comment]
Plasma is in latest binary, must have been "fixed" since yesterday (I didn't update today).

**Comment by olear** [comment]
Found the issue, if Natron crashes then the plugin "list" state is corrupted or something, and some plugins don't show up, cleaning the config after a crash works.
