### ISSUE TITLE
after installation, missing the icon of natron (beta)

### ISSUE THREAD

**Issue by manuelsongokuh** [MrKepzie/Natron#714]
hello
i download last snapshot, after installation, worked as perfect, and I want add ICON on my panel of kde4, but i dont find icon of natron...

i suggest:
for linux:  KDE4/KDE5 need add file Natron.desktop (that is information for launch of application, icon, command, etc)
GNOME 3.X i dont know..

**Comment by MrKepzie** [comment]
We do already provide a .desktop file, it is located in ~/.local/share/applications/Natron.desktop
Icon is located under ~/.local/share/icons/
The location of these files is probably not correct for your distribution, however according to http://doc.qt.io/qtinstallerframework/operations.html, Qt uses the standard variables  $XDG_DATA_DIRS/application and $XDG_DATA_HOME/application to place the .desktop/icon files

**Comment by olear** [comment]
Bug in KDE, don't read .desktop from home folder properly.

**Comment by olear** [comment]
Workaround for KDE is to copy the desktop file from the home folder to the system folder (/usr/local/share/applications), the same for the icon (/usr/share/pixmaps).

**Comment by manuelsongokuh** [comment]
hello
i will check tomorrow my job and will back here for result of problem ok?

**Comment by olear** [comment]
You can also install Natron as root (for example to /opt/natron), then the icons/shortcuts will be available in KDE.

https://github.com/olear/natron-linux/issues/1

**Comment by manuelsongokuh** [comment]
hello i'm back here
my job has arrived pc workstation dual xeon for my job: natron, kdenlive, inkscape, gimp, blender, dvdstyler!
then
first time installation natron and not work icon but after reboot it's return icon.. then this issue is clos as fine, for future annotate for new user ok? thank you
