### ISSUE TITLE
Dual Monitor: how i set in "defaul"?

### ISSUE THREAD

**Issue by manuelsongokuh** [MrKepzie/Natron#715]
hello

i have Dual monitors, i want to keep:
first monitor: main netron (node graph, proprietaries, curves,)
second monitor: viewer1 or viewer2
set it as default, also when i new project..?

**Comment by MrKepzie** [comment]
in the layout menu you can export your current layout to a .nl file. Then in the Preferences you can point to a "Default layout file" (.nl) which will be loaded for any new project.

**Comment by manuelsongokuh** [comment]
PERFECT!
IT'S WORKED! THANK YOU!
note:
did it added in documentation? because it will be good the information for new user "fresh"..right?
