### ISSUE TITLE
TuttleText crashes Natron

### ISSUE THREAD

**Issue by hpetrus** [MrKepzie/Natron#716]
TuttleText node crashes Natron when connecting to a Viewer node.

This time, the system that this was discovered on was a current Mac Pro with OSX 10.10.4

Steps to reproduce:

1)  Create a TuttleText node
2)  Connect it to a Viewer node
3)  Crash

Error message:

Fontconfig error: Cannot load default config file
Fontconfig error: Cannot load default config file
Fontconfig error: Cannot load default config file
Segmentation fault: 11

This is a shame because TuttleText has more control over the standard Text node.

Thanks for looking into this.

**Comment by olear** [comment]
https://github.com/tuttleofx/TuttleOFX/issues/419
https://github.com/tuttleofx/TuttleOFX/pull/422

Not an Natron issue as far as I know.

Btw, Natron2 will have a better Text node than TuttleText.

**Comment by hpetrus** [comment]
Thanks for the links to the threads.  Very useful.

Also, can't wait to test out the new Text node in the snapshots. 
Currently, the snapshots don't feature a feature-rich Text node.
