### ISSUE TITLE
Include opencv2fx plugins in OSX builds

### ISSUE THREAD

**Issue by hpetrus** [MrKepzie/Natron#718]
Linux builds feature a whole slew of plugins that are freely available (under various permissive licenses), but OSX builds do not have all of them.  Inpaint, for example, would be great to have included without having to build them.

Is this a license issue?  If not, then, please, consider including them in Natron OSX bin builds.

**Comment by olear** [comment]
The Linux installer has TuttleOFX and openfx-opencv2fx as an option, this was added in 2014 when the selection of plugins in Natron was small, so we added several third-party plugins to ease the usage of Natron. The reason for including Tuttle was that the official build from Tuttle didn't (and still don't) work on all the distros supported by Natron, so we had to build our own version. On Windows and Mac you can just download binaries for Tuttle etc.

Maybe @devernay can provide binaries of opencv2fx for Mac on the project github page or at http://devernay.free.fr/hacks/openfx/ if not included with the Natron builds.

**Comment by hpetrus** [comment]
Thanks for the brief history.  I'll check with @devernay to see if 
providing Mac binaries is in the realm of possibilities.

**Comment by MrKepzie** [comment]
@hpetrus  We have completely reworked the openfx-opencv repository and in its newer version it will include up to date plug-ins. Currently the plug-ins in opencv2fx are not really good, they need to be cleaned up first. I don't know exactly when it's going to make it though.
