### ISSUE TITLE
Crash when open appendClip Node

### ISSUE THREAD

**Issue by rcspam** [MrKepzie/Natron#719]
To reproduce:  Open Natron with an empty project, add an AppendClip... Crash

**Comment by MrKepzie** [comment]
Iv fixed it I think, please try out the next snapshot

**Comment by rcspam** [comment]
It's always the case with the last snapshot ...
![about natron_001](https://cloud.githubusercontent.com/assets/10021906/8475752/98a4bc62-20ba-11e5-971e-feab46dac730.png)
Sorry

**Comment by MrKepzie** [comment]
I just committed another fix
