### ISSUE TITLE
Is "Export as Group" Broken ?

### ISSUE THREAD

**Issue by rcspam** [MrKepzie/Natron#721]
Is the "export project as group" broken, perhaps i do something wrong but after create a group , impossible to export it as plugin ! 

e.g. : After do this:
![screenshot1](https://cloud.githubusercontent.com/assets/10021906/8482015/07d22d8c-20e7-11e5-8e26-f8ac3b898cae.png)

If i want export as group...
This is what i have:
![export_001](https://cloud.githubusercontent.com/assets/10021906/8481987/de74f398-20e6-11e5-90a0-65c79aa93b00.png)

**Comment by olear** [comment]
Seems to work here (if I understand you right)
![screenshot-1](https://cloud.githubusercontent.com/assets/7461595/8482271/ea2ba3d8-20e8-11e5-9658-f8c71844f650.png)

The "plugin" didn't show up before I restarted Natron.

**Comment by olear** [comment]
Add a output node?
![screenshot-2](https://cloud.githubusercontent.com/assets/7461595/8482432/0178e7ca-20ea-11e5-8b95-a63a85264357.png)

**Comment by rcspam** [comment]
Oops! i was thinking that the output node was yet in the project (output node group), so sorry to have open this issue.
