### ISSUE TITLE
why file manager is disorder list?...(question)

### ISSUE THREAD

**Issue by manuelsongokuh** [MrKepzie/Natron#726]
hello

i wnat to know and understand...
why file manager is disorder list? 
![schermata1](https://cloud.githubusercontent.com/assets/12126929/8496739/cb935c4c-2177-11e5-9c16-63a98fba07fe.png)

maybe good order:
first place all folders, after all files, option: order from: date, type, name, size..?
COOL : filter

QT is best manager file, will be find many information internet, qt is flessble.. this is my opinion ok?
i know QT is BEST of ALL..

**Comment by MrKepzie** [comment]
It is sorted in alphabetical order, we can change it and put folders first
