### ISSUE TITLE
Unit testing Natron

### ISSUE THREAD

**Issue by devernay** [MrKepzie/Natron#731]
we should have a batch of unit tests, possibly run at each build, possibly on travis.
This could be a set of example graphs. Input and output images should preferably be JPEG, and the tests should compare with reference renders.
The set of unit testing projects and images should be put in a separate github.
The tests should be run both in batch rendering mode, where full frames are rendered, and also with tiled rendering, which simulates better what happens when using Natron interactively.

**Comment by MrKepzie** [comment]
https://github.com/MrKepzie/Natron-Tests

**Comment by MrKepzie** [comment]
TIle rendering support is not yet effective
