### ISSUE TITLE
Render report should contain per-node timing breakdown

### ISSUE THREAD

**Issue by StepanDav** [MrKepzie/Natron#732]
A feature request -- for the benefit of both compositors and developers, render should provide a report with timing breakdown for each node, e.g.:
```
Merge1: triggered in 50 frames (out of 90), spent 1500ms total (average 50ms per frame)
Transform1: triggered in 90 frames (out of 90), spent 90000ms total (average 1000ms per frame)
```

**Comment by MrKepzie** [comment]
I added timing breakdown here: https://github.com/MrKepzie/Natron/commit/56b8f59b52dae426bc9930c71c2a8487a983a3dc

Report per node is not there but can be added

**Comment by MrKepzie** [comment]
See render statistics in the Render menu
