### ISSUE TITLE
Natron crashes when saving

### ISSUE THREAD

**Issue by ReverendVodka** [MrKepzie/Natron#733]
I downloaded Natron and was using the tracker to track a scene I have filmed.  I wanted to save my work but it kept crashing on me.  I am using Windows 8.  Please advise.

**Comment by olear** [comment]
Save as in render or save project? Natron v1 or v2? If render what output format?

**Comment by ReverendVodka** [comment]
From the dropdown box under "file" the following commands:  "save"  "save as" and "open" were tried.  I believe it is version 2 as I downloaded it from the Natron website two weeks ago.

**Comment by MrKepzie** [comment]
Please indicate the version of Natron as indicated in the about window

**Comment by ReverendVodka** [comment]
Sorry - v1.2.1

**Comment by olear** [comment]
I have v1.2 on Win7, no crash here when using open/save.

You could try the latest snapshot of v2: http://sourceforge.net/projects/natron/files/snapshots/Windows64/ maybe that will work better.

**Comment by ReverendVodka** [comment]
Thanks!

**Comment by ReverendVodka** [comment]
Tried but it didn't work.  :(

**Comment by ReverendVodka** [comment]
Ok, it only has problems when attempting to access my computer so I though it was the firewall.  It wasn't, though.  I have tried running in compatibility modes for Windows Vista (sp2), 7 and 8.  Nothing.  I have tried running as administrator and that did not work.  Am I missing anything?
