### ISSUE TITLE
Enhancement for 'Manage user param' and 'python plugin exporter'

### ISSUE THREAD

**Issue by rcspam** [MrKepzie/Natron#736]
Hi,
Some Enhancement:
 1.  When work on  group python plugins and we must change or one or several param, is it possible when manage them to add just the last params added in the "createInstance function" only without remove eventual function, import,etc and auto-fill the export window.
 2. Auto-fill the export window when plugins exist.
 3. This is impossible, i suppose, but reload plugins without reboot Natron.

And make plugins in Natron could  become "user-friendlier" ;)
Thanx

**Comment by MrKepzie** [comment]
1) is doable to some extent. 
2) can do
3) could be possible but would require some code changes and we don't have time for that right now

**Comment by MrKepzie** [comment]
We changed a few things to PyPlug:

You can now have a script next to the original script where you put all the "hand-written" code (callbacks etc...). See documentation [here](http://natron.readthedocs.org/en/workshop/groups.html#adding-hand-written-code-callbacks-etc).

Basically if you have a pyplug named **MyPlugin.py** you would have a script named **MyPluginExt.py** containing all callbacks. This script can have a *createInstanceExt(app,group)* function where you set all callbacks etc...

**Comment by rcspam** [comment]
Great News.. Thanks
Regards
