### ISSUE TITLE
Roto shapes not closed on reopening file

### ISSUE THREAD

**Issue by OldSkoolVFX** [MrKepzie/Natron#737]
Hi...
I am using Natron version 2.0.0 commit 50382121c2a54991a9797ed2efdd3c0bde3b2715.
After doing several rotos and saving the file.  On reopening all the roto shapes went from the closed shapes that I saved to open shapes on reopening.  I had to use to close curve tool in the roto tools to fix all the shapes prior to rendering.  This never happened in the stable 1.2.1 release.
- Thanks

**Comment by MrKepzie** [comment]
I fixed a bug regarding this matter last week, can you update and tell me if this is fixed

**Comment by OldSkoolVFX** [comment]
With the following snapshot version:
http://repo.natronvfx.com/Natron-linux-x86-install-snapshot-64.tgz
The issue is fixed.
Thanks.
