### ISSUE TITLE
[Feature Request] Render output frame count

### ISSUE THREAD

**Issue by OldSkoolVFX** [MrKepzie/Natron#739]
Hi ...
Instead of just the percentage completed it would really be nice to have an incrementing rendered frame count and a per frame render time, cumulative average per frame render time, and an incrementing global render time.  A projected estimated time remaining for the job would be real nice too. The global render time and the average render time per frame should be displayed on a render completed dialog box.
Thanks.

**Comment by MrKepzie** [comment]
Will add these infos

**Comment by MrKepzie** [comment]
This is implemented in https://github.com/MrKepzie/Natron/commit/56b8f59b52dae426bc9930c71c2a8487a983a3dc
