### ISSUE TITLE
keyboard shortcuts should be more visible in the GUI

### ISSUE THREAD

**Issue by devernay** [MrKepzie/Natron#741]
Shortcuts should be made more visible in Natron, so that the user can learn these, and when possible they shoud appear in ComboBoxes / Button hints, etc.

see for example https://github.com/MrKepzie/Natron/commit/dda95df0706a917d1a2be49ebb1f29dce9bcefce : the zoom combobox in the viewer should show all possible zoom actions (including zoom in/out/fit)

**Comment by MrKepzie** [comment]
Problem is that if the shortcuts are changed, we have to reset all tooltips and stuff, that means for all current widget we need to make a function that sets all tooltips

**Comment by manuelsongokuh** [comment]
maybe good idea:
![keyboard](https://cloud.githubusercontent.com/assets/12126929/8599152/2a6d8df0-265f-11e5-9495-30858178814b.png)
that is an example of kde4, when i add new key shortcut and it checks if free key or occupied, if occupied then see screenshot example:
![keyboard1](https://cloud.githubusercontent.com/assets/12126929/8599210/72bc607c-265f-11e5-9c09-bf50f7b5ff27.png)

maybe that  "Problem is that if the shortcuts are changed, we have to reset all tooltips and stuff.." it's possible "automatic" from assigned key and update to "tooltips".. can does it?

**Comment by MrKepzie** [comment]
We already have a shortcut editor window…

**Comment by devernay** [comment]
We should just keep a map from actions to a list widgets that have this action and shortcut as labels. This doesn't look very difficult and would be nice for natron apprentices.

**Comment by devernay** [comment]
This issue was moved to NatronGitHub/Natron#101
