### ISSUE TITLE
User Menu command in Doc

### ISSUE THREAD

**Issue by rcspam** [MrKepzie/Natron#746]
Is this line must be change since PyPlug correction ?
````
natron.addMenuCommand("Inria/Sc....

```
to
```
 NatronGui.natron.addMenuCommand("Inria/Sc....
```
at https://natron.readthedocs.org/en/workshop/userCommands.html#project-wide-menu-commands

**Comment by MrKepzie** [comment]
Yep

**Comment by rcspam** [comment]
I forgot: 
is 'NatronEngine.natron.pane1.Viewer1.startForward()' should work to start playback

**Comment by MrKepzie** [comment]
nope panes are defined on the "app" object, see the list of automatically defined variables in the output window of the ScriptEditor when you create a viewer

**Comment by rcspam** [comment]
I want just an acces to an existant viewer

**Comment by MrKepzie** [comment]
app1.pane1.Viewer1

**Comment by rcspam** [comment]
thanx good night

**Comment by rcspam** [comment]
Sorry @MrKepzie , but if i want use "app1" in the PyPlug :
"NameError: name 'app1' is not defined", so i don't understand why because the script "knows" app1 apparently ...
![screenshot2](https://cloud.githubusercontent.com/assets/10021906/8636876/1c936ea0-2878-11e5-9334-364bcd339e48.png)

**Comment by MrKepzie** [comment]
Your script does not know any external variable, it can just use the variables passed in parameters to the callback. 
So if you are using the paramChangedCallback, only use the (thisParam, thisNode, thisGroup, app, userEdited) variables provided. 

The exception is for natron which is an attribute of the NatronEngine module.
