### ISSUE TITLE
Natron-snapshots-183e381435f7f73890f7d93c9a06a4f7ede5d426: New Node Plugins Errors

### ISSUE THREAD

**Issue by blackearth2014** [MrKepzie/Natron#747]
The new text, filter and translation nodes plugins are showing "Unknown Errors Messages" on my Mac. See attached images.

![screen shot 2015-07-11 at 12 17 51 am](https://cloud.githubusercontent.com/assets/7956901/8632319/9bbd17fa-2763-11e5-8922-7f134fd0523d.png)

![screen shot 2015-07-11 at 12 19 40 am](https://cloud.githubusercontent.com/assets/7956901/8632318/9bbc9c6c-2763-11e5-9cd6-1c553f4ab8ee.png)

![screen shot 2015-07-11 at 12 19 07 am](https://cloud.githubusercontent.com/assets/7956901/8632317/9bbc1076-2763-11e5-9796-37b1b7d864fb.png)

![screen shot 2015-07-11 at 12 20 08 am](https://cloud.githubusercontent.com/assets/7956901/8632320/9bbec6fe-2763-11e5-9e38-bebcc4fd6f06.png)

**Comment by olear** [comment]
Looks like a broken build. Can you click about plugin on the new text plugin and post a screenshot of the info.

**Comment by blackearth2014** [comment]
Hey Ole,

Here is your screenshot request.

![ole build info](https://cloud.githubusercontent.com/assets/7956901/8633174/fce2a4ca-2789-11e5-8dcb-3808ec77ca3c.png)

**Comment by olear** [comment]
Unsupported ImageMagick version and wrong depends....

How it should be:
![text](https://cloud.githubusercontent.com/assets/7461595/8633315/317e580e-27c2-11e5-8cb8-aa285330350d.png)

**Comment by MrKepzie** [comment]
Works fine here with 6.9.1-7 Q32 HDRI and same depends , If I recall we had issues building 6.8.9.x

**Comment by blackearth2014** [comment]
When will this problem be fixed?

**Comment by olear** [comment]
Don't know...

@MrKepzie ;
I recommend building without gslib and ps, they may interfere with font selection. The file formats are overkill, but won't interfere with anything (libpng+zlib is required). When it comes to the IM version, I only support 6.8.9-10 + patches in the 3rdparty folder, IM 6.9.1-3+ is not supported from my side.

**Comment by olear** [comment]
If you can't get 6.8.9-10 to build (that would be strange) then I can support 6.9.0-6.9.1-2, but I need to test and supply patches, I would prefer to use the same version on all platforms etc.

I backport stuff from newer IM's when needed, so there shouldn't be a problem staying on that version.

**Comment by MrKepzie** [comment]
It seems to be an exception thrown from ImageMagick itself (std::bad_alloc)

**Comment by olear** [comment]
A bit unsure... If IM is static do you link against all the IM depends in the plugin? but then the plugin wouldn't load at all ...(?) when I think about it.

on Linux/Win I build the plugins using: make STATIC=1 USE_PANGO=1 USE_SVG=1, but I don't build against as many depends as your are, so that may need to be adjusted or could interfere with something(?).

Add 'image.debug(true);' on https://github.com/olear/openfx-arena/blob/master/Text/Text.cpp#L410 to get debug info from IM.

**Comment by MrKepzie** [comment]
It is not statically linked. It has all shared dependencies which are properly loaded. 
The only difference between the release build in the snapshot and my configuration on my mac is that librsvg is not enabled here in my case. I’m testing with it to see the difference

**Comment by olear** [comment]
Also note that 6.9.1-5+ has broken anti-aliasing due to compositing changes, so most of my plugins will not work as expected (jagged text, jagged transforms etc), at least on Linux/Windows/FreeBSD, would be strange if this differs on Mac.

In 6.9.1-3 they changed some colour stuff, that breaks transparency on text, I can fix that bug, but that breaks compat with older versions.

That's the reason I only support one version (with patches, 6.8- got bugs as well)....

**Comment by blackearth2014** [comment]
This problem still exists on my Mac even after 5 or more snapshot releases. Will these new plugins ever be usable on the Mac platform? Ifnot, is it possible to not have it compile until the right dependencies get implemented.

**Comment by olear** [comment]
The plugins are usable according to @MrKepzie , so it's currently a deployment/build issue. I have done some changes that may work better on Mac, but I don't know if those changes has been added to the Mac build (IM also need to be changed if it's still at 6.9.1-7).

I don't have access to Mac so I can't test or build.

**Comment by MrKepzie** [comment]
I’ll downgrade and test with the other version of IM once I finished the migration from source forge to natron.fr <http://natron.fr/>

**Comment by MrKepzie** [comment]
Aight I set up the OS X build server with IM 6.8.9-10 with @olear patches. We'll see if next build is ok;)

**Comment by olear** [comment]
Great :)

**Comment by MrKepzie** [comment]
Forgot to start the build :D just started it

**Comment by MrKepzie** [comment]
The new build is online and working

**Comment by olear** [comment]
Seems to still be issues with the Text plugins

https://plus.google.com/u/0/photos/113342871193163005597/albums/6174346591779382977/6174346598915496306?pid=6174346598915496306&oid=113342871193163005597

Since @blackearth2014  don't get any fonts in the combobox it's probably related to fontconfig?

**Comment by MrKepzie** [comment]
Hmm link is not public. What is the issue ?

**Comment by olear** [comment]
Sorry, didn't know that.

![screenshot-2](https://cloud.githubusercontent.com/assets/7461595/8851914/7ea095ae-3152-11e5-8239-ea55c0bd387c.png)

Fonts don't work in Text(Pango), the combobox is empty.

Also the color management in ReadPSD don't seem to work, at least not as on Linux (no default profiles in combobox), could someone check that there are profiles in the comboboxes.
![screenshot-1](https://cloud.githubusercontent.com/assets/7461595/8851874/4ad1a7e0-3152-11e5-845d-42bde24a3cd7.png)
