### ISSUE TITLE
Natron Won't Save Project File

### ISSUE THREAD

**Issue by AnsonSavage** [MrKepzie/Natron#748]
When attempting to save the .ntp project file through the File > Save As menu option, after opening a writeable directory, Natron will not do anything when the "Save" button is pressed.  Thanks!
![screenshot from 2015-07-11 14 53 52](https://cloud.githubusercontent.com/assets/12112399/8635553/b95ea7dc-27dc-11e5-93d2-3fa362771975.png)

**Comment by olear** [comment]
add your file in the field over the one you use.

**Comment by AnsonSavage** [comment]
@olear What do you mean?

**Comment by olear** [comment]
see screenshot:
![screenshot-1](https://cloud.githubusercontent.com/assets/7461595/8635579/6926cb8a-2829-11e5-9f77-c7c50246c1d2.png)

**Comment by AnsonSavage** [comment]
@olear Okay, that makes a lot more sense now.  Thanks!

**Comment by olear** [comment]
Maybe we should make it more logical (hide prefix folders), this is not the first time this is asked.
