### ISSUE TITLE
Crash when "Open file" or "Save file" windows are opened

### ISSUE THREAD

**Issue by Phantom-Studio** [MrKepzie/Natron#751]
Hello everybody,

Well on Natron v1.2.1 and Natron's last snapshot (Natron-183e381435f7f73890f7d93c9a06a4f7ede5d426), I've added a mapped network drive (QNap NAS) in the "Open file" windows ; this drive is where all our project files are stored.

Then each time I want to save or open a comp, Natron is crashing...
So I am unable to use it at the moment, so sad.

If you have any idea to remove this mapped network drive from Natron's brwoser, just let me know.
Thanks in advance.

Regards.
Jonathan

**Comment by MrKepzie** [comment]
The issue you are running into is: https://github.com/MrKepzie/Natron/issues/413
I've never been able to reproduce it myself as I don't have a NAS. I hope someone could help debugging this on windows;)

**Comment by Phantom-Studio** [comment]
Thanks MrKepzie for this feedback!

Even if I've changed the "LastLoadSequenceDialogPath" "LastOpenProjectDialogPath" "LastSaveProjectDialogPath" "LastSaveSequenceDialogPath" in HKEY_CURRENT_USER for C:\

the "open" or "save" dialog boxes are making Natron crashing.
For information I'm on windows 7 x64 pro edition.

Regards.
Jonathan

**Comment by MrKepzie** [comment]
Is this possible for you to try using the file dialog while your computer is isolated from the Network drive to figure out if this is what makes it crash ?

**Comment by Phantom-Studio** [comment]
Yep, you are right MrKepzie!
It works now if I'm deactivating my network card...

Then I've reactivated it and I'm able to open or save in Natron.
For the moment this workaround is ok but we have to move all our data on local drive and is pretty sad...

But I hope this tips will help other people.
And thanks again MrKepzie.

Regards.
Jonathan

**Comment by MrKepzie** [comment]
Well this is a temporary workaround, but sadly If I’m not able to reproduce the issue, someone needs to help debugging this. 

Some extra info: how did you add your network drive to the “Open file” window ? (what was the path and the sequence of actions you did)

**Comment by Phantom-Studio** [comment]
![natron_bug_01](https://cloud.githubusercontent.com/assets/13329038/8672415/634e821e-2a2e-11e5-8f4c-09b83938f475.jpg)

Here are the steps I've followed in order to add my mapped network drive as a Favorite in Natron.
But I've noticed something, if I directly browse to this network drive with the "Look In" roll out, everything is fine.

Hope it helps.

**Comment by MrKepzie** [comment]
Aight I’ve just reproduced the crash!

**Comment by Phantom-Studio** [comment]
Good to hear! ;-)

**Comment by Phantom-Studio** [comment]
Great! Thanks for this!

**Comment by MrKepzie** [comment]
At least for me it now works flawlessly when using network drives. To be tested once this is up on the build server.
I will fix the windows snapshots tomorrow on the build server.

**Comment by Phantom-Studio** [comment]
Ok, when it will be uploaded, I will test it and let you know!

Have a nice day.
