### ISSUE TITLE
 to take care visual design GUI of natron

### ISSUE THREAD

**Issue by manuelsongokuh** [MrKepzie/Natron#752]
hello
here i add report for feedback, to correct visual design, maybe future, to-do-list fix...
hello i'm back here, see screenshot natron actual:
![crop2](https://cloud.githubusercontent.com/assets/12126929/8696689/ca4dd170-2aee-11e5-90a9-a27eb1191df1.png)

zoom 
![crop](https://cloud.githubusercontent.com/assets/12126929/8696695/d52cc54c-2aee-11e5-93e9-536b12ae4017.png)

design graphical is not good..
need fix it.. see my example design base of natural natron:
![image10](https://cloud.githubusercontent.com/assets/12126929/8696706/0154dfce-2aef-11e5-92d0-c20dc9f4cff8.png)
![crop1](https://cloud.githubusercontent.com/assets/12126929/8696710/07472b62-2aef-11e5-815c-b3970edc4119.png)

see compare:
![crop2](https://cloud.githubusercontent.com/assets/12126929/8696689/ca4dd170-2aee-11e5-90a9-a27eb1191df1.png)![image10](https://cloud.githubusercontent.com/assets/12126929/8696706/0154dfce-2aef-11e5-92d0-c20dc9f4cff8.png)
![crop](https://cloud.githubusercontent.com/assets/12126929/8696695/d52cc54c-2aee-11e5-93e9-536b12ae4017.png)![crop1](https://cloud.githubusercontent.com/assets/12126929/8696710/07472b62-2aef-11e5-815c-b3970edc4119.png)

**Comment by manuelsongokuh** [comment]
there are error design:
![need-cancel-1](https://cloud.githubusercontent.com/assets/12126929/8696989/9c6a9790-2af1-11e5-94f1-b3d7e27e6e1c.png)
![crop4](https://cloud.githubusercontent.com/assets/12126929/8696992/a61efc68-2af1-11e5-9ee1-0dda2128ce41.png)

**Comment by olear** [comment]
Been thinking about fixing the stylesheet etc since 2014, but there's always something else .... At the moment I think stability should be the most important focus.

Everyone is free to do changes btw ;) Start with a clean stylesheet (and remove hard-coded stuff), and take it from there ....

**Comment by manuelsongokuh** [comment]
@olear 
yes of course for ["stability] and [remove hard coded stuffs]

but need to report to take care information to correct, because i dont find little report...so i add here for information helpful ok?

**Comment by manuelsongokuh** [comment]
see here example base fix:
![a](https://cloud.githubusercontent.com/assets/12126929/8697959/eaba1cb0-2af9-11e5-8f9b-4b5b7b7a7fc9.png)![b](https://cloud.githubusercontent.com/assets/12126929/8697962/ef4b33f4-2af9-11e5-973e-ce6f06827c40.png)

**Comment by MrKepzie** [comment]
This is not so easy to do and requires many changes in fact just for that little change. It was already suggested in https://github.com/MrKepzie/Natron/issues/641
