### ISSUE TITLE
ERROR: The node net.sf.openfx.MergePlugin version 1.0 was found in the script but does not exist in ...

### ISSUE THREAD

**Issue by InRoCh** [MrKepzie/Natron#753]
As you can see in the title the Merge and many other Nodes aren't in good shape
The capture below is from the last Windows x86 snapshot - Natron-e284c8b66d98ccfd84bf849330d0dd798bbe7bcd
The x64 version have also the same problem.
![missing-tools](https://cloud.githubusercontent.com/assets/13278672/8706840/e22c926e-2b29-11e5-8437-f6adbcb87a5c.jpg)

**Comment by MrKepzie** [comment]
This is fixed, will be on next snapshot. We are moving snapshots onto downloads.natron.fr btw
