### ISSUE TITLE
Make upgrade mechanism more robust by mimicking Debian's uscan magic

### ISSUE THREAD

**Issue by ronalde** [MrKepzie/Natron#754]
It would be great if the update feature of the maintenance utility would use something more sophisticated than the the current (static) list of urls to some sourceforge mirrors of which none really works most of the time. 

Debian created a small PHP-script to assist Debian package maintainers. It makes downloading the latest snapshot of natron for 64bit Linux as easy as:
```
wget https://qa.debian.org/watch/sf.php/natron/Natron_Linux_bundle_snapshot_x86-64bit.tgz
```

The source code for the URL above is avaliable at
http://anonscm.debian.org/viewvc/qa/trunk/wml/watch/sf.wml?view=markup. Although its coded in PHP it would be easy enough to translate its functionality to any other language. I imagine the same applies to your upgrade procedures?

Regards,
Ronald

--
 For the convenience of Linux users, the following one liner will download the latest (64bit) Natron snapshot and start the installer:
```
wget https://qa.debian.org/watch/sf.php/natron/Natron_Linux_bundle_snapshot_x86-64bit.tgz -O - | \
tar -xz && \
./Natron_Linux_bundle_install_x86-64bit_vworkshop
```

**Comment by MrKepzie** [comment]
Hi, we are in the process of migrating from source forge to downloads.natron.fr, there will be no more mirrors issues.

**Comment by ronalde** [comment]
Thanks for your swift answer (and great software too!).
