### ISSUE TITLE
Viewer1.startForward() python function issue in last snap version

### ISSUE THREAD

**Issue by rcspam** [MrKepzie/Natron#755]
Hi,
Since last snapshot version (Linux e284c8b66d98ccfd84bf849330d0dd798bbe7bcd), when Viewer1.startForward() start play in the viewer  take control without return it back. Need to push stop in the viewer to have control again . test on precedent version without problem.
Is something had change ?

**Comment by rcspam** [comment]
[screenshot is more explicit](https://dl.dropboxusercontent.com/u/2677320/screenshot-2015-07-16_18.57.42.mp4)

**Comment by MrKepzie** [comment]
That’s the turbo-mode causing that.

**Comment by rcspam** [comment]
Oops!
Auto-turbo mode was on, so no possible to unset it from python !?

**Comment by rcspam** [comment]
Is there plans to improve python API to interact yet more with GUI ?
Good Night.

**Comment by MrKepzie** [comment]
What more do you need ?

**Comment by rcspam** [comment]
Read Project setting parameters, know when turbo-mode is on in viewer;)
No idea at the moment, i discover python and PyPlug last days so perhaps add some improve as your devel progresses.
For example, i want set a frame rate in script from project frameRate, i didn't find in doc a function which do that, but i m a beginner with this kind of stuff, so i surely missed something. 
Directly enter function in script editor (surely lot of work here) could be great.

**Comment by rcspam** [comment]
Sorry app.frameRate.get() is ok for frame rate but what about turbo mode ?

**Comment by MrKepzie** [comment]
It is not available to the Python API, i can add it

**Comment by rcspam** [comment]
Thank you, it would allow to check if it is on or off before play viewer from plugin...

**Comment by MrKepzie** [comment]
I’m just gonna make the buttons enabled while in turbo-mode, there is no point is making them disabled.

**Comment by rcspam** [comment]
Yes more better. i just need the info

**Comment by rcspam** [comment]
ThisNode.myParam.setVisible(myBoolean) works no probleme, but ThisNode.myParam.setLocked(myBoolean)  give me an error:
```
thisNode.framesPerSec.getLocked()
AttributeError: 'NatronEngine.DoubleParam' object has no attribute 'getLocked'
```

**Comment by rcspam** [comment]
I hope i am not mistaken, as i comment above i have just replace 'setVisible' which works by 'setLocked' in the script ! In the documentation this functions are both in the same group, so i don't understand why '{gs}etLocked' doen't work. Sorry to ask for help, cause i know migration is time-consuming.
Thank you

**Comment by MrKepzie** [comment]
There is no getLocked function, I don’t know where you got this from in the reference

**Comment by rcspam** [comment]
https://natron.readthedocs.org/en/python/PythonReference/NatronEngine/ItemBase.html?highlight=getlocked#NatronEngine.NatronEngine.ItemBase.getLocked

**Comment by MrKepzie** [comment]
This is for the Roto shapes

**Comment by rcspam** [comment]
Nothing to locked a param when a checkbox is True ?

**Comment by MrKepzie** [comment]
Maybe you are after setEnabled ?

**Comment by rcspam** [comment]
Ok thanks i'll try. But why setVisible works, it's for the Roto shapes too ?

**Comment by MrKepzie** [comment]
yes but visible on the viewer or not

**Comment by rcspam** [comment]
No , a checkbox in the node properties, when it's switched on/off, the FrameRate DoublParam appears/disappears.

**Comment by rcspam** [comment]
An idea for pyAPI ! Possibility to put icons on buttonParams !

**Comment by MrKepzie** [comment]
http://natron.readthedocs.org/en/workshop/PythonReference/NatronEngine/ButtonParam.html#NatronEngine.NatronEngine.ButtonParam.setIconFilePath <http://natron.readthedocs.org/en/workshop/PythonReference/NatronEngine/ButtonParam.html#NatronEngine.NatronEngine.ButtonParam.setIconFilePath>

**Comment by rcspam** [comment]
I'm desperate to see you've thought of everything ;) but "Je trouverai un jour, je trouverai !"

**Comment by rcspam** [comment]
Is it compat with Py group ?

**Comment by rcspam** [comment]
Button create by 'createButtonParam' in PyPlug Group must set with a label.
Use '...setIconFilePath("myIcon")' on this ButtonParam is not possible, so how to change label to icon?

**Comment by rcspam** [comment]
Cool thing could be 'pick' viewer transport to put in PyPlug  like we can 'pick' param in the nodes.
So we could deport some transports from viewer to plugin for example  or start action  when start playing viewer or some other stuff....
Btw, have you a response for the last post (button/icon) ?

**Comment by MrKepzie** [comment]
> 
> Cool thing could be 'pick' viewer transport to put in PyPlug like we can 'pick' param in the nodes.
> So we could deport some transports from viewer to plugin for example or start action when start playing viewer or some other stuff....
> Btw, have you a response for the last post (button/icon) ?
> 

The viewer buttons are not parameters available in the API.

For now the icon of buttons must be an absolute path. 
I will modify to look for the icon in Natron search paths too.

**Comment by MrKepzie** [comment]
It’s fixed, the code was already there but we a little bug

**Comment by rcspam** [comment]
Ok, when linux snapshots will come back  on 'downloads.natron.fr' . Have you some problems to available them for now ?

**Comment by rcspam** [comment]
About icon/button and PyPlug Group: If i set a button with an icon in 'createInstance' function with param.setIconFilePath(..) all is ok but if i want to change icon in a "parameters change" callback with 
thisNode.myButton.setIconFilePath(..), icon button doesn't change. Is this the 'little bug' you speak about above?

**Comment by MrKepzie** [comment]
It is not dynamic and will only be refreshed if you call refreshUserParamsGUI()

**Comment by rcspam** [comment]
Thanks, it works. 
However, i think find out a bug:  if we put thisNode.refreshUserParamsGUI() directly in the "parameters change"  callback without condition, it crash Natron ! 
It happened on any Param change except buttonParam.
[Screenshot here](https://dl.dropboxusercontent.com/u/2677320/screenshot-2015-07-26_17.39.21.mp4).
Little question, is it possible to change the button color ?

**Comment by MrKepzie** [comment]
Hmm yeah this is kinda hackish to do so,  I’m not sure we can support that

**Comment by rcspam** [comment]
Ok... and for button color ?

**Comment by rcspam** [comment]
Sorry, misunderstood the answer , thank you !

**Comment by rcspam** [comment]
Is there a way to do an action when node is deleted or project close in PyPlug group.
I have try "The Before node removal callback" but if i'm right not in group... ?

**Comment by MrKepzie** [comment]
You can set the Before node removal callback on the group node itself

**Comment by rcspam** [comment]
def beforeNodeDeleted(thisNode, app):

**Comment by rcspam** [comment]
First i have tried this:
```
paramHasChanged(thisParam, thisNode, thisGroup, app, userEdited):
     do somethings...
...
def beforeNodeDeleted(thisNode, app):
    do somethings...
....
app.myPyScript.onParamChanged.set("myPyScript.paramHasChanged")
app.myPyScript.beforeNodeRemoval.set("myPyScript.beforeNodeDeleted")
```
then
```
paramHasChanged(thisParam, thisNode, thisGroup, app, userEdited):
     do somethings...
...
paramHasChanged(thisParam, thisNode, thisGroup, app, userEdited):
     do somethings...
     thisNode.beforeNodeRemoval.set("myPyScript.beforeNodeDeleted")
...
app.myPyScript.onParamChanged.set("myPyScript.paramHasChanged")
```
Neither of them works...

**Comment by MrKepzie** [comment]
in the createInstance function of myGroup.py:

def beforeNodeDeleted(thisNode, app):
	...

def createInstance(app,group):

	group.beforeNodeRemoval.set(“myGroup.beforeNodeDeleted”)

**Comment by rcspam** [comment]
Sorry, it doesn't work !
![group plugin creation error_001](https://cloud.githubusercontent.com/assets/10021906/8935710/64317cd8-354e-11e5-9319-08bc209aefe7.png)

**Comment by MrKepzie** [comment]
Huh I’m sorry this is a per project param:

app.beforeNodeRemoval.set(“…”)

I also fixed a bug which prevented this callback from working.

I realise that since this is per project this might not be a good idea to set it directly from your PyPlug. 

I’m guessing I should duplicate all the callbacks that in the project to the group node too and restrain their effect to the nodes within the group

**Comment by rcspam** [comment]
This callback was my first test.... So i'm waiting last snapshot...
But i want just kill a 'ffplay' running when the node is deleted, supended or the project closed... An idea to do that with other way ?

**Comment by rcspam** [comment]
Is this one is concerned by the bug :
     app.AudioToAscii1.beforeProjectClose.set("AudioToAscii.beforeProjectClose")
Same result:
   ... AttributeError: 'NatronEngine.Effect' object has no attribute 'beforeProjectClose'

**Comment by rcspam** [comment]
Ok, test with last snapshot, 'beforeProjectClose' & "beforeNodeRemoval" works, but for this last, callback is call although if i delete another node . If you add the Group as param in "beforeNodeDeleted" , will we test its Label name ?

**Comment by MrKepzie** [comment]
The callback is project wide, hence is called for all nodes! 
That’s why I will also add a per-group callback.

**Comment by rcspam** [comment]
Well understood! thanks

**Comment by MrKepzie** [comment]
I’ve added the 2 callbacks on Group nodes.
The callbacks will be called in addition to the Project-wide callback and only on the Group node and its direct children (not recursively)

**Comment by rcspam** [comment]
The beforeNodeDeleted callback works...but only one time we delete it: If we reload/add the same group node the callback doen't do its work anymore.
[Sceenshot](https://dl.dropboxusercontent.com/u/2677320/screenshot-2015-07-30_09.07.24.mp4)

**Comment by rcspam** [comment]
i call beforeNodeDeleted with:

      def beforeNodeDeleted(thisNode, app):
        some stuff... 
   
      app.AudioToAscii1.beforeNodeRemoval.set("AudioToAscii.beforeNodeDeleted")

**Comment by rcspam** [comment]
Is it possible to add same kind of callback when disable(Crtl-D) a node ?

**Comment by MrKepzie** [comment]
This is the paramChangedCallback, the disabled feature is a parameter in the “Node” tab.

**Comment by rcspam** [comment]
And for https://github.com/MrKepzie/Natron/issues/755#issuecomment-126206516

**Comment by rcspam** [comment]
Sorry for insistence, Alex but is there a possibility to fix it ?
https://github.com/MrKepzie/Natron/issues/755#issuecomment-126206516

**Comment by MrKepzie** [comment]
I don't understand your issue ?

**Comment by rcspam** [comment]
Add AudioToAscii node, add audio file, launch preview (ffplay), delete it, audio preview stop.
So far so good.
Now i add new  AudioToAscii node,  add audio file, launch preview, delete it... audio preview doesn't stop. It's like the beforeNodeRemoval callback works one time only... see the screenshot...
Here how i call it:
 ```
 def beforeNodeDeleted(thisNode, app):
    some stuff... 

  app.AudioToAscii1.beforeNodeRemoval.set("AudioToAscii.beforeNodeDeleted")
```

**Comment by MrKepzie** [comment]
I cannot reproduce your issue, the callback is triggered everytimes here.

**Comment by rcspam** [comment]
This is what i'm doing to kill ffplay(read its pid in a tmp file) when delete node or close app:

```
def createInstance(app,group):
...
...
        # Create a tempfile within "ffplay pid"
        param = lastNode.createFileParam("tmpFile", "Temp File")
        param.setVisible(False)
        tf = tempfile.NamedTemporaryFile(suffix='tmp', prefix='a2a_ffplay_', delete=False)
        param.setDefaultValue(tf.name)
        lastNode.tmpFile = param
        del param

    app.AudioToAscii1.onParamChanged.set("AudioToAscii.paramHasChanged") 
    # kill ffplay when remove node ...
    app.AudioToAscii1.beforeNodeRemoval.set("AudioToAscii.beforeNodeDeleted")
    # ... or close app.
    app.beforeProjectClose.set("AudioToAscii.beforeProjectClose")
...
...

def paramHasChanged(thisParam, thisNode, thisGroup, app, userEdited):
...
...
 # ffplay pid tmp file
    global tmp_file
    tmp_file = thisNode.tmpFile.get()
...
...

# ffplay pid killer
def kill_pid_player(tfKPP):
    pid_file_kpp = open(tfKPP, "r")
    pid = pid_file_kpp.readline()
    os.system("/bin/kill " + pid)
    pid_file_kpp.close()


# Some stuff to do before deleted an AudiToAscii node
def beforeNodeDeleted(thisNode, app):
    kill_pid_player(tmp_file)
    app.pane1.Viewer1.pause()
    os.remove(tmp_file)
    os.remove(ascii_file)

# Some stuff to do before close project within AudiToAscii node(s)
def beforeProjectClose(app):
    kill_pid_player(tmp_file)
    os.remove(tmp_file)
    os.remove(ascii_file)
```
Is there a problem with the scope of **global tmp_file** which is not update when create a new node ?
If you can light me, I'd appreciate...

**Comment by MrKepzie** [comment]
You should not store tmp_file like this, rather you should get the value in the callback instead

**Comment by rcspam** [comment]
*"You should not store tmp_file like this"*. What do you mean ?

**Comment by rcspam** [comment]
If i put *tmp_file = thisNode.tmpFile.get()* in the callback *beforeNodeDeleted* to replace *global tmp_file*, the issue is the same (works only first time), and i don't know how to give *tmp_file* to *beforeProjectClose* , *app.AudioToAscii1.tmpFile.get()* not working

**Comment by rcspam** [comment]
A little help please thanks

**Comment by MrKepzie** [comment]
This is weird, if I just use print in the beforeNodeDeleted callback, it is triggered multiple times. I don't understand why you use tmp_file when you can just use thisNode.tmpFile.get() in beforeNodeDeleted.

Regarding thisNode.tmpFile.get() not working in the beforeProjectClose callback, this is another issue.

**Comment by rcspam** [comment]
My first code was without tmp_file variable, but with thisNode.tmpFile.get(). Dut to this issue, i intoduce "global tmp_file" to try an other way, but with same result so this is this last code i give you . The first code was:
```
def beforeNodeDeleted(thisNode, app):
    kill_pid_player(thisNode.tmpFile.get())
    app.pane1.Viewer1.pause()
    os.remove(thisNode.tmpFile.get())
    os.remove(thisNode.curveFile.get())
```

**Comment by rcspam** [comment]
hi Alex, i know you work at full steam for the next natron release, but what you think about this issue, i like to fix that before natron 2.0. Thanks

**Comment by MrKepzie** [comment]
I have no idea, I cannot test right now. If I get some free time I’ll try it

**Comment by rcspam** [comment]
OK tank toi
Le 9 sept. 2015 09:15, "Alexandre Gauthier" <notifications@github.com> a
écrit :

> I have no idea, I cannot test right now. If I get some free time I’ll try
> it

**Comment by hafuz** [comment]
Hi,
I doesn't have use natron since a long time now, butafter try the new version 2.0.1, audio2asii & audiocurve doesn't work anymore.
Is there some change in the PyPlug API which prevent this plugins to work ?

**Comment by olear** [comment]
Audiocurve works with latest RB-2.0 snapshot, and will work in 2.0.2.
