### ISSUE TITLE
This is not a Natron Issue

### ISSUE THREAD

**Issue by InRoCh** [MrKepzie/Natron#757]
This is a an error of the new "downloads.natron.fr" site.
When i try to download the last build this page appeared.
![403-forbidden](https://cloud.githubusercontent.com/assets/13278672/8763108/759bd574-2d86-11e5-9069-5e359095a426.png)
but for the precdent it works fine.
This is for the Snapshot Windows Build 32bit and 64bit.

**Comment by MrKepzie** [comment]
We are not finished migrating to downloads.natron.fr <http://downloads.natron.fr/>, we will inform when it’s done.
