### ISSUE TITLE
ArchLinux installer is wrong

### ISSUE THREAD

**Issue by nicolasdanelon** [MrKepzie/Natron#759]
https://github.com/MrKepzie/Natron/blob/workshop/INSTALL_LINUX.md
this file **https://raw.githubusercontent.com/olear/natron-linux/master/installer/misc/build-natron-on-archlinux.sh** don't exists any more but the pkg exists in [AUR](https://aur.archlinux.org/packages/natron/)

**Comment by olear** [comment]
I changed stuff in the repo, new url is https://raw.githubusercontent.com/olear/natron-linux/master/include/misc/build-natron-on-archlinux.sh

**Comment by MrKepzie** [comment]
Fixed

**Comment by nicolasdanelon** [comment]
nice, btw, great peace of software!
