### ISSUE TITLE
Very minor request: audio file amplitude extraction node

### ISSUE THREAD

**Issue by blackearth2014** [MrKepzie/Natron#76]
Can we get a node that can analyze an audio waveform file for it amplitude levels.  This way we can use the data to drive the transform node's scale, rotation and location parameters to simulate a camera shake. It can also drive a blur node parameters to create random focus effects and etc.

**Comment by olear** [comment]
I can probably make a plugin with libsndfile and create a waveform, but where to take it from there I don't know... ("export" some value to something ...)

**Comment by sozap** [comment]
I don't know if that make much sense, but why not having your node to show read-only floating value (like amplitude , maximal amplitude , minimal amplitude ) on the properties panel, and then let the user link these value like he want using expressions ?
That would make a nice workaround without having to do all the work for full audio support in Natron.

**Comment by sozap** [comment]
Another way could be like the imageStatistic node : a button to analyse the sound, making an animation on the sliders....

**Comment by olear** [comment]
Creating a plugin has been delayed (https://github.com/olear/openfx-arena/issues/110) on my part, but have alternatives:
https://github.com/rcspam/audio2ascii (bash script)
https://github.com/olear/audio2ascii (qt port)

Select an audio file, tweak some params, save to txt, import into curve editor in Natron.

**Comment by olear** [comment]
Thanks to @rcspam we are getting close to a working "plugin". Just need to adjust/tweak the pythonstuff.

![screenshot](https://cloud.githubusercontent.com/assets/7461595/8578640/1ba82028-25b0-11e5-93ad-dd8abd672e9e.png)

**Comment by olear** [comment]
One question, where can python plugins be located? using the system OFX folder don't seems to work here, only the Plugins folder bundled with Natron (and possible the homefolder/.INRIA/something. Trying to make an installer ...

**Comment by MrKepzie** [comment]
http://natron.readthedocs.org/en/workshop/natronpath.html <http://natron.readthedocs.org/en/workshop/natronpath.html>

**Comment by olear** [comment]
Thanks (RTFM :) ).

**Comment by rcspam** [comment]
How to "import"  'NatronEngine.PyCoreApplication.isLinux()' or 'NatronGui.PyGuiApplication.warningDialog()' for example or other functions in python scripts ?

**Comment by MrKepzie** [comment]
You just have to call

if natron.isLinux():
	…

and 

natron.warningDialog()
…

**Comment by MrKepzie** [comment]
See http://natron.readthedocs.org/en/workshop/PythonReference/NatronEngine/PyCoreApplication.html#coreapp-details <http://natron.readthedocs.org/en/workshop/PythonReference/NatronEngine/PyCoreApplication.html#coreapp-details>

**Comment by rcspam** [comment]
Just another question:
Is it possible to read diskcache stream output from an external app. What is the format of thediskcache.
I want to mux it with audio from external "ffplay/mplayer/mpv or other multiplatform player" to preview ?

**Comment by rcspam** [comment]
natron.isLinux() and natron.warningDialog() produce error:
"NameError: name 'natron' is not defined"

**Comment by MrKepzie** [comment]
Where are you trying to use it ?

**Comment by rcspam** [comment]
in the callback function

**Comment by MrKepzie** [comment]
which callback ?

**Comment by rcspam** [comment]
in AudioCurve.py:
....
paramHasChanged(....)
  **here**
 .......
app.AudioCurve1.onParamChanged.set("AudioCurve.paramHasChanged")

**Comment by MrKepzie** [comment]
Works pretty well here:

def callback(thisParam,thisNode,thisGroup,app,userEdited):
	if not natron.isLinux():
		print("This is not LINUX!")

**Comment by rcspam** [comment]
It doesn't work here !!??
more than half an hour i'm 'm fighting with it !

**Comment by MrKepzie** [comment]
Wait, it seems to not work when used inside a PyPlug

**Comment by rcspam** [comment]
![natron - untitled ntp - _001](https://cloud.githubusercontent.com/assets/10021906/8599906/3e06c8fa-2663-11e5-9ccc-90dcdfb561a7.png)

**Comment by MrKepzie** [comment]
I’m making some changes to the Python API to overcome the problem

**Comment by rcspam** [comment]
Thank you, i have test
@MrKepzie , Have you an answer about [diskCache above question](https://github.com/MrKepzie/Natron/issues/76#issuecomment-119994898) ?
Sorry for my insistence, but iwant know if we have a chance to "pyplug code" this cool function in the audiocurve.py (or audio2ascii.py), just like in Nuke flipBook, But pehaps have you plan to code flipbook in Natron very this week ! Just a joke ;)

**Comment by MrKepzie** [comment]
Access to cache buffers of Natron is not possible via Python.

Anyway we have plans to have basic sound support soon after v2 (probably v2.1)

**Comment by rcspam** [comment]
Thank-you

**Comment by rcspam** [comment]
@blackearth2014 
If you want, you can adapt [my script](https://github.com/rcspam/audio2ascii) for mac, until  'audiocurve' is finished.
If you have questions, don't hesitate.
I think this should be simple and easy, perhaps it  can work without change, it just call to 'bash' which itself call to 'sox' (you have just to install bash and sox which should be in your $PATH)... I'm not a mac user but, it's Unix, so...

**Comment by MrKepzie** [comment]
I’ve fixed it. 

You can use the natron variable like this:

NatronEngine.natron.isLinux()

If you want to remove the NatronEngine prefix, just use

from NatronEngine import *

If you want to access dialogs and stuff use

NatronGui.natron.warningDialog()

You can also use from NatronGui import *
but then it will conflict the 2 attributes natron, so for clarity it is better to keep them prefixed with the module to identify them.

**Comment by rcspam** [comment]
Very Cool . Thak you !

**Comment by rcspam** [comment]
@MrKepzie, Apparently, functions using *NatronEngine* works, but which using *NatronGui* give always 
*NameError: name 'NatronGui' is not defined* with last snapshot :(

**Comment by MrKepzie** [comment]
if not NatronEngine.natron.isLinux():
        NatronGui.natron.warningDialog("Big warning","This is not linux!”)

Works fine here. You probably did not import NatronGui

**Comment by rcspam** [comment]
Sorry ! I had understood that 'import NatronEngine' was sufficient !
It'ok ;)
![unix only_001](https://cloud.githubusercontent.com/assets/10021906/8617387/9bcb2210-2703-11e5-863d-f413dc4f5ab2.png)

**Comment by rcspam** [comment]
Is there anyone crazy enough to test [this new version of audio2ascii](https://github.com/rcspam/audio2ascii/releases/tag/v1.9) on OSX, It works well on Linux, but i can't test it on Mac (env PATH must be set and [some utilities installed](https://github.com/rcspam/audio2ascii/blob/master/README.md#requirements)) so... thanks for the feedback.

**Comment by blackearth2014** [comment]
rcspam,

Would you mind posting this in my NatronNation group at https://www.facebook.com/groups/NatronNation/. Someone there maybe able to help or test this code.

Thanks,

**Comment by rcspam** [comment]
hi,
Can you do that for me, i have no facebook account !

**Comment by blackearth2014** [comment]
Done

**Comment by rcspam** [comment]
Thanks @blackearth2014

**Comment by rcspam** [comment]
@blackearth2014,   [Version 2beta of audio2ascii](https://github.com/rcspam/audio2ascii/releases/tag/v2.0beta) is out, you can test it on OSX if you have time and feedback me.  [Simple to install]( https://github.com/rcspam/audio2ascii#installation--usage). You can see  [a video demo here](https://www.youtube.com/watch?v=koagSOPnsVw). Or put the video on your natron's facebook. thanks

**Comment by devernay** [comment]
This issue was moved to https://github.com/NatronGitHub/Natron/issues/76
