### ISSUE TITLE
(Question) Can nodes have more explicit inputs and outputs in the node viewer?

### ISSUE THREAD

**Issue by ericshawlinux** [MrKepzie/Natron#760]
I noticed you guys like to use nuke, which I never used, however I am used to shake. In shake all the node's inputs, outputs, and mask inputs were clear.

Inputs were tiny tabs on the top of the node
Outputs were tiny tabs on the bottom of the node
Mask was a circle on the right of the node

[Nodes in Shake - Imgur](http://i.imgur.com/Emmd5SU.jpg)

by the way, the left button (green) selected viewing, and the right button selected node properties to appear.

**Comment by devernay** [comment]
It looks more like a "style" issue. Inputs, output, and mask are already at these places in Natron. Better than describing what you want, could you please describe what seems wrong in the current node graph (please refer to snapshot versions of Natron, there have been many gaphic changes since 1.2.1)

**Comment by ericshawlinux** [comment]
I was using 1.2.1 ... I'm actually having a core dump when I run the snapshot version, here is the terminal output:

```
eric@solid-box:~/Natron/bin$ ./Natron
Natron
Version: 2.0.0
Copyright (C) 2015 the Natron developers
>>>Use the --help or -h option to print usage.<<<
Attempt to read an OpenColorIO configuration but the configuration directory/usr/share/OpenColorIO-Configsdoes not exist.
Attempt to read an OpenColorIO configuration but the configuration directory/home/eric/Natron/bin/../Resources/OpenColorIO-Configsdoes not exist.
Cannot mix incompatible Qt library (version 0x40806) with this library (version 0x40807)
Aborted (core dumped)
```

**Comment by MrKepzie** [comment]
Yes, we have been migrating (almost done) the snapshots over to downloads.natron.fr <http://downloads.natron.fr/>

In fact you can download it already, but there are still some bugs left with the some new plug-ins

**Comment by ericshawlinux** [comment]
I got it working actually! I find that there is nothing wrong with the snapshot release's nodes now that I'm using it.
