### ISSUE TITLE
crash when open textOFX/textPango

### ISSUE THREAD

**Issue by rcspam** [MrKepzie/Natron#761]
As says in the title ...
Linux last snapshot

**Comment by olear** [comment]
The last snapshots have a broken IM, so none of the openfx-arena plugins work.

**Comment by rcspam** [comment]
This what i am trying, other openfx-arena :(

**Comment by olear** [comment]
Use this while you wait: https://fxarena.net/~olear/openfx-arena-natron2-linux-x86_64bit-58c9a9d614075c124173e93476749905ff4a1b12.tgz

**Comment by rcspam** [comment]
Thanks, it works !

**Comment by devernay** [comment]
Can we close it?

**Comment by rcspam** [comment]
Don't know if it'fix in new snapshot !

**Comment by olear** [comment]
Still have some issues with the build (don't download latest).

**Comment by rcspam** [comment]
By the way, is the return of Maintenance Tool planned with snapshots on "natron.fr" ?

**Comment by MrKepzie** [comment]
yes
