### ISSUE TITLE
Render threads issue

### ISSUE THREAD

**Issue by Phantom-Studio** [MrKepzie/Natron#762]
Hello ,
we are rendering some comps with natron snapshot "27d8dfe0b7c7bd4be2d4e4dc4e71c5e186b47250"  on win 7 64bits.
It seems natron does not use all cores (cpu running between 13% and 21 %).
It happens with number of render threads=8 and with number of render threads=0.
we use fr.inria.openfx.WriteOIIO version 1.0 to render our jpeg(s) and exr(s).

in addition it would be nice to have a -threads flag for NatronRenderer.exe in order to be able to lauch 8 natron render (or more depending on compouter's cores )in parrallel.

Let we know if i am not clear , i can explain the issue in french more fluently.
Mathieu.

**Comment by MrKepzie** [comment]
How complex is your graph ?

Basically in the tree, what takes most of the time is Reading and Writing images. So my guess is you don’t have a tree “big enough” to make the Reading and Writing negligible. 
Basically 8 threads writing/reading images simultaneously isn’t going to cap your CPU to 100% activity because of the time waited on I/O

**Comment by Phantom-Studio** [comment]
*The graph is pretty simple (cf attachement),  
for this shot the goal is not to render in parrallel but it's to have one render using the 8 threads in order to speed up rendering.  
Maybe the ofx frishluft outOfFocus slows down everything ?  
  
  
  
  
*- - - - - -

*Mathieu ARCE**Superviseur VFX  
*  
![sign](https://storage-master.infomaniak.ch/webmail/signature/8327/d09902fa0b66c05ad3e55207333d9bb579d49271)  
  
  
How complex is your graph ?

  Basically in the tree, what takes most of the time is Reading and Writing images. So my guess is you don�t have a tree �big enough� to make the Reading and Writing negligible. 
  Basically 8 threads writing/reading images simultaneously isn�t going to cap your CPU to 100% activity because of the time waited on I/O


  > On 22 Jul 2015, at 12:06, Phantom Studio  wrote:
  > 
  > Hello ,
  > we are rendering some comps with natron snapshot "27d8dfe0b7c7bd4be2d4e4dc4e71c5e186b47250" on win 7 64bits.
  > It seems natron does not use all cores (cpu running between 13% and 21 %).
  > It happens with number of render threads=8 and with number of render threads=0.
  > we use fr.inria.openfx.WriteOIIO version 1.0 to render our jpeg(s) and exr(s).
  > 
  > in addition it would be nice to have a -threads flag for NatronRenderer.exe in order to be able to lauch 8 natron render (or more depending on compouter's cores )in parrallel.
  > 
  > Let we know if i am not clear , i can explain the issue in french more fluently.
  > Mathieu.
  > 
  > �
  > Reply to this email directly or view it on GitHub .
  > 

�

**Comment by MrKepzie** [comment]
There is no attachment possible on github, contact me by mail privately (in french if you want) @ alexandre.gauthier-foichat@inria.fr

**Comment by MrKepzie** [comment]
I close this as this is related to the EXR reader bug
