### ISSUE TITLE
Features Request

### ISSUE THREAD

**Issue by Phantom-Studio** [MrKepzie/Natron#763]
hello , here some features request 

-search and replace for reads and write nodes

-select nodes by class (Readers,Blur, merge ..)

-channel Merge node

-vectorBlur node

-hueCorrect node (https://www.youtube.com/watch?v=DFjoFU_Qvao)

-a shuffle node with an A dropdown menu even if the two inputs are only RGB. It will allow to set an 
alpha with a value of 0 or 1 without to pipe an other node.

-paste to selected function (eg: I copy a blur node and i want to paste to x selected nodes)

-when the 3d workspace will come , a reconcile3D(compute a 3Dpoint to 2d screenspace coordinates ) would be great ! it s a nice tool to drives flares and other optical effect.

-select all upstream nodes by crtl+click on a node

-in the nodeGraph , be able to navigate in the graph with alt+LMB with an arrow selected.
It s useful when you need to connect a node at the bottom of the tree to a node at the top without to have to zoom out ,

-a larger size for gain and gamma sliders of viewport, if it can fit the whole width it will be nice

I know all those request are probably not the most urgent for the dev team, but i m sure it will improve the user experience.

bye.
Mathieu.

**Comment by devernay** [comment]
Hi @Phantom-Studio
You should make a separate issue for each feature request.
We will need more contributors/developers to get all these implemented, so you can also help by convincing more developers to join the very short list of developers (i.e. Alex, Ole, and me)

**Comment by MrKepzie** [comment]
Just told him by mail that it was ok to make 1 feature request, i will sort them myself to avoid duplicates
