### ISSUE TITLE
HueCorrectNode

### ISSUE THREAD

**Issue by MrKepzie** [MrKepzie/Natron#764]
Make a huecorrect node to be able to edit suppression curves

**Comment by olear** [comment]
Can add a "modulate" node in arena if good enough...

http://www.imagemagick.org/Usage/color_mods/#modulate

**Comment by MrKepzie** [comment]
This is different I think

**Comment by olear** [comment]
Ok.

**Comment by devernay** [comment]
@olear we already have a lot of color correction tools to do this (saturation, color correct, hsvtool)
The node @MrKepzie is mentioning is one that applies successive corrections using curves on h s v r g b etc. There is one in Nuke I think

**Comment by olear** [comment]
Understand, I checked the hue node in Nuke.

Den 2015-07-22 18:39, skrev Frédéric Devernay:

**Comment by blackearth2014** [comment]
Ole,
The attached image is what the HueCorrect Node looks like in Nuke. I consider it as a must have for green screen VFX artist(s) or director(s).  I for one needs this type of node.

![huecorrectnode_demo_scene](https://cloud.githubusercontent.com/assets/7956901/8852294/4643b9fa-3122-11e5-990c-67337849b405.png)

**Comment by sobotka** [comment]
Any Hue operation should be colourspace agnostic. That is, it must not rely on low level weights that are based on any given chromaticity coordinates. Rather, it should be a blind and agnostic division of the RGB primaries into simple degrees.

**Comment by olear** [comment]
This feature was added for 2.1.6.
