### ISSUE TITLE
Merge Behavior

### ISSUE THREAD

**Issue by Phantom-Studio** [MrKepzie/Natron#770]
hello , 
I just noticed a strange behavior with the merge Node.
i set a checkboard in B , and a roto with a rectangle in A.
The merge is set to over, everything is ok , i have my rectangle on top of my checkerboard.
But when i disable the merge and let the viewer connected to it , i see my A input (rectangle roto), and i expect to see my B input.
Is it normal or is there a workaround, or an option to set the default to B ?

**Comment by MrKepzie** [comment]
This is a preference. Go in Preferences—>NodeGraph —> Merge node connect to A input.  Uncheck it.
