### ISSUE TITLE
Feature Request: version up for readers and Writers

### ISSUE THREAD

**Issue by Phantom-Studio** [MrKepzie/Natron#773]
Hello , 
It would be nice to have a function to version up read and write nodes:
ex : i have a read node with in filename :/myDisk/myProject/myRender_v01/myRender_v01.####.exr
and i want to change it to v02 in dirname and basename with just a shortcut (alt+up).
of course it will be better if it work on multiples items selected.
Let me know if i am not clear.

**Comment by MrKepzie** [comment]
You could make a python script for that (or find help to do that), it's not going to happen built-in in Natron as it serves a limited purpose and have some issues: how do you decide which reader/writer to version etc...
