### ISSUE TITLE
last snapshot on OSX : reloading a project, dont take account of dopesheet readers offset

### ISSUE THREAD

**Issue by sebloss** [MrKepzie/Natron#774]
Load any image-sequence-####.png [34-150]
Move his dopesheet strip at 1500
Save project and reopen it.
Reader starting time is reset with the first frame value ( dopesheet reflect this value )
Offset time is good.
Values are well saved in .ntp

My guess is that problem seems to be linked with autodetecting the first frame from the file name, except if "First frame" value has been touched. Because when I change the first frame value, starting time value is well updated. Saving with First frame touched is ok.

So if reader is not a new project instance ( i.e a reloaded reader from .ntp description), dont take account of first frame file name.

This "frame mode" is a weirdy thing , isn't it ? ;)
Maybe just "offset" label with two synced input fields. One for input real starting time and another for real offset..... 

Thank for this great soft !

**Comment by MrKepzie** [comment]
Fixed via https://github.com/MrKepzie/openfx-io/commit/3803274a6483944ad25fbada8691b612eed8c410
