### ISSUE TITLE
re-timing / interpolation

### ISSUE THREAD

**Issue by enetheru** [MrKepzie/Natron#777]
I use my gopro to take footage of various framerates and resolutions, its really nice to have some re-timing/interpolation to bring up my 4k footage from 12.5fps to 25fps, and also animate the slowdown of 100fps dynamically with animation curves. smooth out a timelapse etc.

take inspiration from http://slowmovideo.granjow.net/
which I recently got them to confirm their licence as GPLv3

as suggested on the google groups forum 2014-07-24
https://groups.google.com/forum/#!searchin/natron-vfx/slowmovideo/natron-vfx/8ughCAQ4QQ4/lRHUVN5asvEJ

forum says to submit feature requests as issues.

**Comment by devernay** [comment]
In the works already, but wait a bit more.
You can still use slpwmovideo on your footage beforehand and then set a higher speed using the retimer node

**Comment by devernay** [comment]
This issue was moved to NatronGitHub/Natron#104
