### ISSUE TITLE
Contact Sheet Node (enhancement request)

### ISSUE THREAD

**Issue by nicholascarroll** [MrKepzie/Natron#778]
A contact sheet node would be very useful in Natron when using multilayer EXR. This would let you see all your layers with their labels (channel names).

**Comment by devernay** [comment]
Great idea

**Comment by sirdavid32** [comment]
I second that. I was trying to shuffle the channels and then make a still frame, too much work, a contact sheet will solve it on a single pass (node). Thanks

**Comment by mangopipeline** [comment]
this is not working yet correct?
this is a very requested feature :)

**Comment by devernay** [comment]
This has been available since Natron 2.2.8
