### ISSUE TITLE
Wipe tool: allow viewing of different channels (enhancement request)

### ISSUE THREAD

**Issue by nicholascarroll** [MrKepzie/Natron#779]
When using wipe it would be helpful if the channel in either A or B could be changed independently of the other. 

EXAMPLE:
Compare channel B of A side to channel R of B side.

BENEFIT:
More flexibility and convenience using the viewer, because when comparing two multichannel inputs it is by no means a given that they will be in the same channel. 

WITHOUT THIS ENHANCEMENT you can do it using a shuffle node, but it is inconvenient.

**Comment by devernay** [comment]
I had just pointed this out to @MrKepzie. In Nuke it is done by pressing shift while selecting the channel in wipe mode

**Comment by MrKepzie** [comment]
https://github.com/MrKepzie/Natron/issues/779
