### ISSUE TITLE
Roto implovement

### ISSUE THREAD

**Issue by Ambassy** [MrKepzie/Natron#782]
I know we always do that but i guess there is no direct button for it. Narmal when you draw a bezier(roto) around some thing you're selecting it. But there is a feature that help me more in my editor.  When you draw a bezier there is a button where you can switch between negative/positive. positive means the selected area is the area inside the shape and negative means that the selected area is the area which is outside the bezier. Eg:i want to rotate  hue of my entire picture except one petal of the flower. So i draw a bezier around the petal and select negative. By selecting negative means i want the effect to affect every thing except the petal.  By deafault the roto is positive. So i can directry switch to negative. Is this feature present for direct switch...   I think it can fasten job

**Comment by MrKepzie** [comment]
This is based on the natural matting node I think, it is already in the road map, so I'm closing this.
