### ISSUE TITLE
Rotopaint artifacts

### ISSUE THREAD

**Issue by rcspam** [MrKepzie/Natron#785]
Some artifacts after save and re-open a project with clone rotopaint (no test with other tools).
I fix the nodes with new curves, save and re-open again, but...
![screenshot1](https://cloud.githubusercontent.com/assets/10021906/8951371/73f3f39c-35cd-11e5-8634-061cf9ab274e.png)
![screenshot2](https://cloud.githubusercontent.com/assets/10021906/8951373/7653b992-35cd-11e5-967b-2e993f25f282.png)

**Comment by MrKepzie** [comment]
Just reproduced, will fix
