### ISSUE TITLE
Roto rendering bug 

### ISSUE THREAD

**Issue by sebloss** [MrKepzie/Natron#786]
last osx snapshot version

I'm working on videomapping project and I try to integrate Natron in my workflow.
Here is my simple cropping script in aim to load five projectors with SVGA+ MJPEG videos outputs.
Problem : when you render selected writers at same time, each result output file randomly flickers at the begin ( black frame blinking). It seems threads dont wait the processing branch before append frame in file.

Render each writers one by one works.

It is my bad ?

I try to enable "turbo mode", but render  selected writers action ( dropdown menu ) do nothing at all in this case.

![capture d ecran 2015-07-29 a 15 29 35](https://cloud.githubusercontent.com/assets/13097644/8958716/b1927640-3606-11e5-93fb-31817e002776.png)

**Comment by sebloss** [comment]
Hum this occured not only at the beginning, and images append but the pixel buffer is incomplete :

good frame ( black area is a roto mask ) 
![capture d ecran 2015-07-29 a 15 54 16](https://cloud.githubusercontent.com/assets/13097644/8959379/c42390c4-360a-11e5-8489-091aee14f0a3.png)

some bad frames
![capture d ecran 2015-07-29 a 15 54 34](https://cloud.githubusercontent.com/assets/13097644/8959397/e6474286-360a-11e5-851e-021152392078.png)

![capture d ecran 2015-07-29 a 15 54 50](https://cloud.githubusercontent.com/assets/13097644/8959430/17ec2ba8-360b-11e5-816e-5e550c9c53d2.png)

this one is really bad ( blocks and lines missing )
![capture d ecran 2015-07-29 a 15 55 04](https://cloud.githubusercontent.com/assets/13097644/8959439/32917d28-360b-11e5-9f78-3a9485eae034.png)

**Comment by sebloss** [comment]
Ok, after some test, roto seems to be the bad guy.
Disable it at merge node -> outputs ok
Crop it before merging -> outputs more stable ( 4/5 OK)
I try to replace roto with some random process ( blur/add/color correction ) -> outputs OK

So, roto rasterisation is a little buggy ;)
Question : when roto is rasterized and which node provides the final raster resolution to it ?
Request : menu action for cancel all current renders 

![capture d ecran 2015-07-29 a 16 13 15](https://cloud.githubusercontent.com/assets/13097644/8960135/dc55c0f0-360e-11e5-93d1-ef82af5c81e7.png)

**Comment by MrKepzie** [comment]
This bug is similar to https://github.com/MrKepzie/Natron/issues/785 I'm closing.

**Comment by MrKepzie** [comment]
Re-opening as this is in fact a different issue

**Comment by MrKepzie** [comment]
I fail to reproduce this bug, can you send me the project? I do not necessarily need the input images, just replace it with a radial or constant

**Comment by sebloss** [comment]
I do this now

**Comment by sebloss** [comment]
can I send to you a wetransfert ? ( I package 100 frames with the natron project file ... maybe 5000x1420 image format cause this bug).
email ? natron-contact ?

**Comment by MrKepzie** [comment]
You can email me at alexandre.gauthier-foichat@inria. <mailto:alexandre.gauthier-foichat@inria.Fr>fr

No need for all that frames, just 5 is enough

**Comment by sebloss** [comment]
Maybe this can help.
Roto node seems having a bounding box optimisation under the hood , but it show it  !!
When you scrub the time line, node output looks good. But if you zoom in as render area is bigger than view and you scrub , missing block and other glitches start to come in the cache.

Putting a crop node after roto one improve that.... even disabled ...
 
![capture d ecran 2015-07-30 a 11 10 50](https://cloud.githubusercontent.com/assets/13097644/8979663/b73d5df8-36ab-11e5-8a97-d8bebdc009b0.png)

**Comment by sebloss** [comment]
With "Pyramid" file. 2 viewers in graph but just one connected ( anywhere ). The other is left alone. Clear all caches. Scrub timeline. No pb with roto mask.

Now connect second viewer ( anywhere ). Clear caches. Scrub. Problem with roto like with more than one writer in action.

I try this with second test file ( green rectangle with holes ). Opened like the screnshot state ( two independent branch ). Problem when scrubbing. Ok. Not connected on same stream but problem is always here. So I delete one viewer. Clear caches. Bug still here ??!!

Because I notify another bug, I decide to reload default layout....two viewers tab appear ... the last viewer deleted is still here in memory... I delete it again. Save, close, load, just one viewer -> scrub OK.

Hope this can help you to find this bug. Roto rasterization is losted with more than one output .

**Comment by MrKepzie** [comment]
I found the issue, now I have to come up with a solution and will update

**Comment by MrKepzie** [comment]
Please confirm that this fixes it correctly

**Comment by sebloss** [comment]
yes , it works in this snapshot ! thanks
But in this one Natron-snapshots-75c49eff01f780e1bc70a076af44e73235235cdc.dmg , roto is broken ( no output at all )
