### ISSUE TITLE
Please update website to reflect forum/snapshot changes

### ISSUE THREAD

**Issue by StepanDav** [MrKepzie/Natron#787]
Hi,

this is a minor quibble, but the website could use updates:
1) The "Forum" link points to Google Groups: https://natron.inria.fr/
2) The "Download" link points to https://natron.inria.fr/install/ which in turn leads to https://natron.inria.fr/snapshots/ for snapshots, which still discusses SourceForge.

Thanks!
 - Steve

**Comment by olear** [comment]
The web team is working on the new website last I checked, the old site will/should be replaced soon.

**Comment by StepanDav** [comment]
Over a week has passed, and people are clearly confused, e.g.: https://groups.google.com/d/msg/natron-vfx/wuQqmZrULAw/yV6IuYDNKQAJ

Updating a few links seems fairly straightforward, and might decrease barrier of entry for the users (both to communicate and report issues, as well as to download recent snapshots which is the recommended course of action for most issues).

Given that new website is work-in-progress, would it be reasonable to update just the links to avoid sending people wrong places?

**Comment by olear** [comment]
Seems like the web stuff has been stalled for a while, I don't know...

Moving to the new site (natron.fr) should be a easy job, copy existing website to new server, add new skin (or whatever needed), update info. done (bonus: forward natron.inria.fr to new website to keep "legacy" links).

**Comment by MrKepzie** [comment]
I’ve redirected the links. The site is being updated by Ren, just got in touch with him.

**Comment by StepanDav** [comment]
To clarify, "natron.fr" is the current website? I'm asking because "natron.inria.fr" doesn't say anything about that, and is still the first hit if I Google for "Natron", opening a world of misleading links to the end user.

Is it now possible to retire "natron.inria.fr" entirely?

**Comment by StepanDav** [comment]
Gentle ping?

**Comment by MrKepzie** [comment]
Yes natron.fr is the current website, we are just very slow on the communication process. natron.inria.fr is soon going to redirect to natron.fr

**Comment by olear** [comment]
If the new website is done, I have some feedback.

Frontpage:
- No menu
- Download buttons are too small (also need hoover info, or something)
- broken links
- no real info

Website:
- Less is more, but this is too much, need some gfx/color (but not blue+orange), anything.
- http://natron.fr/blog/ , too much black, and why call it a blog, this is news
- light blue links (and some of the buttons are also light blue) when the rest is white/black? don't work
- all pages  should have a header text (h1/h2), this is now inconsistent

This is after 5min surfing, probably more when I get the time to check the website properly.

**Comment by azerupi** [comment]
Also I think it would be a good idea to add the website to Github so that anyone can make pull-requests. Maybe you could even set autodeploy on new commits with travis?

**Comment by olear** [comment]
If I'm not mistaken the website uses wordpress, that will make things a bit complicated.

btw, the website is not that advanced, it could be possible to just make some XMLs (tools/www) or something and make a build script that builds the HTMLs through XSLT or something and uploads them.

**Comment by StepanDav** [comment]
Few more:
Download is surprisingly difficult to spot from the main page. It's not obvious that the logo silhouettes actually go to per-platform download page. Adding "Download: " at the end of description sentence does not make this obvious. There's also no instruction on how to get snapshots.

There's also a substantial number of broken links:
* http://natron.fr/home/features-roadmap/ (broken; linked from main page)
* http://natron.fr/roadmap/ (empty content, linked from top menu)
* Clicking "More" surprisingly lands me at team page.

FAQ should probably also not be hidden behind "More", it seems like a first class citizen -- if the questions are asked frequently, their answers should be easily reachable.

Alright, everyone's a critic:) The new site is an improvement, I'm glad this move is happening -- just a few bits of the second 80% work left. :)
