### ISSUE TITLE
Merge node not working during render (or sometimes during playback)

### ISSUE THREAD

**Issue by AnsonSavage** [MrKepzie/Natron#788]
Hey guys!  I did a quick masking trick which I successfully completed in Blender:
https://www.youtube.com/watch?v=_Iq9PyEYmfs

Before I did it in Blender, I tried doing it in Natron, however I got this effect:
https://www.youtube.com/watch?v=7Hs-HhzSpAk

It doesn't seem to be a problem with the framerate, however, it could (I already tested that).

Here is a screenshot of my node setup (during the playback, sometimes it plays back perfectly, but other times it looks like it does in the video):
![screenshot from 2015-07-29 17 27 55](https://cloud.githubusercontent.com/assets/12112399/8973201/2af112f2-3617-11e5-95a9-d81fc3d3c7ca.png)

**Comment by MrKepzie** [comment]
Same as https://github.com/MrKepzie/Natron/issues/786

**Comment by AnsonSavage** [comment]
@MrKepzie Okay, do you know what the answer is?

**Comment by MrKepzie** [comment]
The answer is this is a big with the roto node

**Comment by AnsonSavage** [comment]
@MrKepzie Okay, so it's still being solved?

**Comment by MrKepzie** [comment]
yes
