### ISSUE TITLE
textOIIO prevent natron to use all cpu cores

### ISSUE THREAD

**Issue by sebloss** [MrKepzie/Natron#791]
only textOIIO works for me. I have not built arena plugins with good version of imagemagick. ( ... and honestly , I have too many little problems in my own dev, with this lib in the past ).
textOIIO works rather well for burn-in some stamp infos ( thank to great python features ).
But even disable, textOIIO nodes avoid natron to use full cpu when it do renders ( multi writers for my case ).

By the way Natron is really impressive.

**Comment by blackearth2014** [comment]
Sebloss,

Ole has also created a ReadSVG node as well. You can create your text work in Inkscape, save it as a SVG file and load it in Natron using the ReadSVG node. It is a workaround to Natron's TextOIIO and TextOFX shortcomings for now.

**Comment by sebloss** [comment]
Hi Blackearth,

ReadSVG node, yes I saw it ! 
But for now  I'm searching to add some time stamps and other dynamics infos ( date, frame render time, frame/ smpte time stamp, current reader nodes name playing, notations , files location...just basic but useful workflow stuff ). So I just need simple, but solid text node with a bunch of python lines ;)

**Comment by olear** [comment]
Probably related to https://github.com/MrKepzie/openfx-io/blob/master/OIIO/OIIOText.cpp#L78

As far as I know TextOIIO is EOL. If you want more features etc TextOFX or TuttleText is needed.

**Comment by MrKepzie** [comment]
TextOIIO is no longer gonna be around in v2

**Comment by sebloss** [comment]
aaah ! okay, okay.
Tuttle : brew formula doesnt exist anymore
I try to install it through osx package , but tuttle nodes are very instable.
I guess I should switch to macport to build your arena bundle and continue to read natron dev doc.

**Comment by olear** [comment]
TextOFX on Mac should work if you setup fontconfig (make a default fonts.conf and run fc-cache should work in theory), no need to build anything (as far as I know).

**Comment by sebloss** [comment]
Wait a minute , can you help me to see more clearly about ofx arena bundle ?
Because I download the last OSX built snapshot ( 283c8394d0ce5bb60a6acf84970862873cb0abd4 ).
It's works expect a bunch of new nodes ( "Render failed: Unknow failure reason"). This nodes rely on Imagemagick API (Magick++) if I well understand.  In the Natron package, Arena bundle contain Imagemagick-6.9.1 dynlib. After a quick search, I read there is a problem with imagemagick version in OSX snapshot package. Maybe a dont understand because I'm just discover Natron project....so in a hurry... 

I succeed to build Natron workshop with homebrew package manager and io and misc. But no time to look at arena. I try with macport but , again, no time for install local port ( opencolorio missing, ect).

fontconfig is on my mac. Where fonts.config must to be ? I saw natron complain about Fontconfig "error: Cannot load default config file". You're right. But this will not fix arena plugin render issue, isn't it ?

Sorry for flood you with my questions :)

**Comment by olear** [comment]
Arena on Mac snapshots should be built against IM 6.8.9-10+patches/headers from openfx-arena (6.9.0-6.9.1-2 also work (patches/headers needed), but higher is not supported), but I don't know what the binaries in Natron are built against since I don't have access to Mac (push the "?" button in TextOFX for info).

The issues on Mac is related to fontconfig, if you get "no fonts" or "render error" it's because fontconfig (supplied with Natron) is not configured.

Setup fontconfig:
You need to supply a fonts.conf (example: http://www.opensource.apple.com/source/X11fonts/X11fonts-14/fontconfig.osx-fonts.conf) in the right path (can probably be overridden by an ENV option), then you need to run fc-cache (if supplied by Natron) to generate a font cache the plugins can use.

I'm trying to find a solution for Mac (the other platforms don't have these problems), but it's not easy when I don't have access (and limited knowledge) to that platform...

**Comment by sebloss** [comment]
Ok Thanks.
TextOFX give me this info
Powered by ImageMagick 6.9.1-7 Q32 x86_64 2015-07-10 http://www.imagemagick.org

fontconfig continue to complain about default font file. I dont known where it is searching it. I try to place at standard path. /etc/fonts/fonts.conf ( not present )and there is an already exist fonts.conf in macport tree ( /opt/local/etc/fonts/). I run fc-cache -fv

/usr/share/fonts: skipping, no such directory
/usr/X11/lib/X11/fonts: skipping, no such directory
/opt/local/share/fonts: caching, new cache contents: 0 fonts, 2 dirs
/opt/local/share/fonts/Type1: caching, new cache contents: 0 fonts, 1 dirs
/opt/local/share/fonts/Type1/gsfonts: caching, new cache contents: 35 fonts, 0 dirs
/opt/local/share/fonts/urw-fonts: caching, new cache contents: 35 fonts, 0 dirs
/Library/Fonts: caching, new cache contents: 561 fonts, 0 dirs
/Network/Library/Fonts: skipping, no such directory
/System/Library/Fonts: caching, new cache contents: 158 fonts, 0 dirs
/Users/sebastien/.local/share/fonts: skipping, no such directory
/Users/sebastien/.fonts: skipping, no such directory
/Users/sebastien/Library/Fonts: caching, new cache contents: 12 fonts, 0 dirs
Re-scanning /opt/local/share/fonts: caching, new cache contents: 0 fonts, 2 dirs
Re-scanning /opt/local/share/fonts/Type1: caching, new cache contents: 0 fonts, 1 dirs
/opt/local/var/cache/fontconfig: not cleaning unwritable cache directory
/Users/sebastien/.cache/fontconfig: cleaning cache directory
/Users/sebastien/.fontconfig: cleaning cache directory
fc-cache: succeeded

by default updated cache is in $HOME/.cache/fontconfig
but I found a $HOME/.fontconfig dated in 2014 ( an X11 app like inkscape maybe)
I update this folder too.
I put fonts.conf in $HOME/.fonts.conf; $HOME/.fontdonfig/;$HOME/.config/fontconfig/ and /etc/fonts/

Plugins search fonts.conf or cache ?

**Comment by sebloss** [comment]
export FONTCONFIG_PATH=/etc/fonts/
export FONTCONFIG_FILE=/etc/fonts/fonts.conf

OK but :
![capture d ecran 2015-08-02 a 21 31 48](https://cloud.githubusercontent.com/assets/13097644/9027654/f8837d2e-395d-11e5-936f-9eab1153fe62.png)

Fontconfig warning: no <cachedir> elements found. Check configuration.
Fontconfig warning: adding <cachedir>R7bUU6jiFv/var/cache/fontconfig</cachedir>
Fontconfig warning: adding <cachedir prefix="xdg">fontconfig</cachedir>
Fontconfig warning: no <cachedir> elements found. Check configuration.
Fontconfig warning: adding <cachedir>R7bUU6jiFv/var/cache/fontconfig</cachedir>

**Comment by sebloss** [comment]
<cachedir>~/.cache/fontconfig</cachedir> added in fonts.config. No more warning.
Render failure not only concern this font loading config problem...
Maybe Natron error report should be more explicit in the future ( I know it's a lot of rigorous work)

Thank for your time Olear !

**Comment by devernay** [comment]
@sebloss: May be solved by https://github.com/MrKepzie/Natron/commit/ef677f6214b67ab63db7d7f4137da3ad939005de
Please download the new snapshot as soon as it's available, test, and report here.

**Comment by devernay** [comment]
oops the initial issue is about TextOIIO, but the solution is for TextOFX
