### ISSUE TITLE
Crop based ofx plugins dont works as expected

### ISSUE THREAD

**Issue by sebloss** [MrKepzie/Natron#792]
"Black Outside" bool set to false doesnt release pixels out of crop region.
Set to true, 1 pixel contour is well added and is soft ramp apply.

I read a little openfx doc and Crop.cpp... but no clue, it's seems ok regarding what I can understand now. ( ok, i'm a newbie ... :) )

So I try it in Nuke.

![capture d ecran 2015-08-01 a 14 50 47](https://cloud.githubusercontent.com/assets/13097644/9021908/e1484686-385d-11e5-80fb-1324d0258ffa.png)

CropOFX ( the red one ) works but not same behaviour with adjustRod than Nuke Crop.

In Natron I try to adjust the RoD but no effect at all ( no allow negative value).
Intersect obviously doesnt affect process.

![capture d ecran 2015-08-01 a 15 27 48](https://cloud.githubusercontent.com/assets/13097644/9022001/fc78cdbe-3861-11e5-82e2-1574b109e97b.png)

Animate transformation, ROD box, .... can result in nice FXs.

Anyway, I try to understand this "boxes tree"
window, bbox, rod, clip, roi  .... its a litlle confusing.

Any pointer to a clean explanation ( with a nice draw :) ) for this hell of rectangle ?

Thank you

**Comment by MrKepzie** [comment]
Here is the openfx spec: http://openfx.sourceforge.net/Documentation/1.3/ofxProgrammingReference.html

RoD = Region Of Definition is the absolute portion of data that a plug-in may produce
RoI = Region of Interest and is what Natron uses to determine what is required to render at each step of the tree

In Natron the dashed window is the RoD: the data that may be produced, whereas  the plain rectangle is the project format. 
By default everything falling outside the project format is hidden, but you can deactivate this clipping in the viewer by toggling-off the "Clip to project format" button.

**Comment by sebloss** [comment]
Thank for specs.

Clear. But questions come :
So, the "black outside" button is useless if I understand you.
Maybe it should become "preserve original RoD" or just let adjustRoD Node do the job.
Is Crop just an interactive AdjustRoD node ? :)
