### ISSUE TITLE
alignment, possible?

### ISSUE THREAD

**Issue by manuelsongokuh** [MrKepzie/Natron#796]
hello

i think need very "alignment" like as

inkscape (relative to: page, selected, last selected, first selected, all selected)
natron     (relative to: project format, selected node (any), from X: 100 and y: 100 (customize).

top, center, bottom, left, middle, right

maybe also "Distribution of Objects" of inkscape (this is maybe)

see example image link:
http://tavmjong.free.fr/INKSCAPE/MANUAL/html/Align.html

i hope this feature is very usefully and HELPFUL SO MUCH  for all FANS natron...[incluso me :-) ]
thank you

**Comment by MrKepzie** [comment]
If I understand well you would like this feature in the Roto node. I'm not so sure this is really needed to pull off masks, correct me anyone if I'm wrong. Anyway this is quite a development to do, and I'm afraid the outcome is not so necessary.

**Comment by manuelsongokuh** [comment]
hello
sorry i had add more information, @MrKepzie is right.

then for alignment needs for object (nodes): roto, rectangle, trasform, text (textpango or/and textofx or/and textoiio or/and texture, all that like as OBJECTS in viewer ok?

there is "necessary" see forum group of natron:
link:https://groups.google.com/forum/#!topic/natron-vfx/UnvQnomUs4A

"While this option make perfectly sense in applications like inkscape or openoffice,"
"For me it's like a good and simple option for some cases that doesn't mix well with others."

but i'm ok for milestone to 3.0, important to be REPORT in roadmap or milestones ok?
good summer

**Comment by devernay** [comment]
This issue was moved to NatronGitHub/Natron#106
