### ISSUE TITLE
Group Node: parent - child expand/collapse feature

### ISSUE THREAD

**Issue by blackearth2014** [MrKepzie/Natron#797]
When I place a some read nodes with other processing nodes in a group node, I'd notice that in the dopesheet and curves editor it shows the group node only. It doesn't have a way to expand the group node to get to nodes. If your read nodes all have image sequences, shouldn't they be visible as a child link to group parent?

**Comment by manuelsongokuh** [comment]
try use press: shift + 2 click node group , i find myselft..

**Comment by blackearth2014** [comment]
It doesn't work for me.

**Comment by MrKepzie** [comment]
In the dopesheet the nodes in the group are under the hierarchy of the group nodes. 
The CurveEditor view will be updated to look exactly like the Dopesheet tree

**Comment by devernay** [comment]
This issue was moved to NatronGitHub/Natron#107
