### ISSUE TITLE
Roto doesnt output anything

### ISSUE THREAD

**Issue by sebloss** [MrKepzie/Natron#798]
Last OSX snapshot, roto is broken

**Comment by MrKepzie** [comment]
hmm please elaborate with screenshot and graph, it works fine here

**Comment by sebloss** [comment]
No alpha ( no colors too) and weird things ...

![capture d ecran 2015-08-05 a 06 54 26](https://cloud.githubusercontent.com/assets/13097644/9078453/e43308ca-3b3e-11e5-9d4a-6484ab6b2d4e.png)

**Comment by MrKepzie** [comment]
It's working perfectly fine here, might be a bug in the build

**Comment by sebloss** [comment]
Natron-snapshots-75c49eff01f780e1bc70a076af44e73235235cdc.dmg this build doesn't work well so

**Comment by devernay** [comment]
@sebloss make sure you haven't compiled/installed plugins separately, and that you are running the snapshot version, and not a version you compiled yourself.

**Comment by devernay** [comment]
@MrKepzie  I confirm that Roto and RotoPaint are completely broken

**Comment by MrKepzie** [comment]
fixed

**Comment by sebloss** [comment]
Roto is on the road again. Thanx
