### ISSUE TITLE
[OPENGL]...strange..

### ISSUE THREAD

**Issue by manuelsongokuh** [MrKepzie/Natron#799]
hello
my video board: amd hd 6870
my linux: opensuse 13.2 64bit
driver for video:(source close) AMD Catalyst 15.20.3 (OpenGL:4.5)
natron: 6652abf58d027a2b5710d19a53ceb63e493a7376
~> fgl_glxgears 
Using GLX_SGIX_pbuffer
7574 frames in 5.0 seconds = 1514.800 FPS
9398 frames in 5.0 seconds = 1879.600 FPS

~> fglrxinfo
display: :0  screen: 0
OpenGL vendor string: Advanced Micro Devices, Inc.
OpenGL renderer string: AMD Radeon HD 6800 Series 
OpenGL version string: 4.5.13397 Compatibility Profile Context 15.20.1046

i add 2 viewers, 2 windows separate..show windows error:
The viewer may not be fully functional. This software needs at least openGL 1.5 with NPOT textures, GLSL, VBO, PBO, vertex arrays."

how...uhm...it's strange...or my linux is problem?
or natron can check for TEST opengl?

**Comment by manuelsongokuh** [comment]
![crop7](https://cloud.githubusercontent.com/assets/12126929/9074016/24b3d908-3b06-11e5-85bf-a3e5b6b2ca21.png)
![crop8](https://cloud.githubusercontent.com/assets/12126929/9074015/24b39c9a-3b06-11e5-8797-666b988540aa.png)

**Comment by MrKepzie** [comment]
This might be a bug in Qt, afaik it should not prevent you from using the viewer anyway

**Comment by manuelsongokuh** [comment]
ok, luck find a bug, natron is grow up many bug to fixed this big important, but @MrKepzie @devernay @olear  are serious men courages, only 3 developer for FIX all bugs..comparison that big softwares have many men..
compliment 3 developers(for now i know: 3 developers, maybe there are other developer i dont know them)
i can help you to find true bug ok? byebye

**Comment by MrKepzie** [comment]
Honestly, for now just ignore the error, this is likely a bug fixed in Qt 5.

**Comment by manuelsongokuh** [comment]
ok, i hope, will be not a bug during wip ok? but keep that strange ok? thank you

**Comment by olear** [comment]
I'm using the Radon opensource driver on my primary computer (laptop) they work perfectly. You should test and see if they work better than FGLRX (AMD is not known to supply good drivers on Linux to say the least).

btw, Qt5 is no guarantee that things are fixed ;) (found several annoying Qt5 bugs when converting some Qt4 desktop projects I got)

**Comment by manuelsongokuh** [comment]
FGLRX is big features than radeon, Mesa, because i have use blender and natron, kdenlive, lightworks..i will try into open source radeon..

**Comment by olear** [comment]
Understand why you use FGLRX, but if this does not happen when using the Radeon driver, then it could be a driver issue.

**Comment by manuelsongokuh** [comment]
yes it's possible for driver issue..this issue will close or waiting for future find will be fix or bug third party issue...i dont know what is problem from...

**Comment by olear** [comment]
Just try running with the opensource driver and see if your problem still exists (can't test issue since my gfx card is too old for the FGLRX driver)

**Comment by manuelsongokuh** [comment]
i cant try reproduce this window error, it's rare maybe stress ram or stress CPU...
so i did remove fglrx and return mesa radeon..

there is interesting result of glxgear..

 glxgears 
Running synchronized to the vertical refresh.  The framerate should be
approximately the same as the monitor refresh rate.
302 frames in 5.0 seconds = 60.267 FPS
300 frames in 5.0 seconds = 59.954 FPS
300 frames in 5.0 seconds = 59.958 FPS
XIO:  fatal IO error 11 (Resource temporarily unavailable) on X server ":0"
      after 3207 requests (3207 known processed) with 0 events remaining.


FGLRX is FASTER than RADEON open source...but for now is worked on my linux opensuse but i'm not sure to use radeon open source because is not faster.. but for now i can try with radeon to use it a period until when radeon is not good i will back re-install fglrx ok?
then i will back here the same ok?

**Comment by manuelsongokuh** [comment]
there is other interesting information result from phoronix for test AMD old and AMD latest http://www.phoronix.com/scan.php?page=article&item=catalyst-155-linux&num=2

**Comment by manuelsongokuh** [comment]
![opengl-1 5](https://cloud.githubusercontent.com/assets/12126929/10620902/d6bc83d0-777d-11e5-8fdf-d983a88005c4.png)
again...
https://github.com/MrKepzie/Natron/commit/9b8abe3fc4517cfce2d9fdb65966ea7b06e3f032

**Comment by olear** [comment]
I think this is a KDE issue.

**Comment by manuelsongokuh** [comment]
it's possible, not know, but i have heave nodes and groups..this is maybe stress to cpu and ram and gpu will be broken opengl background process..?

**Comment by olear** [comment]
Try turning off "desktop effects" in kwin/kde, may fix the issue.

**Comment by manuelsongokuh** [comment]
i use without desktop effects kwin to startup.. this is true strange..

**Comment by olear** [comment]
Does this still happen?

I could replicate this last year on KDE (only) sometimes, but are currently unable. I don't think this is a Natron issue if it still exists.

**Comment by manuelsongokuh** [comment]
me too dont know, why kde sometimes.. i think can close this issue, because period i dont find problem yet..
in future can back here if same issue ok?

**Comment by olear** [comment]
Closing, feel free to re-open if this happens again.

**Comment by manuelsongokuh** [comment]
yes..
