### ISSUE TITLE
Roto shapes cannot be constrained at creation

### ISSUE THREAD

**Issue by sebloss** [MrKepzie/Natron#801]
Last osx snapshot.

I try many shortcut key , but it seems impossible to constrain roto shapes to create circle or square.

Am I missing somethings ?

**Comment by MrKepzie** [comment]
I do not understand the issue, ellipses and rectangles are separated tools

**Comment by sebloss** [comment]
I mean : perfect circle ( special ellipses ) and square rectangle.
CTRL when mouse pressed and dragging -> constrain ellipse to circle
SHIFT when mouse pressed and dragging -> draw ellipse with mouse pressed pos as center
CRTL+SHIFT when mouse and dragging -> combine these two options

same for rectangle and all shapes in general.
 
It's a classic in graphics apps.

This can be apply on selection bounding box ( always constrained when dragging corners for now)

**Comment by devernay** [comment]
I think it's the reverse (at least on Mac):
SHIFT = constrain to circle
CONTROL = center
This is also the way it works on Nuke (and control and/or shift have can be pressed/depressed after clicking).
Right now, only CONTROL=center is implemented in Natron, and control has to be pressed when clicking, which is wrong.
This has to be fixed (hint : the modifier state should be checked in penMotion and keyDown/keyUp, not in penDown).
@sebloss do you confirm?

**Comment by sebloss** [comment]
@devernay Yeah ! that works very well. Big thanks
Reporting bug is efficient for learning how to code works. Cool
