### ISSUE TITLE
setup google breakpad for automatic bug reporting

### ISSUE THREAD

**Issue by devernay** [MrKepzie/Natron#802]
marking this as 2.1, since we probably won't have time to set this up before 2.0

**Comment by olear** [comment]
Been busy with work this last days, will setup server as soon as possible (so at least the server is ready).

**Comment by devernay** [comment]
@MrKepzie can you upgrade the google-breakpad submodule in the mean time (as well as google-mock & google-test) - I don't have control on these.

Note that you can use the export-to-github feature from google code to get fresh copies of these projects:
https://code.google.com/export-to-github/
