### ISSUE TITLE
File Browser not displaying files

### ISSUE THREAD

**Issue by hellocatfood** [MrKepzie/Natron#803]
I've been using Natron 2.0 and versions before it on Ubuntu 15.04. I'm trying to read a sequence of 4000 pngs using the Read node. When I try to import the sequence the files don't appear in the file browser and if they do the interface "blinks".

https://youtu.be/WSQYFWbLImc

See above video for more info. The window on the right shows that the files do actually exist.

**Comment by MrKepzie** [comment]
It’s actually just very slow to be loaded and while you wait you only see the “/“. This is because of the sequence “parsing” which takes some time to build. Change the dropdown to “File” instead of “Sequence” and this should be instantaneous.

**Comment by sebloss** [comment]
Used to have long sequence to work on , and I notice this little problem. Often back and forth between finder and Natron to check if I really save my sequence where I try to find it.
Sequence parsing code maybe do too much check.

**Comment by MrKepzie** [comment]
The code is in https://github.com/MrKepzie/SequenceParsing <https://github.com/MrKepzie/SequenceParsing> if you think you can add any improvement

**Comment by devernay** [comment]
it seems to be O(n^2), but this should really be less complex:
- keep a map with key=pattern and value = set of filenames
- for each filename, compute all possible "patterns" and add this file to all corresponding entries in the map (it's O(n))
- take the key with the largest set, mark all filenames in this set as belonging to this sequence, and remove each filename from all other sets (O(n*m) where m is the number of guessed patterns. If a set is empty, remove the entry from the map
- voila

**Comment by sebloss** [comment]
Ok, I'll take a look at this one

**Comment by olear** [comment]
One more .... Clean all Natron config's, start Natron, press 'r', the home folder is empty. Press '/' (or something else than home folder) and back again, all is good. Happens on first-run after cleaning config.

Normal:
![normal](https://cloud.githubusercontent.com/assets/7461595/9114587/ea85f80a-3c5a-11e5-8cdf-389d9914e4cc.png)
I see the folders/files in my home dir.

Clean (rm -rf ~/.config/INRIA):
![clean](https://cloud.githubusercontent.com/assets/7461595/9114614/0635aac8-3c5b-11e5-96b9-059e3d6c6141.png)
Pressing '/' and then 'olear' works. Only happens on clean config.

**Comment by MrKepzie** [comment]
The current algorithm is as follow:

For each file in the folder, make a possible pattern out of it, e.g: mySequence###.jpg (see https://github.com/MrKepzie/SequenceParsing/blob/master/SequenceParsing.cpp#L756 for the parsing)

For all existing patterns, try to match the current file pattern to one of the existing pattern.
If it matches, insert it into the sequence otherwise if it does not match or no sequence exist so far, just create a new one. 
See https://github.com/MrKepzie/SequenceParsing/blob/master/SequenceParsing.cpp#L1271 for the matching test

Afaik the possible improvements are in the matching and parsing of patterns

**Comment by azerupi** [comment]
> For each file in the folder, make a possible pattern out of it, e.g: mySequence###.jpg

Most of the time people only have one sequence in a directory. Or at least the number of files belonging to a sequence outnumber the number of sequences you have. 

If you assume the above, you can calculate the possible patterns for 1 file and then check the other files for matches. Repeat until you have matched all files. Though, this will perform badly when the sequences are very short and you have a lot of them or even if you have a lot of files that don't belong to sequences. Bu it can probably be improved, just throwing in ideas :)

**Comment by MrKepzie** [comment]
Huge speed up after https://github.com/MrKepzie/Natron/commit/38ff10ae4005bdbfe2c3b510f3f514abf1749def
