### ISSUE TITLE
TextOFX - Font familly not populated 

### ISSUE THREAD

**Issue by philouvb** [MrKepzie/Natron#805]
I'm on a mac running Yosemite V10.10.4 using Natron version 2.0.0 . It seems that the "TextOFX" node does not populate his "Font-familly" list. It stay empty whatever you do !
![screenshot](https://cloud.githubusercontent.com/assets/2259686/9088825/4d8aedee-3b92-11e5-9f0f-5173de7d226e.jpg)

**Comment by blackearth2014** [comment]
Have you downloaded the latest snapshot from http://downloads.natron.fr/Mac/snapshots/?

**Comment by philouvb** [comment]
I downloaded the latest snapshot . Launched Natron . With the latest Snapshot I don't have this problem anymore the List is quite well populated . A remark it's quite complicated to access dev snapshots now thru your website .Is there a way to correctly reference "Snapshots" in the download section for the moment its not .

Anyway thanks for your response !

**Comment by philouvb** [comment]
I downloaded the latest snapshot . Launched Natron . With the latest Snapshot I don't have this problem anymore the List is quite well populated . A remark it's quite complicated to access dev snapshots now thru your website .Is there a way to correctly reference "Snapshots" in the download section for the moment its not .

Anyway thanks for your response !
