### ISSUE TITLE
File Browser sequence player start at the first project frame range

### ISSUE THREAD

**Issue by sebloss** [MrKepzie/Natron#806]
I want to check my images sequence in file browser player.
My sequence output start at 11300.
Project range fisrt frame is setup to 1.
First I think my output is bad ( same image for whole sequence)
AAh no, animation is here at the very last 10 pixels of the timeline...

A workflow bug ;)

**Comment by devernay** [comment]
You are right, the last frame of the project is correctly set when creating the first reader, but not the first one. The current frame should also be changed if it's outside of the frame range, and the timeline should be resized accordingly.
