### ISSUE TITLE
Roto ->mask-> merge over  issue ?!

### ISSUE THREAD

**Issue by rcspam** [MrKepzie/Natron#808]
![natron - untitled ntp - _002](https://cloud.githubusercontent.com/assets/10021906/9104998/184feb8a-3c13-11e5-9cf9-5ea0dee21c46.png)

**Comment by rcspam** [comment]
precision: commit 1d08991f7a2e24d086881c29b638461dd9db846e linux

**Comment by MrKepzie** [comment]
No, your Constant in A has a 0 alpha channel,hence over does nothing

**Comment by rcspam** [comment]
Constants are 1 alpha
![natron - untitled ntp - _001](https://cloud.githubusercontent.com/assets/10021906/9129339/afff21e4-3cd6-11e5-884e-2472a8217806.png)

**Comment by rcspam** [comment]
Sorry
