### ISSUE TITLE
Timeline Playback Bug

### ISSUE THREAD

**Issue by PostPollux** [MrKepzie/Natron#810]
There is an issue with the timeline. When I start playback  and then hoover over the timeline and move my cursor the playback stops to update until the you stop to move the cursor.

Here a video so you get what I mean:
https://goo.gl/photos/1Ct5kwAB79XtrJBe9

Further more the scrubbing is ultra slow. Im not sure if this is correlated to the bug above and it just doesn't update because I'm moving my cursor on the timeline. I think fast scrubbing on a cached image sequenz shoud be possible at least its possible in djv - imaging.

Thanks for your awesome work!
Johannes

Linux Manjaro 64 bit (GTX 765 with official nVidia drivers)
Natron version 2.0.0 Release .
This version was generated from the source code branch workshop at commit cb958c27230bf846740d89fd9c47f3cffd3059aa

P.S.: I used this snapshot of Natron on Linux Manjaro. Sorry, it's not the newest one and I wanted to update it, but it didn't work. None of the Repositories in the Mantaniance tool was available and I can't find a new dowload as the link on "https://natron.inria.fr/snapshots/" points to sourceforge with no files. And there it says the files could be downloaded here: downloads.natron.fr
But I can't find those files...

**Comment by blackearth2014** [comment]
Here is the new download link page at http://downloads.natron.fr.

**Comment by PostPollux** [comment]
Thanks, you are right! I tryed "www.downloads.natron.fr". So it was my fault. Ok, I downloaded the newest version (6652abf58d027a2b5710d19a53ceb63e493a7376) and it's exactly the same.

**Comment by olear** [comment]
The Linux builds has staled, try this while you wait: https://downloads.natron.fr/~olear/Natron/Natron-1d08991f7a2e24d086881c29b638461dd9db846e-Linux-x86_64bit.tgz (don't know if this fixes the issue you have)

**Comment by MrKepzie** [comment]
Cannot reproduce here on OS X

**Comment by PostPollux** [comment]
Hm, I now tested it on windows here with the latest snapshot and another sequence and the hoovering doesn't stop the playback. Just works like it should. But it's still ultra slow.
I'll test it again with linux and another file sequence as maybe the buggy blender exr has something to do with it. I'll let you know what happens.

**Comment by MrKepzie** [comment]
How many cores do you have? What happens if you change the number of parallel renders settings in the preference of Natron ?

This may also be a graphic card driver issue

**Comment by PostPollux** [comment]
I've downloaded the newest snapshot from today. I've tried several different file sequences and I changed the number of parallel renders. And I updated Manjaro and the graphics drivers today. Nothing helped. It's still the same. :(
I have a quadcore cpu.

**Comment by MrKepzie** [comment]
I must say I don't know what's causing this, but the slow playback you mention has never occurred in all tests I performed across all platforms. Is it possible to you to try on another computer or another operating system to check if the bug still persists ?

**Comment by PostPollux** [comment]
I've just updated to the newest Snapshot and the scrubbing bug is still there under linux on my machine.
But I noticed something that might help.
If I keep scrubbing back and forth, sometimes the update of the viewport works just fine for about 1 second. But during this time the yellow time indicator doesn't update. As soon as the yellow time indicator updates again, my viewport stops from updating. So maybe this helps. Maybe there are some update priorities? I don't know.
Here's a video where you can see what I explained above: https://goo.gl/photos/198qi5VB7vE9wthQA
It's just a read node connected to the viewer. Nothing else.

**Comment by PostPollux** [comment]
I updated Natron and scrubbing works perfectly fine now! Thanks! I don't know if it was some update of natron or linux, but the problem is gone!

Now, concerning my problems with the timeline, the only one left is this bug mentioned in the first post:
When I start playback and then hoover over the timeline and move my cursor the playback stops to update until the you stop to move the cursor.

**Comment by MrKepzie** [comment]
Is it still an issue ? If so can you post a screen-cast ?

**Comment by PostPollux** [comment]
No it's gone! Thanks a lot! You can close it now.
