### ISSUE TITLE
OpenEXR Full (+zdepth) bad performance

### ISSUE THREAD

**Issue by sebloss** [MrKepzie/Natron#812]
5000x1420 OpenExr full 32 float + zdepth (blender output).

Same process in nuke vs natron : natron 7 time slower with 8 cores at 100%
Nuke take just 160% of cpu 
I know it's not really a bug and maybe a priority. But this is very limiting for production.
Process here is very simple.

I investigate this later. Blender video sequencer figth a lot reading this image format. Maybe same lib opensource openexr lib is used.

![capture d ecran 2015-08-06 a 10 49 54](https://cloud.githubusercontent.com/assets/13097644/9108314/777250a2-3c2d-11e5-85b6-9b2a84662f28.png)
![capture d ecran 2015-08-06 a 10 53 20](https://cloud.githubusercontent.com/assets/13097644/9108319/82249ae6-3c2d-11e5-8b70-7b9ac1c6e3aa.png)

**Comment by MrKepzie** [comment]
This is known and a bug in openimageio. The issue is already opened there

**Comment by sebloss** [comment]
Ok so I close this one
