### ISSUE TITLE
Natron crashes with Blender MultichannelEXR

### ISSUE THREAD

**Issue by PostPollux** [MrKepzie/Natron#813]
Me again! Natron doesn't seem to like the MultichannelEXR i rendered in Blender (2.75). I can open and watch it, but as soon as I use a node inbetween the loader and the viewer natron just crashes. It doesn't matter which note.
I tested it with PNG and an mp4 file and they worked just fine...

My EXR-File: https://drive.google.com/open?id=0B7H7o4A_ad-naXQ1bVRic1NBekU

My System:
Linux Manjaro 64bit (GTX 765 with official nVidia drivers)
Natron version 2.0.0 Release .
This version was generated from the source code branch workshop at commit 6652abf58d027a2b5710d19a53ceb63e493a7376.

**Comment by PostPollux** [comment]
Mh, maybe it's a blender bug! I used to use the multilayer exr fileformat and had never any problems with it. But now even if I open the file in the blender compositor and look at ze z-channel or the matIndex pass I get this strange result:
![bug_blender](https://cloud.githubusercontent.com/assets/9008901/9110315/0e20d6a4-3c3d-11e5-8e05-c449d8c532f0.png)
Looks like the file is broken... So maybe it's not Natrons fault.

**Comment by MrKepzie** [comment]
Works fine here
