### ISSUE TITLE
Use proper version naming

### ISSUE THREAD

**Issue by devernay** [MrKepzie/Natron#814]
The snapshots should be tagged as "Natron version 2.0.0 Snapshot." (not Release), and versions compiled from source should be tagged as "Natron version 2.0.0 Devel."

TODO: modify the build scripts to add CONFIG+=snapshot to qmake options.

Alpha, Beta, RC and Release should be reserved for released versions only (both binary and source tarballs).

I modified the OSX build script to do that (add CONFIG+=snapshot to the qmake arguments), but couldn't find a linux build script in the sources (where is it?), and I don't know how to modify the windows build script (I don't know anything about BAT, sorry).
@MrKepzie & @olear can you help?

**Comment by olear** [comment]
add to qmake or replace CONFIG+=release ?

**Comment by olear** [comment]
https://github.com/olear/natron-linux/commit/a1dcabd13de8447801c872bf3f3d2a89e32d79f9

**Comment by manuelsongokuh** [comment]
This is goood idea for public the information clear sincery ok?

**Comment by MrKepzie** [comment]
All scripts have that now
