### ISSUE TITLE
Should NodeGraph be rewritten to use OpenGL instead of QGraphics framework?

### ISSUE THREAD

**Issue by captainmpc** [MrKepzie/Natron#815]
I notice, node graph ( on OSX at least ) come to be very slow to navigate.
Few nodes slowdown the graph.

I notice the first level of zoom which doesnt show node text label, is more fast to be drawn.

![capture d ecran 2015-08-06 a 15 29 00](https://cloud.githubusercontent.com/assets/13097644/9113215/97fe5570-3c53-11e5-91e6-80bcc33faaf2.png)

I think text is too " beautiful " : it seems to be generated each time the graph is navigated.
and We dont need to zoom graph at this level

![capture d ecran 2015-08-06 a 15 29 35](https://cloud.githubusercontent.com/assets/13097644/9113201/8ab6395a-3c53-11e5-9ea6-66b42a945e36.png)

Should it be rasterized in texture at a fairly nice dpi but not to much, one time only and limit zoom level?

Here nuke graph at max level. Notice the aliased text

![capture d ecran 2015-08-06 a 15 42 55](https://cloud.githubusercontent.com/assets/13097644/9113250/cfbdb1ea-3c53-11e5-94bf-9571d49a21cf.png)

**Comment by MrKepzie** [comment]
We are not using OpenGL for the node graph drawing anyway. One would have to make a wrapper around QGraphicsPixmapItem to have textured text

**Comment by MrKepzie** [comment]
Perhaps the best we could do is port the node graph to OpenGL which would give much more flexibility and also better zooming functionalities

**Comment by manuelsongokuh** [comment]
Port in 2.0 or 2.1 milestone?

**Comment by MrKepzie** [comment]
More like 2.1 or 2.2, this is not blocking.

**Comment by MrKepzie** [comment]
It is not decided whether it's going to be ported to QWidget or QGlWidget because font rendering is going to be really bad with QGLWidget

**Comment by devernay** [comment]
There is no proof yet that this is a problem with QGraphicsWidget

**Comment by devernay** [comment]
"By default, QGraphicsView provides a regular QWidget for the viewport widget. You can access this widget by calling viewport(), or you can replace it by calling setViewport(). To render using OpenGL, simply call setViewport(new QGLWidget). QGraphicsView takes ownership of the viewport widget."

**Comment by devernay** [comment]
Note that the nodegraph can also be rendered using OpenGL by adding "-graphicssystem opengl".
You will notice many rendering bugs, which may be due to a mis-use of the QGraphicsView API.

QGraphicsView itself may also be optimized by using simpler graphics primitives and other tricks:
- http://agurines.blogspot.fr/2011/02/qgraphicsview-performance.html
- Qt DevDays 2010 - Qt GraphicsView in Depth: Alexis Menard https://www.youtube.com/watch?v=s3sHIheBe94

**Comment by LifeIsStrange** [comment]
Hum you should envisage to use Vulkan instead of openGL because it will twice the performance and will be massively supported.  And be released this month :D

**Comment by devernay** [comment]
This issue was moved to NatronGitHub/Natron#108
