### ISSUE TITLE
Auto Offset for adding & removing nodes

### ISSUE THREAD

**Issue by blackearth2014** [MrKepzie/Natron#816]
Is it possible to get a feature domelike what is coming to Blender call Auto Offset for Nation when adding and subtracting nodes.  Here is a video link for a reference example at https://vimeo.com/135125839.

**Comment by MrKepzie** [comment]
It's already in there when creating a new node, so we just have add more use cases like dropping a node on an arrow and removing nodes

**Comment by blackearth2014** [comment]
Cool Breeze.

**Comment by devernay** [comment]
This issue was moved to NatronGitHub/Natron#109
