### ISSUE TITLE
Shuffle node not display all of Blender's Multilayer exr files

### ISSUE THREAD

**Issue by blackearth2014** [MrKepzie/Natron#817]
I am having difficulty trying to get the Shuffle node to read all of Blender's EXR Multilayer image.  The ReadOIIO node is reading the great, But soon as I load the Shuffle node only certain channel are read. See Images for references.

This image is the ReadOIIO node display of all EXR Multilayer channel file
![screen shot 2015-08-06 at 11 28 37 am](https://cloud.githubusercontent.com/assets/7956901/9115794/ea690b68-3c2e-11e5-944f-5caedfd96e63.png)

This image is the Shuffle node display of all EXR Multilayer channel file
![screen shot 2015-08-06 at 11 28 59 am](https://cloud.githubusercontent.com/assets/7956901/9115795/ebda876a-3c2e-11e5-8e6e-395ac870b5c0.png)

Thanks

**Comment by MrKepzie** [comment]
Can you send a sample please

**Comment by blackearth2014** [comment]
Here is a link to the request exr file at https://www.dropbox.com/s/wgzav3fdb5tagn7/super_bones0001.exr?dl=0.

**Comment by MrKepzie** [comment]
Do you have something smaller ? I have a very weak internet connection and it takes forever to download. Something really small which can just help reproduce the bug is enough

**Comment by blackearth2014** [comment]
This file is 21mb 720*480 resolution at https://www.dropbox.com/s/p97y4aa6f5kycuh/blocks.exr?dl=0.

**Comment by MrKepzie** [comment]
Here is what I have here, nothing to report:

**Comment by MrKepzie** [comment]
Does it still happen?

**Comment by MrKepzie** [comment]
Aight I fixed the bug, there was an issue if the pass name was "Image"
