### ISSUE TITLE
Add a preference to disable layout loading from projects

### ISSUE THREAD

**Issue by OldSkoolVFX** [MrKepzie/Natron#820]
I am using 2.0.0 commit *1d08991f7a2e24d086881c29b638461dd9db846e*.
When I load a file it automatically changes to the layout saved in the NTP file.  Is this normal or is it suposed to load into the users default layout?  If Natron is now saving the layouts in the file (which has some pros to doing that) then there needs to be a way to disable that function and load the user's default layout.  This could be a setting in the preferences or a check box in a dialog box when opening the file.

Thanks.

**Comment by olear** [comment]
Natron will use the layout saved in the ntp.

**Comment by manuelsongokuh** [comment]
Ah....Luke as blender saved in blend All stuffs(layout,winodws,etcs..) wow :-D

**Comment by OldSkoolVFX** [comment]
*> Natron will use the layout saved in the ntp.*

Well say I do a project on a system with a dual screen setup, why would you want that setup if you are using a laptop?

**Comment by olear** [comment]
Most users want their project to open exactly as last time, if you change computer/hw etc then you need to adapt your project (that's normal in my opinion). 

A setting could of course fix this if not too complex to implement.

**Comment by MrKepzie** [comment]
Implemented
