### ISSUE TITLE
UTF-8 characters do not display correctly in text

### ISSUE THREAD

**Issue by chrisredberry** [MrKepzie/Natron#823]
Attempting to write special characters (UTF-8) into textOIIO node renders boxes instead of the correct characters. We have checked that the glyphs are present in the font. For example, this text:

RT @iamdevloper: We’re safe for a few more years…

(Note the UTF-8 apostrophe and ellipsis character) gives the following result:
![natron-utf8](https://cloud.githubusercontent.com/assets/13523396/9131726/162283bc-3ce6-11e5-99bc-311997b71ffe.png)

The font above is Times New Roman Condensed, but it seems to occur for any typeface - e.g. we've tried Proxima Nova and Gill Sant MT Bold with the same result.

We are using Natron v1.2.1 on OSX Yosemite V10.10.4.

**Comment by olear** [comment]
If possible try latest snapshot of v2 and see if that works for you.

https://downloads.natron.fr/Mac/snapshots/

**Comment by GMaxera** [comment]
@olear : the snapshots of version 2 include your Text plugin and openArenaFx ?

**Comment by olear** [comment]
Yes, but there may be some issue yet (but TextOFX should work).

You could also try TuttleText from TuttleOFX.

**Comment by GMaxera** [comment]
TuttleText has the same issue.
We just need TextOFX, so we'll try it. Thanks.

**Comment by GMaxera** [comment]
@olear do you know if the Linux snapshots of version 2 include your TextOFX also ?

**Comment by olear** [comment]
I can't guarantee anything since I don't test on Mac :)

Linux has all plugins from OpenFX-Arena.

**Comment by MrKepzie** [comment]
TextOIIO is going to be removed in v2 so we cannot fix anything in this regard

**Comment by GMaxera** [comment]
@MrKepzie Sorry ... but this not close the problem for us.
Please, can you give us a solution ? How it will be solved the problem ?
We need to wait the Natron v.2.0 ?

**Comment by olear** [comment]
Did you try TextOFX?

**Comment by GMaxera** [comment]
I cannot try it because the latest snapshot of Natron "destroyed" my Mac.
It start to load more than 60Gb of RAM at startup and my Mac blocked totally.
I stop to try to run the Natron snapshot.

**Comment by olear** [comment]
You can copy Arena.ofx from v2 and it should work on v1, but I can't guarantee anything.

TextOFX is included on Linux, and available for Windows (https://github.com/olear/openfx-arena/releases/tag/1.9.0)

Maybe your issues on Mac could be related to old v1 config/cache/layout?

**Comment by GMaxera** [comment]
I'll try your suggestion ... but probably at the end of the next week because I don't have any time now :-(

**Comment by sebloss** [comment]
Just import your text as bitmap. Done
Generate it with Blender for example.
You'll be able to add some subtle animations
