### ISSUE TITLE
Natron keep crashing - probably QFileSystemWatcher or FileSystemModel

### ISSUE THREAD

**Issue by Phantom-Studio** [MrKepzie/Natron#826]
![natron_crash_v01](https://cloud.githubusercontent.com/assets/13329038/9149727/775f4b02-3db7-11e5-8451-1db053fefc3c.jpg)

Hi all,

I have done a comp for a still image (5000x2811p), all read nodes are .exr.
Nothing fancy, I use to do comp like this with Natron.

But Natron, keep crashing each time. Is there a way to debbug please?
The only indication I get is in the Output Window (see attachment).

That's why I think the bug is linked to a bad server adress (/Phantom-sv-03 instead of //Phantom-sv-03) in QFileSystemWatcher and FileSystemModel.

I'm using a 2.0 snapshot of 1 week about (for the moment I'm unable to download the last snapshot to give it a try).

Just let me know if you need something else.
Thanks in advance.

Regards.

Jonathan

**Comment by MrKepzie** [comment]
You can download snapshots here http://downloads.natron.fr/Windows/snapshots/64bit/

The warnings in the terminal are not what is making it crash, it's just a misc thing. 
When does it crash exactly ? Can you make a video ?

**Comment by MrKepzie** [comment]
This is probably fixed by now. We will re-enable snapshots on Windows next week, we've made massive changes to the windows build and it is now using the same installer and update mechanism as on Linux.
