### ISSUE TITLE
Provide release source tarballs

### ISSUE THREAD

**Issue by minijackson** [MrKepzie/Natron#827]
Hi! I'm creating an ebuild file for Natron (basically a config file for building on Gentoo) and I noticed that the source tarballs provided by GitHub does not include the submodules neither on the releases panel nor on the main page. So I wondered if you could provide the release source tarballs in some way (e.g. on the Natron website) to help packaging ?

**Comment by olear** [comment]
No disrespect, but is it that hard to add one git command in the ebuild? :)

**Comment by minijackson** [comment]
Didn't think about that -_-"
But even though, cloning is slow (especially in this case). Zipping the project, distribute it and downloading it would be faster than only cloning this project.

**Comment by olear** [comment]
Understand you situation, been packaging for many years ;)

I will make a note and (try to) remember to make tarballs on tags.

**Comment by minijackson** [comment]
Thank you!

**Comment by devernay** [comment]
Just make tags, github handles the tarballs

**Comment by minijackson** [comment]
Yes, but github doesn't include the submodules in them.

**Comment by devernay** [comment]
You're right. I'll prepare a super tarball for the release.
Do you think openfx-misc openfx-io and openfx-arena should be distributed as separate packages? (They can be used with other OFX hosts)

**Comment by minijackson** [comment]
The fact that they can be used with other OFX hosts makes me think that way. Besides, I already have some ebuild files for their git version (if you're interested in them, please tell me).

**Comment by olear** [comment]
Note that on Linux the only openfx "alternative" is Nuke as far as I know, and if you want the plugins to work on Nuke you need to build against CentOS5+GCC 4.1.2.

And as a final note, do not build openfx-arena against ImageMagick supplied with Gentoo.

**Comment by devernay** [comment]
As long as the plugins don't use dynamic librairies, we don't care about the centos+GCC Nuke recommendations (openfx is a pure C API, and the C ABI hasn't changed since gcc 1.x)
I guess the Linux snapshot build script is the best place to start from, but I can't find it in the repository. @olear any idea where to look at?

**Comment by minijackson** [comment]
@olear I built openfx-arena "as-is" (like the other "openfx-*"), so probably against the system ImageMagick and it seems to work fine.

**Comment by olear** [comment]
@devernay:
I just noted that the plugins built on Gentoo won't work on Nuke, so they are only useful for Natron.

Linux build script: https://github.com/olear/natron-linux

@minijackson: They won't work as expected.

**Comment by devernay** [comment]
@olear would you agree to put the Linux build scripts in the main repo with the others?
The compatibility problems with Nuke (which Nuke version) are very probably just a matter of dynamic libraries.
 This is a well known problem with the dso-based plugin system, and cand either be solved by making sure the libraries used by the plugin use different symbols than those used by Nuke (eg by putting them is a different namespace if they are C++), or by linking them statically into the plugin. 
Do you have any hint on which library causes problems? 
I had similar problems with tuttleofx, which uses lots of libraries, some conflicting with Nuke or natron

**Comment by olear** [comment]
They must be built against GCC 4.1.2 to be compatible with Nuke, it's not an recommendation, just try yourself.

Where the build scripts are don't matter to me.

Nuke (and better Linux) compat is on the TODO, but requires moving from CentOS6 to CentOS5, https://github.com/olear/natron-linux/issues/25, not an high priority at the moment (since this does not affect Natron).

I can of course provide Misc and IO builds compatible with Nuke if wanted, but as an alternative to the existing builds.

**Comment by olear** [comment]
Should I just put the scripts in tools/linux, and do a pull request? (do you want history? goes back to 0.9.3)

**Comment by olear** [comment]
Regarding packaging, added a RPM spec for openfx-arena for how it should be built/packaged by distros, should be easy to adapt (ebuild/pkgbuild/slackbuild whatever ...)

**Comment by olear** [comment]
https://github.com/MrKepzie/Natron/releases/tag/2.0.1
