### ISSUE TITLE
[WEB] error https...

### ISSUE THREAD

**Issue by manuelsongokuh** [MrKepzie/Natron#831]
hello
https://natron.fr/
i clicked from https://github.com/MrKepzie/Natron
is error or security..
firefox
![https-natron-error](https://cloud.githubusercontent.com/assets/12126929/9174578/f7492e76-3f80-11e5-8cb0-2f8036689a44.png)
chromium
![https-natron-error1](https://cloud.githubusercontent.com/assets/12126929/9174587/0a7e55f2-3f81-11e5-9783-50a1dad0e540.png)

**Comment by olear** [comment]
Only downloads.natron.fr and forum.natron.fr supports https.

**Comment by MrKepzie** [comment]
please do not open issues here unrelated to the software

**Comment by manuelsongokuh** [comment]
Oh sorry so much..
