### ISSUE TITLE
not good: picker for chromekey..(title name..dont know, yet)

### ISSUE THREAD

**Issue by manuelsongokuh** [MrKepzie/Natron#832]
hello

this is not BUG, it's error wip (work in progress) for chromekey....why?
when i add node read movie, there is green or blue screen, when i use picker click "blue" (my case)
blue is detected, this is OK, but i again picker click result color is GRAY..this mean: GARY is not original color (from node read), GRAY is AFTER result of picker..this is error or bad progress..
first of all , i'm sorry for my english and maybe i'm not goot explain..
then i can screen record a moment..

**Comment by manuelsongokuh** [comment]
now it uploading...10 min...wait.

when use picker for chromekey needs to keep image (read node) original.. not grey or black..
do you understand what i mean..?

**Comment by manuelsongokuh** [comment]
https://mega.co.nz/#!SgMkBJiC!TyHzsafej92_jvUmWhXc14BRM-tMSLevzOC0-59JhY4

**Comment by devernay** [comment]
This looks normal to me: the picked ccolor is the one you see in the viewer. There are.many solutions to this (use a second viewer, use the wipe tool, etc)

**Comment by manuelsongokuh** [comment]
Ok, this mean that i do add time free ok? I believe natron will be best save time in work in progress, then im ok for chose from team develop. Natron goes the best
