### ISSUE TITLE
my error or the bug....viewer zoom

### ISSUE THREAD

**Issue by manuelsongokuh** [MrKepzie/Natron#834]
hello
natron: 41d953ae9fb859efe45038d319c4b58c7baedc4e
zoom under mouse scroll wheel, result bad show..
see screen record:
https://mega.co.nz/#!3ldmBI6a!V_hOVnvY1X-MrHybPBz4BCzFRXuiowAIsDC6oD_Ulwc

file ntp: http://www.pastefile.com/rLM4v0
(this files will available in 1 week)

**Comment by MrKepzie** [comment]
I'm not able to reproduce that

**Comment by manuelsongokuh** [comment]
ok, how i can find problem from? natron -debug ?

**Comment by manuelsongokuh** [comment]
maybe it problem from node roto.. see screen record:
https://mega.co.nz/#!Dot01ZqY!79-a0Bi0EWB2ywzgaX1-inpn6RaMcBpG9t2OPgEbeqY

file ntp:
https://mega.co.nz/#!LlchXYJI!TGV5zx0a05z3Dnd6r5lumlq7dztKLoqi8R4fjk2ofTA

terminal, but not reproduce error for viewer...
/Natron2> ./Natron -debug
Natron Version 2.0.0
Copyright (C) 2015 the Natron developers
>>>Use the --help or -h option to print usage.<<<
Attempt to read an OpenColorIO configuration but the configuration directory/usr/share/OpenColorIO-Configsdoes not exist.
Attempt to read an OpenColorIO configuration but the configuration directory/home/gokuh/Natron2/bin/../Resources/OpenColorIO-Configsdoes not exist.

**Comment by manuelsongokuh** [comment]
i did try remove fglrx (close source driver AMD), installed last MESA radeon (open source), result same problem strange in viewer...

**Comment by manuelsongokuh** [comment]
there is other screen record for 4 viewer result problem bad view into roto..
https://mega.nz/#!yolEzaYT!LCIw80u5NwtQ1G01tryBr4RVnkKuZOcqvVeas-d86TU

**Comment by MrKepzie** [comment]
Ok, I figured what's wrong, fix incoming

**Comment by manuelsongokuh** [comment]
ok, not worry for wrong :-) i help you for natron STABLE! :+1:

**Comment by manuelsongokuh** [comment]
i did download latest snapshot 1d55118779b2241f139eb84d576ad38746b03fb8.
i dont see bug to viewer!, i believe @MrKepzie did fixed?! WOW...
i think will be close here issue? the best @MrKepzie will close here for confirm ok?
i can start my new tutorial for natron..
