### ISSUE TITLE
Add keystrokes for many actions (especially in the viewer)

### ISSUE THREAD

**Issue by devernay** [MrKepzie/Natron#836]
for example, see
-  http://help.thefoundry.co.uk/nuke/8.0/content/user_guide/hotkeys/hotkeys.html
- http://help.thefoundry.co.uk/nuke/9.0/#appendices/appendixb/hotkeys_studio.html

**Comment by manuelsongokuh** [comment]
hello
i did send the cool information for keyboard for helpfully:
http://waldobronchart.github.io/ShortcutMapper/

**Comment by devernay** [comment]
This issue was moved to NatronGitHub/Natron#111
