### ISSUE TITLE
MaintenanceTool ?!

### ISSUE THREAD

**Issue by rcspam** [MrKepzie/Natron#838]
Hey all,
When will we see the comeback of MaintenanceTool ?

**Comment by olear** [comment]
Comeback? It never left... Did a rename to NatronSetup, but that's it.

**Comment by rcspam** [comment]
:)

**Comment by rcspam** [comment]
Old habits are emptying the reflection ;)

**Comment by olear** [comment]
btw, running 'Natron -update' starts the maintenance tool.

**Comment by rcspam** [comment]
Proof is done! this issue was important to learn some things
