### ISSUE TITLE
blocked to start natron..(splash screen)

### ISSUE THREAD

**Issue by manuelsongokuh** [MrKepzie/Natron#839]
natron is 41d953ae9fb859efe45038d319c4b58c7baedc4e.
file ntp:   http://www.pastefile.com/wx1omR
(this files will available in 1 week, from today data)

**Comment by olear** [comment]
The project want net.fxarena.openfx.Distort, I guess you don't use that plugin anymore. And some of the plugins may have changes param names since then.

**Comment by manuelsongokuh** [comment]
(this is duplicate https://github.com/olear/openfx-arena/issues/162 )
@olear of course for changed code fromold  plug to new plug.
thanks
