### ISSUE TITLE
The NodeGraph does not refresh

### ISSUE THREAD

**Issue by MarcRose** [MrKepzie/Natron#841]
Google Translate:
The display of the node graph does not refresh all the time ...
Thank you

https://youtu.be/JCNtgPXxECs

L'affichage du node graph n'est pas remi à jour tout le temps...
Merci.

OSX 10.9.5
Proc : i5 2.5Ghz
Memory : 8Go
Vidéo card : Intel HD Graphics 4000

**Comment by manuelsongokuh** [comment]
what is version of Natron?
youtube is available..so i cant to see your video...

**Comment by devernay** [comment]
Can't access this video, 
This is a known bug, but we're having difficulties reproducing it. Do you know how we can reproduce this?

Le lien vers la vidéo ne fonctionne pas.
Ce bug est connu, mais nous n'arrivons pas à le reproduire systématiquement, est-ce que vous savez le faire apparaître ?

**Comment by MarcRose** [comment]
Unfortunately I deleted the video, because the bug was known: /.
With the latest Snapshots (Natron-snapshots-9329d830ca493fbbc7685f2e5b2221bdb8a7cbec.dmg 2015-Aug-15 10:13:14) I have not been able to reproduce the bug, I will continue the recordings and as soon as I come again unto you.

Malheureusement j'ai effacé la vidéo, car le bug été connu :/.
Avec le dernier Snapshots (Natron-snapshots-9329d830ca493fbbc7685f2e5b2221bdb8a7cbec.dmg  2015-Aug-15 10:13:14 ), je n'ai pas réussi à reproduire le bug, je vais continué les enregistrements et dés que je l'ai je reviens vers vous.

**Comment by MarcRose** [comment]
Here is the new link
https://youtu.be/JCNtgPXxECs

**Comment by manuelsongokuh** [comment]
maybe will be fix in future port in opengl, but not sure, see issue
https://github.com/MrKepzie/Natron/issues/815
ok?

**Comment by MrKepzie** [comment]
It should now refresh more often. No need to re-open if it arises again in the future, we will change the implementation of the node graph

**Comment by MarcRose** [comment]
Ok ! Thank you !
