### ISSUE TITLE
Natron wants 70+ GB of RAM ?

### ISSUE THREAD

**Issue by azerupi** [MrKepzie/Natron#842]
![natron](https://cloud.githubusercontent.com/assets/7647338/9276088/320959ea-42a2-11e5-8253-412eabb44fcc.png)

I am on the latest snapshot for OS X. 
```
Natron-snapshots-3eadd12bae285dd7df06309cba9f2230c15994fa.dmg	2015-Aug-14 04:20:15
```
Is it a known problem?

**Comment by olear** [comment]
Does this happen in a specific project? Is this a project from Natron v1? Have you cleaned your config/cache since moving from Natron v1? Can you make a simple project that reproduces the error? Have you tried the project in question on another computer?

Sorry for many questions :)

**Comment by azerupi** [comment]
> Sorry for many questions :)

No worries, I know how hard it is to debug for someone else ;)

I did indeed just update from a v1 that I built myself a couple of months back. I haven't cleaned the cache / config. What files should I delete for that?

I should have mentioned that Natron doesn't actually start, it hangs on the splash screen because I run out of memory and I have to kill it.c

**Comment by devernay** [comment]
When you kill the process, do you get a backtrace (in the "report to apple" windows' details)?
You can paste this backtrace in http://gist.github.com and paste the resulting link here

**Comment by azerupi** [comment]
No backtrace, apparently Natron is able to quit gracefully when I "force quit".
I am downloading the latest snapshot right now to see if there is any difference.

**Comment by azerupi** [comment]
I finally found the cache `Library/Cache/INRIA/Natron/...` I deleted it. And now it works.
So the problem is that Natron 2 doesn't like cache from old versions.

Could Natron possibly detect old cache and remove it itself?

**Comment by olear** [comment]
Due to changes in v2 there are some problems when using old cache/config (from v1 or earlier snapshots), at the moment the best is to clear the config/cache manually.

**Comment by azerupi** [comment]
Yeah no problem :)
I was just wondering if Natron could check for that problem before it starts, or the installer could? Isn't there anything in the cache that reveals for what version it was created?

If Natron could do that, it would streamline the upgrade when v2.0 comes out as stable release

**Comment by MrKepzie** [comment]
Cache is now cleaned completely between 2 major versions of Natron
