### ISSUE TITLE
Fullscreen on OS X with maximize button

### ISSUE THREAD

**Issue by azerupi** [MrKepzie/Natron#844]
It would be really nice to allow fullscreen on OS X with the green window button (maximize). It's the default behaviour of OS X since Yosemite I think.

It's not very important though, because you can go fullscreen with `option+S`. But it would be a nice little enhancement :)

**Comment by MrKepzie** [comment]
Not really possible on Qt4 if I remember well when we looked for it

**Comment by devernay** [comment]
hackable, but better wait for Qt5 (the hack would have to be removed when going to Qt5)

**Comment by MrKepzie** [comment]
In El Capitan it is now done by the OS automatically.
