### ISSUE TITLE
build system: move to C++11 compilers on all platforms (OSX, Windows, Linux)

### ISSUE THREAD

**Issue by devernay** [MrKepzie/Natron#845]
We can benefit from C++11 if we upgrade the compilers for Natron (and maybe plugins):
- OS X build should use clang-3.4 from macports
  - sudo port install clang-3.4
  - sudo port select --set clang mp-clang-3.4 (so that clang and clang++ point to that version)
  - qmake -r -spec unsupported/macx-clang CONFIG+=c++11 ...
  - and for the plugins, something like "make CXX=clang++ ..." should do
- Windows build should at least use VS2012 (or GCC 4.8.1)
- Linux build (on centos) should use at least GCC 4.8.1. Is there a backport to CentOS 6.2 ? (@olear?)
- Travis builds are already using c++11 compilers (found a backport of gcc 4.8.1 to ubuntu 12.04)

Then we'll be able to write more modern C++ code.

**Comment by olear** [comment]
I can upgrade to 4.8.2, but I need to test first.

**Comment by olear** [comment]
Linux build system has now been upgraded to GCC 4.8.2 (as defined by CY2015/CY2016), so should be ready when needed.

**Comment by olear** [comment]
This can be closed, we use 4.8.5 or higher on the build system.
