### ISSUE TITLE
g++: error: /usr/lib/libcairo.a: No such file or directory

### ISSUE THREAD

**Issue by azerupi** [MrKepzie/Natron#849]
When I build, I get this error:
```
g++ -Wl,-O1,--sort-common,--as-needed,-z,relro -Wl,-O1 -o NatronRenderer NatronRenderer_main.o    -L/usr/lib -L/home/azerupi/Programming/Natron/target/Renderer/../Engine/ -lEngine -L/home/azerupi/Programming/Natron/target/Renderer/../HostSupport/ -lHostSupport /usr/lib/libcairo.a -L/usr/lib -lpython3.4m -ldl -lutil -lm -Xlinker -export-dynamic -lboost_serialization -lpyside.cpython-34m /usr/lib64/libpython3.4m.so -lexpat -lpixman-1 -lfontconfig -lfreetype -lshiboken.cpython-34m -lQtNetwork -lQtCore -lpthread 
g++: error: /usr/lib/libcairo.a: No such file or directory
```
I do have cairo installed but don't seem to have a `libcairo.a`. In both `/lib` and `/usr/lib` I have a `libcairo.so` though. I have tried to modify the `config.pri` with not much luck.

**Comment by devernay** [comment]
we link with static cairo to avoid linking NatronRenderer with X11 libraries, and to avoid this plugin.
If a static version of cairo is not available on your distribution (it's usually part of the "devel" packages), just fallback to using pkgconfig for caire.
Add in your config.pri:

         cairo:     PKGCONFIG += cairo

**Comment by azerupi** [comment]
Thanks, I am rebuilding now. Will let you know if that fixed it :)

**Comment by azerupi** [comment]
It did not solve the issue :(

**Comment by olear** [comment]
Distros don't ship static libraries, build Cairo from source with --enable-static

**Comment by azerupi** [comment]
Thanks @olear I got it to work with that!
