### ISSUE TITLE
Property panels open up small when Floating panel are active

### ISSUE THREAD

**Issue by sirdavid32** [MrKepzie/Natron#850]
Hi, If I choose to have floating panels on the layout, everytime I CTRL+double click a node on the node graph, the property panel for that item appears for the first time very small. (See atachment) after fixing it´s lenght and height the panel re-invokes are normal "fixed" sized.

If you close the app, and re-open it, the problem persists.
I´m using the latest snapshot.
![small](https://cloud.githubusercontent.com/assets/11066585/9310266/671cfed2-44d4-11e5-9add-67ab2b87ca5e.jpg)

**Comment by MrKepzie** [comment]
fixed

**Comment by sirdavid32** [comment]
Thank you so much! Today´s snapshot fixed the floating pannels issue. :D
