### ISSUE TITLE
Closing Project settings panel won´t open back if invoked from the menu

### ISSUE THREAD

**Issue by sirdavid32** [MrKepzie/Natron#851]
Hi, if I close the project settings from the property bin (so I can have it as a floating panel later), and then I want to re open this property dialogue from the OPTIONS menu (Project settings "S") it won´t open. Thus becomes impossible to re-edit the project settings because no panel for that opens.

**Comment by MrKepzie** [comment]
Cannot reproduce here

**Comment by devernay** [comment]
What Natron version, please?

**Comment by devernay** [comment]
Can't reproduce with current snapshot on OSX

**Comment by sirdavid32** [comment]
21-08-2015 snapshot. I tested it also on Linux. Close the Project Setting property panel, and recall it from the menu. Doesn´t open it back again. (ever). Can´t even invoke it back to a floating panel with the "S" over the compositing tree area of the layout.

**Comment by olear** [comment]
If you close the properties panel you won't get any properties ;)

Just readd a properties bin and all is good.

**Comment by MrKepzie** [comment]
Can you post a video showcasing the bug? I fail to reproduce on linux
