### ISSUE TITLE
Enhancement: Hotkey to select B side input

### ISSUE THREAD

**Issue by nicholascarroll** [MrKepzie/Natron#852]
With Wipe enabled, you can select the A side using the number keys. Would be good if you could also select the B side using the number keys + modifier key. Suggested key is Shift.

EXAMPLE USER PROCEDURE
Click in the viewer and press the W key. Press the number key of the input that you want on the A side. Now *hold Shift* and press the number key for the input you want on the B side.

**Comment by MrKepzie** [comment]
See https://github.com/MrKepzie/Natron/commit/1f3b8893279a55231c98cec4475a8398a1ce196b
From now on:
- If you are hovering the mouse on the viewer, it automatically enables wipe and acts as though you are switching the input B
- If you've got the cursor anywhere else, it just switches the active A input of the viewer

**Comment by nicholascarroll** [comment]
Ouch! Aie! You've removed the option to disable Automatically Enable Wipe. So now the user can't simply change inputs using numkeys while the mouse is over the viewer without enabling wipe, they can't select A and B side of wipe using keyboard commands. Yet there's no efficiency gained by automating wipe anyway!

**Comment by MrKepzie** [comment]
I've brought back the option in https://github.com/MrKepzie/Natron/commit/9f3f56094d13b6d36666b56c9109d10963ecf58c <https://github.com/MrKepzie/Natron/commit/9f3f56094d13b6d36666b56c9109d10963ecf58c>
Basically you can now disable the auto wipe even if the mouse is hovering the viewer. By default it is enabled.

**Comment by nicholascarroll** [comment]
Hey Great thanks Mr Kepzie. Keep up the good work.
