### ISSUE TITLE
Plugin's output to stdout

### ISSUE THREAD

**Issue by nitsch** [MrKepzie/Natron#853]
Is there a way to make a plugin's output to stdout appear on some console when it is run in Natron?

I tried starting Natron fom the command line and that does output something on startup. But the strings that OFX plugins write to stdout do not appear there.

**Comment by olear** [comment]
I use stdout for debugging plugins etc, the output works as it should here(?)

**Comment by nitsch** [comment]
This only seems to affect the official releases (tested on Windows and Linux). In the current snapshots it seem to work just fine. Oh well ...

**Comment by olear** [comment]
Works on v1 here:
![screenshot-17](https://cloud.githubusercontent.com/assets/7461595/9356157/0e2e7a4c-467f-11e5-8e16-e3fba3a199c3.png)
![screenshot-18](https://cloud.githubusercontent.com/assets/7461595/9356222/9949b920-467f-11e5-8ab0-3cd2527d87dd.png)

Output on Windows didn't work properly until a v2 snapshot, but on Linux it should just work.
