### ISSUE TITLE
GUI improvement

### ISSUE THREAD

**Issue by budislav** [MrKepzie/Natron#857]
Natron GUI could be clearer and cleaner. Compare.
![natron ui](https://cloud.githubusercontent.com/assets/3619927/9375226/679a9a00-46fe-11e5-9a8e-4fec9f25acde.jpg)
![untitled-1](https://cloud.githubusercontent.com/assets/3619927/9375227/6b5f91f4-46fe-11e5-9a59-5f84de2893ba.jpg)

**Comment by blackearth2014** [comment]
This should be a Theme option. The top markup image looks more like a Photoshop clone than a true compositor. In my opinion, an apps GUI should never get in the way of practicals and process.

**Comment by mamarilmanson** [comment]
yep... it's very adobe... but anyway... if improves "eyesight" why not? :D

**Comment by azerupi** [comment]
I too think the GUI should have some love, with special attention to the properties panel. I like the "color bar" idea. It could be useful to see what nodes it belongs to with a quick look.

> This should be a Theme option

@blackearth2014 does Natron support themes? I cloned the repo to play with the GUI but if it supports themes I don't even have to build Natron every time I change something.

**Comment by blackearth2014** [comment]
I don't think it supports Themes as of yet. Its not a major priority for the developers. I am more concern about stability and nodes that get the job done faster and efficiently. If anyone know anyone who knows how to code, this could be a great asset to all of us. The developers can spend more time, well developing.

**Comment by azerupi** [comment]
I can code, but not on the same scale as Natron ;) Maybe I will see if I can do some GUI improvements after my exams (September)

**Comment by MrKepzie** [comment]
We have already tons of requests and ideas for Gui enhancement but no time for it though. Any developer is welcome to contribute.

**Comment by azerupi** [comment]
@MrKepzie That is great to hear, is there some centralized place where all the ideas are? So that new developers could quickly see what people wish and what they could implement depending on their skills

**Comment by MrKepzie** [comment]
No, currently this is by e-mail only, but we should create a section for that on the forums. I just don't have time to create it right now

**Comment by azerupi** [comment]
Ok thanks :)

**Comment by olear** [comment]
What needs to be done:

- start from scratch with the stylesheet
- pick a good qt style (plastique/fusion)
- remove hardcoded checkbox (and more?) and other color stuff

I'm willing to help, but other things have higher priority.

Just make a new thread/topic on the forum for discussion/progress on this issue.

**Comment by azerupi** [comment]
I will, but I first need to concentrate on my exams. I will have more time in September.

I have played a little bit with the stylesheet today and it seems fairly easy to tweak once you found the correct widget. So I will be able to help out. I will contact you or create a thread on the forum when I finish my exams so that we can discuss it, does that sound good to you?

**Comment by olear** [comment]
Sounds good.
