### ISSUE TITLE
Sony RAW Import

### ISSUE THREAD

**Issue by filmhome** [MrKepzie/Natron#859]
Please enables Sony RAW files (MXF / S log 2) to import.

Great program, thank you.

**Comment by MrKepzie** [comment]
Have you tried in the Natron 2.0 snapshots ?

**Comment by filmhome** [comment]
No.

**Comment by filmhome** [comment]
Natron 2.0 snapshot don´t work

**Comment by MrKepzie** [comment]
Natron-f8f18f0150c5a7e8f2a806e526530bc21254f681.zip <http://downloads.natron.fr/Windows/snapshots/64bit/Natron-f8f18f0150c5a7e8f2a806e526530bc21254f681.zip>

Have you tried on this one ?

**Comment by filmhome** [comment]
Thanks , but I am on mac.

**Comment by olear** [comment]
https://downloads.natron.fr/Mac/snapshots/

**Comment by filmhome** [comment]
Thank you olear, as I have already written, Snapshot 2.0 is not working for importing Sony Raw files (MXF).

**Comment by olear** [comment]
ffmpeg should be able to decode MXF, but maybe the gpl version is needed (or something else?).

Will do some tests with MXF.

**Comment by devernay** [comment]
Can you. please provide a video sample? It should work with the current version so we have to check what is wrong

**Comment by manuelsongokuh** [comment]
if natron uses ffmpeg, then can test:
ffplay -i filename-mxf
this mean if ffplay worked then file mxf worked as fine, i have file mxf from canon xf 105..
other best investigation:
ffmpeg -i filename.mxf
there are output information for stream 0, stream 1, audio 0, audio1, also will be output the error message..

if ffplay worked and ffmpeg worked with mxf, natron not work then natron has problem..
this is nature theory for investigation base ok?

my mxf worked with natron, and worked with ffmpeg and ffplay...
@filmhome : you can try command: ffplay (player video), ffmpeg read the file information precise (ffmpeg - i filename.mxf will be helpfully for developers)

my little information here. good night!

**Comment by MrKepzie** [comment]
Without a video sample we may not be able to help unfortunately. Please provide one

**Comment by filmhome** [comment]
Here is the sample. Sorry for the delay.
https://www.dropbox.com/s/24rfffr9r20um70/Test%20sony%20F5%20RAW.zip?dl=0

@manuelsongokuh 
Sorry i am a user not a programmer. I did not understand a single word of what you wrote.

**Comment by MrKepzie** [comment]
FFplay, VLC, Blender, Nuke are unable to read this file too.

**Comment by MrKepzie** [comment]
F55RAWSQ is unrecognised by ffmpeg. Strangely, ffprobe is not even able to report the codec name, so 
this codec is completely unknown of ffmpeg.

As long as it's not working in ffmpeg we are not going to add specific development for that particular format.

**Comment by devernay** [comment]
It's not that the codec is unknown (ffmpeg reports the ID of unknown codecs), it's that there isn't any codec information in the video stream. It's only in the metadata, and it's probably a closed and proprietary codec.
Try with another codec (e.g. XAVC or AVC, which are H.264)
