### ISSUE TITLE
i contribute for linux debug under terminal : Natron -debug

### ISSUE THREAD

**Issue by manuelsongokuh** [MrKepzie/Natron#860]
hello
i dont know if my little contribute is need or good..?
the original natron.sh:
if [ "$1" == "-debug" ]; then
export SEGFAULT_SIGNALS="all"
  catchsegv $DIR/bin/Natron.debug -style fusion "$@"
else
  $DIR/bin/Natron -style fusion "$@"
fi

i added little code for debug:
if [ "$1" == "-debug" ]; then
echo -e "\e[5m\e[31mDEBUG\e[25m"
  export SEGFAULT_SIGNALS="all"
  catchsegv $DIR/bin/Natron.debug -style fusion "$@"
else
  $DIR/bin/Natron -style fusion "$@"
fi
echo -e "\e[39m"
result color red for debug, and blink for "debug"..

this is for unix-like..

**Comment by Ambassy** [comment]
I guess you have to submit this in the«pull request» directory, not in issues.

**Comment by MrKepzie** [comment]
Nice, but we don't need to display "DEBUG" when the user explicitly types in "-debug"

**Comment by olear** [comment]
Been trying to deprecate the shell wrapper anyway. The shell wrapper is now only used to enable "-debug" and force a qt style. Will be removed when breakpad and style issues has been resolved.
