### ISSUE TITLE
../Resources/OpenColorIO-Configsdoes not exist.

### ISSUE THREAD

**Issue by manuelsongokuh** [MrKepzie/Natron#861]
it's normal or i have problem of installation of natron?
Natron Version 2.0.0
Copyright (C) 2015 the Natron developers
>>>Use the --help or -h option to print usage.<<<
Attempt to read an OpenColorIO configuration but the configuration directory/usr/share/OpenColorIO-Configsdoes not exist.
Attempt to read an OpenColorIO configuration but the configuration directory/home/gokuh/Natron2/bin/../Resources/OpenColorIO-Configsdoes not exist.

natron at commit 06d800797df8991ad06b50708edbd3469f6b8185.

**Comment by olear** [comment]
Just warnings, Natron searches in /usr/share and in ../Resources, but finds them in ../share. If not you would notice if the color profiles was missing ;)

**Comment by manuelsongokuh** [comment]
I will need install in usr for root?

**Comment by olear** [comment]
No need to do anything. Natron searches several locations for config files, it just warns if no folder was found.

Your config files are in /where/you/installed/Natron/share/OpenColorIO-Configs

Just ignore ;)

**Comment by manuelsongokuh** [comment]
ok, /natron/share*opencolorio-configs, there is ok? i will close here ok?
