### ISSUE TITLE
Button toTurn on/off particular nodes overlays.

### ISSUE THREAD

**Issue by Ambassy** [MrKepzie/Natron#862]
Many time we use to deal with many transformation nodes. All of them have overlays in the viewer.  When i right click in the viewer and check «hide overlays» they all disappear while i still need to work on particular node at a time.  Can we have button in the nodes settings to turn on/off its overlay whithout hiding all overlay of all nodes please?  Eg: my script contaim 6 transform nodes,4 corner pin,two transform masked. In this case it's hard to know which overlay of which node,then i need to turn of some nodes overlays.That's why this feature is important.

**Comment by MrKepzie** [comment]
This was already discussed before, you can just open/close the settings panel of the node when needed. We are not going to add another button which will make it more complex for people picking up a project if some checkbox is not checked.
