### ISSUE TITLE
Making keyboard shortcuts independent of the keyboard language

### ISSUE THREAD

**Issue by devernay** [MrKepzie/Natron#864]
For some keyboards, keys that are available without mofifiers on US QWERTY may require modifiers on other keyboards (e.g. UK QWERTY or French AZERTY). A good example is all numbers, which are shifted on AZERTY.
As a result, a default shortcut such as ctrl-3 will never work on a French Keyboard.
We have to add a "ignore Alt and Shift state" option to each shortcut (in which case the "alt" and "shift" modifier options are disabled).
Other examples are ">", "?", ".", "/", "+", "_", "\*" which are shifted on the French keyboard, or the backslash which requires Alt+Shift on the French Mac keyboard.
We should also check that it's OK on French keyboards on windows/linux (what does the infamous "AltGr" key translate to? A modifier? if yes, it should be ignored too).
@MrKepzie you did the shortcuts editor, so I'm assigning this to you.
See also another shortcuts-related issue: https://github.com/MrKepzie/Natron/issues/741 (which would help user learn shortcuts: they *have* to be visible in the UI, not only in the editor, so that users switch from mouse-clicking to using shortcuts)

**Comment by MrKepzie** [comment]
You can now add multiple shortcuts to an action. This is a less complicated alternative to adding a whole system of keyboard layouts in Natron.
