### ISSUE TITLE
Natron fails to build 

### ISSUE THREAD

**Issue by thomassross** [MrKepzie/Natron#867]
I'm trying to build on Debian Linux Testing, using the instructions in `INSTALL_LINUX.MD`.
It fails on this command:

    thomas@thomas-debian:~/Desktop/Natron/build/build$ qmake -r ~/Desktop/Natron/build/natron-1.2.1/
    Project MESSAGE: Compiling in RELEASE mode.
    Reading /home/thomas/Desktop/Natron/build/natron-1.2.1/HostSupport/HostSupport.pro [/home/thomas/Desktop/Natron/build/build/HostSupport]
    WARNING: Failure to find: ../libs/OpenFX/HostSupport/src/ofxhBinary.cpp
    WARNING: Failure to find: ../libs/OpenFX/HostSupport/src/ofxhClip.cpp
    WARNING: Failure to find: ../libs/OpenFX/HostSupport/src/ofxhHost.cpp
    WARNING: Failure to find: ../libs/OpenFX/HostSupport/src/ofxhImageEffect.cpp
    WARNING: Failure to find: ../libs/OpenFX/HostSupport/src/ofxhImageEffectAPI.cpp
    WARNING: Failure to find: ../libs/OpenFX/HostSupport/src/ofxhInteract.cpp
    WARNING: Failure to find: ../libs/OpenFX/HostSupport/src/ofxhMemory.cpp
    WARNING: Failure to find: ../libs/OpenFX/HostSupport/src/ofxhParam.cpp
    WARNING: Failure to find: ../libs/OpenFX/HostSupport/src/ofxhPluginAPICache.cpp
    WARNING: Failure to find: ../libs/OpenFX/HostSupport/src/ofxhPluginCache.cpp
    WARNING: Failure to find: ../libs/OpenFX/HostSupport/src/ofxhPropertySuite.cpp
    WARNING: Failure to find: ../libs/OpenFX/HostSupport/src/ofxhUtilities.cpp
    Reading /home/thomas/Desktop/Natron/build/natron-1.2.1/Engine/Engine.pro [/home/thomas/Desktop/Natron/build/build/Engine]
    WARNING: Failure to find: ../libs/SequenceParsing/SequenceParsing.cpp
    WARNING: Failure to find: ../libs/SequenceParsing/SequenceParsing.h
    WARNING: Failure to find: ../libs/OpenFX/include/ofxCore.h
    WARNING: Failure to find: ../libs/OpenFX/include/ofxDialog.h
    WARNING: Failure to find: ../libs/OpenFX/include/ofxImageEffect.h
    WARNING: Failure to find: ../libs/OpenFX/include/ofxInteract.h
    WARNING: Failure to find: ../libs/OpenFX/include/ofxKeySyms.h
    WARNING: Failure to find: ../libs/OpenFX/include/ofxMemory.h
    WARNING: Failure to find: ../libs/OpenFX/include/ofxMessage.h
    WARNING: Failure to find: ../libs/OpenFX/include/ofxMultiThread.h
    WARNING: Failure to find: ../libs/OpenFX/include/ofxNatron.h
    WARNING: Failure to find: ../libs/OpenFX/include/ofxOpenGLRender.h
    WARNING: Failure to find: ../libs/OpenFX/include/ofxParam.h
    WARNING: Failure to find: ../libs/OpenFX/include/ofxParametricParam.h
    WARNING: Failure to find: ../libs/OpenFX/include/ofxPixels.h
    WARNING: Failure to find: ../libs/OpenFX/include/ofxProgress.h
    WARNING: Failure to find: ../libs/OpenFX/include/ofxProperty.h
    WARNING: Failure to find: ../libs/OpenFX/include/ofxSonyVegas.h
    WARNING: Failure to find: ../libs/OpenFX/include/ofxTimeLine.h
    WARNING: Failure to find: ../libs/OpenFX/include/nuke/camera.h
    WARNING: Failure to find: ../libs/OpenFX/include/nuke/fnOfxExtensions.h
    WARNING: Failure to find: ../libs/OpenFX/include/nuke/fnPublicOfxExtensions.h
    WARNING: Failure to find: ../libs/OpenFX/include/tuttle/ofxReadWrite.h
    Reading /home/thomas/Desktop/Natron/build/natron-1.2.1/Gui/Gui.pro [/home/thomas/Desktop/Natron/build/build/Gui]
    WARNING: Failure to find: ../libs/OpenFX/include/ofxCore.h
    WARNING: Failure to find: ../libs/OpenFX/include/ofxDialog.h
    WARNING: Failure to find: ../libs/OpenFX/include/ofxImageEffect.h
    WARNING: Failure to find: ../libs/OpenFX/include/ofxInteract.h
    WARNING: Failure to find: ../libs/OpenFX/include/ofxKeySyms.h
    WARNING: Failure to find: ../libs/OpenFX/include/ofxMemory.h
    WARNING: Failure to find: ../libs/OpenFX/include/ofxMessage.h
    WARNING: Failure to find: ../libs/OpenFX/include/ofxMultiThread.h
    WARNING: Failure to find: ../libs/OpenFX/include/ofxNatron.h
    WARNING: Failure to find: ../libs/OpenFX/include/ofxOpenGLRender.h
    WARNING: Failure to find: ../libs/OpenFX/include/ofxParam.h
    WARNING: Failure to find: ../libs/OpenFX/include/ofxParametricParam.h
    WARNING: Failure to find: ../libs/OpenFX/include/ofxPixels.h
    WARNING: Failure to find: ../libs/OpenFX/include/ofxProgress.h
    WARNING: Failure to find: ../libs/OpenFX/include/ofxProperty.h
    WARNING: Failure to find: ../libs/OpenFX/include/ofxSonyVegas.h
    WARNING: Failure to find: ../libs/OpenFX/include/ofxTimeLine.h
    WARNING: Failure to find: ../libs/OpenFX/include/nuke/camera.h
    WARNING: Failure to find: ../libs/OpenFX/include/nuke/fnOfxExtensions.h
    WARNING: Failure to find: ../libs/OpenFX/include/nuke/fnPublicOfxExtensions.h
    WARNING: Failure to find: ../libs/OpenFX/include/tuttle/ofxReadWrite.h
    Reading /home/thomas/Desktop/Natron/build/natron-1.2.1/Renderer/Renderer.pro [/home/thomas/Desktop/Natron/build/build/Renderer]
    WARNING: target.path is not defined: install target not created
    
    Reading /home/thomas/Desktop/Natron/build/natron-1.2.1/Tests/Tests.pro [/home/thomas/Desktop/Natron/build/build/Tests]
    WARNING: Failure to find: google-test/src/gtest-all.cc
    WARNING: Failure to find: google-test/src/gtest_main.cc
    WARNING: Failure to find: google-mock/src/gmock-all.cc
    Reading /home/thomas/Desktop/Natron/build/natron-1.2.1/App/App.pro [/home/thomas/Desktop/Natron/build/build/App]
    WARNING: target.path is not defined: install target not created

`config.pri`:

    $ cat ../natron-1.2.1/config.pri 
    boost: LIBS += -lboost_serialization

I'm using `1.2.1` from [here](https://github.com/MrKepzie/Natron/releases/tag/1.2.1). What I think is happening is the submodules aren't initialized (but the release I downloaded isn't even a git repository)

Thanks,
Thomas.

**Comment by olear** [comment]
Use git to get the source (we will offer proper release source tarballs in v2+).

```
git clone https://github.com/MrKepzie/Natron
cd Natron
git submodule update -i --recursive
```
This will get the source to the latest v2 snapshot (you should target v2, v1 will not get any updates/fixes). The Linux documentation will also be updated to reflect changes on release.
