### ISSUE TITLE
Full SMPTE timecode values: Request for FFMpeg videos

### ISSUE THREAD

**Issue by blackearth2014** [MrKepzie/Natron#868]
Is it possible to get a full SMPTE timecode reading in the viewer when working with video and even still photography animation? I will be cutting my footage in my NLE and I want to composite some elements is in Natron. In my NLE, I have markers at certain frames in my timeline than I want to have a composite to take place.  If we have a SMPTE display of the input video will help speed up the vfx composition. In Natron's timeline and dope sheet, we can create the keyframes for each VFX as a guide. It will feel like round tripping accept its oneway.

![desertland inc](https://cloud.githubusercontent.com/assets/7956901/9496487/8f8c2378-4bde-11e5-827d-46b8ab474d21.png)

**Comment by devernay** [comment]
we have to look into this. We'll probably have to implement metadata support for this.

**Comment by blackearth2014** [comment]
Cool Breeze

**Comment by sobotka** [comment]
While we are on this subject, might as well drop [libltc](https://github.com/x42/libltc) here, which is probably in the view of this discussion.

**Comment by devernay** [comment]
This issue was moved to NatronGitHub/Natron#113
