### ISSUE TITLE
true problem, bug, crash...last snapshot..

### ISSUE THREAD

**Issue by manuelsongokuh** [MrKepzie/Natron#869]
hello
i want to create new tutorial for contribute Natron.. but i'm stop here because many problem..
so i cant go to continue.. sigh..

natron:
6ae0950d9b51c59787adc3961f4f725a5dfbad81.

ftp:
https://mega.nz/#!alsAyD4D!HPNwgDluP5runE7ftrFPFpmNLIv--eN8X2xpoJ0DwFg

DEBUG:
https://gist.github.com/manuelsongokuh/5cbe4290010efaf4f82a

screen record:
https://mega.nz/#!ftVWCLJY!Yi4bYtnauwiSmOxgku2GtfYJCrAA7OCEfCWKU8OJ_l0

maybe is problem from Roll..but also problem from Roto (strange: i cant add rectangle like as i add selection tool...after restart natron worked roto but is not sure for stable from roto...)

**Comment by MrKepzie** [comment]
Seems related to Arena.ofx

**Comment by olear** [comment]
Did some tests with Roll, but can't get Natron to crash here. I also tested the test2.ntp (I had to replace original image), no crash.

**Comment by manuelsongokuh** [comment]
hello
i did have repeat same problem..I dont know why...
maybe problem from open source driver of GPU..?

**Comment by olear** [comment]
Could you also link to the image used in the project?

**Comment by manuelsongokuh** [comment]
![fractal-noise-original-ae](https://cloud.githubusercontent.com/assets/12126929/9522652/1892d048-4cd6-11e5-9dcc-63f54e7e452a.png)

**Comment by olear** [comment]
Thanks , will do some tests a bit later today.

**Comment by manuelsongokuh** [comment]
i reboot my pc, i have not produce problem...
i'm not changed driver of GPU for linux (from open to close source amd) yet...
i dont know what is up..it's strange produce problem..

for now i have other strange problem:
- ROTO: i cant remove key animation number 2..
- ROTO: NOT WORK FEATHER FALL-OFF after I delete key animation number 2

see screen record:
https://mega.nz/#!HxkkxZzL!oCANK4x3abJoaarW6RJIG_3DMC6NW07bxn3vmVXNz_Q

ntp update:
https://mega.nz/#!Wg8hTLQQ!HPNwgDluP5runE7ftrFPFpmNLIv--eN8X2xpoJ0DwFg
.
******
other suggest: add label name on viewer for ROTO naming , when i will click node ROTO1 and label in viewer will show name "roto1", because i'm confusing for more roto.. 
i dont know if this is needed...?
******

**Comment by manuelsongokuh** [comment]
nothing feedback for problem ROTO?

**Comment by manuelsongokuh** [comment]
i did try ROTO any project ntp (new) not work correct for position x,y. key animations impossible to delete..not showed number of x and y of transform...so this mean that ROTO is very instable..?

**Comment by manuelsongokuh** [comment]
i check:
new project and add node roto1, add rectangle, simple created roto..
file ntp for roto..result:
1733 rows of code??!! from <RotoContext> to </RotoContext>
this mean: one roto, one layer, one draw rectangle like as 1733..????
it's very long rows.. it's normal??? clouds be hard to code and instable?

in code from <RotoContext> to </RotoContext> there are many code that is not usable..like as:
brushSize
brushSpacing
brushHardness
brushEffect

there are milion code for roto... why?

**Comment by manuelsongokuh** [comment]
but i'm not sure for this problem file ntp or problem from natron inside..
i did see many issues of ROTO long time for many produce problems..right? needed to check it node ROTO..or remake code core of ROTO..i dont know what is best way..
other problems non-roto is fixed short time and not high critical..but roto is long time hard to fix it..

i dont hate to write here, i write like as honesty for situation serious of ROTO problem..

maybe in the future roto will be new code or new engine or new philosophy..
i want to use natron for my jobs for EU COMMON (project european). i'm doubt more of ROTO..
roto is very potential but not stable..
sorry for my long english..i dont abuse here comment ok? i love natron!

**Comment by MrKepzie** [comment]
Please try to post everything in the same comment otherwise we get too many notifications. 
I pushed a commit yesterday fixing your issue, the build server is down right now so there's no snapshot to test it.

**Comment by manuelsongokuh** [comment]
Ah..ok, sorry for many notifications, ok i will for last snapshot..thanks you

**Comment by manuelsongokuh** [comment]
when will release snapshot latest natron? if server is down can other like sourceforge? or olear for temporary?

**Comment by olear** [comment]
The move to GPL requires some changes, a new build will probably be uploaded later today.

**Comment by manuelsongokuh** [comment]
ok for move to gpl, but today snapshot is not update to server web natron.fr, but i'm jealousy of MAC OSX did updates...grrrr....

@olear : what is your distro for builder generator linux from source github to binary for linux ready to use..?

**Comment by olear** [comment]
Natron is built on CentOS 6.4.

A new build will be up soon ...

**Comment by olear** [comment]
@manuelsongokuh : http://downloads.natron.fr/~olear/CY2015/Natron-1b5b3f5b951699ec542b65a8a6247d9fc7cd557d-Linux-x86_64bit.tgz

**Comment by manuelsongokuh** [comment]
@olear thank you for snapshot, i did checked 5 min ago, for ROTO..
it's fixed : 
FIXED - ROTO: i cant remove key animation number 2..
FIXED - ROTO: NOT WORK FEATHER FALL-OFF after I delete key animation number 2

other ask..(always ROTO) what is transform (tab) for ROTO?
because x and y always value 0.0 when i move roto result same value 0.0... it's normale?
i need to know position roto (ractangle or circle, etc) when i move with mouse in viewer..maybe it's not work..i'm right or i'm wrong?

thank you for FIX
