### ISSUE TITLE
Natron As a Python Module (enhancement)

### ISSUE THREAD

**Issue by nicholascarroll** [MrKepzie/Natron#872]
Natron would be more generally useful if it could be run as a python module:
1. Create and modify Natron project files.
2. Use it as the main Python library for compositing operations
3. Integration of Natron and Blender

Similar to what [Blender offers](http://wiki.blender.org/index.php/User%3aIdeasman42/BlenderAsPyModule). Or [Nuke since v 8.0](http://docs.thefoundry.co.uk/nuke/80/pythondevguide/nuke_as_python_module.html)

I read the [Natron Python doc](http://natron.readthedocs.org/en/workshop/natronexecution.html) and it does not seem to have that option.

**Comment by MrKepzie** [comment]
NatronEngine and NatronGui cannot be imported externally, they are built statically into Natron binary. 

If we were to make them modules (.so), then importing it would also require the end-user to have all the libraries that we ship in the bin/ folder on Windows when they do so. 
Needless to say, some libraries we use for Natron are also used, for example by Blender, without saying Blender is using Python 3, whereas we use Python 2.

In the end this is a matter of testing, but I'm not sure of the feasibility of this and if this is really used in production anyway.

**Comment by nicholascarroll** [comment]
mainly for editing natron project files

**Comment by MrKepzie** [comment]
If we implement that, Natron's python module(s) will only be usable from the Python executable shipped with Natron.

**Comment by MrKepzie** [comment]
What you can do (which is pretty much the same) is use NatronRenderer to execute your python script:

This will attempt to render

    NatronRenderer script.py -w MyWriter

If you just need a python interpreter with access to Natron, use Natron like this:

    NatronRenderer -t <script.py>

**Comment by devernay** [comment]
I think this issue is about handling Natron project files from another application, such as Nuke or Blender, or any python interpreter.

**Comment by nicholascarroll** [comment]
Yes, mainly for performing an edit on a Natron file from within another application. 

Here is a use case:
We are in the NLE and have a shot we want to do roto on. We have a python function in the NLE that will create a Natron project file with our clip as read node and just a write node. Then, when we come to compositing we have a Natron project file ready for each compositing job. This means we don't have to build any kind of workflow external to the applications.

Natron is modular which is ideal but we need plenty of options for tight integration to other modular applications.

**Comment by devernay** [comment]
This issue was moved to NatronGitHub/Natron#115
