### ISSUE TITLE
Python shiboken error when launching self-built version

### ISSUE THREAD

**Issue by azerupi** [MrKepzie/Natron#874]
It was working a couple of days ago but I deleted my local clone of Natron's repo and cloned the fork I made, to be able to submit PR's in the future. But now I get this error when I compile:

```
App/Natron                                                                           
Natron Version 2.0.0
Copyright (C) 2015 the Natron developers
>>>Use the --help or -h option to print usage.<<<
Fatal Python error: [libshiboken] Failed to initialise Shiboken.BaseWrapper type.
Aborted (core dumped)
```

The only thing that could have changed between the two is the `config.pri`. I don't remember exactly what I put into it the last time and I deleted it, so I can't check... 

This is my current `config.pri`

```
boost: LIBS += -lboost_serialization
expat: LIBS += -lexpat
expat: PKGCONFIG -= expat
cairo: PKGCONFIG -= cairo
pyside {
        PKGCONFIG -= pyside
        INCLUDEPATH += $$system(pkg-config --variable=includedir pyside-py3)
        INCLUDEPATH += $$system(pkg-config --variable=includedir pyside-py3)/QtCore
        INCLUDEPATH += $$system(pkg-config --variable=includedir pyside-py3)/QtGui
        INCLUDEPATH += $$system(pkg-config --variable=includedir QtGui)
        LIBS += -lpyside.cpython-34m
}
shiboken {
        PKGCONFIG -= shiboken
        INCLUDEPATH += $$system(pkg-config --variable=includedir shiboken)
        LIBS += -lshiboken.cpython-34m
}
```

**Comment by olear** [comment]
The build fails or the app fails when starting?

Can't see any problems in config.pri (as long as pkgconfig works ;) )

Your system has not been updated/changed since last time? Natron binary links against the right libraries?

**Comment by azerupi** [comment]
It builds fine but the App fails on launch, I based my `config.pri` on yours both times with some modifications for my setup, but last time it worked without problems.

I am on Arch Linux, all the dependencies are from system. I update frequently since Arch is a rolling release. Last week it worked, so every dependency should be present. 

The only things I can think of is that an update broke something (which is highly unlikely since the shiboken package was last updated `2015-03-28 17:33 UTC`) or I changed something in my `config.pri`

**Comment by olear** [comment]
Last time I tested on Arch I had to build shiboken/pyside, https://github.com/MrKepzie/Natron/blob/workshop/tools/linux/include/misc/build-natron-on-archlinux.sh (src url is broken replace with http://downloads.natron.fr/Third_Party_Sources/), but since Arch always change, I don't know what works or not ....

**Comment by azerupi** [comment]
Yeah but I got it to work last week with shiboken and pyside from system, so it's strange that it doesn't work anymore. Where there any changes in Natron in the last 2 weeks that could explain this error? Like the move to python 2 maybe?

**Comment by olear** [comment]
Both py2 and py3 should work, granted I have not tested py3 since we moved to py2.

**Comment by azerupi** [comment]
Tried to link to the py2 versions, but get the same error when I start the App. So Python 3 shouldn't be the problem.

**Comment by MrKepzie** [comment]
Can you link your config.pri when using python 2?

**Comment by azerupi** [comment]
Yes, the only thing I change is that I add `-py2` at the end of the package, like this
```
boost: LIBS += -lboost_serialization
expat: LIBS += -lexpat
expat: PKGCONFIG -= expat
cairo: PKGCONFIG -= cairo
pyside {
        PKGCONFIG -= pyside
        INCLUDEPATH += $$system(pkg-config --variable=includedir pyside-py2)
        INCLUDEPATH += $$system(pkg-config --variable=includedir pyside-py2)/QtCore
        INCLUDEPATH += $$system(pkg-config --variable=includedir pyside-py2)/QtGui
        INCLUDEPATH += $$system(pkg-config --variable=includedir QtGui)
        LIBS += -lpyside.cpython-34m
}
shiboken {
        PKGCONFIG -= shiboken
        INCLUDEPATH += $$system(pkg-config --variable=includedir shiboken-py2)
        LIBS += -lshiboken.cpython-34m
}
```
-----

**To give some background info:**

**`ls /lib/pkgconfig/shibo*` gives**
```
/lib/pkgconfig/shiboken.pc  /lib/pkgconfig/shiboken-py2.pc
```

**`ls /lib/pkgconfig/pyside*` gives**
```
/lib/pkgconfig/pyside-py2.pc  /lib/pkgconfig/pyside-py3.pc
```

**`echo $PKG_CONFIG_PATH` gives**
```
/lib/pkgconfig
```

**Comment by MrKepzie** [comment]
You’re still linking against libshiboken.cpython-34m which is not going to work since it’s linked against Python 3.4.

**Comment by azerupi** [comment]
You are right, my bad. It works now with Python 2. I guess there si a problem with pyhton 3 then.

Thanks for the help! :)

**Comment by MrKepzie** [comment]
We will not maintain support for Python 3 for now, feel free to try to fix it though ;)

**Comment by azerupi** [comment]
> We will not maintain support for Python 3 for now, feel free to try to fix it though ;)

I wouldn't even know where to begin ;)

**Comment by MrKepzie** [comment]
The possible issue is that Python bindings are generated by Shiboken-py2, and if using Shiboken-py3 you probably have to regenerate them again (see INSTALL_OSX.md)

**Comment by azerupi** [comment]
Ok, I will check tomorrow if that fixes the issue for python 3 :)

**Comment by azerupi** [comment]
@MrKepzie I get the same error on OS X with xcode, I was finally able to build on xcode and when launching it crashes giving me:

```
dyld: Symbol not found: __Py_FalseStruct
  Referenced from: /usr/local/lib/libshiboken.cpython-34m.1.2.dylib
  Expected in: flat namespace
 in /usr/local/lib/libshiboken.cpython-34m.1.2.dylib
(lldb) 
```

It's linking against shiboken for python 3 even with this config.pri:

```
boost: INCLUDEPATH += /usr/local/include
boost: LIBS += -L/usr/local/lib -lboost_serialization-mt -lboost_thread-mt -lboost_system-mt
expat: PKGCONFIG -= expat
expat: INCLUDEPATH += /usr/local/opt/expat/include
expat: LIBS += -L/usr/local/opt/expat/lib -lexpat
cairo: PKGCONFIG -= cairo
cairo: INCLUDEPATH += /usr/local/opt/cairo/lib/
cairo: LIBS += -L/usr/local/opt/cairo/lib -lcairo
pyside {
	PKGCONFIG -= pyside
        INCLUDEPATH += $$system(pkg-config --variable=includedir pyside)
        INCLUDEPATH += $$system(pkg-config --variable=includedir pyside)/QtCore
        INCLUDEPATH += $$system(pkg-config --variable=includedir pyside)/QtGui
        INCLUDEPATH += $$system(pkg-config --variable=includedir QtGui)
        LIBS += -lpyside-python2.7
}
shiboken {
	PKGCONFIG -= shiboken
        INCLUDEPATH += $$system(pkg-config --variable=includedir shiboken)
	LIB += -lshiboken-python2.7
}
```

Is there something specific to do for xcode or OS X ?

**Comment by olear** [comment]
@azerupi https://github.com/MrKepzie/Natron/blob/672289c14d57c9bd56548af02ec582706479e90f/global.pri#L200

**Comment by olear** [comment]
Tested against py3 on Linux, no problems.

```
[root@CY2015 linux]# /opt/Natron-CY2015/bin/NatronRenderer -t
Note: -t argument given, loading in command-line interpreter mode, only Python commands / scripts are accepted
Restoring the image cache...
Restoring user settings...
Loading PyPlugs...
Python 3.4.3 (default, Aug 16 2015, 04:06:12) 
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 
```

**Comment by azerupi** [comment]
> @azerupi https://github.com/MrKepzie/Natron/blob/672289c14d57c9bd56548af02ec582706479e90f/global.pri#L200

I tried some things without success, I am really not comfortable with those config files. Could you explain what you wanted me to understand with that link? :)

**Comment by azerupi** [comment]
I tried that, but it didn't work

**Comment by MrKepzie** [comment]
It’s important that you call 

qmake -r -spec macx-xcode CONFIG+=debug PYTHON_CONFIG=python2-config 

from the terminal. 

The thing is (I don’t know if you’re using home-brew or macports) but Xcode probably doesn’t have the python2-config in its path and by default will use python3

**Comment by azerupi** [comment]
@MrKepzie I installed everything with Homebrew, the command you gave doesn't seem to change anything. Is there a setting in Xcode to change?

**Comment by MrKepzie** [comment]
No.  I use macports anyway, but the thing is you have something messed up in your environment making qmake load the py3 version of shiboken instead of py2. Cannot figure it out for you since your environment is unique...
