### ISSUE TITLE
CurveTool

### ISSUE THREAD

**Issue by wochen** [MrKepzie/Natron#875]
Hi there. 

Are you planning to add it to Natron? It will be very useful.

Best.

BTW: fantastic piece of software.

**Comment by MrKepzie** [comment]
Not planned, I'm not sure of the necessity of such tool. Someone could contribute one.

**Comment by wochen** [comment]
Maybe AVG Intensities for a specific number of frames only would be possible? 
Please have it in your mind. It's very useful tool for cleaning shots, for example removing flickering.

**Comment by devernay** [comment]
Did you try ImageStatistics? I could easily add all the measures from CurveTool in that plugin.
To Average intensities or make a clean plate, you can use FrameBlend

**Comment by wochen** [comment]
I would be very grateful for preparing this. Really.

Thanks.
T.

2015-09-17 0:02 GMT+02:00 Frédéric Devernay <notifications@github.com>:

**Comment by devernay** [comment]
This issue was moved to https://github.com/NatronGitHub/Natron/issues/116
