### ISSUE TITLE
it's possible add 2 buttons: 'set start of range' and 'set end of range' for 'frame range'?

### ISSUE THREAD

**Issue by manuelsongokuh** [MrKepzie/Natron#876]
hello

it good add new 2 buttons for add/set 'frame range'?
- 1 button: 'set start of frame range' (will be added number frame from timeline current)
- 2 button: 'set end of frame range' (will be added number frame from timeline current)

the buttons will be near the place of 'frame range', instead i use click for put in number value of 'frame range'..'its be good and faster click without keyboard..

it's be good or nothing?
thank you

**Comment by MrKepzie** [comment]
See https://github.com/MrKepzie/Natron/issues/1079
