### ISSUE TITLE
Poor performance with Exr file and can't stop the render of the current frame

### ISSUE THREAD

**Issue by zabander** [MrKepzie/Natron#878]
Good day, I've been testing the last snapshoot August 8 found the next error with an EXR file rendered in vray from 3ds Max. Resolucion 5k. No multi channel exr.

Extreme low performance rendering in the viewver  it takes couple of minutes to show correctly, and I can't change the viewer node to other node. I also can't stop the viewer rendering. 

I have also noticed that if I hit the numpad 1 to see the image as soon as I loaded to the node graph and the thumbnail in the node editor is not loaded the performance issue happens too.

Is anything I can give you to track this issue?

**Comment by MrKepzie** [comment]
Hey, 

This is a known bug in the OpenImageIO library.
We’ve already opened an issue there and we hope this will get fixed soon.

**Comment by zabander** [comment]
Oh I see, so Natron will have to wait until this is fixed.

**Comment by MrKepzie** [comment]
Or if we get time to fix it there ourselves… You can bump the issue there if you want, might get it fixed faster;)

https://github.com/OpenImageIO/oiio/issues/1123

**Comment by zabander** [comment]
I did it! :D I hope they can fix it soon.

**Comment by ramellij** [comment]
Did it too. I can't work with until it's fixed :/

**Comment by MrKepzie** [comment]
@zabander Can you send me a sample of your EXR though for testing ? I don't have VRay, and there might be an issue unrelated to the bug linked above

**Comment by ramellij** [comment]
Bonjour Alexandre,

Voici un exemple d'EXR (RGBA uniquement) venant de VRay Maya compressé 
en "scanline zip" :
http://we.tl/YLEs1cFXer
<http://docs.chaosgroup.com/display/VRAY3MAYA/Image+Format+Options>
Le "scanline zip" est le format conseillé pour travailler sur Nuke. 
L'EXR étant un standart dans l'industrie, un Reader optimisé serait 
vraiment nécessaire. VRay propose aussi d'autres compressions (peut être 
mieux adaptées) :
http://docs.chaosgroup.com/display/VRAY3MAYA/Image+Format+Options

Si tu as besoin d'autres samples ou de séquences d'images n'hésite pas à 
demander ;)

Merci
JR

**Comment by MrKepzie** [comment]
Bonjour,

Merci pour l’image. En effet je vais avoir besoin d’une séquence pour pouvoir tester correctement. 
OpenImageIO en interne utilise exactement le même code que celui utilisé dans Nuke et je suppose aussi VRay (dans le cas de fichiers non multi passe), il n’y a donc pas de raison qu’il soit plus lent.

**Comment by ramellij** [comment]
Voici une séquence de 80 frames EXR fullHD 16 bits half-float en scanlineZip : http://we.tl/ZPIX3vhwPr

**Comment by zabander** [comment]
Hi!, sure, http://we.tl/AFyCHehYFy this are new test files I made today to send you. They are 5k EXR no extra channels and 16FP. They are tiled files with scanline zip comp.
On Monday I'll send you the files I tested at the office and presented the problem, but the settings used in those are pretty much the same. I hope that they can help you.

**Comment by MrKepzie** [comment]
Jonathan: Ici sur la version en développement, Natron lit environ à la même vitesse que Nuke 9 la séquence en playback

**Comment by ramellij** [comment]
Nice! C'est la même que la snapshot windows du 8 Aout ou la future release stable 2.0 ?

**Comment by MrKepzie** [comment]
Non c’est une nouvelle version. Nous allons remettre en route les snapshots sur Windows sous peu, on a changé entièrement le système de build et l’installateur

**Comment by zabander** [comment]
MrKepzie, did you tried the EXR I sent you? Testing in my windows 10 install at home I had no issues with the version I sent you. Monday I'll send you others, BUT! the OS where I had problems is a windows 7 install at the office. Maybe a problem only in windows 7 only?

**Comment by MrKepzie** [comment]
I tested the files and everything is OK here (OS X). 
I will test tomorrow on Win7. We will re-activate snapshots on next week and hopefully release Natron 2 about the end of next week.

**Comment by zabander** [comment]
Do you have a mail where I can send you the files for testing? Can't share them publicly

**Comment by MrKepzie** [comment]
Sure alexandre dot gauthier-foichat at inria dot fr <http://inria.fr/> 

I’m also setting up the snapshot server for Windows right now. The next build should be available soon

**Comment by zabander** [comment]
I have already sent you, please can you check?

**Comment by zabander** [comment]
Also you can try to importa all files from the zip simultaneously to the node graph, sometimes it crashes Natron.

**Comment by MrKepzie** [comment]
Will test

**Comment by MrKepzie** [comment]
Works well. We’ll see on the next build on windows

**Comment by zabander** [comment]
Thanks! MrKepzie, I'll check that computer to see if that's the problem. If it doesn't I'll make a video to recreate the problem.

Thanks again for the amazing job you're doing.

**Comment by ramellij** [comment]
hi, 
I saw there are some new snapshots : http://downloads.natron.fr/Windows/snapshots/64bit/files/
Does it make sense to try them or the new stable release is about to come out ?

**Comment by MrKepzie** [comment]
Stable release is about to come out, we're just testing our build scripts.

**Comment by ramellij** [comment]
Cool, can't wait! I have so much to do with :D

**Comment by MrKepzie** [comment]
We have made a small tweek to OIIO and it should drastically increase EXR I/O performances. Please try out after next snapshot

**Comment by zabander** [comment]
That's really cool, thank you! Testing soon.
