### ISSUE TITLE
snapshots

### ISSUE THREAD

**Issue by rcspam** [MrKepzie/Natron#880]
It could be cool to have some snapshots to test last commits (linux)
Thanks...
Btw, why no communicate of what happens with actual Natron development.
A topic on the forum would be welcome.

**Comment by olear** [comment]
preparing for release, I have limited HW resources at the moment, so I can't dedicate CPUs to the build system.

I do however got some builds at http://downloads.natron.fr/~olear/CY2015/, use at own risk ;) (installers-only, no repo)

**Comment by MrKepzie** [comment]
We have been working a lot on the build system to make it more robust and easier to maintain in the future. We are about to be ready to release Natron v2. The only big thing left is updating the website now.
