### ISSUE TITLE
Error creating dialogs through Python

### ISSUE THREAD

**Issue by zabander** [MrKepzie/Natron#881]
Hi Guys, I try to create warning dialogs using:
NatronGui.PyGuiApplication.warningDialog("title","message")
And I receive:
TypeError: descriptor 'informationDialog' requires a 'NatronGui.PyGuiApplication' object but received a 'str'

Where is the issue?
I'm in the GUI

**Comment by MrKepzie** [comment]
You have to use:

    NatronGui.natron.warningDialog("title","message")

*natron* is a variable part of the NatronGui and NatronEngine module. Depending on the module in which you use it, it offers different functionnalities (see PyCoreApplication and PyGuiApplication documentation)
