### ISSUE TITLE
Dopesheet Keyframe Duplication: Modifier Key

### ISSUE THREAD

**Issue by blackearth2014** [MrKepzie/Natron#882]
Can we get a modifier key + left click & drag to duplicate keyframe nodes without having to copy and paste them? Also can the playhead follow mouse clicks in the frame range?

**Comment by MrKepzie** [comment]
Implemented: Just CTRL (CMD) + Double click on a parameter line and it will add keyframes at the current curve value.

**Comment by blackearth2014** [comment]
Thanks
