### ISSUE TITLE
Crash on Right Click -> Image -> Read

### ISSUE THREAD

**Issue by Srimavo** [MrKepzie/Natron#885]
On WIndows 8.1 64bit I get the following crash every time I open Image -> Read:

The open sequence dialog shows up and the app crashes instantly.

Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	Natron.exe
  Application Version:	0.0.0.0
  Application Timestamp:	54e76f20
  Fault Module Name:	QtGui4.dll
  Fault Module Version:	4.8.6.0
  Fault Module Timestamp:	54dca400
  Exception Code:	c0000005
  Exception Offset:	00000000001af2de
  OS Version:	6.3.9600.2.0.0.768.101
  Locale ID:	1033
  Additional Information 1:	c2e1
  Additional Information 2:	c2e1b1314e3724c34db23ac2adb2cbb7
  Additional Information 3:	a359
  Additional Information 4:	a359afbcc2f8e109e803af510f41a7ad

**Comment by MrKepzie** [comment]
Which version of Natron ?

**Comment by Srimavo** [comment]
v1.2.1 - Release - build on Feb 20 2015    x64

**Comment by olear** [comment]
Then you should wait for v2 (or download and test latest v2 snapshot at http://downloads.natron.fr/Windows/snapshots/64bit/files/).

**Comment by Srimavo** [comment]
Thanks, the snapshot works like a charm.
