### ISSUE TITLE
OpenGL rendering

### ISSUE THREAD

**Issue by rcspam** [MrKepzie/Natron#888]
Hi,
Is there a plan to add OpenGL rendering in Natron ?
Is the cost worth it ?
Blender developers had improve the CPU render very well.
It is speediest than GPU (cuda) with some GPU cards !
What will happen about future Natron's versions ?

**Comment by MrKepzie** [comment]
Yes, we are going to do some OpenGL plug-ins. This is only worth doing it if the user can chain them one after another so the image stays on the GPU. So we would need to code most of the default plug-ins on the GPU before it starts being a contender to the CPU version. 

Note that when doing OpenGL rendering, you cannot compute multiple frames in parallel, hence you do a very poor usage of the CPU.

**Comment by rcspam** [comment]
Thank you for that clarification.
