### ISSUE TITLE
PSD files crash the app

### ISSUE THREAD

**Issue by zabander** [MrKepzie/Natron#890]
Good day sir!, I have a problem, when importing a psd file from the menu it crashes inmediatly. If I toss it just makes the app not respond.
Windows 7.
photoshop cc 2014
Last Snapshot from Sep 10.

**Comment by olear** [comment]
Can you provide a sample psd that crashes Natron?

**Comment by zabander** [comment]
Sure: https://www.dropbox.com/s/qek8o32t2vh8k33/Blendi%20Views.psd?dl=0
I used the snapshot from Sept 10

**Comment by olear** [comment]
The build seems broken .... (Arena don't work, parts of IO don't work)

I also get "multi-resolution not supported", and can't connect anything to the viewer.

**Comment by olear** [comment]
Fix: http://downloads.natron.fr/~olear/misc/Arena.ofx

Overwrite /path/to/Natron/Plugins/Arena.ofx.bundle/Contents/Win64/Arena.ofx

@MrKepzie : Same computer that does the Linux builds? then it's IM.

**Comment by MrKepzie** [comment]
Works well againt http://downloads.natron.fr/Windows/snapshots/64bit/files/Natron-17b377a55009a5a31b1126300d8cf886fd1de630-Windows-x86_64bit-setup.exe

it's just a miscompiled version you are using

**Comment by olear** [comment]
Still multi-resolution issues.

**Comment by MrKepzie** [comment]
Yes this was fixed in Natron in a later commit, need to rebuild

**Comment by olear** [comment]
My bad, didn't notice the build date on the link :)
