### ISSUE TITLE
SeExpr Node Crashes the app

### ISSUE THREAD

**Issue by zabander** [MrKepzie/Natron#891]
Just testing the Windows Snapshot from Sep 10. on windows 7 machine. the SeExpr Node crashes Natron.

Is it ok to post here in issues all the bugs found in the snapshots? or it is better to wait a RC?

**Comment by MrKepzie** [comment]
Can you show us your configuration of the node ?

**Comment by olear** [comment]
instant crash on usage here.

**Comment by olear** [comment]
screenshot:
![crash](https://cloud.githubusercontent.com/assets/7461595/9809941/da83ecb8-586c-11e5-9ab2-32a7858428b8.png)
and after that I get xml error on startup, charset/text issues again maybe?

**Comment by MrKepzie** [comment]
Do not get that error. We recently changed the compilation with UNICODE enabled, might be the issue.

**Comment by MrKepzie** [comment]
Try this version instead. http://downloads.natron.fr/Windows/snapshots/64bit/files/Natron-17b377a55009a5a31b1126300d8cf886fd1de630-Windows-x86_64bit-setup.exe 

Other versions online were miscompiled. Anyway I'm going to compile without UNICODE

**Comment by olear** [comment]
Still crashing here... (also with an old natron-mingw build)

**Comment by MrKepzie** [comment]
Make sure you have nothing on your system installed in Program Files/Common Files/OFX/Plugins

**Comment by olear** [comment]
It's empty. Tested on laptop and workstation.

**Comment by zabander** [comment]
It was instant crash just after I created the node as Olear, I am going to test the build you post in this page.

**Comment by zabander** [comment]
MrKepzie, could you share the current snapshot to test?, it still crashes with the built you mentioned.

**Comment by MrKepzie** [comment]
This is an issue with snprintf and char. I suspect it being related to UNICODE or _MBCS defines in Natron

**Comment by zabander** [comment]
@MrKepzie All tested build in the snapshot folder have the same issue. Thank you for tracking this issue, I hope you can solve it soon.

**Comment by MrKepzie** [comment]
@olear I've been playing around and it does not seem to be an issue with UNICODE and _UNICODE defines or _MBCS but an issue with MingW implementation of stdio. 
It seems that everything in MSYS2 is compiled using -D__USE_MINGW_ANSI_STDIO . I gave it a shot and tried to compile openfx-io and sdk with it too but did not solve the issue. 
WIll try changing calls from snprintf to c++ iostream to see if that makes any difference.

**Comment by MrKepzie** [comment]
http://downloads.natron.fr/Windows/snapshots/64bit/files/Natron-58c5107732415582723217b6150246f3d0fbaf95-Windows-x86_64bit-setup.exe fixes it.

**Comment by zabander** [comment]
@MrKepzie, just tested the built, it still crashes the SeExp node, etc.

**Comment by olear** [comment]
works here (win7), try clearing config/cache.

![seexprwin](https://cloud.githubusercontent.com/assets/7461595/9832968/2f0433c6-5988-11e5-8ec7-08315207dd3f.png)

**Comment by zabander** [comment]
@olear with this built Natron-58c5107732415582723217b6150246f3d0fbaf95-Windows-x86_64bit-setup.exe?

I'm testing in windows 10. But is the same I had in win 7. I cleared the Cache in Natron, is there other place where I should?

**Comment by olear** [comment]
I used the update function (Natron is 58c5107732415582723217b6150246f3d0fbaf95, but it's openfx-io that has the fix).

Try removing the INRIA folder in Users/your_username/AppData/Local/

**Comment by zabander** [comment]
![error_01](https://cloud.githubusercontent.com/assets/1145623/9833272/1e231126-5956-11e5-9540-0085b6f1e5d4.jpg)
![screenshot 2015-09-12 13 57 06](https://cloud.githubusercontent.com/assets/1145623/9833276/2e9dc492-5956-11e5-98af-c01baf33cba8.png)


I get these two errors, I have deleted the folder from Users/your_username/AppData/Local/, with not success.

**Comment by olear** [comment]
Installing the setup file over will not fix the issue, run NatronSetup and choose update.

**Comment by zabander** [comment]
Thank you @olear !!!, I completely missed that. Never tried to update. Now it works fine!
Can I continue testing the snapshots only by updating? no need of reinstall?

**Comment by olear** [comment]
Should be no need to reinstall :) When moving from snapshot to stable you can just switch url (or of course reinstall).
