### ISSUE TITLE
Matte Monitor (enhancement)

### ISSUE THREAD

**Issue by nicholascarroll** [MrKepzie/Natron#892]
In Chapter 3 of Steve Wright's book Digital Compositing for Film and Video (2nd Ed), he describes what he calls a 'Matte Monitor'. This will show alpha 1.0 as white, alpha zero as black, and all other values as grey. 

It would be useful to have this readily available in the viewer and a hotkey assigned.

Without this, it would be done with a node but it that is not as convenient.

**Comment by devernay** [comment]
Shortcut "a" does exactly this.

**Comment by nicholascarroll** [comment]
Shortcut a gives alpha channel. Matte monitor would push all values not exactly 1.0 or 0.0 into a mid grey.

**Comment by nicholascarroll** [comment]
Here is a link to the chapter in [google books](https://books.google.com.au/books?id=9OgUaoidIYMC&pg=SA3-PA2&dq=Digital+Compositing+for+Film+and+Video+matte+monitor&hl=en&sa=X&ved=0CCsQ6AEwAGoVChMIoZizlfTwxwIVR8emCh17uwXw#v=onepage&q=Digital%20Compositing%20for%20Film%20and%20Video%20matte%20monitor&f=false)

**Comment by devernay** [comment]
I made a small plugin for that purpose. A UI item in the viewer would have polluted the interface, and a shortcut would have been too hidden. Besides, the plugin has a "slope" setting which may be useful

**Comment by nicholascarroll** [comment]
Yes a slope option is better than just 0.5.
