### ISSUE TITLE
Natron crashing upon Lauch: Natron-f4ea671bb6a17d0f9dbc78230e4bf7fd54de2acc Snapshot

### ISSUE THREAD

**Issue by blackearth2014** [MrKepzie/Natron#898]
https://gist.github.com/blackearth2014/87c79c3dec57886ffdf4

**Comment by MrKepzie** [comment]
this is an issue with the build server

**Comment by blackearth2014** [comment]
Okay. This Mac version Natron-0712738629ec1af9c083ecef379474a25d3e1f69 is crashing too.
