### ISSUE TITLE
Error in the console windows 10

### ISSUE THREAD

**Issue by zabander** [MrKepzie/Natron#899]
I have this errors in windows 10, during lunch in the console lastest  snapshot (14-09-2015)

![screenshot 2015-09-15 00 24 55](https://cloud.githubusercontent.com/assets/1145623/9868586/70bed384-5b40-11e5-9434-3b2f733b1c5a.png)

**Comment by MrKepzie** [comment]
It's just a missing openssl dll, it shouldn't be needed anyway since we barely use it. We will add it to the distrib  though.
