### ISSUE TITLE
Natron-201509160707-e483ac9b0b01cae22fb00c1dc04560bc72dad412: Crashed on Launch

### ISSUE THREAD

**Issue by blackearth2014** [MrKepzie/Natron#901]
Here is the GIST file link at https://gist.github.com/blackearth2014/b9397c64a6da58315605. It crashes on the Fontconfig config portion of the launch.

This image below is from the Natron.App show package.

![natron-unix exe file](https://cloud.githubusercontent.com/assets/7956901/9914927/42a3ef28-5c82-11e5-9f5f-5737a6934792.png)

**Comment by devernay** [comment]
snapshots are still unstable. Natron runs OK here, but we still have a few deployment issues. Excpect it to be runnable in a couple of days.
