### ISSUE TITLE
Merge3D node 

### ISSUE THREAD

**Issue by Ambassy** [MrKepzie/Natron#902]
At the imprementation of cards and camera nodes,It may be good to have a merge3D node with the ability&features to hundle 3D planes than the usual merge. Eg:to set distance between foreground plan and background plane without direct overlaping images like usual. This feature can be useful in comps to set the illusion of depth of field and make realistic comp etc.

**Comment by devernay** [comment]
This issue was moved to NatronGitHub/Natron#118
