### ISSUE TITLE
Creating Channels doesn't work in with and without python

### ISSUE THREAD

**Issue by zabander** [MrKepzie/Natron#904]
Hey there, I've been trying to create channels but it only returns false.

This is what I've Done. 
I created a Shuffle node.
then used this
app =  app1
app1.Shuffle1.addUserPlane("MyLayer",["R", "G", "B", "A"])

And later nothing happens, and when I print the result is always false.

**Comment by zabander** [comment]
I can't create a layer even manually!

**Comment by MrKepzie** [comment]
Can you post a screen shot of your setup and on which node you are trying to call it

**Comment by zabander** [comment]
Sure, it doesn't work with any setup, even the simpliest. Just can't create a channel in a shuffle manually or through Python.

![01a](https://cloud.githubusercontent.com/assets/1145623/10004617/4d90b624-6078-11e5-849d-69fcfe701b1a.jpg)
![02](https://cloud.githubusercontent.com/assets/1145623/10004623/52da2f98-6078-11e5-9a17-49dbd9060fd1.jpg)
![03](https://cloud.githubusercontent.com/assets/1145623/10004626/56230a1c-6078-11e5-89ce-13e99d596495.jpg)

**Comment by timurhai** [comment]
At first i tried it on Afanasy group, that i creating by a python script, writing it by hands.
That i checked it on a group created with by "Ctrl+Shift+G" on a selected Grade1 effect (created by "G").
![screenshot from 2015-09-21 23 46 55](https://cloud.githubusercontent.com/assets/1492143/10004693/ae6f6650-60bb-11e5-9df8-59023d83f10d.png)
![screenshot from 2015-09-21 23 46 47](https://cloud.githubusercontent.com/assets/1492143/10004703/b88c806e-60bb-11e5-987f-b10fe6502111.png)

**Comment by zabander** [comment]
@timurhai  :D it was fixed already look at closed issues. This is other problem :)

**Comment by timurhai** [comment]
Great! Many thanks!
ps
Several Afanasy nodes connected with each other needed to override something, for example - frame range: if we need to render precomp and comp within one job and precomp with some time offset.

**Comment by timurhai** [comment]
Sorry for confuse :)

**Comment by zabander** [comment]
@MrKepzie I have updaloaded images about the problem with channels creation above timuhai's ones.

**Comment by MrKepzie** [comment]
This is an issue with the Shuffle node, will fix it. 

Confirm that it works fine on other nodes
