### ISSUE TITLE
Python: getInput() skips groups.

### ISSUE THREAD

**Issue by timurhai** [MrKepzie/Natron#905]
Hi!
It seems that getInput method pass trough custom groups.
( or may be i do something wrong )

Create a simple group.
Copy it.
Connect them (input of Group1 with an output of Group1_1).
Create Grade effect.
Connect an output of Grade with an input of Group1_1.
Select Group1 group.
Type:
print(app1.getSelectedNodes()[0].getInput(0).getLabel())
#Result:
Grade1

**Comment by zabander** [comment]
Yep, is skiping the copied group, or any other group.

**Comment by timurhai** [comment]
Can i query somehow if a group connected to some other node through another group?

**Comment by zabander** [comment]
the only way I find until a fix arrives is to store somehow the group in a variable or lista and then call it if it is needed.

**Comment by timurhai** [comment]
Sorry for confuse )
https://github.com/MrKepzie/Natron/issues/904
I put images there ( answered on other email ).
 - hot project!
