### ISSUE TITLE
Snapshot (Sept 22) doesn´t resize images - error

### ISSUE THREAD

**Issue by sirdavid32** [MrKepzie/Natron#906]
Hi, the issues with floating panels are solved only for READ nodes (I de-installed all previous snapshot versions, and installed today´s snapshot for Natron), but all other nodes are still appearing in small windows.
Additionally, the resize image node (to the project´s compositing size) is giving me an error:
![bad-image](https://cloud.githubusercontent.com/assets/11066585/10024521/28c5ce7e-611d-11e5-8cfb-dd5c73233bdb.png)

**Comment by MrKepzie** [comment]
Can you tell me the formats of the images in the 2 readers upstream of the Merge node ? (Show me the configuration of the read nodes)

**Comment by MrKepzie** [comment]
Fixed in https://github.com/devernay/openfx-misc/commit/1fe48d12266a549e76e00724cd7d9775ed34a2b8 and https://github.com/MrKepzie/Natron/commit/1131169ccc919f9358bf4360d4f327a82fc74cf2
