### ISSUE TITLE
Errors when opening a pyplug

### ISSUE THREAD

**Issue by zabander** [MrKepzie/Natron#907]
I have errors after exporting a pyplug and trying to open it in a new project. It has not been edited by hand, just exported it and then relunch the app the find the pyplug in the menu.

Is just a chain of nodes inside a group nothing more thant resize nodes, seExp nodes and a constant.

I'm using windows 7 and 10 with the Sep 22 Snapshot.

![screenshot 2015-09-22 21 45 08](https://cloud.githubusercontent.com/assets/1145623/10036869/64bd3a4c-6173-11e5-84a5-2c3ed5884799.png)

**Comment by zabander** [comment]
Nice thank you, I just updated but it seems to have the same problem with a new pyplug, was it already fixed in the current build? or should a wait a new update?

**Comment by MrKepzie** [comment]
You have to regenerate the pyplug again

Or you have to add those lines at the end of yours:

    try:
        extModule = sys.modules[“<YOURPYPLUG>Ext"]
    except KeyError:
        extModule = None
    if extModule is not None and hasattr(extModule ,"createInstanceExt") and hasattr(extModule.createInstanceExt,"__call__"):
        extModule.createInstanceExt(app,group)

Don’t forget to replace “<YOURPYPLUG>"

**Comment by zabander** [comment]
Thank you, works perfectly!
