### ISSUE TITLE
All arena plugins crash Natron a71c127967749393e1f4b1ca4bc9ff9a3143a211

### ISSUE THREAD

**Issue by rcspam** [MrKepzie/Natron#908]
All is in the title !
Regards

**Comment by olear** [comment]
broken sdk, since the old has been replaced I need to rebuild IM.

**Comment by olear** [comment]
@MrKepzie sdk repack: http://downloads.natron.fr/~olear/Natron-CY2015-Linux-x86_64-SDK-repack.tar.xz

**Comment by MrKepzie** [comment]
@olear Can you also upload separately just IM 64b and 32b ?

**Comment by olear** [comment]
Sorry for late reply (I did the 64bit rebuild just before I was going to work, so didn't have the time to split IM from the rest or start a 32bit build). Can do a 32bit now.
