### ISSUE TITLE
Rotopaint tablet problems

### ISSUE THREAD

**Issue by Montaire** [MrKepzie/Natron#909]
I really like this plugin and it is improving nicely! Here is some thoughts after testing it again:
**Tablet Usability (i am using windows 8.1 + wacom):**
1. With my tablet I can not release the image after grabbing it, but it is jumping around when I release the button. I have to click with my mouse left button to release it. (but I can grab and release the node tree)
2. Drawing a circle looks like this. The sample rate is really low, and also a basic smoothing  not working for some reason.
![screenshot](https://cloud.githubusercontent.com/assets/9551575/10043613/bc510370-61f4-11e5-8e8c-1966c4294bdb.PNG)
3. If I draw like 5 circle, the delay of  feedback is about 4 sec. It is just too slow for serious work yet.

**Other usability:**
4. If i draw something, and I step forward a frame an draw again, the pervious drawing changes its frame, and the new drawing adds to it. The plugin should be able to create a new drawing too after frame stepping, not continue the previous one (or when it continues the drawing, it should expand the frame range too). An extra setting for the multi stroke checkbox would be nice. 
5. If the show alpha (draw check board) is enabled on the viewer, It shows only the drawing. with the clone brush, it just shows a plane alpha.

**Not so important:**
6. A middle click + ctrl + drag zoom would be a great addition. It makes the workflow faster.
7. The turbo button cant remember its state before drawing. Its always get disabled.

**Comment by olear** [comment]
RotoPaint crashes (add one dot and it will crash) on latest Linux build.

**Comment by MrKepzie** [comment]
@Montaire 
Please try after https://github.com/MrKepzie/Natron/commit/857b3009e7404a6c3732a051d0c5ec3d3ef275eb
It should speed-up the rotopaint.

**Comment by Montaire** [comment]
Its a tablet specific problem I think (but I am really happy for the speed-up!).
If I draw with the mouse everything fine. If I draw with my wacom tablet slowly, still works but little bit laggy. But if I do it fast, it becomes really slow, and edgy. (Also I cant drag the image with tablet)
![screenshot](https://cloud.githubusercontent.com/assets/9551575/10059110/6604b62e-6249-11e5-9391-72d9929d6cd2.PNG)
Here I drew two circles. the first is the slow one, and the second is the fast. And for some reason the background turns black, if there is an another stroke on an another frame.
Also 4. now works great thanks!

**Comment by MrKepzie** [comment]
All points have been fixed. You should try with a more recent snapshot (in an hour or so). 
We are testing with a Wacom bamboo and it works fine here.

Regarding the zoom, you have to configure it in your tablet settings: 
Natron is already taking into accounts zoom from tablet if:

Alt + middle or
 Left + middle or
 Crtl + Alt + Left 

are pressed

**Comment by Montaire** [comment]
The new snapshot does not work either. I made a clean install.  Have you tried on windows too?
On my system the background turns black if there is a drawing on a different frame, drawing not always updated on the screen, but its noticeably faster when it does. Grab and zoom (tablet middle button) stick, I cant still exit these modes with tablet, I have to use my mouse. 
Zoom really works now I feel bad i thought I tried sorry.
Only 4. 6. 7. fixed here.
I don't know whether its related but i get a lot of 
*MemoryFile EXC : Failed to open file C:/Users/[USER]/AppData/Local/INRIA/Natron/ca
che/ViewerCache/d7/47af07a470cc13.ntc*
And an *xml error:9* on startup.

[OFF] There was a couple image processing plugins like skeleton, segmentation in a recent build, but they are gone. There is any way to get those binaries?[OFF]

**Comment by MrKepzie** [comment]
MemoryFile EXC : Failed to open file C:/Users/[USER]/AppData/Local/INRIA/Natron/ca
che/ViewerCache/d7/47af07a470cc13.ntc means there is an issue writing to the cache. How much RAM do you have / disk space ? Black images might be due to this. 

The segment/inpaint plug-in are gone since they were buggy and not at all suitable for production code. They are deactivated until they are ported to a decent level

**Comment by Montaire** [comment]
I have 12GB ram and around 20GB free space on my notebook right now.

**Comment by olear** [comment]
Noticed reduced performance when using a Wacom vs. the mouse. Moving in the viewer is very slow.

I'm using a wacom intuos 3.

http://downloads.natron.fr/~olear/mouse_vs_wacom.ogv

**Comment by MrKepzie** [comment]
Can this be a driver issue ? On Windows & mac this works fine

**Comment by olear** [comment]
Unsure, other apps work as they should (krita, shake etc). Will do some more tests

**Comment by MrKepzie** [comment]
Ok seems to be a bug in Natron, but having a hard time to debug it since the tablet does not work at all for me in Natron. (but works fine in Qt tablet example)

**Comment by Montaire** [comment]
As I remember Krita has its own tablet support now, because they had a lot of problems with qt as well.

**Comment by MrKepzie** [comment]
I fixed it. It will be available in a few hours

**Comment by olear** [comment]
Works great :)

But Smear seems to be unusable/broken, I can smear, but when I release then my changes are gone.

**Comment by MrKepzie** [comment]
Cannot reproduce here

**Comment by MrKepzie** [comment]
Ok the bug is when you draw the second multi-stroke
