### ISSUE TITLE
Not getting info from outside of a group

### ISSUE THREAD

**Issue by zabander** [MrKepzie/Natron#911]
Hey!, I got a problem when I try to get information from a node that is outiside the group in this case I want to get the resolution of the read node.  Inside the group I use an expresion to get the resolution information from the input. But it gets 0.0 , 0.0 when it should 1920.0 , 1080.0.

**Comment by MrKepzie** [comment]
You can only reference nodes in the same group (or the group nose itself). 

To do this you can add an expression on the group nose itself which is in the same group as the read node and then make an expression in the node inside the group referencing the value on the group

**Comment by zabander** [comment]
Thank you! That works fine

**Comment by zabander** [comment]
@MrKepzie After testing this method it causes some problems when I disconnect the input and reconnect to other file with other resolution, the expression is not reevaluated and it doesn't chance. Also noticed that when saving the pyplug it doesn't save the expression in the nose of the group.

**Comment by MrKepzie** [comment]
No you cannot set invalid expressions. The correct way to handle your issue is:

- Override the [after input changed callback](http://natron.readthedocs.org/en/workshop/callbacks.html#the-after-input-changed-callback)
And put it in the extension script (<PyPlugName>Ext.py ). 

- Create 2 user parameters on the group node itself and make them invisible: call one bottomLeft and the other topRight

- In the implementation of the input changed callback, whenever an input changed, call getRegionOfDefinition on it (if this is an input that is interesting for your problem)  and retrieve the bottom left and top right of the RoD (region of definition)

- Set the values of the parameters you create on the group node to respectively the bottom left and top right point of the RoD

- In your node internally to the group, connect with an expression to the bottomLeft  and topRight parameters you added manually to the group node. 

- voila

**Comment by zabander** [comment]
to be sure: I have to create this Ext.py and put in there that if the input change I have to look for RoD of the input node, if I don't have one I have to look for the parameters I created?

Are the values of this new parameters whatever I want?

**Comment by MrKepzie** [comment]
I do not understand the question

**Comment by zabander** [comment]
The problem I have is this: I created this pyplug that needs to get connected to a read file and get the Resolution of this file. So I have to create an expression to get this info. But when disconnected it tose an error because the expression is not valid.

 Now I create this after input changed callback with the Ext.py. that if the node input change it has to look for other data, in this case the new 2 params ( bottomLeft and the other topRight ), right?  

But now when I gets connected again to a valid read file how it will get the resolution of this read node if it is looking for this new two parameters?

**Comment by zabander** [comment]
I think I got more clearly what you explained but I get this error when calling a callback:
Failed to run onInputChanged callback: getFunctionArguments(): interpretPythonScript(import inspect
args_spec = inspect.getargspec(inputChanged)
 failed!
I'm using the Ext.py to call a simple funtion to print a message when the input is changed

**Comment by MrKepzie** [comment]
Please show me the code

**Comment by zabander** [comment]
#in the testExt.py

def inputChanged(inputIndex, thisNode, thisGroup, app):
     print "hello"
thisNode.onInputChanged.set("inputChanged")

**Comment by MrKepzie** [comment]
You have to set the callback on the group node in the createInstanceExt function (called right after the createInstance function)

#This is in MyPyPlugExt.py

def inputChangedCallback(inputIndex, thisNode, thisGroup, app):
	#...

def createInstanceExt(app,group):
        #Note that the callback belongs to the PyPlug to so we use it as prefix
	group.onInputChanged.set("MyPyPlug.inputChangedCallback")

**Comment by zabander** [comment]
@MrKepzie Thank you a lot!, now the script works, but I had to use a try and except which is something I dont like. Is there a way to validate if a node is connected in an input?

**Comment by MrKepzie** [comment]
Please show the code, I don’t see why you need a try catch

**Comment by zabander** [comment]
Yes, it is unnecessary, I did as you said without the try and except and works fine. thanks for the help, now everything works fine but the SeExp node that got bugged the last update I did. I just simple tryed a Cs1 == Cs2 and got an error, I opened another issue for that.
