### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [MrKepzie/Natron#916]
I would like to point out that identifiers like "[`_Engine_BezierCP_h_`](https://github.com/MrKepzie/Natron/blob/86a97fa6fa719c65ecc10687b832bf98c10c7c5f/Engine/BezierCP.h#L19)" and "[`__NATRON_FILEDOWNLOADER_H`](https://github.com/MrKepzie/Natron/blob/4f3b39504ebe7b13beb5bafda24f1a5bae515269/Engine/FileDownloader.h#L19)" [do not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not use identifiers that are reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by devernay** [comment]
I'm pretty sure this will help us getting military-grade certification for Natron!

**Comment by devernay** [comment]
And BTW this is not in the C++ language standard, but in the CERT C++ *coding* standards

**Comment by elfring** [comment]
Are there [a few update candidates](https://github.com/MrKepzie/Natron/blob/4f3b39504ebe7b13beb5bafda24f1a5bae515269/Engine/FileDownloader.h#L19 "Update candidate") left over after [your software update](https://github.com/MrKepzie/Natron/commit/121e8b40a057f428baedb03de0866a37b8355108 "Source code clean-up")?

**Comment by elfring** [comment]
I guess that [a bit more source code clean-up](https://github.com/MrKepzie/Natron/blob/364ec29f9797ba9d3d816fc85c36d6239f91b334/Gui/Gui.h#L44 "Update candidate") would be useful.
