### ISSUE TITLE
Timeline zooming, panning, and default range

### ISSUE THREAD

**Issue by devernay** [MrKepzie/Natron#917]
As reported by @azerupi in #870 :

- *Done* **Inter-frame graduations** I am not sure how useful that is since you can't put the time cursor between frames. I would remove them

- *Done, also in DopeSheet* **Zoom** I can't imagine a situation where you would need to zoom in more than 10 frames on the timeline. I would therefore limit the zoom level to have minimum 10 graduations (frames) on the timeline instead of the current 2 graduations. Especially if you remove inter-frame graduations

- *Done* **Default frame range** This is more of a preference but, I think a default frame range of **± 1-250** (10 seconds) would be better than the current 1-1

- *Done¨**Panning with middlemouse or alt-click** it would be great of you could pan left / right in the timeline with the middlemouse button like in the viewer and in the dope sheet

Other enhancements:
- **Zoom on frame range with right-click+drag** to focus on a specific range

- **Frame on project range with right-click** to show the whole project range

**Comment by manuelsongokuh** [comment]
for "PANNING WITH MIDDLEMOUSE OR ALT-CLICK", could better:
panning with middlemouse + alt click = move the range left or right.
ALT+CLICK-LEFT on timeline = set point of start of range
ALT+CLICK-RIGHT on timeline = set point of end of range
it's comfortable..(good) ?

**Comment by devernay** [comment]
no, before not all mice and trackpads have a middle button, and alt + left click replaces the middle button.
