### ISSUE TITLE
Chinese Language or Unicode Charset Support?

### ISSUE THREAD

**Issue by Nicksbest** [MrKepzie/Natron#918]
Hello developers,
I can't help but noticed that Natron doesn't have a good support for eastern characters like Chinese.The only Chinese characters that displays correctly is in the file browser.I can't input or use Chinese or Japanese while I'm in composing interface. So is there a plan to include international language support in Natron?Or should I change some options that enables this?
Thanks!

**Comment by MrKepzie** [comment]
This is hard for us to do for the following reasons:
- All Python related stuff must remain in english (parameter names, node script names etc…)
- Internationalisation of the interface requires all plug-ins to also translate their interface, which is hard to maintain 

Nevertheless we will put more attention into supporting other languages in the future. Right now this is not the high priority. 
A Chinese contributor would be welcome on the task;)

**Comment by devernay** [comment]
@Nicksbest internationalization (aka i18n) should not be too hard, but needs a lot of testing. After that, we can start work on localization (aka l10n), and we will make a call for translations.

**Comment by devernay** [comment]
This issue was moved to NatronGitHub/Natron#119
