### ISSUE TITLE
Color Correction Node: Feature Request - Ranges Off/On buttons

### ISSUE THREAD

**Issue by blackearth2014** [MrKepzie/Natron#919]
Could we get a feature in the Color Correction node to be able to disable any of the individual  tone ranges. I like to be able to turn off a Shadow adjustment while adjusting my Mid-tones and Highlights. As well as the other ranges with off/on buttons.

**Comment by devernay** [comment]
fixed by https://github.com/devernay/openfx-misc/commit/6a93820ac1b85cf77353d674fe80e2797bce11d9
