### ISSUE TITLE
Curves modifiers

### ISSUE THREAD

**Issue by ThomasMorley-T3D** [MrKepzie/Natron#920]
![20110715-blender-25-modifier-noise-ipo-curves-stars](https://cloud.githubusercontent.com/assets/11800663/10125157/0047922c-6530-11e5-928d-b311c004a105.JPG)

It would be great if you could use modifiers on the curve editor like in blender. You could crete all kinds of additional effects with this. Like handhelp camera motion, glitch effects etc.

**Comment by ThomasMorley-T3D** [comment]
I did use the expression editors on the transform nodes properties to get effects somewhat like camera shake but it is not very interactive. I guess some tweaks to the transform node could also make a great shake/glitch node too!
![shake](https://cloud.githubusercontent.com/assets/11800663/10125191/cb77fd38-6530-11e5-8511-a216730ce549.png)

**Comment by FB-NPG** [comment]
Well our Facebook - Natron Programmers Group has created a Shaker_NPG PyPlugin to fill in the gap until curve modifier can be created. Hope you all like it!

https://github.com/FB-NPG/PyPlugins/archive/master.zip

**Comment by devernay** [comment]
This issue was moved to NatronGitHub/Natron#120
