### ISSUE TITLE
Group Node crash on switch from output to input of group. Linux Mint 17.2 64 Bit OS

### ISSUE THREAD

**Issue by ThomasMorley-T3D** [MrKepzie/Natron#921]
![groupinput_crash](https://cloud.githubusercontent.com/assets/11800663/10125948/d078f6f0-654b-11e5-9b79-a544d591c9f4.png)

**Comment by ThomasMorley-T3D** [comment]
Natron Version 2.0.0
Copyright (C) 2015 the Natron developers
>>>Use the --help or -h option to print usage.<<<
Qt has caught an exception thrown from an event handler. Throwing
exceptions from an event handler is not supported in Qt. You must
reimplement QApplication::notify() and catch all exceptions there.

terminate called after throwing an instance of 'std::invalid_argument'
  what():  Index out of range
/home/tom/Natron2/Natron: line 33: 31902 Aborted                 "$DIR/bin/Natron" -style fusion "$@"

**Comment by ThomasMorley-T3D** [comment]
Sep 26 2015 Snapshot.

**Comment by MrKepzie** [comment]
Can you show us the graph or detail steps to reproduce the bug
