### ISSUE TITLE
Crash when adding a new reader node to a goroup node. Linux Mint 17.7 64Bit

### ISSUE THREAD

**Issue by ThomasMorley-T3D** [MrKepzie/Natron#922]
Natron Version 2.0.0
Copyright (C) 2015 the Natron developers
>>>Use the --help or -h option to print usage.<<<
/home/tom/Natron2/Natron: line 33: 32289 Segmentation fault      "$DIR/bin/Natron" -style fusion "$@"

**Comment by ThomasMorley-T3D** [comment]
Natron Version 2.0.0
Copyright (C) 2015 the Natron developers
>>>Use the --help or -h option to print usage.<<<
/home/tom/Natron2/Natron: line 33: 32289 Segmentation fault      "$DIR/bin/Natron" -style fusion "$@"

**Comment by MrKepzie** [comment]
https://github.com/MrKepzie/Natron/commit/0e10692466db8e4a04047930045a72214c3d7721
