### ISSUE TITLE
Render not outputting Constants

### ISSUE THREAD

**Issue by myromance123** [MrKepzie/Natron#933]
Hi,
I'm using Natron 2.0.0 snapshot from the 1st of October 2015, on Ubuntu 15.04 64bit.

No matter how I try to render my current project, it will output without the constants colors that I've included. It's a very small project so I'm including it here.

Rendering the TextOFX node goes without issue, but the constants do not appear even if the writer is directly attached to the Constant node. It is visible in the Viewer however and seems to animate the way I currently desire it to.

I am attempting to render an Image Sequence by saving as a .png with the name format of level_####.png

It's at 300 frames for a 60fps 5 second sequence. I would rather export it as a .mp4 or .mov  but none of the video rendering outputs work at all currently with WriteFFMPEG (crashes natron or outputs errors). I'll leave that for another bug submission though.

Am I doing something wrong with my writer or is this a bug? Hopefully this is an easy fix and just my incompetence at work. I appreciate any guidance or help here, and thank you for the awesome software :)

Download link for my .ntp file:
https://mega.nz/#!8shS1T5b!wHm74n_dxoN46pyuAJ5epQcwetDtBhfO7Q2d4bc64eY

A quick screenshot to see what I'm working with:
![levelbar_project](https://cloud.githubusercontent.com/assets/3523483/10235578/2d8878e8-68d0-11e5-8e24-5e4c71d40538.png)

If you'd like me to upload one of the image outputs, I can. It is literally just an empty png (at least before the TextOFX node enters the scene).

**Comment by olear** [comment]
WriteFFMPEG works here, do you have any error/debug info?

output with WriteFFMPEG using Quicktime/ProRes 444 on CentOS7: http://downloads.natron.fr/~olear/github/levelup.mov , no issues here.

Regarding WriteOIIO (png), if you select 'Opaque' in 'Input PreMult' you will get output, but you should also get it in default mode (?).

**Comment by myromance123** [comment]
Running Natron through the terminal, no errors seem to get posted when trying to render an MP4 file via WriteFFmpeg. In the editor though it outputs this:

    WriteFFmpeg2 error: the selected codec is not supported in this container.

Writing to a .mov would crash it, and nothing gets outputted in the terminal either. If I replace the constants nodes with a Read node (just a 1080p PNG file), it renders without crashing in .mov. But it does output this:

    [mov @ 0x7ff2a0012200] Encoder did not produce proper pts, making some up.

The end file is unusable. In SMPlayer it can't play the file, and in VLC it just shows a green screen throughout the 5 seconds.

Outputting to PNGs with the Read node (1080p PNG) instead of Constant nodes works, and I get the full 300 frames image sequence.

Does using Opaque remove the transparency? I need the transparency to be there for this to work in my project. Regardless, I changed it to Opaque and it crashed. This was the output:

    ./Natron: line 47: 11299 Killed                  "$DIR/bin/Natron" -style fusion "$@"

Thank you for trying to help me.

**Comment by myromance123** [comment]
I've just installed the newest snapshot from today October 2nd 2015. Apparently the error about the codec I was getting was due to my incompetence after all. After selecting .mp4 for the WriteFFmpeg node, I didn't notice that the codec was defaulting to ap4h. After changing the codec to mp4v, it renders successfully!

The mp4v codec does not respect transparency though, so I changed the Format to QuickTime/MOV (mov) and the codec to rle QuickTime Animation (RLE) and the output is a video with working transparency!

I can finally use this in Kdenlive as an awesome animated overlay. The issue with the constants not rendering still seems to be an issue, but I can create my own constants by using GIMP and the Read nodes, so I'm covered for now.

I'm very sorry for not being more educated on this, thank you for trying to help me. If you want to close this, you can. If you still want to look into the constant nodes not rendering issue, I'm willing to try different things.

**Comment by MrKepzie** [comment]
For the constant: Bear in mind that by default alpha = 0 in Constant. Maybe that is your issue

**Comment by myromance123** [comment]
Alright, the snapshot from yesterday I've confirmed I cannot get the constants working at all even after messing with the node and changing its RGBA values (they work fine in the viewer, but nothing gets written ever even if only the constant node is directly connected to the writer).

After restarting my computer, today's snapshot (2nd October 2015) works with constants just fine. If I reinstall yesterdays one, the issue returns. Since today's snapshot is the newer version, I'd say my problem is fixed. Thanks guys, I sincerely appreciate the help!

Keep up the good work :)

**Comment by TakeonMe** [comment]
In linux I used `cpulimit 100 -l -p pid_of_natron` and I managed to render well
