### ISSUE TITLE
Natron crashes when clicking on Refresh Info on the Info tab of a PyPlug-in

### ISSUE THREAD

**Issue by ThomasMorley-T3D** [MrKepzie/Natron#934]
Natron crashes when clicking on Refresh Info on the Info tab of a PyPlug-in
![screenshot from 2015-10-02 22 57 03](https://cloud.githubusercontent.com/assets/11800663/10261354/22028c32-6959-11e5-997a-6956be601fa5.png)

**Comment by ThomasMorley-T3D** [comment]
02 - Oct -15 Snapshot Natron 2.0 - On Linux Mint 17.2 64 Bit OS

**Comment by FB-NPG** [comment]
This is the error...
Natron Version 2.0.0
Copyright (C) 2015 the Natron developers
>>>Use the --help or -h option to print usage.<<<
/home/tom/Natron2/Natron: line 47:  9378 Segmentation fault      "$DIR/bin/Natron" -style fusion "$@"
