### ISSUE TITLE
Falure to create a rectangle node.

### ISSUE THREAD

**Issue by FB-NPG** [MrKepzie/Natron#936]
![screenshot from 2015-10-03 23 07 20](https://cloud.githubusercontent.com/assets/14950371/10266391/c0af4eea-6a23-11e5-9335-b86c40c728c5.png)

**Comment by FB-NPG** [comment]
02 Oct 2015 64 Bit Snapshot on Linux Mint 17.2 64 Bit

**Comment by blackearth2014** [comment]
Both the rectangle and radial is not loading, though they are enabled in the preferences. In these versions: Natron-201510032008-9f3f56094d13b6d36666b56c9109d10963ecf58c is from Oct 3, 2015 and Natron-201510040050-1e6eadd50e16f59a2411ea5c3daa19ff144dac98 Oct 4, 2015.
