### ISSUE TITLE
Rename Write node and command line rendering.

### ISSUE THREAD

**Issue by timurhai** [MrKepzie/Natron#938]
Hi.
I created a test scene for a command line rendering and it works.
http://cgru.info/software/natron

      natron -b -w "Write1" 1-1 "/cgru/examples/natron/scene.ntp"

Than i renamed Write node from "Write1" to "w_jpg" and it does not woks. Command

      natron -b -w "w_jpg" 1-1 "/cgru/examples/natron/scene.ntp"

finishes with a non-zero exit status and this error message in the last line of the output:

     ERROR: Natron: std::exception

First scene code that works:

		<item>
			<Plugin_label>Write1</Plugin_label>
			<Plugin_script_name>Write1</Plugin_script_name>
			<Plugin_id>fr.inria.openfx.WriteOIIO</Plugin_id>
			<PythonModule></PythonModule>

Scene code that does not work after rename:

		<item>
			<Plugin_label>w_jpg</Plugin_label>
			<Plugin_script_name>Write1</Plugin_script_name>
			<Plugin_id>fr.inria.openfx.WriteOIIO</Plugin_id>
			<PythonModule></PythonModule>

If i make equals Plugin_label and Plugin_script_name manually with text editor it works again:

		<item>
			<Plugin_label>w_jpg</Plugin_label>
			<Plugin_script_name>w_jpg</Plugin_script_name>
			<Plugin_id>fr.inria.openfx.WriteOIIO</Plugin_id>
			<PythonModule></PythonModule>

ps
i`ve created and executable script "natron" that just runs the latest version, for now:
/data/soft/natron/2.0.0-2015.10.02/Natron

**Comment by MrKepzie** [comment]
The documentation is clear in this regard, you have to pass the script-name of a Write node and not its label. That’s why in case 1) and 3) it works

**Comment by timurhai** [comment]
Ah. I see. Sorry.
btw
It will be much greater to make some check and print some clean error message.
( for example: Write node with a script name "w_jpg" was not founded in the project )
