### ISSUE TITLE
Latest build crashes on start-up

### ISSUE THREAD

**Issue by hpetrus** [MrKepzie/Natron#939]
The latest Linux build for all current Ubuntu variants crashes with error in bash shell, saying:

Natron2/bin/Natron: symbol lookup error: Natron2/Plugins/IO.ofx.bundle/Contents/Linux-x86-64/IO.ofx: undefined symbol: _Z18getSeNoisePluginIDRSt6vectorIPN3OFX13PluginFactoryESaIS2_EE

**Comment by MrKepzie** [comment]
Known, this is fixed already
