### ISSUE TITLE
Double click keyframe in dopesheet to move to that keyframe in timeline

### ISSUE THREAD

**Issue by myromance123** [MrKepzie/Natron#942]
Hi,

I've noticed double clicking the keys in the dopesheet currently does nothing. Would it be possible to make double clicking a single keyframe in the dopesheet have the current frame in the timeline jump to this selected keyframe?

It would make it easier to navigate the dopesheet keys when making edits. I'm on the current snapshot October 7 2015 and this feature is not here as far as I can tell.

Thanks for putting up with all my problems thus far, I appreciate it :)

**Comment by MrKepzie** [comment]
Will do

**Comment by MrKepzie** [comment]
Should it seeks the timeline too even if clicking in the middle of nowhere ?

**Comment by myromance123** [comment]
Seeking in the timeline even if clicking on an empty area of the dopesheet would be a preferred reaction as well.

You work really fast! Thank you for bringing in this feature so quickly, :+1:
