### ISSUE TITLE
Natron Snapshots + RC v.2 scroll bug

### ISSUE THREAD

**Issue by sirdavid32** [MrKepzie/Natron#943]
Hi, I download every snapshot and today the RC v2 of Natron.
I make changes in the layout. Save the Layout into (user)/documents/natron layouts/mylayout.nl
I use floating panels. Create my compo. Close natron.
The next time I open Natron using my Layout as default, appears this scroller over the FILE - EDIT options in the menu on the upper left part of the layout. There´s no property open or no way to close it.
Please help in fixing that bug.
Thanks.

*italic Ps1: I don´t work with PROJECT PROPERTY (so I close that tab -maybe this is the reason why it comes back when natron restarts?-) I find it extremely stange to -forever- attach project properties to a part of a layout when it should be a floating window when "S" is invoked over the node graph.*

Ps2: Floating panels, now open relativelly well the first time (on their parameters and proportions to it´s properties) but the second time they´re open (by CTRL+double clicking on them) they appear reduced (just like previous versions) to almost 200px by 200 px. Please help.

Thanks.

![scroller](https://cloud.githubusercontent.com/assets/11066585/10374812/a06904a6-6dba-11e5-9572-204d7fde7b00.jpg)
![pesky](https://cloud.githubusercontent.com/assets/11066585/10374866/0e98fcd8-6dbb-11e5-9789-5d4dcda0b56a.jpg)

**Comment by MrKepzie** [comment]
I have fixed the second issue. I'm not sure about the 1st one since I cannot reproduce. Can you test with a snapshot in a few hours ?

**Comment by sirdavid32** [comment]
Ok. I'll record it tomorrow.

**Comment by sirdavid32** [comment]
Okay, here´s the behavior report:
https://youtu.be/Ks8jFe9VbRY
I´m downloading today´s snapshot to see if this went away. Basically the property bin is the one bugging (which appears as a floating scroller over the FILE menu).
