### ISSUE TITLE
OpenFX not included in tarball

### ISSUE THREAD

**Issue by cwilling** [MrKepzie/Natron#944]
If I try building from source tarball, it has no git information. Therefore I can't run 'git submodule update -i --recursive', as instructed in INSTALL_LINUX.md, therefore I have nothing in OpenFX directory etc.  Can all these updates be included in the source tarball please? I can do it myself by cloning the Natron git repo here but I'm trying to make (for unsupported platform) a build script for that uses the official source tarball.

**Comment by olear** [comment]
Fixed.

What unsupported platform are you building on?

**Comment by cwilling** [comment]
Building on Slackware Linux.
Thanks for the extra tarball - compiling as I write this.
One problem with new tarball was that wget complained that resulting url was too long so I had to use browser to download it. That's not so good for a build script that includes downloading the tarball. Is that easy to change so wget would work?

**Comment by olear** [comment]
Github mangles the url when using wget etc.

Btw, I test on Slackware, official binaries work just fine.

**Comment by olear** [comment]
Just do a
```
wget https://github.com/MrKepzie/Natron/releases/download/2.0.0-RC1/Natron-2.0.0-RC1.tar.gz -O $TMP/Natron-2.0.0-RC1.tar.gz
```
in your SlackBuild (or whatever).

**Comment by cwilling** [comment]
That wget is better (no complaint about length) but now:
Connecting to github-cloud.s3.amazonaws.com (github-cloud.s3.amazonaws.com)|54.231.65.33|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2015-10-09 11:01:16 ERROR 403: Forbidden.

**Comment by olear** [comment]
Works here, could be connection issue with github.
```
wget https://github.com/MrKepzie/Natron/releases/download/2.0.0-RC1/Natron-2.0.0-RC1.tar.gz -O Natron-2.0.0-RC1.tar.gz
--2015-10-09 03:04:41--  https://github.com/MrKepzie/Natron/releases/download/2.0.0-RC1/Natron-2.0.0-RC1.tar.gz
Resolving github.com (github.com)... 192.30.252.128
Connecting to github.com (github.com)|192.30.252.128|:443... connected.
HTTP request sent, awaiting response... 302 Found
```

**Comment by cwilling** [comment]
It works now - I had to turn wget's content-dispostion option off.
BTW the build has finished without major problems. I had to massage some Makefiles to remove looking for cairo.a files; also had to add QtCore & QtGui subdirectories to some -I/usr/include/PySide directives. I'll check my PySide installation before I complain about it though :)
Thanks for your help.
chris

**Comment by olear** [comment]
We force static cairo on NatronRenderer, you can of course change this in global.pri.

Also see https://github.com/MrKepzie/Natron/blob/workshop/tools/linux/include/natron/config.pri and https://github.com/MrKepzie/Natron/blob/workshop/tools/linux/include/natron/config_py3.pri

**Comment by cwilling** [comment]
Yes, changing global.pri solved the static cairo problem.

Interestingly, tools/linux/include/natron/config.pri had exactly the correct pyside configuration but using it to replace existing pyside stanza in global.pri didn't work. Instead, I put it in top level config.pri and now Makefiles all have the correct pyside paths.

Thanks again.

I like your Bob-like avatar too - very Slack.
