### ISSUE TITLE
Interface text troubles in Natron 2.0

### ISSUE THREAD

**Issue by lcenzoredl** [MrKepzie/Natron#946]
http://joxi.ru/Vrwo3V4UvGWorX
It's everywhere, not only in project settings.
RC1 and latest snapshot too.

**Comment by blackearth2014** [comment]
LCENZOREDL

By any chance that your Droid Sans font got deleted and your system is trying to substitute it with another font? Did you do a clean install on your Windows or Linux operation system of Natron?

**Comment by MrKepzie** [comment]
Try to go in Preferences of Natron and click on “Restore defaults”. 
If that does not work please indicate your platform for further help

**Comment by lcenzoredl** [comment]
Thank you, MrKepzie. It worked.
