### ISSUE TITLE
"F" shortcut key: smal issue

### ISSUE THREAD

**Issue by blackearth2014** [MrKepzie/Natron#947]
The F shortcut key does not scale and center your image(s) in the viewer. You still have to center and scale up to a non exceeding size in the viewer.

**Comment by blackearth2014** [comment]
Further research shows that this only happens when you have two layers merged together and when you press the "F" key, it seems scales to the largest image ROD and not the project resolution size.

**Comment by MrKepzie** [comment]
this is intended

**Comment by MrKepzie** [comment]
so that this is easy to work with images that differ from the project size
