### ISSUE TITLE
Error after open a just saved file. Bad path for ReadFFmpeg

### ISSUE THREAD

**Issue by genete** [MrKepzie/Natron#950]
Using Natron 2.0RC1
OS X 10.10.3
Steps to reproduce:
1) Start Natron
2) Create a ReaderFFmpeg node
3) Select a movie (.mov, 1920x1080, AAC, H264, 99 MB size) Path: Users/carlos/Desktop/PabloColumpio.mov
4) Save project. Path: Users/carlos/Desktop/pablo.ntp
5) Close Natron
6) Open Natron and open saved file -> Error
See error message:
![captura de pantalla 2015-10-11 a las 13 59 54](https://cloud.githubusercontent.com/assets/346755/10416716/b21ef6ba-7021-11e5-8ea1-b7b17e856e4b.png)
Notice the double home path used.

**Comment by genete** [comment]
I can't use Natron due to this error.

**Comment by MrKepzie** [comment]
I cannot reproduce the bug with the steps your indicated.

**Comment by devernay** [comment]
@genete why is there no "/" before "Users" in your path, step 3?

**Comment by devernay** [comment]
can you share with us the resulting ntp file?

**Comment by genete** [comment]
I want to rewrite the steps to reproduce:
1) Start Natron
2) Create a ReaderFFmpeg node (it prompts to open a file)
3) Select a movie (.mov, 1920x1080, AAC, H264, 99 MB size) 
(Path copied from Natron's open file dialog): Users/carlos/Desktop/PabloColumpio.mov
4) Save project. (Path copied from Natron's open file dialog): /Users/carlos/Desktop/pablo.ntp
4.1) Move reader node's place a little bit so document is dirty.
5) Close Natron. It asks for save the modified file. I say yes, save.
6) Open Natron and open saved file -> Error

**Comment by genete** [comment]
Here is the file:
https://drive.google.com/file/d/0Bx8g_H3f7qpZTTBGbGtfRzhLazA/view?usp=sharing

**Comment by MrKepzie** [comment]
Can you restore preferences of Natron to their default ? And also can you do a screen recording of the bug ? I'm unable to reproduce it myself

**Comment by genete** [comment]
Here is the link of the screen recording:
https://drive.google.com/file/d/0Bx8g_H3f7qpZdWVCUjlBYldNWWM/view?usp=sharing

**Comment by MrKepzie** [comment]
The bug is that somehow the first time you create the ReadFFMPEG node, it does not have a preceding "/" as first root of the path. Hence when loading the project, Natron  thinks the path you provide is a *relative* path and prepends the project path. 

What I'm wondering is how in the first place the media is reading ok for you, since that when I try that on OS X it won't load the file

**Comment by genete** [comment]
@MrKepzie: But when you try that on your OS X. Do you get the path to load the media with or without the "/"?
In my case the key point is the 4.1 step. If I don't do that, it loads without problems, so something is doing wrong when saving a modified file.

**Comment by MrKepzie** [comment]
The issue is that at some point in the file dialog (or in the filename edit) you entered an invalid location (i.e not starting with “/“). 
Then secondly, reading the file without a starting “/“ should fail, but somehow on your station in does not.

Anyway, simplest fix is to erase all preferences. Just remove the following files

/Users/<username>/Library/Preferences/fr.inria.natron.plist
/Users/<username>/Library/Preferences/com.inria.natron.plist

**Comment by genete** [comment]
I did no enter any invalid location. The location is **offered** to me by the open file dialog and **I don't change it**, just click the file to read and press the open button.

I have deleted the two preferences files as suggested and the issue is repeteable exactly the same.

Notice that the action Image>Readers>ReaderFFmpeg delivers to a open file dialog that offers a bad path. It also happen with the normal image reader and the rest of readers.
 
Can you confirm what's the first folder offered for that file open dialog after a preferences cleaning in your  case? In my case the offered path is this:
"Users/carlos/Desktop/"

What is an invalid path and so it is a bug.

**Comment by MrKepzie** [comment]
I will try to look into it, with fresh install on OSX I properly get the initial '/'

**Comment by MrKepzie** [comment]
In this commit https://github.com/MrKepzie/Natron/commit/14ec4f215152a15587bf42c19700e54a838e742a the file dialog can no longer have paths not starting with a drive name.
