### ISSUE TITLE
Color Picker

### ISSUE THREAD

**Issue by Sergusster** [MrKepzie/Natron#956]
It is not a big secret, that compositing is all about manipulating color values. And at the moment adjusting RGB color values with current ancient color picker (Windows) is REALLY clumsy. Can we ever hope to see something like this?
![2015-10-13 04-16-26](https://cloud.githubusercontent.com/assets/4726895/10443147/95e5bb54-7162-11e5-9b61-5cfc22885d8b.png)

**Comment by MrKepzie** [comment]
See https://github.com/MrKepzie/Natron/issues/185
