### ISSUE TITLE
Crash on project open.

### ISSUE THREAD

**Issue by tayotain** [MrKepzie/Natron#957]
everytime i make compositoion (new) with these files i have i get crash when i try to open that project. it only happens when i try to do it with some files. very frustrating cause i need to do these on other aplication.
Dont know what causes these files to make this behavior. Some projects work fine. also with these files trying to change project framerate crashes natron.

https://www.dropbox.com/s/8rvldnox31uhdnx/natron_crashreport.rar?dl=0

**Comment by MrKepzie** [comment]
Thanks for the report.
I’m able to load your project correctly here, it does not crash. 
I see that you are storing your comp in your H:\Dropbox drive, could you try and move the comp to another Drive and see if the crashes persist?

**Comment by tayotain** [comment]
This is what i see on CMD 

copied project file to other drive but didnt help. 
other projects work fine.

![crash](https://cloud.githubusercontent.com/assets/15104981/10455353/71efbcca-71c3-11e5-9936-53598349a13d.jpg)

**Comment by MrKepzie** [comment]
Can you try with a recent snapshot please:

http://downloads.natron.fr/Windows/snapshots/64bit/files/Natron-431c59584d4b95aad3d1498d71c7c9145d3dbd73-Windows-x86_64bit-setup.exe

The issue might be already solved.

**Comment by tayotain** [comment]
Tried ne build but no go....
But Found this:

-Loaded project from separate folder. (reader were empty).
-updated readers with correct files.
-All but first readnode worked (laivojen_hautuumaa######.exr)
-If its connected to ahuffle and loading laivojen_hautuumaa######.exr to it, natron crashes.
-plugging it off, adding correct file plugging in and it didnt crash. :P 

So its "laivojen_hautuumaa######.exr" file crashing on project loading or its shufflenode or Matte .png file doing the crash.

**Comment by tayotain** [comment]
Ok. i only need to add "laivojen_hautuumaa######.exr"  to first reader and crash. So its that sequence that does it.

**Comment by tayotain** [comment]
Added merge between reader and shuffle and now i can load project file again. :D
![helping_merge](https://cloud.githubusercontent.com/assets/15104981/10456952/8e2f35a6-71cc-11e5-9d5f-3d1a9eb38b33.jpg)

**Comment by MrKepzie** [comment]
At what point during the loading of the project does the crash occurs ? What is displayed on the splashcreen ? Can you do a screen recording ?

**Comment by MrKepzie** [comment]
Ok I have reproduced the bug. I attempted a fix in a recent commit. Can you try with a snapshot in about 2 or 3 hours ?

**Comment by tayotain** [comment]
Hi! Sorry for delay. I try to check it today.

**Comment by tayotain** [comment]
thanks for checking and fixing but gotta go now. i check it when im back to office.

**Comment by tayotain** [comment]
OK!
Tested latest snapshot and NO PROBLEMS so far! :) 
Good good!

Thanks for fix and developing this very nice software!
