### ISSUE TITLE
OCIO config related GUI issues

### ISSUE THREAD

**Issue by mash-graz** [MrKepzie/Natron#958]
there are some nasty bugs concerning ocio configuration options in natron (actual version 2.0.0 Snapshot):

1.) when the config.ocio is set to an huge hierarchic list of colorspaces and my mouse hovers over any "input colorspace"/"output colorspace" chooser (e.g. in settings for a file reader node) instead of an appearing tool tip my window manager (cinnamon) gets killed. it could be related to the huge amount of [useless] entries in this tool tip -- it's bigger than the screen size! but this could be an cinnamon bug likewise.

2.) when i try to change the config.ocio for a node. the choosers for "input colorspace" and "output colospace" don't show the usual pop-up choosers but simple text filed. i have to enter any nonsense to them, to get an error message and the the usual widget for choosing in a list appears again. but it's still not usable! most of the entries are in very strange order, some repeating others missing etc.
i have to save the project and restart the application, than it works again.

3) the ocio configuration via edit->preferences...-menu also shows a nasty issue:
when you use it to change the config.ocio and the check box "Warn on OpenIO config changes" is active, you get this warning to restart the application, but as a side effect the Preferences window will be immediately hidden under the window of the main application and you do not see the button to save your preferences changes anymore. :(

please contact me, if you need any additional details to reproduce this issues.

**Comment by devernay** [comment]
You are right, there are lots of bugs when using a custom config.ocio

Will look into it (but not before thursday)

1) why do you say these entries are useless?

**Comment by mash-graz** [comment]
On 2015-10-13 16:59, Frédéric Devernay wrote:
> Will look into it (but not before thursday)

it doesn't hurry at all!

> 1) why do you say these entries are useless?

it's usually to much to read in a tool tip.

the hierarchy of the choosing widged and the tool tips on its leaf nodes 
are much more useful in practice IMHO.

thanks
martin

**Comment by devernay** [comment]
Fixed:
- if there is help for more than 40 items, help for items is not put in the tooltip (but it is still there if there are less than 40 items, e.g. for the operator in Merge)
- "OCIO Config Help" button was crashing Natron if the config.ocio contained too many entries
- hierarchical choice menus were broken
- a few other bugs were fixed
