### ISSUE TITLE
Hiding the console

### ISSUE THREAD

**Issue by voyager25** [MrKepzie/Natron#959]
On Windows, the console currently stays open during a Natron session, this leads to unnecessary clicks when switching to the Natron window. A possible solution would be hiding the console by default, and adding a "Toggle Console" button in the "Display" menu, like in Blender.
(Natron version 2.0.0rc1)

**Comment by MrKepzie** [comment]
I've implemented it

**Comment by GregTheHun** [comment]
Where is this implemented?
