### ISSUE TITLE
Ramp Node: Overlays missing

### ISSUE THREAD

**Issue by blackearth2014** [MrKepzie/Natron#960]
Ramp node is missing its viewer overlay interact controls.

![ramp node missing overlay interact controls](https://cloud.githubusercontent.com/assets/7956901/10474686/b12cb0ac-7207-11e5-9639-bb62559a9fb2.png)

**Comment by MrKepzie** [comment]
Fixed via https://github.com/devernay/openfx-misc/commit/b0f40a0c77faef7776f0d5ac9f09652a541dd1c2
