### ISSUE TITLE
error with writer FFmpeg

### ISSUE THREAD

**Issue by MarcRose** [MrKepzie/Natron#963]
Hello.
I have an error with the writer node FFmpeg.
There is only one project open and only one render.
How can I fix this?

Thank you

OSX 10.9.5
Natron 2 RC1

here's a print screen of the error.
![error writer ffmpeg](https://cloud.githubusercontent.com/assets/13001616/10508636/911a6f8a-7328-11e5-984c-541283a386fb.png)

**Comment by MrKepzie** [comment]
I'm having a hard time to reproduce the bug. Can you show a screen cast where you reproduce the bug ?

**Comment by MarcRose** [comment]
Screen cast is here
https://youtu.be/15fm2Sg8SwE

**Comment by MrKepzie** [comment]
You are not supposed to pass a '#' to the output filename, because Natron will remplace it by the frame number, hence attempt to write multiple files. 

Unrelated by I remark a black screen at the start when you load your project, does it happen always ?

**Comment by MarcRose** [comment]
Yes, just for this project.

**Comment by MarcRose** [comment]
it works ok ! thank you !
