### ISSUE TITLE
Linux: using NatronSetup from CLI, without a Gui

### ISSUE THREAD

**Issue by rcspam** [MrKepzie/Natron#964]
Is it possible to enhance linux 'NatronSetup' to launch and automate an update from command line without GUI neither questions.

**Comment by olear** [comment]
Will check if supported in qtifw, if not I can probably make a stripped-down console version.

**Comment by rcspam** [comment]
Viva @olear ;)

**Comment by rcspam** [comment]
Hi all,
Ok if we wait the 3.0 milestone, the first real update from cmd line will be to upgrade to Natron 4.0 ?! ;)

**Comment by devernay** [comment]
This issue was moved to NatronGitHub/Natron#122
