### ISSUE TITLE
strange error with merge and mode over

### ISSUE THREAD

**Issue by zabander** [MrKepzie/Natron#969]
Hi! I have this issue with the merge node.
I just connected a group where I created a lightwrap to a BG with the merge, the alpha of the group is solid, as you can see in the image and the bg...well is just a simple image. The effect of the lightwrap dessapears in the merge. It somehow works fine with conjoint-over mode...but it should work with over perfectly.

I'm using the lasted windows 7 snapshot (Oct 16)

![error_merge_over](https://cloud.githubusercontent.com/assets/1145623/10555097/b1c54d4c-742f-11e5-954c-e1ee2ebe4f1d.jpg)

**Comment by MrKepzie** [comment]
Can you send me the project with images ?

**Comment by zabander** [comment]
Sure, may you give me your email address?

**Comment by zabander** [comment]
I sent you an email, can you confirm that you received  it?

**Comment by MrKepzie** [comment]
Merge over is A + B * (1 - a) but here you have in the tail of the beaver alpha values > 1, so instead of layering A over B it also removes some color of B. You should clamp alpha values to 1

**Comment by zabander** [comment]
Thank you  @MrKepzie , didn't realized about it!
