### ISSUE TITLE
Natron Snapshot Oct 16 - Tracker is dead

### ISSUE THREAD

**Issue by sirdavid32** [MrKepzie/Natron#970]
Hi, I´m using the Tracker PM to stabilize a shot, but pressing CTRL+ALT on the viewer doesn´t create a Tracker. Also, It´s not drawn even though I create it with the floating property panel open, on the viewer. 
![not-visible](https://cloud.githubusercontent.com/assets/11066585/10562346/701b8552-751d-11e5-8029-53e498a30c62.png)

**Comment by MrKepzie** [comment]
This was an issue when settings panel was floating. Download upcoming snapshot to get the fix
