### ISSUE TITLE
Mac Natron-201510180524-4a85ba955ccde42dfd7df79bfd68253a6909ade2: Crashes on launch

### ISSUE THREAD

**Issue by blackearth2014** [MrKepzie/Natron#971]
Error report 1 in gist: https://gist.github.com/blackearth2014/d587b09e28d4927630b4

Error report 2 in gist: https://gist.github.com/blackearth2014/4699c09ccdbfc3d9ce5e

Error report 3: same as above - Natron-201510182348-d012d10125eb12113a916b8d1ec1f8814875d68b

The same issues are from my 897, 897 & 901 crash reports are happening again with the two snapshots listed above.

The image below is what is showing in the terminal window when I am launching the latest Natron.
![crash terminal](https://cloud.githubusercontent.com/assets/7956901/10570578/560dcb7a-7603-11e5-8c5c-f6bbacb73418.png)

**Comment by MrKepzie** [comment]
this will be fixed, this is  a plug-in deployment issue

**Comment by blackearth2014** [comment]
There has been 4 releases today and they all crash with the problem. IT seems like the plugins for the Mac platform are becoming a major issue. Or, are they third party plugins that are the problem?

**Comment by blackearth2014** [comment]
This Natron-201510191458-2f1f096a79221f7934c27cded473ab68e8bc88f5 version is crashing too.
