### ISSUE TITLE
Abort rendering

### ISSUE THREAD

**Issue by nitsch** [MrKepzie/Natron#974]
I do not seem to be able to [abort](http://openfx.sourceforge.net/Documentation/1.3/ofxProgrammingReference.html#OfxImageEffectSuiteV1_abort) a plugin during rendering in Natron. Is there currently even a mechanism implemented to do this? I expected the Escape key to do the trick but that does not seem to abort anything. The same plugin reacts to pressing Escape in NUKE -- even though NUKE immediately issues a new render action which makes it kind of useless.

I tested this with Natron 2.0.0-RC1 and previous releases on Windows.

**Comment by MrKepzie** [comment]
abort() is a function you should check periodically to determine if Natron wants your plug-in to abort processing or not. 
It is implemented and works correctly depending on many parameters. You can see the internal implementation in:

EffectInstance::aborted()

**Comment by nitsch** [comment]
> abort() is a function you should check periodically to determine if Natron
> wants your plug-in to abort processing or not.
> It is implemented and works correctly depending on many parameters.

My question was more about the user interface side. Can the user abort by
pressing the Escape key for instance?

**Comment by MrKepzie** [comment]
The user can abort either by changing a parameter, or the timeline current frame or the nodes connections, etc…
Basically anything that has an impact on the output image will trigger an abort.

During playback, the user can abort with the stop button of the player.
Note that zooming or panning the viewer does NOT abort any computation
