### ISSUE TITLE
seg fault

### ISSUE THREAD

**Issue by Jau-Al** [MrKepzie/Natron#975]
Hello,

I just tried to open a project I saved some minutes ago bug Natron crashed while opening it. I saw the project opening for, maybe 1sec then it crashed.
I'm under Ubuntu 14.04 x86_64.

Output : 
`init.py script not loaded
initGui.py script not loaded
/usr/bin/Natron : ligne 47 :  4634 Erreur de segmentation  (core dumped) "$DIR/bin/Natron" -style fusion "$@"`

**Comment by MrKepzie** [comment]
Can you try on a recent snapshot:

http://downloads.natron.fr/Linux/snapshots/64bit/files/Natron-latest-Linux-x86_64bit-snapshot.tgz
