### ISSUE TITLE
not refresh in node graph: switch input 1 and input 2..?

### ISSUE THREAD

**Issue by manuelsongokuh** [MrKepzie/Natron#976]
i did try keyboard: shirft + x changed worked but not refresh in node graph..
maybe it's bug.. natron 9b8abe3fc4517cfce2d9fdb65966ea7b06e3f032

**Comment by MrKepzie** [comment]
This is a know bug, see https://github.com/MrKepzie/Natron/issues/815

**Comment by manuelsongokuh** [comment]
ok. thank you.
