### ISSUE TITLE
Roto not refreshing

### ISSUE THREAD

**Issue by manuelsongokuh** [MrKepzie/Natron#977]
natron https://github.com/MrKepzie/Natron/commit/9b8abe3fc4517cfce2d9fdb65966ea7b06e3f032

see my record screen:
https://mega.nz/#!LwUX3Q6D!SPR_mfy7hP_uWxNsGuy9Ae6zd-uhQbDowZqVA5nHrI8

i think is from nature of natron inside..

**Comment by MrKepzie** [comment]
Can you send me the project ?

**Comment by manuelsongokuh** [comment]
ok, what is your email?

**Comment by manuelsongokuh** [comment]
https://mega.nz/#!3wpxWToZ!31xH_7pdLMiD44ZJoVPvE548wzqr6tINz1sFYZ1wLOI

**Comment by MrKepzie** [comment]
I do not understand your issue ? The problem is that you are not viewing the tab (in the viewer pane) corresponding to the viewer node you are connecting. Try splitting the tabs and you will see that they refresh correctly

**Comment by manuelsongokuh** [comment]
ok, issue: viewer is not refresh or update incorrect from roto rectangle..when i try off of layer of roto and on (icon "eye") viewer is refresh..
now i do recoerd screen..

**Comment by manuelsongokuh** [comment]
maybe i find result but is not sure.
when open my project ntp, but viewer is not updated from all nodes render..
resolve: i click button "forces a new render of the current frame." this is update render frame..
maybe best: when natron starts or opens my project needs update before to ready to use instead i click "forces a new render of the current frame."

because when i open my project it's not update to all viewer..
it's possible to force new render to start to natron for default?
(sorry for my english..)

**Comment by MrKepzie** [comment]
There was indeed a small bug on startup where only the viewers in the main-nodegraph would be refreshed. Others that were inside a group would not be refreshed.

**Comment by manuelsongokuh** [comment]
ah ok but it's small bug? or you did fix it?
