### ISSUE TITLE
Preferences - Node Graph option 

### ISSUE THREAD

**Issue by sirdavid32** [MrKepzie/Natron#978]
Hi, could it be possible to make the nodegraph background be changed by a custom color?
There are some parameters already that can be customized, and NodeGraph background could be inside those options, please? Thanks.
![nodegraps](https://cloud.githubusercontent.com/assets/11066585/10646150/36357c1c-77f7-11e5-8e10-53478a62e579.png)

**Comment by MrKepzie** [comment]
This is possible from the preferences. Since the underlying QGraphicsView is caching the painting of the background, you have to zoom or do anything in the nodegraph to refresh it once you have modified the preference.
