### ISSUE TITLE
Bilateral Guided Blur: Error issues

### ISSUE THREAD

**Issue by blackearth2014** [MrKepzie/Natron#979]
Natron Bilateral Blur node is showing an error in the node graph. For some odd reason this node Guide input needs an image with an Alpha Channel in order to process the effect. So in the ReadOIIO node, I had activated the alpha channel. Is this an error/bug or is the Bilateral Guided node suppose to work this way?

![bilateral blur - error issues](https://cloud.githubusercontent.com/assets/7956901/10711338/ee24ec2c-7a45-11e5-8744-1df1a0857a09.png)

**Comment by MrKepzie** [comment]
Fixed in https://github.com/devernay/openfx-misc/commit/1e3f72587e5900494621340a70fabd9b1b95970f
