### ISSUE TITLE
Natron 2.0 RC2: Keep crashing when trying to use the reveal tool and paint in another background image

### ISSUE THREAD

**Issue by blackearth2014** [MrKepzie/Natron#980]
Here is the Error Report at https://gist.github.com/blackearth2014/8c8b2449b4ebad21bf6c.

**Comment by MrKepzie** [comment]
Can you post a screen-cast to reproduce the bug ,?

**Comment by blackearth2014** [comment]
I will in a couple of hours. Just going to bed.

**Comment by blackearth2014** [comment]
I had rebooted my system and all is well thus far.
