### ISSUE TITLE
cancel NatronRenderer using Ctrl+C in shell

### ISSUE THREAD

**Issue by cg-cnu** [MrKepzie/Natron#984]
Is there a way to cancel the NatronRenderer operation in the command line?
Lets say I typed in **NatronRenderer /path/to/test.ntp** and hit enter, I expected **ctrl+C** to cancel the task but it didn't.

**Comment by MrKepzie** [comment]
https://github.com/MrKepzie/Natron/commit/f57824e2288242587295313e38962c33ff3733f3
