### ISSUE TITLE
Properties panel max panels opened is buggy 

### ISSUE THREAD

**Issue by mathiastesar** [MrKepzie/Natron#985]
Hi,
j ai constate qq problemes de refresh cote UI.
Les vues ne semble pas toujours se rafraichir, j ai de maniere recurrente les problemes suivants.

Onglet Properties
Au bout d un certain temps d utilisations dans des comp le champ du nombre maximum de vues dans l onglet properties ne fonctionne plus.

Nodegraph
L UI ne raffraichi pas bien quand il commence a y avoir un certain nbr de noeuds. Exemple: Rectangle de selection qui ne disparait pas ou nouvel selection d item qui ne highlight pas sauf quand on zoom en scrollant (le refresh a lieu).

**Comment by MrKepzie** [comment]
Node graph:  https://github.com/MrKepzie/Natron/issues/815 Qt-bug, we have to re-write without it
Properties: c'est à dire ? Tu ne peux plus interagir ou bien il y a un nombre de panels ouverts qui ne correspondent pas au nombre indiqué

**Comment by mathiastesar** [comment]
Hi mate,
eh bien le champ ne repond plus. Si il est a 10 par defaut par ex tu peux
mettre 1,5,20 il ne se passe plus rien mm apres avoir vider les caches.
Alors ce probleme je n ai jamais reussi a le reproduire mais il arrive
regulierement.

2015-10-29 13:49 GMT-04:00 Alexandre Gauthier <notifications@github.com>:

**Comment by MrKepzie** [comment]
Ok je vais voir.

Par contre pour le coup du NodeGraph si tu as un moyen systématique de le reproduire le bug hésite pas, je n’arrive que très rarement à le reproduire et je ne sais pas quelles sont les conditions qui font que ca ne marche plus

**Comment by MrKepzie** [comment]
Je n'arrive pas à la reproduire. Tu me diras si ca t'arrives encore sur la RC3

**Comment by mathiastesar** [comment]
yes pas de pb !
Effectivement j ai eu le probleme de maniere assez aleatoire.
Te dirais ;^)

Le 2 novembre 2015 10:36, Alexandre Gauthier <notifications@github.com> a
écrit :
