### ISSUE TITLE
Add mime types to copy/paste Natron nodes between projects of 2 separate process

### ISSUE THREAD

**Issue by mathiastesar** [MrKepzie/Natron#987]
It would be great to have the ability of copy/paste  some nodes from a natron file to another

**Comment by MrKepzie** [comment]
Can you describe exactly what's needed ? 
Currently you can:

- Copy/paste between 2 separate opened projects (if not then this is a bug)
- Copy/paste between groups

**Comment by mathiastesar** [comment]
Hi !

   - Copy/paste between 2 separate opened projects (if not then this is a
   bug)

   ;^)


2015-10-29 13:51 GMT-04:00 Alexandre Gauthier <notifications@github.com>:

**Comment by MrKepzie** [comment]
What node are you trying to copy paste ? A group ? Multiple nodes ?

**Comment by mathiastesar** [comment]
just a node from the nodegraph, but even with multiple nodes or a group it
doesn t work.

2015-10-29 13:55 GMT-04:00 Alexandre Gauthier <notifications@github.com>:

> What node are you trying to copy paste ? A group ? Multiple nodes ?
>

**Comment by MrKepzie** [comment]
Is it the same Natron process ?
Did you just click “New Project” or “Open project” from the menu or did you launch a separate Natron instance ?

On 2 separate process it will not work as we did not implemented the clipboard mime types.
On the same process it should work. If it does not please tell me what are the steps to reproduce it

**Comment by mathiastesar** [comment]
Hi ! Indeed, it works fine when in the same process.
mat


2015-10-29 14:01 GMT-04:00 Alexandre Gauthier <notifications@github.com>:

> Is it the same Natron process ?
> Did you just click “New Project” or “Open project” from the menu or did
> you launch a separate Natron instance ?
>
> On 2 separate process it will not work as we did not implemented the
> clipboard mime types.
> On the same process it should work. If it does not please tell me what are
> the steps to reproduce it
>
