### ISSUE TITLE
Hard Coded sRGB Transforms will Fail

### ISSUE THREAD

**Issue by sobotka** [MrKepzie/Natron#988]
Hard coded sRGB transformations as in Lut.h will fail miserably when the reference space is not sRGB / 709 primaries based. These should be avoided at all costs.

https://github.com/MrKepzie/Natron/blob/121e8b40a057f428baedb03de0866a37b8355108/Engine/Lut.h#L469-L487

**Comment by devernay** [comment]
we know about this, and you can use OCIODisplay for that purpose. The functionalities of OCIODisplay may well be integrated in the Natron viewer at some time.

**Comment by devernay** [comment]
Note that all transforms should now be clearly documented, both in the source code and in plugins (eg ChromaBlur etc). Please point out if I missed something.

**Comment by sobotka** [comment]
Is there a clear path for toggling between display referred algorithms (EG 80% of Adobe PDF blend modes) and scene referred algorithms?

**Comment by devernay** [comment]
??? Aren't blend modes just arithmetic operations? They work in scene linear space, whatever it is.

**Comment by sobotka** [comment]
Almost every Adobe PDF canonized blend mode is for based on display referred concepts. Try screen for example with scene referred content. http://blender.stackexchange.com/questions/56960/why-does-the-screen-node-turn-hotspots-pink-and-blue

The bottom line is that ideally all nodes operate scene referred values. In Nuke, there is a nasty titled toggle called "Video Space" which while being a horrifically mangled term, makes it viable to flip to display referred formulas.

The AdobePDF Specification lists them all. Look for unity (1.0) values to spot the mangling.

As per the Cinematic Colour PDF, remember there are two linear encodings: Display linear (display referred to linear) and Scene linear (scene referred).

**Comment by sobotka** [comment]
I would also emphatically try to point out that "scene linear space" is likely junk jargon picked up from some rather unfortunate Blender developer. Scene linear is *not* a space. Scene referred data is stored linearly, but it is merely an *attribute* of a full colour space. ACES, 709/sRGB, Arri, Sony, etc. all use different primaries for the basis lights, and as such, there is no such thing as a singular scene referred space.

I would encourage all developers to read the Cinematic Color PDF, and use the terms within for clarity and communication. It is endorsed by the Visual Effects Society.

**Comment by devernay** [comment]
Sorry, but Porter & Duff predate all the things you are talking about. We implement the Porter & Duff compositing operators

**Comment by devernay** [comment]
I don't mean to be harsh, but this is a space: https://en.wikipedia.org/wiki/Space_(mathematics)

scene linear the space defined in OCIO as having the scene_linear role

Now, let's close this useless discussion

**Comment by sobotka** [comment]
Porter and Duff's paper doesn't cover blend modes such as screen last I looked. That is Adobe PDF spec. But alas, perhaps there is a better forum for this discussion?

**Comment by devernay** [comment]
really, what's your point?

**Comment by sobotka** [comment]
Uh... That the blend modes won't work for 99.5% of footage from Arri, Sony, RED etc?

**Comment by CameraRick** [comment]
>Porter and Duff's paper doesn't cover blend modes such as screen last I looked

A screen is nothing more than two inverted souces multiplied together and then inverted again, what's there to cover? :o

**Comment by sobotka** [comment]
Nuke, OIIO, and other imaging tools dealing with scene referred imagery assume scene referred by default I believe. Nuke for example, will assume scene referred *unless* the inappropriately labeled "Video Colorspace" radio box is checked.

Scene referred is zero to infinity, so no such simple assumption of inversion applies.

Scene referred imagery covers every camera in Natron's design scope I believe, as well as every piece of CGI out of a raytracer.

Trying to composite even two renders out of Cycles would lead to broken imagery in the event any of those blend modes are applied, and as such, I was curious about the code path.
