### ISSUE TITLE
RotoPaint- Crashes Natron - minor issue

### ISSUE THREAD

**Issue by blackearth2014** [MrKepzie/Natron#992]
I was needing to clone a tree branch and other parts of a tree. When I'd selected the clone tool, I have forgotten to switch the source color from background to foreground. I had barely made one stroke before it crashed.

Can we get a safety backup implementation that detects if there is a connection on the other inputs. If there is only one input active when the Clone Tool is selected, can the Source Color auto change to foreground?

**Comment by MrKepzie** [comment]
I fail to reproduce this crash, besides I'm not sure foreground is what you want by default when cloning.

**Comment by blackearth2014** [comment]
Okay!! I had any problems since this post with the later snapshots. I am closing.
