### ISSUE TITLE
transform handle in roto's transform tab ?

### ISSUE THREAD

**Issue by mathiastesar** [MrKepzie/Natron#994]
I wondered if there is any transform handle (like from the transform node) in roto's transform tab.
it could be very useful to move layers of bezier curves. Does it exists ?

**Comment by MrKepzie** [comment]
Implemented in https://github.com/MrKepzie/Natron/commit/c759e0ebf3f4ca57ae0c8452680990561f37dc1b

**Comment by manuelsongokuh** [comment]
FINALLY!!!!! I NEED THIS TRUE!!! I WAS FORGET TO ISSUE AND THANK YOU!!!
:+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1:
